### ISSUE TITLE
Need a dedicated document for Alluxio upgrade procedure

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#10002]
**Page**
Now we only have [Upgrade from 1.x to 2.x](https://docs.alluxio.io/ee/user/stable/en/operation/2.x-Upgrade.html?q=upgrade)

**Summary**
There are a few reasons why we are needing this more. Since we are looking towards v2.1, this document page suffice less and less. Also with more users trying to move to use Alluxio in containerized environments like docker and K8s, upgrade become easier and mostly automated. It natural that more people will ask about it.

We need to be explicit about at least few points:

* What are backward compatible and what needs to be formatted in order to upgrade successfully. For example, do users have to format their journal and Alluxio worker storage? This can be a big factor whether they choose to upgrade.

* What is the correct order to turn off the Alluxio service components, and start them once the upgrade is complete?

* Is rolling update possible? For production environments this can be critical. If possible how should the update be performed and validated at each step?

* How to handle anomalies in the procedure of an update? For example, if journal on one master is corrupted, is it possible to recover?

**Comment by jja725** [comment]
This is necessary since rolling upgrade is not possible right now @Xenorith

**Comment by jiacheliu3** [comment]
Addressed by https://docs.alluxio.io/os/user/stable/en/administration/Upgrade.html
