### ISSUE TITLE
Avoid persisting staging files

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#10008]
**Alluxio Version:**
2.0

**Describe the bug**
Hive creates temp directories like
`<table_location>/.hive-staging_hive_<date>_<time>-xx/-ext-xxxxx`.
Currently, with Async through write mode, Alluxio will still persist files like this.

**To Reproduce**
Running lower Hive versions like 1.2

**Expected behavior**
These are files not expected to persist. Having them persist will cause issues
as the persist jobs may conflict with final rename as the commit

**Urgency**
High

**Additional context**

**Comment by calvinjia** [comment]
@apc999 Is this solved by #10111 ?

**Comment by apc999** [comment]
Close this PR as it is solved by #10111
