### ISSUE TITLE
heartbeat bug

### ISSUE THREAD

**Issue by yoock** [Alluxio/alluxio#10005]
**Alluxio Version:**
2.0.1

**Describe the bug**
When the number of files reaches 200,000, the heartbeat data is too much, leading to frequent master GC

**Comment by ZacBlanco** [comment]
Hi @yoock, you'll need to describe this in more detail.

- Can you more clearly define the set of operations and the time frame which they occur?
- Do you know which heartbeat is causing the GC?

**Comment by bf8086** [comment]
Closing this issue as it is no longer active. Please update and reopen the issue if you have more information.

**Comment by yoock** [comment]
alluxio.worker.block.heartbeat.interval




------------------ 原始邮件 ------------------
发件人: "Zac Blanco"<notifications@github.com>; 
发送时间: 2019年10月1日(星期二) 凌晨1:18
收件人: "Alluxio/alluxio"<alluxio@noreply.github.com>; 
抄送: "wlong"<869372753@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Alluxio/alluxio] heartbeat bug (#10005)




Hi @yoock, you'll need to describe this in more detail.
  
Can you more clearly define the set of operations and the time frame which they occur?
 
Do you know which heartbeat is causing the GC?

**Comment by yoock** [comment]
the trouble heartbeat Controlled by alluxio.worker.block.heartbeat.interval
