### ISSUE TITLE
Merge helm chart b/w directories helm-chart and helm

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#10011]
**Is your feature request related to a problem? Please describe.**
We have 2 directories for helm which are out of sync after https://github.com/Alluxio/alluxio/pull/9933.

**Describe the solution you'd like**
We should merge the features supported in both and have a single helm chart

**Describe alternatives you've considered**
N/A

**Urgency**
Urgent

**Additional context**
Community contributed helm chart has diverged from the helm chart in the official Alluxio repo.

**Comment by madanadit** [comment]
@cheyang created the issue to track this

**Comment by madanadit** [comment]
The directory `integration/kubernetes/helm` and `integration/kubernetes/helm-chart` have diverged.

Changes from the following PRs in the directory `integration/kubernetes/helm` need to merged into the new modularized helm template structure in `integration/kubernetes/helm-chart`:
- HA including Embedded Journal: https://github.com/Alluxio/alluxio/pull/9832
- Generation of pre-defined deployment YAMLs from the helm templates: https://github.com/Alluxio/alluxio/pull/9898
- Dedicate alluxio-format job: https://github.com/Alluxio/alluxio/pull/10003
- Run as non-root user: https://github.com/Alluxio/alluxio/pull/9966
- Misc fixes: https://github.com/Alluxio/alluxio/pull/9961, https://github.com/Alluxio/alluxio/pull/10030, https://github.com/Alluxio/alluxio/pull/10039

**Comment by cheyang** [comment]
Thanks @jiacheliu3 , I will also help review.
