### ISSUE TITLE
Proactively remove deleted inodes from LockPool

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#10022]
**Is your feature request related to a problem? Please describe.**
Currently lock-pool evicts based on watermark levels. Which means locks for potentially removed inodes would remain in the pool until eviction is triggered due to capacity. 

**Describe the solution you'd like**
Set a tombstone in lock-pools when an inode is removed/renamed.
Then periodically remove tombstoned entries from the lock-pool.

Since high entry count in the map decreases throughput, we would consider more aggressive eviction as well, like removing a lock as soon as its ref-count reaches 0.

**Additional context**
Recent investigations have shown that high item count in this map is associated with high cpu overhead. In a bulk-delete scenario we possibly want lock-pool to reflect that by removing locks that belong to a removed inodes.

**Comment by yuzhu** [comment]
@ggezer I remember a discussion with you about this topic, has this been addressed?
