### ISSUE TITLE
Why the same tiered layer data are not loaded in order

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10031]
**Alluxio Version:**
2.1.0-snapshot

**Describe the bug**
I put all the data in the same tiered layer:
```
-Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.alias=MEM -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=MEM,SSD -Dalluxio.worker.tieredstore.level0.dirs.path=/dev/shm,/var/lib/docker/alluxio-ssd -Dalluxio.worker.tieredstore.level0.dirs.quota=40GB,50GB -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95 -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7
```
My assumption is that all the data will be put into MEM layer `/dev/shm`, then SSD `/var/lib/docker/alluxio-ssd`

But during  loading the data, I've found it looks `/dev/shm` and `/var/lib/docker/alluxio-ssd` are loaded at the same time.

```
[root@iZhp3b4qysu7phen3sah9sZ shm]# du -sh /var/lib/docker/alluxio-ssd/
18G	/var/lib/docker/alluxio-ssd/
[root@iZhp3b4qysu7phen3sah9sZ shm]# du -sh /dev/shm/alluxioworker/
7.7G	/dev/shm/alluxioworker/
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by bf8086** [comment]
hey @cheyang, Alluxio uses a block allocator to determine where a block should go. The block allocator is specified by property `alluxio.worker.allocator.class` and the default value is `alluxio.worker.block.allocator.MaxFreeAllocator` which will write data to the storage location with most free space. You can try using `alluxio.worker.block.allocator.GreedyAllocator` to write blocks to the first available tier with enough space.

**Comment by rastogiasr** [comment]
This is not a defect, will close the issue unless some other information is provided.

**Comment by cheyang** [comment]
Thank you! Got it.
