### ISSUE TITLE
Improve error message when passing wrong args to CLI

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#10032]
**Alluxio Version:**
2.0.1

**Describe the bug**
```console
$ bin/alluxio fs mount --readOnly /input s3://apc999/emr/mid_input_alluxio_alluxio
Usage: mount [--readonly] [--shared] [--option <key=val>] <alluxioPath> <ufsURI>
Mounts a UFS path onto an Alluxio path.
```

**To Reproduce**
Above

**Expected behavior**

The console output should say the `--readOnly` is unrecognized before showing the usage.
 
**Urgency**
Low

**Additional context**

**Comment by yangjf2019** [comment]
Hi, @apc999 Does this mean that we need to output a reminder? For example, don't know this command. Thanks :)

**Comment by yangjf2019** [comment]
or `--readOnly is an unknown command.`

**Comment by apc999** [comment]
@yangjf2019  yes, something like 
```
Unrecognized option "--readOnly".
Usage: mount [--readonly] [--shared] [--option <key=val>] <alluxioPath> <ufsURI>
Mounts a UFS path onto an Alluxio path.
```

**Comment by yangjf2019** [comment]
I'm not sure if I want to modify this file in this directory. Can you confirm it? Thank you!
`Java class: alluxio.cli.fs.command.MountCommand`
`Directory: alluxio/shell/src/main/java/alluxio/cli/fs/command`
Do we need to modify the `run(CommandLine cl)`  method of the MountCommand class?

**Comment by yangjf2019** [comment]
My code as follows:
` String cmd = stripLeadingHyphens(args[1]);`
`  if (!READONLY_OPTION.getLongOpt().equals(cmd) ||!SHARED_OPTION.getLongOpt().equals(cmd) || !OPTION_OPTION.getLongOpt().equals(cmd)) {`
     ` // Unrecognized option (we didn't find the option in our dict)`
     ` System.out.println(String.format("Unrecognized option \"%s\".", cmd));`
     ` return -1;`
   ` }`

**Comment by yangjf2019** [comment]
Thank you :)

**Comment by apc999** [comment]
@yangjf2019 thanks for your input. Here we want to actually have a more general solution. Instead of working with `MountCommand` alone, how about adding the following line before [here](https://github.com/Alluxio/alluxio/blob/c19798b11e5592636ee1beb5f53788832ae764e8/core/common/src/main/java/alluxio/cli/AbstractShell.java#L125)
```
System.out.println(e.getMessage());
```

In this way, wrong argument will be shown 
```console
$ bin/alluxio fs mount --readOnly  /mnt s3://alluxio-quick-start/data
Failed to parse args for mount: Unrecognized option: --readOnly
Usage: mount [--readonly] [--shared] [--option <key=val>] <alluxioPath> <ufsURI>
Mounts a UFS path onto an Alluxio path.
```

**Comment by yangjf2019** [comment]
@apc999  Thanks for your helping. I will modify the bug ,and when it  test passed, I will open  a new PR.

**Comment by yangjf2019** [comment]
The error message has Found  in the directory (`alluxio/alluxio-2.0.0/logs/user/user_pro.log`),
and when we use this code `System.out.println(e.getMessage());` , error messages will show on the CLI.

**Comment by yangjf2019** [comment]
Hi, @apc999  Here you can find the [PR](https://github.com/Alluxio/alluxio/pull/10077), Please take a look ,Thank you very much.
