### ISSUE TITLE
Filter and refine listStatus results

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#10038]
**Is your feature request related to a problem? Please describe.**
ListStatus returns so much information many of which are not utilized at client side.

**Describe the solution you'd like**
A new filter based listStatus API through which caller can control what files are of interest, and what categories of information to return per item. So that clients can run intelligent queries with lower master-side overhead.

**Describe alternatives you've considered**
Segmenting the existing FileInfo type into several sections and explicitly requesting each segment to be populated.

**Additional context**
For example, UfsPath and MountId fields that are UFS level information, requires resolving against the mount table and are only used in limited context. They are calculated and sent back for every listStatus request regardless.

**Comment by yuzhu** [comment]
@ggezer are there follow up PRs to #10006 or can this issue be closed now?

**Comment by ggezer** [comment]
#10006 is closed in order to get a proper fix as mentioned in this issue. We'd ideally want to get this done at some point in order to reduce listStatus overhead.

**Comment by ggezer** [comment]
Another use case to justify this feature: https://github.com/Alluxio/alluxio/issues/13278

**Comment by jja725** [comment]
Will close it for now since we have batch list status and we can filter on the caller side, feel free to reopen it and contact us if this is a strong request.
