### ISSUE TITLE
EMR script does not work in all regions

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#10047]
**Alluxio Version:**
2.0.1

**Describe the bug**
Launch an EMT cluster in region us-west-1, the hostname fqdn is `<>..us-west-1.compute.internal` which breaks our EMR script which assumes `<>.ec2.internal`

**To Reproduce**
^

**Expected behavior**
N/A

**Urgency**
Medium

**Additional context**
N/A

**Comment by ns1123** [comment]
I wish AWS didn't have these silly exceptions for different regions...
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html

**Comment by yuzhu** [comment]
@ZacBlanco what is the status on this?

**Comment by ns1123** [comment]
This has been resolved.
https://github.com/TachyonNexus/golluxio/pull/2023
