### ISSUE TITLE
Enable Alluxio to run with Java v1.9+

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#10042]
**Is your feature request related to a problem? Please describe.**
In `libexec/alluxio-config.sh` seems we define Alluxio to only support Java v1.8.
```
# Check Java version == 1.8
JAVA_VERSION=$(${JAVA} -version 2>&1 | awk -F '"' '/version/ {print $2}')
if [[ $(echo "${JAVA_VERSION}" | awk -F. '{printf("%03d%03d",$1,$2);}') != 001008 ]]; then
  echo "Error: Alluxio requires Java 8, currently Java $JAVA_VERSION found."
  exit 1
fi
```

**Describe the solution you'd like**
Java version v1.9+ are backward compatible so Alluxio should support those too.

**Urgency**
Low. 

**Additional context**
NA

**Comment by ZacBlanco** [comment]
@jiacheliu3 is there a reason you want to support java 9? Java 9 is not an LTS release and from my knowledge is no longer supported by OpenJDK. The next LTS after Java 8 is Java 11. There is already a ticket for supporting Java 11 in #9856

**Comment by jiacheliu3** [comment]
@ZacBlanco I don't really have a use case. I'm just curious why only v1.8 is specified in the script and thought generally it's a good idea not to ignore the new versions. So I created this issue in case the hardcoded version is a potential bug.

Now the reason why Alluxio stays with v1.8 makes sense to me. This is a duplicate issue to #9856 so I will close this one. Thanks for the explanation.
