### ISSUE TITLE
Allow backups on any file system

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#10066]
**Is your feature request related to a problem? Please describe.**
Currently backup path should either be in root-ufs or local. This means if your backup resides anywhere else, you should first make a copy.

**Describe the solution you'd like**
Allow reading/writing backups from arbitrary file system schemes.

**Additional context**
https://github.com/Alluxio/alluxio/pull/10046

**Comment by ggezer** [comment]
@ns1123 WDYT?

**Comment by ns1123** [comment]
The easy fix for this is to mount the UFS that you want to configure to take backups to. Is there a scenario where this wouldn't be needed?

**Comment by ggezer** [comment]
Is there a reason why we currently restrict backups to root&local ufs?

**Comment by yuzhu** [comment]
@ggezer  do we plan to address this in the upcoming release?

**Comment by ns1123** [comment]
I think this can be closed. Backup related issues have mostly been addressed. Scenarios with backing up to a different storage system haven't been requested.

**Comment by yuzhu** [comment]
Closing this as discussed.

**Comment by ggezer** [comment]
This restriction is too inconvenient

**Comment by jja725** [comment]
@jenoudet do you think this is still a valid request? otherwise I would close this, thanks

**Comment by jenoudet** [comment]
@jja725 It's a valid request but definitely not a priority.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
