### ISSUE TITLE
Use protobuf for JobConfig

### ISSUE THREAD

**Issue by ghost** [Alluxio/alluxio#10135]
**Summary**
Currently, `JobConfig` implements `java.io.Serializable`, every time when creating a new `JobConfig`, if it contains nested objects, we need to make sure those objects are serializable too, without writing unit tests for each JobConfig, we won't be sure whether the serialization and deserialization work.
Also, if we need to update existing `JobConfig`, using protobuf is easier to maintain backward compatibility.

**Comment by yuzhu** [comment]
@bradyoo has this been addressed with your recent improvement to the job service?

**Comment by bradyoo** [comment]
No. Probably no plan to in any reasonable future.
