### ISSUE TITLE
Provide an entry shell script for LocalAlluxioCluster to let user use single process mode alluxio

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#10165]
**Is your feature request related to a problem? Please describe.**
For the more and more popular alluxio is, we want to use alluxio as a single process tiny mode to manage the single node tier storages, like hdd, ramdis, ssd.

**Describe the solution you'd like**

A tiny version, no more complex components, just a process, it just manage the file in the tier well, and provide the filesystem api for application.

**Describe alternatives you've considered**

after overlook the alluxio source, i find LocalAlluxioCluster is a way to run master and worker in a process for the test purpose, and it maybe satisfy my demand.

**Urgency**

As this little change can make zero to one, it worth to do it quickly.

**Additional context**

If we can make it more tiny, it will be better. BTW, in fact, we should have a way to make all of our component as a cut able, so that alluxio can adapt more situation.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
