### ISSUE TITLE
Make Alluxio inode meta data management as a optional configure

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#10166]
**Is your feature request related to a problem? Please describe.**
If fact, i know some of company use alluxio because its fs translate api and mount point management, it shows a unite global namesystem, they neither need alluxio cache the inode meta, nor the block cache, if we can make the metadata management optional, it can help alluxio to be used for them.

**Describe the solution you'd like**

Create a option to close the inode management.

**Describe alternatives you've considered**

Create a option to close the inode management.

**Urgency**

Normal

**Additional context**

Make anything cut-able  if it can, split alluxio as small, small clip can make more results.

**Comment by jja725** [comment]
Would consider during redesign. Will close it for now, feel free to reopen it and contact us if this is a strong request.
