### ISSUE TITLE
Support cancelling job-service based CLIs

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#10170]
**Is your feature request related to a problem? Please describe.**
Users often type the wrong arguments in CLI, then they want to cancel the CLI and re-run the CLI with the correct arguments. Currently, if the Alluxio CLI is based on job-service (e.g., distributedLoad, distributedCp, distributedMove, persist), it will simply submit the job. Quitting from this running CLI will not result in the stop of the job.

**Describe the solution you'd like**
When users cancel a running CLI which is based on job service, we should support cancel the job.

**Describe alternatives you've considered**

**Urgency**
High

**Additional context**

**Comment by calvinjia** [comment]
This issue has been addressed.
