### ISSUE TITLE
copy to a folder while dest path is endsWith a `/`

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#10191]
**Alluxio Version:**

master

**Describe the bug**

Not sure whether we should honor posix fs, if so, we should output error for this case.

**To Reproduce**

```bash
✗ bin/alluxio fs copyFromLocal /tmp/bug.log alluxio://192.168.31.120:19998/abc/ 
Copied file:///tmp/bug.log to alluxio://192.168.31.120:19998/abc
```

**Expected behavior**

it should output `cp: directory alluxio://192.168.31.120:19998/abc/  does not exist`

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by yuzhu** [comment]
@maobaolong  issue reproduced. will fix

**Comment by maobaolong** [comment]
@yuzhu How about the status of this issue?
