### ISSUE TITLE
 helm install --name alluxio -f config.yaml  alluxio --version 2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by SeeMyWorld** [Alluxio/alluxio#10216]
Alluxio Version: master

Describe : When I carry out the command,(helm install --name alluxio -f config.yaml  alluxio --version 2.1.0-SNAPSHOT),I don't know why this mistake happened:`Error: configmaps "alluxio-config" is forbidden: User "system:serviceaccount:kube-system:default" cannot delete resource "configmaps" in API group "" in the namespace "default"
`

**Comment by ZacBlanco** [comment]
Have you followed the instructions in the `edge` documentation for deploying k8s with helm?

https://docs.alluxio.io/os/user/edge/en/deploy/Running-Alluxio-On-Kubernetes.html#deploy-using-helm

**Comment by SeeMyWorld** [comment]
yes ,Now the state of my node is Pending,The reason for the error is (  message: '0/5 nodes are available: 1 Insufficient memory, 5 Insufficient cpu.')

**Comment by ZacBlanco** [comment]
I am closing this issue as it seems you've solved the original problem. Please re-open if you still have issues.
