### ISSUE TITLE
Remove the restriction that tier 0 alias has to be "MEM"

### ISSUE THREAD

**Issue by yuzhu** [Alluxio/alluxio#10229]
**Summary**
There are some assumptions about our tier 0 alias being "MEM", we should not rely on that..

**Urgency**
not urgent

**Comment by ZacBlanco** [comment]
@yuzhu can you provide a list of places that have the assumption? It doesn't have to be exhaustive, but a small set of references can help.

**Comment by yuzhu** [comment]
I found the following by greping for "MEM"
```
core/server/common/src/main/java/alluxio/cli/validation/RamDiskMountPrivilegeValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/StorageSpaceValidationTask.java
core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java
shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java
```

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
