### ISSUE TITLE
Remove logging jars from uber jar in alluxio-client

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#10224]
**Alluxio Version:**
1.8.x

**Describe the bug**
Logging jars in the client should be removed/shaded.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Urgency**
High

**Comment by ZacBlanco** [comment]
removing is different from shading - which one do we want, and why does it need to be done (please add information to the issue description)

**Comment by calvinjia** [comment]
This issue has been addressed.
