### ISSUE TITLE
Add docs to K8s/helm for tiered storage and fuse

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#10241]
**Page**
https://docs.alluxio.io/os/user/edge/en/deploy/Running-Alluxio-On-Kubernetes.html

**Summary**
The K8s deployment instructions is missing documentation for:
- Configuring tiered storage w/ helm chart
- Deploying the fuse daemonset using the helm chart

The ask for this issue is to 
1. create an "Example: Tiered Storage" under the section https://docs.alluxio.io/os/user/edge/en/deploy/Running-Alluxio-On-Kubernetes.html#configuration
2. Split the section https://docs.alluxio.io/os/user/edge/en/deploy/Running-Alluxio-On-Kubernetes.html#posix-api into 2 sub-sections "Using helm" and "Using kubectl"

**Comment by madanadit** [comment]
@cheyang Please take a look. Thank you!

**Comment by cheyang** [comment]
@madanadit  #10237 addresses `Configuring tiered storage w/ helm chart`, do you think if it's ok?

I will take a look at `fuse doc` later.

**Comment by madanadit** [comment]
Thanks, tiered store documentation looks good.

**Comment by madanadit** [comment]
@cheyang would you be able to add docs for deploying the fuse daemons w/ helm? thx

**Comment by LuQQiu** [comment]
POSIX API related K8S/Helm doc are added.
@ssz1997 Please help confirm

**Comment by LuQQiu** [comment]
This issue is resolved, thanks for confirmation from @ssz1997
