### ISSUE TITLE
Add a `TIER_DOWNGRADE` TTL Action

### ISSUE THREAD

**Issue by rblaine95** [Alluxio/alluxio#10248]
**Is your feature request related to a problem? Please describe.**
Currently when you set `alluxio.user.file.create.ttl`, the only options you have with `alluxio.user.file.create.ttl.action` is `FREE` (remove from Alluxio entirely) or `DELETE` (remove from Alluxio **_and_** UFS)

**Describe the solution you'd like**
It'd be really useful to add a third option to `alluxio.user.file.create.ttl.action`, that being something along the lines of `TIER_DOWNGRADE` which would move stale data down the storage tiers until there are no more tiers to downgrade it by, maybe at which point the file is removed from Alluxio, or both Alluxio and UFS.

For example:
`wine_quality.csv` is currently in T0 (`MEM`)
One hour passes, the TTL on `wine_quality.csv` has gone stale.
Alluxio Master starts the `ttl.checker` and finds `wine_quality.csv` has gone stale.
`ttl.checker` moves `wine_quality.csv` from T0 (`MEM`) to T1 (`SSD`)
Another hour passes and `wine_quality.csv` still hasn't been touched.
`ttl.checker` then moves it from T1 (`SSD`) to T2 (`HDD`)
This continues until `wine_quality.csv` is at Tn, the final tier of storage in the Alluxio cluster
`ttl.checker` then executes the `FREE` `ttl.action` and removes the file from Alluxio

This would mean that space is preemptively freed from higher tiers (T0, for example) which means that Alluxio Workers will not have to swap blocks while the cluster is probably under load.

**Describe alternatives you've considered**
There are no alternatives.

**Urgency**
Not very urgent, would be a nice feature to have.

**Comment by rblaine95** [comment]
It might be a good addition to have tier-specific TTL
For example:
T0 has a block ttl of 1 hour
T1 has a block ttl of 2 days
T2 has a block ttl of 1 week

**Comment by calvinjia** [comment]
Thanks for bringing up this optimization. We are moving more toward a black box approach to alluxio storage, so we will not provide APIs to users for fine control over multiple cache tiers. However there will be internal logic to move data between tiers pre-emptively, similar to what you are suggesting.
