### ISSUE TITLE
Can we use 1 master statefulset  to replace 3 ?

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10316]
**Alluxio Version:**
2.1.0

**Describe the bug**
I notice if there are 3 alluxio masters,  we have to create 3 statefulsets. It looks odd. Can we enhance it? Can we use 1 statefulset with 3 replicas to deploy it?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Urgency**
N/A

**Additional context**
Using a single stateful set will improve maintainability.

**Comment by cheyang** [comment]
I think we can leverage to attach different services to the same statefulset https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-name-label.

**Comment by jiacheliu3** [comment]
I think we can use 1 StatefulSet with multiple replicas for multiple Alluxio masters. We are planning to do this actually, and use volumeClaimTemplates to make the PVC be created and managed automatically. This doesn't have a concrete ETA yet but is definitely the way to go in the near future.

**Comment by calvinjia** [comment]
@jiacheliu3 Has this issue been addressed in master?

**Comment by jiacheliu3** [comment]
Closed as this has been addressed in https://github.com/Alluxio/alluxio/pull/10686
