### ISSUE TITLE
Alluxio JAVA_OPTS should not be required to end w/ a space

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#10341]
**Alluxio Version:**
2.1.0-SNAPSHOT

**Describe the bug**
Java options are appended to common options `ALLUXIO_WORKER_JAVA_OPTS+=${ALLUXIO_JAVA_OPTS}`

When not ending/beginning with a space, properties are not handled correctly

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
K8s specific workaround: https://github.com/Alluxio/alluxio/pull/10337

**Comment by apc999** [comment]
@madanadit has https://github.com/Alluxio/alluxio/pull/10337 fixed this issue? If yes, I will close it .

**Comment by ns1123** [comment]
@madanadit is this something that a lot of users are going to be impacted by? How obvious is it that the missing spaces is the root of the problem?

**Comment by madanadit** [comment]
It is not necessarily obvious, I would guess a significant number of users can run into this
