### ISSUE TITLE
Warning on failed dir deletion after running a Spark job

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#10365]
**Alluxio Version:**
2.2.0-SNAPSHOT

**Describe the bug**
Running Spark with Alluxio (with default conf)
A warning like "19/10/30 13:34:26 WARN hadoop.AbstractFileSystem: delete failed: Path "/cache/.spark-staging-2" does not exist." is always shown:

```console
scala> val sampleRdd = sc.textFile("file:///tmp/sample-100m")
sampleRdd: org.apache.spark.rdd.RDD[String] = file:///tmp/sample-100m MapPartitionsRDD[1] at textFile at <console>:24

scala> sampleRdd.saveAsTextFile("alluxio://localhost:19998/cache")
19/10/30 13:34:26 WARN hadoop.AbstractFileSystem: delete failed: Path "/cache/.spark-staging-2" does not exist.
```

**To Reproduce**
See above

**Expected behavior**
No such a warning

**Urgency**
Low

**Additional context**

**Comment by ChernikovP** [comment]
This is still an issue in `2.2.1`. Any ideas what causing this and whether it could really affect what's written?

**Comment by apc999** [comment]
@ChernikovP this is due to a noisy logging message in Alluxio hadoop compatible client.
Fixed in https://github.com/Alluxio/alluxio/pull/14857 by @ljl1988com
