### ISSUE TITLE
Terminate ZK client connection from Alluxio Client after acquiring the leader hostname

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#10376]
**Is your feature request related to a problem? Please describe.**
Currently, the Alluxio client holds the connection to Zookeeper for the entire duration that it is running even though the master hostname is requested once and cached. This results in overloading of the Zookeeper service.

**Describe the solution you'd like**
Alluxio Clients, once they have acquired and cached the leader hostname, should close their connection to Zookeeper.

**Describe alternatives you've considered**
N/A.

**Urgency**
Overloading Zookeeper, especially during backups where clients all hang because they're blocked waiting for the master.

**Additional context**
N/A

**Comment by madanadit** [comment]
@ggezer @ns1123 please comment if the relevancy of this issue has changed

**Comment by ns1123** [comment]
Can close this for now. ZK was overloaded for different reasons.
