### ISSUE TITLE
shell command "test " cannot differentiate exception and "false" result

### ISSUE THREAD

**Issue by wanwe** [Alluxio/alluxio#10385]
sample command: "test -f some_existing_file"
Problem:
in case of exception, this command returns code=1, implying this is NOT a file, which is not the fact.

[TestCommand.java](https://github.com/Alluxio/alluxio/blob/9dea2a67cad376d32b2d2409e08e9280770b27b3/shell/src/main/java/alluxio/cli/fs/command/TestCommand.java#L165)

proposal:
in case of exception, can we output the exception together with return code=1?
so that we could retry if "exception" is detected in command line output.

**Comment by ZacBlanco** [comment]
@wanwe Sorry for the late reply. I agree that the current behavior is not ideal.

How about we improve the command to more closely adhere to the POSIX standard, as well as what we find in most common systems today: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html

I would suggest that we simply return >1 on errors, and 1 when the file doesn't exist.

**Comment by wanwe** [comment]
@ZacBlanco sounds good !

Thanks,
Wei
