### ISSUE TITLE
Remove requirement to distribute HDFS core-site/hdfs-site to all nodes

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#10381]
**Is your feature request related to a problem? Please describe.**
Deploy an Alluxio cluster using EMR or Dataproc. There is no password-less ssh access b/w nodes w/ a root_ufs != HDFS

At present there is no easy way to mount HDFS as a nested mount point as core-site/hdfs-site needs to be present on all Alluxio server nodes.  

The end-user either needs to redeploy the cluster or manually write a script to scp the files onto all nodes.
 
**Describe the solution you'd like**
HDFS config should only be required on the client node. The master should be able to serialize the contents and distribute the resource to registered workers and other also masters (identified using zkp or embedded addresses).

**Describe alternatives you've considered**
N/A

**Urgency**
Low

**Additional context**
N/A

**Comment by ns1123** [comment]
+1 since it would allow non-root users to mount an HDFS without assistance of the cluster admin

**Comment by yuzhu** [comment]
implemented in #12783
