### ISSUE TITLE
Weird Mac OS mount behavior causes failures

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#10395]
**Alluxio Version:**
Any

**Describe the bug**
In Mac OS (running Alluxio locally), trying to SudoMount on a system where the Ramfs path already exists causes Mac to mount a ramfs at a different location ("$RAMFSPATH 1"). This then results in a worker with 0 space which becomes unusable.

**To Reproduce**
Create /Volumes/ramdisk using a sudo account on a Mac. Then try to start Alluxio. Check UI to see 0 byte space.

Ex:
umount /Volumes/ramdisk
sudo mkdir /Volumes/ramdisk
./bin/alluxio-mount.sh SudoMount

**Expected behavior**
Fails to SudoMount with sysout message explaining that a directory already exists in the ramfs directory and prompting user to delete it before re-running.

**Urgency**
Medium

**Additional context**
Mac's mount command is messed up

**Comment by ns1123** [comment]
@yuzhu @tieujason330 FYI

**Comment by ZacBlanco** [comment]
@ns1123 can you provide a more concrete set of steps "To Reproduce"? i.e.  a set of bash commands?

**Comment by ns1123** [comment]
@ZacBlanco done

**Comment by jja725** [comment]
@ns1123 Hi, is this still valid in the recent version?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
