### ISSUE TITLE
LockPoolTest flakey

### ISSUE THREAD

**Issue by yuzhu** [Alluxio/alluxio#10390]
**Summary**
LockPoolTest often fails with the following error, there is probably a concurrency bug.
```
Failed tests:  alluxio.collections.LockPoolTest.parallelInsertTest(alluxio.collections.LockPoolTest)  

Run 1: LockPoolTest.parallelInsertTest:117 expected:<16> but was:<15>   
Run 2: LockPoolTest.parallelInsertTest:117 expected:<16> but was:<15>```

**Urgency**
Explain why it is important to address the tech debt

**Comment by ns1123** [comment]
@yuzhu is this still an issue? Are you/anyone else looking into this?

**Comment by yuzhu** [comment]
I don't think anyone has looked at this yet. so this is probably still an issue

**Comment by madanadit** [comment]
@yuzhu is this still an issue?

**Comment by yuzhu** [comment]
@madanadit I have not seen this error in a while, so maybe we can close it for now.
