### ISSUE TITLE
Swap FindBugs plugin with SpotBugs

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#10406]
**Summary**

The original codehaus FindBugs plugin is deprecated and no longer under active maintenance - https://gleclaire.github.io/findbugs-maven-plugin/

The successor to findbugs is SpotBugs - https://spotbugs.github.io/ It contains more checks for poor patterns throughout the codebase and is actively maintained.

We should use the newer plugin. I made a small attempt at switching, and spotbugs has found nearly 200 issues which findbugs didn't. We should switch to this ASAP.

**Urgency**

Help reduce common bugs across our code base.

**Comment by yuzhu** [comment]
@ZacBlanco could you open a PR with SpotBugs? so that we can track what kind of issues are discovered by SpotBugs?

**Comment by ZacBlanco** [comment]
Done - https://github.com/Alluxio/alluxio/pull/10407

**Comment by ZacBlanco** [comment]
Also, I noticed my original change didn't properly use the old findbugs exclusion file, so some extra errors were caught (that's why is showed nearly 200). After using the exclusion though there were still  a few errors that showed up.

 We might want to re-visit the list of exclusions because there was a number of errors that the plugin reported up which, based on the description seemed somewhat severe
