### ISSUE TITLE
Need Alluxio metrics support Prometheus

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10409]
**Is your feature request related to a problem? Please describe.**
Prometheus is most common monitoring system in Kubernetes. It would be great if the users  monitoring the Alluxio system with other systems or components(TiDB, mysqls, nginx) in Kubernetes to  so I don’t need to log into allxuio master.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by ZacBlanco** [comment]
Have you tried using the endpoint at `http://<alluxio master>:19998/metrics/json` and having prometheus scrape it for metrics?

**Comment by ZacBlanco** [comment]
@cheyang were you able to get it to work with that endpoint?

**Comment by ns1123** [comment]
@cheyang there's a prometheus Metrics Sink provided. Please see the link below:
https://docs.alluxio.io/os/user/stable/en/operation/Metrics-System.html?q=metrics

**Comment by rastogiasr** [comment]
Closing the issue, hopefully the docs help.
