### ISSUE TITLE
Timeout for calls to external systems

### ISSUE THREAD

**Issue by yuzhu** [Alluxio/alluxio#10426]
**Summary**
Currently, we make blocking calls to external systems for information. All these calls should have proper timeout values and recovery mechanisms. We should not be impacted negatively if one of these services are down or have significant service degradations.  

Just as importantly, proper logging should enable fast diagnosis of such problems

External systems include:
UFS
Security Plugins (BlueTalon etc)
Anything else? 

**Urgency**
It is important for the reliability of our system..

**Comment by yuzhu** [comment]
@gpang @ns1123

**Comment by yuzhu** [comment]
@ggezer https://grpc.io/blog/a_short_introduction_to_channelz/
do you think we should enable this? how much overhead would there be?

**Comment by ggezer** [comment]
It's an internal metrics system or gRPC and we'd need a code change to enable it. I'd imagine it would become a bottleneck in high traffic scenarios but can't say before trying. I don't see much value in tracking the gRPC internals as our use of gRPC makes it easy to deduce much of the information through our own metrics.

**Comment by ns1123** [comment]
+1 for this change. What is the behavior expected if a call blocks too long? For example, if the Ranger plugin takes too long to respond, does the Master fallback to it's own internal permission model? Or do we just return some sort of ModuleTimeoutException?

**Comment by jja725** [comment]
Will close it for now, and take it into consideration during redesign
