### ISSUE TITLE
Helm doc version should be updated in branch-2.1 after release > 2.1

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#10422]
**Page**
https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html

**Summary**
As of now the documentation in the linked page points to the helm chart version included in the released 2.1 docker image (=0.5.1). However branch-2.1 was updated to helm 0.5.2 (https://github.com/Alluxio/alluxio/pull/10384/files). As docs for the released 2.1 are generated off branch-2.1 we have not updated the helm documentation version in the branch but only in master (https://github.com/Alluxio/alluxio/pull/10405#event-2768885278).

This is a workaround till the time we have documentation at patch release granularity.

**Comment by ns1123** [comment]
@madanadit can this be marked as done?

**Comment by madanadit** [comment]
No
