### ISSUE TITLE
Dataproc initialization action does not create Alluxio cluster (conf/workers)

### ISSUE THREAD

**Issue by roderickyao** [Alluxio/alluxio#10438]
Alluxio Version: 2.1.0

The Dataproc initialization action does not set /opt/alluxio/conf/workers file properly. It only has "localhost" as content. When modified this file, start cluster also fails due to SSH failure because the start command does not handle the request of adding first time connect host to its known host list.

**Comment by madanadit** [comment]
Hi @yhqs540, this is expected behavior. We do not rely on passwordless ssh for startup in dataproc and do not use `conf/workers` or `conf/masters`

**Comment by yhqs540** [comment]
In that case, how to enable cluster mode in Dataproc?

**Comment by rastogiasr** [comment]
@yhqs540 - Currently we are not supporting HA mode. For HA mode to work, there is additional work that needs to be done in the init_action script to figure out the ip/dns for other Alluxio masters. Do you know how many users typically go with HA Cluster mode vs Single Master mode?

**Comment by yuzhu** [comment]
expected behavior
