### ISSUE TITLE
Presto queries get stuck infinitely while accessing files from alluxio.

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#10468]
**Alluxio Version:**
Alluxio v2.1.0

**Describe the bug**
Originally reported from https://alluxio-community.slack.com/archives/CEXGGUBDK/p1573638510393600

we are facing some weird issue while accessing data from Alluxio using presto. Presto queries are getting stuck infinitely while accessing files from alluxio. I checked the thread dumps for presto worker and seems that threads are getting locked while accessing alluxio file. We were facing this issue with Alluxio 2.0.0, we were told that few improvements has done on client side in the latest version so we upgraded to latest version 2.1.0, but still we are getting the same issue. Could someone please help us to resolve this issue? I am adding alluxio worker logs  and presto thread dumps.
Note - This deployment has done using kubernetes on AWS

**To Reproduce**

**Expected behavior**

**Urgency**
High

**Additional context**
Thread dump
[thread_dumps.log](https://github.com/Alluxio/alluxio/files/3842826/thread_dumps.log)
Worker log: 
[alluxio_worker_log.txt](https://github.com/Alluxio/alluxio/files/3842827/alluxio_worker_log.txt)

**Comment by surajc-cuelogic** [comment]
@apc999,
As per discussion on slack I tried by setting **alluxio.user.file.master.client.threads=128** this property but I still getting the same issue. I have captured the thread dumps and attaching here. I hope that will help to debug the issue.
[presto-worker-thread-dump-18-11.txt](https://github.com/Alluxio/alluxio/files/3857872/presto-worker-thread-dump-18-11.txt)

**Comment by surajc-cuelogic** [comment]
Attaching files to understand the alluxio configurations we have on production

[alluxio-env-master.txt](https://github.com/Alluxio/alluxio/files/3858519/alluxio-env-master.txt)
[alluxio-env-worker.txt](https://github.com/Alluxio/alluxio/files/3858520/alluxio-env-worker.txt)

**Comment by apc999** [comment]
@bf8086 can you help take a look?

**Comment by bf8086** [comment]
@surajc-cuelogic thanks for reporting the issue. Do you still have the Alluxio worker log for node `soc-alluxio-worker-5.soc-alluxio-worker` around timestamp `2019-11-13 07:54`?

**Comment by prashantk-cuelogic** [comment]
@bf8086 Thanks for your response. We have saved Alluxio worker logs of soc-alluxio-worker-0.soc.alluxio-worker around timestamp 2019-11-13 07:40 and attached same. Unfortunately we do not have worker logs for soc-alluxio-worker-5.soc-alluxio-worker.
[alluxio_worker_log.txt](https://github.com/Alluxio/alluxio/files/3862093/alluxio_worker_log.txt)

**Comment by bf8086** [comment]
@prashantk-cuelogic do you have master log for around the same time period? How many masters do you have?

Can you also post your Alluxio client side configuration set in presto?

**Comment by prashantk-cuelogic** [comment]
I do not have alluxio msater logs around the same time period. We have 3 alluxio masters running in HA mode(using zookeeper). We are using glusterFs as a journal path for masters.
Please find alluxio client side configuration set in presto:
[config_properties.txt](https://github.com/Alluxio/alluxio/files/3867538/config_properties.txt)

[hive_properties.txt](https://github.com/Alluxio/alluxio/files/3867539/hive_properties.txt)

[core-site-xml.txt](https://github.com/Alluxio/alluxio/files/3867619/core-site-xml.txt)
[hive-site-xml.txt](https://github.com/Alluxio/alluxio/files/3867620/hive-site-xml.txt)

**Comment by bf8086** [comment]
@prashantk-cuelogic is it possible for you to share the query or type of workload running when this issue happen? How many presto workers and alluxio workers are you running? Are they colocated?

**Comment by bf8086** [comment]
From the attached thread dump it looks like the presto worker is reaching maximum number of Alluxio master clients. Can you also attach your presto worker log from the worker which hangs? To get more detailed information, please also turn on Alluxio client debug log by adding a new line `alluxio=DEBUG` to presto log configuration `/etc/presto/log4j.properties`

**Comment by bf8086** [comment]
[presto-worker-logs.log](https://github.com/Alluxio/alluxio/files/3912989/presto-worker-logs.log)
[thread-dumps for same presto worker.log](https://github.com/Alluxio/alluxio/files/3913000/thread-dumps.for.same.presto.worker.log)

**Comment by bf8086** [comment]
@surajc-cuelogic Thanks for the additional logs. I see two issues from the logs/thread dump:
- From the presto worker logs there seems to be a network issue happening around `2019-12-02T12:22` and many network requests including Presto, Kudo and Alluxio worker requests has failed. You might want to investigate the network issue which seems to cause timeout in various places.

- The thread dump indicates that the presto worker is running on OpenJDK 11. Currently Alluxio only support Java JDK 8(see [docs](https://docs.alluxio.io/os/user/stable/en/deploy/Requirements.html) for detail). Higher version of Java is not supported and might lead to unknown issues. Can you try using Java version 8 for your presto service and see if it helps?

**Comment by surajc-cuelogic** [comment]
@apc999 @bf8086 I had discussion with presto team, they are saying JAVA 11 is more performant than Java 8 and in near future they are making Java 11 as minimum requirement for presto. Are we considering moving Alluxio as well to Java 11?

**Comment by apc999** [comment]
@surajc-cuelogic we think this patch https://github.com/Alluxio/alluxio/pull/10719 will fix the issue (this issue looks unrelated to Java version). In the meanwhile, we are working on supporting Java 11 too.

**Comment by surajc-cuelogic** [comment]
Hi Team,
I tried to verify latest alluxio version 2.2.0 with Presto 323 with jdk11. But I am still getting the same issue. Queries are getting stuck for infinite time while fetching data from alluxio-s3. Could some one help me to get this solve?

**Comment by surajc-cuelogic** [comment]
Let me know if I need to create new issue or can we reopen this?

**Comment by ZacBlanco** [comment]
@surajc-cuelogic if you are still seeing your queries hanging it's likely a different issue. Either misconfiguration or some other bug. You can open a new issue where you should attach a `jstack -l <pid>` of the presto workers which are hanging, your `alluxio-site.properties`, and presto configuration
