### ISSUE TITLE
Extend JournalTool to dump Copycat internals

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#10479]
**Is your feature request related to a problem? Please describe.**
For certain cases, a post-mortem on embedded journals will be easier when having access to internal copycat logs.

**Describe the solution you'd like**
An `-advanced` flag that instructs JournalTool to dump copycat internal logs when reading copycat journal directory.

**Additional context**

**Comment by yuzhu** [comment]
not using copyCat anymore, using Ratis
