### ISSUE TITLE
Allow clients to call getWorkerInfoList() without grabbing WorkerInfo locks 

### ISSUE THREAD

**Issue by gpang** [Alluxio/alluxio#10472]
**Is your feature request related to a problem? Please describe.**
When many clients access the master for the list of workers (for reading or writing files), it will grab the locks for all the workers on the master. However, if there are a lot of clients and/or lots of workers, this adds a lot of contention.

Here is the lock:
https://github.com/Alluxio/alluxio/blob/v2.1.0/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java#L410

**Describe the solution you'd like**
Instead of requiring a lock to get the list of workers, the `getWorkerInfoList()` call should be able to generate the list without grabbing locks. This could mean there is a snapshot of the list.

**Describe alternatives you've considered**

**Urgency**
This increases the scalability with many clients and many workers.

**Comment by madanadit** [comment]
@LuQQiu Can you please provide an update on this issue?

**Comment by LuQQiu** [comment]
The synchronization of `getWorkerInfoList` is an issue when the `workerHeartbeat` is slow and holds the worker lock. In PR https://github.com/Alluxio/alluxio/pull/10601 we change `workerHeartbeat` to process metrics async. After this change, the synchronization of `getWorkerInfoList` is not an issue anymore. They are fast and do not hold the worker lock for too long.

**Comment by LuQQiu** [comment]
If we find more issues about the low concurrency of `getWorkerInfoList()`, https://github.com/Alluxio/alluxio/pull/10480 is an example of what changes we can make.
