### ISSUE TITLE
Metrics System

### ISSUE THREAD

**Issue by lord-i-will** [Alluxio/alluxio#10471]
**Page**
https://docs.alluxio.io/os/user/stable/en/operation/Metrics-System.html

**Summary**
Don't you support InfluxDBSink? Is this in your roadmap?

**Comment by ZacBlanco** [comment]
Hi @lord-i-will ,

Currently, there are no plans to support an InfluxDB sink with our metrics system.

Personally, I recommend using the Graphite or Prometheus sink, and seeing if you can export them to InfluxDB from there. I'm not as familiar with the tool, so I can't provide a better recommendation.

**Comment by lord-i-will** [comment]
thx，our company is using influxDB for all services monitor. We are now using python to parse /metrics/json and import the parsed metrics to InfluxDB.
