### ISSUE TITLE
Revise master shutdown sequence

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#10505]
**Summary**
There are problems with the way we're shutting down masters:
1- There is no graceful wait period. We interrupt first, then wait.
2- Not all RPCs/ HeartbeatExecutors handle interruptions properly
3- Timeout for server shutdown is not well defined. A same value is used as a timeout for various sequential shutdown stages. (shutdown server -> shutdown executor -> shutdown master executors )

**Urgency**
Hygiene in this area will prevent dangling RPCs/tasks corrupting state.

**Comment by ns1123** [comment]
+1

**Comment by yuzhu** [comment]
fixed via #10489
