### ISSUE TITLE
alluxio-1.8.2 directory hang

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#10501]
**Alluxio Version:**
1.8.2

**Describe the bug**

    1. Spark read hive table, partitionBy and write to Alluxio
    2. due to run over 10 mins, i killed job
    3. file in Alluxio didn't delete
    4. "alluxio fs ls /" hang
    5. restart master and worker didn't work
    6. alluxio master can work after one night
    7. replay 1-3，alluxio fs ls / worked，but target directory hang, and export
    Failed after 1 attempts: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out

    8. alluxio fs rm -R /pass hang, export
    Failed after 1 attempts: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
    9. alluxio fs checkConsistency -r -t 32 /pass export
    Failed after 1 attempts: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
    10. wait 2 hours，target path deleted

**Additional context**
I found the key scene when the bug appear：
1. spark be killed when not all files moved out temporary dir 
2. user try to overwrite this dir
3. then the dir can be hang

**Comment by ZacBlanco** [comment]
@JySongWithZhangCe do you happen to have any of the master or worker logs from when you saw this error occur?

**Comment by apc999** [comment]
please help upload the jstack thread dump and master logs when the master hangs, which will be very helpful for us to identify the issue  @JySongWithZhangCe

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe do you happen to have any of the master or worker logs from when you saw this error occur?

in debug level, there was no ERROR information, i will provide logs and jstack thread

**Comment by JySongWithZhangCe** [comment]
> please help upload the jstack thread dump and master logs when the master hangs, which will be very helpful for us to identify the issue @JySongWithZhangCe

sure

**Comment by JySongWithZhangCe** [comment]
> please help upload the jstack thread dump and master logs when the master hangs, which will be very helpful for us to identify the issue @JySongWithZhangCe

i open a github project and push logs here
https://github.com/JySongWithZhangCe/AlluxioBugAnalysis/tree/master/alluxio-1.8.2-2019-11-19
