### ISSUE TITLE
Enable early release of locks during rpcs

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#10545]
**Is your feature request related to a problem? Please describe.**
Currently, setAttribute and setAcls calls iterate inode tree with DFS. This means the write-lock on the parent will remain locked until the whole tree is enumerated. Switching to BFS for these calls can help avoiding locking overhead when they are called on branches of a root concurrently, so that they don't contend for write-lock on the root.

**Additional context**
Optimizing traversals to allow quick unlocking of the tree may bring significant memory overhead due to space inefficiency of BFS compared to DFS.

I'd guess the structure of the inode tree in a typical deployment would have sufficient branching. However BFS's space inefficiency would be compounded in a higher rate than DFS, when many traversals run concurrently.

That being said, `setAttribute` and `setAcl` calls could still be switched to BFS since we won't allow multiple writes on the same inode. `listStatus`, on the other hand, is prone to mentioned memory overhead and better to leave unchanged.

**Comment by gpang** [comment]
Are you suggesting that if you do BFS, you can unlock sooner (before completion of rpc)? If so, then I think the title should reflect something like "enable early release of locks during rpcs" or something.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
