### ISSUE TITLE
fuse下测试大量写入后，很多失败的记录导致文件列表无法读取

### ISSUE THREAD

**Issue by we7team** [Alluxio/alluxio#10541]
**Alluxio Version:**
alluxio/alluxio-fuse:2.2.0-SNAPSHOT

**Describe the bug**
**测试命令：**
`for i in {1..10000};do dd if=/dev/zero of=file_$i bs=4K count=$i;done`

结果我 ls 时，出现大量错误日志，并且这一步会一直卡住，删也不删掉，猜测可能是在获取元数据对数据块进行了完整性检测，这种同步操作会严重影响获取元数据的速度，我认为应该异步处理，或者有个开关配置可以关掉这种检测才是比较合理的。

**错误日志：**
![image](https://user-images.githubusercontent.com/4837122/69961879-c3334580-1547-11ea-8164-1a7f9b3ed4e9.png)

**Comment by LuQQiu** [comment]
Fuse 会将大量应用转换为底层API, 且AlluxioFuse无法控制这种转换， 比如你运行ls /test , 理想情况下FUSE 应该给到AlluxioFuseFileSystem.getattr(/test),但它会转换为对所有的子文件进行ls 比如getattr(/test/file_1), getattr(/test/file_2), getattr(/test/file_3)......
我不确定这步能否被取消。根据你的反应，可能你就卡在这里了

Fuse 写入一个文件会呼叫AlluxioFuseFileSystem.create(), 一系列 write(), 然后 close() 这代表这个文件写入完成。当一个文件还没有写入完成时，AlluxioFuseFileSystem.getattr()会显示 `File is not completed` ERROR. 这是因为文件正在写入，不支持getattr()。

的确允许getattr() 异步 （当文件正在写入也允许ls) 是比较合理的。我们对getattr()进行了特殊的处理因为Alluxio的文件长度不是实时显示在文件状态中的。 Alluxio文件只能写一次，不允许修改，文件长度会在文件写完后更新在文件状态中，文件完成前的文件状态一直是长度为0. 这个特征影响了一些tensorflow 程序的正确运行。tensorflow程序会在文件写入过程中查看文件状态，得到文件长度为0就会显示程序错误。

**Comment by jja725** [comment]
Will close it for now since seems like it's resolved
