### ISSUE TITLE
Allow IPC's for stop/start/restart of specific systems within Alluxio

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#10571]
**Is your feature request related to a problem? Please describe.**
Rebooting the entire Alluxio Master process can be expensive depending on the size of the journal/inodetree. In some scenarios, errors can be corrected with a restart of just the internal gRPC server (gRPC server thread limits, buffer limits, potential issues with the server itself). Having the ability to reset other systems like Metrics/BackupManager/Copycat may also be helpful to change certain settings i.e. Automated Backup Time, Cluster Metric heartbeats without incurring the overhead of a full restart of the service and interrupting existing clients.

**Describe the solution you'd like**
Add a CLI utility to 'bin/alluxio fsadmin' to allow stop/start/restarting of some of the different Alluxio Master Internal systems.

**Describe alternatives you've considered**
No clear alternative for this. Allowing a stop option may be more complicated since the impact of stopping certain services indefinitely aren't fully understood. Restart would be more preferred.

**Urgency**
Allows for more flexibility in cluster operation, tuning, and triage of issues.

**Comment by ZacBlanco** [comment]
I think we should carefully think about the implementation of something like this because being able to start/stop the system via an RPC is susceptible to security issues with denial-of-service attacks being carried out in environments that are not properly secured.

**Comment by ns1123** [comment]
@ZacBlanco I'll modify the description to be an IPC. It doesn't need to be executable from a remote host and since part of the reason for implementing this is to restart the RPC server anyway, it wouldn't make sense to have it rely on the RPC framework for this call.

**Comment by ns1123** [comment]
As added clarification, this could be done using a UNIX domain socket with permissions set as 700 so that only the Alluxio process owner would be able to issue the specific calls and only from the leader-master host.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
