### ISSUE TITLE
zsh doesn't work as the shell in EMR documentation

### ISSUE THREAD

**Issue by MadanKumar21** [Alluxio/alluxio#10595]
Alluxio EE documentation for 2.1.0 on EMR should specify that should be using /bin/bash terminal when running aws emr create statement. iTerm by default uses zsh which doesn't take in URLs accurately. 
zsh: no matches found: Path=s3://alluxio-public/emr/2.1.0/alluxio-emr.sh,Args=[s3://madans3bucket/emr/mount/]

**Comment by ZacBlanco** [comment]
In light of preserving simplicity across most systems - I've added a note that the command is designed for bash.

Most people who use `zsh` are using it by choice. MacOS has recently started defaulting the shell to `zsh` when upgrading to MacOS Catalina, but I don't think the user base is large enough to justify having a second command.

If you don't think this fix is enough, we can try to spend some more effort to design a command compatible with both interpreters.
