### ISSUE TITLE
The worker has stored some blocks, but BlockInfo tab has nothing.

### ISSUE THREAD

**Issue by ChangjiGuo** [Alluxio/alluxio#10611]
**Alluxio Version:**
alluxio version is 2.1.0.

**Describe the bug**
The worker has stored some blocks, but "BlockInfo" tab has nothing in the web ui.

**To Reproduce**
1. Install alluxio-2.1.0
2. Use default configuration
3. I wanna test data locality, so i run the same command on each node :
```
alluxio fs load /kylincluster/tmp/bench/15 --local
```
4. http://worker-address:30000/blockInfo has nothing. Each node is like this:
![image](https://user-images.githubusercontent.com/35126911/70593056-a917f800-1c16-11ea-9ef1-5c84130b988c.png)
5. The json is as follows:
```
{"ntotalFile":109,"path":null,"blockSizeBytes":null,"fileBlocksOnTier":null,"orderedTierAliases":["SSD"],"fileInfos":[],"fatalError":"","invalidPathError":""}
```

**Comment by ZacBlanco** [comment]
I can reproduce this on my local machine. On my end the root cause is that the react application is making a request to `/webui_blockinfo`, where it should actually be making a request to `/api/v1/worker/webui_blockinfo`

**Comment by ChangjiGuo** [comment]
@ZacBlanco  Thanks for your response! In my case, when I access the worker's webui I also see a 404 in the list of responses for `/overview` instead of the  `/blockInfo`.
![image](https://user-images.githubusercontent.com/35126911/70683823-c617fe00-1cde-11ea-99f8-958785dce2d9.png)

**Comment by ChangjiGuo** [comment]
@ZacBlanco Thanks for your response! I remember it was normal in 2.0, has anything changed in 2.1?

**Comment by ZacBlanco** [comment]
@ChangjiGuo Yes, it looks like this bug was the result of another bug fix.

https://github.com/Alluxio/alluxio/commit/bd0086609530926f51c15675e106442d6707f5a3#diff-8fd58f2fff6b98cc6cbb70f6f878e3cc

**Comment by ChangjiGuo** [comment]
Is there any command that can do the same? Thanks.

**Comment by ZacBlanco** [comment]
@ChangjiGuo you can try using `./bin/alluxio fs stat <path>` to get the information that would be available in that UI, but may contain blocks across multiple workers.

Also, I've just merged a PR that fixes the issue in the UI. It will be in the next release (2.1.1) that should be out some time in the next week or two. Keep an eye out on the email list or on the github releases page for when it is released.
