### ISSUE TITLE
List files from OSS bucket took 20mins

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10636]
**Alluxio Version:**
2.2.0

**Describe the bug**

The number of files in OSS bucket is about 3000000.  try to list the directory. And find it takes 22 minutes

```
$ time alluxio fs ls /images_2
-rwxrwxrwx                                          26333       PERSISTED 12-11-2019 17:05:24:000   0% /images_2/999994.png
...
-rwxrwxrwx                                          26150       PERSISTED 12-11-2019 17:05:24:000   0% /images_2/999999.png

real    22m5.159s
user    1m48.367s
sys     0m27.279s
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by cheyang** [comment]
And I also notice the disk of journal is very large. Not a big deal. Just interesting. <img width="328" alt="snapshot" src="https://user-images.githubusercontent.com/3724388/70777747-84a95080-1dbb-11ea-9080-c23f339481fb.png">

**Comment by jiacheliu3** [comment]
@apc999 Maybe this `fs ls` command should have a pagination parameter for this kind of extremely flat FS structure. For example `fs ls -limit 500 /` to only show 500 files or `fs ls -p 0 /` to show the 0th page of whatever files.

**Comment by jiacheliu3** [comment]
Regarding the journal file sizes, you may want to refer to [journal tuning](https://docs.alluxio.io/ee/user/stable/en/operation/Journal.html?q=journal#advanced) for better controlling the size.

**Comment by cheyang** [comment]
> @apc999 Maybe this `fs ls` command should have a pagination parameter for this kind of extremely flat FS structure. For example `fs ls -limit 500 /` to only show 500 files or `fs ls -p 0 /` to show the 0th page of whatever files.

I suggest that user can is able to cache such info if he claims to need this. The user scenario is ,that the AI training program will call the `directory list` action first, then shuffle the file names. If we can speed up it this action, it will be helpful. Thanks.

**Comment by hooooyeah** [comment]
你这个是有元数据缓存条件还是没有缓存 条件？

**Comment by cheyang** [comment]
没有缓存，这个操作的目的就是缓存oss元数据

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a valid issue
