### ISSUE TITLE
Persist Job remains in JobWorker even after cancel.

### ISSUE THREAD

**Issue by bradyoo** [Alluxio/alluxio#10648]
**Alluxio Version:**
What version of Alluxio are you using? 2.2.0-SNAPSHOT, but reproducible in 2.1.1 and 2.0.x

**Describe the bug**

PersistJob cancellation doesn't get processed properly.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

With AsyncThrough writeType

1. Write a large number of files as AsyncThrough
2. Before all of them gets persisted, rm them all.
3. Wait for a long time.
4. Run jobservice report

You will see that there are a large number of jobs still stuck under CREATED/RUNNING.

**Expected behavior**

0 jobs under CREATED or RUNNING

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

There is no report in 2.0 to see the bug clearly but the bug is nonetheless still there.

**Comment by rastogiasr** [comment]
@bradyoo  is this still an open issue?

**Comment by bradyoo** [comment]
It's not in 2.1. I should actually resolve it.
