### ISSUE TITLE
checkConsistency ok between alluxio and HDFS, but actual file content and MD5 not consistent

### ISSUE THREAD

**Issue by lord-i-will** [Alluxio/alluxio#10678]
**Alluxio Version:**
1.8.1

**Describe the bug**
Run "alluxio fs checkConsistency /path/folder", the result is ok:
![image](https://user-images.githubusercontent.com/14847104/71341857-07899280-2596-11ea-869b-6e1c14b22492.png)
Download these files from alluxio and md5sum these files, the result as followings:
![image](https://user-images.githubusercontent.com/14847104/71341947-559e9600-2596-11ea-80ad-3a4ff6fd5eda.png)
Download these files from HDFS and md5sum these files, the result as followings:
![image](https://user-images.githubusercontent.com/14847104/71342026-8c74ac00-2596-11ea-9669-b31fc1c2c97b.png)
Don't know why this situation happens. No alluxio errors. We found this situation when hive tasks throw errors like followings:
![image](https://user-images.githubusercontent.com/14847104/71342179-fc833200-2596-11ea-9a7f-70f1448a662e.png)

**To Reproduce**
None.

**Expected behavior**
checkConsistency should not be OK and there should be some alluxio errors.

**Urgency**
very critical..

**Additional context**
None.

**Comment by lord-i-will** [comment]
i found this error: https://alluxio.atlassian.net/browse/ALLUXIO-2636

**Comment by ns1123** [comment]
@lord-i-will, In 1.8, there are a few known bugs. The main thing to realize is that checkConsistency bases it's comparison on filesize, while using alluxio.user.file.metadata.sync.intereval=0 will validate that the file metadata matches in both size and timestamp. Likely what happened here is that the file was modified but the size didn't change so checkConsistency didn't notice the difference.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
