### ISSUE TITLE
Add listening address for embedded journal

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#10693]
**Is your feature request related to a problem? Please describe.**
Fine control over the embedded journal service's listening address is not available.

**Describe the solution you'd like**
Add a property to specify the listening address of the journal service, similar to how the master has a listening address for the rpc service.

**Additional context**
This allows users to more easily deploy Alluxio in K8s environments secured with istio.

**Comment by ggezer** [comment]
Do copycat clients supposed to connect to listen port then? This means the membership address list config property should list host and listen addresses separately for each.
