### ISSUE TITLE
Persist command persist file to s3 underfs second time.

### ISSUE THREAD

**Issue by pragnesh** [Alluxio/alluxio#10699]
**Alluxio Version:**
2.1.0

**Describe the bug**
I am using Alluxio server with s3 underfs on aws. I am writing output to Alluxio using spark job.
Alluxio server is configure with following setting as describe in doc.
```
# Writes data only to Alluxio before returning a successful write
alluxio.user.file.writetype.default=ASYNC_THROUGH
# Does not persist the data automatically to the underlying storage, this is important because
# only the final committed data is necessary to persist
alluxio.user.file.persistence.initial.wait.time=-1
# Hints that Alluxio should treat renaming as committing data and trigger a persist operation
alluxio.user.file.persist.on.rename=true
# Determines the number of copies in Alluxio when files are not yet persisted, increase this to
# a larger number to ensure fault tolerance in case of Alluxio worker failures
alluxio.user.file.replication.durable=1
# blacklist files which contain the string "_temporary" anywhere in their path
alluxio.master.persistence.blacklist=_temporary
```
Once spark job is completed. Alluxio start writing to s3. Now before Alluxio complete writing to s3 if i issue persist command on ouput dir. It seems that Alluxio start uploading file which is not persisted yet but it is getting uploaded by async process. I have s3 notification enabled on bucket. and I am getting two s3 create "ObjectCreated:CompleteMultipartUpload" notification for the same object. 
I can see persist command writing file s3 second time in output. This issue only occur for file which is not persisted yet.

**To Reproduce**
Already mention in bug description.

**Expected behavior**
Alluxio should write file to s3 underfs only once.

**Urgency**

**Additional context**

**Comment by jja725** [comment]
Async write dedupe would be considered during the async write redesign.

**Comment by jja725** [comment]
@cwang9208 Hey, thanks for the interest, please take a look at the scheduler in the main branch and this would be the basement for new job service

**Comment by cwang9208** [comment]
@jja725 Hi, I'm recently reading the latest scheduler code, but I'm still confused about how the job scheduler addresses the "network partition" problem.  Say the job master assigns a persist job to worker A. Then, worker A is network partitioned but is still persisting the job in the background. Then job master assigns the same job to worker B. So, there can be two workers working on the same file on S3 at the same time, which might corrupt the data. I'm wondering how does the job master handle this problem?

**Comment by cwang9208** [comment]
@jja725 Noted. Thanks for your reply!
