### ISSUE TITLE
checkConsistency fails for files that are asynchronously persisted

### ISSUE THREAD

**Issue by bf8086** [Alluxio/alluxio#10735]
**Alluxio Version:**
2.2-SNAPSHOT

**Describe the bug**
Running `alluxio fs checkConsistency` will fail on files that are asynchronously persisted.

**To Reproduce**
Start Alluxio.
Run `alluxio runTests`
Run `alluxio fs checkConsistency /`
Got
```
The following files are inconsistent:
/default_tests_files/BASIC_CACHE_ASYNC_THROUGH
/default_tests_files/BASIC_CACHE_PROMOTE_ASYNC_THROUGH
/default_tests_files/BASIC_NON_BYTE_BUFFER_CACHE_ASYNC_THROUGH
/default_tests_files/BASIC_NON_BYTE_BUFFER_CACHE_PROMOTE_ASYNC_THROUGH
/default_tests_files/BASIC_NON_BYTE_BUFFER_NO_CACHE_ASYNC_THROUGH
/default_tests_files/BASIC_NO_CACHE_ASYNC_THROUGH
```
**Expected behavior**
checkConsistency should show that everything is consistent.

**Urgency**
medium, does not affect data integrity or other operations, but can be confusing to users.

**Additional context**

**Comment by rastogiasr** [comment]
@bf8086  - is this fixed in 2.1.2 patch?

**Comment by bf8086** [comment]
yes.

**Comment by bf8086** [comment]
Resolved by https://github.com/Alluxio/alluxio/pulls?page=3&q=is%3Apr+is%3Aclosed
