### ISSUE TITLE
Update README.md to reference 2.1.1 as the default latest release instead of 2.1.0.

### ISSUE THREAD

**Issue by haoyuan** [Alluxio/alluxio#10803]
**Page**
https://github.com/Alluxio/alluxio/blob/master/README.md

**Summary**
Update README.md to reference 2.1.1 as the default latest release instead of 2.1.0.

**Comment by ZacBlanco** [comment]
this is a duplicate of https://github.com/Alluxio/alluxio/issues/10752.
