### ISSUE TITLE
Alluxio CLI doesn't show right mount info (readonly/shared)

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#10812]
**Alluxio Version:**
Tested in both branch-2.1 and master branch 

**Describe the bug**
CLI doesn't show right mount info (readonly/shared)

Start alluxio with 
```
alluxio.master.mount.table.root.ufs=${alluxio.work.dir}/underFSStorage
alluxio.master.mount.table.root.readonly=true
alluxio.master.mount.table.root.shared=true
```
but mount info shows not read-only and not shared
```
$ ./bin/alluxio fs mount
/Users/alluxio/alluxioFolder/alluxio/underFSStorage  on  /  (local, capacity=465.72GB, used=-1B(0%), not read-only, not shared, properties={})
$ ./bin/alluxio fsadmin report ufs
Alluxio under storage system information:
/Users/alluxio/alluxioFolder/alluxio/underFSStorage  on  /  (local, capacity=465.72GB, used=-1B(0%), not read-only, not shared, properties={})
```

Try to delete file but find the mount point should be read-only
```
$ ./bin/alluxio fs rm /LICENSE
Failed to delete /LICENSE (Operation WRITE not allowed on ufs path /Users/alluxio/alluxioFolder/alluxio/underFSStorage/LICENSE under maintenance mode READ_ONLY) from the under file system
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
Mount should show read-only in my case

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jiacheliu3** [comment]
@LuQQiu Actually when creating the root mount as readonly and shared, I don't think it really takes effect. For example I started Alluxio with readonly root mount using your config properties, and then I can put files in the root mount. 
```
$bin/alluxio fs copyFromLocal ./LICENSE /LICENSE
Copied file:///Users/jiachengliu/Documents/Alluxio/alluxio-jiacheng/alluxio/LICENSE to /LICENSE
```

Do you know if readonly works at all?

**Comment by jiacheliu3** [comment]
Confirmed that readonly doesn't work for root mount but seems to work for nested mount. See different behavior below. 
```
$ ./bin/alluxio fs mount --shared --readonly /readonly_folder /Users/jiachengliu/Documents/Alluxio/alluxio-jiacheng/alluxio/readonly
Mounted /Users/jiachengliu/Documents/Alluxio/alluxio-jiacheng/alluxio/readonly at /readonly_folder
$ bin/alluxio fs mount
File system class class alluxio.client.file.BaseFileSystem
/Users/jiachengliu/Documents/Alluxio/alluxio-jiacheng/alluxio/readonly        on  /readonly_folder  (local, capacity=420.03GB, used=-1B(0%), read-only, shared, properties={})
/Users/jiachengliu/Documents/Alluxio/alluxio-jiacheng/alluxio/underFSStorage  on  /                 (local, capacity=420.03GB, used=-1B(0%), not read-only, not shared, properties={})
$ bin/alluxio fs touch /readonly_folder/aaaaa
A write operation on /readonly_folder/aaaaa under a readonly mount point /readonly_folder is not allowed
```

Please update the title of this issue.

**Comment by jiacheliu3** [comment]
Readonly attribute is fixed by https://github.com/Alluxio/alluxio/pull/10895
Shared attribute problem is more tricky and logged in https://github.com/Alluxio/alluxio/issues/10896
Closing this issue as we can keep track on #10896
