### ISSUE TITLE
Timeout from alluxio in HA or Multi Cluster's with MySQL Metastore

### ISSUE THREAD

**Issue by ChethanUK** [Alluxio/alluxio#10887]
**Alluxio Version:**
What version of Alluxio are you using?
2.1.1

**Describe the bug**
I have following Presto and Hive Dataproc Cluster:
![Dataproc](https://i.imgur.com/spryv1T.png?height=800px&width=950px)

Created some table in the first cluster.

For example, consider:

```bash
CREATE EXTERNAL TABLE u_user (
userid INT,
age INT,
gender CHAR(1),
occupation STRING,
zipcode STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
LOCATION 'alluxio://cluster1-m:19998/ml-100k';
```

Now, tried querying the table u_user from cluster2, it's timing out

**Expected behavior**
Like with normal Hive tables, both cluster should be able to query the data on created table.

**Comment by ZacBlanco** [comment]
@ChethanUK can you provide your `alluxio-site.properties` file? Please make sure to omit any passphrases or sensitive information
