### ISSUE TITLE
Failed to pass all runTests in k8s 

### ISSUE THREAD

**Issue by wangyuqing4** [Alluxio/alluxio#10894]
**Alluxio Version:**
code: master branch，2.2.0；docker images tag: 2.2.0-SNAPSHOT

**Describe the bug**
use /integration/kubernetes/singleMaster-localJournal,  
```
kubectl create -f alluxio-configmap.yaml
kubectl create -f ./master/ 
kubectl create -f ./worker/
```
when i kubectl get po, 
```
NAME                   READY   STATUS    RESTARTS   AGE
alluxio-master-0       2/2     Running   0          10s
alluxio-worker-gvmqj   2/2     Running   0          5s
```
```
kubectl exec -ti alluxio-master-0 /bin/sh
./bin/alluxio runTests
```
some tests pass, but 12 tests failed, print

```
2020-02-12 10:43:52,171 ERROR CliUtils - Exception running test: alluxio.examples.BasicOperations@1b75c2e3       
alluxio.exception.status.NotFoundException: /opt/alluxio-2.2.0-SNAPSHOT/underFSStorage/default_tests_files/BASIC_
id: -1   
......
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: /opt/alluxio-2.2.0-SNAPSHOT/underFSStorage/default_tests_fi
        at io.grpc.Status.asRuntimeException(Status.java:533)                                                    
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)            
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)      
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)                    
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallLi
        at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:176)                     
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)      
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)                    
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallLi
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)                                
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)                                    
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)   
......
 Number of failed tests: 12
```
i just started using alluxio, i can run alluxio on centos/docker container, but i can't pass all tests on k8s. looking forward to your reply :)

**Expected behavior**
when i use ./bin/alluxio runTests, all tests pass

**Comment by ZacBlanco** [comment]
Did you configure alluxio to point to a UFS? Have you followed the guide here:

https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html

Please let us know if there are further issues.

**Comment by wangyuqing4** [comment]
thx, you mean when i use kubectl create -f alluxio-configmap.yaml, in the alluxio-configmap.yaml, i should add **-Dalluxio.master.mount.table.root.ufs=<under_storage_address>** to ALLUXIO_JAVA_OPTS ?
in the master branch alluxio/integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template i did't see the property.

**Comment by ZacBlanco** [comment]
Yes you will need to add `-Dalluxio.master.mount.table.root.ufs` if you haven't yet.

For a simple local deployment, you will need to create a persistent volume in k8s  and mount that to your master and worker containers in the same location.

Otherwise, if you have access to an external storage service like s3, you should just be able to specify the s3 path along with the credentials to create the mount properly

**Comment by wangyuqing4** [comment]
thx，now i use obs(https://docs.alluxio.io/os/user/edge/en/ufs/OBS.html?q=obs), according to the doc,  completed successfully in centos，but in k8s failed

kubectl exec -ti alluxio-master-0 /bin/sh
./bin/alluxio extensions install alluxio-underfs-obs-2.0.0.jar

```
Failed to install extension on hosts:
localhost
```

**Comment by wangyuqing4** [comment]
why i can't use the file /underFSStorage in node which the pod deploy?

**Comment by ZacBlanco** [comment]
Is there anything under `${ALLUXIO_HOME}/logs/task.log` within the container you tried to install the extension with?

`/underFSStorage` is a local directory specific to the container that is running in that pod. In order to use that as a UFS it must be accessible to all nodes in the cluster (Alluxio masters and workers). If you have more than one physical machine (multiple kubelets), then you can't simply use a directory because that can't be read across machines unless you've mounted the same disk on multiple systems.

However, if you are running on a single node, you can make PV claim in k8s which can then be mounted to any number of containers within the Alluxio pod. It can work for a simple local deployment - but will not work otherwise.

**Comment by wangyuqing4** [comment]
thx, now i use local directory,  one physical machine, when runTests, 12 tests failed the same. 
With ASYNC_THROUGH field test will success, but without ASYNC_THROUGH test will failed.  probably not a problem with volume？

runTest.log and *yaml all in the link https://github.com/wangyuqing4/alluxio-k8s

**Comment by ZacBlanco** [comment]
It sounds like there is a problem with the mounted volume. If the tests with `THROUGH` and `CACHE_THROUGH` write types are failing, then your volume is probably not mounted correctly for each container

**Comment by wangyuqing4** [comment]
i solve it last week，volumes in master branch alluxio-worker-daemonset.yaml maybe have error，when i add pvc the same as alluxio-master-statefulset.yaml， runTests all pass.

**Comment by jiacheliu3** [comment]
@wangyuqing4 Sounds like you are using a ReadWriteMany persistent volume as the under storage. In that case you need to mount that to masters and workers.

You mentioned volumes in master branch alluxio-worker-daemonset.yaml maybe have error. What was the error you found or observed?

**Comment by ZacBlanco** [comment]
@jiacheliu3 I think this was the log: https://github.com/wangyuqing4/alluxio-k8s/blob/d2607444693b7fa8eac8b385b21bd4b7a6ef1574/runTests.log

**Comment by jiacheliu3** [comment]
@ZacBlanco I wonder why the error is 
```
NOT_FOUND: /journal/default_tests_files/BASIC_NON_BYTE_BUFFER_CACHE_PROMOTE_CACHE_THROUGH
```
Seems the under storage dir is the journal path?

**Comment by jiacheliu3** [comment]
@ZacBlanco Do you think this can be closed? I feel this is most probably due to a misconfigure on the PVC.

**Comment by jiacheliu3** [comment]
Closed as this is a mis-configuration
