### ISSUE TITLE
unexpected behavior of meta info synced from Hadoop UFS

### ISSUE THREAD

**Issue by casperit** [Alluxio/alluxio#10927]
**Alluxio Version:**
Alluxio 2.1.1

**Describe the bug**
with a Hadoop path mounted on the alluxio path, the meta info(acl,mask, user/group) sub-directories and sub-files is  wrong, which makes it impossible to make queries to the alluxio namespace 

**To Reproduce**
1. set up a kerberos hdfs cluster(version>=2.7)
2. set up a alluxio cluster with hdfs as the ufs location
3. mount a hdfs path to a alluxio path
     alluxio fs mount /formal/g37_us/ods hdfs://mycluster/data/gamein/g37_us/ods
4. The hdfs path `hdfs://mycluster/data/gamein/g37_us/ods` has a sub-directory `/data/gamein/g37_us/ods/ods_huangkulou_info_day/dt=20200102` and the sub-file `/data/gamein/g37_us/ods/ods_huangkulou_info_day/dt=20200102/000000_0.snappy`
5. The hdfs file has the following permission info
![image](https://user-images.githubusercontent.com/46516818/74670934-1af75980-51e5-11ea-8e3e-42da1912deb4.png)
6. when check the permission info on alluxio namespace,it is different from hdfs meta
![image](https://user-images.githubusercontent.com/46516818/74671178-93f6b100-51e5-11ea-8d13-c163063d7eaf.png)
7. to check the permission of `/data/gamein/g37_us/ods/ods_huangkulou_info_day/dt=20200102`, the meta info is also different between alluxio and hdfs 
![image](https://user-images.githubusercontent.com/46516818/74671366-f8b20b80-51e5-11ea-8c97-8c8037d05467.png)
the mask info the group acl are different

in a word: the permission info(mask and mode) is different bewteen hdfs and alluxio for the same mapping directories and files

**Expected behavior**
the permission info should be the same bewteen hdfs and alluxio for the same mapping directories and files

**Urgency**
1. urgent
2. the compute engine(in my case presto) cant retrive data from alluxio  because of the permission inequivalence

**Additional context**
1. the file mode info can be amended  manually by triggering a `alluxio startSync` command on the file path  or by `alluxio ls` on the parent-directory, but the mask is still wrong
2. the problem arises when i try to do a upgrade from Version-1.8.1 to Version-2.1.1, it is sure that on 1.8.1, the mode info is the same between hdfs and alluxio and the mask info is unkownd because there is no `getfacl` command on 1.8.1

**Comment by loushang0826** [comment]
hi, any updates?  @apc999

**Comment by yuzhu** [comment]
kerberos is not completely supported in the community version, please look into enterprise edition.
