### ISSUE TITLE
Support security in webfs

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#10937]
**Is your feature request related to a problem? Please describe.**
I cannot connect to a secured http endpoint through webfs.

**Describe the solution you'd like**
Ability to pass simple user/password credentials to webfs.

**Urgency**
This limits the use cases of webfs to public sites.

**Comment by calvinjia** [comment]
Technical details - in `WebUnderFileSystem`, we have the `UnderFileSystemConfiguration` which could be used to pass in a `webfs.user` and `webfs.password`. Then we could attach the credentials to any requests we make through `HttpUtils`.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
