### ISSUE TITLE
helm-generate.sh does not support Helm 3

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#10956]
**Alluxio Version:**
2.2.0-SNAPSHOT

**Describe the bug**
helm-generate.sh uses Helm 2.X to generate Helm template YAML files. Helm 3 has changed the API so the script doesn't work anymore.

**To Reproduce**
Run `helm-generate.sh` with Helm 3.X

**Expected behavior**

**Urgency**
Medium

**Additional context**

**Comment by jiacheliu3** [comment]
Helm 3 and 2 has incompatible APIs so I think it's hard to support both with one script. I would recommend having another script for Helm 3. What do you think? @madanadit

**Comment by madanadit** [comment]
We could remove support for helm 2 and only support helm 3 going forward as it’s simpler by removing tiller @jiacheliu3

**Comment by jiacheliu3** [comment]
Addressd by #11324
