### ISSUE TITLE
Add a isFile() option to PropertyKey.Builder

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#10966]
**Is your feature request related to a problem? Please describe.**
Multiple file properties don't do validations that the file exists or is accessible. Flagging properties that specify file paths (alluxio.underfs.hdfs.keytab.file) with the option could enabled launch-time checks for validity.

**Describe the solution you'd like**
Add a new option in PropertyKey.Builder like .isFile()

**Describe alternatives you've considered**
N/A

**Urgency**
P1 for User Experience

**Additional context**
Might also be nice to have extra validations for mount properties at runtime (matching file checksums on all nodes etc.)

**Comment by apc999** [comment]
more explanation (based on my understanding & requirement) 
there are plenty of alluxio property keys, each could represent a boolean value, a int value or a string.
In certain cases, a string could represent a path to a file (e.g., `alluxio.underfs.hdfs.keytab.file` pointing to a file path).
For these properties, when they are set, it will be nice to check if the value of this property really points to an existing file

**Comment by rongrong** [comment]
> more explanation (based on my understanding & requirement) there are plenty of alluxio property keys, each could represent a boolean value, a int value or a string. In certain cases, a string could represent a path to a file (e.g., `alluxio.underfs.hdfs.keytab.file` pointing to a file path). For these properties, when they are set, it will be nice to check if the value of this property really points to an existing file.
> 
> This ticket is asking to add a field in `PropertyKey`, indicating if this property key points to an existing file path as expected on runtime. `alluxio.conf.InstancedConfiguration#validate` is a centralized place to check configuration in runtime

So it's more like having another property type "path"? I'm assuming they can be files or directories?
