### ISSUE TITLE
Create a Custom Replication Policy based on Datacenter, Rack and Node Awareness

### ISSUE THREAD

**Issue by chandrasaripaka** [Alluxio/alluxio#11021]
Create a Custom Replication Policy based on Datacenter, Rack and Node Awareness.

Alluxio workers can be marked with the labels for the Datacenter, rack and node.
In my case, I would need a CustomReplicationPolicy to be created since we have to ensure more than 2 copies of cache selectively for different paths for hot and cold data. This is only for the layers where we use MEM/DISK. Here we need to induce the node coordinates to the replication policy.

**/opt/alluxio/bin/alluxio fs setReplication <Path> --min 3 --max 4 --policy CustomReplicationPolicy**

**Comment by chandrasaripaka** [comment]
Any suggestions are welcome, to rephrase or suggestions to do better.

**Comment by haoyuan** [comment]
Thanks @chandrasaripaka ! Looking forward to your PR! In the meantime, let the community know anything the community can help. Cheers.

This Issue is based on the conversation from https://alluxio-community.slack.com/archives/CEXGGUBDK/p1580965409161200 ;

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
