### ISSUE TITLE
Inconsistent library versions notice.

### ISSUE THREAD

**Issue by kaifeng-h** [Alluxio/alluxio#11074]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 2 inconsistent libraries.

Take org.apache.hadoop:hadoop-common for example, this library is declared as version 2.7.3.2.6.1.0-129 in underfs/wasb, 2.7.3 in integration/yarn and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take org.apache.hadoop:hadoop-common for example, if we harmonize all the library versions into 3.1.3. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table is listed below. It shows the overall harmonization effort by modules. The columns represents the number of library APIs and API calls(NA,NAC), deleted APIs and API calls(NDA,NDAC) as well as modified API and API calls(NMA,NMAC). Modified APIs refers to those APIs whose call graph is not the same as previous version. Take the first row for example, if upgrading the library into version 3.1.3. Given that 24 APIs is used in module integration/yarn, 0 of them is deleted in a recommended version(which will throw a NoMethodFoundError unless re-compiling the project),  15 of them is regarded as modified which could break the former API contract.

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|integration/yarn|24(34)|0(0)|15(25)|
|2|underfs/wasb|0(0)|0(0)|0(0)|

The file table listed below shows the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

|Module|File|Type|API|
|-|-|-|-|
|integration/yarn|integration/yarn/src/main/java/alluxio/yarn/Client.java|modify|org.apache.hadoop.security.Credentials.writeTokenStorageToStream(java.io.DataOutputStream)|
|integration/yarn|integration/yarn/src/main/java/alluxio/yarn/Client.java|modify|org.apache.hadoop.security.UserGroupInformation.getCurrentUser()|
|integration/yarn|integration/yarn/src/main/java/alluxio/yarn/Client.java|modify|org.apache.hadoop.security.Credentials.addToken(org.apache.hadoop.io.Text,org.apache.hadoop.security.token.Token)|
|4|..|..|..|

If you are interested, you can have a more complete and detailed report in the attached PDF file.

[Alluxio alluxio.pdf](https://github.com/Alluxio/alluxio/files/4270474/Alluxio.alluxio.pdf)

**Comment by apc999** [comment]
thanks @kaifeng-h  , 
dependencies in `underfs/wasb` shall be shaded and class-loaded by different classloader to avoid class conflict. 
And we are removing `integration/yarn` module now.

Thanks for the report! It is quite useful
