### ISSUE TITLE
Add readiness and liveness probes to Alluxio containers in K8s

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11079]
**Is your feature request related to a problem? Please describe.**
In K8s, the Alluxio container processes goes to `RUNNING` state right after the process is started (`entrypoint.sh` doesn't end in error). 

However, the container being in `RUNNING` state doesn't mean the container can work. It can be waiting for masters to elect a leader. It can wait for a certain process to start and then fail eventually. We need a readiness probe to help us make sure the container is functioning, before we do anything on it.

Going further on this thread, we probably need a liveness probe to help us identify a container failing. For example, when the masters crash, the workers are still in `RUNNING` state, although they are obviously not connected to any master and cannot work.

**Describe the solution you'd like**
**Part I: Add readiness probes to all Alluxio master and worker containers**
For readiness probes, `alluxio fsadmin report` command can work on masters and workers.
The command returns successful state when the Alluxio masters are running and the leader is elected. Having this as the readiness probe at least guarantees the basic functionality of the Alluxio container. In addition it doesn't take much resource or block the cluster from working.

Part I can be well satisfied with `alluxio fsadmin report`

**Part II: Add liveness probes to all Alluxio master and worker containers**
`alluxio fsadmin report` on the master side guarantees there is a leader. 
`alluxio fsadmin report` on the worker side guarantees the worker is connected with the master(s).
However, the trick thing is, K8s will try to restart the container if its liveness probe returns an error. If the master(s) connection is lost, there is no point restarting the worker containers. There may be better options for a liveness probe on worker.

**Describe alternatives you've considered**

**Urgency**
MEDIUM

**Additional context**

**Comment by jiacheliu3** [comment]
@madanadit Wanted to discuss with you on **Part II** regarding the liveness probe.

In a HA environment and 1 master goes down, will `alluxio fsadmin report` return error only for the dead master container (and makes K8s restart it)?

For an Alluxio worker that lost master connection (masters are down), how do we make the liveness probe still return alive? What do you think is a good probe in this case?

**Comment by madanadit** [comment]
@ZacBlanco how does the monitor script check for readiness?

**Comment by ZacBlanco** [comment]
It depends on the process.

Single master
- RPC server ping

Multi-master w/ HA
- ssh into each node, pgrep for Alluxio(Job)Master and check a PID exists

(Job)Worker
- RPC ping

**Comment by madanadit** [comment]
@jiacheliu3 you should look at `bin/alluxio-monitor.sh` and check the `run_monitor` method. For the workers, you can use the same health check: `alluxio.worker.AlluxioWorkerMonitor`

**Comment by jiacheliu3** [comment]
In HA mode I can also just do `bin/alluxio-monitor.sh master` instead of `masters`. This can also work.

**Comment by jiacheliu3** [comment]
It's actually recommended to use an http probe instead of executing a command which spawns up a JVM. This is especially true for liveness probes as they can get probed quite often and ends in error state if it times out (and get the container restarted). 

So if there currently isn't a `localhost:port/health` endpoint, I would propose we add one. Or maybe we can use the rest service to do it.

If we have to use the `alluxio-monitor.sh` as liveness probe, I would say the interval and allowed timeout should be big.

**Comment by jiacheliu3** [comment]
This has been addressed in https://github.com/Alluxio/alluxio/pull/11080
