### ISSUE TITLE
Add a query parameter to job list interface

### ISSUE THREAD

**Issue by zhangfy** [Alluxio/alluxio#11104]
We use Alluxio 2.1.2. Due to the alluxio.user.file.writetype.default=ASYNC_THROUGH, we have to make sure the data is persistent. So we need an interface to monitor jobs, especially persist jobs. We read the code,find the following urls.

1、http://xxx.xxx.xxx.xxx:20002/api/v1/master/job/list
2、http://xxx.xxx.xxx.xxx:20002/api/v1/master/job/get_status?jobId=1582614078889

First url to get all jobs, second url be uesd to find the detail of one job. So it's not convenient. If the first interface can get a query parameter, the parameter is used to distinguish job types. That would be good.

**Comment by zhangfy** [comment]
@ZacBlanco Can you assign this task to me? As a newer, I want to try it.

**Comment by ZacBlanco** [comment]
I've assigned this issue to you. You may open a PR which closes the issue. The PR description should include the message `closes #11104`. We can iterate on the implementation there.

If you need a starting point I would recommend looking at the [`AlluxioJobMasterRestServiceHandler`](https://github.com/Alluxio/alluxio/blob/master/job/server/src/main/java/alluxio/master/AlluxioJobMasterRestServiceHandler.java)

**Comment by zhangfy** [comment]
@ZacBlanco Thank you for your advice. Sorry, I don't know what's the PR mean.Can you give me the full name of PR?

**Comment by ZacBlanco** [comment]
PR -> **P**ull **R**equest

It's the standard github workflow for contributing code to a repository that you don't own:
https://guides.github.com/introduction/flow/

We also have a contribution guide in our documentation: https://docs.alluxio.io/os/user/stable/en/contributor/Contributor-Getting-Started.html

**Comment by zhangfy** [comment]
@ZacBlanco Thanks

**Comment by apc999** [comment]
this feature is working in progress now led by @jja725

**Comment by jja725** [comment]
now new job service infra doesn't provide detailed file level information. Will close it for now, feel free to reopen it and contact us if this is a strong request.
