### ISSUE TITLE
Export the whole file tree.

### ISSUE THREAD

**Issue by zhangfy** [Alluxio/alluxio#11105]
We use alluxio 2.1.2. In practice, we found that we need a tool to export the file tree every day for analysis. But the current version has no interface to export. If the new version has the command, that would be good.

**Comment by ZacBlanco** [comment]
@zhangfy can you elaborate a bit more on your request?

What do you mean by "Export the whole file tree"?

Do you mean simply being able to see the inode metadata for all paths? Or do you mean simply backing up the journal in case of failure recovery?

Alluxio provides `alluxio fsadmin backup` to create a backup of the current master's journal. You can then explore this through the `JournalTool`

In either case, Alluxio should already provide those features.

If it is not those could you explain what exactly you're looking for?

**Comment by zhangfy** [comment]
@ZacBlanco Sorry, I didn't describe the question clearly.In my case, I need to dump the whole path to a file. The dump file need to include columns such as using `alluxio fs stat path` command.

**Comment by ZacBlanco** [comment]
I see. Using the combination of tools I listed above can get you all the information you need in a human-readable format, but probably not in the format you're looking for. You might need to write something yourself to dump that information

**Comment by zhangfy** [comment]
Thank you for your patience. But I still have the following two questions.

1. I try the `alluxio fsadmin backup` command. I found characters appear as gibberish when I open the backup file with using VIM. How to open the backup file is correct? 
2. As you said above, alluxio has the feature to see inode metadata for all paths. Which command can I use to check?

**Comment by hooooyeah** [comment]
alluxio readjournal ?
![image](https://user-images.githubusercontent.com/11880771/76963308-c66a0a00-695b-11ea-9094-02e9400dbe7c.png)
