### ISSUE TITLE
Backup Coordinator

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#11155]
**Is your feature request related to a problem? Please describe.**
Daily backup manager lacks in versatility to be used on periodic backup needs other than daily backup.

**Describe the solution you'd like**
Backup manager that allows taking backups at any cadence. After backup delegation support, taking backups aggressively has became viable. This component can provide required functionality in order to avoid external scripting.

**Additional context**
There could be possible improvements to backup delegation code in order to support back-to-back backups from this new component.

**Comment by jja725** [comment]
Will close it for now since it's not priority
