### ISSUE TITLE
Alluxio cluster Cache Hit Rate 's Alluxio Remote = 100 , short-circuit Read is not work ?

### ISSUE THREAD

**Issue by jinhang** [Alluxio/alluxio#11152]
**Alluxio Version:**
2.1.2
**Describe the bug**
Problem:
Alluxio cluster Cache Hit Rate (Alluxio Remote = 100) is not update, short-circuit Read is not work ?

Cache Hit Rate (Percentage):
    Alluxio Local                                            0.00
    Alluxio Remote                                        100
    Miss                                                         0.00
**To Reproduce**

alluxio-site.properties:
alluxio.home=
alluxio.work.dir=
alluxio.conf.dir=${alluxio.home}/conf
alluxio.logs.dir=${alluxio.home}/logs
alluxio.metrics.conf.file=
alluxio.underfs.address=
alluxio.master.bind.host=
alluxio.master.hostname=
alluxio.master.web.bind.host=host-*
alluxio.master.web.hostname=host-*
alluxio.master.web.port=19999
alluxio.master.keytab.file=*
alluxio.master.principal=*
alluxio.worker.keytab.file=*
alluxio.worker.principal=*

alluxio.security.authentication.type=SIMPLE
alluxio.master.security.impersonation.root.users=*
alluxio.worker.memory.size=160GB
alluxio.worker.tieredstore.level0.dirs.path=*
alluxio.worker.tieredstore.level0.dirs.mediumtype=MEM
alluxio.worker.tieredstore.level0.dirs.quota=160GB
alluxio.user.metrics.collection.enabled=true
#alluxio.worker.network.max.inbound.message.size=100MB
#alluxio.user.network.max.inbound.message.size=100MB
alluxio.user.file.passive.cache.enabled=false
# User properties
alluxio.user.file.readtype.default=CACHE_PROMOTE
alluxio.user.file.writetype.default=MUST_CACHE
alluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.DeterministicHashPolicy
alluxio.user.ufs.block.read.location.policy.deterministic.hash.shards=3
alluxio.master.journal.checkpoint.period.entries=10000
alluxio.master.metastore.inode.cache.max.size=31000000
alluxio.locality.compare.node.ip=true

**Expected behavior**
short-circuit Read is work 
**Urgency**
performance is low
**Additional context**
when run:
time ./alluxio runMiniBenchmark -Dalluxio.user.block.write.location.policy.class=alluxio.client.block.policy.LocalFirstPolicy -concurrency 3 -fileSize 100MB -iterations 3 -type READ
Iteration: 0; Duration: 0.323301 seconds; Aggregated throughput: 0.906181 GB/second.
Iteration: 1; Duration: 0.137067 seconds; Aggregated throughput: 2.137414 GB/second.
Iteration: 2; Duration: 0.106042 seconds; Aggregated throughput: 2.762758 GB/second

**Comment by jinhang** [comment]
I also encountered this problem like : https://github.com/Alluxio/alluxio/issues/10110

**Comment by jinhang** [comment]
conf]$ ../sbin/alluxio getConf alluxio.user.metrics.collection.enabled
true

**Comment by apc999** [comment]
MiniBenchmark is deprecated. With Alluxio release 2.7 or later, 
you can use stressbench to test
https://docs.alluxio.io/os/user/stable/en/operation/StressBench.html#client-io-stress-bench
