### ISSUE TITLE
31-03-2020 - Presto queries get stuck infinitely while accessing files from alluxio

### ISSUE THREAD

**Issue by surajc-cuelogic** [Alluxio/alluxio#11223]
**Alluxio Version:**
2.2.0

**Describe the bug**
When data is getting queried from Alluxio using presto, presto worker are getting stuck infinitely. We observed this issue only when we upgraded presto to JDK 11. Normally when we are running alluxio with presto 323(JDK 8) we did not observe this.

**To Reproduce**
We need to run presto with JDK 11 and alluxio 2.2.0. If we query data from alluxio then presto worker gets stucked for infinite time.
**Expected behavior**
Presto worker should not get stuck while accessing data from Alluxio

**Urgency**
We are not able to use presto 323 with JDK 11 with alluxio

**Comment by ZacBlanco** [comment]
hi @surajc-cuelogic 

Can you provide a jstack of the Presto worker(s) which are hanging?

**Comment by apc999** [comment]
ping @surajc-cuelogic  it will be helpful to have jstack threaddump for us to root cause the issue

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
