### ISSUE TITLE
UI does not build

### ISSUE THREAD

**Issue by martenlindblad** [Alluxio/alluxio#11233]
**Alluxio Version:**
2.2.0

**Describe the bug**
```
lerna ERR! npm run build --production  --no-save --no-package-lock --no-shrinkwrap exited 1 in '@alluxio/worker-ui'
lerna ERR! npm run build --production  --no-save --no-package-lock --no-shrinkwrap stdout:

> @alluxio/worker-ui@1.0.0 build /root/alluxio/webui/worker
> NODE_ENV=production && npm-run-all --parallel build-css build-js


> @alluxio/worker-ui@1.0.0 build-css /root/alluxio/webui/worker
> node-sass-chokidar --importer=../node_modules/node-sass-tilde-importer --include-path ./src --include-path ./node_modules src/ -o src/


> @alluxio/worker-ui@1.0.0 build-js /root/alluxio/webui/worker
> react-app-rewired build --scripts-version react-scripts

Rendering Complete, saving .css file...
Wrote CSS to /root/alluxio/webui/worker/src/containers/App/App.css
Rendering Complete, saving .css file...
Wrote CSS to /root/alluxio/webui/worker/src/index.css
Creating an optimized production build...
Failed to compile.

/root/alluxio/webui/worker/src/index.tsx
Type error: Property 'scroll' does not exist on type '{}'.  TS2339

    38 | 
    39 |   // Allow the client to control scroll-to-top using location.state
  > 40 |   if (loc.state && loc.state.scroll !== undefined && !loc.state.scroll) {
       |                              ^
    41 |     return;
    42 |   }
    43 |



lerna ERR! npm run build --production  --no-save --no-package-lock --no-shrinkwrap stderr:
Wrote 2 CSS files to /root/alluxio/webui/worker/src/
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alluxio/worker-ui@1.0.0 build-js: `react-app-rewired build --scripts-version react-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @alluxio/worker-ui@1.0.0 build-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-02T07_25_33_290Z-debug.log
ERROR: "build-js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alluxio/worker-ui@1.0.0 build: `NODE_ENV=production && npm-run-all --parallel build-css build-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @alluxio/worker-ui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-02T07_25_33_306Z-debug.log
```

**To Reproduce**
mvn -T 2C clean package -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Dlicense.skip on FreeBSD 12.1 using node v10.17.0 and npm v6.12.1

**Expected behavior**
Compile!

**Urgency**
No real urgency

**Additional context**

**Comment by ZacBlanco** [comment]
@tieujason330 can you take a look at this?

**Comment by tieujason330** [comment]
@martenlindblad I'm also seeing your issue when I use node v10.17.0. Can you switch to using v10.11.0?

If you have [nvm](https://github.com/nvm-sh/nvm#install--update-script) installed, you can run `nvm install v10.11.0`. When the webui builds, it installs node v10.11.0 locally, but it looks like it doesn't get used if another node version is already installed on the system.

**Comment by martenlindblad** [comment]
> @martenlindblad I'm also seeing your issue when I use node v10.17.0. Can you switch to using v10.11.0?
> 
> If you have [nvm](https://github.com/nvm-sh/nvm#install--update-script) installed, you can run `nvm install v10.11.0`. When the webui builds, it installs node v10.11.0 locally, but it looks like it doesn't get used if another node version is already installed on the system.

I have the same issues with node v10.11.0 and npm 6.4.1 installed via nvm.

**Comment by tieujason330** [comment]
When you installed 10.11.0, did nvm switch to using it? Can you paste what the output of `npm version` is?

ex:
```
$ npm version 

{ npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.33.0',
  node: '10.11.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.0',
  v8: '6.8.275.32-node.28',
  zlib: '1.2.11' }
```

**Comment by martenlindblad** [comment]
```
{ npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.33.0',
  node: '10.11.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.0',
  v8: '6.8.275.32-node.28',
  zlib: '1.2.11' }
```

**Comment by tieujason330** [comment]
Your versions look identical. I haven't used FreeBSD but I'm not sure if that should cause issues. Have you built Alluxio successfully before? Other than version mismatches, I'm not sure what else could be causing that particular error. If you don't need the webui, you can ignore that in the build by adding `-pl !webui`.

If you're able to, can you try building the webui manually (using npm 10.11.0) and seeing if it gives you the same error?
```
cd alluxio/webui
npm run bootstrap --production  --no-save --no-package-lock --no-shrinkwrap
npm run build --production  --no-save --no-package-lock --no-shrinkwrap
```

**Comment by heshan04** [comment]
@tieujason330 hello，i meet the same issue in centos6.  but it can run successfully in macOS.

**Comment by tieujason330** [comment]
thanks guys, i'm not entirely sure why it's complaining for some OSes, but i'll make a minor change to fix this.
