### ISSUE TITLE
Need support for S3 server-side encryption with customer-provided encryption keys (SSE-C)

### ISSUE THREAD

**Issue by tonyye** [Alluxio/alluxio#11236]
**Is your feature request related to a problem? Please describe.**
Need support for S3 server-side encryption with customer-provided encryption keys (SSE-C)

**Describe the solution you'd like**
Be able to set alluxio.underfs.s3.server.side.encryption.key as a configuration parameter and specify an encryption/decryption key to be used when writing and reading data from an S3 object store.

**Describe alternatives you've considered**
None

**Urgency**
I have an on-premise S3 object store which only support SSE-C. Without this feature, I cannot use Alluxio as I require data to be encrypted while at rest.

**Additional context**
None.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
