### ISSUE TITLE
Kerberos principal is not in the right format

### ISSUE THREAD

**Issue by tonyye** [Alluxio/alluxio#11231]
**Alluxio Version:**
2.2.0

**Describe the bug**
I have set up Alluxio with Kerberized HDFS by addition the following to my alluxio-site.properties:
alluxio.master.keytab.file=/some/path/to/keytab/hdfs.keytab
alluxio.master.principal=hhdfs/host11.mydomain.com@CLOUDERA.DEV
alluxio.worker.keytab.file=/some/path/to/keytab/hdfs.keytab
alluxio.worker.principal=hdfs/host11.mydomain.com@CLOUDERA.DEV

I then run "./bin/alluxio validateEnv local" and get the following error:

Validating master.ufs.hdfs.security.kerberos...
Path to server-side hadoop configuration unspecified, skipping validation for HDFS properties.
Principal hhdfs/host11.mydomain.com@CLOUDERA.DEV is not in the right format.
FAILED

**To Reproduce**
Follow the steps described in the description of the bug

**Expected behavior**
Should not get a "Principal hhdfs/host11.mydomain.com@CLOUDERA.DEV is not in the right format." error when running "alluxio validateEnv local"

**Urgency**
N/A

**Additional context**
None

**Comment by ZacBlanco** [comment]
Hi @tonyye . This bug report isn't really helpful to us.

Can you please fill out the issue template? Otherwise I will need to close this issue.

**Comment by tonyye** [comment]
> Hi @tonyye . This bug report isn't really helpful to us.
> 
> Can you please fill out the issue template? Otherwise I will need to close this issue.
I updated the issue with the details.

**Comment by ZacBlanco** [comment]
thanks! someone will take a look shortly.

**Comment by ZacBlanco** [comment]
thanks! someone will take a look shortly

**Comment by jja725** [comment]
@yyongycy do you think this is still valid?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
