### ISSUE TITLE
Hide the protobuf generated code usage into a Helper class

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#11230]
**Is your feature request related to a problem? Please describe.**

Now, i see some proto auto-generated class appear the user-side API, it would be difficult and not graceful to let the user read the auto-generated class. Further more, as a contributor of Alluxio, i still don't want to touch the auto-generated class in the rpc server side.

**Describe the solution you'd like**

I think, we should create some ProtoBufferHelper class as a layer between the human readable class and proto auto-generated class, then, whichever side of rpc, it just call the xxxConvert method in the ProtoBufferHelper class to get the expected object.

**Describe alternatives you've considered**

As it would be some alternatives in the API, we can start this work anytime, but we should keep the legacy api live but with the annotation `Deprecated` the 2.x, removed it in 3.0.

Well, it could be a lot of refactor effort here, but do refactor in a IDE, it does not invoke many human work here.

We can separate this work into some sub task, and do it concurrently.

**Urgency**

Now, many applications use the `alluxio.client.file.FileSystem`, the developer of these applications have to open and read the auto-generated class, and build the instance of it, it is not a kind way.

**Additional context**

Hide the auto-generated class so that limited them into a small layer, few developer maintain it, many developer say bye-bye to these noisy classes.

**Comment by gpang** [comment]
@maobaolong Thanks for this issue! Will the helper classes be auto-generated? My concern would be the maintenance cost of keeping the helper classes consistent with the proto generated classes.

**Comment by maobaolong** [comment]
@gpang Yeah, it will be a little work about keep the consistent between both the auto-generated class and the human readable class with the helper class. But we can still keep the consistent by changes-invoke human mode, for example, if the message of proto change, the author should check the consistent in the helper class. For the other hand, if the human readable class changes, the author should check the helper too, this work well in the hadoop and ozone.

**Comment by maobaolong** [comment]
I think there are 3 way
1. Use proto auto-generated class directly. 
2. With two method fromProto and toProto into a class which could be serialized and deserialized.
3. Define a ProtobufferHelper util class to convert between the human readable classes and generated classes.

Now, in Alluxio repo, the 1 and 2 is used, i think both 2 and 3 is ok, and 3 is better, because it bring the serialized and deserialized away from the main class make the main class clearly. But 1 is a worst way now, it bring the verbose classes to the others who don't want to see them.

So, let's discuss which way we should chose. @gpang

**Comment by ZacBlanco** [comment]
Don't we already have something like this in the `GrpcUtils` class along with the wire types?
https://github.com/Alluxio/alluxio/blob/master/core/common/src/main/java/alluxio/grpc/GrpcUtils.java

It may not be complete, but there is a good number of functions there.

**Comment by maobaolong** [comment]
@ZacBlanco Yeah, Indeed, it's great! It is what i almost expected, and we have a minor refactor work to do, we should rename the function name from `fromProto`, `fromMountEntry`, `toProto` to `convert` or `to` or whatever name it is, but the same name. So that the `GrpcUtils` user no need care about the detail, just use the one magic function, and it prove to let you use the right function by java function reload mechanism.
