### ISSUE TITLE
Write Parquet file using Alluxio Java Client

### ISSUE THREAD

**Issue by achyuthvv** [Alluxio/alluxio#11251]
**Alluxio Version:**
What version of Alluxio are you using?
Alluxio enterprise Version - 2.2.0

**Describe the bug**
I am trying to convert a Text file to a parquet file in java using alluxio client, but not able to find any relevant API.
Is there a way to convert text file to parquet file (based on schema) and write to alluxio.

**Comment by ZacBlanco** [comment]
@achyuthvv Alluxio is agnostic to the format your file is in. It has no concept of Parquet data. It only knows bytes.

Alluxio's client options should allow you to interact with any standard libraries that interface with `java.io.FileInStream` classes. Try looking at this: https://github.com/Parquet/parquet-compatibility/blob/master/parquet-compat/src/test/java/parquet/compat/test/ConvertUtils.java

**Comment by achyuthvv** [comment]
Thanks for the response. I have tried using apache-parquet library to convert to parquet format.
Below is what I used .


```
InstancedConfiguration conf = InstancedConfiguration.defaults();

conf.set(PropertyKey.fromString("alluxio.master.hostname"), hostName);
conf.set(PropertyKey.fromString("alluxio.master.port"), port);
conf.set(PropertyKey.SECURITY_AUTHENTICATION_TYPE, "KERBEROS");
conf.set(PropertyKey.fromString("alluxio.security.kerberos.client.principal"),cliPrincipal);
conf.set(PropertyKey.fromString("alluxio.security.kerberos.client.keytab.file"),cliKeytab);

Configuration mergedConf =
                   HadoopConfigurationUtils.mergeAlluxioConfiguration(new Configuration(),
                           conf);

```

and passing the above configuration to below parquet converter. since builder method is expecting Hadoopfs  Path object, I set my path as path.getPath()
 
 

> AvroParquetWriter.Builder<GenericRecord> parquetWriter = AvroParquetWriter
>                 .<GenericRecord>builder(new Path(path.getPath()))
>                 .withSchema(avroSchema).withConf(mergedConf);
> 
>   final ParquetConfig parquetConfig = createParquetConfig(context, flowFile.getAttributes());
>   applyCommonConfig(parquetWriter, conf, parquetConfig);
>   return new AvroParquetHDFSRecordWriter(parquetWriter.build(), avroSchema);
> 

  I checked the path , but I didn't see the file and when I rerun the same job, it shows the file already exists.
  Am I doing anything wrong/missing here. Please help.

  Thanks.

**Comment by achyuthvv** [comment]
Hi @ZacBlanco ,

When I am specifying the scheme as "alluxio://", it is showing, "no filesystem as alluxio".

After parquet conversion,I am assuming the above code writes to the local file system on master host. 
I am specifying the parquet writer configuration with conf object containing hostname,port, keytab details.
```

AvroParquetWriter.Builder parquetWriter = AvroParquetWriter
.builder(new Path(path.getPath()))
.withSchema(avroSchema).withConf(mergedConf);
```

I would be glad if you can help us with this.

Thanks

**Comment by ZacBlanco** [comment]
You likely need to include the Alluxio HDFS client jar in your applications dependencies, or on the classpath of your application.

See this as an example: https://docs.alluxio.io/os/user/stable/en/compute/Hadoop-MapReduce.html#basic-setup
