### ISSUE TITLE
Reinterpret IOException from HDFS to AlluxioStatusException

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#11263]
**Summary**
Hadoop FileSystem APIs all throw java IOException with exact HDFS level exception embedded as a cause.

Currently, we have a course handling of HDFS exceptions by not looking into cause. This helps us not worry about breaking changes of HDFS, but limits our intelligence in making the right integration choices.

**Comment by jja725** [comment]
This is finished by new AlluxioRuntimeException system.
