### ISSUE TITLE
Implement getDefaultBlockSize(Path f) method

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#11269]
**Alluxio Version:**
2.2.0

**Describe the bug**
Currently on HDFS interface, Alluxio returns one global block size
regardless of file path, which may not be true. In case different 
paths use different HDFS block size, this will cause issues.

```java
  @Override
  public long getDefaultBlockSize() {
    return mFileSystem.getConf()
        .getBytes(PropertyKey.USER_BLOCK_SIZE_BYTES_DEFAULT);
  }
```
**To Reproduce**

**Expected behavior**
Block size should be 
It should be replaced by:
  ```java
    @Override
    public long getDefaultBlockSize(Path path)
    {
      AlluxioURI uri = getAlluxioPath(path);
      try {
        URIStatus status = mFileSystem.getStatus(uri);
        return status.getBlockSizeBytes();
      } catch (AlluxioException | IOException e) {
        throw new RuntimeException(e);
      }
    }
  ```

**Urgency**
Medium

**Additional context**
This  issue is reported and fix proposed by @iAlaska

**Comment by jja725** [comment]
close now since we have page store now
