### ISSUE TITLE
Sync on S3 can set the owner to "" or "_"

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#11266]
**Alluxio Version:**
2.2

**Describe the bug**
S3 does not set owner/group for objects when `inherit_acl=false`. When syncing metadata with s3, an `updateMetadata` sync plan could lead to setting the owner and group to `_` in `DefaultFileSystemMaster::setAttributeSingleFile` or to "" (empty) when updating inode entry during sync

**To Reproduce**
This can be reproduced when a directory is created in alluxio only, the same directory is then later created in the ufs and then synced. 

Steps to reproduce:
```
$ aws s3 ls s3://adit-bucket-west/
                           PRE /
$ afs mkdir /adit
Successfully created directory /adit
$ afs mount /adit/s3a s3a://adit-bucket-west/
Mounted s3a://adit-bucket-west/ at /adit/s3a
$ afs mkdir /adit/s3a/nested
Successfully created directory /adit/s3a/nested
$ aws s3 cp world s3://adit-bucket-west/nested/file
upload: ./world to s3://adit-bucket-west/nested/file
$ afs ls -Dalluxio.user.file.metadata.sync.interval=0 /adit/s3a/nested
-rwx------  _              _                            6       PERSISTED 04-09-2020 22:22:18:000   0% /adit/s3a/nested/file
$ afs ls /adit/s3a/
drwx------  _              _                            1       PERSISTED 04-09-2020 22:22:18:000  DIR /adit/s3a/nested
```

**Expected behavior**
Owner and group inherited from parent dir previously should not be modified.

**Urgency**
Urgent

**Additional context**
N/A

**Comment by ZacBlanco** [comment]
This has been closed by #11257
