### ISSUE TITLE
The light weighted namespace feature for cross-region multi FS cluster.

### ISSUE THREAD

**Issue by copperybean** [Alluxio/alluxio#11276]
As far as I know, Alluxio works very well for the FS cache scenario, especially the combination with Presto, which speeds up the adhoc query significantly. But Alluxio is also famous with its FS namespace functionality, it seems there are little improvement for this feature in recent versions.
**For large companies, it is common that there are many FS clusters in different region**. If one Alluxio cluster in one region is used as the FS namespace for these FS clusters, it will slow down the different region access significantly, especially for the data reading/writing access. By the way, if Alluxio workers are spread in different region, it will be too complicated to manage the workers.

I have some ideas for the cross-region namespace feature.
**Firstly, the worker should be bypassed when reading/writing uncached data**. For the situation that client, worker, UFS are distributed in different regions, the worker will slow down the reading/writing significantly.
**Secondly, master should not record every UFS path**. Currently, the UFS path is recorded automatically once it is accessed. For large companies, there maybe tens of huge HDFS clusters, recording each path is not possible.
**Thirdly, an uniform light weighted privilege model is required**. I proposed an IACL privilege model in [issue 11275](https://github.com/Alluxio/alluxio/issues/11275) for this feature. Further more, all privilege info is also written to UFS directly by default currently. This is not useful and can not be implemented for Object Store like S3. I think all files' privilege in UFS can be set to same as the mount point.

With these features, tens of huge FS clusters can be managed by Alluxio with ignorable performance penalty. I think it is the time to enhance the namespace functionality for Alluxio.

**Comment by jja725** [comment]
now we have cross-cluster sync @tcrain , @copperybean you can contact us if you are interested. Will close it for now
