### ISSUE TITLE
Make Alluxio helm chart configurable for hostNetwork or not

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#11271]
**Alluxio Version:**
2.2.0

**Describe the bug**
The current implementation on Helm chart only supports non-hostnetwork environment: https://github.com/Alluxio/alluxio/commit/4d6126a5d9e03128c01ca73f2a8cad12558e981c

I suggest to make it configurable? the user can decide whether they want hostNetwork or non-hostNetwork. In fact, the network performance is much worse when using non hostNetwork. I

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jiacheliu3** [comment]
After https://github.com/Alluxio/alluxio/commit/4d6126a5d9e03128c01ca73f2a8cad12558e981c when ALLUXIO_WORKER_CONTAINTER_HOSTNAME is set on worker, the connections to worker will use this hostname even if the worker is using `hostNetwork`. I'll apply a small fix to remove ALLUXIO_WORKER_CONTAINTER_HOSTNAME when the workers are using `hostNetwork`.

**Comment by jiacheliu3** [comment]
@cheyang please take a look if #11290 meets your need. Thanks!

**Comment by cheyang** [comment]
@jiacheliu3 Thank you!
