### ISSUE TITLE
ALLUXIO_FUSE_JAVA_OPTS Not take effect

### ISSUE THREAD

**Issue by Binyang2014** [Alluxio/alluxio#11282]
**Alluxio Version:**
2.2.0

**Describe the bug**
deploy alluxio in k8s. Using single master config
https://github.com/Alluxio/alluxio/blob/2529b73c6162e935edfc308cc390559c3911c025/integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template#L40-L41

But  `ALLUXIO_FUSE_JAVA_OPTS` not take effect. According to https://github.com/Alluxio/alluxio/blob/2529b73c6162e935edfc308cc390559c3911c025/integration/fuse/bin/alluxio-fuse#L48
It was overwrite. 

What's the recommend way to set FUSE_OPTS in alluxio?

**Comment by ZacBlanco** [comment]
Hi @Binyang2014 this looks like a bug to me

```bash
 ALLUXIO_FUSE_JAVA_OPTS=${ALLUXIO_JAVA_OPTS} 
```
should probably be

```bash
 ALLUXIO_FUSE_JAVA_OPTS+=" ${ALLUXIO_JAVA_OPTS}"
```

**Comment by apc999** [comment]
@ZacBlanco  I created a PR to address this issue.
@Binyang2014 not sure if you are able to recompile the code but this fix should be available in our nightly docker image build

**Comment by Binyang2014** [comment]
Thanks @apc999 for quick fix.  Will have a try.
