### ISSUE TITLE
Alluxio FileSystem client static resource management

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#11295]
**Summary**
There are `FileSystem` bound resources that do not scale well under concurrent access.
Each file system holds:
 - `EventLoop` instance for use by **any** channel in the system
 -  Alluxio RPC client pools
    * BlockWorkerClient pool
    * FileSystemMaster/BlockMaster pools

There are two concerns:
- Resource Leak: If `FileSystem` is not closed, system resources (fd) held by `EvetLoop`  and some RPC threads will be leaked.
- Concurrency: `FileSystem` level integration will end up every channel having its own event-loop, and will introduce coordination overhead to the whole JVM process. Additionally, being configured per user-conf, reducing the total count of pooled RPC clients will introduce a fairness problem and possible starvation to the critical operations.

Alluxio static resource management should provide JVM level pools for mentioned resources.

**Urgency**
To efficiently work with applications that do `FileSystem` level access

**Comment by ZacBlanco** [comment]
@ggezer is this fixed now? If so, can we link the PR(s)?

**Comment by ggezer** [comment]
Partly. Client pools need to go through a similar procedure as connections did.

**Comment by jja725** [comment]
Will close it for now and reconsider resource management during redesign
