### ISSUE TITLE
Add parquet catalog in Alluxio catalog service

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#11303]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Alluxio add presto under catalog type that make parquet file which stored in Alluxio as a table just like Spark

**Urgency**
There is a big demand that users want to do some ad-hoc on presto with data produced by spark.
Now they need  create table in hive first and sync metastore in Alluxio. This mode is complex and not useful, because there are thousands of "tables" and some of them are temporary. It make a big sense users can simply use presto reading parquet data stored in alluxio.

**Comment by apc999** [comment]
@gpang can you take a look at this? thanks

**Comment by JySongWithZhangCe** [comment]
> @gpang can you take a look at this? thanks

Thx:）

**Comment by jja725** [comment]
catalog service is deprecated
