### ISSUE TITLE
Upgrade from Helm 2 to Helm 3

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11319]
**Is your feature request related to a problem? Please describe.**
Helm 3 has a lot of great improvements from Helm 2. https://helm.sh/docs/faq/

We decided to change from Helm 2 to 3. One big factor is that Helm 3 removed Tiller, which makes the management a lot simpler, especially in security and access control perspective.

Helm 3 is not backward compatible. Some Helm calls we are currently using in `helm-generate.sh` and in the document are no longer valid.

**Describe the solution you'd like**
We are upgrading to use Helm 3 in future Alluxio versions and removing Helm 2 from our stack and docs.

**Describe alternatives you've considered**

**Urgency**
MEDIUM

**Additional context**

**Comment by ZacBlanco** [comment]
Related to https://github.com/Alluxio/alluxio/issues/10956

**Comment by jiacheliu3** [comment]
Addressed by #11324
