### ISSUE TITLE
nosasl cause alluxio master no working

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#11329]
**Alluxio Version:**
2.2.0

**Describe the bug**
presto query shows :
failed to list directory: alluxio://ip:port/xxxx

**To Reproduce**
1. alluxio-site.properties
alluxio.master.hostname=30.105.22.146
alluxio.master.embedded.journal.addresses=30.105.22.147:19200,30.105.22.146:19200
alluxio.master.mount.table.root.ufs=hdfs://CNSH431627:8020
alluxio.security.authentication.type=NOSASL

2. prestodb + catalog service
execute a query:
select count(*) from hivedemo1.emp5;

3. master printed the log:
2020-04-22 16:36:43,508 WARN  FileSystemMasterClientServiceHandler - Exit (Error): ListStatus: request: path: "/user/hive/warehouse/hivedemo1.db/emp5"
options {
  loadMetadataType: ONCE
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: DELETE
  }
}
, Error=alluxio.exception.AccessControlException: Authentication is not enabled

4. alluxio version :
 community 2.2.0
presto-hive-alluxio-connector  version: 
enterprice-2.2.0-1.0

**Comment by ZacBlanco** [comment]
Did you set `alluxio.security.authentication.type=NOSASL` on the client side as well as on the masters and workers?

Clients need to be aware of the authentication type before connecting. See our documentation on how to configure alluxio properties for presto

https://docs.alluxio.io/os/user/stable/en/compute/Presto.html#customize-alluxio-user-properties

**Comment by apc999** [comment]
can you also run 
```
./bin/alluxio logLevel \
--logName=alluxio.master.file.FileSystemMasterClientServiceHandler \
--target master --level=DEBUG
```
to enable more details in the error log? It will help us locate the exception

@ZacBlanco  the same error message `Authentication is not enabled` is used by multiple different methods when throwing exception for different reasons. it is pretty hard to tell where really is the origin of this exception if we have only the error message. Shall we target to change this pattern ?
