### ISSUE TITLE
integrate with presto error

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#11323]
**Alluxio Version:**
2.2.0

**Describe the bug**
alluxio cannot visit hdfs 

**To Reproduce**
1. i set up alluxio cluster with raft-based embedded journal according to the wiki 
https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-a-HA-Cluster.html
2. then i config presto to query alluxio according to the wiki 
https://docs.alluxio.io/os/user/stable/en/core-services/Catalog.html
3. when i query with presto like "select count(*) from db.table"
the error message is :
Query 20200421_120646_00011_77kp4 failed: Failed to list directory: alluxio://30.1.2.17:19998,30.5.2.16:19998/catalog/hivedemo1/tables/source_table_40x_cols/hive

**Expected behavior**
alluxio should visit the hdfs to read data, and cache the data at alluxio works's ram

**Additional context**
should i config alluxio according to wiki below to use presto to query hive table?
https://docs.alluxio.io/os/user/stable/en/ufs/HDFS.html

**Comment by ZacBlanco** [comment]
Please provide more information on the failure.

Your presto logs should have more detailed information.
