### ISSUE TITLE
prestodb-hive-alluxio-227  is free to use? or i need to buy Enterprise Edition to use prestodb-hive-alluxio-227?

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#11322]
prestodb-hive-alluxio-227  is free to use? or i need to buy Enterprise Edition to use prestodb-hive-alluxio-227?

i came from https://docs.alluxio.io/os/user/stable/en/core-services/Catalog.html

**Comment by ZacBlanco** [comment]
When you download a release from https://alluxio.io/download the tarball will contain the connector under the `client` subdirectory
