### ISSUE TITLE
Incomplete Docker Image Documentation

### ISSUE THREAD

**Issue by pedersen** [Alluxio/alluxio#11352]
**Page**
https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html

**Summary**
Two environment variables are not documented, and have negative impact when running Alluxio purely as a local disk cache via docker containers.

* ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH
* ALLUXIO_RAM_FOLDER

If neither of these environment variables is set, and the docker container is run, then the configuration of your `level0` storage tier becomes irrelevant. It will be configured to use `/dev/shm` no matter what is put in for 

```
alluxio.worker.tieredstore.level0.alias=HDD
alluxio.worker.tieredstore.level0.dirs.mediumtype=HDD
alluxio.worker.tieredstore.level0.dirs.path=/opt/alluxio/cache
alluxio.worker.tieredstore.level0.dirs.quota=1024GB
```
In this case, if your docker container cannot address 1T of RAM in /dev/shm, your entire environment will fail to even start. Having those variables documented correctly will ensure that others do not have issues when trying to configure a pure disk cache via Alluxio and docker containers.

**Comment by jja725** [comment]
@ssz1997 is this still valid? otherwise help me close this please

**Comment by ssz1997** [comment]
ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIR_PATH is not used any more. Close this issue.
