### ISSUE TITLE
Support alluxio on emr 6.0.0

### ISSUE THREAD

**Issue by igreenfield** [Alluxio/alluxio#11378]
For now can use it seems like incompatible jar versions:

[root@ip-172-31-38-87 presto]# grep HivePlanOptimizerProvider *
launcher.log:[Loaded com.facebook.presto.hive.rule.HivePlanOptimizerProvider from file:/usr/lib/presto/plugin/hive-alluxio/presto-hive-0.227.jar]
launcher.log:[Loaded com.facebook.presto.hive.rule.HivePlanOptimizerProvider$$FastClassByGuice$$a07b4ab1 from file:/usr/lib/presto/plugin/hive-alluxio/presto-hive-0.227.jar]
launcher.log:[Loaded com.facebook.presto.hive.rule.HivePlanOptimizerProvider from file:/usr/lib/presto/plugin/hive-hadoop2/presto-hive-0.230.jar]
launcher.log:[Loaded com.facebook.presto.hive.rule.HivePlanOptimizerProvider$$FastClassByGuice$$a07b4ab1 from file:/usr/lib/presto/plugin/hive-hadoop2/presto-hive-0.230.jar]

**Comment by jja725** [comment]
@Xenorith is this still valid? otherwise help me close this please

**Comment by Xenorith** [comment]
we currently do not plan on maintaining support of the EMR bootstrap scripts for newer versions for EMR
