### ISSUE TITLE
lastAccessTimeMs and creationTimeMs transposed in REST Api

### ISSUE THREAD

**Issue by pedersen** [Alluxio/alluxio#11397]
**Alluxio Version:** 2.1.2

**Describe the bug**
When using the REST Api Proxy, the values for `lastAccessTimeMs` and `creationTimeMs` appear to be transposed with each other in a `list_status` call.

**To Reproduce**
`curl -d '' -H 'Content-Type: application/json' http://<RESTAPIPROXY>:39999/api/v1/paths/<FILENAME>/list-status >out.json`

out.json will now contain something like this:
`{'owner': 'root', 'lastAccessTimeMs': 1560288128615, 'defaultAcl': {'owner': 'root', 'owningGroup': 'wheel', 'stringEntries': []}, 'acl': {'owner': 'root', 'owningGroup': 'wheel', 'stringEntries': ['user::rwx', 'group::r-x', 'other::r-x']}, 'group': 'wheel', 'completed': True, 'folder': True, 'fileBlockInfos': [], 'ufsPath': 'BLOCKED_OUT', 'mountId': 1, 'persisted': True, 'persistenceState': 'PERSISTED', 'replicationMin': 0, 'blockIds': [], 'creationTimeMs': 1587485323746, 'inMemoryPercentage': 0, 'inAlluxioPercentage': 0, 'lastModificationTimeMs': 1560288128615, 'ttlAction': 'DELETE', 'cacheable': False, 'pinnedMediumTypes': [], 'mountPoint': False, 'ufsFingerprint': '', 'ttl': -1, 'fileId': 16777216323, 'mode': 493, 'replicationMax': 0, 'pinned': False, 'blockSizeBytes': 0, 'length': 0, 'name': 'partitions', 'path': '/partitions'}`

A `lastAccessTimeMs` of 1560288128615 corresponds to 2019-06-11-17:22:08 while `creationTimeMs` of 1587485323746 corresponds to 2020-04-21-12:08:43. Pretty impossible to have a file last accessed almost a year before it was created :)

**Expected behavior**
When I checked the UFS, I found those two items had been transposed by the REST Api.

**Urgency**
Not high urgency. Since we're using Alluxio-py, I can modify that (locally of course) to reference that if I really had to. However, lastModificationTimeMs is close enough for our purposes, so we're using that instead for now.

**Comment by ZacBlanco** [comment]
Hi @pedersen, If you can still reproduce this I have one question.

If you run `alluxio fs stat` on the same path that you've tried to access via the REST API, does it still return the values improperly? This can help diagnose where they are being switched.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
