### ISSUE TITLE
Make Alluxio as UFS of Alluxio

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#11412]
**Is your feature request related to a problem? Please describe.**

Now, Alluxio can mount so many kind of ufs to alluxio united namespace, but it hard to mount some same kind ufs into alluxio, for example, Alluxio support tencent COS as its ufs, and we can mount a cos bucket to a mountpoint of Alluxio, but if you want to mount two COS bucket with different credential, maybe it is not easy. Many HDFS cluster with different version has the same issue. So if we can support mount more than one Alluxio with different config as ufs, and we can mount them to the root Alluxio namespace, it make many thing easier.

**Describe the solution you'd like**

Make Alluxio as UFS of Alluxio, Support different mount point with different config

**Describe alternatives you've considered**

Add a new module under UFS module.

**Urgency**

Normal

**Additional context**
Its cool if we impl it.

**Comment by ZacBlanco** [comment]
If you are looking to add different configurations for different mount points, that it already possible with the `alluxio fs mount` command: https://docs.alluxio.io/os/user/stable/en/core-services/Unified-Namespace.html#mount-ufs-with-specific-versions

From the link:

> Nested Mount Points
> In addition to the root mount point, other under file systems can be mounted into Alluxio namespace by using the mount command. The --option flag allows the user to pass additional parameters to the mount operation, such as credentials.

```console
$ ./bin/alluxio fs mount /mnt/hdfs hdfs://host1:9000/data/
$ ./bin/alluxio fs mount \
  --option aws.accessKeyId=<accessKeyId> --option aws.secretKey=<secretKey> \
  /mnt/s3 s3://data-bucket/
```

**Comment by jinhang** [comment]
Its cool if we impl it.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
