### ISSUE TITLE
Support properties toCacheAvoidEviction for asyncing cache block in the local worker

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#11416]
**Is your feature request related to a problem? Please describe.**

By default, the data will be cached into the local worker, and it will invoke cache eviction in the local worker. 

**Describe the solution you'd like**

I'd like add the properties `toCacheAvoidEviction`, and it will check if the cache capacity of the local worker has reached low water mark. If it's less than low water mark, it will cache. Otherwise it won't cache in localworker.

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by ggezer** [comment]
@cheyang, watermark based eviction is no longer used in the master branch. Eviction will not be triggered until the worker storage is fully utilized.

Would that partially solve your problems?

**Comment by jiacheliu3** [comment]
> @cheyang, watermark based eviction is no longer used in the master branch. Eviction will not be triggered until the worker storage is fully utilized.
> 
> Would that at least partially solve your problems?

Per discussion with @cheyang, the intention is to avoid local caching to prevent eviction whenever possible. Basically the overhead of triggering eviction outweighs the benefit of having one more local copy. 

However, not having watermark based eviction will definitely change our approach to achieve this goal. @ggezer Could you link the PR that removed watermark?

**Comment by ggezer** [comment]
https://github.com/Alluxio/alluxio/pull/11129

**Comment by ggezer** [comment]
There has been many changes in this area that should prevent mentioned problems.
@cheyang Please reopen if you think this is still an issue.
