### ISSUE TITLE
Alluxio Java Client FileSystem mount  called  widthout mount options

### ISSUE THREAD

**Issue by cammette** [Alluxio/alluxio#11427]
**Alluxio Version:**
v2.2

**Describe the bug**
call the Java Client FileSystem mount with mount options，but alluxio master can not recieve the options，alluxio.client.file.DelegatingFileSystem call incorrect method?
```
@Override
  public void mount(AlluxioURI alluxioPath, AlluxioURI ufsPath, MountPOptions options)
      throws IOException, AlluxioException {
    mDelegatedFileSystem.mount(alluxioPath, ufsPath);
 }
```

**Comment by ZacBlanco** [comment]
@apc999 this looks like an issue only when the local cache is enabled

**Comment by jja725** [comment]
it's fixed in newer version.
