### ISSUE TITLE
Permission Denied while creating table on Alluxio with supergroup user.

### ISSUE THREAD

**Issue by lxqfy** [Alluxio/alluxio#11445]
**Alluxio Version:**
2.2.1

**Describe the bug**
- Got exceptions while creating tables with Presto
```
I failed to create table in the following case:Query 20200515_055447_00008_q2ruu failed: java.security.AccessControlException: Permission denied: user=presto, path="alluxio://10.130.11.81:19998/projects/test":hdfs:hadoop:drwxrwxr-x
```
- I create the table from scratch with Alluxio path. (actually copying schema from another table)
- The Presto user is presto, it is in supergroup of HDFS. No permission issue if it is an HDFS path.
- If I create the table on Hive with `hdfs` (owner), the table can be created. When query on Presto, there is no data returned, and files are not loaded to Alluxio. If I manually load those files, still no data returned on Presto
-  If I change the ownership of the directory to `presto` , I am able to create table and the data can be automatically loaded to Alluxio and returned.

- Got following warnings during Alluxio startup (might not be related)
```
2020-05-14 19:22:30,836 WARN  HdfsUnderFileSystem - Cannot create SupportedHdfsAclProvider. HDFS ACLs will not be supported.
2020-05-14 19:22:31,548 WARN  NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-05-14 19:22:31,554 WARN  DomainSocketFactory - The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
```

**To Reproduce**
Create a table with an HDFS supergroup account(e.g. `presto`) on a path without ownership (e.g. `hdfs:hadoop:drwxrwxr-x`)

**Expected behavior**

- Be able to create table without any issue
- Data can be automatically loaded to Alluxio and returned while querying

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jja725** [comment]
Hi @lxqfy sorry for the late response, is this still a valid issue? I think it should be resolved in newer version. Feel free to reopen it if it's not resolved.
