### ISSUE TITLE
Active Sync: Presto query stuck at querying old file after overwriting files directly on HDFS

### ISSUE THREAD

**Issue by lxqfy** [Alluxio/alluxio#11446]
**Alluxio Version:**
2.2.1

**Describe the bug**
`bin/alluxio fs startSync /user/hive/warehouse/test.db/xiangqun_test5`
After enabling active sync, every time after I overwrite the above folder, the query will be stuck for a few minutes getting the old file(the deteled file) and raise error as follows:
```
Error opening Hive split alluxio://10.130.11.81:19998/user/hive/warehouse/test.db/xiangqun_test5/part-00000-abb0bba1-341e-49f9-b6aa-fe0a6fa03d05-c000.snappy.parquet (offset=0, length=756): Failed to read block ID=83886080000 from tiered storage and UFS tier: File does not exist
```

**To Reproduce**
- Create a table with a folder.
- Enable active sync for that path
- Overwrite the folder directly on HDFS with e.g. spark.
- Query the table.

**Expected behavior**
Query returns the updated data without duplications or errors.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by yuzhu** [comment]
Thanks for filing the issue to help us track this better. 

Could you also attach your presto configuration, specifically your hive connector config?

**Comment by lxqfy** [comment]
```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://metastore_server:9083

hive.metastore.username=presto
hive.metastore.user.rpcpassword=******

hive.max-initial-splits=300
hive.max-initial-split-size=64MB
hive.max-split-size=128MB
hive.max-outstanding-splits=1000
hive.max-outstanding-splits-size=1GB
hive.max-split-iterator-threads=1000
hive.metastore-timeout=1m
hive.metastore.partition-batch-size.min=20
hive.metastore.partition-batch-size.max=200
hive.config.resources=/etc/presto/core-site.xml,/etc/presto/hdfs-site.xml
hive.dfs-timeout=1m
hive.dfs.connect.timeout=30s
hive.storage-format=PARQUET
hive.compression-codec=SNAPPY
hive.parquet.use-column-names=true
hive.parquet.fail-on-corrupted-statistics=false
hive.non-managed-table-writes-enabled=true
hive.table-statistics-enabled=true
hive.ignore-corrupted-statistics=true

hive.security=file
security.config-file=/etc/presto/rules.json
security.refresh-period=5m
```

**Comment by jja725** [comment]
Hi @lxqfy sorry for the late response, is this still a valid issue? I think it should be resolved in newer version. Feel free to reopen it if it's not resolved.
