### ISSUE TITLE
Data locality is not working well on K8s

### ISSUE THREAD

**Issue by cyliu0204** [Alluxio/alluxio#11450]
**Alluxio Version:**
2.2.0

**Describe the bug**
  We submit two spark on K8S  wordcount jobs which share the same piece of data, and the data  was stored in remote Ceph S3 object store;
  After the first job finished, the data was actually already cached in alluxio worker node, but the second job's  task data locality in sparkUI is still ANY which seems not reasonable to me, please take a look at this;

spark job conf:
![image](https://user-images.githubusercontent.com/11987690/82295548-7a325900-99e2-11ea-8e69-0d435a95952c.png)

after the second job finished, the domain socket nubmer grows:
![image](https://user-images.githubusercontent.com/11987690/82295729-c54c6c00-99e2-11ea-9dad-346b75094522.png)

the cached data:
![image](https://user-images.githubusercontent.com/11987690/82295786-d9906900-99e2-11ea-91fc-4032f0e65a9c.png)

two spark job metrics:
![image](https://user-images.githubusercontent.com/11987690/82295976-1cead780-99e3-11ea-995b-8d40a18d2fe4.png)

![image](https://user-images.githubusercontent.com/11987690/82296029-2a07c680-99e3-11ea-8b0d-053f4d081c6c.png)

![image](https://user-images.githubusercontent.com/11987690/82296390-b4e8c100-99e3-11ea-95ef-5cf632e362f0.png)

**To Reproduce**
spark 2.4.3  k8s 1.14.9  alluxio 2.2.0  

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jja725** [comment]
@ssz1997 seems like this is still valid issue?

**Comment by ssz1997** [comment]
@cyliu0204 Please try a newer version of Alluxio and see if it's still a problem. If the problem persists, feel free to reopen and update this issue or create a new one. Close this noe for now.
