### ISSUE TITLE
Client requestion timeout when evicting worker cache 

### ISSUE THREAD

**Issue by dingye2020** [Alluxio/alluxio#11465]
**Alluxio Version:**
2.2.0

**Describe the bug**
when the WORKER cache is reach the high watermark, the CLIENT requestions is blocked and return timeout.

**To Reproduce**
1. restart the alluxio to make a clean alluxio
2. Use Vdbench to read form ufs , then WORKER will aync cache the data
3. when the WORKER'cache  hit high watermark, the client ops is 0
4. the client ops is recover when the evict of WORKER cache is done.

**Urgency**
Senior

**Additional context**
I doubt that sync worker block info between worker and master block the grpc message( port?)

![E99FF892-40DB-4a69-AED6-5A017DFFA48C](https://user-images.githubusercontent.com/63621540/82648789-ce3f7680-9c4a-11ea-8a74-3dab30f96edf.png)

**Comment by dingye2020** [comment]
my benchmark
vdbench:
fsd=fsd1,anchor=/mnt/alluxio-fuse/testdir100w,depth=1,width=1,files=1000000,sizes=(64k,15,128k,15,512k,20,1M,20,5M,15,32K,15)
fwd=fwd1,fsd=fsd1,operation=read,xfersize=4K,fileio=sequential,fileselect=sequential,threads=16
rd=rd1,fwd=fwd1,fwdrate=max,format=no,elapsed=20000,interval=1

**Comment by dingye2020** [comment]
bc my test lots of small files( 1 million) , there are many blocks (10k+) need to be sync when evicting. if i divide the blocks that tobe sync to many batches , and include some delay (eg 10ms) for send ,  this problem is relieve.

**Comment by jja725** [comment]
we will redesign the tier management, Will close it for now, feel free to reopen it and contact us if this is a strong request.
