### ISSUE TITLE
client I/O suspended when enable client metadata cache

### ISSUE THREAD

**Issue by dingye2020** [Alluxio/alluxio#11475]
**Alluxio Version:**
2.2.0

**Describe the bug**
client I/O is suspended when enable client metadata cache.

**To Reproduce**
1. start the alluxio with enable client metadata cache
2.use vdbench to read file sequentially
3. when run abount 8000 second , the ops become 0
4. read file manually suppend  too.

**Expected behavior**
normal

**Urgency**
S

**Additional context**
1.  i think it suspended at READ operation。 when i CAT one file , i got the follow trace:
[root@node01 alluxio]# strace cat /mnt/alluxio-fuse/dingye100w_3/vdb.1_1.dir/vdb_f0001.file >/dev/null
execve("/usr/bin/cat", ["cat", "/mnt/alluxio-fuse/dingye100w_3/v"...], [/* 27 vars */]) = 0
brk(NULL)                               = 0xe31000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efd35059000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=49065, ...}) = 0
mmap(NULL, 49065, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7efd3504d000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P%\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2173512, ...}) = 0
mmap(NULL, 3981792, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7efd34a6c000
mprotect(0x7efd34c2f000, 2093056, PROT_NONE) = 0
mmap(0x7efd34e2e000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c2000) = 0x7efd34e2e000
mmap(0x7efd34e34000, 16864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7efd34e34000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efd3504c000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efd3504a000
arch_prctl(ARCH_SET_FS, 0x7efd3504a740) = 0
mprotect(0x7efd34e2e000, 16384, PROT_READ) = 0
mprotect(0x60b000, 4096, PROT_READ)     = 0
mprotect(0x7efd3505a000, 4096, PROT_READ) = 0
munmap(0x7efd3504d000, 49065)           = 0
brk(NULL)                               = 0xe31000
brk(0xe52000)                           = 0xe52000
brk(NULL)                               = 0xe52000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=106070960, ...}) = 0
mmap(NULL, 106070960, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7efd2e543000
close(3)                                = 0
fstat(1, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 3), ...}) = 0
open("/mnt/alluxio-fuse/dingye100w_3/vdb.1_1.dir/vdb_f0001.file", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0700, st_size=16384, ...}) = 0
fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
read(3, 

2.  vdbench output:
21:42:29.043       8409 6508.0  4.687  14.9 4.77 100.0 6508.0  4.687    0.0  0.000 25.42  0.00  25.42    4096   0.0  0.000   0.0  0.000   0.0  0.000  1692  0.371  1693  0.171   0.0  0.000
21:42:30.043       8410 7568.0  4.218  22.2 7.62 100.0 7568.0  4.218    0.0  0.000 29.56  0.00  29.56    4096   0.0  0.000   0.0  0.000   0.0  0.000  2017  0.511  2017  0.311   0.0  0.000
21:42:31.044       8411 4291.0  4.122  20.8 8.63 100.0 4291.0  4.122    0.0  0.000 16.76  0.00  16.76    4096   0.0  0.000   0.0  0.000   0.0  0.000  1155  0.755  1154  0.263   0.0  0.000
21:42:32.043       8412  11503  3.699  22.3 7.69 100.0  11503  3.699    0.0  0.000 44.93  0.00  44.93    4096   0.0  0.000   0.0  0.000   0.0  0.000  3066  0.638  3070  0.113   0.0  0.000
21:42:33.044       8413  10672  2.690  27.2 8.77 100.0  10672  2.690    0.0  0.000 41.69  0.00  41.69    4096   0.0  0.000   0.0  0.000   0.0  0.000  2797  0.772  2798  0.098   0.0  0.000
21:42:34.044       8414 1063.0  5.707   6.4 1.16 100.0 1063.0  5.707    0.0  0.000  4.15  0.00   4.15    4096   0.0  0.000   0.0  0.000   0.0  0.000 293.0  2.600 288.0  1.249   0.0  0.000
21:42:35.047       8415    0.0  0.000   0.5 0.16   0.0    0.0  0.000    0.0  0.000  0.00  0.00   0.00       0   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000
21:42:36.044       8416    0.0  0.000   3.5 2.36   0.0    0.0  0.000    0.0  0.000  0.00  0.00   0.00       0   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000
21:42:37.045       8417    0.0  0.000   1.3 0.60   0.0    0.0  0.000    0.0  0.000  0.00  0.00   0.00       0   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000
21:42:38.047       8418    0.0  0.000   3.2 1.95   0.0    0.0  0.000    0.0  0.000  0.00  0.00   0.00       0   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000

3.  i have 1 million files under same directory. 
4. the client metadata cache configuration is :
alluxio.user.metadata.cache.enabled=true
alluxio.user.metadata.cache.max.size=2000000
alluxio.user.metadata.cache.expiration.time=30m

**Comment by apc999** [comment]
alluxio fuse was reimplemented now using JNIFuse to overcome original limitations with JNRFuse, please try versions after 2.6.
