### ISSUE TITLE
chown -R on Alluxio 2.2.1 does not change all child inodes owner/group

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#11474]
**Alluxio Version:**
What version of Alluxio are you using?
2.2.1
**Describe the bug**
chown -R can not change all subdir or file to correct user/group
**To Reproduce**
use alluxio fs chown -R user:group /path command to change /path owner
where will be 4 combination in subdir and file:
user_new:group_new
user_old:group_old
user_new:group_old
user_old:group_new
and which user/group will a subdir or path belong can not predict

there are no log even in debug mode

**Comment by jiacheliu3** [comment]
I had a session with @JySongWithZhangCe and confirmed on the above behavior.

The directory is not too deeply nested but pretty large each. We tried an example like /A/B1~100/C1~1000 where we did `alluxio fs -R new_user:new_group /A`. And we had the below observations:

1. This is very likely a regression. @JySongWithZhangCe 's team upgraded from 2.1 to 2.2.1 and immediately had this issue. Their team performs chown operations very frequently and they should be able to identify the same issue had it existed in 2.1. @JySongWithZhangCe can you please confirm on the open source version of Alluxio which is verified to be fine?

1. ALL the direct children (B1 ~ B100) are correctly updated. 

1. Many grand children are not successfully updated and end in one of the 4 combinations. 

1. As far as we observe, ALL the children in one particular directory are in one user:group combination. @JySongWithZhangCe can you please confirm on this?

1. The call took only a few seconds to complete and completed successfully. We found no logs on master or client side regarding this chown operation.

**Comment by JySongWithZhangCe** [comment]
> I had a session with @JySongWithZhangCe and confirmed on the above behavior.
> 
> The directory is not too deeply nested but pretty large each. We tried an example like /A/B1-100/C1-1000 where we did `alluxio fs -R new_user:new_group /A`. And we had the below observations:
> 
> 1. This is very likely a regression. @JySongWithZhangCe 's team upgraded from 2.1 to 2.2.1 and immediately had this issue. Their team performs chown operations very frequently and they should be able to identify the same issue had it existed in 2.1. @JySongWithZhangCe can you please confirm on the open source version of Alluxio which is verified to be fine?
> 2. ALL the direct children (B1 ~ B100) are correctly updated.
> 3. Many grand children are not successfully updated and end in one of the 4 combinations.
> 4. As far as we observe, ALL the children in one particular directory are in one user:group combination. @JySongWithZhangCe can you please confirm on this?
> 5. The call took only a few seconds to complete and completed successfully. We found no logs on master or client side regarding this chown operation.

>1. All Alluxio version used before did right work in this case, which are 1.7.0, 1.7.1, 1.8.1, 1.8.2, 2.1.1
>4.Yes

**Comment by JySongWithZhangCe** [comment]
> > I had a session with @JySongWithZhangCe and confirmed on the above behavior.
> > The directory is not too deeply nested but pretty large each. We tried an example like /A/B1-100/C1-1000 where we did `alluxio fs -R new_user:new_group /A`. And we had the below observations:
> > 
> > 1. This is very likely a regression. @JySongWithZhangCe 's team upgraded from 2.1 to 2.2.1 and immediately had this issue. Their team performs chown operations very frequently and they should be able to identify the same issue had it existed in 2.1. @JySongWithZhangCe can you please confirm on the open source version of Alluxio which is verified to be fine?
> > 2. ALL the direct children (B1 ~ B100) are correctly updated.
> > 3. Many grand children are not successfully updated and end in one of the 4 combinations.
> > 4. As far as we observe, ALL the children in one particular directory are in one user:group combination. @JySongWithZhangCe can you please confirm on this?
> > 5. The call took only a few seconds to complete and completed successfully. We found no logs on master or client side regarding this chown operation.
> 
> > 1. All Alluxio version used before did right work in this case, which are 1.7.0, 1.7.1, 1.8.1, 1.8.2, 2.1.1
> > 4.Yes

**Comment by JySongWithZhangCe** [comment]
> > > I had a session with @JySongWithZhangCe and confirmed on the above behavior.
> > > The directory is not too deeply nested but pretty large each. We tried an example like /A/B1-100/C1-1000 where we did `alluxio fs -R new_user:new_group /A`. And we had the below observations:
> > > 
> > > 1. This is very likely a regression. @JySongWithZhangCe 's team upgraded from 2.1 to 2.2.1 and immediately had this issue. Their team performs chown operations very frequently and they should be able to identify the same issue had it existed in 2.1. @JySongWithZhangCe can you please confirm on the open source version of Alluxio which is verified to be fine?
> > > 2. ALL the direct children (B1 ~ B100) are correctly updated.
> > > 3. Many grand children are not successfully updated and end in one of the 4 combinations.
> > > 4. As far as we observe, ALL the children in one particular directory are in one user:group combination. @JySongWithZhangCe can you please confirm on this?
> > > 5. The call took only a few seconds to complete and completed successfully. We found no logs on master or client side regarding this chown operation.
> > 
> > 
> > > 1. All Alluxio version used before did right work in this case, which are 1.7.0, 1.7.1, 1.8.1, 1.8.2, 2.1.1
> > >4.Yes

**Comment by madanadit** [comment]
@JySongWithZhangCe can you reproduce this issue with a single entry at each level, i.e., the tree is  `/A/B/C` and then `alluxio fs chown -R new_user:new_group /A`?

**Comment by madanadit** [comment]
This is how I tried to reproduce
```
(base) ➜  alluxio git:(master) ✗ for i in $(seq 1 10); do for j in $(seq 1 10); do afs mkdir /a/b${i}/c${j}; done; done
(base) ➜  alluxio git:(master) ✗ afs ls /a/b8/
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:53:53:706  DIR /a/b8/c1
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:54:03:785  DIR /a/b8/c10
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:53:54:826  DIR /a/b8/c2
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:53:55:956  DIR /a/b8/c3
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:53:57:073  DIR /a/b8/c4
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:53:58:185  DIR /a/b8/c5
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:53:59:301  DIR /a/b8/c6
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:54:00:432  DIR /a/b8/c7
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:54:01:545  DIR /a/b8/c8
drwxr-xr-x  adit           staff                        0   NOT_PERSISTED 06-03-2020 08:54:02:666  DIR /a/b8/c9
(base) ➜  alluxio git:(master) ✗ afs chown -R root:wheel /a
Changed owner:group of /a to root:wheel.
(base) ➜  alluxio git:(master) ✗ afs ls /a/b8/
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:53:53:706  DIR /a/b8/c1
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:54:03:785  DIR /a/b8/c10
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:53:54:826  DIR /a/b8/c2
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:53:55:956  DIR /a/b8/c3
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:53:57:073  DIR /a/b8/c4
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:53:58:185  DIR /a/b8/c5
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:53:59:301  DIR /a/b8/c6
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:54:00:432  DIR /a/b8/c7
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:54:01:545  DIR /a/b8/c8
drwxr-xr-x  root           wheel                        0   NOT_PERSISTED 06-03-2020 08:54:02:666  DIR /a/b8/c9
(base) ➜  alluxio git:(master) ✗ afs ls /a/
drwxr-xr-x  root           wheel                        1   NOT_PERSISTED 06-03-2020 08:32:56:399  DIR /a/b
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:52:44:824  DIR /a/b1
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:54:27:836  DIR /a/b10
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:52:56:375  DIR /a/b2
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:53:07:523  DIR /a/b3
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:53:18:761  DIR /a/b4
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:53:30:055  DIR /a/b5
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:53:41:259  DIR /a/b6
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:53:52:577  DIR /a/b7
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:54:03:785  DIR /a/b8
drwxr-xr-x  root           wheel                       10   NOT_PERSISTED 06-03-2020 08:54:16:577  DIR /a/b9
```

**Comment by HelloHorizon** [comment]
@JySongWithZhangCe I am trying to reproduce this issue from our side. I assume /a /b and /c are all directories. Is there any possible for me to know the estimated number of files under each directory?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
