### ISSUE TITLE
Performance gap between Alluxio fuse and Java client

### ISSUE THREAD

**Issue by Binyang2014** [Alluxio/alluxio#11477]
**Summary**
Seems there is performance gap between Alluxio fuse and Java client.
I do some tests in my own machine. The test process is:

1. Load one 100 GB file into alluxio (avoid massive open operations)
2. Use java client random read 128KB data from the file (with random offset, using 64 threads)
3. Use Fuse and a python script to random read 128 KB data from the file (with random offset, using 64 processes)

For both java client and fuse, the read count is 1000000 (122GB). And the results is:

                 | Consume time     | Speed         |
-----------  | -------------------| ------------  |
Java client | 129.143 seconds  | 968MB/s     |
Fuse client | 507.190 seconds | 246MB/s      |

Seems for massive read requests, the java client and fuse client have large performance gap.

I'm not sure the reason about this, but seems the bottleneck is not RPC calls. And for userspace fuse daemon, seems it can not send RPC request as fast as java client. Maybe is caused by following reasons:

1. Java code and native code interaction. (Copy data between Java and C lib)
2. Inefficient use of libfuse. (Such as using `direct_io`...)
....

Hope we can give some official comparison for java client and fuse client. And can give some workaround to mitigate the performance gap.

Further more, more efficient fuse client may need to be designed. Especially for DL workload.

**Comment by apc999** [comment]
the performance should be improved by https://github.com/Alluxio/alluxio/pull/12606 which introduce new JNI fuse integration with kernel_cache instead of direct_io

**Comment by Binyang2014** [comment]
Thanks @apc999, we already tested this feature in jni-fuse branch. And it show about 30% improvement. Thanks for your work

**Comment by apc999** [comment]
@Binyang2014 thanks for the heads up! I am releasing 2.4.1-1 next week with new JNI support. 
We are still keep improving the fuse integration FYI.
