### ISSUE TITLE
Data rebalancing between worker nodes

### ISSUE THREAD

**Issue by jpohanka** [Alluxio/alluxio#11487]
**Is your feature request related to a problem? Please describe.**

There are situations, when there is a disbalance in data distribution across the Alluxio workers in a cluster. In such cases, some workers contain proportionally more data (possibly across multiple tiers) while other workers contain proportionally far less data, or could be even empty. Here are two example cases, when such situations occur:

- **cluster upscaling**
  - adding more worker nodes to the Alluxio cluster
- **recovery from a failed worker**
   - a worker has crashed and has recovered
   - the data on the failed worker could be lost, but the data on the remaining workers should be rebalanced after the failed worker has recovered

Working with a data-unbalanced Alluxio cluster could lead to:

- **unbalanced storage/compute workloads** - some workers are overloaded, some are underutilized
- **overall performance degradation**

**Describe the solution you'd like**

A convenient solution to such a problem would comprice of the following parts:

- **a command line tool**
  - the user could send the rebalance request to the Alluxio master
  - the structure of the command would be:
    - `alluxio rebalance` - for an overall rebalancing
    - `alluxio rebalance <path>` - this would rebalance all data present in the Alluxio cluster that are under a certain file path

- **a background process**
  - the user would have the option to configure a background process running in the Alluxio cluster that would do the rebalancing in the background when i.e. the cluster is not under a high workload
  - the user would have the following **configuration variables** available:
    - *an enable/disable variable* for enabling/disabling the background rebalancing
    - *a type of data distribution disbalance measure*, which would be used to numerically evaluate the measure of data distribution disbalance, taking into account the configuration of individual Alluxio workers (i.e. statistical divergences between the actual data distibution functions and the equilibrium distribution functions)
    - *a threshold variable*, that would represent the maximum allowed value for the measure of the data distribution disbalance
    - *a policy variable*, that would detemine, under what circumstances the background rebalancing should be executed (i.e. specific level of client requests to the Alluxio workers)
    - *a check frequency variable*, that would represent the frequency of the periodic checks of the value of the data distribution disbalance
  - the configuration of the background rebalancing process should be consistent with other data placement policies (i.e. if for the `alluxio.user.ufs.block.read.location.policy` the `DeterministicHashPolicy` is chosen, then the rebalancing functionality should be omitted)

**Describe alternatives you've considered**

N/A

**Urgency**

This feature is important in deployments with **dynamic infrastructure scaling**, and also would be beneficial in generic situations **when the worker nodes have failed** and have recovered and the data needs to be rebalanced in order to meet certain performance SLAs.

**Additional context**

N/A

**Comment by jja725** [comment]
This is being considered, close it for now

**Comment by jpohanka** [comment]
@jja725 Thank you for the update. Can you let me know if there will be any progress with this feature?

**Comment by jja725** [comment]
Just planning no actual progress, so not in near future.
