### ISSUE TITLE
Issue when mounting the same bucket twice with different names

### ISSUE THREAD

**Issue by caiopavanelli** [Alluxio/alluxio#11499]
**Alluxio Version:**
v2.2.0

**Describe the bug**
If a bucket is mounted twice, with different names, Alluxio responds with success message but the action is not actually performed.

**To Reproduce**
```
$ alluxio fs mount /various s3://alluxesto/various/
Mounted s3://alluxesto/various at /various

$ alluxio fs mount /variouzz s3://alluxesto/various/
Mounted s3://alluxesto/various at /various
```

**Expected behavior**
Alluxio should either mount the second time or return an error informing the operation cannot be done.

**Urgency**
NORMAL

**Additional context**

**Comment by apc999** [comment]
@caiopavanelli  for some reason I could not really repro what you're reporting.
Below is what I see.  Can you try my example? the bucket I'm listing is public so everyone can make the same mount

```console
$ ./bin/alluxio fs mount  alluxio://localhost:19998/mnt1/ s3://alluxio-quick-start/data/
Mount point alluxio://localhost:19998/mnt1 already exists
$ ./bin/alluxio fs mount  alluxio://localhost:19998/mnt2/ s3://alluxio-quick-start/data/
Mount point s3://alluxio-quick-start/data is a prefix of s3://alluxio-quick-start/data
```

**Comment by caiopavanelli** [comment]
Hi @apc999, unfortunately (or fortunately) I couldn't reproduce the error anymore. There were environment updates on our end that might have resolved the issue and the message **Mount point X is a prefix of Y** is being correctly shown at the moment. I'm sorry for the time spent on this.
