### ISSUE TITLE
TTL actions in conjunction with persistence on rename results in exception while trying to free `_SUCCESS` file

### ISSUE THREAD

**Issue by ChernikovP** [Alluxio/alluxio#11500]
**Alluxio Version:**
`2.2.1`

**Describe the bug**
I was trying to follow https://docs.alluxio.io/ee/user/stable/en/operation/Performance-Tuning.html , to be more precise “Optimized Commits for Compute Frameworks” section. Along with that I’m trying to setup TTL and TTL action using “path defaults” -https://docs.alluxio.io/os/user/stable/en/operation/Configuration.html#path-defaults. 

Due to combination of  `alluxio.user.file.persist.on.rename` and  / or `alluxio.user.file.persistence.initial.wait.time` properties, `_SUCCESS` files have forever persistence state - `TO_BE_PERSISTED`. And as a result in `master.log` after TTL action takes place, you'll see:

```
ERROR InodeTtlChecker - Exception trying to clean up alluxio.master.file.meta.InodeDirectory@31 for ttl check
alluxio.exception.UnexpectedAlluxioException: Cannot free file /mlp/alluxio_ttl_test/_SUCCESS which is not persisted
	at alluxio.master.file.DefaultFileSystemMaster.freeInternal(DefaultFileSystemMaster.java:2295)
	at alluxio.master.file.DefaultFileSystemMaster.free(DefaultFileSystemMaster.java:2262)
	at alluxio.master.file.InodeTtlChecker.heartbeat(InodeTtlChecker.java:89)
	at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**

Important `alluxio-site.properties`:

```
alluxio.user.file.writetype.default=ASYNC_THROUGH
alluxio.user.file.persistence.initial.wait.time=-1
alluxio.user.file.persist.on.rename=true
alluxio.user.file.replication.durable=1
alluxio.master.persistence.blacklist=_temporary
```

Setting up TTL on specific folder:

```
$ ./bin/alluxio fsadmin pathConf add --property alluxio.user.file.create.ttl=10min /mlp
$ ./bin/alluxio fsadmin pathConf add --property alluxio.user.file.create.ttl.action=FREE /mlp
```
Writing some dummy data:
```
$ spark-shell
scala> case class Test(i: Int, s: String)
scala> val df = Seq(Test(1, "a"), Test(2, "b"), Test(3, "c"), Test(4, "d")).toDF
scala> df.write.json(("alluxio://master_1:19998;master_2:19998;master_3:19998/mlp/alluxio_ttl_test")
```

**Expected behavior**

No thrown exceptions in `master.log`. I do understand that this is happening due to MapReduce FileOutputCommitter's behaviour that is used by Spark - https://github.com/apache/hadoop/blob/master/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/lib/output/FileOutputCommitter.java#L313-L341 (i.e `_SUCCESS` file is created after renaming `_temporary` directory), so it's never persisted, but then either alluxio should not attempt to take ttl action on not persisted files or there should be explicit configuration flag like `alluxio.user.file.persist.mapred.success.file` to give user ability to persist `_SUCCESS` file even if `alluxio.user.file.persist.on.rename` is set to `true`.

**Urgency**
Low-urgency.

**Additional context**
There should be a warning that `alluxio.user.file.persist.on.rename=true` effects persistence of files that are copied to alluxio manually, e.x using `copyFromLocal`. As `copyFromLocal` doesn't involve renaming , such files also remain indefinitely in `TO_BE_PERSISTED` state.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
