### ISSUE TITLE
REST API Enhancements

### ISSUE THREAD

**Issue by pedersen** [Alluxio/alluxio#11524]
At my company, we do a lot of our work with Python. Having to include the JVM based Alluxio client causes our docker images to grow by at least 200M, and introduces dependencies that we are trying to reduce.

It would be helpful to allow the Python work to *all* go through the REST API, including `distributedCp`, `distributedMv`, `distributedLoad`, and `persist` operations. This would remove our need to include the JVM and Alluxio libraries, dropping our docker image sizes.

Right now, the only solution we have is to include Alluxio in our images. It works, but is suboptimal, and requires a lot of extra configuration that the REST API proxy already has and can maintain.

**Comment by apc999** [comment]
@pedersen  I implemented a prototype of `distributedLoad` in branch-2.3-fuse in this commit: https://github.com/Alluxio/alluxio/commit/d2fb1ff3e0c267bda4297096973c1da78b210a36
Note, this is not in master branch yet

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
