### ISSUE TITLE
The Alluxio worker's use of mmap can hang the worker for multiple minutes

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#11522]
**Alluxio Version:**
2.2.1

**Describe the bug**

When the worker is configured to use disks and uses the linux page cache, during high-load scenarios the worker can freeze for multiple minutes at a time while the kernel flushes data from the page cache to the disk. This happens because there are cases where the JVM needs to reach a safepoint, but the `mmap` syscall will hang for extended periods of time on a page fault.

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/3464508/83905937-73605180-a717-11ea-8e8d-ebbd81759fcb.png">

The "sync" time is over 3 minutes of a completely paused JVM.

**To Reproduce**
Configure Alluxio with slower drive (i.e. spinning disk). Read and write a lot of data. The worker eventually hangs

**Expected behavior**
The worker should either

1. Continue to serve IO requests, even at a slower rate or
2. Respond with an out of resources exception

**Urgency**
medium. Not many people using spinning disk drives.

**Comment by jja725** [comment]
maybe solved by netty channel and page store
