### ISSUE TITLE
Add a root/nonroot mode switch for Helm chart

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11526]
**Is your feature request related to a problem? Please describe.**
This request is originally from @cheyang 

In current 2.3 we removed dependency on root privilege in Helm chart. Specifically we removed on `hostNetwork` and `hostPath`, and run Alluxio pods with non-root user. However, when a user has root privilege and wants to stick to `hostNetwork` and `hostPath`, there's no easy way to achieve it.

A user may want `hostNetwork` and `hostPath` for the maximized performance. 

**Describe the solution you'd like**
There should be a switch to easily switch between "root" and "nonroot" modes in the deployment. The check can be as easy as `{{- $isRoot := eq (int .Values.user) 0 }}`

Root mode:
1. Workers use `hostNetwork`
1. Masters use `hostPath` for journal and metastore, instead of PV.
1. Workers use `hostPath` for tiered storage and domain socket, instead of PV.

Nonroot mode:
1. Workers do not use `hostNetwork`, and set `ALLUXIO_WORKER_CONTAINER_HOSTNAME`.
1. Masters use `volumeClaimTemplates` to generate PVCs for journal and metastore.
1. Workers use PVC for tiered storage and domain socket

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by jiacheliu3** [comment]
@cheyang I don't have good sources for the performance difference in `hostNetwork` vs no `hostNetwork`, or `hostPath` vs `local`. Do you mind adding some references/statistics if you happen to have any? Thanks!

**Comment by jiacheliu3** [comment]
@madanadit PTAL https://github.com/Alluxio/alluxio/pull/11527 is the PR for this feature. This PR provides everything except the worker tiered store, because the tiered stores are defined one by one manually.

If the feature request makes sense to you, I will proceed with all the necessary tests on my PR. Thanks!

**Comment by cheyang** [comment]
@liujiacheng I suggest we shouldn't assume the user is root, then choose hostNetwork. And ClusterFirstWithHostNet should be used when hostnewtork  is true.

```
hostNetwork: {{ hasKey .Values.worker "hostNetwork" | ternary .Values.worker.hostNetwork $isRoot }}
      dnsPolicy: {{ .Values.worker.dnsPolicy }}	      dnsPolicy: {{ .Values.worker.dnsPolicy | default ($isRoot | ternary "ClusterFirstWithHostNet" "ClusterFirst") }}
```

**Comment by jiacheliu3** [comment]
Added in #11554
