### ISSUE TITLE
Very serious performance problem found that alluxio will have a long tail effec

### ISSUE THREAD

**Issue by jinhang** [Alluxio/alluxio#11534]
**Alluxio Version:**
2.2.1

**Describe the bug**

Alluxio acceleration effect, found that alluxio will have a long tail effect, which causes some tasks to be particularly time-consuming. Compared with HDFS, there is no obvious advantage.

**To Reproduce**
excute spark shell 
or
excute TestDFSIO also can reeproduce

**Expected behavior**
so smart read performance

**Urgency**
I think it is urgency

**Additional context**

`#~/cloud/alluxio/bin/alluxio fs mkdir -p /xubo/project/SparkSW/input/
for i in 1 2 3 4 5 6 7 8 9 10
do
echo 'time:'$i
for j in 1 2 3 4 5 6 7 8 9 10
do
          sh test.sh 10G  hdfs://Master:9000/xubo/project/SparkSW/input/'D'$i'Line.fasta' hdfs://Master:9000/xubo/project/alluxio/output/TimeCount
  #sh test.sh 10G  alluxio://Master:19998/xubo/alluxio/uniref/'D'$j'Line.fasta' hdfs://Master:9000/xubo/project/alluxio/output/TimeCount
  #sh test.sh 10G  alluxio://Master:19998/xubo/project/SparkSW/input/'D'$j'Line.fasta' alluxio://Master:19998/xubo/project/alluxio/output/TimeCount
done

for j in 1 2 3 4 5 6 7 8 9 10
do
        sh test.sh 10G  alluxio://Master:19998/xubo/project/SparkSW/input/'D'$i'Line.fasta' hdfs://Master:9000/xubo/project/alluxio/output/TimeCount
done
done`

**Comment by jinhang** [comment]
@ZacBlanco @apc999

**Comment by ZacBlanco** [comment]
This issue doesn't have enough information to determine if there are any mis-configurations or errors. If you see poor performance then you'll need to answer a few things:

1. Is the data already cached in Alluxio?
2. Which UFS are you using?
3. If you aren't using a cloud-based UFS like AWS S3, is the data in the UFS co-located with Alluxio or in a separate remote cluster somewhere?

You also should share:
- `alluxio-site.properties`
- Your cluster architecture
- Look for any errors in the `master.log`, `job_master.log`, `worker.log`, or job_worker.log` and share them here.
- The exact benchmark workload that is being run. The information about your script you provided doesn't tell us much about what kind of workload you're actually running.

**Comment by jinhang** [comment]
1、Is the data already cached in Alluxio?
yes，we use MUST_CACHE  write some file into alluxio
2、Which UFS are you using?
hdfs
3、co-located with Alluxio

others info:
1、alluxio-site.properties
`alluxio.master.mount.table.root.ufs=/dev/shm
alluxio.master.bind.host=host1
alluxio.master.hostname=host1
alluxio.master.embedded.journal.addresses=host1.:19200,host2:19200,host3:19200
alluxio.security.authentication.type=SIMPLE
alluxio.master.security.impersonation.test.users=*
# Worker properties
alluxio.worker.memory.size=50GB
alluxio.worker.tieredstore.level0.dirs.path=/dev/shm
alluxio.worker.tieredstore.level0.dirs.mediumtype=MEM
alluxio.worker.tieredstore.level0.dirs.quota=50GB`


2、block suspend
`worker.log.2020-06-09 20:00:24.593 DEBUG AbstractReadHandler - Received read request block_id : 4725420326914
worker.log.2020-06-09 20:01:24.593 DEBUG AbstractReadHandler - Received read request block_id : 4725420326914
worker.log.2020-06-09 20:01:24.593 DEBUG AbstractReadHandler - Received read request block_id : 4725420326914
worker.log.2020-06-09 20:01:24.607 DEBUG AbstractReadHandler - Received read request block_id : 4725420326914
worker.log.2020-06-09 20:01:24.611 DEBUG AbstractReadHandler - Received read request block_id : 4725420326914
worker.log.2020-06-09 20:01:24.639 DEBUG AbstractReadHandler - Received read request block_id : 4725420326914
worker.log.2020-06-09 20:01:24.692 DEBUG AbstractReadHandler - Received read request block_id : 4725420326914

worker.log.2020-06-09 20:00:24.593 DEBUG TieredBlockStore - accessBlock ssesionId = 187541131331, block_id : 4725420326914
worker.log.2020-06-09 20:00:24.593 DEBUG TieredBlockStore - getBlockReader - ssesionId = 187541131331, block_id : 4725420326914
worker.log.2020-06-09 20:00:24.593 DEBUG TieredBlockStore - lockBlockNoExcetion - ssesionId = 187541131331, block_id : 4725420326914
worker.log.2020-06-09 20:00:24.593 DEBUG AbstractReadHandler - Received read request block_id : 
4725420326914


`
3、

**Comment by jinhang** [comment]
> @jinhang Do you mind sharing your findings?

reopen it to new issue
