### ISSUE TITLE
Very serious performance problem found that alluxio will have a long tail effec

### ISSUE THREAD

**Issue by jinhang** [Alluxio/alluxio#11547]
**Alluxio Version:**
2.2.1

**Describe the bug**
Alluxio acceleration effect, found that alluxio will have a long tail effect, which causes some tasks to be particularly time-consuming. Compared with HDFS, there is no obvious advantage.

**To Reproduce**

excute TestDFSIO also can reproduce

what is TestDFSIo you can read : https://community.pivotal.io/s/article/Running-DFSIO-MapReduce-benchmark-test?language=en_US

**Expected behavior**
so smart read performance

**Urgency**
I think it is urgency

**Additional context**
`
case 1:
yarn jar hadoop-mapreduce-client-jobclient-3.1.1-tests.jar TestDFSIO -fs alluxio://host-1:19998 -Dtest.build.data=alluxio://host-1:19998/benchmark/test/  -write -nrFiles 25  -fileSize 4096

**case 1 use time is so good**

case2 : yarn jar hadoop-mapreduce-client-jobclient-3.1.1-tests.jar TestDFSIO -fs alluxio://host-1:19998 -Dtest.build.data=alluxio://host-1:19998/benchmark/test/  -read -nrFiles 25  -fileSize 4096

**case 2  read most of the execution for 10s, some are randomly executed on different alluxio worker nodes for 2 minute** 
`

**Comment by jinhang** [comment]
alluxio-site.properties
`alluxio.master.mount.table.root.ufs=/dev/shm
alluxio.master.bind.host=host-1
alluxio.master.hostname=host-1
alluxio.master.embedded.journal.addresses=host-1:19200,host-10:19200,host-33.:19200
alluxio.security.authentication.type=SIMPLE
alluxio.master.security.impersonation.root.users=*
alluxio.worker.memory.size=50GB
alluxio.worker.tieredstore.level0.dirs.path=/dev/shm
alluxio.worker.tieredstore.level0.dirs.mediumtype=MEM
alluxio.worker.tieredstore.level0.dirs.quota=50GB
`

jobmaster.log and worker.log has not err and warn log.

**Comment by jinhang** [comment]
```

@Override
  public StreamObserver<ReadRequest> readBlock(StreamObserver<ReadResponse> responseObserver) {
    CallStreamObserver<ReadResponse> callStreamObserver =
        (CallStreamObserver<ReadResponse>) responseObserver;
    if (ZERO_COPY_ENABLED) {
      callStreamObserver =
          new DataMessageServerStreamObserver<>(callStreamObserver, mReadResponseMarshaller);
    }
    BlockReadHandler readHandler = new BlockReadHandler(GrpcExecutors.BLOCK_READER_EXECUTOR,
        mWorkerProcess.getWorker(BlockWorker.class), callStreamObserver,
        getAuthenticatedUserInfo(), mDomainSocketEnabled);
    callStreamObserver.setOnReadyHandler(readHandler::onReady);
    return readHandler;
  }



  @Override
  // TODO(calvin): Remove when lock and reads are separate operations.
  public boolean unlockBlock(long sessionId, long blockId) {
    return mBlockStore.unlockBlock(sessionId, blockId);
  }

 @Override
  public long lockBlockNoException(long sessionId, long blockId) {
    return mBlockStore.lockBlockNoException(sessionId, blockId);
  }

  @Override
  public BlockReader readBlockRemote(long sessionId, long blockId, long lockId)
      throws BlockDoesNotExistException, InvalidWorkerStateException, IOException {
    return mBlockStore.getBlockReader(sessionId, blockId, lockId);
  }

```

**Comment by jinhang** [comment]
we find some read task waitForComplete finished use more time than others
`
public void waitForComplete(long timeoutMs) throws IOException {
    if (mCompleted || mCanceled) {
      return;
    }
    while (receive(timeoutMs) != null) {
      // wait until inbound stream is closed from server.
    }
  }
`

**Comment by jinhang** [comment]
@ZacBlanco @apc999

**Comment by jja725** [comment]
we've implemented paged worker and improve the performance a lot. Will close it for now, feel free to reopen it and contact us if this is still valid.
