### ISSUE TITLE
Support emptyDir for volume types

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11555]
**Is your feature request related to a problem? Please describe.**
This request is from @cheyang 

Previously in 2.1, `emptyDir` volume can be used for master metastore and journal. Later we removed them as they are not persistent storage.

In @cheyang 's use case, they would like to provide users a easy start without the need for PVC, and at the cost of having no persistency. (This will be a temporary/ephemeral deployment.) Therefore they would like to use emptyDir for:
1. master metastore
1. master journal
1. worker tiered store (this is already supported)

Worker domain socket will not use emptyDir as it is not visible to other pods.

**Describe the solution you'd like**
Add `emptyDir` to the options for these components.

**Describe alternatives you've considered**

**Urgency**
MEDIUM

**Additional context**

**Comment by jiacheliu3** [comment]
@cheyang Per our discussion earlier, please see if this summarizes your use case. Thanks!

**Comment by cheyang** [comment]
I think if `worker domain socket` is in empty dir, the other pods can't access it. So I suggest to remove it from this fix. thanks.

**Comment by jiacheliu3** [comment]
Implemented in #11554
