### ISSUE TITLE
Master pods in K8s cannot see the service for itself

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11562]
**Alluxio Version:**
2.3.0-SNAPSHOT

**Describe the bug**
A master pod cannot access itself using its `NodePort` service. This is called "hair-pinning" and this is disabled in K8s when using iptables. (Ref: https://kb.vmware.com/s/article/67455)

When the master pod is not able to find its own service, the readiness probe never succeeds.

This issue is originally reported by @cheyang 

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
The work around for the hair-pinning problem is to use headless services for the master pods.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
The change from headless service to NodePort was done in https://github.com/Alluxio/alluxio/pull/10686/files

**Comment by jiacheliu3** [comment]
https://github.com/Alluxio/alluxio/pull/11563 should fix this issue

**Comment by jiacheliu3** [comment]
@cheyang Do you mind sharing the network configuration in your environment, so we can have a deeper understanding on this please? We didn't face this issue in our internal test environments.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
