### ISSUE TITLE
Allow a cancelled RPC to interrupt metadata syncing

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#11672]
**Is your feature request related to a problem? Please describe.**

If a user triggers a sync (i.e. via a listStatus) on a large directory and the sync takes an extended period of time, then the user might be inclined to ctrl-C to cancel the RPC and issue it again.

The problem with this now is that the metadata sync will continue to run on the master until completion. Only after completion will the handler eventually run into an error when returning the RPC response.

Imagine syncing a large directory that creates > 1M files. This will consume a large swath of CPU for some period of time. Depending on the hardware configuration, this can be a _long_ time. If the user cancels the RPC, then it should interrupt the metadata sync which should allow more operations

**Describe the solution you'd like**

The solution itself is straightforward. Each RPC is associated with an `OperationContext<T>` - the context has a method `isCancelled` which will return whether the RPC issued by the user has been cancelled for one or more reasons (user, network, etc..). It uses the underlying gRPC `StreamObserver#isCancelled` method.

Within a metadata sync we should be able to provide an `OperationContext` and periodically check the `isCancelled` on the operation to see if we should continue syncing.

**Describe alternatives you've considered**

None at the moment. The proposed solutions seems like a simple and straightforward implementation with few, if any, downsides. The only argument I could see against this is that someone wants a "fire-and-forget" implementation for syncing where they can issue an `ls`, cancel the command, and continue using their terminal while the sync runs. In that case, the user would just never know when the sync is finished - but they would at least know that it was started.

**Urgency**

Prevent over-utilization on the master that doesn't benefit any client operation.

**Additional context**
N/A

**Comment by ZacBlanco** [comment]
One other issue I'd like to bring up is that in the event of a cancelled RPC, then we can leave a half-synced directory. In the implementation we probably want to think about what we should do in such an event.

If the sync interval is set to, let's say, 1h. Then someone comes along that does an ls which triggers the sync and cancels it, then even if only half or 10% of the directory was synced, another sync won't be attempted for another hour. 


We should probably remove at least the root path from the UFS sync path cache in this situation so an RPC following a cancel can still trigger a sync without having to wait for the metadata interval. @ggezer What do you think?

**Comment by ggezer** [comment]
If we do reset the sync status for the cancelled sync session, then the root need not be an exception and it's more consistent to reset for all base paths. 

Overall, I believe we shouldn't need to reset. The sync logic should be confident when marking a path as synced by making sure all its child has been synced and marked successfully. Then no reset would be necessary. However, I can see some challenges associated with this solution and am fine with resetting for now.
