### ISSUE TITLE
Use a different configurable sync interval while Active full sync is ongoing

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#11697]
**Is your feature request related to a problem? Please describe.**

Users who enable active sync that that want to avoid having a sync interval all together may still encounter times where the active sync mechanism falls behind and triggers a sync on the entire sync point. Users will likely still want metadata synced in a timely manner. During the full sync, this may not occur.

**Describe the solution you'd like**

In order to preserve behavior in the best possible manner, during the full sync if the user's sync interval is configured to -1 _and_ active sync has a full sync occurring, then we should add a configuration flag which will automatically use a specified sync interval during active sync.

Example
- by default sync interval is -1, active sync is enabled
- Active sync falls too far behind
- full sync is triggered
- All RPCs to paths underneath the sync point use a different (typically much shorter, 1-5s) sync interval

**Describe alternatives you've considered**

None at the moment

**Urgency**
 
Low

**Comment by jja725** [comment]
@da is this still valid? otherwise help me close this please
