### ISSUE TITLE
Add Backblaze B2 as UFS

### ISSUE THREAD

**Issue by caiopavanelli** [Alluxio/alluxio#11707]
**Is your feature request related to a problem? Please describe.**
Backblaze B2 Cloud Storage is advertised as ¼ of the price of Amazon S3.

If Alluxio support Backblaze B2 as a UFS, Alluxio can support people migrating from S3 to a more affordable object storage by providing compute integrations.

**Describe the solution you'd like**
Support Backblaze B2 as UNDERFS through develop a module of Alluxio.

**Describe alternatives you've considered**
Develop a module under underfs module, named alluxio-underfs-b2.

**Urgency**
Normal.

**Additional context**
No.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
