### ISSUE TITLE
Limit the logging for MasterWorkerInfo

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11729]
**Is your feature request related to a problem? Please describe.**
When a `MasterWorkerInfo` is converted to string, all its blocks are converted to a list of block IDs. When a `MasterWorkerInfo` has too many blocks this wastes resource and take up a very large block in the logs. For example a MasterWorkerInfo of a good 400 blocks can fill my 15-inch screen. I've seen a 10MB log file mostly filled by one `MasterWorkerInfo` object.

**Describe the solution you'd like**
Limit the printout for a `MasterWorkerInfo`.

**Describe alternatives you've considered**

**Urgency**
LOW

**Additional context**
The drawback is we lose the full knowledge about the omitted blocks in the logs. One option is to print the full list in DEBUG and chunk the output in normal mode, like https://github.com/Alluxio/alluxio/pull/11514

**Comment by jiacheliu3** [comment]
@gpang I wanted to discuss with you on this. Do you think it's okay to chunk the full list of blocks in our logs? Do we rely on the logs to trace the existence of certain blocks?

**Comment by gpang** [comment]
What do you mean by "chunk the list"?

Maybe a simple solution is to print the prefix (and the count) of the list at INFO level, and the rest at DEBUG level, so we have access to the full list if we need it.

**Comment by jiacheliu3** [comment]
@gpang I think I meant "truncate" the list. See https://github.com/Alluxio/alluxio/pull/12841, the `blockCount` field contains the count. When log level is above DEBUG, only the prefix of 100 blocks are printed. And when the log level is DEBUG, all the blocks are printed.

**Comment by jiacheliu3** [comment]
Resolved by the PR
