### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.google.guava:guava:jar

### ISSUE THREAD

**Issue by Bing-ok** [Alluxio/alluxio#11744]
Hi, there are multiple versions of <b><i>com.google.guava:guava</i></b> in <b><i>alluxio-2.3.0\examples</i></b>. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only <b><i>com.google.guava:guava:27.1-jre</i></b> can be loaded, <b><i>com.google.guava:guava:11.0.2</i></b> and <b><i>com.google.guava:guava:28.1-android</i></b> will be shadowed.

As <b><i>com.google.guava:guava:11.0.2</i></b> has not been loaded during the building process, several methods are missing. However, the missing methods:
<b><i>1. com.google.common.util.concurrent.Futures: void addCallback(com.google.common.util.concurrent.ListenableFuture,com.google.common.util.concurrent.FutureCallback)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;alluxio.examples.Performance$HdfsWorker: void init (int,int,int,java.nio.ByteBuffer,boolean,java.lang.String)&gt; alluxio-2.3.0\examples\target\classes
</br>&lt;org.apache.hadoop.conf.Configuration: void clinit ()&gt; Repositories\org\apache\hadoop\hadoop-common\2.7.3\hadoop-common-2.7.3.jar
</br>&lt;org.apache.hadoop.util.ApplicationClassLoader: java.net.URL getResource(java.lang.String)&gt; Repositories\org\apache\hadoop\hadoop-common\2.7.3\hadoop-common-2.7.3.jar
</br>&lt;org.apache.hadoop.util.ApplicationClassLoader: void clinit ()&gt; Repositories\org\apache\hadoop\hadoop-common\2.7.3\hadoop-common-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.RemoteBlockReader: void close()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.PeerCache: void put(org.apache.hadoop.hdfs.protocol.DatanodeID,org.apache.hadoop.hdfs.net.Peer)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.PeerCache: void putInternal(org.apache.hadoop.hdfs.protocol.DatanodeID,org.apache.hadoop.hdfs.net.Peer)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.PeerCache: void startExpiryDaemon()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.Checkpointer: void run()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.Checkpointer: void doCheckpoint()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.FSImage: void saveFSImageInAllDirs(org.apache.hadoop.hdfs.server.namenode.FSNamesystem,long)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.FSImage: void saveFSImageInAllDirs(org.apache.hadoop.hdfs.server.namenode.FSNamesystem,org.apache.hadoop.hdfs.server.namenode.NNStorage$NameNodeFile,long,org.apache.hadoop.hdfs.util.Canceler)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.util.ShutdownHookManager$1: void run()&gt; Repositories\org\apache\hadoop\hadoop-common\2.7.3\hadoop-common-2.7.3.jar
</br>&lt;com.google.common.util.concurrent.Futures$6: void run()&gt; 
</br>&lt;org.apache.hadoop.mapred.LocatedFileStatusFetcher$ProcessInitialInputPathCallback: void onSuccess(java.lang.Object)&gt; Repositories\org\apache\hadoop\hadoop-mapreduce-client-core\2.7.3\hadoop-mapreduce-client-core-2.7.3.jar
</br>&lt;org.apache.hadoop.mapred.LocatedFileStatusFetcher$ProcessInitialInputPathCallback: void onSuccess(org.apache.hadoop.mapred.LocatedFileStatusFetcher$ProcessInitialInputPathCallable$Result)&gt; Repositories\org\apache\hadoop\hadoop-mapreduce-client-core\2.7.3\hadoop-mapreduce-client-core-2.7.3.jar
</br>&lt;com.google.common.util.concurrent.Futures: void addCallback(com.google.common.util.concurrent.ListenableFuture,com.google.common.util.concurrent.FutureCallback)&gt; 
</details>

<b><i>2. com.google.common.base.Objects: java.lang.Object firstNonNull(java.lang.Object,java.lang.Object)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;alluxio.examples.Performance$HdfsWorker: void init (int,int,int,java.nio.ByteBuffer,boolean,java.lang.String)&gt; alluxio-2.3.0\examples\target\classes
</br>&lt;org.apache.hadoop.conf.Configuration: void clinit ()&gt; Repositories\org\apache\hadoop\hadoop-common\2.7.3\hadoop-common-2.7.3.jar
</br>&lt;org.apache.hadoop.util.ApplicationClassLoader: java.net.URL getResource(java.lang.String)&gt; Repositories\org\apache\hadoop\hadoop-common\2.7.3\hadoop-common-2.7.3.jar
</br>&lt;org.apache.hadoop.util.ApplicationClassLoader: void clinit ()>&gt; Repositories\org\apache\hadoop\hadoop-common\2.7.3\hadoop-common-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.RemoteBlockReader: void close()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.PeerCache: void put(org.apache.hadoop.hdfs.protocol.DatanodeID,org.apache.hadoop.hdfs.net.Peer)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.PeerCache: void putInternal(org.apache.hadoop.hdfs.protocol.DatanodeID,org.apache.hadoop.hdfs.net.Peer)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.PeerCache: void startExpiryDaemon()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.Checkpointer: void run()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.Checkpointer: void doCheckpoint()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.Checkpointer: void rollForwardByApplyingLogs(org.apache.hadoop.hdfs.server.protocol.RemoteEditLogManifest,org.apache.hadoop.hdfs.server.namenode.FSImage,org.apache.hadoop.hdfs.server.namenode.FSNamesystem)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.FSImage: long loadEdits(java.lang.Iterable,org.apache.hadoop.hdfs.server.namenode.FSNamesystem)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.FSImage: long loadEdits(java.lang.Iterable,org.apache.hadoop.hdfs.server.namenode.FSNamesystem,org.apache.hadoop.hdfs.server.common.HdfsServerConstants$StartupOption,org.apache.hadoop.hdfs.server.namenode.MetaRecoveryContext)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.FSEditLogLoader: long loadFSEdits(org.apache.hadoop.hdfs.server.namenode.EditLogInputStream,long,org.apache.hadoop.hdfs.server.common.HdfsServerConstants$StartupOption,org.apache.hadoop.hdfs.server.namenode.MetaRecoveryContext)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.FSEditLogLoader: long loadEditRecords(org.apache.hadoop.hdfs.server.namenode.EditLogInputStream,boolean,long,org.apache.hadoop.hdfs.server.common.HdfsServerConstants$StartupOption,org.apache.hadoop.hdfs.server.namenode.MetaRecoveryContext)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.FSEditLogLoader: long applyEditLogOp(org.apache.hadoop.hdfs.server.namenode.FSEditLogOp,org.apache.hadoop.hdfs.server.namenode.FSDirectory,org.apache.hadoop.hdfs.server.common.HdfsServerConstants$StartupOption,int,long)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.FSDirAclOp: java.util.List unprotectedSetAcl(org.apache.hadoop.hdfs.server.namenode.FSDirectory,java.lang.String,java.util.List,boolean)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.AclTransformation: java.util.List replaceAclEntries(java.util.List,java.util.List)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;org.apache.hadoop.hdfs.server.namenode.AclTransformation: void calculateMasks(java.util.List,java.util.EnumMap,java.util.EnumSet,java.util.EnumSet)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.7.3\hadoop-hdfs-2.7.3.jar
</br>&lt;com.google.common.base.Objects: java.lang.Object firstNonNull(java.lang.Object,java.lang.Object)&gt;
</details>

The above missing methods are actually referenced by <b><i>alluxio-2.3.0\examples</i></b>, which will cause “NoSuchMethodErrors” at runtime.

Suggested fixing solutions:
1. Upgrade dependency <b><i>org.apache.hadoop:hadoop-client</i></b> from <b><i>2.7.3</i></b> to <b><i>3.2.1</i></b>. Because one conflicting library version <b><i>com.google.guava:guava:11.0.2</i></b> is transitively introduced by <b><i>org.apache.hadoop:hadoop-client:2.7.3</i></b>. Upgrading dependency <b><i>org.apache.hadoop:hadoop-client</i></b> from <b><i>2.7.3</i></b> to <b><i>3.2.1</i></b> can solve this dependency conflict.

Thank you very much for your attention.
Best regards,

Dependency tree----
<details>
<summary>click for details</summary>
</br>[INFO] org.alluxio:alluxio-examples:jar:2.3.0
</br>[INFO] +- <b>com.google.guava:guava:jar:27.0.1-jre:compile</b>
</br>[INFO] +- org.apache.hadoop:hadoop-client:jar:2.7.3:compile
</br>[INFO] |  +- org.apache.hadoop:hadoop-common:jar:2.7.3:compile
</br>[INFO] |  |  \- <b>(com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 11.0.2; omitted for duplicate)</b>
</br>[INFO] |  +- org.apache.hadoop:hadoop-hdfs:jar:2.7.3:compile
</br>[INFO] |  |  \- <b>(com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 11.0.2; omitted for duplicate)</b>
</br>[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.7.3:compile
</br>[INFO] |  |  \- org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.7.3:compile
</br>[INFO] |  |     +- org.apache.hadoop:hadoop-yarn-client:jar:2.7.3:compile
</br>[INFO] |  |     |  \- <b>(com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 11.0.2; omitted for duplicate)</b>
</br>[INFO] |  |     \- org.apache.hadoop:hadoop-yarn-server-common:jar:2.7.3:compile
</br>[INFO] |  |        \- <b>(com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 11.0.2; omitted for duplicate)</b>
</br>[INFO] |  +- org.apache.hadoop:hadoop-yarn-api:jar:2.7.3:compile
</br>[INFO] |  |  \- <b>(com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 11.0.2; omitted for duplicate)</b>
</br>[INFO] |  \- org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.7.3:compile
</br>[INFO] |     \- org.apache.hadoop:hadoop-yarn-common:jar:2.7.3:compile
</br>[INFO] |        \- <b>(com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 11.0.2; omitted for duplicate)</b>
</br>[INFO] +- org.alluxio:alluxio-core-client-fs:jar:2.3.0:compile
</br>[INFO] |  +- (com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 11.0.2; omitted for duplicate)
</br>[INFO] |  +- io.grpc:grpc-api:jar:1.28.1:compile
</br>[INFO] |  |  \- (com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 28.1-android; omitted for duplicate)
</br>[INFO] |  +- org.alluxio:alluxio-core-base:jar:2.3.0:compile
</br>[INFO] |  |  \- (com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 28.1-android; omitted for duplicate)
</br>[INFO] |  \- org.alluxio:alluxio-core-transport:jar:2.3.0:compile
</br>[INFO] |     +- (com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 28.1-android; omitted for duplicate)
</br>[INFO] |     \- io.grpc:grpc-protobuf:jar:1.28.1:compile
</br>[INFO] |        +- (com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 28.1-android; omitted for duplicate)
</br>[INFO] |        \- io.grpc:grpc-protobuf-lite:jar:1.28.1:compile
</br>[INFO] |           \- (com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 28.1-android; omitted for duplicate)
</br>[INFO] +- org.alluxio:alluxio-core-common:jar:2.3.0:compile
</br>[INFO] |  +- (com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 28.1-android; omitted for duplicate)
</br>[INFO] |  \- org.apache.curator:curator-client:jar:4.2.0:compile
</br>[INFO] |     \- (com.google.guava:guava:jar:27.0.1-jre:compile - version managed from 28.1-android; omitted for duplicate)
</br>[INFO] \- com.google.guava:guava-testlib:jar:27.0.1-jre:test
</br>[INFO]    \- (com.google.guava:guava:jar:27.0.1-jre:test - version managed from 28.1-android; omitted for duplicate)
</details>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @ZacBlanco

**Comment by apc999** [comment]
thanks for reporting this issue @Bing-ok

**Comment by NeolithEra** [comment]
@apc999 Thanks for your feedback! Do you agree this solution? Could I pull a request?

**Comment by Bing-ok** [comment]
@apc999  Do you agree with the solution? Could I pull a request to fix it?

**Comment by yuzhu** [comment]
@Bing-ok we recently upgraded hdfs client version, please let me know if there is more to be done about this ticket? otherwise i will close it in a week.

**Comment by Bing-ok** [comment]
Thanks for your support!
