### ISSUE TITLE
CLI command validateEnv don't sum up number of failures/warnings/skipped

### ISSUE THREAD

**Issue by akantak** [Alluxio/alluxio#11793]
**Alluxio Version:**
2.3.0

**Describe the bug**
When there are some issues in setup (any of the checks has failed/warn/skip status) while using command `./bin/alluxio validateEnv local`, there is sum up in the last line `1 failures 1 warnings 1 skipped` which should count the number of occurrences of each issue, but it doesn't. It is either number 1 or no mention.

**To Reproduce**
Use command `./bin/alluxio validateEnv local` without any settings configured, ex. no settings for Kerberos should lead to 2 skipped checks, but in a sum up it would be counted as 1.

**Expected behavior**
The last line in validateEnv output should correctly sum up a number of issues, not be only 1 or no mention.

**Urgency**
Very low urgency.

**Additional context**
Quickly checked the source code and the rootcause is probably in:
https://github.com/Alluxio/alluxio/blob/a38f2f2742aec16c5d56997f688c3e42bca6f32c/integration/tools/validation/src/main/java/alluxio/cli/ValidateEnv.java#L305
where there is:
`results.put(result.mState, results.getOrDefault(result, 0) + 1);`
instead of:
`results.put(result.mState, results.getOrDefault(result.mState, 0) + 1);`

**Comment by akantak** [comment]
pinging @jiacheliu3 FYI, as he may be interested in this bug

**Comment by jiacheliu3** [comment]
Thanks! @akantak Assigning the issue to myself.
