### ISSUE TITLE
A GlusterFS directory of 930k files/subdirs took 249G RAM for alluxio master

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11794]
**Alluxio Version:**
2.2

**Describe the bug**
Mounting a Glusterfs directory with roughly 930k files/subdirs is using 249G RAM for Alluxio master. 
```
16531 root      20   0  0.354t 0.249t  45760 S  45.2 67.6 755:06.55 java
```

`alluxio fs mount` gives
```
/mnt/glusterfs-sub1  on  /data3  (local, capacity=10.91TB, used=-1B(0%), not read-only, not shared, properties={})
/mnt/glusterfs       on  /       (local, capacity=3724.17GB, used=-1B(0%), not read-only, not shared, properties={})
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
alluxio-site.properties:
```
alluxio.master.hostname=node9
alluxio.master.mount.table.root.ufs=/mnt/glusterfs/
alluxio.logs.dir=/data/alluxio-log
alluxio.master.worker.timeout=10min
alluxio.master.worker.heartbeat.interval=60s
alluxio.master.worker.connect.wait.time=60s
alluxio.master.ufs.active.sync.event.rate.interval=6000000000sec
alluxio.master.ufs.active.sync.interval=3000000000sec
alluxio.master.journal.type=NOOP
alluxio.master.metastore=HEAP
alluxio.master.metastore.dir=/data2/metastore
alluxio.master.rpc.executor.max.pool.size=10000
alluxio.master.lock.pool.concurrency.level=10000
alluxio.master.lock.pool.high.watermark=5000000
alluxio.master.lock.pool.low.watermark=500000
alluxio.master.lock.pool.initsize=10000
alluxio.master.ufs.block.location.cache.capacity=50000000
alluxio.master.ufs.path.cache.capacity=1000000
alluxio.master.metastore.inode.cache.high.water.mark.ratio=0.9
alluxio.master.metastore.inode.cache.low.water.mark.ratio=0.7
alluxio.master.metastore.inode.cache.max.size=10000000
alluxio.master.metastore.inode.cache.evict.batch.size=1000
alluxio.master.ufs.active.sync.thread.pool.size=256
```

**Comment by gongbing851217** [comment]
@jiacheliu3 , here, thank you for your help.

**Comment by jiacheliu3** [comment]
@gongbing851217 After some internal discussion we suggest looking into the below directions. Could you try those and share with us your findings?

1. Better understanding on the memory consumption and configuration
What are your JVM options for the 250G master? Does it GC and gets lower than 250G? Do you see GC pressure and have GC logs?

2. Do you identify leaks?
On checking How does your Alluxio master memory usage change over time? If there are resource leaks, the memory usage keeps going up even if you do nothing, then triggers GC and goes down, but then goes up again. If you observe a loop like this it's a good indication of a resource leak.

3. What objects are consuming the most resource
Since your heap is really big I don't think you can do a heap dump.` jprofiler` or `arthas` can help you do a histogram on what objects are using how much heap.

**Comment by gongbing851217** [comment]
> @gongbing851217 After some internal discussion we suggest looking into the below directions. Could you try those and share with us your findings?
> 
> 1. Better understanding on the memory consumption and configuration
>    What are your JVM options for the 250G master? Does it GC and gets lower than 250G? Do you see GC pressure and have GC logs?
ALLUXIO_MASTER_JAVA_OPTS+="-Dalluxio.master.audit.logging.enabled=true "
ALLUXIO_MASTER_JAVA_OPTS+=" -Xmx300g "
ALLUXIO_MASTER_JAVA_OPTS+=" -Xms300g "
ALLUXIO_MASTER_JAVA_OPTS+=" -XX:MetaspaceSize=512m "
ALLUXIO_MASTER_JAVA_OPTS+=" -XX:MaxMetaspaceSize=512m "
ALLUXIO_MASTER_JAVA_OPTS+=" -XX:+UseG1GC "
ALLUXIO_MASTER_JAVA_OPTS+=" -XX:+PreserveFramePointer "
#ALLUXIO_MASTER_JAVA_OPTS+=" -XX:MaxGCPauseMillis=250 "
ALLUXIO_MASTER_JAVA_OPTS+=" -Djava.net.preferIPv4Stack=true "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dcom.sun.management.jmxremote "
ALLUXIO_MASTER_JAVA_OPTS+=" -Xnoclassgc "
ALLUXIO_MASTER_JAVA_OPTS+=" -Xloggc:/data/alluxio-log/alluxio-master-gc.log "
ALLUXIO_MASTER_JAVA_OPTS+=" -XX:+PrintGCDetails "
ALLUXIO_MASTER_JAVA_OPTS+=" -XX:+PrintGCDateStamps "
ALLUXIO_MASTER_JAVA_OPTS+=" -XX:-OmitStackTraceInFastThrow "
ALLUXIO_MASTER_JAVA_OPTS+=" -XX:InitiatingHeapOccupancyPercent=65 "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dcom.sun.management.jmxremote "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dcom.sun.management.jmxremote.ssl=false "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dcom.sun.management.jmxremote.authenticate=false "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dcom.sun.management.jmxremote.port=10102 "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dalluxio.home=/home/alluxio-2.3.0/ "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dalluxio.conf.dir=/home/alluxio-2.3.0/conf "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dalluxio.logs.dir=/data/alluxio-log "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dlog4j.configuration=file:/home/alluxio-2.3.0/conf/log4j.properties "
ALLUXIO_MASTER_JAVA_OPTS+=" -Dorg.apache.jasper.compiler.disablejsr199=true "
ALLUXIO_MASTER_JAVA_OPTS+=" -Djava.net.preferIPv4Stack=true "

> 2. Do you identify leaks?
>    On checking How does your Alluxio master memory usage change over time? If there are resource leaks, the memory usage keeps going up even if you do nothing, then triggers GC and goes down, but then goes up again. If you observe a loop like this it's a good indication of a resource leak.

I do nothing, GC almost can't let memory goes down,  util now, this alluxio master memory goes up to 350G. 

> 3. What objects are consuming the most resource
>    Since your heap is really big I don't think you can do a heap dump.` jprofiler` or `arthas` can help you do a histogram on what objects are using how much heap.

**Comment by jiacheliu3** [comment]
@gongbing851217 From what you describe, seems the memory keeps going up and it sounds like a leak to me.

Are you able to try visualvm or arthas to take a closer look at what in the heap keeps growing and takes up all the memory? The below links may be helpful to you. Depending on your heap size, if you are not able to use visualvm, try arthas (which uses asyn-profiler).

https://codenuclear.com/java-memory-profiling-with-visualvm/
https://alibaba.github.io/arthas/en/advanced-use.html#profiler-flame-graph

**Comment by gongbing851217** [comment]
i use jmap -histo  command to dump memory use info as follow:
   1:     106282256    40693986272  [Ljava.lang.Object;
   2:     263792402    20044214176  [C
   3:     189593227    16684203976  java.util.concurrent.ConcurrentHashMap$TreeNode
   4:     525188134    12604515216  java.lang.Long
   5:      51795101    10359020200  alluxio.master.file.meta.MutableInodeFile
   6:     258947014     8286304448  java.lang.String
   7:      78851738     8200580752  java.util.HashMap$TreeNode
   8:        754530     6732556688  [I
   9:      83622338     5351829632  java.util.HashMap
  10:        934491     4265234824  [Ljava.util.concurrent.ConcurrentHashMap$Node;
  11:      88116449     4229589552  java.util.concurrent.ConcurrentHashMap$Node
  12:     102542694     4101707760  java.util.ArrayList
  13:      51000064     3672004608  com.google.common.cache.LocalCache$StrongAccessEntry
  14:      44369243     3549539440  java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync
  15:      31081207     3334789960  [Ljava.util.HashMap$Node;
  16:      51795187     2900530472  alluxio.proto.meta.Block$BlockMeta
  17:      52729437     2531012976  alluxio.security.authorization.AccessControlList
  18:      44366054     1774642160  alluxio.collections.LockPool$Resource
  19:      44365504     1774620160  java.util.concurrent.locks.ReentrantReadWriteLock
  20:      33753754     1620180192  java.util.HashMap$Node
  21:      54690731     1312577544  java.util.Optional
  22:      52730534     1265532816  java.util.HashSet
  23:      52729676     1265512224  java.util.HashMap$KeySet
  24:      51000067     1224001608  com.google.common.cache.LocalCache$StrongValueReference
  25:      44382836     1065188064  java.util.concurrent.atomic.AtomicInteger
  26:      44367670     1064824080  java.util.concurrent.locks.ReentrantReadWriteLock$Sync$ThreadLocalHoldCounter
  27:      44365626     1064775024  java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock
  28:      44364786     1064754864  java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock

**Comment by jja725** [comment]
@jiacheliu3  is this still valid? otherwise help me close this please

**Comment by jiacheliu3** [comment]
Since this issue is inactive, we are not able to continue the investigation. So my recommendation is to upgrade to the latest Alluxio version. In the past two years we have resolved many memory and leak issues. Hope that solves your problem @gongbing851217 Thanks!
