### ISSUE TITLE
Replace Aliyun OSS SDK with JindoFS OSS SDK for OSS underfs

### ISSUE THREAD

**Issue by inetfuture** [Alluxio/alluxio#11795]
**Is your feature request related to a problem? Please describe.**

The Aliyun OSS SDK does not support native rename operation, so we all have to use copy + delete as a work around and be patient. But the JindoFS OSS SDK does(with close source native code I think), and has significant improvements on put, get, delete operations too. It comes from Aliyun EMR team, was limited to EMR product only before, just open for community use recently.

You can refer to a blog here(it's in Chinese though), the important part is the benchmark result, compared to Hadoop-OSS-SDK, which also uses Aliyun OSS SDK.

<img width="756" alt="a3fd5f28965c440990a7609a33cf7a7b" src="https://user-images.githubusercontent.com/1363189/88071853-ec701700-cba6-11ea-9cc1-76aaa46b6ad4.png">

It provides Hadoop File System interface.

**Describe the solution you'd like**

Is it possible to replace Aliyun OSS SDK with JindoFS OSS SDK to gain better performance for OSS uderfs? I'm not familiar with the code, just want to bring this up for discussion.

Thanks

**Comment by yuzhu** [comment]
@inetfuture is there a reason why we should not have both supported?

**Comment by inetfuture** [comment]
@yuzhu  I guess no, adding a new underfs is also fine, just need to document about the differences.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
