### ISSUE TITLE
JNIFuse should support write and rename operation

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#11825]
**Is your feature request related to a problem? Please describe.**
2.3

**Describe the solution you'd like**
JNI Fuse supports write and rename operation

**Describe alternatives you've considered**

**Urgency**
High, because it blocks our AI  business adopt JNIFuse

**Additional context**

**Comment by apc999** [comment]
both are supported now in JNI Fuse since 2.6.0
