### ISSUE TITLE
初始化或者用几天后会出现fuse挂载hdfs到本地的文件夹无法访问

### ISSUE THREAD

**Issue by xiesibo** [Alluxio/alluxio#11856]
**Alluxio Version:**
What version of Alluxio are you using?
2.3.0
**Describe the bug**
alluxio的数据无法访问，页面也一直转圈圈
![image](https://user-images.githubusercontent.com/28520049/88775312-2187f500-d1b7-11ea-9be7-c51a7bf067e2.png)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by apc999** [comment]
we shall be good with latest fuse implementation after v2.6.1
