### ISSUE TITLE
I cann't disable MEM

### ISSUE THREAD

**Issue by xumingming** [Alluxio/alluxio#11896]
Actually I encountered the same issue as: https://github.com/Alluxio/alluxio/issues/9968 , which seems not resolved yet, closed due to lacking of activity. We have also discussed this issue on slack: https://alluxio-community.slack.com/archives/CEXGGUBDK/p1594719543176100

**Comment by jja725** [comment]
It's more of an alias problem, could you check the process in https://github.com/Alluxio/alluxio/issues/9968? Will close it for now, feel free to reopen it and contact us if this is still valid.
