### ISSUE TITLE
Support updating debug log on K8s/Docker

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11930]
**Is your feature request related to a problem? Please describe.**
The log level should be able to be updated either during runtime or changed at start time for each container. 

**Describe the solution you'd like**
Either this is done with `alluxio logLevel` command or updating the `log4j.properties`.

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by jja725** [comment]
resolved
