### ISSUE TITLE
What version of aws s3‘s java sdk does the S3 api provided by Alluxio support?

### ISSUE THREAD

**Issue by LeeYubo** [Alluxio/alluxio#11986]
Hello, I have a question, what version of aws s3‘s java sdk does the S3 api provided by Alluxio support?
Which java sdk version i should use if i want to access my under storage data via s3 api provided by Alluxio?

**Comment by apc999** [comment]
@LeeYubo we are using `aws-java-sdk-s3:1.11.215` currently. 
You don't need to provide extra s3 java sdk as this dependency has been included in Alluxio binary.
