### ISSUE TITLE
checkconsistency cannot check &  fetch new files

### ISSUE THREAD

**Issue by magicsilence** [Alluxio/alluxio#12008]
**Alluxio Version:**
Alluxio 2.3

**Describe the bug**
`checkconsistency` does not check & fetch new files

Doc:  [checkconsistency](https://docs.alluxio.io/os/user/stable/en/operation/User-CLI.html#checkconsistency)
```
The checkConsistency command compares Alluxio and under storage metadata for a given path.
If the path is a directory, the entire subtree will be compared. 
The command returns a message listing each inconsistent file or directory 
...
```

**To Reproduce**
1. mount s3  bucket1 to path '/mnt/s3_bucket1/'
2. config hive table A location 'alluxio:////mnt/s3_bucket1/path1'(table A data already exist in s3://bucket1//path1)
3. s3://bucket1//path1  add some new files without alluxio 

**Expected behavior**
`checkconsistency` cmd can check & fetch new files

**Urgency**
alluxio metadata inconsistent with the under storage system.

**Additional context**

1. bash opertions:
       
```
[root@bigdata-test-01 client]# hadoop fs -ls s3a://bucket1/test/table_a 
Found 4 items
drwxrwxrwx   - hdfs hdfs          0 2020-08-19 03:40 s3a://bucket1/test/table_a/.hive-staging_hive_2020-08-17_09-12-14_621_192631147332299901-1
-rw-rw-rw-   1 hdfs hdfs   59208994 2020-08-17 09:16 s3a://bucket1/test/table_a/000000_0
-rw-rw-rw-   1 hdfs hdfs   21618116 2020-08-17 09:16 s3a://bucket1/test/table_a/000001_0
-rw-rw-rw-   1 hdfs hdfs   21618116 2020-08-19 03:29 s3a://bucket1/test/table_a/000001_0_cp


[root@bigdata-test-01 client]#  alluxio fs ls  /mnt/s3_bucket1/test/table_a 
drwx---rwx  hive           corp                         0       PERSISTED 08-17-2020 09:14:00:698  DIR /mnt/s3_bucket1/test/table_a/.hive-staging_hive_2020-08-17_09-12-14_621_192631147332299901-1
-rwx---rwx  corp           corp                  59208994       PERSISTED 08-17-2020 09:16:14:000   0% /mnt/s3_bucket1/test/table_a/000000_0
-rwx---rwx  corp           corp                  21618116       PERSISTED 08-17-2020 09:16:14:000   0% /mnt/s3_bucket1/test/table_a/000001_0


[root@bigdata-test-01 client]#  alluxio fs checkConsistency  /mnt/s3_bucket1/test/table_a     
/mnt/s3_bucket1/test/table_a is consistent with the under storage system.
```

2. others
And,  it will be ok when use `alluxio fs ls -R -Dalluxio.user.file.metadata.sync.interval=0  /PATH`

**Question**
I meet an exception(`alluxio.exception.AlluxioException: Active Syncing is not supported on this UFS type: s3 `) when i use startSync.  

Is there have some solutions can sync  ufs(s3) metadata when write operations without use alluxio?

**Comment by liuweibin6566396837** [comment]
I met the same problem UFS type: hdfs

**Comment by jja725** [comment]
alluxio fs ls -R -Dalluxio.user.file.metadata.sync.interval=0  /PATH is the recommended way to do metadata sync.
startSync is only supported in HDFS.
Will close it for now, feel free to reopen it and contact us if this is still valid.
