### ISSUE TITLE
Reverse proxy not worked in 2.2.3

### ISSUE THREAD

**Issue by xiashei** [Alluxio/alluxio#12021]
I have many alluxio clusters,   I  used nginx Reverse proxy in case the master changed，and I use route to distinguish different cluster.for example, http://ip:port/a redirect to alluxio cluster a,http://ip:port/b redirect to alluxio cluster b.
It works in version 1.8.2,but not work in 2.2.3.
In 1.8.2,the network is this.

![微信图片_20200824144218](https://user-images.githubusercontent.com/28834220/91012183-40dc3b80-e618-11ea-96bc-eeb517c4de5c.png)
the network will redirect to http://ip:port/a/api

![微信图片_20200824144258](https://user-images.githubusercontent.com/28834220/91012153-34f07980-e618-11ea-9d72-90e58935a926.png)

the network will redirect to http://ip:port/api, the route b is not found.In thi picture,it works because I redirect http://ip:port to cluster b,and I have only one cluster 2.2.3  and others are 1.8.2 now ,but I will updata them all to 2.2.3  in futrue.

It seems use publickPath in webpack will resolve this problem,I'm not sure if it can help.

the config is like this

```
upstream alluxioa {
    server 10.0.0.1:19999 max_fails=1;
    server 10.0.0.2:19999 backup ;
}
upstream alluxiob {
    server 10.1.0.1:19999 max_fails=1;
    server 10.1.0.2:19999 backup ;
}
server {
    listen 8888 ;
    location /a/ {
        proxy_pass http://alluxioa/;
    }
    location /b/ {
        proxy_pass http://alluxiob/;
    }

}
```
`

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
