### ISSUE TITLE
config ttl to free files in alluxio

### ISSUE THREAD

**Issue by shanying2017** [Alluxio/alluxio#12034]
version = 2.3.0 ,presto+alluxio docker container
Hi:
I'm trying  to make my files in alluxio lives for half day, which are mounted from hdfs,  and there are files writed to hdfs every 5min, my purpose is to keep every file new added in alluxio cache for 12hours, so I can always get the latest 12 hours data.

 I choose the passtive ttl way for a test

this is alluxio-site.properties:

alluxio.home=/opt/alluxio
alluxio.master.hostname=localhost
alluxio.user.block.size.bytes.default=16M
alluxio.user.file.writetype.default=MUST_CACHE
alluxio.user.hostname=localhost
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/dev/shm
alluxio.worker.tieredstore.level0.dirs.quota=4GB
alluxio.worker.tieredstore.levels=1
alluxio.user.file.create.ttl=20s
alluxio.user.file.create.ttl.action=FREE
alluxio.master.ttl.checker.interval=10s

[root@40b630be016f conf]# alluxio fs ls /input
-rw-r--r--  root           root                         6       PERSISTED 08-26-2020 09:33:07:539   0% /input/test1.txt
-rw-r--r--  root           root                         9       PERSISTED 08-26-2020 09:33:07:539   0% /input/test2.txt
[root@40b630be016f conf]# alluxio fs cat /input/test1.txt
12345
[root@40b630be016f conf]# alluxio fs ls /input
-rw-r--r--  root           root                         6       PERSISTED 08-26-2020 09:33:07:539 100% /input/test1.txt
-rw-r--r--  root           root                         9       PERSISTED 08-26-2020 09:33:07:539   0% /input/test2.txt

but after a long time it still like that:
[root@40b630be016f conf]# alluxio fs ls /input
-rw-r--r--  root           root                         6       PERSISTED 08-26-2020 09:33:07:539 100% /input/test1.txt
-rw-r--r--  root           root                         9       PERSISTED 08-26-2020 09:33:07:539   0% /input/test2.txt

I also try the command line 
[root@40b630be016f conf]# alluxio fs setTtl --action free /input 20s
TTL of path '/input' was successfully set to 20000 milliseconds, with expiry action set to FREE

but it expired immediately,not 20s, and it only work for once, I copy another file to alluxio  and it never expired. 

where am I wrong ? 
could anyone help ?
thanks

**Comment by ZacBlanco** [comment]
The configuration properties:

```
alluxio.user.file.create.ttl=20s
alluxio.user.file.create.ttl.action=FREE
```

Must be set on the client application which creates the file(s) in your cluster. That may be spark, presto, a custom application, etc.

Additionally, TTL works from the creation time of a file, so setting the TTL  to 20000ms on a file > 20s old will immediately cause the file to be freed.

**Comment by shanying2017** [comment]
thanks a lot, it works, I'll close the issuse
