### ISSUE TITLE
Alluxio fuse file i/o error

### ISSUE THREAD

**Issue by bastrik** [Alluxio/alluxio#12049]
**Alluxio Version:** branch-2.3-fuse

**Describe the bug**
If  `file` was removed from the UFS storage during sync with the remote storage, creating a new `file` with same name in UFS storage results in I/O error. There will also be a `file.tmp` left in the remote storage.

**To Reproduce**
1. copy a file (`file.txt`) to mounted storage, and wait for completion
2. while the file is being persisted, remove the file
3. create a file (`file.txt`) in mounted storage again

**Expected behavior**
First `file.txt.tmp` removed from remote storage, second `file.txt` to be created in UFS storage

**Urgency**
I/o issue on fuse client.

**Additional context**

**Comment by bastrik** [comment]
The root cause for the issue is that the `MetadataCachingBaseFileSystem` `MetadataCache` not being updated when file in UFS is removed/renamed by the fuse client. 
@apc999 , I added a cache purging logic for when a UFS file is removed/renamed, which would allow rewriting a file with the same name. The limitation is that the cache is only purged on the pod that initiated the rename/removal. What are your thoughts?

**Comment by apc999** [comment]
as discussed offline, we will discuss the cleaner solution and update you here

**Comment by apc999** [comment]
this is fixed by https://github.com/Alluxio/alluxio/pull/13790
