### ISSUE TITLE
Is there any restapi about load and free data in alluxio ?

### ISSUE THREAD

**Issue by shanying2017** [Alluxio/alluxio#12054]
version: 2.3.0

Hi:
  I see there are some restapis about web info,https://docs.alluxio.io/os/restdoc/stable/master/index.html
  Is there any restapi about load and free data in alluxio ?

**Comment by apc999** [comment]
@shanying2017 no there is not such RestAPIs currently. I am adding some as an experimental feature in near future. I will update you here.
