### ISSUE TITLE
REST API `list_status` Enhancements (max recursion, conditionals)

### ISSUE THREAD

**Issue by pedersen** [Alluxio/alluxio#12080]
**Is your feature request related to a problem? Please describe.**
I need to be able to query for subsets of the files/folders in Alluxio, but the only way to do that at this time seems to be to make multiple requests, causing slowdowns. Specifically, I'm using the Alluxio REST API and the `list_status` call does not have any way to reduce the amount of data being requested.

In my case, I'd like to start at a specific directory and recurse to a certain depth (3 or 4 being my most common depth). I've implemented a workaround for me for now, but it involves multiple trips to the REST API.

**Describe the solution you'd like**
Ideal: A way for pass some sort of condition (such as `is_folder == True` or `lastModificationTimeMs > 1234567890`) along with a maximum recursion depth, to prune the listing of data before sending it back to the caller.

Acceptable: Allowing to pass a maximum recursion depth.

**Describe alternatives you've considered**
I've already implemented a version which accomplishes this via multiple `list_status` calls, but with a large enough directory, this can result in hundreds (or even thousands) of calls. It works, but it's definitely not the most ideal solution.

**Urgency**
This is not truly urgent, but it is nice to have. Since we can do the workaround of multiple calls, we're in okay shape. Just want to be in better shape.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
