### ISSUE TITLE
RunAs no-root in alluxio change the permission of UFS

### ISSUE THREAD

**Issue by ldd91** [Alluxio/alluxio#12093]
**Alluxio Version:**
What version of Alluxio are you using?
alluxio-fuse:2.3.0-SNAPSHOT-f83f51e
**Describe the bug**
I deploy [fluid](https://github.com/fluid-cloudnative/fluid/pull/130/commits/5cf07df987c7e4ff0f46c41a49c059b7049848a6) in my cluster,in dataset.yaml,I set mountPoint: local:///tmp,owner uid=844,gid=844,and in runtime.yaml I set runAs:uid=844,gid=844,after I create the dataset and runtime,the UFS /tmp permisson all change to 844,
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
alluxio should not change the permission of UFS
**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by ldd91** [comment]
![fluid](https://user-images.githubusercontent.com/29392150/92688829-9c286080-f370-11ea-9f0c-5acccd65cf46.png)

**Comment by cheyang** [comment]
It's fixed by https://github.com/fluid-cloudnative/fluid/pull/143

**Comment by jja725** [comment]
resolved
