### ISSUE TITLE
UfS sync causing duplication of data

### ISSUE THREAD

**Issue by jainanuj07** [Alluxio/alluxio#12106]
**Alluxio Version:**
alluxio-2.3.0/ alluxio-2.4.0-Snapshot

**Describe the bug**
I am facing an issue with alluxio ufs sync.  I have some tables whose data get overwrite every hour in S3 but Alluxio not purging old files so my data is getting duplicated while I am query through Alluxio catalog in Presto.

As per doc:
Metadata sync keeps a fingerprint of each UFS file so that Alluxio can update the file if it changes. The fingerprint includes information such as file size and last modified time. If a file is modified in the UFS, Alluxio will detect this from the fingerprint, free the existing data for that file, and reload the metadata for the updated file. If a file is added or deleted in the UFS, Alluxio will update the metadata in its namespace as well.

**Data in Alluxio showing files of 2 hrs.** 

./bin/alluxio fs ls /catalog/dataplatform/tables/task/hive/
-rwx------  systemmanager  systemmanager                0       PERSISTED 09-08-2020 19:08:15:000 100% /catalog/dataplatform/tables/task/hive/_SUCCESS
-rwx------  systemmanager  systemmanager        129016033       PERSISTED 09-09-2020 08:07:55:000 100% /catalog/dataplatform/tables/task/hive/part-00000-e4b562fe-3d03-41ef-8b43-727e26c8aa1a-c000.snappy.parquet
-rwx------  systemmanager  systemmanager        128775563       PERSISTED 09-09-2020 09:08:26:000   0% /catalog/dataplatform/tables/task/hive/part-00000-e6ec7eac-f87a-498d-8429-e209a922b26e-c000.snappy.parquet
-rwx------  systemmanager  systemmanager        117141346       PERSISTED 09-09-2020 08:07:54:000 100% /catalog/dataplatform/tables/task/hive/part-00001-e4b562fe-3d03-41ef-8b43-727e26c8aa1a-c000.snappy.parquet
-rwx------  systemmanager  systemmanager        115965603       PERSISTED 09-09-2020 09:08:26:000   0% /catalog/dataplatform/tables/task/hive/part-00001-e6ec7eac-f87a-498d-8429-e209a922b26e-c000.snappy.parquet
-rwx------  systemmanager  systemmanager         91051189       PERSISTED 09-09-2020 08:07:53:000 100% /catalog/dataplatform/tables/task/hive/part-00002-e4b562fe-3d03-41ef-8b43-727e26c8aa1a-c000.snappy.parquet
-rwx------  systemmanager  systemmanager         86995170       PERSISTED 09-09-2020 09:08:23:000   0% /catalog/dataplatform/tables/task/hive/part-00002-e6ec7eac-f87a-498d-8429-e209a922b26e-c000.snappy.parquet
-rwx------  systemmanager  systemmanager         44151789       PERSISTED 09-09-2020 08:07:49:000 100% /catalog/dataplatform/tables/task/hive/part-00003-e4b562fe-3d03-41ef-8b43-727e26c8aa1a-c000.snappy.parquet
-rwx------  systemmanager  systemmanager         49253364       PERSISTED 09-09-2020 09:08:21:000   0% /catalog/dataplatform/tables/task/hive/part-00003-e6ec7eac-f87a-498d-8429-e209a922b26e-c000.snappy.parquet

**Data in S3:** 
![image](https://user-images.githubusercontent.com/13156748/93064734-8038fd80-f695-11ea-9f9f-84d6071e608e.png)

**To Reproduce**
1.  add a file to the test s3 UFS path
     s3://.../test-a
2.  force the sync (expected to show just test-a)
    ./bin/alluxio fs -Dalluxio.user.file.metadata.sync.interval=0 ls /dir/
3.  remove the existing file and add a different file
     remove s3://.../test-a 
     add s3://.../test-b
4.  Use a longer sync interval (still expected to show just test-a)
     ./bin/alluxio fs -Dalluxio.user.file.metadata.sync.interval=5m ls /dir/
5.  wait over 5 minutes
6. Use a longer sync interval to see what it returns (expected to show just test-b but it will show both test-a and test-b)
     ./bin/alluxio fs -Dalluxio.user.file.metadata.sync.interval=5m ls /dir/

**Expected behavior**
When the sync is happening it is able to detect new files that got added in S3 but it not able to detect deleted files. So it detects delete also and those files should be deleted from Alluxio. 

**Urgency**
It's a very critical issue as we can not use alluxio with this issue as all the data is incorrect because of duplication. 

**Additional context**

**Comment by apc999** [comment]
@jainanuj07  thanks for the report! We will investigate this issue

**Comment by apc999** [comment]
@yuzhu  mind take a quick look at this and see if there is anything obvious?

**Comment by yuzhu** [comment]
@jainanuj07 I was not able to reproduce this error. Could you share your alluxio configuration (be sure to remove any sensitive information)
When I tried it, deleted files in the s3 was also deleted from the alluxio space after the sync. 
```
[ec2-user@FsmetaV2S3AlluxioS3aCACHE-THROUGHdavid-masters-1 alluxio]$ bin/alluxio fs ls -R -Dalluxio.user.file.metadata.sync.interval=0 /testdir
          19640       PERSISTED 09-22-2020 13:30:48:000   0% /testdir/LICENSE3
[ec2-user@FsmetaV2S3AlluxioS3aCACHE-THROUGHdavid-masters-1 alluxio]$ aws s3  cp ./LICENSE  s3://autobots-fsmetav2s3alluxios3acache-throughdavid-lai3l6/autobots-test/testdir/LICENSE4
upload: ./LICENSE to s3://autobots-fsmetav2s3alluxios3acache-throughdavid-lai3l6/autobots-test/testdir/LICENSE4
[ec2-user@FsmetaV2S3AlluxioS3aCACHE-THROUGHdavid-masters-1 alluxio]$ aws s3  rm   s3://autobots-fsmetav2s3alluxios3acache-throughdavid-lai3l6/autobots-test/testdir/LICENSE3
delete: s3://autobots-fsmetav2s3alluxios3acache-throughdavid-lai3l6/autobots-test/testdir/LICENSE3
[ec2-user@FsmetaV2S3AlluxioS3aCACHE-THROUGHdavid-masters-1 alluxio]$ bin/alluxio fs ls -R -Dalluxio.user.file.metadata.sync.interval=1m /testdir
          19640       PERSISTED 09-22-2020 13:38:39:000   0% /testdir/LICENSE4
```

**Comment by apc999** [comment]
@gpang @yuzhu  any update on this issue? are we targeting fixing it in 2.4?
