### ISSUE TITLE
Deployment resource consultation

### ISSUE THREAD

**Issue by iwasjoker** [Alluxio/alluxio#12118]
Hello! I want to know what server resources are required to deploy alluxio on a cluster。No relevant information found in the document

**Comment by ZacBlanco** [comment]
The software requirements can be found here: https://docs.alluxio.io/os/user/stable/en/deploy/Requirements.html

Please close this issue if the information here is what you are looking for, otherwise, let us know what other information you are missing

**Comment by iwasjoker** [comment]
Thanks , I get it.
