### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by liupan664021** [Alluxio/alluxio#12131]
**Page**
https://docs.alluxio.io/os/user/stable/cn/contributor/Code-Conventions.html

**Summary**
Typo

4. 日志约定
![image](https://user-images.githubusercontent.com/27497685/93958347-e35b1c00-fd88-11ea-9c12-505426b465d3.png)
 should be 
LOG.warn(...)

**Comment by apc999** [comment]
@liupan664021  thanks for finding this issue. Fixing this typo in #12132 
next time you can create a pr like this to quickly correct our doc and we will send you a gift!
