### ISSUE TITLE
master pod consumers extremely high vm resources when running 'alluxio fs ls <folder path>'

### ISSUE THREAD

**Issue by chaowangnk1** [Alluxio/alluxio#12138]
**Alluxio Version:**
alluxio-2.3-fuse, with adls gen1 supported.

**Describe the bug**
With alluxio deployed on k8s, I mounted an adls gen1 folder (~4 TiB data, 8 files in total) and then run 'alluxio fs distributedLoad /adls' to preload data. 
Then I observed vm (the node hosting the alluxio master pod) resource usage extremely high when running 'alluxio fs ls /adls' on alluxio master pod. I didn't figure out which usage is extremely high: network, memory, cpu, disk I/O. This behavior impacts k8s health status and causes livesite issues on our k8s. 

The adls gen1 folder contains 8 files, 4TiB data in total.
Size of one file is 3.8 TiB, size of another file is 900 GiB. and the other files are all in GiB level.

**To Reproduce**
 - Deploy alluxio to k8s
 - mount an adls gen1 folder with big files.
 - on alluxio master pod, run 'alluxio fs distributedLoad <mounted path>'
 - on alluxio master pod, run 'alluxio fs ls <mounted path>'
At last step, extremely high resource usage observed. and command 'alluxio fs ls <mounted path>' may return timeout error.

**Expected behavior**
all alluxio operations should not impact k8s health status.

**Urgency**
Blocking issue for our critical perf test.

**Additional context**

**Comment by apc999** [comment]
@chaowangnk1 after `alluxio fs ls` times out, can you download master and job_master log here? they should be located at your master pod at `/opt/alluxio/logs/{master,job_master}.log`.
I want to see if there is any error in the logs. 
meanwhile, if you have threaddump of alluxio master process at that moment, that will also be very helpful.

**Comment by apc999** [comment]
@calvinjia FYI

Fixed by https://github.com/Alluxio/alluxio/pull/12315 as reported by @chaowangnk1 
The reason is that master resource utilization was kept high in sending results to different client (FUSE) after `fs ls`, without being able to  release resource timely
