### ISSUE TITLE
Broken link to AWS getting started docs

### ISSUE THREAD

**Issue by stuartsierra** [Alluxio/alluxio#12158]
**Page**

https://docs.alluxio.io/os/user/stable/en/Overview.html

**Summary**

Under "4. Getting Started",
the link labeled "ON AMAZON AWS USING AMI"
links to https://www.alluxio.io/alluxio-presto-sandbox-aws/
which returns HTTP 404 Not Found.

**Comment by apc999** [comment]
@stuartsierra  thanks for reporting this broken link.
@madanadit @Xenorith : the page https://www.alluxio.io/products/aws/alluxio-presto-sandbox-aws/
 is still alive. do you know if there any reason we remove https://www.alluxio.io/alluxio-presto-sandbox-aws/ ?

**Comment by Xenorith** [comment]
it was likely intentional; my guess is the page was moved under `aws/` path during a reorganization. i may ask for this to be changed on the website side with a redirect to handle any other backcompat, but this change should still go in imo

**Comment by apc999** [comment]
thanks for the update. let me simply fix the docs for now. Leave the website side to you folks

**Comment by apc999** [comment]
@stuartsierra the fix should be propagated to website in a day or two
