### ISSUE TITLE
distributedLoad with checking available space in alluxio

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#12162]
**Is your feature request related to a problem? Please describe.**

When running distributedLoad,  it will load the data to alluxio without checking if there are available spaces in alluxio. We'd like to make it more intelligent, it's able to check the available space before loading the data. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by jja725** [comment]
I think the semantic is loading as much as possible. Will close it for now, feel free to reopen it and contact us if this is a strong request.
