### ISSUE TITLE
LostStorageIntegrationTest failure on user 'root'

### ISSUE THREAD

**Issue by sunghopark98** [Alluxio/alluxio#12187]
**Alluxio Version:**
2.3.1

**Describe the bug**
I noticed that when I run the `LostStorageIntegrationTest` in root user, the `reportLostStorageInWorkerRegister()` and `lostStorageWhenRestart()` fail because the `setReadOnly()` for the `ssdDir` and `hddDir` doesn't stop the root user from creating the directory "/alluxioworker".

I believe this isn't a flaky test reason as I have deep dived to check the temporary directory that is created in these tests, and I saw the directory /alluxioworker inside of it when it should've been readonly.

**To Reproduce**
Switch user to "root" or whichever is the most parent user on machine:
`sudo su - root`
and then run 
`mvn clean install -DskipTests` (if not built yet)
`mvn test -Dtest=LostStorageIntegrationTest -pl tests`

**Expected behavior**
```
Failed tests:
alluxio.server.tieredstore.LostStorageIntegrationTest.reportLostStorageInWorkerRegister(alluxio.server.tieredstore.LostStorageIntegrationTest)
  Run 1: LostStorageIntegrationTest.reportLostStorageInWorkerRegister:68->checkLostStorageResults:148 expected:<1> but was:<0>
  Run 2: LostStorageIntegrationTest.reportLostStorageInWorkerRegister:68->checkLostStorageResults:148 expected:<1> but was:<0>
Tests in error:
alluxio.server.tieredstore.LostStorageIntegrationTest.lostStorageWhenRestart(alluxio.server.tieredstore.LostStorageIntegrationTest)
  Run 1: LostStorageIntegrationTest.lostStorageWhenRestart:102->checkLostStorageResults:151 NullPointer
  Run 2: LostStorageIntegrationTest.lostStorageWhenRestart:102->checkLostStorageResults:151 NullPointer
```

**Urgency**
Not urgent

**Additional context**
This does not become an issue on normal 'user's since the directory is successfully 'readonly'

**Comment by apc999** [comment]
thanks @sunghopark98 for reporting this issue

**Comment by maobaolong** [comment]
@sunghopark98 Thanks for reporting this issue, I've reproduced this issue.

**Comment by maobaolong** [comment]
@sunghopark98 Glad to share that I've correct this failure test.

I'd like to share one idea that we can use `mock technology` to instead of real method call, something like this issue, root user is a super user so it can disregard the permission, so by using `powermock`, the test result can be same no master which user executed this test.
