### ISSUE TITLE
ETag headers in S3 API Proxy

### ISSUE THREAD

**Issue by stuartsierra** [Alluxio/alluxio#12212]
**Is your feature request related to a problem? Please describe.**

Trying to read files from the [Alluxio S3 API Proxy](https://docs.alluxio.io/os/user/stable/en/api/S3-API.html) with the Python library [s3fs](https://github.com/dask/s3fs/).

When trying to read a file, the s3fs library code throws an exception with the following message:

    KeyError: 'ETag'

**Describe the solution you'd like**

I think this exception occurs because the Alluxio S3 API Proxy does not send `ETag` headers and the s3fs library expects to receive them.

It looks like the lack of `ETag` headers is a known issue based on comments at [line 397](https://github.com/Alluxio/alluxio/blob/71554a48a840ea894db58b20560f30214f663b0b/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java#L397) and [line 478](https://github.com/Alluxio/alluxio/blob/71554a48a840ea894db58b20560f30214f663b0b/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java#L478) of `S3RestServiceHandler.java`.

Ideally, the Alluxio S3 API Proxy would send an `ETag` header for `Get Object` and `Get Object Info (HEAD)` requests, and the value of that header would be an MD5 hash of the file's contents. This would match the behavior of Amazon S3 in most cases.

**Describe alternatives you've considered**

I was able to work around the problem by modifying the s3fs library to ignore the missing `ETag` header.

Another alternative would be to modify the Alluxio S3 API Proxy to send an `ETag` header that is not an MD5 hash but acts as an equivalent signal when the file changes. For example, it could be a hash of the file's modification time. There is precedent for this, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag):

> The method by which `ETag` values are generated is not specified.
> Often, a hash of the content, a hash of the last modification timestamp,
> or just a revision number is used.

**Urgency**

Low priority since a workaround is possible.

**Additional context**

Since Amazon S3 always sends `ETag` headers, there may be other S3 client libraries with a similar issue.

**Comment by maobaolong** [comment]
@stuartsierra Thanks for report this issue, would you please paste your python test code and the necessary reproduce steps?

**Comment by maobaolong** [comment]
@stuartsierra 

```python
import s3fs

if __name__ == "__main__":
    fs = s3fs.S3FileSystem(anon=False,
                           client_kwargs={
                               'endpoint_url': 'http://localhost:39999/api/v1/s3/'
                           }
                        )
    print fs.ls('abc/')
    with fs.open('abc/1212', 'rb') as f:
        print f.read()
```

This is my test code, it can successfully read the content of `/abc/1212`, so is there something important I didn't catch?

**Comment by stuartsierra** [comment]
Hi, thanks for following up @maobaolong. 

There may be different versions of the `s3fs` library with different behavior.
Here is my test environment:

* s3fs 0.5.1
* Python 3.8.2
* Ubuntu Linux 20.04 LTS

The exact versions of all the Python libraries are:

```
aiobotocore==1.1.2
aiohttp==3.7.2
aioitertools==0.7.0
async-timeout==3.0.1
attrs==20.2.0
botocore==1.17.44
chardet==3.0.4
docutils==0.15.2
fsspec==0.8.4
idna==2.10
jmespath==0.10.0
multidict==5.0.0
pkg-resources==0.0.0
python-dateutil==2.8.1
s3fs==0.5.1
six==1.15.0
typing-extensions==3.7.4.3
urllib3==1.25.11
wrapt==1.12.1
yarl==1.6.2
```

And this is my test script:

```python
import time

import s3fs

TEST_DIRECTORY = "s3fs-test"


def main():
    file_path = "%s/demo-%d.txt" % (TEST_DIRECTORY, round(time.time()))

    fs = s3fs.S3FileSystem(
        anon=False,
        client_kwargs={"endpoint_url": "http://localhost:39999/api/v1/s3/"}
    )

    if not fs.exists(TEST_DIRECTORY):
        fs.mkdir(TEST_DIRECTORY)
        print("Created directory in Alluxio:", TEST_DIRECTORY)

    with fs.open(file_path, "w") as f:
        f.write("This is demo text stored in Alluxio.\n")
    print("Wrote file in Alluxio:", file_path)

    print("Attempting to read file from Alluxio:", file_path)
    with fs.open(file_path, "r") as f:
        print(f.read())


if __name__ == "__main__":
    main()
```

Running this script produces the following output:

```
Created directory in Alluxio: s3fs-test
Wrote file in Alluxio: s3fs-test/demo-1603984413.txt
Attempting to read file from Alluxio: s3fs-test/demo-1603984413.txt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "try-alluxio-s3fs/src/try_alluxio_s3fs/demo.py", line 30, in <module>
    main()
  File "try-alluxio-s3fs/src/try_alluxio_s3fs/demo.py", line 25, in main
    with fs.open(file_path, "r") as f:
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/fsspec/spec.py", line 893, in open
    self.open(path, mode, block_size, **kwargs), **text_kwargs
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/fsspec/spec.py", line 897, in open
    f = self._open(
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/s3fs/core.py", line 402, in _open
    return S3File(self, path, mode, block_size=block_size, acl=acl,
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/s3fs/core.py", line 1326, in __init__
    super().__init__(s3, path, mode, block_size, autocommit=autocommit,
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/fsspec/spec.py", line 1224, in __init__
    self.details = fs.info(path)
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/s3fs/core.py", line 770, in info
    return maybe_sync(self._info, self, path, bucket, key, kwargs, version_id)
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 100, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "try-alluxio-s3fs/var/lib/venv/lib/python3.8/site-packages/s3fs/core.py", line 713, in _info
    'ETag': out['ETag'],
KeyError: 'ETag'
```

Hope this helps to narrow down the problem. Thanks!

**Comment by maobaolong** [comment]
@stuartsierra Thanks for your test code and output, these really helps, now I can reproduce this issue, and I create.a PR to fix this ETag header missing problem, I use modificationTimeMs as etag header now, your test code can pass now.

**Comment by stuartsierra** [comment]
@maobaolong Thank you for your help! I will add additional feedback on the Pull Request https://github.com/Alluxio/alluxio/pull/12442
