### ISSUE TITLE
alluxio.user.file.metadata.sync.interval cause error:zero copy grpcdatareader

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#12235]
alluxio 2.2
i set client config alluxio.user.file.metadata.sync.interval=60000
when i use presto to query , i turn out this error:zero copy grpcdatareader

if i change alluxio.user.file.metadata.sync.interval=0, it turn out to be ok.  (the ufs hdfs file is not changed during the test period)

**Comment by apc999** [comment]
@yuzhu  do you think these two are related, or maybe there is something else can be the root cause?

**Comment by jiemar** [comment]
> @yuzhu do you think these two are related, or maybe there is something else can be the root cause?

i restart alluxio cluster, the problem is resolved

at first the client side , alluxio.user.file.metadata.sync.interval=0   is ok
then i change alluxio.user.file.metadata.sync.interval=3600000, and restart client,  then it throw zero copy grpcdatareader error
then i change alluxio.user.file.metadata.sync.interval=0, it still throw the error
then i restart alluxio cluster, then it is ok

**Comment by jja725** [comment]
resolved
