### ISSUE TITLE
which config property can resolve the problem

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#12236]
offset in file:
 block_size:4943554
 maxufsReadconcurrency: 2147483647
 mountId: 1
 no_cache: false
 osition_ short: false
: Task alluxio. worker.grpc. GrpcExecutorssImpersc ambdas87/21223931194d92887d rejected from java.util. concurrent. ThreadPoolExecaefb38f3Running, [ pool size=4096, active threads=4096, queued tasks =0, completed tasks =101673]

i have already set alluxio.worker.network.block.reader.threads.max=4096, but when high concurrent clients, the error comes out

**Comment by apc999** [comment]
it looks like your concurrency is really high and run out of 4096 threads at a time on worker.
mind sharing your workload here? e.g. how many clients (e.g., Spark or Presto workers) and how many Alluxio workers?

**Comment by jiemar** [comment]
> it looks like your concurrency is really high and run out of 4096 threads at a time on worker.
> mind sharing your workload here? e.g. how many clients (e.g., Spark or Presto workers) and how many Alluxio workers?

presto has 162 workers, and alluxio has 7 workers
there are 50 concurrent clients submitting sql to presto at the same time

**Comment by jja725** [comment]
recommend local cache for this scenario.
Will close it for now, feel free to reopen it and contact us if this is still valid.
