### ISSUE TITLE
How to upgrade alluxio 2.2 community version to 2.3 community version?

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#12234]
How to upgrade alluxio 2.2 community version to 2.3 community version?

**Comment by apc999** [comment]
there is no specific action required to upgrade 2.2 to 2.3 --- in alluxio 2.x series, newer version is supposed to be backward compatible. let us create a documentation on upgrade

**Comment by apc999** [comment]
I was wrong, @LuQQiu just updated https://github.com/Alluxio/alluxio/blob/master/docs/en/operation/Upgrade.md
page on upgrading from 2.2 to 2.3. Please take a look there @jiemar
