### ISSUE TITLE
which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)

### ISSUE THREAD

**Issue by ljk-1993** [Alluxio/alluxio#12250]
Alluxio Version:v2.3.0

Describe the bug：

1.Although I specified JAVA_HOME in the conf/alluxio-env.sh file, there are still prompt messages  as shown in the title during installation.
2.I have installed different versions of java in my system, and I specified a specific version of java for alluxio, but it did not take effect.

Related logs：
-----------------------------------------
Starting to monitor all remote services.
-----------------------------------------
which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
--- [ OK ] The master service @ node1.bigdata is in a healthy state.

Expected behavior：
If I specify JAVA_HOME, the console should no longer display the prompt message "which: no java in...", and alluxio should use the Java version I specified

Additional context：

I modified the relevant code in the libexec/alluxio-config.sh file to solve this problem：

if [[ -z "${JAVA}" ]]; then
  if [[ -n "${JAVA_HOME}" ]] && [[ -x "${JAVA_HOME}/bin/java" ]];  then
    JAVA="${JAVA_HOME}/bin/java"
  elif [[ -n "$(which java 2>/dev/null)" ]]; then
    JAVA=$(which java)
  else
    echo "Error: Cannot find 'java' on path or under \$JAVA_HOME/bin/."
    exit 1
  fi
fi

**Comment by apc999** [comment]
thanks for reporting this issue @ljk-1993 . Can you create a pull request here to contribute your fix back? Thanks!

**Comment by apc999** [comment]
the new fix will show up in next 2.4.0 release. Let me know if you need this in other versions and I could help cherrypick @ljk-1993 . thanks for reporting and fixing this issue!
