### ISSUE TITLE
There is an extra bracket in the alluxio-config.sh file

### ISSUE THREAD

**Issue by ljk-1993** [Alluxio/alluxio#12332]
**Alluxio Version:2.4**

**Describe the bug**
In line 46 of the alluxio-config.sh file,there is an extra bracket in the elif statement。

**To Reproduce**
I'm very sorry, due to my carelessness, I added a parenthesis in the code when submitting a PR #12289  to resolve #12250  issue.

**Comment by apc999** [comment]
Fixed by #12340
