### ISSUE TITLE
 alluxio.user.file.replication.min=47 doesnot work

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#12348]
**Alluxio Version:**
2.3

**Describe the bug**
alluxio.user.file.replication.min doesnot works.
i have set alluxio.user.file.replication.min=47, but from the ui, i found the file's locations's num is 11
![alluxio1](https://user-images.githubusercontent.com/1522163/96406894-e70c8200-1212-11eb-9e48-1fc0cb0f1b6f.jpg)

**Comment by apc999** [comment]
@jiemar how many workers do you have? if you can have no more than n copies with n workers.
in addition, the replication process is running in background and it may take a while to achieve the target.

**Comment by jiemar** [comment]
> @jiemar how many workers do you have? if you can have no more than n copies with n workers.
> in addition, the replication process is running in background and it may take a while to achieve the target.

i have 47 workers  of a presto cluster.  
maybe this block  has already  visited by 11 workers of presto

**Comment by apc999** [comment]
you can wait a while and run `alluxio fsadmin getBlockInfo <blockId>` to check number of copies too.

if still not achieving 47 copies, check out the job master logs.

**Comment by jiemar** [comment]
> you can wait a while and run `alluxio fsadmin getBlockInfo <blockId>` to check number of copies too.
> 
> if still not achieving 47 copies, check out the job master logs.

i hava 47 presto workers colocated with 47 alluxio workers , but i found "remote alluxio read" is growing high.
Why alluxio client chose to remote read instead of reading from ufs and saving to local cache since i have set alluxio.user.file.replication.min=47

**Comment by jja725** [comment]
SetReplicaiton is somehow flaky and would improve it during redesign.
Will close it for now, feel free to reopen it and contact us if this is still valid.
