### ISSUE TITLE
Config WORKER_NETWORK_READER_BUFFER_SIZE_BYTES  doesn't work

### ISSUE THREAD

**Issue by chaowangnk1** [Alluxio/alluxio#12347]
**Alluxio Version:**
Alluxio-2.3-fuse

**Describe the bug**
With WORKER_NETWORK_READER_BUFFER_SIZE_BYTES set to 4MiB, we observed 20+MiB data sent to client, without client notifying data received.

**To Reproduce**

**Expected behavior**

**Urgency**

**Additional context**

**Comment by apc999** [comment]
@chaowangnk1 , how did you set it?

**Comment by chaowangnk1** [comment]
@apc999 The default value is '4MB'. I observed much more than 4MB data is pushed to fuse. 
I tried to set it to '1MB' which equals to chunk size, and the behavior didn't change.

**Comment by apc999** [comment]
@chaowangnk1 , I was asking how did you set `WORKER_NETWORK_READER_BUFFER_SIZE_BYTES`? 
this property should be set by `alluxio.worker.network.reader.buffer.size.bytes` in `alluxio-site.properties`.
did you set it in this way? 

`WORKER_NETWORK_READER_BUFFER_SIZE_BYTES` alone will not set this property

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
