### ISSUE TITLE
Alluxio fail to read files Qiniu Kodos written with THROUGH

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#12354]
**Alluxio Version:**
2.4.0

**Describe the bug**
When running `alluxio runTests`, all files written with `writeType=THROUGH` cannot be read, thus failing the `runTests` check. All the other tests are passing.

For the failed test, the `readType` does not matter. The file will succeed to write, and I can see the file on the Qiniu file viewer UI in the bucket. But Alluxio is not able to read that file in the `runTest`, after a few minutes of retries, the test fails.

The errors are 
```
2020-10-20 16:09:44,842 WARN  AbstractReadHandler - Exception occurred while reading data for read request BlockReadRequest{chunkSize=1048576, end=84, id=17381195776, openUfsBlockOptions=ufs_path: "kodo://alluxio/default_tests_files/BASIC_NON_BYTE_BUFFER_NO_CACHE_THROUGH"
offset_in_file: 0
block_size: 84
maxUfsReadConcurrency: 2147483647
mountId: 1
no_cache: true
, promote=false, sessionId=5279800197220608210, start=0, positionShort=false}. session 5279800197220608210: java.io.IOException: Qiniu kodo:get object failed errcode:400,errmsg:Bad Request
2020-10-20 16:09:47,001 WARN  AbstractReadHandler - Exception occurred while reading data for read request BlockReadRequest{chunkSize=1048576, end=84, id=17381195776, openUfsBlockOptions=ufs_path: "kodo://alluxio/default_tests_files/BASIC_NON_BYTE_BUFFER_NO_CACHE_THROUGH"
offset_in_file: 0
block_size: 84
maxUfsReadConcurrency: 2147483647
mountId: 1
no_cache: true
, promote=false, sessionId=5797768354693227370, start=0, positionShort=false}. session 5797768354693227370: java.io.IOException: Qiniu kodo:get object failed errcode:400,errmsg:Bad Request
```

**To Reproduce**
1. Deploy Alluxio on KODO following doc
1. Start Alluxio cluster
1. Execute `alluxio runTests`

**Expected behavior**
`runTests` should all pass.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jiacheliu3** [comment]
Since the THROUGH test does not work, I think the issue is in the read path of `alluxio.underfs.kodo.KodoClient` code.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
