### ISSUE TITLE
can alluxio run with two clusters which one is in keberos and another is not?

### ISSUE THREAD

**Issue by feelshana** [Alluxio/alluxio#12351]
can alluxio run with two clusters which one is in keberos and another is not?

**Comment by apc999** [comment]
@feelshana This is possible. Though I don't quite get it why you want to setup Alluxio in this way.
Could you elaborate the reason to run Alluxio in both K8s and non-k8s clusters?

**Comment by feelshana** [comment]
Thanks for your reply
there are two hadoop clusters in our company ,becase of some history reason ,the two clusters in different authentication which  one is in kerberos ,and another is simple.
the alluxio-site.xml support keberos authentication or simple ; but how can i run it with two diffrent authentication

**Comment by apc999** [comment]
Currently, no there is no way to run one alluxio cluster with two different authentication scheme inside Alluxio.
Though Alluxio can talk to two different clusters (one Hadoop cluster using SIMPLE and one using Kerberos),
by mounting both clusters into Alluxio namespace, see https://docs.alluxio.io/ee/user/stable/en/core-services/Unified-Namespace.html#nested-mount-points for mounting and https://docs.alluxio.io/ee/user/stable/en/ufs/HDFS.html#connect-to-secure-hdfs for connecting to secure HDFS.

Does this answer your question, @feelshana ?

**Comment by apc999** [comment]
Close this PR due to lack of feedback. @feelshana  you are welcome to reopen this issue once you have more update
