### ISSUE TITLE
Support forcing distributeLoad to read the latest data

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#12369]
**Alluxio Version:**
What version of Alluxio are you using?

**Describe the bug**
We'd like to distributedLoad the data with the latest metadata, does the following configuration work?

```
alluxio fs distributedLoad -Dalluxio.user.file.metadata.sync.interval=0 /
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jinhang** [comment]
mark

**Comment by apc999** [comment]
@bradyoo  do you know the answer?

**Comment by bradyoo** [comment]
I believe that this should work based on the codebase.

**Comment by apc999** [comment]
agree with @bradyoo  . @cheyang  to achieve what you are describing here as a workaround for now.

```console
$ alluxio fs loadMetadata -R /path
$ alluxio fs distributedLoad /path
```

**Comment by cheyang** [comment]
> agree with @bradyoo . @cheyang to achieve what you are describing here as a workaround for now.
> 
> ```
> $ alluxio fs loadMetadata -R /path
> $ alluxio fs distributedLoad /path
> ```

It will take a long time to process the two command. What about `alluxio fs distributedLoad -Dalluxio.user.file.metadata.sync.interval=0 /`?

**Comment by apc999** [comment]
> It will take a long time to process the two command. What about alluxio fs distributedLoad -Dalluxio.user.file.metadata.sync.interval=0 /?

Ideally we should make this happen. in reality, this requires extra setup to pass the CLI options to job service which I think is not there and not straightforward to add (@bradyoo feel free to correct me). Let me turn this into a feature request and discuss it with @calvinjia next week before get you back

**Comment by bradyoo** [comment]
@apc999 I think you are confused what I meant here.. I said that I believe 

```alluxio fs distributedLoad -Dalluxio.user.file.metadata.sync.interval=0 ``` currently works.

**Comment by TrafalgarZZZ** [comment]
@cheyang @apc999 Hi, I've tried this `alluxio fs distributedLoad -Dalluxio.user.file.metadata.sync.interval=0 /`, it works for us.

**Comment by cheyang** [comment]
Thanks, @TrafalgarZZZ
