### ISSUE TITLE
Support changing log4j.properties and metrics.properties in K8s

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#12360]
**Is your feature request related to a problem? Please describe.**
When the user needs to tune log4j or metrics settings, it's very hard in K8s.

The user can mount an updated file to `conf/log4j.properties` and `conf/metrics.properties` but that requires much manual work. Also this is impossible in helm.

**Describe the solution you'd like**
The Helm template should support updating these config files, with either a configurable mount or a configmap.

**Describe alternatives you've considered**

**Urgency**
MEDIUM. Good-to-have and helpful for deployments.

**Additional context**
https://alluxio-community.slack.com/archives/CEXGGUBDK/p1603232673280900

**Comment by jiacheliu3** [comment]
@LuQQiu FYI

**Comment by jja725** [comment]
@ssz1997  is this still valid? otherwise help me close this please

**Comment by ssz1997** [comment]
Still valid

**Comment by ssz1997** [comment]
CE300 helm chart will support editing log4j.properties and metrics.properties. See https://github.com/Alluxio/k8s-operator/pull/1. Thus closing this issue.
