### ISSUE TITLE
Alluxio ListStatus Always synchronize the metadata of files in the next level directory

### ISSUE THREAD

**Issue by cammette** [Alluxio/alluxio#12372]
**Alluxio Version:**
alluxio 2.3.0

**Describe the bug**
ths alluxio path  /nfs is nfs underfs，and the /nfs has the following directory structure:
```
/nfs/1990
/nfs/1991
...
/nfs/2020
```
There are 5000 files in every /nfs/{year} subdirectory，and list the alluxio path /nfs is very slow
```
time alluxio fs ls  -Dalluxio.user.file.metadata.sync.interval=0 /nfs
Getting directory status of 13 files or sub-directories may take a while.
           5000       PERSISTED 10-23-2020 14:12:35:000  DIR /nfs/1990
           5000       PERSISTED 10-23-2020 14:13:48:000  DIR /nfs/1991
           5000       PERSISTED 10-23-2020 14:43:05:000  DIR /nfs/1992
           5000       PERSISTED 10-23-2020 14:46:31:000  DIR /nfs/1993
           5000       PERSISTED 10-23-2020 15:08:56:000  DIR /nfs/1994
           5000       PERSISTED 10-23-2020 16:30:17:000  DIR /nfs/1995
           5165       PERSISTED 10-23-2020 17:26:54:000  DIR /nfs/1996
           5000       PERSISTED 10-23-2020 17:27:32:000  DIR /nfs/1997
           5000       PERSISTED 10-18-2020 12:11:00:000  DIR /nfs/2016
           5000       PERSISTED 10-18-2020 12:07:59:000  DIR /nfs/2017
           5000       PERSISTED 10-18-2020 12:07:01:000  DIR /nfs/2018
           5000       PERSISTED 10-18-2020 12:05:27:000  DIR /nfs/2019
           1001       PERSISTED 10-18-2020 12:03:51:000  DIR /nfs/2020
real	2m49.228s
user	0m2.127s
sys	0m2.089s
```
I don't need to browse the metadata information of subdirectories in advance, just check whether there is a new directory under / nfs，Any suggestions？

**Comment by maobaolong** [comment]
@cammette  Thanks for report this issue.

I can see each line of the subdir of /nfs contains a size, most of them are 5000, for example `/nfs/1990` contains 5000 children, without loading children of `/nfs/1990`, Alluxio cannot get the childCount, do you have any other idea?

**Comment by apc999** [comment]
@cammette  I created a patch #12441 to reduce the unnecessary overhead that introduced to read 5000 children files inside each `/nfs/{years}` dir
