### ISSUE TITLE
S3 STS credential provider

### ISSUE THREAD

**Issue by 51yu** [Alluxio/alluxio#12374]
**Is your feature request related to a problem? Please describe.**
1. enable sts credential provider as an option for s3 auth
2. aws doc - https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.html
3. sts role has advantage in cross aws account s3 access i.e aws IAM policy delegation

Sample scenario: 
Data consumer under aws account C access data provider under aws account P
aws admin of P create an assume role R for account C and share with aws admin of C.
then C share arn of R with P, now data consumer (alluxio) can access C's s3 bucket by providing assume role

**Describe the solution you'd like**
Add STSAssumeRole credential provider before default aws credential provider chain
https://github.com/Alluxio/alluxio/blob/master/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java#L129

**Other**
Sample usage of STSAssumeRole from other project
https://github.com/prestosql/presto/blob/58ee2329fe769042b72974e5b683332e09fc973e/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java#L226

**Comment by apc999** [comment]
@51yu  it is likely we will work on this feature in coming releases. @calvinjia  can have more update on this when the roadmap is finalized.

**Comment by apc999** [comment]
@51yu @tomiles  this feature will be available in Alluxio 2.8 enterprise edition.
