### ISSUE TITLE
alluxio.user config does not work

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#12402]
**Alluxio Version:**
2.3

**Describe the bug**
i have set min replicate at client's  alluxio-site.properties.  but after file was loaded,   ./alluxio fs stat ,  i found the file still min replicate is 0
![image](https://user-images.githubusercontent.com/1522163/97383410-8531d380-1908-11eb-8df5-bbee61746f2f.png)
![image](https://user-images.githubusercontent.com/1522163/97384129-09388b00-190a-11eb-91ad-5c3ff49ac7f0.png)

**Comment by apc999** [comment]
@jiemar  have you restarted alluxio master after updating `alluxio-site.properties`?
can you run respectively `bin/alluxio getConf alluxio.user.file.replication.min` and
 `bin/alluxio getConf --master alluxio.user.file.replication.min`
to find out if the configuration is taking effect?

**Comment by jiemar** [comment]
> @jiemar have you restarted alluxio master after updating `alluxio-site.properties`?
> can you run respectively `bin/alluxio getConf alluxio.user.file.replication.min` and
> `bin/alluxio getConf --master alluxio.user.file.replication.min`
> to find out if the configuration is taking effect?

i have restarted alluxio all nodes.

my client is presto, how to check presto 's config is effective.

need i set alluxio.user.*  config at alluxio server config?

**Comment by jiemar** [comment]
> @jiemar have you restarted alluxio master after updating `alluxio-site.properties`?
> can you run respectively `bin/alluxio getConf alluxio.user.file.replication.min` and
> `bin/alluxio getConf --master alluxio.user.file.replication.min`
> to find out if the configuration is taking effect?

![微信图片_20201028170652](https://user-images.githubusercontent.com/1522163/97415368-11abb880-1940-11eb-8cbf-d7565db00ff1.jpg)
as the picture shows , bin/alluxio getConf alluxio.user.file.replication.min and bin/alluxio getConf --master alluxio.user.file.replication.min     at alluxio worker node
return 47,
but the file loaded  still be min replicate=0

**Comment by apc999** [comment]
@jiemar thanks for the update. it does look like a bug to me. We will investigate. 
Just to double check, how did you load this file? e.g. by a Presto query, or by `fs load` or by `fs distributedLoad` ?

**Comment by jiemar** [comment]
> @jiemar thanks for the update. it does look like a bug to me. We will investigate.
> Just to double check, how did you load this file? e.g. by a Presto query, or by `fs load` or by `fs distributedLoad` ?

by presto query.   i set up  presto on alluxio

**Comment by maobaolong** [comment]
@jiemar @apc999  After some test and analytics, I found the following truth.
- Some create file operation will respect the `alluxio.user.file.replication.min` from alluxio-site.properties, the client load the conf from `alluxio-site.properties` and set a rpc request to alluxio master, then, alluxio master create an inode and persist the metadata which contains replicationMin from client request.
- In fact, load command just read data by `CACHE_PROMOTE` readType, `distributedLoad ` and presto query is another program, but they are also read data operation.
- The load command or some client read file operation, will not send the `alluxio.user.file.replication.min` to alluxio master, there are no any rpc request to master when read a file now, expected a `getStatus` operation. So, alluxio master never update the metadata of the inode which is loading by the current client.

As a conclusion, `alluxio.user.file.replication.min` is for client when create file, for read operation, it don't update the inode metadata by client.

The following is the MutableInodeFile structure.
```java

public final class MutableInodeFile
    implements InodeFileView {
  private List<Long> mBlocks;
  private long mBlockContainerId;
  private long mBlockSizeBytes;
  private boolean mCacheable;
  private boolean mCompleted;
  private long mLength;
  private long mPersistJobId;
  private long mShouldPersistTime;
  private int mReplicationDurable;
  private int mReplicationMax;
  private int mReplicationMin;
  private String mTempUfsPath;
}
```

**Comment by maobaolong** [comment]
@jiemar 

> i have set min replicate at client's alluxio-site.properties. but after file was loaded, ./alluxio fs stat , i found the file still min replicate is 0

The file `000000_0` was not created by client, it was created by master metadata sync, so the `min replicate` is was set by Alluxio master's `alluxio-site.properties`, not the client's `alluxio-site.properties`. For alluxio master, its `min replicate` in `alluxio-site.properties` was `0` before alluxio master start.  Client's `alluxio-site.properties` is only used for the create file rpc to alluxio master.

**Comment by apc999** [comment]
@jiemar  

In short, if you have this file loaded into alluxio the first time (Alluxio does not know this file before), `min replica` should be respected when we create the metadata of this file (i.e., an inode in Alluxio master).
However, if this file is known already to alluxio, and then the  `min replicate` at client's alluxio-site.properties is updated, this information is not sent to alluxio currently. 

one workaround is to use `fs setReplication` (https://docs.alluxio.io/os/user/stable/en/operation/User-CLI.html#setreplication) to manually change the replication number.

Let me know if my and @maobaolong 's explanation makes sense to you. Or you can reopen this issue to report what you find in case it is not what happens to you.

Thanks!
