### ISSUE TITLE
alluxio logLevel find wrong address on standby master

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#12447]
**Alluxio Version:**
2.3.0

**Describe the bug**
Run command below：
`bin/alluxio logLevel --level DEBUG --logName alluxio.client.* --target master,workers`
the command will raise a standby-master-host can not make response for logLevel request error

**Comment by jiacheliu3** [comment]
Resolved by https://github.com/Alluxio/alluxio/pull/12874
