### ISSUE TITLE
Provide a service for file system events

### ISSUE THREAD

**Issue by NilsBerger** [Alluxio/alluxio#12446]
Hi!

We are currently trying to integrate Alluxio with Apache Atlas and Apache Camel. The problem we are facing is, that Alluxio does not provide a good way to inform us about file events when a file gets added, modified and removed. We are already aware of the journal where some events are stored, but the problem is, that we would have to parse the file after every change to the file. We would like to have a service that informs us about a file event in a appropriate time. No events should be missed and the events should be fired in the right order.

**Comment by apc999** [comment]
assigning this to @calvinjia for keeping records. After discussion, we will not prioritize this feature in next coming release. I am closing this issue. but once we revisit this feature request, we can come back and talk to you again @NilsBerger  for more details.

**Comment by calvinjia** [comment]
To add, I think this is a useful feature for Alluxio to have and we will likely attempt an implementation the future, just not in the near term releases.
