### ISSUE TITLE
alluxio fs loadmetadata can't load metadata of all the files

### ISSUE THREAD

**Issue by TrafalgarZZZ** [Alluxio/alluxio#12462]
**Alluxio Version:**
What version of Alluxio are you using?
[branch-2.3-fuse](https://github.com/Alluxio/alluxio/tree/branch-2.3-fuse)

**Describe the bug**
We mounted a UFS to Alluxio, and the UFS consists of 10789180 files. However when we tried to loadMetadata all the metadata from UFS by running:
```
alluxio fs loadMetadata -R /
```
It returns the following result every time:
```
10554886 paths loaded
```
so, it seems that about 200k(10789180 - 10554886) paths were not loaded.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
Mount a UFS with large amounts of files(like 10million), and try to load all the metadata from it.

**Expected behavior**
Metadata of all the files should be loaded to Alluxio.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jja725** [comment]
try `bin/alluxio fs ls -R -Dalluxio.user.file.metadata.sync.interval=0 /`. which is the recommended way
Will close it for now, feel free to reopen it and contact us if this is still valid.
