### ISSUE TITLE
Get inconsistent result when runnning `alluxio fs du -sh` on large amounts of files

### ISSUE THREAD

**Issue by TrafalgarZZZ** [Alluxio/alluxio#12461]
**Alluxio Version:**
What version of Alluxio are you using?
[branch-2.3-fuse](https://github.com/Alluxio/alluxio/commits/branch-2.3-fuse)

**Describe the bug**

When mounting a UFS with large amounts of files, the result of `alluxio fs du -sh` is inconsistent with the actual size of the mounted UFS.

Here is the detailed version of how we got this problem:
Firstly, we mount a UFS to Alluxio. The UFS consists of about 3.8million files and the total size of it is about 92GiB.

Then we load metadata from the UFS by running `alluxio fs loadMetadata -R /`, we got result like this:
```
3804850 paths loaded
```
This is a expected result as it's consistent with the actual number of files stored in our UFS.

However, when we try to check the total size of the whole UFS by running `alluxio fs du -sh /`, it returns:
```
File Size     In Alluxio       Path
84.29GB      0B (0%)          /
```
The `84.29GB` is not consistent with the actual size of the UFS(92GiB).

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
launch an Alluxio master and mount an UFS with millions of files. Check the total size of it may reproduce it.

**Expected behavior**
Returned total size of all the files should be consistent with the actual size.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by ZacBlanco** [comment]
@TrafalgarZZZ just want to ask, have you confirmed the size in your underlying UFS is measured in GiB or GB? Technically the Alluxio UI reports the GB unit (1000^3), but in reality it is actually measuring GiB (1024^3). 

84.29GiB (90.5GB) measured by Alluxio is not quite the 92GB you say that your UFS measures, but I just want to make sure that the units you expect from your underlying storage system are consistent with the way Alluxio is reporting the storage.

**Comment by TrafalgarZZZ** [comment]
@ZacBlanco it's measured in GiB, sorry not to make it clear, already update my issue description. I think I might found something else related:

I got the "92GiB" by running `du -sh` on my underlying UFS. But I just try `du -s --apparent-size --block-size=1` and I got `90618492308(84.39GiB)`. 

This seems pretty close to what Alluxio returns me by running just `alluxio fs du -s /`:
```
File Size     In Alluxio       Path
90506724756   90368668017 (99%) /
```
But there's still a slight difference between those two. I don't know why is that happening?

**Comment by ZacBlanco** [comment]
A few other questions come to mind that I want to confirm before making the determination that the Alluxio count is wrong:

1. Are any files in your UFS updated in-place? e.g. file has the same name, but some operations circumvent Alluxio and append directly to the file, increasing the size?
1. Does the number of files reported by Alluxio match the exactly the number of files reported by the same subtree in your UFS?
1. Can you confirm the last time metadata was synced between your UFS and Alluxio? If files were added or appended to between mount and sync time, then the data could be misrepresented.

**Comment by TrafalgarZZZ** [comment]
1. There is no updates in our UFS.
2. Yes, the number of files reported by Alluxio did match the exact number of files.
3. I did `alluxio fs loadMetadata -R /` just before I run `alluxio fs du -sh`, so I think there is no updates between the two operations

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
