### ISSUE TITLE
Intermittent Issue: Short Reads from Alluxio

### ISSUE THREAD

**Issue by pedersen** [Alluxio/alluxio#12477]
**Alluxio Version:**
2.3.0

**Describe the bug**
Differing systems are reporting short reads from Alluxio. Hadoop gives an error like this:
```Caused by: java.io.IOException: alluxio.exception.FileIncompleteException: Cannot read from <REDACTED_FILE_NAME> because it is incomplete at alluxio.hadoop.HdfsFileInputStream```

The UFS has the file, it is complete, and as soon as we use `alluxio fs checkConsistency -r <REDACTED_FILE_NAME>` it gets back to working normally. Thing is, the file name changes. We've had, at this point, a couple dozen errors like it.

**To Reproduce**
Unknown

**Expected behavior**
The read to complete in full successfully.

**Urgency**
Medium. It doesn't break us entirely, but it can produce errors when trying to process data and make us go back to review/fix those errors.

**Additional context**
---alluxio-site.properties---
```# Common configuration settings for Alluxio masters, workers and clients.
alluxio.zookeeper.enabled=true
alluxio.zookeeper.address=<REDACTED>:2181,<REDACTED>:2181,<REDACTED>:2181<REDACTED>

alluxio.security.authentication.type=SIMPLE
alluxio.security.authorization.permission.enabled=true
alluxio.security.underfs.hdfs.impersonation.enabled=false
alluxio.security.login.username=<REDACTED>
alluxio.security.login.impersonation.username=<REDACTED>

alluxio.user.file.metadata.sync.interval=3m

alluxio.underfs.hdfs.remote=true

# Configuration settings for Alluxio masters.

# Note: the paths are relative to the Docker container.
alluxio.underfs.hdfs.configuration=/opt/alluxio/conf/<REDACTED>.core-site.xml:/opt/alluxio/conf/<REDACTED>.hdfs-site.xml
alluxio.master.metastore.inode.iteration.crawler.count=12
alluxio.master.rpc.executor.parallelism=24
alluxio.master.mount.table.root.ufs=hdfs://<REDACTED>:8020/

alluxio.master.journal.type=UFS
alluxio.master.journal.folder=hdfs://<REDACTED>:8020/<REDACTED>
alluxio.master.journal.checkpoint.period.entries=500000
```

**Comment by apc999** [comment]
@pedersen thanks for reporting this issue. Do you have master log, it will be helpful.

**Comment by maobaolong** [comment]
The related code is 

![image](https://user-images.githubusercontent.com/17329931/99213992-0397dc00-280a-11eb-9d2f-fdc38f27c117.png)

> The UFS has the file, it is complete, and as soon as we use alluxio fs checkConsistency -r <REDACTED_FILE_NAME> it gets back to working normally. Thing is, the file name changes.

As the information from this, let's guess the use-case of yours,

![image](https://user-images.githubusercontent.com/17329931/99214437-165ee080-280b-11eb-991b-e7da136412c7.png)

Do you update the ufs directly without through Alluxio? If so, it is possible to make inconsistent between alluxio metadata and ufs, not sure catch your point, please show me more detail to try to reproduce this issue and fix it.

**Comment by maobaolong** [comment]
@pedersen Hi, do you have any other information? master.log or a reproduce operation sequences?

**Comment by fanyunbojerry** [comment]
Hit this issue too.
My case is hbase on alluxio-2.4.1.
Something more, regionserver will crash and can't restart cause of the spliting wal.

**Comment by jja725** [comment]
try `bin/alluxio fs ls -R -Dalluxio.user.file.metadata.sync.interval=0 /`
Will close it for now, feel free to reopen it and contact us if this is still valid.
