### ISSUE TITLE
Support MemPageStore as a new PageStore type

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#12485]
**Is your feature request related to a problem? Please describe.**

Now Alluxio support a significant feature `Alluxio User-side local cache`. Now `PageStore` is an abstraction of a dump storage for pages, there are only `2` `PageStoreType` supported now, `LOCAL` and `ROCKS`, but lack of a `MEM` here.

**Describe the solution you'd like**

Support `MEM` `PageStoreType`

**Describe alternatives you've considered**

Create a implementation MemPageStore, maybe we'd better to use offheap

**Urgency**

Normal

**Additional context**

Now, we use it for presto

**Comment by maobaolong** [comment]
@apc999 Hi bin, Do you have any idea about this feature request?

**Comment by apc999** [comment]
@maobaolong this is no priority to implement the MemPageStore in Alluxio for now. 
We can discuss offline to understand better the motivation and your feedback.

**Comment by maobaolong** [comment]
Close this issue now, reopen it when we need it.
