### ISSUE TITLE
If alluxio can support index file based distributedLoad CLI

### ISSUE THREAD

**Issue by chaowangnk1** [Alluxio/alluxio#12553]
**Is your feature request related to a problem? Please describe.**
Given a UFS is mounted, we only want to distributedLoad a subset of files which are listed in a index file.

**Describe the solution you'd like**
an index file can be provided in distributedLoad CLI to specify files being loaded.

**Describe alternatives you've considered**
N/A

**Urgency**
Medium. 

**Additional context**

**Comment by calvinjia** [comment]
@chaowangnk1 If I understand correctly, you have a file with a bunch of names you want loaded. Would having a script that parses that and call distload for each file work and you are looking for a more convenient API? Or are you looking for a batch distload (ie. decrease the number of RPCs)?

**Comment by chaowangnk1** [comment]
@calvinjia yes, in one scenario, I have a file with list of files I want to load.
It would be great if we could have a convenient CLI to load files based on the index file, in one CLI run. for example, to extend CLI dtsirbutedLoad to support index file based distload.

**Comment by calvinjia** [comment]
Got it, thanks for clarifying. Would something like `distributedLoad -f <FileName>` work?

**Comment by chaowangnk1** [comment]
Definitely works for me.

**Comment by yuzhu** [comment]
@jenoudet could you take a look at this issue?

**Comment by jenoudet** [comment]
@calvinjia @chaowangnk1 should the index file live on Alluxio or is it a local file ?

**Comment by calvinjia** [comment]
@jenoudet let's start with a local file.
