### ISSUE TITLE
How to restore journal in docker

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#12571]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I'd like to try restore https://docs.alluxio.io/os/user/stable/cn/operation/Journal.html, but I have no ideas how to restore it in lluxio/integration/docker/entrypoint.sh. Could you give me an example to help me understand how to use it. Thank you.

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by jiacheliu3** [comment]
Hi @cheyang The docker `entrypoint.sh` calls `bin/launch-process` internally so I think you can specify the journal backup as https://github.com/Alluxio/alluxio/blob/a6cc9dbe396eb427b38b3596eaa7f7977270fbe1/bin/launch-process#L118. Note that you should do the same for ALL masters, the address should be different depending on whether you are using ZK or Embedded Journal for HA.

Undeniably this is not documented. Would you please let me know if this works, and I can update the doc afterwards. Hope this is helpful. Thanks!

**Comment by apc999** [comment]
@cheyang  does Jiacheng's suggestion works here?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
