### ISSUE TITLE
Display checkstyle error in the end of the build log

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#12583]
**Is your feature request related to a problem? Please describe.**
When I push a PR contains checkstyle issue, it's a bad experience to find the error log of checkstyle issue.

For example. The following build log file is downloaded from CI checks, can you easily to find the error?

[1_build.txt](https://github.com/Alluxio/alluxio/files/5600300/1_build.txt)

But for `ratis` and `ozone`, it's easy to find the error, because the error is displayed in the end of the log.

![image](https://user-images.githubusercontent.com/17329931/100305540-3ac17680-2fdc-11eb-9707-95b5004c6f6a.png)

**Describe the solution you'd like**

Display the style error in the end of the log.

**Describe alternatives you've considered**

Learn the ci checks approach about collect checkstyle issue and bring it to Alluxio. 

**Urgency**

Normal

**Additional context**

Workaround: search " error: "

**Comment by apc999** [comment]
agree @maobaolong  . is this a fix on maven file to enable some flag?
if yes, feel free to fix it

**Comment by maobaolong** [comment]
@apc999 Not clearly know how ozone and ratis fix this issue, will take a look.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
