### ISSUE TITLE
Add a maven proto file backward compatibility checker into Alluxio

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#12596]
**Is your feature request related to a problem? Please describe.**

Not sure everyone can notice how harmful a non backward compatible PR is, but I know it definitely, so we'd better to keep backward compatible for each PR, especially for proto. 

**Describe the solution you'd like**
Use a proto lock to keep proto changes are backward compatible, if not, fail the ci check.

**Describe alternatives you've considered**

Reference how apache ozone did, back port it here.

**Urgency**

Urgent(Prevent the non backward compatible PR)

**Additional context**
Reference this ticket https://issues.apache.org/jira/browse/HDDS-3595

**Comment by timmylicheng** [comment]
Thanks @maobaolong for creating this. I will working on adding proto lock to alluxio code base.

**Comment by apc999** [comment]
thanks @timmylicheng , please update us on the progress. Thanks!

**Comment by maobaolong** [comment]
@apc999 , Thanks for watching this issue, @timmylicheng will update a progress before next community dev sync.

**Comment by timmylicheng** [comment]
I plan to leverage with this maven plugin: https://github.com/salesforce/proto-backwards-compat-maven-plugin.
Ozone project has adopted it well and it helps to remind proto changes every time you do maven build. 

Still working on compilation and dependency issues. Will update with PR once issues are resolved. @apc999 @maobaolong

**Comment by maobaolong** [comment]
@timmylicheng Thank you for your improvement, As the related PR was closed yesterday, I will close this issue.

BTW, a tip for open a issue related PR, you can start with "Fix #<ISSUE_ID>" in the description of the new PR, so that the issue can be closed automatically when the PR was merged.
