### ISSUE TITLE
[Alluxio on K8s] Can alluxio be configured to use infiniband?

### ISSUE THREAD

**Issue by chaowangnk1** [Alluxio/alluxio#12600]
**Is your feature request related to a problem? Please describe.**
We have inifniband enabled in our k8s. Can alluxio be configured to use infiniband? If so, we will benefit a lot:
- Better file I/O perf
- Avoid becoming a noisy neighbor of training jobs since alluxio won't share the same network with training jobs.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Medium

**Additional context**

**Comment by gpang** [comment]
@chaowangnk1 Thanks for this request! Currently, that is not supported, but do you have any more details on this integration?

Would you be interested in working on this feature?

**Comment by chaowangnk1** [comment]
@gpang I don't have details so far. And it's not urgent for us.
I can try to think about the implementation once I understand more about infiniband setup in our k8s.

**Comment by timmylicheng** [comment]
Any updates on this?

**Comment by link89** [comment]
According to [this](https://support.mellanox.com/s/article/rdma-improves-alluxio--tachyon--remote-read-bandwidth-and-cpu-utilization-by-up-to-50-x) alluxio already support RDMA (which is built on top of IB),  I think that can be used to speed up the io perf.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
