### ISSUE TITLE
alluxio.master.journal.folder should be mentioned in the document

### ISSUE THREAD

**Issue by magicsilence** [Alluxio/alluxio#12619]
**Page**
https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-a-HA-Cluster.html
https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html

**Summary**
The `alluxio.master.journal.folder` must be a local path when use embedded journal.
And this property should be mentioned  in Section 3.1, but not.

**Comment by gpang** [comment]
@magicsilence Thanks for the issue! Here is a PR to address it: https://github.com/Alluxio/alluxio/pull/12620
