### ISSUE TITLE
Issue creating UFS file without a parent directory

### ISSUE THREAD

**Issue by bf8086** [Alluxio/alluxio#12621]
**Alluxio Version:**
2.x

**Describe the bug**
We have been using default CreateOptions when creating a UFS file. This can fail in some configuration when a file is written to an Alluxio directory not backed by a UFS one. 

**To Reproduce**
Create a file in Alluxio with CACHE_THROUGH and under a directory not backed by UFS.

**Expected behavior**
Creation should succeed and the parent directory should be created in UFS.

**Urgency**
Medium. Some data migration tasks may fail.

**Additional context**
N/A

**Comment by gpang** [comment]
fixed by https://github.com/Alluxio/alluxio/commit/81070b986ec0f5baecbd3156adace629a83df369
