### ISSUE TITLE
Add a lock healthy check service to avoid deadlock or unhandled lock

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#12633]
**Is your feature request related to a problem? Please describe.**

Fain gained lock bring a significant throughput improvement, but in a downside, it's hard to debug an issue about lock. So, we need a lock healthy check service. For some maintenance purpose, we need unlock a unhandled lock manually to work abound some corner case to keep our service high available .

**Describe the solution you'd like**

Start a service to check and make sure lock health, create a new batch shell to talk to the remote services to check or unlock some specific lock. 

**Describe alternatives you've considered**

Modify every services to start a background daemon thread to do some check work. Using the exist rpc server to listen the request about lock operation.

BTW, log more helpful necessary information, something likes callstack, thread info, lock holder info and context to identify a thread. 

**Urgency**

Normal, but as this feature can help us to diagnose lock issue, hope to have this feature as soon as posible.

**Additional context**

NO

**Comment by maobaolong** [comment]
@runzhiwang Would you like to take this ticket?

**Comment by runzhiwang** [comment]
@maobaolong Sure, thanks.

**Comment by runzhiwang** [comment]
design doc: https://docs.google.com/document/d/1j-vK7rhXKirRUa-VStybJ6kna6cv7MP0ylqiPT_r5So/edit

**Comment by maobaolong** [comment]
@gpang Do you have any suggestion about the design doc?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
