### ISSUE TITLE
Master server restarts causing reattach of DB

### ISSUE THREAD

**Issue by pabrahamusa** [Alluxio/alluxio#12634]
**Alluxio Version:**
2.4.1

**Describe the bug**
I am using Catalog Service and AWS Glue . I attached the Db from glue to Alluxio and able to see /catalog files
created in S3 bucket successfully. Also I am able to execute queries via Alluxio. However when master server get restarted
I have to detach and attach the Db again else it wont work. Is this a bug? or are there any parameters I have to set so that master server will reattach/sync/activate the catalog connection so that I should be able to use it as normal.

**To Reproduce**
 a) Attach a Glue DB 
b) Execute Query - Works
c) restart master server 
d) Execute Query - fails

**Expected behavior**
Restart of master server should not affect the DB attachment

**Comment by gpang** [comment]
@pabrahamusa I have a question. You mentioned you have to detach after the restart. Could you provider more information about that?

**Comment by pabrahamusa** [comment]
@gpang   I am running Alluxio master and worker ina Kubernetes. And if due to any reason the master Alluxio pod crashes, or restarts or change a node (which is normal in kubernetes ) . Then after restart of master the search will stop working. Then my solution is  
a) Detach the DB catalog
/opt/alluxio-2.4.1/bin/alluxio table detachdb alluxio_mydatabase
b)  Attach the Database back
/opt/alluxio-2.4.1/bin/alluxio table attachdb --db alluxio_mydatabase glue null mydatabase -o udb-glue.aws.region=us-east-1 -o udb-glue.aws.catalog.id=xxxxxxxxxx

After this two steps search will start to work. Also I have to do the same steps to see the latest data from S3. Why restarts causes master to lose DB information also why Allusio is not syncing with Glue regularly to fetch latest metadata

**Comment by gpang** [comment]
@pabrahamusa For the syncing, there is a `sync` cli command to fetch the latest metadata: https://docs.alluxio.io/os/user/stable/en/operation/User-CLI.html#sync

However, could you describe what happens when you DO NOT detach the catalog after a restart? What is the error? If you use the `table ls` command (https://docs.alluxio.io/os/user/stable/en/operation/User-CLI.html#ls-1) what does it show?

**Comment by gpang** [comment]
I don't currently have a glue setup yet, but I tried restarting the master locally, with an attached hive metastore, and the restarted Alluxio master still has all of the catalog information, without having to detach and attach.

Could you give us more information after the restart, for example, with the `alluxio table ls ...` command?

**Comment by pabrahamusa** [comment]
Thanks @gpang , I tried the ls command 

`
bash-4.4$ /opt/alluxio-2.4.1/bin/alluxio table ls alluxio_mydatabase
sb_s3_mydata
`
As you can see it  is listing correct S3 

`
bash-4.4$ /opt/alluxio-2.4.1/bin/alluxio table ls alluxio_mydatabase sb_s3_mydata
`
This print all catalog information

The issue now is when you fire a query from Presto it will not work . To make it work we have to detach and attach the DB again.  Let me try sync and see.

**Comment by pabrahamusa** [comment]
@gpang , I tried the following and I can see data appearing with out detach attach. However I have to do the sync every time if master server got restarted.

`/opt/alluxio-2.4.1/bin/alluxio table sync alluxio_mydatabase`

**Comment by apc999** [comment]
@gpang  anu idea?

**Comment by pabrahamusa** [comment]
I also tried setting this at master level however no effect
alluxio.table.catalog.udb.sync.interval: "45m"

**Comment by pabrahamusa** [comment]
@gpang @apc999  I solved it by adding one more container to do the sync, Hope this helps some till there a permanent soln

```
        - name: sync-ax-data
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
            runAsUser: {{ .Values.user }}
          command:
          - /bin/sh
          - -c
          - /opt/alluxio-2.4.1/scripts/sync_ax_data.sh
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-script-config
  labels:
    name: extra-script-config
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  sync_ax_data.sh: |-
      #!/bin/bash
      set -x
      while [ 0 = 0 ]; do
        date
        /opt/alluxio-2.4.1/bin/alluxio table sync alluxio_mydatabase
        echo "Syncing AX data ...."
        sleep 900
      done
```

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
