### ISSUE TITLE
Cannot read from abcpath because it is incomplete

### ISSUE THREAD

**Issue by xinip** [Alluxio/alluxio#12647]
alluxio fs stat alluxio://alluxio:19998//xxx/yyy/zzz/dt=2020-12-07/6/000000_0

alluxio://alluxio:19998//xxx/yyy/zzz/dt=2020-12-07/6/000000_0 is a file path.
FileInfo{fileId=6098199248895, fileIdentifier=null, name=000000_0, path=//xxx/yyy/zzz/dt=2020-12-07/6/000000_0, ufsPath=hdfs://hdfs/hive/warehouse//xxx/yyy/zzz/dt=2020-12-07/6/000000_0, length=0, blockSizeBytes=134217728, creationTimeMs=1607910793716, completed=false, folder=false, pinned=false, pinnedlocation=[], cacheable=true, persisted=true, blockIds=[], inMemoryPercentage=100, lastModificationTimesMs=1607729256078, ttl=-1, lastAccessTimesMs=1607997847785, ttlAction=DELETE, owner=hadoop, group=supergroup, mode=493, persistenceState=PERSISTED, mountPoint=false, replicationMax=-1, replicationMin=0, fileBlockInfos=[], mountId=1, inAlluxioPercentage=100, ufsFingerprint=, acl=user::rwx,group::r-x,other::r-x, defaultAcl=}
This file does not contain any blocks.

but hdfs have this file and it is completed.

How should I fix it, please help me.

alluxio version:2.3.0

**Comment by gpang** [comment]
@xinip If the file is already in HDFS, you can re-sync that particular file. To do that you can run:

```
alluxio fs -Dalluxio.user.file.metadata.sync.interval=0 stat alluxio://alluxio:19998//xxx/yyy/zzz/dt=2020-12-07/6/000000_0
```

What this will do is force a sync with the HDFS, in order to retrieve the latest metadata for that file.

**Comment by xinip** [comment]
my config interval is 0.but still error.

cat alluxio-site.properties|grep "alluxio.user.file.metadata.sync.interval"

alluxio.user.file.metadata.sync.interval=0

**Comment by gpang** [comment]
@xinip Hrmmm, can you delete the incomplete data?

```
alluxio fs rm --alluxioOnly /xxx/yyy/zzz/dt=2020-12-07/6/000000_0
```

This will remove the metadata from only Alluxio, and then you can read it again with

```
alluxio fs stat /xxx/yyy/zzz/dt=2020-12-07/6/000000_0
```

**Comment by gpang** [comment]
@xinip Yes, I verified in the code that the sync will ignore incomplete files. This is because there is an assumption that incomplete files are in the process of being written to, so the sync should not disturb incomplete files. However, in our case, it seems like the writing was maybe interrupted, so now, you can force to remove the inconsistent file by `alluxio fs rm --alluxioOnly` and then sync it from UFS again with `alluxio fs -Dalluxio.user.file.metadata.sync.interval=0 stat`.

**Comment by xinip** [comment]
alluxio fs rm --alluxioOnly also report an error, it cannot be executed successfully，because our alluxio is read-only

**Comment by gpang** [comment]
@xinip Could you describe how you "created" this (incomplete) file, if the mount is read-only? What operations did you perform to create this file?

**Comment by xinip** [comment]
my app is presto, presto on alluxio, this my alluxio config:

alluxio.master.mount.table.root.ufs=hdfs://hdfs/hive/warehouse/
alluxio.master.mount.table.root.readonly=true

**Comment by jja725** [comment]
it's recommended to use local cache with presto. Will close it for now, feel free to reopen it and contact us if this is a strong request.
