### ISSUE TITLE
Alluxio Catalog Service add support for Hive views

### ISSUE THREAD

**Issue by hycsam** [Alluxio/alluxio#12654]
**Is your feature request related to a problem? Please describe.**
Alluxio Catalog Service currently only supports syncing and querying Hive tables but not views, while we have some important Presto queries that involve querying the Hive views. Would be good to have Hive view support Alluxio Catalog.

**Describe the solution you'd like**
Create a filter on Presto client side to submit only queries that don't involve Hive views to Alluxio catalog, which is hacky.

**Describe alternatives you've considered**
Nope

**Urgency**
Some important queries involve querying Hive views

**Additional context**
Error log for table attachdb and sync command:
```
Table SOME_VIEW failed to sync: java.lang.IllegalArgumentException: Can not create a uri with a null path
```

**Comment by danielzayas** [comment]
This would be great 🙏

**Comment by apc999** [comment]
can be a good feature to add. Let me know if you are interested to contribute, @hycsam

**Comment by hycsam** [comment]
Lots of work needs to be done for the View support, I don't think I have time for this currently.

**Comment by amaliujia** [comment]
@hycsam @apc999 

As you might not have enough time, can I work on this feature?

**Comment by hycsam** [comment]
@amaliujia Sure, that would be great! Thanks!

**Comment by amaliujia** [comment]
I am working on new contributor tasks to ramp up on Alluxio repo. After that I will take a look on this issue.

/assign @amaliujia

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
