### ISSUE TITLE
Enable -Prelease for maven build by default

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#12661]
**Alluxio Version:**
2.5.0-SNAPSHOT

**Describe the bug**
-Prelease should be on by default or the output client jar may have issues to compile depending projects like Presto, due to the lack of reduced pom file

**To Reproduce**
build Alluxio without -Prelease
then build Presto using the Alluxio version built above

**Expected behavior**
It should pass

**Urgency**
Medium

**Additional context**
When turning on -Prelease, there should be only 1 working thread or the workers may hang

**Comment by jja725** [comment]
@Xenorith  is this still valid? otherwise help me close this please

**Comment by Xenorith** [comment]
current scenario: all devs can compile, but local compilation of jars + using compiled jars for presto causes issue
"fixed" scenario: local compilation of jars can be used for presto compilation, but devs that enable multiple threads for compilation will encounter a hanging process

the problem with the "fixed" scenario seems more likely to occur, and i'm not aware of any way to avoid it (ex. disable release profile if multiple threads are used), so i think we should not perform this fix.
