### ISSUE TITLE
How to use Alluxio-FUSE simultaneously on a cluster of nodes

### ISSUE THREAD

**Issue by DavidLzr** [Alluxio/alluxio#12678]
Hi everyone, I have an emergent question about Alluxio-FUSE.
**Question Description:**
Previously, I have two machines to run programs, so I just deploy Alluxio locally on each of them (they access the same MinIO bucket). And I manually mount Alluxio File System into the local file system by using FUSE on each of them.

But now I have 10 machines to use. So I have to deploy an Alluxio Cluster on these 10 machines, right? But, can I use FUSE simultaneously on these 10 machines? Or I have to manually one-by-one use FUSE to mount the Alluxio system to the local system on each of the machines?

**Comment by gpang** [comment]
Yes, you will have to mount the FUSE to each local filesystem on each machine. I don't think there is currently a script that mounts the Alluxio FUSE to all the nodes.
