### ISSUE TITLE
在COS上配置Alluxio

### ISSUE THREAD

**Issue by cloudwalkerfre** [Alluxio/alluxio#12677]
**Page**
https://docs.alluxio.io/os/user/stable/cn/ufs/COS.html

**Summary**
在COS上，bucket name是和appid拼接在一起的，包括桶列表之中也是这么显示的，比如test-mount-appid
`在该指南中，COS Bucket的名称为COS_ALLUXIO_BUCKET，在该bucket里的目录名称为COS_DATA`
这里的COS_ALLUXIO_BUCKET描述有一些误导人，因为腾讯自己的qcloud_cos.CosS3Client用的就是直接拼接后的，这里建议注明一下

**Comment by apc999** [comment]
@maobaolong  can you take a look of this issue? thanks!

**Comment by maobaolong** [comment]
@wheatxiong Please feel free to take this issue.

**Comment by wheatxiong** [comment]
> @wheatxiong Please feel free to take this issue.

OK，i will fix it as soon as possible.
