### ISSUE TITLE
Add a configure option that delete file will move file to .Trash with a TTL instead of delete

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#12688]
**Describe the solution you'd like**
Add configure options like `alluxio.user.path.remove.direct=true` and `alluxio.user.path.remove.ttl=10000`.
When `alluxio.user.path.remove.direct=true` `alluxio fs rm /path` will remove the path directly, when `alluxio.user.path.remove.direct=false` `alluxio fs rm /path` will move the path to .Trash with a TTL configured with `alluxio.user.path.remove.ttl=10000`.

**Describe alternatives you've considered**
When users run `alluxio fs rm /path` command, they will input wrong path. In this sense, we need a recover method.

**Urgency**
Remove importent files by accident brings a big lost.

**Comment by gpang** [comment]
@JySongWithZhangCe Could you add more details about this feature request in the Issue description?

**Comment by JySongWithZhangCe** [comment]
OK！

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe Could you add more details about this feature request in the Issue description?

I have updated!

**Comment by calvinjia** [comment]
One challenge with this kind of feature is needing to support it in the underlying storage system as well. This may not be possible and/or can cause consistency issues (for example if the underlying storage supports another kind of trash). Conversely, if you are using an underlying storage system that supports this, this functionality is still available, just not at the Alluxio level.

**Comment by JySongWithZhangCe** [comment]
> One challenge with this kind of feature is needing to support it in the underlying storage system as well. This may not be possible and/or can cause consistency issues (for example if the underlying storage supports another kind of trash). Conversely, if you are using an underlying storage system that supports this, this functionality is still available, just not at the Alluxio level.

I agree

**Comment by zh-jn** [comment]
> One challenge with this kind of feature is needing to support it in the underlying storage system as well. This may not be possible and/or can cause consistency issues (for example if the underlying storage supports another kind of trash). Conversely, if you are using an underlying storage system that supports this, this functionality is still available, just not at the Alluxio level.

Hi calvinjia, can you explain why/or give an example of consistency issues.
I am using alluxio.hadoop.FileSystem, because there is no namenode, then no one can cleaning the content in trash folder (e.g. /user/hive/.Trash) automatically. Or, is there exists an machanism to clean the trash?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
