### ISSUE TITLE
what is the difference between "alluxio.user.file.metadata.sync.interval" and "alluxio.user.metadata.cache.expiration.time"?

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#12680]
if i open alluxio.user.metadata.cache.enabled=true

alluxio.user.metadata.cache.expiration.time   ,    alluxio.user.file.metadata.sync.interval    will affect each other?

**Comment by maobaolong** [comment]
- `alluxio.user.metadata.cache.enabled`
If this is enabled, metadata of paths will be cached. The cached metadata will be evicted when it expires after alluxio.user.metadata.cache.expiration.time or the cache size is over the limit of alluxio.user.metadata.cache.max.size.

- `alluxio.user.metadata.cache.expiration.time`
Metadata will expire and be evicted after being cached for this time period. Only valid if the filesystem is alluxio.client.file.MetadataCachingBaseFileSystem.

- `alluxio.user.file.metadata.sync.interval`
The interval for syncing UFS metadata before invoking an operation on a path. -1 means no sync will occur. 0 means Alluxio will always sync the metadata of the path before an operation. If you specify a time interval, Alluxio will (best effort) not re-sync a path within that time interval. Syncing the metadata for a path must interact with the UFS, so it is an expensive operation. If a sync is performed for an operation, the configuration of &quot;alluxio.user.file.metadata.load.type&quot; will be ignored.

As conclusion, it is different between `cache.expiration` and `sync.interval`.

For `cache.expiration`, when `metadata.cache.enabled` is true, metadata of paths will be cached and expired.

For `sync.interval`, it is the interval for syncing UFS metadata before invoking an operation on a path.

**Comment by apc999** [comment]
thanks @maobaolong ! Let me know if you need more help @jiemar
