### ISSUE TITLE
Does Alluxio support for Iceberg table?

### ISSUE THREAD

**Issue by sontt710** [Alluxio/alluxio#12685]
Hello,

Does Alluxio support for Iceberg table?

Many Thanks!

**Comment by maobaolong** [comment]
@sontt710 I think Alluxio support the HCFS(Hadoop compatible file system) API, so that the application of Alluxio which can use HCFS API access Alluxio, Iceberg can use HCFS API access Alluxio.

Not sure I know well about `Iceberg table`, could you please  explain more detail?

**Comment by sontt710** [comment]
Hello @maobaolong,

We are researching https://iceberg.apache.org/getting-started, and trying to integrate between Alluxio vs Iceberg.

We want use Alluxio as caching layer (same as Apache Hudi & Alluxio) and use Presto for query. ( Presto > Iceberg > Alluxio > Deep Storage).

We are tried to setup, but the query go through Alluxio and pull data from deep storage, We don't know what are missing or does Alluxio support for Iceberg? Please suggest for us.

Thank @maobaolong

**Comment by HelloHorizon** [comment]
@sontt710 if you want to deploy your iceberg on HDFS, which means all table metadata(like iceberg snapshot, etc) are stored on HDFS. And at the meantime you want to use Alluxio as a caching layer for your presto, it should work. In this case, you can specify the table location on Alluxio with HDFS UFS instead of specify the table location on HDFS directly.

**Comment by pPanda-beta** [comment]
@HelloHorizon Have you tried this on any system? 

Architecture of iceberg is pretty simple : 
1. For iceberg Hadoop Tables :  presto/trinodb does not support that yet, so we are skipping that discussion here
2. For iceberg HMS Tables: HMS stores the metadata json file location, this metadata json holds all the parquet file locations (UNFORTUNATELY ABSOLUTE PATHs NO RELATIVE PATHs).
 
 So for gcs backed HMS iceberg tables : 
 
` HMS ---(1)--> metadata (gs://.../metadata.json) ---(2)--> data files (gs://.../mydata.parquet) `

Now definitely 1 will be converted to alluxio once we will start using alluxio catalog. 
But I doubt about 2. (2) happens via the iceberg-hive serde. Will that also be intercepted and converted like this?

` HMS ---(1)--> metadata (alluxio://.../metadata.json) ---(2)--> data files (alluxio://.../mydata.parquet) `
