### ISSUE TITLE
How do I execute a custom substitution policy in version1.8.1？

### ISSUE THREAD

**Issue by Syt-hdu** [Alluxio/alluxio#12683]

**Comment by apc999** [comment]
I could not understand what `substitution policy` is. Can you help elaborate?
In case you mean cache eviction policy, look for `Evictor` interface in `Evictor.java` in 1.8.1

**Comment by Syt-hdu** [comment]
> I could not understand what `substitution policy` is. Can you help elaborate?
> In case you mean cache eviction policy, look for `Evictor` interface in `Evictor.java` in 1.8.1

 framework for customized allocators，i want to ask for it

**Comment by Syt-hdu** [comment]
> I could not understand what `substitution policy` is. Can you help elaborate?
> In case you mean cache eviction policy, look for `Evictor` interface in `Evictor.java` in 1.8.1

the aim of our project  is to make a  personal cache eviction policy
