### ISSUE TITLE
Add a distributed load table shell command tools to support load table or partition

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#12690]
**Is your feature request related to a problem? Please describe.**
Add a distributed load table shell command tools to support load table or partition. So that, we can load a table or a partition into alluxio cache tier, without this feature, we have to get the location of target table, and execute distributed load, this is complex.

**Describe the solution you'd like**

Add a shell command line tool 

**Describe alternatives you've considered**

Modify the table/shell module

**Urgency**

High

**Additional context**

No

**Comment by JySongWithZhangCe** [comment]
@maobaolong May be I can assign this feature

**Comment by maobaolong** [comment]
@JySongWithZhangCe That's great!!! I can't wait to see your PR any more! 😄

**Comment by JySongWithZhangCe** [comment]
For now,  `TableShell` only support to talk to `TableMaster` with `TableMasterClient`. In this design, table shell commands are able to take options on metadata, but are hard on taking options on data. I'll implement this feature by two steps:
1. Add a implemention on `TableShell` looks like `FileSystemShell `for taking options on data. 
2. Add a `load` command on new  `TableShell`.
@gpang @maobaolong What do you think of

**Comment by gpang** [comment]
@JySongWithZhangCe That sounds reasonable.

 In this issue, can you specify the proposed what the command will look like, and how the users will interact with it?

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe That sounds reasonable.
> 
> In this issue, can you specify the proposed what the command will look like, and how the users will interact with it?

How about `alluxio table load -p year=2021/month=1/day=24,year=2020 <database>.<table>`

**Comment by JySongWithZhangCe** [comment]
@maobaolong May be you can give some good suggestions

**Comment by JySongWithZhangCe** [comment]
@apc999 What do you think?

**Comment by timmylicheng** [comment]
Sorry coming late on this issue. 
We had discussion with @maobaolong @apc999 @bradyoo one day on async load table proposal. I also wanna bring it up here and collect some thoughts. 
Please check this brief doc.
https://docs.google.com/document/d/1SA_4XNOmtjy2CZ8WEDZgmyQTMy4wkHgS2xAwRhSkc7s/edit?usp=sharing

**Comment by maobaolong** [comment]
@JySongWithZhangCe Sorry for the late reply, I think the given example is good, how about your idea? @timmylicheng , maybe we can create a chapter in the document to show how we expect to use this feature.

**Comment by JySongWithZhangCe** [comment]
@maobaolong @timmylicheng I have seen your docs, and I find that both your design and my design are not consistent with other data operation commands, like `alluxio table <db name> <table name> [-d <definition>]`. I suggest we should have more discussion and make a consistent design.
