### ISSUE TITLE
fail to determine address for FileSystemMasterClient after 1 attempts

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#12691]
**Alluxio Version:**
2.3

**Describe the bug**
fail to determine address for FileSystemMasterClient after 1 attempts
what cases the exception?

**Comment by gpang** [comment]
Hi @jiemar Thanks for the report. Could you provide more details on how to reproduce this?

**Comment by apc999** [comment]
@jiemar  can you put more details? e.g., error messages to help us?

**Comment by zhouzach** [comment]
I want to deploy  Alluxio on a Cluster with HA using Zookeeper and Shared Journal Storage.My CDH version is 3.0.0+cdh6.3.2. I build alluxio from source using commond:
```
mvn -T 2C clean install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip \
-Dcheckstyle.skip -Dlicense.skip \
-Pufs-hadoop-3 -Dufs.hadoop.version=3.0.0
or
mvn -T 2C clean install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip \
-Dcheckstyle.skip -Dlicense.skip \
-Pufs-hadoop-3 -Dufs.hadoop.version=3.0.0-cdh6.3.1
```
and put the jar to the lib directory under the Alluxio directory.
I edit alluxio-site.properties file:
```
alluxio.zookeeper.enabled=true
alluxio.zookeeper.address=pre-cdh001:2181,pre-cdh002:2181,pre-cdh003:2181
alluxio.master.journal.type=UFS
alluxio.master.journal.folder=hdfs://nameservice1/alluxio/journal/
alluxio.master.mount.table.root.ufs=hdfs://nameservice1/alluxio/data
alluxio.underfs.hdfs.configuration=/etc/hadoop/conf/core-site.xml:/etc/hadoop/conf/hdfs-site.xml
alluxio.master.security.impersonation.root.users=*
alluxio.worker.tieredstore.level0.dirs.quota=10GB
alluxio.worker.tieredstore.level1.dirs.quota=10GB
alluxio.worker.tieredstore.level2.dirs.quota=10GB
```
When run the following commond:
```./bin/alluxio fs mount \
--option alluxio.underfs.version=3.0 \
/mnt/hdfs hdfs://nameservice1
```
got a error:
Failed to determine address for FileSystemMasterClient after 1 attempts

@gpang @apc999

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
