### ISSUE TITLE
Add s3 support on alluxio runUfsIOTest

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#12703]
Is your feature request related to a problem? Please describe.
`alluxio run UfsIOTest` on object storage which is the common remote storage is more useful then hdfs which is the common local storage. To make this command more useful in the storage-calculation-separation scene, `alluxio run UfsIOTest` should support s3.

Urgency
Normal

**Comment by calvinjia** [comment]
@JySongWithZhangCe Thanks for reporting this issue, have you attempted running with an S3 mount, I recall that this is already supported.

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe Thanks for reporting this issue, have you attempted running with an S3 mount, I recall that this is already supported.

I will try ! Thx !

**Comment by HelloHorizon** [comment]
@calvinjia I have tried out the `runUfsIOTest` for s3 and it seems doesn't work(and it works for hdfs), the test will hang without meaningful logs.

**Comment by yuzhu** [comment]
assigning this to myself.  I refactored runUfsIOTest recently, so it is possible that I introduced a regression here.

**Comment by yuzhu** [comment]
#12786 should fix the issues related to s3 ufsIOtest

**Comment by JySongWithZhangCe** [comment]
Thx：） @yuzhu

**Comment by yuzhu** [comment]
@JySongWithZhangCe have you verified the fix works for you? if so, we can close this issue

**Comment by jiacheliu3** [comment]
I verified with 2.5 and this works.

**Comment by JySongWithZhangCe** [comment]
Thx @yuzhu and @jiacheliu3 !
