### ISSUE TITLE
Add Spark support on SDS

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#12706]
**Describe the solution you'd like**
Spark can run SQL on SDS.

**Urgency**
Normal

**Additional context**
Spark on Hive is slow while Spark on DFS is complex for business users. If Spark is able to work on SDS, business will become easy and fast.

**Comment by maobaolong** [comment]
@JySongWithZhangCe What version of Spark you want start to support? Do you need modify some of the codes of Spark? Something like Spark alluxio connector?

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe What version of Spark you want start to support? Do you need modify some of the codes of Spark? Something like Spark alluxio connector?

Q: What version of Spark you want start to support:?
A: Spark 3+ is needed.
Q: Do you need modify some of the codes of Spark? 
A: Compared with Presto on SDS, there will be some new codes on Spark.
Q: Something like Spark alluxio connector?
A: I guess so.

**Comment by JySongWithZhangCe** [comment]
@apc999 @gpang What do you think of?

**Comment by maobaolong** [comment]
@JySongWithZhangCe Can you explain more about why you need Spark3+? As Spark 2 is more widely used, so do you think start with spark 2 will get more use cases?

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe Can you explain more about why you need Spark3+? As Spark 2 is more widely used, so do you think start with spark 2 will get more use cases?

Due to resolve lacking of hardware resource, we decided to upgrade Spark 3+ at 2021 which is much faster then Spark 2.X  to ensure business running well. I agree with you, what's you suggest? Spark 2.2+, 2.3+, or 2.4+?

**Comment by maobaolong** [comment]
@JySongWithZhangCe Not sure the detail sub version of 2.X, but as far as I know, it would be hard if we force our user upgrade their spark application from 2.x to 3.x. I just want to know, is there some advantage if you start with Spark 3.x, other than 2.x? Does spark 3.x can decrease the efforts for spark alluxio connector?

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe Not sure the detail sub version of 2.X, but as far as I know, it would be hard if we force our user upgrade their spark application from 2.x to 3.x. I just want to know, is there some advantage if you start with Spark 3.x, other than 2.x? Does spark 3.x can decrease the efforts for spark alluxio connector?

I agree we start with Spark 2.x rather than 3.x

**Comment by maobaolong** [comment]
@JySongWithZhangCe Cool, look forward to your design doc.

**Comment by gpang** [comment]
I thought the main challenge with the older version of spark was how the catalog service could be accessed. In Presto, the connector can easily talk to a different catalog, so that is how the Alluxio presto connector can communicate with the Alluxio catalog service. However, I think Spark only communicates with hive metastore, and there wasn't a way to interact with a different catalog. I don't know if things have changed recently.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
