### ISSUE TITLE
Jni based Fuse hung when mount on macosx

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#12720]
**Alluxio Version:**

HEAD of master branch..

**Describe the bug**

Stuck when mount alluxio when enable jnifuse, but it can work well when disable jnifuse

**To Reproduce**

set `alluxio.fuse.jnifuse.enabled=true` in the alluxio-site.properties to enable jnifuse

exexute the following command line to mount alluxio /abc to local path /tmp/mp_target

```bash
integration/fuse/bin/alluxio-fuse mount /tmp/mp_target /abc

```

**Expected behavior**

see the log `AlluxioJniFuseFileSystem mounted` and can execute ls /tmp/mp_target well.

**Urgency**

High

**Additional context**

Not sure what is the root cause.

I got a stack

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at alluxio.jnifuse.LibFuse.fuse_main_real(LibFuse.java:-1)
	  at alluxio.jnifuse.AbstractFuseFileSystem.execMount(AbstractFuseFileSystem.java:108)
	  at alluxio.jnifuse.AbstractFuseFileSystem.mount(AbstractFuseFileSystem.java:88)
	  at alluxio.fuse.AlluxioJniFuseFileSystem.mount(AlluxioJniFuseFileSystem.java:603)
	  at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:123)
```

**Comment by maobaolong** [comment]
@apc999 Please take a look at this issue. Thank you for telling me Macosx cannot run jnifuse for now.

**Comment by apc999** [comment]
currently `alluxio.jnifuse.struct.FileStatTest` does not pass on MacOS with failed asserts on some fields. I am working on it

**Comment by LuQQiu** [comment]
@apc999 's PR #12836 is able to launch the JNI FUSE and run `ls` `mv` `cat`  `rm`  `vi + modify file` command successfully.
Some commands are failed:
1. cp
```
$ cp fileA fileB
cp: fileB: fchmod failed: Function not implemented
```
2. chmod 
```
$ chmod 777 fileA
chmod: Unable to change file mode on fileA: Function not implemented
```
3.  chown
```
$ chown alluxio:wheel fileA
chown: fileA: Function not implemented
```
