### ISSUE TITLE
Support redis as an UFS of Alluxio

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#12739]
**Is your feature request related to a problem? Please describe.**

We use cloud native redis as a persist storage to store the date which produced by flink, and the data source of flink is a kafka topic. 

Also, we develop an api service to provide the data which stored in the redis, and our user can get the data from the api service.

**Describe the solution you'd like**

Use Alluxio as a cache layer to enhance the locality.

![image](https://user-images.githubusercontent.com/17329931/105109106-c8aa7100-5af6-11eb-9989-8b127b5475c3.png)

**Describe alternatives you've considered**

Create a new module redis under the underfs module to support mount a redis ufs.

**Urgency**

Normal

**Additional context**
No

**Comment by xy008areshsu** [comment]
Probably add one more alluxio as caching layer near the user application

**Comment by JiamingMai** [comment]
This is a pretty good proposal, and we have some concerns to consider:
1. Are Redis's key-value pairs updated frequently in your scenario? Will inconsistencies of metadata often occur in this case?
2. How much performance can be improved for caching Redis with Alluxio (as Redis is usually fast enough)? 
3. Do you use the Redis key as the path of alluxio, and the value as the content of the file?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
