### ISSUE TITLE
support ceph fs as underlying storage

### ISSUE THREAD

**Issue by gtarcoder** [Alluxio/alluxio#12749]
Does alluxio has plan to support ceph fs as underlying storage?

**Comment by haoyuan** [comment]
@gtarcoder https://docs.alluxio.io/os/user/stable/en/ufs/Ceph.html

**Comment by gtarcoder** [comment]
> @gtarcoder https://docs.alluxio.io/os/user/stable/en/ufs/Ceph.html

It seems only ceph object store is supported, I am wondering if the ceph fs storage can be used?

**Comment by imthx** [comment]
you can mount cephfs on master node, and mount into alluxio.
for example, cephfs had been mounted at master node path /mnt/cephfs, and use ./bin/alluxio fs mount /mnt/cephfs file:///mnt/cephfs

**Comment by gtarcoder** [comment]
> you can mount cephfs on master node, and mount into alluxio.
> for example, cephfs had been mounted at master node path /mnt/cephfs, and use ./bin/alluxio fs mount /mnt/cephfs file:///mnt/cephfs

seems an interesting usage, will it accelerate access of ceph fs?

**Comment by apc999** [comment]
@gtarcoder : 
cephfs is contributed by community contributors lead by @maobaolong 
Here is the documentation:
https://docs.alluxio.io/os/user/stable/en/ufs/CephFS.html
