### ISSUE TITLE
Support Google Cloud Data Catalog as a under meta service 

### ISSUE THREAD

**Issue by amaliujia** [Alluxio/alluxio#12751]
**Is your feature request related to a problem? Please describe.**
Google cloud data catalog is a metastore service: https://cloud.google.com/data-catalog. 

We could integrate this data catalog as a under meta service, similarly as Glue and Hive metastore.

**Describe the solution you'd like**
Integrate Google cloud data catalog into the table module. Google cloud data catalog offers Java API.

**Describe alternatives you've considered**
N/A

**Urgency**
Normal

**Additional context**
N/A

**Comment by amaliujia** [comment]
I am working on new contributor tasks to ramp up on Alluxio repo. After that I may take this issue if community agrees this is useful.

**Comment by haoyuan** [comment]
Welcome!

CC @madanadit @apc999

**Comment by yuzhu** [comment]
@amaliujia are you still working on this issue? let me know if you are running into challenges.

**Comment by amaliujia** [comment]
@yuzhu 

I lowered priority of this request. Have you seen an immediate usage for Google Cloud Data Catalog?

**Comment by yuzhu** [comment]
@amaliujia no problem. I am only asking because this would make a good starter project for another member of the team if you do not plan to work on it.  That's why i wanted to check with you.

**Comment by amaliujia** [comment]
@yuzhu 

Please feel free to take this one :) This task has lower priority to me so I am not working on this in near term.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
