### ISSUE TITLE
Support libfuse 3.X in JNI-Fuse

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#12758]
**Is your feature request related to a problem? Please describe.**
JNI-Fuse supports 2.9.5 currently. 

If users want to enable `MAX_IDLE_THREADS` (libfuse supports more idle worker threads so that worker threads will not be opened and closed frequently ) functionality in 2.9.5, they need to use a modified and re-compiled libfuse 2.9.5 https://github.com/cheyang/libfuse/commits/fuse_2_9_5_customize_multi_threads_v2 

This `MAX_IDLE_THREADS` functionality is supported in libfuse 3.2 + .
Alluxio currently doesn't support libfuse 3 because of the APIs / data structures are different. 

According to @iluoeli (the author of libjnifuse), supporting libfuse 3 is possible but require non-trivial code changes in both libjnifuse and `AlluxioJNIFuseFileSystem`.

**Describe the solution you'd like**
Alluxio JNI-Fuse supports both libfuse 2 and 3. 

**Describe alternatives you've considered**

**Urgency**
This eases people's painful in using JNI-Fuse and expands the user-group.

**Additional context**

**Comment by LuQQiu** [comment]
Assign @ssz1997 
@maobaolong will need your help for design review and PR review, thanks!

**Comment by LuQQiu** [comment]
Reason 1: support rename file with overwrite. #14752

**Comment by ssz1997** [comment]
@LuQQiu Since libfuse3 has been supported, I think this can be closed.
