### ISSUE TITLE
The mounted UFS has disappeared after restart master

### ISSUE THREAD

**Issue by loovia** [Alluxio/alluxio#12776]
**Alluxio Version:**
2.4.1

**Describe the bug**
I stop master and start master one by one after I add some configuration in conf/alluxio-site.properties. 
execute `bin/alluxio fs ls /`, the mounted UFS has disappeared, why ???????

Why does Aluxio have so many different problems ???  there seems to be no feedback and there is little information available online

**Comment by liupan664021** [comment]
Did you format the master when you restart Alluxio? 
If you run `./bin/alluxio format` or `./bin/alluxio formatMaster `, the metadata will be erased.
For questions, <https://alluxio-community.slack.com> may help.

**Comment by apc999** [comment]
@loovia  can you check if the journal (which saves the file system states before you stopped master) is valid and still available after restart.

If you really want to make sure everything survives after restart, checkout Journal backup and restore (https://docs.alluxio.io/os/user/stable/en/operation/Journal.html#backing-up-the-journal) . So you can manually make sure the file system state is good across restarts.
