### ISSUE TITLE
Alluxio didn't cache data in remote worker when read them from UFS with Spark

### ISSUE THREAD

**Issue by suninuni** [Alluxio/alluxio#12806]
**Alluxio Version:**
2.4.1

**Describe the bug**

Under these cases data can be cached in worker RAM automaticly(working as expected):

- `alluxio fs load`
- Short circuit read(aka read from local worker)

But when read from UFS with Spark, data can not be cached in remote worker RAM automaticly, not working as expected.

Some configurations might be related:

```
alluxio.user.file.readtype.default=CACHE
alluxio.user.file.passive.cache.enabled=true
```

**To Reproduce**

- Deployed by helm on Kubernetes, set MEM to level 0 and no other customization.
- No local worker, only remote workers.

**Expected behavior**

Data can be cached in worker RAM automaticly when read form remote worker.

**Comment by apc999** [comment]
@suninuni this is expected if you are running `alluxio fs load /file` as by default it will load data only to the current node running this command, with a single thread.

You may want to try   `alluxio fs distributedLoad /file` which will cache files distributedly.

**Comment by suninuni** [comment]
@apc999 actually when use `alluxio fs load` or Filesystem API to read files, it will cache files distributedly in remote workers. But my problem is Alluxio can't cache files as expected when use Spark to query data through it.

Here is configs for Spark:

```java
configs.put("spark.scheduler.mode", "FAIR");
configs.put("fs.alluxio.impl", "alluxio.hadoop.FileSystem");
configs.put("hive.metastore.uris", "thrift://bigdata-hive-metastore:9083");
configs.put("spark.sql.warehouse.dir", "alluxio://alluxio-master-0:19998;alluxio-master-1:19998;alluxio-master-2:19998/");
configs.put("spark.sql.catalogImplementation", "hive");
```
