### ISSUE TITLE
how to get hadoop-2.6.0

### ISSUE THREAD

**Issue by dale-wen** [Alluxio/alluxio#12809]
我想用alluxio-2.4.1 
hdfs 使用2.6.0

根据官网编译  mvn install -Phadoop-2 -Dhadoop.version=2.6.0  -DskipTests 
编译出来 alluxio-underfs-hdfs-3.3.0-2.4.1.jar 

怎么样编译出类似 lib/alluxio-underfs-hadoop-2.6-2.4.1-1.jar 这种包？
然后我们在 alluxio.master.mount.table.root.option.alluxio.underfs.version=2.6 配置的时候能够正常挂载hdfs

**Comment by apc999** [comment]
Please run `mvn install -Pufs-hadoop-2 -Dufs.hadoop.version=2.6.0 -DskipTests`
More Examples:
https://docs.alluxio.io/os/user/stable/en/ufs/HDFS.html#supported-hdfs-versions

**Comment by apc999** [comment]
I added a patch to correct the documentation
https://github.com/Alluxio/alluxio/pull/12821/files
