### ISSUE TITLE
[Kubernetes] Enable Shortcircuit under HA mode

### ISSUE THREAD

**Issue by chaowangnk1** [Alluxio/alluxio#12807]
**Is your feature request related to a problem? Please describe.**
Given HA mode enabled for kubernetes cluster, host IP can't be specified for worker/fuse pods. In this case, short-circuit will be disabled.

**Describe the solution you'd like**
Short-circuit mechanism still works under HA mode.

**Describe alternatives you've considered**
N/A

**Urgency**
Medium.
We have kubernetes with HA mode enabled. In this setup, we can't benefit short-circuit perf improvement.

**Additional context**
N/A

**Comment by apc999** [comment]
Will be resolved by https://github.com/Alluxio/alluxio/issues/12830

**Comment by jja725** [comment]
resolved
