### ISSUE TITLE
if there can be more fine-grained file lock

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#12835]
**Is your feature request related to a problem? Please describe.**
 I try to use the following command to list file path
`alluxio fs ls path`
when the file path is being written ,the operation is slow,I can't see the writing details
**Describe the solution you'd like**
can there be more fine-grained file lock,such as hive lock or hdfs lock?and I can use command to change the lock level

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
