### ISSUE TITLE
Inability to change timeout on proxy requests

### ISSUE THREAD

**Issue by bogdanstate** [Alluxio/alluxio#12843]
**Alluxio Version:**
2.4.1-2, but I had the same bug on 2.4.0. I use Alluxio to write to MinIO.

**Describe the bug**
I am trying to write something to Alluxio via the Python client. The requests succeeds, but the proxy takes a long time to reply back. I don't know why that is, and I am not sure if this itself is a bug.

However, the immediate problem I have is that a call of the kind
```@python
opt = option.CreateFile(write_type=wire.WRITE_TYPE_MUST_CACHE)
    with client.open(path, "w", opt) as f:
        with open(tmp_dir + "/" + source_file) as source:
            f.write(source)
```
 to proxy fails with:
```
alluxio.exceptions.UnknownError: Alluxio exception: status = "UNKNOWN", message = "java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms"
```
I would like to increase this timeout to something longer. I tried fiddling with virtually all relevant-looking config parameters that were set to `30sec` by default, with little effect. Specifically, here's what I've set to 600 seconds from the default 30:
```
    alluxio.user.file.metadata.load.type=ONCE
    alluxio.user.file.passive.cache.enabled=true
    alluxio.user.file.persistence.initial.wait.time=-1
    alluxio.user.network.rpc.keepalive.timeout=600sec
    alluxio.network.connection.auth.timeout=600sec
    alluxio.user.master.polling.timeout=600sec
    alluxio.user.network.streaming.keepalive.timeout=600sec
    alluxio.user.streaming.data.timeout=600sec
    alluxio.worker.network.keepalive.time=600sec
    alluxio.worker.network.keepalive.timeout=600sec
    alluxio.master.embedded.journal.write.timeout=600sec
```

**To Reproduce**
Try writing something really big to an under-resourced Alluxio server via the Python client, and it should fail with this time-out.

**Expected behavior**
I would have expected the timeout to be longer having changed various parameters. I think I missed a config parameter but I don't know which one. 

**Urgency**
This is for a test deployment but it's driving me up the wall. So not super urgent, but very frustrating.

**Additional Context**
Same bug happens with other persistence policies (`CACHE_THROUGH`, `THROUGH`, `ASYNC_THROUGH`).

**Comment by apc999** [comment]
@bogdanstate  
1. can you try `alluxio getConf | grep 30sec` to see if this timeout is set
2. can you make sure you restart the proxy proccess after setting these timeout?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.

**Comment by haoranchuixue** [comment]
上传10MB大文件就会报这个错误，改了所有TIMEOUT都没管用。
Traceback (most recent call last):
  File "C:\Users\yymfbj\PycharmProjects\pythonProject\test_alluxio.py", line 37, in <module>
    f.write(this_file)
  File "D:\g\datahub_py_lineage\lib\site-packages\alluxio\client.py", line 679, in write
    _check_response(self.response)
  File "D:\g\datahub_py_lineage\lib\site-packages\alluxio\client.py", line 54, in _check_response
    raise exceptions.new_alluxio_exception(status, message)
alluxio.exceptions.UnknownError: Alluxio exception: status = "UNKNOWN", message = "java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms"
