### ISSUE TITLE
Make jni-fuse native to a new module to reduce the code

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#12852]
**Is your feature request related to a problem? Please describe.**

Now, we have a great module `integration/fuse`, it supply a POSIX interface through FUSE, further more, Alluxio invent a JNI-FUSE other than JNR-FUSE, and leverage it, Alluxio FUSE can be better than before.

But now, the JNI-FUSE bring the native code to alluxio repository, and many developer are not interested in JNI-FUSE native code, but they have to do some effort to prepare a build env.

**Describe the solution you'd like**

Create a single project or module, let's say it named `jni-fuse`, alluxio will deploy it into central maven repository, and supply a profile to let developer use the jni-fuse instead of build it.

**Describe alternatives you've considered**

Creaate a single project or module for JNI-FUSE.

**Urgency**

Normal

**Additional context**
NO.

**Comment by apc999** [comment]
@maobaolong  how about having a new module in `integration/jnifuse`, then making `integration/fuse` depending on this module. We can discuss it w/ more details offline.
