### ISSUE TITLE
UnsatisfiedLinkError: sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize() running Alluxio client in Spark

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#12882]
**Alluxio Version:**
2.5.0-SNAPSHOT commit 3ef0b4d719

**Describe the bug**
Spark driver log
```
21/02/19 01:48:33 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
21/02/19 01:48:33 INFO AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration {}, uri configuration {alluxio.zookeeper.address=null, alluxio.zookeeper.enabled=false, alluxio.master.hostname=alluxio-master-0, alluxio.master.rpc.addresses=null, alluxio.master.embedded.journal.addresses=null, alluxio.master.rpc.port=19998}
Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize()J
	at sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize(Native Method)
	at alluxio.conf.PropertyKey.lambda$static$8(PropertyKey.java:3044)
	at alluxio.DefaultSupplier.get(DefaultSupplier.java:34)
	at alluxio.conf.PropertyKey.getDefaultValue(PropertyKey.java:7821)
	at alluxio.conf.InstancedConfiguration.validate(InstancedConfiguration.java:549)
	at alluxio.util.ConfigurationUtils.reloadProperties(ConfigurationUtils.java:456)
	at alluxio.util.ConfigurationUtils.defaults(ConfigurationUtils.java:404)
	at alluxio.hadoop.AbstractFileSystem.initialize(AbstractFileSystem.java:512)
	at alluxio.hadoop.AbstractFileSystem.initialize(AbstractFileSystem.java:474)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
        ...
org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	...
```

**To Reproduce**
Following doc 
The spark-alluxio image is built against spark-2.4.4 with the Alluxio client jar.

Run a spark-submit with a word count job:
```
/tmp/alluxio/integration/spark/bin/spark-submit --master k8s://https://blah:6443 \
--deploy-mode cluster --name spark-alluxio --conf spark.executor.instances=1 \
--class org.apache.spark.examples.JavaWordCount \
--driver-memory 500m --executor-memory 1g \
--conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
--conf spark.kubernetes.container.image=alluxio/spark-alluxio:2.5.0-SNAPSHOT \
--conf spark.kubernetes.executor.volumes.persistentVolumeClaim.alluxio-domain.mount.path=/opt/domain \
--conf spark.kubernetes.executor.volumes.persistentVolumeClaim.alluxio-domain.mount.readOnly=true \
--conf spark.kubernetes.executor.volumes.persistentVolumeClaim.alluxio-domain.options.claimName=alluxio-worker-domain-socket \
local:///opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar \
alluxio://alluxio-master-0:19998/BLAH > /tmp/alluxio/integration/spark/spark-alluxio.log 2>&1
```

What command or job it runs does not really matter, as the Alluxio client is not able to initialize the config.

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by LuQQiu** [comment]
By adding 
```
--conf "spark.driver.extraJavaOptions=-Dapplication.home=/usr/lib/jvm/java-1.8-openjdk  -Xcheck:jni -verbose:class" \
--conf "spark.executor.extraJavaOptions=-Dapplication.home=/usr/lib/jvm/java-1.8-openjdk  -Xcheck:jni -verbose:class" \
```
to spark-submit, the error remains the same

The logs
```
[Loaded com.sun.management.OperatingSystemMXBean from /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar]
[Loaded com.sun.management.UnixOperatingSystemMXBean from /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar]
[Loaded sun.management.BaseOperatingSystemImpl from /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar]
[Loaded sun.management.OperatingSystemImpl from /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar]
```

```
bash-4.4$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```

According to https://bugs.openjdk.java.net/browse/JDK-8226575 : When Java is running in a container many of the OperatingSystemMXBean accessor methods return host based information rather than container specific data.

The bug fixed in some JDK versions 
```

Issue | Fix Version | Assignee | Priority | Status | Resolution | Resolved In Build
-- | -- | -- | -- | -- | -- | --
JDK-8236339 | 15 | Daniil Titov | P3 | Resolved | Fixed | team
JDK-8257163 | 13.0.6 | Ekaterina Vergizova | P3 | Resolved | Fixed | b02
JDK-8255833 | 13-pool | Ekaterina Vergizova | P3 | Open | Unresolved |  
JDK-8248803 | 11.0.9 | Severin Gehwolf | P3 | Resolved | Fixed | b01
JDK-8252360 | openjdk8u272 | Severin Gehwolf | P3 | Resolved | Fixed | b06
JDK-8242287 | 8u261 | Poonam Bajaj Parhar | P3 | Resolved | Fixed | b02
JDK-8246888 | emb-8u261 | Poonam Bajaj Parhar | P3 | Resolved | Fixed | team
```
Looks like openjdk 1.8.0_212 does not have the fixes

**Comment by apc999** [comment]
can we close this issue after https://github.com/Alluxio/alluxio/pull/12884 is merged? @jiacheliu3 @LuQQiu

**Comment by LuQQiu** [comment]
Yeah, this issue can be closed, @jiacheliu3 Feel free to reopen it if you think it needs deeper investigation

**Comment by jiacheliu3** [comment]
I think with #12884 we are now catching the exception so it's fine

**Comment by jiacheliu3** [comment]
> By adding
> 
> ```
> --conf "spark.driver.extraJavaOptions=-Dapplication.home=/usr/lib/jvm/java-1.8-openjdk  -Xcheck:jni -verbose:class" \
> --conf "spark.executor.extraJavaOptions=-Dapplication.home=/usr/lib/jvm/java-1.8-openjdk  -Xcheck:jni -verbose:class" \
> ```
> 
> to spark-submit, the error remains the same
> 
> The logs
> 
> ```
> [Loaded com.sun.management.OperatingSystemMXBean from /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar]
> [Loaded com.sun.management.UnixOperatingSystemMXBean from /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar]
> [Loaded sun.management.BaseOperatingSystemImpl from /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar]
> [Loaded sun.management.OperatingSystemImpl from /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar]
> ```
> 
> The container java version
> 
> ```
> bash-4.4$ java -version
> openjdk version "1.8.0_212"
> OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
> OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
> ```
> 
> The host java version
> 
> ```
> $ java -version
> openjdk version "1.8.0_242"
> OpenJDK Runtime Environment (build 1.8.0_242-b08)
> OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
> ```
> 
> According to https://bugs.openjdk.java.net/browse/JDK-8226575 : When Java is running in a container many of the OperatingSystemMXBean accessor methods return host based information rather than container specific data.
> 
> The bug fixed in some JDK versions
> 
> ```
> 
> Issue | Fix Version | Assignee | Priority | Status | Resolution | Resolved In Build
> -- | -- | -- | -- | -- | -- | --
> JDK-8236339 | 15 | Daniil Titov | P3 | Resolved | Fixed | team
> JDK-8257163 | 13.0.6 | Ekaterina Vergizova | P3 | Resolved | Fixed | b02
> JDK-8255833 | 13-pool | Ekaterina Vergizova | P3 | Open | Unresolved |  
> JDK-8248803 | 11.0.9 | Severin Gehwolf | P3 | Resolved | Fixed | b01
> JDK-8252360 | openjdk8u272 | Severin Gehwolf | P3 | Resolved | Fixed | b06
> JDK-8242287 | 8u261 | Poonam Bajaj Parhar | P3 | Resolved | Fixed | b02
> JDK-8246888 | emb-8u261 | Poonam Bajaj Parhar | P3 | Resolved | Fixed | team
> ```
> 
> Looks like Openjdk 1.8.0_212 does not have the fixes

I want to make a clarification regarding this.

When Java is running in a container `OperatingSystemMXBean ` may not return correct properties regarding the system (depending on the java version according to your link). That is true, but irrelevant to the UnsatisfiedLinkError. In other words, #12884 addressed the UnsatisfiedLinkError, and upgrading your java version will address the incorrect information from `OperatingSystemMXBean` (if it does not throw `UnsatisfiedLinkError` at all).

**Comment by apc999** [comment]
@jiacheliu3  maybe we address this in documentation? Feel free to add a FAQ
