### ISSUE TITLE
Failure to load file to Alluxio

### ISSUE THREAD

**Issue by shaoxiong2019** [Alluxio/alluxio#12885]
**Alluxio Version:**
2.3.0

**Describe the bug**
Failure to load file to Alluxio (execute command like 'alluxio fs load ${path}')
Failure to generate file split in MR job, error message as follow
![image](https://user-images.githubusercontent.com/7252486/108458272-4bb61700-72af-11eb-9337-78ed1f1c6362.png)
![image](https://user-images.githubusercontent.com/7252486/108458359-7f913c80-72af-11eb-8d15-b0a4298123c3.png)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
![image](https://user-images.githubusercontent.com/7252486/108458191-18738800-72af-11eb-8cf4-58f93d5a6f42.png)

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by calvinjia** [comment]
@shaoxiong2019 Thanks for reporting this issue. I had a few questions -
Does this only occur after you use the load command? 
Does this occur for all files or only this particular file?
What is the output of running `bin/alluxio fs stat` on that file?

**Comment by apc999** [comment]
@shaoxiong2019 do you have more information to help us investigate your issue?

**Comment by yuzhu** [comment]
@shaoxiong2019 ping? if you have more information, please share with us. thanks.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
