### ISSUE TITLE
Alluxio didn't cache data when read from parquet table with Spark and Hive

### ISSUE THREAD

**Issue by suninuni** [Alluxio/alluxio#12904]
**Alluxio Version:**
2.4.1

**Describe the bug**
Alluxio didn't cache data when read from parquet table with Spark and Hive.

**To Reproduce**

- create table `test` which `STORED AS PARQUET` and mock some data.
- exec `select * from test`.
- `alluxio fs ls /test` show In-Alluxio 0%.

**Expected behavior**
After `select`, alluxio cache all data to memory and show In-Alluxio 100% which same as read data from TEXTFILE.

**Comment by calvinjia** [comment]
@suninuni This should work as you expect. One difference is parquet files are not read sequentially, so the data will not be cached in band of the initial read operations but asynchronously on the worker. Here is some related documentation - https://docs.alluxio.io/ee/user/stable/en/operation/Performance-Tuning.html#async-block-caching

**Comment by apc999** [comment]
feel free to reopen this issue if you still have questions

**Comment by suninuni** [comment]
@apc999 @calvinjia Actually my test data only 14.45KB, but it still can't be cached asynchronously and show In-Alluxio 100% as expect.

![image](https://user-images.githubusercontent.com/7345529/110053520-89796c00-7d94-11eb-979b-d2af01fa9e86.png)

And according to the increased metrics `Under Filesystem Read`, these data is indeed read from UFS.

In another big table which has 903 parquet file, after `select`, I found a block which In-Alluxio changed to 29% and it didn't increase any more. Are those behavior worked as expected?

![image](https://user-images.githubusercontent.com/7345529/110054841-cfcfca80-7d96-11eb-8753-20d1779559ee.png)
