### ISSUE TITLE
Single master ask followers for snapshot

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#12936]
**Alluxio Version:**
Alluxio master

**Describe the bug**
In a single master node scenario, the master will still ask followers for snapshots
![image2](https://user-images.githubusercontent.com/25273483/109074004-feb9b280-76ab-11eb-8523-744a6ad25be4.png)

**To Reproduce**
Create a single master cluster with embedded journal, have a large amount of journal write operations against the cluster.
The master will still try to ask followers for snapshots.

**Expected behavior**
The master in the single master cluster should not ask followers for snapshots.

**Urgency**
Not urgent

**Additional context**

**Comment by bf8086** [comment]
The error complains about no follower to take snapshots of the journal. We can turn off the error for single master given no follower is there anyway. On the other hand, users need to know that without snapshots the journal will grow unboundedly and it would result in long startup time and failover time unless they perform manual stop-the-world snapshot.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
