### ISSUE TITLE
wget --spider on api endpoint results in glassfish error

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#12942]
**Alluxio Version:**
alluxio version 2.4.1-2

**Context**
I'm trying to use the [Master](https://docs.alluxio.io/os/restdoc/stable/master/index.html) and [Worker](https://docs.alluxio.io/os/restdoc/stable/worker/index.html) REST API to build [Docker container healthchecks](https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck).

E.g. by using:
- `wget --spider http://alluxio-master:19999/api/v1/master/info` to check if the master is up,
- `wget --spider http://alluxio-worker:30000/api/v1/worker/info` to check if the worker is up.

Using [`wget --spider`](https://www.gnu.org/software/wget/manual/wget.html#Logging-and-Input-File-Options) will not download the pages, just check that they are there.

**Describe the bug**
Running `wget --spider http://alluxio-master:19999/api/v1/master/info` (for example as a Docker healthcheck) results in  glassfish errors in the logs after a while.

Summary of the error logs:
```
org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
SEVERE: An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
...
Caused by: org.eclipse.jetty.io.EofException
...
Caused by: java.io.IOException: Connection reset by peer
...
```
The full error trace can be found at [error.log](https://github.com/Alluxio/alluxio/files/6045032/error.log)

**To Reproduce**
The problem occurs non-deterministically. Typically the best way is to start a docker-compose deployment with a `healthcheck` using `wget --spider` against the REST APIs, for example as in [this docker-compose.yml file](https://gist.github.com/peterroelants/41ca47634fb4ba15795b85f8dea5f038#file-docker-compose-yml ). (However, I also got it to produce the error by using the commands from the [Docker tutorial](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html).)

Then exec into the worker container: `docker exec -it alluxio-worker /bin/bash` and run a few commands. E.g.
```
alluxio runTests
alluxio fs ls /
alluxio fs copyFromLocal /opt/alluxio/LICENSE /LICENSE
alluxio fs ls /
alluxio fs cat /LICENSE
```

After repeating this once or twice the `alluxio-master` logs will start producing the error. Once it produces the error it will keep producing the error when using `wget --spider`.

**Expected behavior**
- `wget --spider` on API endpoints works without producing errors in the logs. (please note that regular wget works).
- Alluxio webserver fails consistently. (This is maybe the thing that worries me the most, the fact that the webserver only starts producing errors after a while.)

**Urgency**
Low priority, the webservice only produces errors, however it seems to keep on working). The main issue is that my logs are getting spammed with these messages.

**Additional context**
- [error.log](https://github.com/Alluxio/alluxio/files/6045032/error.log)

**Comment by apc999** [comment]
@peterroelants  Hi , it seems you are working on some projects pretty involved with Alluxio & Docker. Thanks for letting us know and reporting these issues! I'd like to have some discussion with you to consolidate the effort to improve Alluxio.
You can find me on Alluxio slack (www.alluxio.io/slack)

**Comment by peterroelants** [comment]
Related feature request on providing health-checks for different Alluxio services: https://github.com/Alluxio/alluxio/issues/13075

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
