### ISSUE TITLE
Alluxio Docker volume plugin

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#12973]
**Is your feature request related to a problem? Please describe.**
I would be great to be able to directly mount an Alluxio FS as a [Docker volume](https://docs.docker.com/storage/volumes/). This would avoid the need to consistently setup an Alluxio FUSE mount in a shared mount folder, and provide convenient access to Alluxio FS from Docker.

**Describe the solution you'd like**
Have a [Docker volume plugin](https://docs.docker.com/engine/extend/plugins_volume/) to allow to directly mount Alluxio folders in a container. This could for example look like:
```
docker volume create --driver=alluxio alluxio_volume -o .....
docker container run -it --volume alluxio_volume:/data ubuntu sh
```
This would avoid spinning up the [alluxio-fuse](https://hub.docker.com/r/alluxio/alluxio-fuse/) service mounting Alluxio via fuse in a host folder.

**Describe alternatives you've considered**
I'm currently using the [alluxio-fuse](https://hub.docker.com/r/alluxio/alluxio-fuse/) container as an alternative.

**Urgency**
Nice-to-have.

**Additional context**
Relevant examples from other technologies:
- [sshFS Docker volume plugin](https://github.com/vieux/docker-volume-sshfs).
- [JuiceFS Docker Plugin documentation](https://juicefs.com/docs/en/use_juicefs_in_docker.html)

Please note: I might be missing some context about the feasibility of having Alluxio as a Docker volume plugin.

**Comment by apc999** [comment]
@cheyang  do you know if https://github.com/fluid-cloudnative/fluid is supporting something like this with Alluxio?
CC @jiacheliu3  FYI, in case we are going to start a K8s/Docker related SIG

**Comment by jja725** [comment]
@ssz1997  is this still valid? otherwise help me close this please
