### ISSUE TITLE
WebUI Metrics graphs all have % as Y axis

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#12989]
**Alluxio Version:**
2.5.0-SNAPSHOT

**Describe the bug**
The metrics graphs all have Y-axis % (0-100) when some values are raw throughput numbers.

**To Reproduce**
Open the metrics UI page.

**Expected behavior**
The Y-axis should match the type of data being displayed.

**Urgency**
High, many graphs are difficult to read / unreadable.

**Comment by tieujason330** [comment]
@calvinjia for raw throughput numbers, what should the y-axis be labeled as? `Throughput`?
