### ISSUE TITLE
Workers can actively deregister itself to leave the Alluxio cluster in kubernetes environment

### ISSUE THREAD

**Issue by TrafalgarZZZ** [Alluxio/alluxio#12998]
**Is your feature request related to a problem? Please describe.**

In kubernetes environment, it is not uncommon to terminate some alluxio-worker pods or migrate them to other nodes to remodify the max storage resources that the Alluxio cluster can use. As far as I know, for now Alluxio uses heartbeats to check whether a worker is lost. I think this is not necessary when Alluxio worker is terminated in a kubernetes environment since it will never rejoin the cluster.

**Describe the solution you'd like**

I wonder is it possible to implement an operation through which the Alluxio worker can actively deregister itself and let the Alluxio master know the worker will leave the Alluxio cluster soon, so no need for the master to keep information about that worker. Moreover, I think it would be even better if during this deregistering process,  the worker can transfer its own data cache to other workers to avoid data loss.

**Urgency**
I think this feature can help Alluxio enhance its elasticity when running in a kubernetes env.

**Additional context**
None

**Comment by calvinjia** [comment]
@TrafalgarZZZ Thanks for suggesting this feature. When we design a tighter integration with K8s for elasticity, this will definitely be considered as an option for scaling down clusters. I expect to see more improvements on the K8s side in upcoming releases.
CC @jiacheliu3

**Comment by jiacheliu3** [comment]
@calvinjia @TrafalgarZZZ this is a good suggestion. I'm not sure how feasible it is, as in K8s a worker pod can be evicted just based on the memory that it's using, or just to make space for other pods. If there's a way to make the worker aware that it is going to be killed, i think it's feasible that we do this.
@madanadit do you happen to know anything like a pre-shutdown hook in k8s?

**Comment by madanadit** [comment]
@jiacheliu3 we use a pre-stop hook for the FUSE daemonset: https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml#L107

**Comment by jiacheliu3** [comment]
@madanadit Thanks! Assigning the issue to myself then, we shall revisit this in the near future.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
