### ISSUE TITLE
Can't visit master and worker web page

### ISSUE THREAD

**Issue by xieydd** [Alluxio/alluxio#13009]
**Alluxio Version:**
What version of Alluxio are you using?
```
alluxio version -r
2.5.0-SNAPSHOT-797ece179773a1c559fb7898f81dc606fc7f8946
```
**Describe the bug**
When i run alluxio in macos local, i can't visit master and worker , and i already set `alluxio.web.ui.enabled=true` in alluxio-site.properties
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
```
git clone https://github.com/Alluxio/alluxio.git
cd alluxio
sudo mvn -T 32C clean install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Dlicense.skip
./bin/alluxio-start.sh local SudoMount

$ ./bin/alluxio fsadmin report
Alluxio cluster summary:
    Master Address: localhost:19998
    Web Port: 19999
    Rpc Port: 19998
    Started: 03-05-2021 17:50:22:248
    Uptime: 0 day(s), 0 hour(s), 11 minute(s), and 40 second(s)
    Version: 2.5.0-SNAPSHOT
    Safe Mode: false
    Zookeeper Enabled: false
    Live Workers: 1
    Lost Workers: 0
    Total Capacity: 10.67GB
        Tier: MEM  Size: 10.67GB
    Used Capacity: 0B
        Tier: MEM  Size: 0B
    Free Capacity: 10.67GB
```
**Expected behavior**
can visit web

**Urgency**
Describe the impact and urgency of the bug.
It's not too urgent.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
