### ISSUE TITLE
As for turning on the short circuit function, the memory capacity of the worker decreases

### ISSUE THREAD

**Issue by fantastic2085** [Alluxio/alluxio#13022]
**Alluxio Version:**
What version of Alluxio are you using?
2.4.1-1

**Describe the bug**
**The following figure shows the memory capacity of the worker after the short circuit function is turned on:**
![image](https://user-images.githubusercontent.com/4116773/110288651-4f71c980-8023-11eb-9825-88dccdd69294.png)
**Here is the alluxio-worker-daemonset.yaml and alluxio-configmap.yaml The short circuit function uses hostpath:**
[alluxio-worker-daemonset.txt](https://github.com/Alluxio/alluxio/files/6099627/alluxio-worker-daemonset.txt)
[alluxio-configmap.txt](https://github.com/Alluxio/alluxio/files/6099645/alluxio-configmap.txt)

**However, turn off the short circuit function:**
![image](https://user-images.githubusercontent.com/4116773/110289107-ea6aa380-8023-11eb-8186-ea7fb399b710.png)
Here is the alluxio-worker-daemonset.yaml and alluxio-configmap.yaml ：
[alluxio-worker-daemonset.txt](https://github.com/Alluxio/alluxio/files/6099649/alluxio-worker-daemonset.txt)
[alluxio-configmap.txt](https://github.com/Alluxio/alluxio/files/6099652/alluxio-configmap.txt)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
**### **I want to know why the memory capacity drops when the short circuit function is turned on, and where is the memory?****

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by ZhuTopher** [comment]
Hey thanks for submitting this issue! I'm going to look into this for you, but before I do are you using Helm to generate those manifest files? If so could you provide the `config.yaml` you are using when you install the alluxio Helm chart? Both for short-circuit enable and disabled if you can.

Also if you are using Helm, could you run `kubectl get pvc` and `kubectl get pv` when you have short-circuit enabled and disabled and show me the outputs? Thanks!

**Comment by fantastic2085** [comment]
> Hey thanks for submitting this issue! I'm going to look into this for you, but before I do are you using Helm to generate those manifest files? If so could you provide the `config.yaml` you are using when you install the alluxio Helm chart? Both for short-circuit enable and disabled if you can. If not could you provide any other k8s resource manifests you used to deploy Alluxio in k8s (eg: `alluxio-worker-pvc.yaml` maybe?)
> 
> Also could you run `kubectl get pvc` and `kubectl get pv` when you have short-circuit enabled and disabled and show me the outputs? Thanks!


My issue contains a TXT file, which is actually yaml file. GitHub can't upload yaml file

The following figure is the PV PVC of aluxio
![image](https://user-images.githubusercontent.com/4116773/110905139-fd8fb300-8344-11eb-9010-f5e79361f61a.png)

**Comment by fantastic2085** [comment]
> Hey thanks for submitting this issue! I'm going to look into this for you, but before I do are you using Helm to generate those manifest files? If so could you provide the `config.yaml` you are using when you install the alluxio Helm chart? Both for short-circuit enable and disabled if you can. If not could you provide any other k8s resource manifests you used to deploy Alluxio in k8s (eg: `alluxio-worker-pvc.yaml` maybe?)
> 
> Also could you run `kubectl get pvc` and `kubectl get pv` when you have short-circuit enabled and disabled and show me the outputs? Thanks!


My issue contains a TXT file, which is actually yaml file. GitHub can't upload yaml file

The following figure is the PV PVC of aluxio
![image](https://user-images.githubusercontent.com/4116773/110905139-fd8fb300-8344-11eb-9010-f5e79361f61a.png)

**Comment by ZhuTopher** [comment]
@fantastic2085 I checked your linked files previously, they looked good to me.

I think I found what is likely going to be the case for the behaviour that you observed, but I will go verify this on my own environment too. For Kubernetes volume mounts of type `emptyDir` with the `medium: "Memory"`, the listed available space will always be [**half the current node's available memory**](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir).
- Note we defined a `sizeLimit: 1G`; so in practice the effective space is still `1G` regardless of what `df` reports. If the memory used exceeds `sizeLimit` [the pod will evict itself](https://github.com/kubernetes/kubernetes/issues/63126?spm=a2c65.11461447.0.0.37da3505fvZ3f9#issuecomment-387817170)

So if you have multiple nodes in your Kubernetes cluster add a [nodeSelector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) to your daemonset definition to ensure your workers get scheduled on the same node. If this still occurs then there might be something else going on. I will be testing this set-up and get back to you.

**Comment by ZhuTopher** [comment]
I just finished testing with the following set-up:

- 3 Kubernetes nodes, 1 master and 2 worker nodes
  - Master node is not schedulable for pods
  - One worker node is labeled `worker: false`
  - One worker node is labled `worker: true`
  - Both worker nodes are AWS EC2 M5.2xLarge instances (8 vCPUs, 32 GiB memory)
- Alluxio master `StatefulSet` with `nodeSelector: worker: "false"`
- Alluxio worker `DaemonSet` with `nodeSelector: worker: "true"`

I deployed Alluxio on Kubernetes with short-circuit enabled (`hostPath` volume) and disabled and ran `df -h` on the `alluxio-worker` container on the single Alluxio worker pods.

## Short-circuit disabled:
```
[kubernetes@ip-172-31-76-132 singleMaster-localJournal]$ kubectl get po
NAME                   READY   STATUS    RESTARTS   AGE
alluxio-master-0       2/2     Running   0          74s
alluxio-worker-pw8qb   2/2     Running   0          34s
[kubernetes@ip-172-31-76-132 singleMaster-localJournal]$ kubectl exec -it alluxio-worker-pw8qb -c alluxio-worker /bin/bash
bash-4.4$ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 128.0G      5.4G    122.6G   4% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.4G         0     15.4G   0% /sys/fs/cgroup
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /dev/termination-log
tmpfs                    15.4G         0     15.4G   0% /dev/shm
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/resolv.conf
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/hostname
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/hosts
tmpfs                    15.4G     12.0K     15.4G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    15.4G         0     15.4G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/timer_stats
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                    15.4G         0     15.4G   0% /proc/scsi
tmpfs                    15.4G         0     15.4G   0% /sys/firmware
bash-4.4$ exit
[kubernetes@ip-172-31-76-132 singleMaster-localJournal]$ kubectl describe po alluxio-worker-pw8qb
Name:               alluxio-worker-pw8qb
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               ip-172-31-69-241.ec2.internal/172.31.69.241
...
```

## Short-circuit enabled
```
[kubernetes@ip-172-31-76-132 shortcircuit]$ kubectl get po
NAME                   READY   STATUS    RESTARTS   AGE
alluxio-master-0       2/2     Running   0          46m
alluxio-worker-l2ngp   2/2     Running   0          89s
[kubernetes@ip-172-31-76-132 shortcircuit]$ kubectl exec -it alluxio-worker-l2ngp -c alluxio-worker /bin/bash
bash-4.4$ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 128.0G      5.4G    122.6G   4% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.4G         0     15.4G   0% /sys/fs/cgroup
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /dev/termination-log
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /opt/domain
tmpfs                    15.4G         0     15.4G   0% /dev/shm
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/resolv.conf
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/hostname
/dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/hosts
tmpfs                    15.4G     12.0K     15.4G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    15.4G         0     15.4G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/timer_stats
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                    15.4G         0     15.4G   0% /proc/scsi
tmpfs                    15.4G         0     15.4G   0% /sys/firmware
bash-4.4$ exit
[kubernetes@ip-172-31-76-132 shortcircuit]$ kubectl describe po alluxio-worker-l2ngp
Name:               alluxio-worker-l2ngp
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               ip-172-31-69-241.ec2.internal/172.31.69.241
...
```

## Conclusion
In both scenarios the reported `emptyDir` volume with `medium: "Memory"` mounted at `/dev/shm` in the pod reports its capacity as ~16 GiB = 32GiB / 2. This is as expected from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir).

If you have any follow-up questions please let me know or open a new issue, but otherwise I'm going to mark this as resolved. Thank you!

**Comment by fantastic2085** [comment]
> I just finished testing with the following set-up:
> 
> * 3 Kubernetes nodes, 1 master and 2 worker nodes
>   
>   * Master node is not schedulable for pods
>   * One worker node is labeled `worker: false`
>   * One worker node is labled `worker: true`
>   * Both worker nodes are AWS EC2 M5.2xLarge instances (8 vCPUs, 32 GiB memory)
> * Alluxio master `StatefulSet` with `nodeSelector: worker: "false"`
> * Alluxio worker `DaemonSet` with `nodeSelector: worker: "true"`
> 
> I deployed Alluxio on Kubernetes with short-circuit enabled (`hostPath` volume) and disabled and ran `df -h` on the `alluxio-worker` container on the single Alluxio worker pods.
> 
> ## Short-circuit disabled:
> ```
> [kubernetes@ip-172-31-76-132 singleMaster-localJournal]$ kubectl get po
> NAME                   READY   STATUS    RESTARTS   AGE
> alluxio-master-0       2/2     Running   0          74s
> alluxio-worker-pw8qb   2/2     Running   0          34s
> [kubernetes@ip-172-31-76-132 singleMaster-localJournal]$ kubectl exec -it alluxio-worker-pw8qb -c alluxio-worker /bin/bash
> bash-4.4$ df -h
> Filesystem                Size      Used Available Use% Mounted on
> overlay                 128.0G      5.4G    122.6G   4% /
> tmpfs                    64.0M         0     64.0M   0% /dev
> tmpfs                    15.4G         0     15.4G   0% /sys/fs/cgroup
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /dev/termination-log
> tmpfs                    15.4G         0     15.4G   0% /dev/shm
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/resolv.conf
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/hostname
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/hosts
> tmpfs                    15.4G     12.0K     15.4G   0% /run/secrets/kubernetes.io/serviceaccount
> tmpfs                    15.4G         0     15.4G   0% /proc/acpi
> tmpfs                    64.0M         0     64.0M   0% /proc/kcore
> tmpfs                    64.0M         0     64.0M   0% /proc/keys
> tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
> tmpfs                    64.0M         0     64.0M   0% /proc/timer_stats
> tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
> tmpfs                    15.4G         0     15.4G   0% /proc/scsi
> tmpfs                    15.4G         0     15.4G   0% /sys/firmware
> bash-4.4$ exit
> [kubernetes@ip-172-31-76-132 singleMaster-localJournal]$ kubectl describe po alluxio-worker-pw8qb
> Name:               alluxio-worker-pw8qb
> Namespace:          default
> Priority:           0
> PriorityClassName:  <none>
> Node:               ip-172-31-69-241.ec2.internal/172.31.69.241
> ...
> ```
> 
> ## Short-circuit enabled
> ```
> [kubernetes@ip-172-31-76-132 shortcircuit]$ kubectl get po
> NAME                   READY   STATUS    RESTARTS   AGE
> alluxio-master-0       2/2     Running   0          46m
> alluxio-worker-l2ngp   2/2     Running   0          89s
> [kubernetes@ip-172-31-76-132 shortcircuit]$ kubectl exec -it alluxio-worker-l2ngp -c alluxio-worker /bin/bash
> bash-4.4$ df -h
> Filesystem                Size      Used Available Use% Mounted on
> overlay                 128.0G      5.4G    122.6G   4% /
> tmpfs                    64.0M         0     64.0M   0% /dev
> tmpfs                    15.4G         0     15.4G   0% /sys/fs/cgroup
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /dev/termination-log
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /opt/domain
> tmpfs                    15.4G         0     15.4G   0% /dev/shm
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/resolv.conf
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/hostname
> /dev/nvme0n1p1          128.0G      5.4G    122.6G   4% /etc/hosts
> tmpfs                    15.4G     12.0K     15.4G   0% /run/secrets/kubernetes.io/serviceaccount
> tmpfs                    15.4G         0     15.4G   0% /proc/acpi
> tmpfs                    64.0M         0     64.0M   0% /proc/kcore
> tmpfs                    64.0M         0     64.0M   0% /proc/keys
> tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
> tmpfs                    64.0M         0     64.0M   0% /proc/timer_stats
> tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
> tmpfs                    15.4G         0     15.4G   0% /proc/scsi
> tmpfs                    15.4G         0     15.4G   0% /sys/firmware
> bash-4.4$ exit
> [kubernetes@ip-172-31-76-132 shortcircuit]$ kubectl describe po alluxio-worker-l2ngp
> Name:               alluxio-worker-l2ngp
> Namespace:          default
> Priority:           0
> PriorityClassName:  <none>
> Node:               ip-172-31-69-241.ec2.internal/172.31.69.241
> ...
> ```
> 
> ## Conclusion
> In both scenarios the reported `emptyDir` volume with `medium: "Memory"` mounted at `/dev/shm` in the pod reports its capacity as ~16 GiB = 32GiB / 2. This is as expected from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir).
> 
> * As a reminder, since we defined a `sizeLimit: 1G` in practice the effective space is 1G regardless of what `df` reports
> 
> If you have any follow-up questions please let me know or open a new issue, but otherwise I'm going to mark this as resolved. Thank you!

**Comment by fantastic2085** [comment]
@ZhuTopher 
Thank you very much for your answer!
As shown in the figure below, we use k8s version:
![image](https://user-images.githubusercontent.com/4116773/111282668-34cdcf00-8679-11eb-906c-6868febf1218.png)

On k8s version 1.18.15, the sizelimit field doesn't seem to work

**Comment by fantastic2085** [comment]
The following figure shows the label of k8s worker node： @ZhuTopher 
![image](https://user-images.githubusercontent.com/4116773/111283220-d9e8a780-8679-11eb-8127-efda0a33c645.png)

**Comment by fantastic2085** [comment]
@ZhuTopher 
In fact, the reason why I ask this question is: because memory is a very expensive storage, it costs a lot of money for customers, so customers need to know the usage of memory and where to use it。
Alluxio provides a Web UI. On the Web UI, there is a storage usage summary. Please look at the picture. From the picture, we can see that the space capacity is 128. What I want to express is that even if alluxio worker is deployed as a container, the data should be consistent. Otherwise, the memory will be wasted. In fact, it will increase the cost of customers

![image](https://user-images.githubusercontent.com/4116773/111284653-4a43f880-867b-11eb-8865-cbcc5a3aca81.png)

![image](https://user-images.githubusercontent.com/4116773/111284706-5760e780-867b-11eb-9f3d-b426a3497de4.png)

**Comment by ZhuTopher** [comment]
Hey, thanks for bringing this up! Yes I believe you're understanding is correct; we'd need to make some changes to properly reflect the worker memory when deployed with a `hostPath` `volumeMount` since Kubernetes currently doesn't accurately report the volume memory capacity with `sizeLimit`.

Unfortunately I can't really say _when_ those changes might be since this is a very Kubernetes-specific and nuanced issue. However I'll bring this up with the dev team and let you know what they think.

**Comment by ZhuTopher** [comment]
Regarding your other two comments:

1. I'm not sure what the Kubernetes behaviour was prior to adding `sizeLimit` since there's no mention of the behaviour in the [v1.18.x k8s docs](https://v1-18.docs.kubernetes.io/docs/concepts/storage/volumes/#emptydir).

From [this Openshift thread](https://bugzilla.redhat.com/show_bug.cgi?id=1422049) it seems like the volume will have capacity equal to its reported capacity of half the memory of the node. According to this thread, if the Pod itself has a memory limit for the container defined like follows:
```
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: 1Gi
        cpu: 1
```
then this limit will apply to the memory-backed `emptyDir` volume as well. So the true capacity of the volume is **at most** the memory limit of the container.

2. I suspected you probably had multiple worker nodes sharing the same label. If those nodes aren't the same spec-wise (specifically their RAM capacity) then you would see different reported capacity for the memory-backed `emptyDir` volume due to the differing RAM capacities. In my test environment I used a single node to put the workers on to ensure the same RAM capacity. If they **are** the same spec-wise, then that'd be a bug on Kubernetes' side I think.

**Comment by fantastic2085** [comment]
@ZhuTopher 
Question 1: in **alluxio-worker-daemonset.yaml** file, both alluxio worker and alluxio job worker are emptydir with the name of men. In other words, will alluxio job worker also use this emptydir?

Question 2: the number of CPU cores of nodes in my k8s cluster is the same, but the memory is different. **The memory of two computers is 64G, and the memory of two computers is 32G**. According to what you said above, if the sizelimit field does not work, then the actual memory usage of the aluxio worker is half of the memory of the node in which it is located. **_Is my understanding correct_**

I want to express why alluxio makes memory planning clear. I think alluxio is also a customer-oriented enterprise. Since I have never used commercial alluxio, I don't know that commercial alluxio makes memory planning very clear. However, in the open source community, this memory planning is not clearly described. However, what I want to say is that this is open source for alluxio Community promotion will bring trouble, because I can't explain how to plan and use the memory for customers when using aluxio to provide services. If aluxio also attaches importance to the development of open source community, I hope to put this problem on the agenda, because in my opinion, this is a more important thing

**Comment by fantastic2085** [comment]
Question 3：
**Environmental description**:
**namespace**: gaozh
**Aluxio cluster**：
![image](https://user-images.githubusercontent.com/4116773/111422132-26d78700-8729-11eb-88fe-36ef73132a5c.png)
**k8s cluster**：
![image](https://user-images.githubusercontent.com/4116773/111423915-f6451c80-872b-11eb-9c47-b678f86b1e39.png)

**testing procedure**:
(1) The container named memlimit is deployed on the k8s-alluxio-work03 node， Here is the yaml file of memlimit:
[memlimit.yaml.txt](https://github.com/Alluxio/alluxio/files/6154152/memlimit.yaml.txt)
**Note the CPU and memory of the memlimit container**
(2) **memlimit-yqbzz-65dd7c77f8-qkhzd and alluxio-worker-v2227** are deployed in k8s-alluxio-work03
![image](https://user-images.githubusercontent.com/4116773/111424777-30fb8480-872d-11eb-8cc5-60555fae630d.png)
(3) View resources:
![image](https://user-images.githubusercontent.com/4116773/111425476-2c839b80-872e-11eb-9380-406ebee06a19.png)
**memlimit-yqbzz-65dd7c77f8-qkhzd and alluxio-worker-v2227, The total memory used is 20G**
(4) View the memory of the k8s-alluxio-work03 node
![image](https://user-images.githubusercontent.com/4116773/111425773-99973100-872e-11eb-9c49-8ce7e12f0e68.png)
(5) The size of /dev/shm of the aluxio worker container
![image](https://user-images.githubusercontent.com/4116773/111426074-08748a00-872f-11eb-82a3-f23db8d86805.png)

in summary, The memory used of the k8s-alluxio-work03 node is (23.5 + 20) = 43.5G， The remaining memory is (47 - 43.5) = 3.5.

From the perspective of k8s, the container memlimit deployed on the k8s-alluxio-work03 node should have no memory resources,The real situation can be deployed.As shown in the figure below：
![image](https://user-images.githubusercontent.com/4116773/111426669-f34c2b00-872f-11eb-95d7-104cfbf5bd97.png)

**This shows a problem, that is, the memory occupied by the volume men defined in the alluxio-worker-daemonset.yaml file is not recognized by k8s. If k8s cluster will deploy other applications, it is possible to deploy other applications to the k8s-alluxio-work03 node, so that the memory of the actual data saved by the alluxio worker will be occupied

It also shows that the capacity of the volume men is independent of the request / limit of the container

In my opinion, the capacity of the volume men should be obtained from the memory specified in the limit field of the yaml file of the container**

**Comment by ZhuTopher** [comment]
@fantastic2085 

**Question 1**: Yes both the `alluxio-worker` and `alluxio-job-worker` are sharing the `emptyDir` volume. I don't personally know if this type of usage is intended by Kubernetes for memory-backed volumes but that is how the Pod is currently defined.

**Question 2**: Yes, since in your version of Kubernetes `sizeLimit` is not supported then the memory-backed `emptyDir` volumes will have **_capacity_** equal to half the host node's RAM where the Pod gets scheduled to.

**Question 3**:
> in summary, The memory used of the k8s-alluxio-work03 node is (23.5 + 20) = 43.5G， The remaining memory is (47 - 43.5) = 3.5
> ...
> It also shows that the capacity of the volume men is independent of the request / limit of the container
- To clarify, my understanding from the posts I linked previously discussing the memory-backed `emptyDir` is that their capacity **_is_** independent of the Pod's memory limit (i.e: that's intentional). However, the memory actively used by that volume will contribute to the memory used by the Pod when Kubernetes looks at memory limits for scheduling purposes
  - I.e: `/dev/shm` has a **listed capacity** `23.5G` = 47G / 2 but its **effective capacity** due to the memory limit of the pod is `12Gi`
  - So for your calculation, the total memory requested by the node should be `12Gi + 8Gi` from the `alluxio-worker-v2227` and `memlimit` Pods; the memory used by `/dev/shm` is part of that `12Gi` limit.
- Hence if in the `alluxio-worker-daemonset.yaml` file you removed the resource limits on memory, the capacity of the volume would indeed be half the node's RAM

> In my opinion, the capacity of the volume men should be obtained from the memory specified in the limit field of the yaml file of the container
- Changing the capacity of the volume to report the Pod's memory limit specification would be non-trivial and require changes on Kubernetes' end
- If you want the Alluxio dashboard to reflect this, then that is what I was referring to when I said:
  > Unfortunately I can't really say _when_ those changes might be since this is a very Kubernetes-specific and nuanced issue. However I'll bring this up with the dev team and let you know what they think.

**Comment by ZhuTopher** [comment]
Also regarding this comment:
> I want to express why alluxio makes memory planning clear. I think alluxio is also a customer-oriented enterprise. Since I have never used commercial alluxio, I don't know that commercial alluxio makes memory planning very clear. However, in the open source community, this memory planning is not clearly described. However, what I want to say is that this is open source for alluxio Community promotion will bring trouble, because I can't explain how to plan and use the memory for customers when using aluxio to provide services. If aluxio also attaches importance to the development of open source community, I hope to put this problem on the agenda, because in my opinion, this is a more important thing

I agree this is a very relevant issue and would love to address it. However it is not something which we directly can cleanly solve as this is the result of the nuances of how Kubernetes' memory-backed `emptyDir` volumes behave. Furthermore, Alluxio is designed to be flexible in various deployment configurations which include non-Kubernetes deployments. That's why I'm letting you know that seeing a hotfix for this in our dashboard for example might end up low priority.

At the very least, I will likely be adding some of these findings from this issue to our documentation for Alluxio-on-Kubernetes in the meantime.

**Comment by fantastic2085** [comment]
> At the very least, I will likely be adding some of these findings from this issue to our documentation for Alluxio-on-Kubernetes in the meantime.

@ZhuTopher 
Alluxio needs to be close to cloud native. In my opinion, it is necessary to integrate alluxio into k8s. I hope alluxio can pay attention to it!

**Comment by fantastic2085** [comment]
> @fantastic2085
> 
> **Question 1**: Yes both the `alluxio-worker` and `alluxio-job-worker` are sharing the `emptyDir` volume. I don't personally know if this type of usage is intended by Kubernetes for memory-backed volumes but that is how the Pod is currently defined.
> 
> **Question 2**: Yes, since in your version of Kubernetes `sizeLimit` is not supported then the memory-backed `emptyDir` volumes will have **_capacity_** equal to half the host node's RAM where the Pod gets scheduled to.
> 
> **Question 3**:
> 
> > in summary, The memory used of the k8s-alluxio-work03 node is (23.5 + 20) = 43.5G， The remaining memory is (47 - 43.5) = 3.5
> > ...
> > It also shows that the capacity of the volume men is independent of the request / limit of the container
> 
> * To clarify, my understanding from the posts I linked previously discussing the memory-backed `emptyDir` is that their capacity **_is_** independent of the Pod's memory limit (i.e: that's intentional). However, the memory actively used by that volume will contribute to the memory used by the Pod when Kubernetes looks at memory limits for scheduling purposes
>   
>   * I.e: `/dev/shm` has a **listed capacity** `23.5G` = 47G / 2 but its **effective capacity** due to the memory limit of the pod is `12Gi`
>   * So for your calculation, the total memory requested by the node should be `12Gi + 8Gi` from the `alluxio-worker-v2227` and `memlimit` Pods; the memory used by `/dev/shm` is part of that `12Gi` limit.
> * Hence if in the `alluxio-worker-daemonset.yaml` file you removed the resource limits on memory, the capacity of the volume would indeed be half the node's RAM
> 
> > In my opinion, the capacity of the volume men should be obtained from the memory specified in the limit field of the yaml file of the container
> 
> * Changing the capacity of the volume to report the Pod's memory limit specification would be non-trivial and require changes on Kubernetes' end
> * If you want the Alluxio dashboard to reflect this, then that is what I was referring to when I said:
>   > Unfortunately I can't really say _when_ those changes might be since this is a very Kubernetes-specific and nuanced issue. However I'll bring this up with the dev team and let you know what they think.

@ZhuTopher 
From the above answer, on the premise that sizelimit takes effect, there is a relationship between request / limit and volume men of aluxio worker. The relationship is that the capacity of volume men of aluxio worker is less than or equal to request / limit. Is this correct?

**Comment by fantastic2085** [comment]
@ZhuTopher 
There is another issue(https://github.com/Alluxio/alluxio/issues/13023). I hope we can come to a conclusion, which is also very important for us!

**Comment by ZhuTopher** [comment]
@fantastic2085 
> From the above answer, on the premise that sizelimit takes effect, there is a relationship between request / limit and volume men of aluxio worker. The relationship is that the capacity of volume men of aluxio worker is less than or equal to request / limit. Is this correct?

Yes, the effective maximum capacity of the `mem` volume can be thought of as `Math.floor(Node's available RAM/2, sizeLimit, Pod requested memory limit)` where `sizeLimit` is infinite if not defined.

**Comment by jiacheliu3** [comment]
@ZhuTopher Can this issue be closed?

**Comment by ZhuTopher** [comment]
I will close this issue after the docfix PR #14004 gets merged in; I forgot to make that doc update back then!
