### ISSUE TITLE
REST Proxy API documentation for stable, 2.5, and 2.4 is empty

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13035]
**Page**
- https://docs.alluxio.io/os/restdoc/2.4/proxy/index.html
- https://docs.alluxio.io/os/restdoc/2.5/proxy/index.html
- https://docs.alluxio.io/os/restdoc/stable/proxy/index.html

**Summary**
The REST Proxy API for version [2.4](https://docs.alluxio.io/os/restdoc/2.4/proxy/index.html) and [2.5](https://docs.alluxio.io/os/restdoc/2.5/proxy/index.html)  and [stable](https://docs.alluxio.io/os/restdoc/stable/proxy/index.html) are empty.

The documentation for [2.3](https://docs.alluxio.io/os/restdoc/2.3/proxy/index.html) however, exists

**Comment by jja725** [comment]
We would reconsider rest support. Will close it for now, feel free to reopen it and contact us if this is a strong request.
