### ISSUE TITLE
alluxio/alluxio-fuse:2.5.0 Docker image fails to run

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13052]
**Alluxio Version:**
Alluxio version: 2.5.0-71bca9f4f3d13fd687a13c4d15656462021403f6 from `alluxio/alluxio-fuse:2.5.0` Docker image.

**Describe the bug**
When running the container I get a the following error:
```
umount: /mnt/alluxio-fuse: not mounted
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "/mnt/alluxio-fuse" with options="big_writes"
2021-03-12 09:03:12,883 INFO  AlluxioFuse - Alluxio version: 2.5.0-71bca9f4f3d13fd687a13c4d15656462021403f6
2021-03-12 09:03:13,115 INFO  NettyUtils - EPOLL_MODE is available
2021-03-12 09:03:13,350 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=c435141d28d5, rack=null)
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnifuse in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at alluxio.jnifuse.AbstractFuseFileSystem.<clinit>(AbstractFuseFileSystem.java:38)
	at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:119)
```

It seems like the JNI cannot be linked.

**To Reproduce**
Run [this docker-compose file](https://gist.github.com/peterroelants/f3ceb4d972c2f819c37d742b3a8602f3#file-alluxio-fuse-compose-yml) that replicates the [Deploy Alluxio on Docker](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html) tutorial.

**Expected behavior**
`alluxio/alluxio-fuse:2.5.0` Docker image works

**Urgency**
High, the current Docker image provided seem to be broken.

**Comment by peterroelants** [comment]
I think it's because the `Dockerfile.fuse` actually deletes the FUSE JNI libs: https://github.com/Alluxio/alluxio/blob/master/integration/docker/Dockerfile.fuse#L32

**Comment by peterroelants** [comment]
Filed a PR that keeps the libraries in the ima

> I think it's because the `Dockerfile.fuse` accidentally deletes the FUSE JNI libs: https://github.com/Alluxio/alluxio/blob/master/integration/docker/Dockerfile.fuse#L32

I filed a PR to keep the FUSE JNI libraries in the image: https://github.com/Alluxio/alluxio/pull/13054

**Comment by apc999** [comment]
Thanks @peterroelants . 

I merged your patch and also fixed the [docker image](https://hub.docker.com/layers/alluxio/alluxio-fuse/2.5.0/images/sha256-e4374a50430757707fb7dcf68891cc594e4d7dab061935480b596d1b952a734f?context=explore) by adding the missing file.

Let me know if you still see any issues using alluxio/alluxio-fuse:2.5.0

**Comment by peterroelants** [comment]
Thanks, I can confirm that the files are now in the Docker image and that the FUSE container seems to work when running with `alluxio.fuse.jnifuse.enabled=true`.
