### ISSUE TITLE
Missing jar: alluxio-integration-fuse-2.5.0-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13055]
[`branch-2.5/integration/fuse/bin/alluxio-fuse#L20`](https://github.com/Alluxio/alluxio/blob/d2f663ea19094673bb01dc8549f1dce54ae269b1/integration/fuse/bin/alluxio-fuse#L20) references a `alluxio-integration-fuse-${VERSION}-jar-with-dependencies.jar`, which is neither to be find in the `alluxio/alluxio-fuse:2.5.0` docker image, nor in the [2.5.0 tar](https://downloads.alluxio.io/downloads/files/2.5.0/).

Could it be that this is missing from the package? Or is this something that I have to build myself?

**Comment by apc999** [comment]
hi @peterroelants  it is renamed to `/opt/alluxio/integration/fuse/alluxio-fuse-2.5.0.jar` in docker image and tarball.

**Comment by peterroelants** [comment]
I see, I'll be using that.

Just so you know, that code is from `branch-2.5`, which I assumed was the 2.5.0 branch. I guess this is not actually the release branch, and this a more up-to-date branch that will become `2.5.1` and so on?

**Comment by apc999** [comment]
branch-2.5 is the branch hosting 2.5.0, and bug fixes  cherry-picked from master branch.
meanwhile, we will a new edge release from bleeding edge of master branch. it will be named like 2.5.0-1, 2.5.0-2 and so on until we cut branch-2.6.

So, if you want to get a more up-to-date branch, today it is branch-2.5. but shortly we will have other branches like release-2.5.0-1

**Comment by peterroelants** [comment]
Got it. Thanks for clarifying.
