### ISSUE TITLE
Add migrating progress on distributedCp job

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#13065]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I run `distributedCp` command for migrating data from local to remote CEPH.

**Describe the solution you'd like**
I want to see the migrating progress

**Describe alternatives you've considered**
`alluxio job statu -v` could show the migration progress.

**Urgency**
Important, it's hardly on managing data migration without this feature.

**Comment by jiacheliu3** [comment]
@bradyoo does this make sense to you?

**Comment by bradyoo** [comment]
distributedCp now submits jobs per file. One of the things it does though is that it traverses all of the files through iterateStatus and submits job one at a time so at the time of doing a job for a file, it doesn't actually know how many files there are in total. So if we want to know that, we would have to do extra iterateStatus which would cause slowdowns if we are doing it for large number of small files.

**Comment by JySongWithZhangCe** [comment]
@jiacheliu3 Is there any other suggestion？

**Comment by yuzhu** [comment]
does simply showing the number of files already copied help? because that would at least indicate that we are making progress and how fast we are making progress. The user might have an idea about how many files need to be copied.

**Comment by JySongWithZhangCe** [comment]
> does simply showing the number of files already copied help? because that would at least indicate that we are making progress and how fast we are making progress. The user might have an idea about how many files need to be copied.

I agree, and I'd like to both show the number and size of files.

**Comment by JySongWithZhangCe** [comment]
> does simply showing the number of files already copied help? because that would at least indicate that we are making progress and how fast we are making progress. The user might have an idea about how many files need to be copied.

I agree, and I'd like to both show the number and size of files.

**Comment by jja725** [comment]
would consider it when moving towards new infra
