### ISSUE TITLE
alluxio-fuse support local disk cache

### ISSUE THREAD

**Issue by shuaiyy** [Alluxio/alluxio#13073]
**Is your feature request related to a problem? Please describe.**

we use alluxio + alluxio-fuse to accelerate s3 read, in AI training jobs;  for one dataset size is 10 ~ 300GB ; 
when alluxio cluster space used 99%, alluxio-fuse read become 2~10X slower  than s3 read directly ;

**Describe the solution you'd like**
I hope alluxio-fuse can cahce the file into local disk, like s3fs;  just for read only; 

**Describe alternatives you've considered**

alluxio-fuse with local disk cache may cause file inconsistent；so just consider that:
1. the files just read only, and underfs file will not changed
2. the local disk have enough space

**Urgency**
very urgent；
we have a 1TB mem alluxio cluster in prod environment， but get little profit， which gives me much pressure;
I'll  try s3fs as alternative plan before I find a solution for alluixo-fuse， so sad！

**Comment by jja725** [comment]
there's fuse sdk coming up soon
