### ISSUE TITLE
Healthcheck endpoints for Alluxio services

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13075]
**Is your feature request related to a problem? Please describe.**

Healthcheck API endpoints could be of benefit because of two mean reasons:
- Observability on the status of the service
- Usage of dependency conditions when starting service. (e.g. in docker-compose [`depends_on`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on) could be used to wait on another service that is a dependency.

**Describe the solution you'd like**

A healthcheck API endpoint that is compatible with [Docker healthchecks](https://docs.docker.com/engine/reference/builder/#healthcheck). For example this could be a `/api/v1/<service>/health` REST endpoint that returns status 200 if the service is health and fails otherwise. Alternatively this could be a local healthcheck implemented as a script or binary.

These healthchecks could be customized and provided for each of the components (master, worker, clients).

**Describe alternatives you've considered**

Make use of the existing webUI REST endpoints. (See comment below for example)

**Urgency**
Low, this would help run stable deployments of Alluxio with better monitorring. However it is not essential to run the service.

**Additional context**
For an example how this could look, see the [Hasura GraphQL `/healthz` endpoint](https://hasura.io/docs/latest/graphql/core/api-reference/health.html).

**Comment by peterroelants** [comment]
An example of using the existing WebUI REST enpoints would for example look like:

`healthcheck.sh` file:
```
#!/bin/bash

# Up more than 500ms? (timing chosen arbitrarily)
required_uptime_ms=500
uptime_ms=$(wget -q -t1 -O - http://alluxio-master:19999/api/v1/master/info | jq '.uptimeMs')
if [ -z "$uptime_ms" ]; then
  echo "Uptime undefined"
  exit 1
elif (( $uptime_ms < $required_uptime_ms )); then
  echo "Uptime < $required_uptime_ms ms>"
  exit 1
else
  exit 0
fi
```

Which in docker-compose is referenced as:
```
    healthcheck:
      test: /opt/startup/healthcheck.sh
      interval: 3s
      timeout: 2s
      retries: 30
      start_period: 5s
```

**Comment by jiacheliu3** [comment]
@peterroelants Currently the health is probing the open ports for each service. You can find how they are used in https://github.com/Alluxio/alluxio/blob/feb4aa08ea675ef1c49005c2f6c401e07bab80cf/integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl#L303 and https://github.com/Alluxio/alluxio/blob/feb4aa08ea675ef1c49005c2f6c401e07bab80cf/shell/src/main/java/alluxio/master/MasterHealthCheckClient.java#L255
Does that serve your need? 

The current implementation sure has pros and cons compared to your thought about having a HTTP endpoint (as you already pointed out in the downside). We can further discuss.

**Comment by jiacheliu3** [comment]
One other pitfall for having an HTTP endpoint is, when masters are in HA, only the primary has a web server. So all the secondaries will reject your HTTP request. This makes the definition of "healthy" a bit confusing.

**Comment by peterroelants** [comment]
Thanks for the references to the helm chart. I wasn't aware of the healthchecks there. I see that those are using [`alluxio-monitor.sh`](https://github.com/Alluxio/alluxio/blob/master/bin/alluxio-monitor.sh).

I tried using `alluxio-monitor.sh master` and this works if the service is up. However if the service is actually down the script does not exit and continues writing DNS error messages to the output. Is this intended behaviour? Is it possible to just get  a status code from these scripts?

**Comment by peterroelants** [comment]
I also noticed there is no monitor for the FUSE endpoint.
I'm currently using the following healthcheck:
```
#!/bin/bash

# File system mounted (local check)
if ! mount | grep ${MOUNT_POINT} &> /dev/null; then
  echo "Local mount not found!"
  exit 1
fi
# File system mounted (Alluxio check)
if ! alluxio-fuse stat | grep ${MOUNT_POINT} &> /dev/null; then
  echo "Alluxio fuse mount not found!"
  exit 1
fi
# All ok
exit 0
```

**Comment by jiacheliu3** [comment]
> Thanks for the references to the helm chart. I wasn't aware of the healthchecks [there](https://github.com/Alluxio/alluxio/pull/11080/). I see that those are using [`alluxio-monitor.sh`](https://github.com/Alluxio/alluxio/blob/master/bin/alluxio-monitor.sh).
> 
> I tried using `alluxio-monitor.sh master` and this works if the service is up. However if the service is actually down the script does not exit and continues writing DNS error messages to the output. Is this intended behaviour? Is it possible to just get a status code from these scripts? I'm currently using the health-check's timeout, but I'm assuming that is not best practise.

What the `alluxio-monitor.sh <component>` does is, it finds the ports (RPC & HTTP) that the component offers, and tries to establish a TCP connection to it. So if you don't want the output that comes from `alluxio-monitor.sh`, you can choose to just use a tcp socket like the K8s probes are doing https://github.com/Alluxio/alluxio/blob/feb4aa08ea675ef1c49005c2f6c401e07bab80cf/integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl#L303 I don't think you get a well-defined code like HTTP status, but at least you get a 0 vs non-zero from commands like `curl <host>:<port>`.

**Comment by jiacheliu3** [comment]
> I also noticed there is no monitor for the FUSE endpoint.
> I'm currently using the following healthcheck:
> 
> ```
> #!/bin/bash
> 
> # File system mounted (local check)
> if ! mount | grep ${MOUNT_POINT} &> /dev/null; then
>   echo "Local mount not found!"
>   exit 1
> fi
> # File system mounted (Alluxio check)
> if ! alluxio-fuse stat | grep ${MOUNT_POINT} &> /dev/null; then
>   echo "Alluxio fuse mount not found!"
>   exit 1
> fi
> # All ok
> exit 0
> ```

That's true.  @LuQQiu Do you think it makes sense to have a health check for FUSE?

**Comment by peterroelants** [comment]
I tried your suggestion using curl to check the RPC port with curl (e.g. `curl --output - alluxio-worker:29999`), this works, however the service logs now show the following exceptions:
```
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET /
```

**Comment by peterroelants** [comment]
If I remember correctly the RPC endpoints use gRPC?
In this case it might be interesting to implement the [GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) which ensures best practise and allows the health to be queried by [`grpc_health_probe`](https://github.com/grpc-ecosystem/grpc-health-probe).

**Comment by LuQQiu** [comment]
Yeah, Fuse health check is helpful, maybe we can add the health check after mounting standalone fuse or fuse in worker. But note that because we now have the embedded Fuse in worker feature #12830, the standalone fuse process may be deprecated in the future. 
I am not that familiar with the monitoring logics but a fuse health check is good to have.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
