### ISSUE TITLE
Support JNI Fuse touch command 

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#13090]
**Alluxio Version:**
Alluxio master - 2.6.0-SNAPSHOT

**Describe the bug**
Running `touch` command with JNI-Fuse mount point fails.
```
$touch /tmp/alluxio/fuseMount/a.file
touch: setting times of ‘/tmp/alluxio/fuseMount/a.file’: Function not implemented
```
Looks like JNI-Fuse need to support `setattr` operation to be able to get `touch` to work

**To Reproduce**
- Create an Alluxio cluster
- Create a fuse mount point `fuseMount` and grant permissions
- Mount JNI-Fuse with `integration/fuse/bin/alluxio-fuse mount fuseMount /`
- Run `touch` command against the mount point

**Expected behavior**
Touch should succeed without exceptions

**Urgency**
Not urgent

**Additional context**
JNR-FUSE touch succeed without error

**Comment by maobaolong** [comment]
I'll take a look at this issue this week.

**Comment by maobaolong** [comment]
@LuQQiu I use `HCFSFuse` test this issue, and it cannot reproduce.

For my acknowledge, I think it can be more easy to reproduce this issue by using `HCFSFuse` instead of start an alluxio cluster.

**Comment by LuQQiu** [comment]
In the current JNIFuseIntegrationTest, we disable the touch test because it keeps failing. I have no background knowledge of HCFSFuse, not quite sure what it actually does.
```
public class JNIFuseIntegrationTest extends AbstractFuseIntegrationTest {
  private AlluxioJniFuseFileSystem mFuseFileSystem;
  @Ignore
  @Override
  public void touchAndLs() throws Exception {
    // TODO(lu) Enable the test after https://github.com/Alluxio/alluxio/issues/13090 solved
  }
}
```

**Comment by maobaolong** [comment]
```
2021-04-04 19:09:41,477 INFO  AlluxioFuse - Alluxio version: 2.6.0-SNAPSHOT-57b1c8c2bc6e5a50266759bd2d667911a4e6e4cd
2021-04-04 19:09:41,899 INFO  NettyUtils - EPOLL is not available, will use NIO
2021-04-04 19:09:42,519 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=192.168.1.102, rack=null)
2021-04-04 19:09:42,818 INFO  NativeLibraryLoader - Loaded lib by jar from path /var/folders/hj/jty18sr93t3_cbkb01szbv3w0000gn/T/libjnifuse5423017182942702284.jnilib.
2021-04-04 19:09:42,846 INFO  AlluxioFuse - Mounting AlluxioJniFuseFileSystem: mount point="fuseMount", OPTIONS="[-obig_writes, -omax_write=131072]"
2021-04-04 19:09:42,846 INFO  AbstractFuseFileSystem - Mounting /Users/mbl/projects/github/alluxio-2/fuseMount: blocking=true, debug=false, fuseOpts="[-obig_writes, -omax_write=131072]"
2021-04-04 19:11:50,815 WARN  BaseFileSystem - File /a.file is not yet completed. getStatus will see incomplete metadata.
2021-04-04 19:11:50,820 WARN  BaseFileSystem - File /a.file is not yet completed. getStatus will see incomplete metadata.
2021-04-04 19:20:50,465 INFO  AbstractFuseFileSystem - Umounting /Users/mbl/projects/github/alluxio-2/fuseMount
```

This is a fuse.log about what I tried to reproduce this issue follow the reproduce step strictly. I start a Alluxio master and fuse

**Comment by maobaolong** [comment]
```
unique: 70, opcode: SETATTR (4), nodeid: 4, insize: 128, pid: 79220
   unique: 70, error: -38 (Function not implemented), outsize: 16
```

I reproduced and got the above output, it shows that only linux didn't implement the `SETATTR` function, will have a further look.

**Comment by maobaolong** [comment]
I try to implement utimens support, but seems nothing changed.

**Comment by LuQQiu** [comment]
According to https://github.com/mafintosh/fuse-bindings/issues/30
It looks like three functions need to be implemented
```
truncate
utimens
chown
```
@maobaolong if you added utimens, we already have chown, then the only missing is truncate which we don't support yet. 
A possible way is to try to implement truncate with alluxio read to a tmp file, delete the file, and write a new Alluxio file up to size.
After that, we may be able to conclude that touch requires `truncate` or not. we can have a discussion about whether we want to support this low efficiency method.

**Comment by maobaolong** [comment]
@LuQQiu According the https://github.com/Alluxio/alluxio/blob/master/integration/jnifuse/native/src/main/native/libjnifuse/operation.cc#L440

I think we have support truncate now, I guess there are some different for macos and linux, will have a further look

**Comment by LuQQiu** [comment]
Truncate is implemented in JNI-Fuse but not in AlluxioJNIFuseFileSystem.
```
  @Override
  public int truncate(String path, long size) {
    LOG.error("Truncate is not supported {}", path);
    return -ErrorCodes.EOPNOTSUPP();
  }
```
In macOS, if you do vi/vim, the operating system will directly do create, delete, and rename operation combinations so that truncate can succeed.
In Linux, i remember vi/vim with modification is not allowed because we don't support truncate.

**Comment by apc999** [comment]
@maobaolong @LuQQiu . It is fine if we do not support `truncate` in general.
But if we shall check file size and and `size==0` (the case `touch` triggers), we shall be able to remove the original file if existing and create a new and empty one.

**Comment by maobaolong** [comment]
@apc999 @LuQQiu For this issue, it's not caused by `truncate`,  but caused by `utimens`, so I implements it to resolve this issue.
