### ISSUE TITLE
Alluxio community helm chart does not get installed in minikube

### ISSUE THREAD

**Issue by mostrovoi** [Alluxio/alluxio#13110]
**Alluxio Version:**

alluxio helm : alluxio-charts/alluxio

**Describe the bug**

I try to install alluxio helm chart with the following command:

helm install alluxio alluxio-charts/alluxio
The chart starts to get installed but  when I type kubectl get po I see the following:

  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  7m27s                   default-scheduler  Successfully assigned default/alluxio-master-0 to minikube
  Warning  BackOff    7m17s (x3 over 7m25s)   kubelet            Back-off restarting failed container
  Normal   Pulled     7m9s (x3 over 7m27s)    kubelet            Container image "alluxio/alluxio:2.5.0" already present on machine
  Warning  Failed     7m9s (x3 over 7m27s)    kubelet            Error: failed to start container "alluxio-master": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"400000\\\\\\\" to \\\\\\\"/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod377c59fe-9c4c-44fe-8474-90c2dd70bcd0/alluxio-master/cpu.cfs_quota_us\\\\\\\": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod377c59fe-9c4c-44fe-8474-90c2dd70bcd0/alluxio-master/cpu.cfs_quota_us: invalid argument\\\"\"": unknown
  Normal   Pulled     7m9s (x3 over 7m27s)    kubelet            Container image "alluxio/alluxio:2.5.0" already present on machine
  Normal   Created    7m9s (x3 over 7m27s)    kubelet            Created container alluxio-job-master
  Warning  Failed     7m9s (x3 over 7m27s)    kubelet            Error: failed to start container "alluxio-job-master": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"400000\\\\\\\" to \\\\\\\"/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod377c59fe-9c4c-44fe-8474-90c2dd70bcd0/alluxio-job-master/cpu.cfs_quota_us\\\\\\\": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod377c59fe-9c4c-44fe-8474-90c2dd70bcd0/alluxio-job-master/cpu.cfs_quota_us: invalid argument\\\"\"": unknown
  Normal   Created    7m9s (x3 over 7m27s)    kubelet            Created container alluxio-master
  Warning  BackOff    2m23s (x29 over 7m25s)  kubelet            Back-off restarting failed container

**To Reproduce**
Whenever you try to install the chart in minikube. Using minikube v1.18.1

**Expected behavior**
The helm chart should have been installed without any problem

**Urgency**
Mid

**Comment by jja725** [comment]
@ssz1997  is this still valid? otherwise help me close this please
