### ISSUE TITLE
Unexpected mask value of new file

### ISSUE THREAD

**Issue by adios666** [Alluxio/alluxio#13123]
**Alluxio Version:**
2.4.1-1

**Describe the bug**
When I create a new file (called A) in a directory (called B), mask of A should be the default mask of B. After checked code I found that mask of new file is calculated by default mask of B AND group mode of B. I think it should inherit straightly from B or 
 be computed from default mask of B AND user mode of B.

**To Reproduce**
1. alluxio fs mkdir test
2. alluxio fs setfacl -R -d -m 'group:test_group:r-x' /test
3. alluxio fs setfacl -d -m 'group:test_group:r-x' /test
4. alluxio fs setfacl -d -m 'mask::rwx' /test
5. alluxio fs mkdir /test/new_dir or alluxio fs touch /test/new_file
6. alluxio fs getfacl /test/*
Now the mask of new file or dir is 'r-x'. Can't be written by user

**Expected behavior**
If I set default mask of B,  mask of file or directory created in B should also the default mask of B. Or every time I create a file or directory, I need to setfacl again.

**Urgency**
Not very urgent, I modified code in local already and it works fine in our environment.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
