### ISSUE TITLE
Alluxio won't jump over file when setting default acl to a directory

### ISSUE THREAD

**Issue by adios666** [Alluxio/alluxio#13124]
**Alluxio Version:**
2.4.1-1

**Describe the bug**
If I have a file(called A) in a directory(called B) and I run command like "alluxio fs setfacl -R -d -m 'user:xxx:rwx' /B". It will return  "Can not set default ACL for a file". This is reasonable, but I think Alluxio should have changed default ACL of other directories in B while jump over A and return this warning.

**To Reproduce**
1. alluxio fs mkdir /test
2. alluxio fs mkdir /test/sub_dir
3. alluxio fs touch /test/file
4. alluxio fs setfacl -R -d -m 'user:xxx:rwx' /test
Now it will return "Can not set default ACL for a file". And we can check ACL of other directory in /test:
5. alluxio fs getfacl /test/sub_dir
The result shows ACL is not changed by setfacl.

**Expected behavior**
Like linux cmd setfacl, Alluxio should jump over file automaticly and set right ACL for other sub-directory when setting ACL for an upper directory.

**Urgency**
Common, I modified code already in our environment and it works fine.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
