### ISSUE TITLE
Support get and set user group information from hadoop UGI 

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13135]
**Is your feature request related to a problem? Please describe.**

Our user require to set user & group information while create file through hadoop ugi, other than getting group name through shell.

**Describe the solution you'd like**

Dependent hadoop and using UGI as current creator.

**Describe alternatives you've considered**

Modify the AlluxioJniFuseFilesystem.

**Urgency**

LOW

**Additional context**
NO

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
