### ISSUE TITLE
Add documentation on launch proxy in a docker or helmchart

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#13137]
**Page**

https://docs.alluxio.io/os/user/stable/en/api/S3-API.html

**Summary**
This page only talks about how to interact using S3 API,
Right now the documentation assumes the ProxyServer is running and configured already
but i could not find pages talking about how to launch and configure ProxyServer in order to enable S3 API.

E.g., how to achieve this in docker or helmchart

This is reported from user slack channel:
https://alluxio-community.slack.com/archives/CEXGGUBDK/p1617116386075100

**Comment by ZhuTopher** [comment]
Community PR adding a proxy service template to the Helm chart: #14759

**Comment by ssz1997** [comment]
This is solved by https://github.com/Alluxio/alluxio/pull/16366
