### ISSUE TITLE
Alluxio cannot loadMetadata if there are two subdirectory in /underFSStorage

### ISSUE THREAD

**Issue by ldd91** [Alluxio/alluxio#13147]
**Alluxio Version:**
What version of Alluxio are you using?
2.4.1-2-bfff8c6881e5cb045fd1d84c59acba26078bb4d9
**Describe the bug**
There are two subdirectory (/underFSStorage/cifar10 and /underFSStorage/imagenet) in /underFSStorage, I exec alluxio fs loadMetadata -R /  and I exec alluxio fs loadMetadata -R /imagenet ,however the metadata was not loaded,But when I exec I exec alluxio fs loadMetadata -R /imagenet/train,the metadata was successfully loaded. I wonder if the problem is caused by soft links, there is a soft link in /underFSStorage/imagenet

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by ldd91** [comment]
![Uploading 软连接.png…]()

**Comment by ldd91** [comment]
![软连接](https://user-images.githubusercontent.com/29392150/113148825-e61d5900-9264-11eb-9bab-493b7c777242.png)

**Comment by ldd91** [comment]
![加载](https://user-images.githubusercontent.com/29392150/113149769-f2ee7c80-9265-11eb-858d-5778f9387583.png)

**Comment by ldd91** [comment]
This may cause by our lustre file system,It is ok to use /tmp in localhost

**Comment by ldd91** [comment]
This issue was caused by soft link

**Comment by LuQQiu** [comment]
@ldd91 Thanks for reporting this issue. Any error/warn/exceptions in the logs/worker.log when you do the loadMetadata operation?
Do you want Alluxio loadMetadata to support soft links?

**Comment by ldd91** [comment]
@LuQQiu Thanks for reply,Yes in our AI  training scenario,we want Alluxio loadMetadata to support soft links

**Comment by LuQQiu** [comment]
@yuzhu Any thoughts on why load metadata fail with soft links and whether it's expected?

**Comment by yuzhu** [comment]
i will take a look. @ldd91 just to be sure, are you using local file system as your ufs?

**Comment by ldd91** [comment]
@yuzhu Yes,we use local file system

**Comment by yuzhu** [comment]
@ldd91 I checked locally and created a test for symlinks. Seems to be working fine with sym links. Do you have any alluxio logs  that could tell us more info about why it failed. Btw I added a test here. #13318

**Comment by ldd91** [comment]
Thank you for have a test,I will check it again and collecte the alluxio log.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
