### ISSUE TITLE
The execution of command "alluxio fs count / " is very slow

### ISSUE THREAD

**Issue by yangyuliufeng** [Alluxio/alluxio#13158]
**Is your feature request related to a problem? Please describe.**
The execution of command "alluxio fs count / " is very slow.
The current logic will traverse all files in the root directory to get ufstotal
Even if this command has been executed once, but the result is not cached, it will still traverse all files if executed again
**Describe the solution you'd like**
Speed ​​up the execution of this command

**Describe alternatives you've considered**
Perhaps you can cache the result after the first execution, if the user have not make any change.

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by LuQQiu** [comment]
Yeah the count is slow, especially for a large folder.
If the system is read-only, and the data is never or seldom change both in Alluxio and UFS, metadata cache could be enabled.
```
alluxio.user.metadata.cache.enabled=true
alluxio.user.metadata.cache.max.size=<Maximum number of paths with cached metadata>
alluxio.user.metadata.cache.expiration.time=<time>
```

**Comment by yangyuliufeng** [comment]
@LuQQiu 
my config is: 
```
alluxio.user.metadata.cache.enabled=true
alluxio.user.metadata.cache.max.size=6000000
alluxio.user.metadata.cache.expiration.time=2day
```
however, the command "alluxio fs count /' is still very slow.
Perhaps because it will traverse all files in the root directory to get ufstotal everytime.

**Comment by yangyuliufeng** [comment]
how about storage the result in "alluxio fsadmin report metrics"

**Comment by apc999** [comment]
@yangyuliufeng @cheyang  this is actually expected given you are running an Alluxio client. An Alluxio shell command is a newly launched alluxio client every time. The file system metadata will be cached there after shell completion, but the JVM will exit soon. And in a next run of Alluxio shell command, the metadata will be empty again and needs a full traverse on master.

In short, for `alluxio fs count /` , nothing will be cached on client-side and it will not benefit the next run. To fix this, ideally we shall add a cache on master side.

**Comment by apc999** [comment]
Closing this issue. I will create a tasks to add server-side cache rather than fixing it on client side
