### ISSUE TITLE
High CPU usage when read data from Azure and seems has memory leak issue

### ISSUE THREAD

**Issue by Binyang2014** [Alluxio/alluxio#13166]
When reading data from AzureBlob, we get high CPU usage in worker. Attached the profile results from async-profiler. Seems it caused by decode https response.
[https-azure.zip](https://github.com/Alluxio/alluxio/files/6249018/https-azure.zip)

And we found worker doesn't free the memory of AzureStorageResponse. So when memory usage reach Xmx limit, the CPU usage will become much higher (about 900% in our env).

Currently, we use AzureStorage SDK v8, and it integrated with hdfs client. But v8 seems has many performance issues, maybe we can change to v12. Since v12 is not compatible with HDSF, need type of UFS need to be added.

Refer: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java?tabs=powershell

**Comment by Binyang2014** [comment]
@apc999 Please help take a look, maybe we should do some performance test for AzureStorage SDK

**Comment by Binyang2014** [comment]
The memory dump link: https://alluxiotestms.blob.core.windows.net/dump/heap.zip?sp=r&st=2021-04-06T02:54:13Z&se=2021-04-30T10:54:13Z&spr=https&sv=2020-02-10&sr=b&sig=%2B1SZXtEAjrvEUaRTHUdYQR5Bfhp%2B%2FOs4tbE1EK8UN1I%3D

**Comment by jja725** [comment]
seems like resolved.Will close it for now, feel free to reopen it and contact us if this is still valid.
