### ISSUE TITLE
Dynamically changing the aluxio storage configuration without downtime

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#13174]
When the storage of aluxio worker is expanded, we need to dynamically change the storage size of each storage layer without downtime.
And it's an ongoing need, not a one-off one

**Describe the solution you'd like**
If we can use the alluxio cli ,it will be okay
such as set alluxio.worker.tieredstore.level0.dirs.quota=2Ti

**Urgency**
the feature is import for us,because we use alluxio in k8s cluster,adjusting configuration in k8s cluster requires continuous restarting worker. It may not be received.

**Comment by apc999** [comment]
can be implemented by https://github.com/Alluxio/alluxio/pull/13514

**Comment by apc999** [comment]
@lilyzhoupeijie , @maobaolong from Tencent is also asking implementing this feature. FYI

**Comment by jja725** [comment]
seems like resolved by dynamic config update. Will close it for now, feel free to reopen it and contact us if this is still valid.
