### ISSUE TITLE
Sometimes, the command "alluxio fs free -f /" cannot clean cache completely

### ISSUE THREAD

**Issue by yangyuliufeng** [Alluxio/alluxio#13182]
**Alluxio Version:**
What version of Alluxio are you using?
alluxio 2.5.0
**Describe the bug**
Sometimes, the command "alluxio fs free -f /" cannot clean cache completely.
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
If the alluxio has mounted a path with plenty of files, the command perhaps unable to clean cache completely.
Sometimes, the command exec successfully, but the block files in ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH still exist.
Sometimes the command spend minutes of time to exec.
**Expected behavior**
Give user a precise way to clean all cache
**Urgency**
Describe the impact and urgency of the bug.
The bug impact the cache cleaning when deleting alluxio.
**Additional context**

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
