### ISSUE TITLE
FUSE hangs when removing a file that is not in the understore anymore

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13191]
**Alluxio Version:**
2.5.0-1

**Describe the bug**

The following command hangs indefinitely 
```
rm -rf ${MOUNT_POINT}/<s3-bucket-dir>/<data-dir>
```
When `<data-dir>` has been manually removed from the S3 bucket prior to running `rm`.

**To Reproduce**
- Have folder with data on S3 in `<s3-bucket>/<data-dir>`
- Mount `<s3-bucket>` to `<s3-bucket-dir>` in Alluxio
- Have Alluxio fuse mount at `${MOUNT_POINT}`
- Access `<s3-bucket-dir>/<data-dir>/` in Alluxio so data is in Alluxio
- Remove `<s3-bucket>/<data-dir>` from S3 (not via Alluxio)
- Remove the remaining files from Alluxio FUSE `rm -rf ${MOUNT_POINT}/<s3-bucket-dir>/<data-dir>`
- `rm` operation blocks indefinitely 
- Alluxio dashboard 

Alluxio FUSE service logs show:
```
WARN  FileSystemMasterClient - Delete(path=/<s3-bucket>/<data-dir>,options=recursive: false
alluxioOnly: false
unchecked: false
commonOptions {
  syncIntervalMs: -1
  ttl: -1
  ttlAction: DELETE
}
) returned  in 398831 ms (>=10000 ms)
WARN  AlluxioJniFuseFileSystem - rmdir(path=/<s3-bucket-dir>/<data-dir>) returned 0 in 398832 ms (>=10000 ms)
```
Alluxio Master logs show:
```
WARN  ObjectUnderFileSystem - Unable to delete s3://<s3-bucket>/<data-dir> because listInternal returns null
```

**Expected behavior**
- `rm` in mounted FUSE folder to exit (and not block indefinitely) when the folder does not exist in understore anymore. 
- Print warning message to the logs that the folder was not found in the understore.

**Urgency**
Medium

**Additional context**
Additionally:
- When trying to view the file in the Alluxio Dashboard at `http://0.0.0.0:19999/browse?path=%2F<s3-bucket-dir>%2Ftest-bucket%2FP<data-dir>` displays "Please wait..." with the Alluxio logo.
- `alluxio fs rm /<s3-bucket-dir>/<data-dir>` from the worker node also hangs.
- `ls ${MOUNT_POINT}/<s3-bucket-dir>/` still shows `<data-dir>`

Environment:
- Run in Docker containers (Ubuntu)
- FUSE config:
```
alluxio.fuse.jnifuse.enabled=true
alluxio.user.file.readtype.default=CACHE
alluxio.user.file.writetype.default=ASYNC_THROUGH
alluxio.fuse.maxwrite.bytes=131072
alluxio.fuse.shared.caching.reader.enabled=false
alluxio.user.metadata.cache.enabled=false
```

**Comment by peterroelants** [comment]
One way to resolve the unstable state of the system seems to be running `alluxio fs free /<s3-bucket-dir>/<data-dir>` from the worker node. This seems to exit after some time with the message `Path "/<s3-bucket-dir>/<data-dir>" does not exist.`. Afterwards the `/<s3-bucket-dir>` seems to be empty.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
