### ISSUE TITLE
Is there a way to add new HDFS cluster without restart all servers/workers

### ISSUE THREAD

**Issue by vanliu-tx** [Alluxio/alluxio#13190]
**Is your feature request related to a problem? Please describe.**
In our environment, we have several HDFS clusters and add more HDFS clusters to alluxio on project need. When we add a new cluster, we have to edit the hdfs-site.xml, copy it to all servers/workers, then restart all servers/workers one by one. It takes time. 

Is there a way to avoid restart all servers/workers?

**Describe the solution you'd like**
We want a command which could be called to let masters/workers to reload config files from local conf directory.

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by apc999** [comment]
@vanliu-tx 
can you run this command to mount UFS (e.g., new HDFS clusters) to your Alluxio service on the fly?
https://docs.alluxio.io/os/user/stable/en/core-services/Unified-Namespace.html#nested-mount-points

**Comment by vanliu-tx** [comment]
thank you! It works when adding all conf via --option from cmd line. @apc999
