### ISSUE TITLE
source code can not found alluxio.grpc.table package dependence

### ISSUE THREAD

**Issue by yangjiurong** [Alluxio/alluxio#13196]
**Alluxio Version:**
2.5.0

**Describe the bug**
source code can not found alluxio.grpc.table package dependence

**To Reproduce**
nothing

**Expected behavior**
source code can found alluxio.grpc.table package dependence

![image](https://user-images.githubusercontent.com/17909638/113978890-18d3dc80-9877-11eb-87e2-3bffddea1c2c.png)

**Comment by apc999** [comment]
@HelloHorizon  can you take a look at this issue?

**Comment by HelloHorizon** [comment]
@yangjiurong Our table service is dependent on the gRPC auto-generated class. And we don't include auto-generated code in our Github repo. If you git clone the Github code, you have to compile the proto class to see these dependencies in your IDE. Try with `mvn clean install -DskipTests`, and details can be found [here](https://docs.alluxio.io/os/user/stable/en/contributor/Building-Alluxio-From-Source.html).
And if you use IntelliJ(and previous step not work for you), you may also want fo to generated sources directory (core/transport/target) and mark it as a generated sources root.
