### ISSUE TITLE
FUSE support for auto_cache mount option

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13207]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a potential improvement.

From [some of my experiments](https://github.com/Alluxio/alluxio/issues/13161#issuecomment-815959894) it seems that the `kernel_cache` is the single largest improvement for tuning JNI-FUSE for reads.

However, libfuse also has a [`auto_cache`](https://libfuse.github.io/doxygen/structfuse__config.html#a9db154b1f75284dd4fccc0248be71f66) option as an alternative to `kernel_cache` with as difference that:
> Instead of unconditionally keeping cached data, the cached data is invalidated on open(2) if if the modification time or the size of the file has changed since it was last opened.

From the [Alluxio POSIX-API documentation](https://docs.alluxio.io/os/user/stable/en/api/POSIX-API.html) I understand that only `kernel_cache` is supported.

**Describe the solution you'd like**
Support `auto_cache` mount option in JNI-FUSE.

**Urgency**
Low

**Comment by LuQQiu** [comment]
@peterroelants `kernel_cache` is used and tested so we have more confidence in it. We haven't tried (or maybe even known) the `auto_cache` option so we don't know whether it can work or not. It may just work magically or not work sadly. Does `auto_cache` come from a certain version of libfuse? What prevents it from working showed in the POSIX API docs?

**Comment by peterroelants** [comment]
I had the time to test `auto_cache` it seems to work out of the box on FUSE 2.9.5. 

From some quick tests it seems to provide similar gains as `kernel_cache`.

**Comment by peterroelants** [comment]
I created a PR documenting this feature: https://github.com/Alluxio/alluxio/pull/13250

**Comment by peterroelants** [comment]
Closing with the PR documenting the feature merged: https://github.com/Alluxio/alluxio/pull/13250
