### ISSUE TITLE
Reading file with cat extremely slow on FUSE-JNI

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13206]
**Alluxio Version:**
2.5.0-1 & 2.5.0-2

**Describe the bug**
Reading a  770MB file with [`cat`](https://man7.org/linux/man-pages/man1/cat.1.html) through Alluxio FUSE-JNI is more than 30 times as slow compared to reading the file via FUSE-JNR.

| Fuse Type |  `cat` read | 
|:----------- |:-----------:|
| 1 - JNR-FUSE | 436 ms | 
| 2 - JNI-FUSE | **14 s** | 

**To Reproduce**
Test for both `alluxio.fuse.jnifuse.enabled=true` and `alluxio.fuse.jnifuse.enabled=false`:
- Load file into Alluxio-cache (worker with 1 RAMDisk tier). From worker: `alluxio fs load <alluxio-file-path>`
- Read file with `cat` from FUSE. From FUSE service: `time cat ${MOUNT_POINT}/<alluxio-file-path> > /dev/null`

**Expected behavior**
JNI-FUSE read time to be in the order of JNR-FUSE read time.

**Urgency**
Medium, this greatly impacts FUSE-JNI reading in certain use cases.

**Additional context**
- JNI-FUSE mount options: `attr_timeout=7200,big_writes,entry_timeout=7200,max_read=131072`
    - I didn't use `kernel_cache` because wanted to avoid data being in the client.
- JNR-FUSE mount options: `direct_io,attr_timeout=7200,big_writes,entry_timeout=7200,max_read=131072`
    - The main difference is the `direct_io` option, which is set by default with JNR-FUSE

Ran on Docker using custom containers.

Alluxio FUSE options:
- ```
  alluxio.user.file.readtype.default=CACHE
  alluxio.user.file.writetype.default=ASYNC_THROUGH
  alluxio.fuse.maxwrite.bytes=131072
  alluxio.fuse.shared.caching.reader.enabled=false
  alluxio.user.metadata.cache.enabled=false
  ```
- `MAX_IDLE_THREADS: 64`

I also did read-tests with Python Dask, in this case we don't see the extreme slowdown that reading with `cat` gives. See results at https://github.com/Alluxio/alluxio/issues/13161#issuecomment-815959894

**Comment by apc999** [comment]
@peterroelants  if you can reproduce this issue deterministically, can you share your fuse and worker logs? thanks

**Comment by peterroelants** [comment]
@apc999 

I'm also seeing a lot of following warnings in the logs when testing on my local machine:
- worker logs:
   - [`Received DATA frame for an unknown stream`](https://github.com/Alluxio/alluxio/issues/13138)
   - ` WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.UnderFileSystemBlockReader location: s3://<bucket>/<file> bytes: 1048576 openMs: 0 transferMs: 10486 durationMs: 10486`
 - FUSE logs:
   - `WARN  AlluxioJniFuseFileSystem - read(path=<alluxio_path>,buf=java.nio.DirectByteBuffer[pos=131072 lim=131072 cap=131072],size=131072,offset=549437440) returned 131072 in 11350 ms (>=10000 ms)`

I'll try to see if I can get the complete logs later this week.

**Comment by apc999** [comment]
thanks Peter. It will be very useful if you can upload the fuse.log and worker.log here

**Comment by LuQQiu** [comment]
@peterroelants Thanks for reporting this issue. One small question: What's the size of the file that you tested?

**Comment by peterroelants** [comment]
> @peterroelants Thanks for reporting this issue. One small question: What's the size of the file that you tested?

In this case it was a single 770MB file.

However, I get a similar behaviour when I save the file into smaller individual chunks: https://github.com/Alluxio/alluxio/issues/13161#issuecomment-815959894

**Comment by peterroelants** [comment]
> thanks Peter. It will be very useful if you can upload the fuse.log and worker.log here

@apc999 I get similar results (16.225s) when `cat` reading the same file on 2.5.0-2. Here are my logs:
- Alluxio Master: [alluxio-master.log](https://github.com/Alluxio/alluxio/files/6334373/alluxio-master.log)
- Alluxio Worker: [alluxio-worker.log](https://github.com/Alluxio/alluxio/files/6334375/alluxio-worker.log)
- Alluxio FUSE: [alluxio-fuse.log](https://github.com/Alluxio/alluxio/files/6334377/alluxio-fuse.log)

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
