### ISSUE TITLE
Helm chart add support for toleration

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#13203]
**Is your feature request related to a problem? Please describe.**
Currently there are only fields for `nodeSelector`. We should have the same fields for `tolerations`

**Describe the solution you'd like**
Add the fields similar to `nodeSelector`

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by ssz1997** [comment]
This is solved by https://github.com/Alluxio/alluxio/pull/13214
