### ISSUE TITLE
DistributedCp faild when Alluxio Worker dead but Alluxio Job Worker alive 

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#13211]
**Alluxio Version:**
2.3.1

**Describe the bug**
`alluxio fs distributedCp` failed when Alluxio Worker dead but Alluxio Job Worker alive.
Job Master's log shows `WARN plan.PlanCoordinator (PlanCoordinator.java:start) - Failed to select executor. Index: 84, Size: 83)` 

**Expected behavior**
DistributedCp success.

**Urgency**
Normal.

**Comment by LuQQiu** [comment]
@JySongWithZhangCe How many workers are in your cluster? One or all workers are dead in this cluster?

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe How many workers are in your cluster? One or all workers are dead in this cluster?

87 total and 4 dead

**Comment by LuQQiu** [comment]
@bradyoo Can you help take a look at the issue? Is this problem solved in the newer releases? Thanks

**Comment by bradyoo** [comment]
Can you turn on debug log on alluxio.master.job.plan.PlanCoordinator?

**Comment by JySongWithZhangCe** [comment]
> Can you turn on debug log on alluxio.master.job.plan.PlanCoordinator?

OK I'll try it

**Comment by yuzhu** [comment]
@JySongWithZhangCe hi, are you still seeing this behavior?
