### ISSUE TITLE
HiveClientPool causes the number of hive metastore connections to be too high

### ISSUE THREAD

**Issue by xinip** [Alluxio/alluxio#13227]
**Alluxio Version:**
2.5.0-1

**Describe the bug**
HiveClientPool causes the number of hive metastore connections to be too high, when there are many databases to synchronize

**To Reproduce**
We have more than 100 databases. Alluxio connected to hive metastore and generated more than 400 connections.

**Expected behavior**
There should not be so many connections. 

**Urgency**
MEDIUM

**Additional context**
The alluxio source code uses a database-level connection pool. In fact, it should use a hive metastore url connection pool.

**Comment by LuQQiu** [comment]
@yuzhu Please help take a look at this issue, thanks!
