### ISSUE TITLE
Add Shadow Cache to Measure Working Set Size

### ISSUE THREAD

**Issue by sunnyszy** [Alluxio/alluxio#13260]
**Is your feature request related to a problem? Please describe.**
Knowing the working set size during the runtime can help to tune the cache size. Since it is hard to log a trace, one approach is to build a shadow cache to track the objects in the requests. 

This measurement tool is also useful to explore the potential improvement in caching algorithms. The shadow cache can measure the hit ratio when the whole working set is in the cache and we can therefore compare the gap of the current LRU algorithm.

**Describe the solution you'd like**
A shadow cache feature: periodically, the algorithm reports the working set size in the past user-specific window, and the object (page) hit ratio under infinite cache size in this period.

**Describe alternatives you've considered**
LRU based workload history, or probabilistic counters such as "Characterizing Storage Workloads with Counter Stacks" in OSDI'14.

**Urgency**
TBD.

**Additional context**
The design doc: https://docs.google.com/document/d/1-BPKJjE8qM4bnEFgRhru50XLRaf-gS4HXKRkJIJvNjc/edit?usp=sharing.
The usage manual: https://docs.google.com/document/d/14jVQxYrjvPTj7ivLEzuTTPCwvxCMNf-A2lMl7lJ9Ccc/edit?usp=sharing

**Comment by sunnyszy** [comment]
@apc999

**Comment by sunnyszy** [comment]
@apc999  I've refactored the metrics from meters to counters in the PR and add a usage manual: https://docs.google.com/document/d/14jVQxYrjvPTj7ivLEzuTTPCwvxCMNf-A2lMl7lJ9Ccc/edit?usp=sharing

**Comment by apc999** [comment]
This feature is implemented and will be included in v2.6.1
Thanks @sunnyszy for the contribution!
