### ISSUE TITLE
Use ROCKS as local client cache not work.

### ISSUE THREAD

**Issue by neuyilan** [Alluxio/alluxio#13280]
**Alluxio Version:**
Master branch or v2.5.0-2 

**Describe the bug**
When I use the local cache mechanism of alluxio, the underlying storage uses `ROCKS`, and there will be the following errors:
![image](https://user-images.githubusercontent.com/6237070/115804951-93276380-a416-11eb-9b9b-7a165fa55e68.png)

**To Reproduce**
The following codes will produce above error

**Expected behavior**
I'm glad to know that alluxio has the ability to be a local client cache. We are also looking forward to using rocksdb as a local client cache.

**Additional context**
The test code is as follows:
[CacheTest.java.txt](https://github.com/Alluxio/alluxio/files/6362091/CacheTest.java.txt)

**Comment by neuyilan** [comment]
Hi, this problem seems to be solved to me, the previous error was due to my use of alluxio-shaded-client-${version}.jar[1]. When I use alluxio-core-client-hdfs-${version}.jar[2], there is no such problem.
These two packages are confusing to me, what is the difference between them? Which one should I use? I saw the presto use the first one[3].

[1] 
```
<dependency>
      <groupId>org.alluxio</groupId>
      <artifactId>alluxio-shaded-client</artifactId>
      <version>2.6.0-SNAPSHOT</version>
      <scope>compile</scope>
</dependency>
```
[2] 
```
<dependency>
      <groupId>org.alluxio</groupId>
      <artifactId>alluxio-core-client-hdfs</artifactId>
      <version>2.6.0-SNAPSHOT</version>
      <scope>compile</scope>
</dependency>
```
[3]  https://github.com/prestodb/presto/blob/master/presto-cache/pom.xml#L82

**Comment by apc999** [comment]
@neuyilan  we typically recommend to use the first one as in Presto codebase. Classes in `alluxio-shaded-client:org.alluxio` are shaded to avoid jar hell due to dependency conflict. I guess the rocksdb dependency was shaded in a wrong way causing your the issue. I will take a look.

**Comment by neuyilan** [comment]
@apc999 Thank you for your reply and thanks for trying to fix this problem.  BTW, I am particularly looking forward to being able to use rocksdb as a local cache in our production environment.

**Comment by neuyilan** [comment]
@apc999 BTW, Does the Alluxio local cache provide some cache hit or cache miss rate statistics? I didn't find it in the code, and I think it will be very friendly for users to analyze their business applications.

**Comment by neuyilan** [comment]
> @apc999 BTW, Does the Alluxio local cache provide some cache hit or cache miss rate statistics? I didn't find it in the code, and I think it will be very friendly for users to analyze their business applications.

Update：Sorry, I have seen the metrics statics in the source code, and I'll try to know how to use it, thanks again.
