### ISSUE TITLE
Support disabling local logs in k8s

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#13311]
**Is your feature request related to a problem? Please describe.**
When [remote logger](https://docs.alluxio.io/ee/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html#enable-remote-logging) is enabled in K8s, the user may want to just turn off local logs.

One reason is to reduce the local disk usage, as writing to the writable layer in a container may be costly. Or this may use too much of the ephemeral storage and cause the pod to be evicted.

**Describe the solution you'd like**
There should be a way to turn off local logging.

One of the possible solution is to offer mounting a modified log4j.properties to `${ALLUXIO_HOME}/conf/log4j.properties` on all containers. In the modified log4j.properties we disable the local logs and only enable remote loggers.

This is one way to change the loggers.

From
```
# Appender for Job Master
log4j.appender.JOB_MASTER_LOGGER=org.apache.log4j.RollingFileAppender
log4j.appender.JOB_MASTER_LOGGER.File=${alluxio.logs.dir}/job_master.log
log4j.appender.JOB_MASTER_LOGGER.MaxFileSize=10MB
log4j.appender.JOB_MASTER_LOGGER.MaxBackupIndex=100
log4j.appender.JOB_MASTER_LOGGER.layout=org.apache.log4j.PatternLayout
log4j.appender.JOB_MASTER_LOGGER.layout.ConversionPattern=%d{ISO8601} %-5p %c{2} (%F:%M) - %m%n
```

To
```
# Appender for Job Master
log4j.appender.JOB_MASTER_LOGGER=org.apache.log4j.varia.NullAppender
```

**Describe alternatives you've considered**

**Urgency**
MEDIUM

**Additional context**

**Comment by jiacheliu3** [comment]
@ssz1997 does this make sense to you? Just reassigned from the previous owner.

**Comment by ssz1997** [comment]
@jiacheliu3 Starting from CE300 we may not have a remote logger any more, so the prerequisite won't be there any more. Let me know if there's any other concern. Otherwise I'll close this issue on Apr 11.
