### ISSUE TITLE
Alluxio-FUSE containers don't have /etc/fuse.conf

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13322]
**Alluxio Version:**
2.5.0 & 2.5.0-2

**Describe the bug**
There doesn't seem to be a `/etc/fuse.conf` template file in the fuse-containers. This file is used for example to allow other users to access the FUSE filesystem.

**To Reproduce**
```
❯ docker run -it -u root --entrypoint='' alluxio/alluxio-fuse:2.5.0-2 ls -al /etc/fuse.conf
ls: cannot access '/etc/fuse.conf': No such file or directory
```

```
❯ docker run -it -u root --entrypoint='' alluxio/alluxio-fuse:2.5.0 ls -al /etc/fuse.conf
ls: cannot access '/etc/fuse.conf': No such file or directory
```

**Expected behavior**
Template of `/etc/fuse.conf` to be available in the Alluxio-fuse containers

**Comment by apc999** [comment]
@peterroelants I updated docker image of 2.5.0-3 to include /etc/fuse.conf by default.
Please take a look. closing this ticket for now.
