### ISSUE TITLE
Alluxio Fuse GC failure

### ISSUE THREAD

**Issue by AlexChenSkyBlue** [Alluxio/alluxio#13400]
Hi,

We have seen our alluxio fuse pod keep get GC failure after running sometime. We have to manually restart pod. Is there setting related to alluxio fuse pod GC?

**Comment by AlexChenSkyBlue** [comment]
[Eden: 0.0B(1632.0M)->0.0B(1632.0M) Survivors: 0.0B->0.0B Heap: 32689.1M(32768.0M)->32689.1M(32768.0M)]
 [Times: user=0.00 sys=0.00, real=0.00 secs] 
2021-05-13T01:21:58.732+0000: 61322.243: [Full GC (Allocation Failure)  32689M->32689M(32768M), 7.3094920 secs]
   [Eden: 0.0B(1632.0M)->0.0B(1632.0M) Survivors: 0.0B->0.0B Heap: 32689.1M(32768.0M)->32689.1M(32768.0M)], [Metaspace: 29241K->29241K(34816K)]
相关日志，
相关参数设置： 
fuse:
  env:
    MAX_IDLE_THREADS: "64"
  image: alluxio/alluxio-fuse
  imageTag: 2.5.0-2
  imagePullPolicy: IfNotPresent
  # Change both to true to deploy FUSE
  enabled: false
  clientEnabled: false
  # Properties for the fuse component
  properties:
    alluxio.fuse.jnifuse.enabled: "false" 
    alluxio.fuse.shared.caching.reader.enabled: "true"
    alluxio.fuse.debug.enabled: "true" 
    alluxio.fuse.cached.paths.max: "3000000"
    alluxio.fuse.logging.threshold: 1000ms
    alluxio.fuse.user.group.tranlation.enabled: "true"
  # Customize the MaxDirectMemorySize
  # These options are specific to the FUSE daemon
  jvmOptions:
    - "-Xmx32G -Xms32G -XX:+UseG1GC -XX:MaxDirectMemorySize=64G -XX:ActiveProcessorCount=4 -XX:+UnlockExperimentalVMOptions -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
  hostNetwork: true
  # hostPID requires escalated privileges
  hostPID: true
  dnsPolicy: ClusterFirstWithHostNet
  user: 0
  group: 0
  fsGroup: 0
  args:
    - fuse
    - --fuse-opts=kernel_cache,max_read=131072,attr_timeout=7200,entry_timeout=7200,allow_other
  # Mount path in the host
  mountPath: /mnt/alluxio-fuse
  resources:
    limits:
      cpu: 4
      memory: 96G
    requests:
      cpu: 4
      memory: 96G
  podAnnotations: {}
  nodeSelector:
    alluxio: worker

**Comment by calvinjia** [comment]
Hi @AlexChenSkyBlue thanks for reporting this issue. Are you on Java 8 or 11? We recommend to use concurrent mark and sweep instead of G1GC `-XX:+UseConcMarkSweepGC`

**Comment by AlexChenSkyBlue** [comment]
We are using official docker image which is using java 8. Do you suggest we switch to java 11? we will try the jvm option

**Comment by calvinjia** [comment]
@AlexChenSkyBlue Were you able to avoid this issue with the GC option?

**Comment by apc999** [comment]
@AlexChenSkyBlue did you get the following setting from any of our documentation? If yes, we will update the docs as G1GC is not well supported for JVM8 (used in our official docker image)

`jvmOptions:
- "-Xmx32G -Xms32G -XX:+UseG1GC -XX:MaxDirectMemorySize=64G -XX:ActiveProcessorCount=4 -XX:+UnlockExperimentalVMOptions -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
hostNetwork: true`

**Comment by AlexChenSkyBlue** [comment]
No, I suspect it may due to our cluster has large amount of data reader, over 100T per day. We use this option:
alluxio.fuse.shared.caching.reader.enabled = true. We try to disable it to see if it improve

**Comment by AlexChenSkyBlue** [comment]
After we switch to jnifuse with client cache disabled. this problem seems goes away
