### ISSUE TITLE
getBlockInfo call is not efficient

### ISSUE THREAD

**Issue by yuzhu** [Alluxio/alluxio#13416]
**Alluxio Version:**
2.5

**Describe the bug**
getBlockInfo call can take a very long time

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
 pingMetaService can be an expensive operation (take ~500ms in my test) to determine the primary master rpc address and in the connect() function in AbstractClient , we are basically calling it 3 times
 in getAddress()
 in getConfAddress()
 in checkVersion  (It doesnt call pingMetaService explicitly but still call the versionService)

**Comment by apc999** [comment]
with #13881 closed, will we close this issue @yuzhu @ggezer ?

**Comment by jiacheliu3** [comment]
Can this be closed?
