### ISSUE TITLE
Fail tests in alluxio worker while deployed in docker

### ISSUE THREAD

**Issue by ssz1997** [Alluxio/alluxio#13420]
**Alluxio Version:**
Alluxio:2.5.0-3

**Describe the bug**
Following https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html, while deploying alluxio in docker and run tests in worker, 12 tests fail.

**To Reproduce**
In an environment with docker installed:
1. `mkdir -p /tmp/alluxio_ufs`
2. `docker run -d --rm \
    --net=host \
    --name=alluxio-master \
    -v /tmp/alluxio_ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS=" \
       -Dalluxio.master.hostname=localhost \
       -Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage" \
    alluxio/alluxio master`
3. `docker run -d --rm \
    --net=host \
    --name=alluxio-worker \
    --shm-size=1G \
    -v /tmp/alluxio_ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS=" \
       -Dalluxio.worker.ramdisk.size=1G \
       -Dalluxio.master.hostname=localhost" \
    alluxio/alluxio worker`
4. `docker exec -it alluxio-worker /bin/bash`
5. `cd /opt/alluxio`
6. `./bin/alluxio runTests`

**Expected behavior**
Expecting pass all tests

@LuQQiu

**Comment by LuQQiu** [comment]
@HelloHorizon This is the .alluxio_ufs_persistence related failure

**Comment by ssz1997** [comment]
alluxio/alluxio:2.8.0 has no such problem. Close the issue.
