### ISSUE TITLE
Fail to helm upgrade logserver deployment in k8s

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#13422]
**Alluxio Version:**
2.5.0

**Describe the bug**
The logserver deployment is using default strategy which is `RollingUpdate`
```
StrategyType: RollingUpdate
MinReadySeconds: 0
RollingUpdateStrategy: 25% max unavailable, 25% max surge
```

When using helm to upgrade, the new logserver pod will fail to create because the PVC is RWO. The new pod will fail to get the PV, and the old one will fail to give up. This is a deadlock.
```
alluxio-logserver-54fbc78989-6rh78 0/1 ContainerCreating 0 4m35s
alluxio-logserver-6b7b485ffc-g994f 1/1 Running 0 19d

Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Normal Scheduled 4m28s default-scheduler Successfully assigned xxxx/alluxio-logserver-54fbc78989-6rh78 to xxxx-k8s-dev32
Warning FailedAttachVolume 4m28s attachdetach-controller Multi-Attach error for volume "pvc-2a1f15a9-06e3-4e8c-ae6b-fdc032db67a1" Volume is already used by pod(s) alluxio-logserver-6b7b485ffc-g994f
Warning FailedMount 9s (x2 over 2m25s) kubelet Unable to attach or mount volumes: unmounted volumes=[alluxio-logs], unattached volumes=[alluxio-logs default-token-r6bfs]: timed out waiting for the condition
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
The logserver should be able to upgrade with helm.

**Urgency**
MEDIUM

**Additional context**

**Comment by jiacheliu3** [comment]
This deadlock can be broken by changing strategy to `Recreate`, where the old pod will be destroyed first.
Ref: https://betterprogramming.pub/understanding-kubernetes-deployment-strategies-12535c3cb379

**Comment by ssz1997** [comment]
Issue resolved. Thus closing this issue.
