### ISSUE TITLE
Throw CCE when using Fuse while enable client cache

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13442]
**Alluxio Version:**
Alluxio master branch, HEAD

**Describe the bug**

![image](https://user-images.githubusercontent.com/17329931/118772342-394f7780-b8b6-11eb-9e6b-5facbbe8cac7.png)

```
java.lang.ClassCastException: alluxio.client.file.cache.LocalCacheFileInStream cannot be cast to alluxio.client.file.AlluxioFileInStream
        at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:429)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$17(AlluxioJniFuseFileSystem.java:404)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
        at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:404)
        at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)
```

**To Reproduce**

Enable client cache in `alluxio-site.properties`

```
alluxio.user.client.cache.enabled=true
```

And then start Alluxio-fuse, read a file

**Expected behavior**

get the content of the file.

**Urgency**

Urgent, block to use Alluxio Local Cache.

**Additional context**
No.

**Comment by maobaolong** [comment]
# How to fix this bug

![image](https://user-images.githubusercontent.com/17329931/118773053-ff32a580-b8b6-11eb-89b9-e7bdfdb56099.png)

A simple workaround is test the is, if it is not the `AlluxioFileInStream`, turn to the original logic like the above code.

**Comment by maobaolong** [comment]
@bzheng888 Will take this issue and fix it, @LuQQiu please take a look at the PR when @bzheng888 make it ready to review, Thanks @bzheng888 @LuQQiu

**Comment by apc999** [comment]
@maobaolong  could you elaborate why you want to enable client cache on FUSE, do you plan to run FUSE process standalone? Otherwise, you can leverage the FUSE+Worker combination and achieve similar performance

**Comment by maobaolong** [comment]
@apc999 Hi Bin, In our scenario, we have to use `standalone` mode fuse, because the alluxio-fuse is out of our alluxio cluster, even worse, the ttl between alluxio-fuse and alluxio cluster are high ~4ms, so we'd like to enable client.metadata.cache and client.local.cache feature to reduce the communicate and data transform between alluxio-fuse and alluxio cluster, but met this CCE.

**Comment by AlexChenSkyBlue** [comment]
We plan to use FUSE+Worker combination.  but there is no valid kubernetes helm deployment option yet
