### ISSUE TITLE
Pin RPC raise master's cpu usage in high level

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#13458]
**Alluxio Version:**
2.3.1

**Describe the bug**

- There is about 35TB data pined in Alluxio in disk.
- Each block of the data has  3 replicas.
- File size of the data is around 50MB.
- Master's CPU usage is over 80%.
- Users want to pin over 150TB data (not include replicas) in Alluxio, because the speed of data transformation between remote UFS and Alluxio is too slow, and the use cases have specific deadline. 

**Urgency**
Normal

**Comment by HelloHorizon** [comment]
@JySongWithZhangCe Thanks for reporting, will take a look.
