### ISSUE TITLE
Get the exist id if the worker restart

### ISSUE THREAD

**Issue by kuszz** [Alluxio/alluxio#13473]
**Describe the solution you'd like**
Store the worker id when it start first time, get the id from local file when restart and update the workerInfo if address changed.

**Urgency**
Getting the exist id can prevent the loss of workerInfo.

**Comment by LuQQiu** [comment]
@kuszz Hold on for implementing this feature. 
For this feature, we need a more detailed design to see if the changes is needed, need to consider all the possible corner cases that may occur and compatibility issues. 

Please follow the https://docs.alluxio.io/os/user/stable/en/contributor/Contributor-Getting-Started.html#submit-your-feature
to submit a design doc about this feature.

**Comment by apc999** [comment]
@kuszz  please share your design doc here following convention https://docs.alluxio.io/os/user/stable/resources/templates/Design-Document-Template.md
Meanwhile, I will tag @ggezer to review your design before we proceed to review implementation.

**Comment by kuszz** [comment]
> @kuszz please share your design doc here following convention https://docs.alluxio.io/os/user/stable/resources/templates/Design-Document-Template.md
> Meanwhile, I will tag @ggezer to review your design before we proceed to review implementation.

https://docs.google.com/document/d/11MCHlgx0MP5_SN2JRP9Myd9A528TS0rTLt-3U-ssTaw/edit#
If something need to add in doc, please tell me, thanks

**Comment by LuQQiu** [comment]
@kuszz can you update the link to give community users read and comment access? Unable to open the doc

**Comment by kuszz** [comment]
> @kuszz can you update the link to give community users read and comment access? Unable to open the doc

https://docs.google.com/document/d/11MCHlgx0MP5_SN2JRP9Myd9A528TS0rTLt-3U-ssTaw/edit?usp=sharing

**Comment by apc999** [comment]
Offline discussion
- An issue was reported when `alluxio.network.ip.address.used` is switched, and that worker lost all blocks.
- If worker restarts with different hostname/ IP, in theory, master will not let worker reformat all blocks, unless the inode tree does not recognize the blocks
- discussed with @jiacheliu3 , we want worker to be stateless. Let's fix this bug rather than having a state on worker.


Close this issue for now
