### ISSUE TITLE
Add a switch about whether FileMaster update accessTime when reading files

### ISSUE THREAD

**Issue by kuszz** [Alluxio/alluxio#13495]
**Describe the solution you'd like**
Add a field in alluxio-site.properties，if the field not set, the master will update accessTime when reading file.

**Urgency**
The master might under great pressure in high concurrency if update accsstime when reading file.

**Comment by ggezer** [comment]
@kuszz Please elaborate on the pressure you mentioned. Is it memory or CPU pressure you're seeing?
Do you have a custom setting for `alluxio.master.file.access.time.journal.flush.interval` ?

**Comment by kuszz** [comment]
It seems no need to add new switch, so close this issue, sorry
