### ISSUE TITLE
Support transfer leadership to a specific follower master in raft based ha cluster

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13499]
**Is your feature request related to a problem? Please describe.**
In a raft based ha cluster, for some reason, we want to transfer leadership to a specific follower gracefully, now, we have to kill the leader master to transfer leadership, but the leadership could transfer to a unexpected follower, we have to kill the leader master again, this is so tricky.

**Describe the solution you'd like**

Support a command line tools like `alluxio ha failover [<NEXT_LEADER_HOST>]`, without specific NEXT_LEADER_HOST, leadership can transform automatically.

**Describe alternatives you've considered**

We can leverage the ratis support from these PRs 

https://github.com/apache/ratis/pull/372/
https://github.com/apache/ratis/pull/366
https://github.com/apache/ratis/pull/373

**Urgency**

Normal

**Additional context**
Look forward to see this feature.

**Comment by LuQQiu** [comment]
@ggezer FYI

**Comment by apc999** [comment]
Based on the offline discussion: not a blocker but an important improvement
Once we have bandwidth, we can revisit this issue. 
And we need a design doc on this feature, reviewed by @ggezer

**Comment by maobaolong** [comment]
https://github.com/apache/ratis/pull/359 Shown that ratis support dynamic change priority.
