### ISSUE TITLE
Failed to write large files into Fuse mount point.

### ISSUE THREAD

**Issue by sg-c** [Alluxio/alluxio#13523]
**Alluxio Version:**
2.6.0-SNAPSHOT (Revision # was not written down.)

**Describe the bug**
With S3 as the UFS, large file cannot be written to FUSE mount point.

**Reproduce the issue**
prep: mount alluxio worker fuse to /mnt/alluxio-fuse and check the mount succeeds
UFS: s3 
commands:
$ head -c 1G </dev/urandom > /tmp/random.touch
$ cp /tmp/random.touch /mnt/alluxio-fuse
result:
$ cp /tmp/random.touch /mnt/alluxio-fuse/
cp: cannot create regular file '/mnt/alluxio-fuse/random.touch': Input/output error
log:
2021-05-27 08:19:16,682 ERROR AlluxioJniFuseFileSystem - Failed to open path=/random.touch,overwrite=false:
alluxio.exception.FileIncompleteException: Cannot read from /random.touch because it is incomplete. Wait for the file to be marked as complete by the writing thread or application.
	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:449)
	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:437)
	at alluxio.client.file.FileSystem.openFile(FileSystem.java:529)
	at alluxio.fuse.AlluxioJniFuseFileSystem.openInternal(AlluxioJniFuseFileSystem.java:382)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$open$4(AlluxioJniFuseFileSystem.java:363)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.open(AlluxioJniFuseFileSystem.java:363)
	at alluxio.jnifuse.AbstractFuseFileSystem.openCallback(AbstractFuseFileSystem.java:171)
2021-05-27 08:19:16,682 WARN  AlluxioJniFuseFileSystem - Fuse.Open(path=/random.touch,flags=0x8001) returned -5 in 5004 ms (>=1000 ms)

**Expected behavior**
The file  /tmp/random.touch is written to Alluxio as well as s3 without problem.

**Other Context**
HDFS is used as the UFS and same exception was NOT observed in that case.

**Comment by sg-c** [comment]
Some observations and questions:
1. the copy is "shut down" in 10sec. is it related to any timeout settings?
2. if the file size is small such as 1K, no problem observed and copy can succeed.
3. for small files such as those of 1K, even if the file is successfully copied from local to fuse mount point, the `alluxio fs ls` shows it's never got persisted automatically, no matter the UFS is S3 or HFDS. is it expected?

**Comment by LuQQiu** [comment]
Will try to do local reproduce or Linux single node reproduce first

**Comment by LuQQiu** [comment]
@sg-c What's the detailed configuration that you used?

**Comment by ssz1997** [comment]
I did exactly the same on a linux machine but can't seem to reproduce it. The file got copied into /mnt/alluxio-fuse without any problem.

**Comment by LuQQiu** [comment]
The steps for ssz1997 to reproduce the issue is
1. Configure alluxio with S3 root UFS
2. Launch Alluxio cluster (plain install without docker)
3. Create alluxio path /large_file
4. mkdir /mnt/alluxio-fuse, chown, chmod 755
5. integration/fuse/bin/alluxio-fuse mount /mnt/alluxio-fuse /large_file
6. Follow the issue, create the random.touch, copy it to /mnt/alluxio-fuse, and everything works without any error

@sg-c there could be some Alluxio or FUSE configuration differences. Could you share that information to help us reproduce the issue? If this issue is not a priority for now, please also let us know, thanks!

**Comment by sg-c** [comment]
Hi Lu, I missed you guy's comments because the notifications were sent to my personal email inbox. I will run the `alluxio collectInfo` and send the results to you.

**Comment by sg-c** [comment]
@LuQQiu & @ssz1997 , I did the test again with 2.6.0-1.0 EE version. It works fine for me now. I will go ahead close this time and let you know if I can reproduce it again. Thank you both.
