### ISSUE TITLE
Format error when hostname is different with dns hostname

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13595]
**Is your feature request related to a problem? Please describe.**

```
2021-05-24 22:24:27,660 ERROR Format - Failed to format
java.lang.IllegalStateException: The cluster addresses ([my-alluxio-master1.xxx.com:19200, my-alluxio-master2.xxx.com:19200, my-alluxio-master3.xxx.com:19200]) must contain the local master address (HOST-192-168-100-111:19200)
        at com.google.common.base.Preconditions.checkState(Preconditions.java:824)
```

![image](https://user-images.githubusercontent.com/17329931/121108613-a3679680-c83c-11eb-8c37-1f360af37f3c.png)

**Describe the solution you'd like**

We can use nslookup tools to resolve the hostname from dns server and cache it for this Process.

**Describe alternatives you've considered**

Run 

**Urgency**

Normal

**Additional context**

**Comment by ssz1997** [comment]
Fixed
