### ISSUE TITLE
Add a in Alluxio file count and in Alluxio block metrics

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13613]
**Is your feature request related to a problem? Please describe.**

To measure cache state of Alluxio cluster, we care about the inode count, block count and cached bytes, in-Alluxio block count, in-Alluxio file count.

Now, we lack of cached block count, cached file count related metrics.

**Describe the solution you'd like**

Add metrics for in-alluxio block count, in-alluxio file count, adjust the value when block report.

**Urgency**

Normal

**Additional context**

No

**Comment by jja725** [comment]
@maobaolong hi is this resolved in the recent version?

**Comment by maobaolong** [comment]
@jja725 Yeah, it have been resolved.
