### ISSUE TITLE
Alluxiofuse embedded in Alluxioworker performance test follow up

### ISSUE THREAD

**Issue by allenhaozi** [Alluxio/alluxio#13669]
#12830 has been merged

If there are performance and stability tests, please update this issue. Thank you

**Comment by apc999** [comment]
@allenhaozi we are working on a benchmarking whitepaper to show the performance and tutorial to setup benchmark.
@LuQQiu  can provide more details

**Comment by LuQQiu** [comment]
Yeah, we are working on a CPU instance [DALI](https://www.google.com/search?q=Nvidia+DALI&oq=Nvidia+DALI+&aqs=chrome..69i57j69i59j69i60l3.3365j0j1&sourceid=chrome&ie=UTF-8) read benchmarking to mock the actual ML/AI data loading, processing phrases.  After the env and DALI script is ready, we will do more benchmarking to understand the performance impact of Fuse on Worker and future performance improvements.

**Comment by allenhaozi** [comment]
Is there any update ?
