### ISSUE TITLE
versioning for local cache filesystem

### ISSUE THREAD

**Issue by njjry** [Alluxio/alluxio#13681]
Problem: When using Alluxio as a local cache, there is no good way to know if the data cached in the Alluxio is valid or not. 

Solution: I'd like to propose using the modification time of the file as the version. So that cached data can be compared with the HDFS file modification time to decide if the data is still valid. If it is not valid, it is deleted from Alluxio and reload the most updated data.

Significance: This feature can make sure Alluxio always gets the most updated data.

**Comment by apc999** [comment]
https://github.com/Alluxio/alluxio/pull/13955 targets to address this by adding lastModificationtime to local cache on file level
