### ISSUE TITLE
删除文件导致上级文件夹也被删除

### ISSUE THREAD

**Issue by JYHarvest** [Alluxio/alluxio#13685]
alluxio fs mkdir /t1
alluxio fs mkdir /t1/t2.txt
alluxio fs rm /t1/t2.txt
alluxio fs ls /t1  路径找不到

**Comment by dbw9580** [comment]
Hi, I can't reproduce this on my Alluxio instance. Can you share more details, e.g. what's your Alluxio setup (local, cluster, under storage), what commands did you use, and what were their output, and any error logs?

**Comment by apc999** [comment]
@JYHarvest may you share your `master.log`? I feel `alluxio fs mkdir /t1` may not succeed thus `alluxio fs ls /t1` failed

**Comment by apc999** [comment]
feel free to re-open this issue when you can provide more info
