### ISSUE TITLE
Unable to initialize worker storage directory does not lead to Alluxio quiting

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13699]
**Alluxio Version:**
2.5.0-3

**Describe the bug**
I have a multi-tiered storage defined as:
```
# Set alluxio.worker.ramdisk.size in config
alluxio.worker.tieredstore.levels=2
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/tmpfs
alluxio.worker.tieredstore.level0.dirs.mediumtype=MEM
# Set alluxio.worker.tieredstore.level0.dirs.quota in config
alluxio.worker.tieredstore.level1.alias=HDD
alluxio.worker.tieredstore.level1.dirs.path=/mnt/hdd-cache
alluxio.worker.tieredstore.level1.dirs.mediumtype=HDD
```

However, it seems like my tmpfs was setup incorrectly (by me, not Alluxio). Due to this incorrect setup Alluxio was not able to initialize the level 0 storage. In worker logs this popped up:
```
2021-06-24 05:30:57,382 ERROR DefaultStorageTier - Unable to initialize storage directory at /mnt/tmpfs/alluxioworker: Failed to create folder /mnt/tmpfs/alluxioworker
```

However, this was already happing in our system for a while, and we did not notice because Alluxio still continued to work.

**Expected behavior**
I would have expected Alluxio to error when setting up, instead of just printing an error to the log.

Or alternatively, it would be nice to have some kind of "robust" option that we can set in the Alluxio config, that makes sure that Alluxio fails to start when any errors are found.

**Urgency**
Minor

**Comment by LuQQiu** [comment]
I took a look at the code, looks like all the "failed to initialize storage" will be added to "mLostStorage" but we didn't stop the worker process from coming up.

The following command can help diagnose the issue earlier
```
./bin/alluxio fsadmin doctor storage
```
For more information, please take a look at https://docs.alluxio.io/os/user/stable/en/operation/Admin-CLI.html#doctor

I do feel that it's worth to not start the AlluxioWorker when failed to initialize, what's your thoughts @ggezer

**Comment by peterroelants** [comment]
I didn't know about `docker`, I'll look into that to ensure my setup is correct in the meantime. Thanks!

**Comment by ggezer** [comment]
For elasticity, I'd prefer workers to start in the face of individual disk failures.
However, we might be more verbose and loud about such failures via logging/webUI warning etc.
