### ISSUE TITLE
Can alluxio resolve problem that real-time computing system write too much small file on hdfs

### ISSUE THREAD

**Issue by ns7381** [Alluxio/alluxio#13738]
When I using sparkstreaming write to hive table, it always lead to genenrate too much small files on hdfs. Is there any way to solve this problem using alluxio?

**Comment by apc999** [comment]
hi @ns7381  thanks for asking the question. Here is my view on your question:

Writing a massive amount of small files is definitely supported in Alluxio (as an alternative of HDFS), but how it performs may depend on a lot of factors, including file number, size, intensity, and directory structure and many others. It is hard to tell if Alluxio will definitely perform better than HDFS for your specific use case (writing a lot of small files). In our users, I see Alluxio deployed more often for read-only or read-heavy workloads today.
