### ISSUE TITLE
Support option to bypass all tables in a database in Alluxio Catalog Service

### ISSUE THREAD

**Issue by utk-spartan** [Alluxio/alluxio#13731]
**Is your feature request related to a problem? Please describe.**
For bypassing all tables in a database, the json config file needs to contain list of all the tables, which is difficult manage if there are frequent table additions/deletions.

**Describe the solution you'd like**
Add another config option eg:  "-o catalog.db.config.ufs.bypass.enabled" to attachdb command, to support this functionality.

**Describe alternatives you've considered**
Dynamically updating the bypassSpec json file each time attachdb or sync command are run.

**Urgency**
Normal

**Additional context**

**Comment by apc999** [comment]
@dbw9580 @maobaolong @HelloHorizon  feel free to communicate your thoughts here

**Comment by HelloHorizon** [comment]
@utk-spartan Is there any reason to bypass all tables?

**Comment by utk-spartan** [comment]
Same use cases of tableBypass functionality but allowing configuring it on a db level to make configuration simpler.

Let me take an example,
lets say I have 100 database/schemas in the UDB, and UFS of only a subset of these can be mounted to Alluxio (due to various reasons security, data volume etc.).
Lets say there are 50 of these databases which require all of their tables mounted with ufsBypass enabled.
To do this, currently the udbBypass config needs to contain list of all the tables, if this list is huge or there are very frequent table additions/deletions, maintaining this config file becomes unwieldly, as the config file needs to be updated before running `table sync`.

**Comment by utk-spartan** [comment]
I have done some preliminary work around its implementation, would like to contribute to upstream.

I have gone through the Contribution-getting-started guide
Do I need to create a design doc on how I am thinking of implementing it?

**Comment by HelloHorizon** [comment]
Got what you mean, I think @dbw9580 proposed the design in #13667. Let's move the discussion there.
