### ISSUE TITLE
Using an all-in-one image in whole alluxio

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13742]
**Is your feature request related to a problem? Please describe.**

To reduce the related images of Alluxio.

**Describe the solution you'd like**

Build an all-in-one image

**Describe alternatives you've considered**

Combine the dockerfile into one.

**Urgency**

Normal

**Additional context**

No

**Comment by apc999** [comment]
@maobaolong  this task is assigned to @ssz1997 to unify alluxio/alluxio and alluxio/alluxio-fuse docker images

**Comment by LuQQiu** [comment]
I think @maobaolong is asking for a docker image that is able to run Alluxio, Alluxio-fuse, and Alluxio CSI. @ssz1997 's PR consolidate alluxio and alluxio-fuse docker image. The item left is integrate CSI docker file into alluxio docker file https://github.com/Alluxio/alluxio/blob/master/integration/csi/Dockerfile 
@ssz1997 We can work on integrating CSI into Alluxio docker file later
