### ISSUE TITLE
Add more information when registering the worker

### ISSUE THREAD

**Issue by codings-dan** [Alluxio/alluxio#13763]
**Is your feature request related to a problem? Please describe.**
When upgrading Alluxio in our cluster, we typically do a rolling upgrade in our K8s cluster. During that, we typically upgrade the workers in batches, so some workers in the cluster will have different version/revision from others. We would like that to be reported to the master so the master can display those information on the UI and in `alluxio fsadmin` commands. 

It will also be very helpful if we can associate issues/performance with the worker version/revision, so during the rolling upgrade we can be notified if the upgrade is bad and we should roll back.

Especially when we are using `SNAPSHOT` versions, it is hard to tell which version/revision the worker is on.

**Describe the solution you'd like**
We want to get more information about workers on the master side. Add the version and revision information of the worker

**Urgency**
Normal

**Additional context**
No

EDIT: rephrased use case and requirements on 2021/10/27

**Comment by LuQQiu** [comment]
@maobaolong @codings-dan As we discussed in the last AI sync, can you help add more detailed upper level information about why this change is needed? Like the background usecase
