### ISSUE TITLE
Non Leader master should also start web server

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13840]
**Is your feature request related to a problem? Please describe.**

- When ha didn't work as expected, or the leader didn't transfer to a new master, there are no leader that time, so we want to the the stacks from web page.

- We want to scrap the metrics of non-leader masters by prometheus, to monitor the gc, heap, and some other metrics of it.

**Describe the solution you'd like**

Start the web server all the time, although it isn't leader.

**Describe alternatives you've considered**

Start the web server all the time, although it isn't leader.

**Urgency**
High

**Additional context**
No

**Comment by ssz1997** [comment]
Supported by https://github.com/Alluxio/alluxio/pull/14259.
