### ISSUE TITLE
Alluxio job master crash caused by OOM

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13907]
**Alluxio Version:**

Master branch from hash   601272157bf

**Describe the bug**

Alluxio job master crash after I use distributed load  several times.

We see oom from alluxio job service master, and the cost time of leadership transfer took 30 minute(Maybe include gc pause times)

This is the related metrics of job master
![image](https://user-images.githubusercontent.com/17329931/128691991-f6c7dbeb-a366-4c33-8b39-da95e733b17d.png)

Thought from me, now, each job is for a file, so there are so many jobs for one time distributedLoad execution, in fact, we can change to let each job load more than one file, it can reduce the job counts.

I use mat analyzed the generated heap dump file after finished distributed loading a big directory, and get the following information

![image](https://user-images.githubusercontent.com/17329931/128711187-25152aa7-ea7d-495e-b18c-0bcea933cb79.png)

![image](https://user-images.githubusercontent.com/17329931/128711220-b7e639dd-0715-4c57-a9f3-30f9f74dd5ed.png)

![image](https://user-images.githubusercontent.com/17329931/128711535-817733da-dfd8-4e1c-9d26-99a6505a3948.png)

![image](https://user-images.githubusercontent.com/17329931/128712010-51c94db3-bc10-45d0-a9e2-a3ce569e3901.png)

![image](https://user-images.githubusercontent.com/17329931/128727501-23aa81fa-9bec-4836-b528-4117beab6d62.png)

**To Reproduce**

Start a alluxio cluster with a jobmaster and assign 16core, 32G MEM resources, load some directories with many small files, we can see the heap used memory increased all the time, although, guess there are some memory leak, or not sure whether there are some magic configure key can helps to workaround

**Expected behavior**

The heap memory can increase smoothly and decreased by ygc.

**Urgency**

Urgent, we cannot use job services to load date now.

**Additional context**

No.

**Comment by maobaolong** [comment]
@yuzhu Would you please take a look at this issue, it's a blocker to load big amount dataset in our scenario.

**Comment by beinan** [comment]
@yuzhu can we close this issue?

**Comment by yuzhu** [comment]
@beinan waiting for confirmation from @maobaolong that the patch alleviates the issue

**Comment by maobaolong** [comment]
@yuzhu Thanks for your fix, I have a workaround approach, that is just increase our worker heap memory and decrease the `alluxio.job.master.job.capacity`

**Comment by apc999** [comment]
ok. I will close this issue for now and feel free to reopen it if @yuzhu 's fix is not working
