### ISSUE TITLE
generate-tarballs.sh with release and hadoop-distributions, the hadoop-distributions param has no effect

### ISSUE THREAD

**Issue by adol001** [Alluxio/alluxio#13962]
**Alluxio Version:**
2.6.1

**Describe the bug**
hadoopClients []string as a param in generateTarball method from generate-tarball.go
isn't used
so when you call generate-tarballs.sh with release and hadoop-distributions, the hadoop-distributions param has no effect

**To Reproduce**
go run src/alluxio.org/build-distribution/main.go release -hadoop-distributions=hadoop-2.7
the hadoop-distributions param has no effect

However, main.go single -hadoop-distribution=hadoop-2.7 has effect, because of 
`singleCmd.StringVar(&hadoopDistributionFlag, "hadoop-distribution", defaultHadoopClient, "the hadoop distribution to build this Alluxio distribution tarball")
`

**Expected behavior**
You can choose the version to release

**Comment by apc999** [comment]
@Xenorith  can you take a look at this issue as it is tooling?

**Comment by Xenorith** [comment]
yeah i'll take a look at this
