### ISSUE TITLE
Worker Container OOMKilled in Kubernetes Deployment

### ISSUE THREAD

**Issue by ffcai** [Alluxio/alluxio#13976]
**Alluxio Version:**
2.6.1

**Describe the bug**
We use Helm to deploy an Alluxio cluster on Kubernetes following the [doc](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html). We configured to run single master and 8 workers, for memory, we set 32G for the master and 64G for each worker. We are seeing the workers' memory usage keeps growing exceed the k8s container limit and triggering OOM.

```
➜  ~ kubectl get pod
NAME                   READY   STATUS             RESTARTS   AGE
alluxio-master-0       2/2     Running            1          110m
alluxio-worker-59ggl   0/2     CrashLoopBackOff   29         122m
alluxio-worker-64fj8   0/2     CrashLoopBackOff   28         122m
alluxio-worker-b42bd   1/2     CrashLoopBackOff   28         122m
alluxio-worker-cbsrj   0/2     CrashLoopBackOff   23         122m
alluxio-worker-gfpbp   1/2     Running            29         122m
alluxio-worker-ghdm7   0/2     CrashLoopBackOff   29         122m
alluxio-worker-mf2gl   0/2     CrashLoopBackOff   29         122m
alluxio-worker-mxzgs   0/2     CrashLoopBackOff   27         122m
```

**To Reproduce**
Follow the [doc](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html) to deploy on Kubernetes, use the [config](https://gist.github.com/ffcai/fd1239bdd5a685fdea43d0a18007e2c3) to customize some configs and settings. After mount S3 buckets and run for ~30 mins, we start to see worker containers restarts caused by OOMKilled in k8s. Sometimes it gets worse, the pods failed to re-create containers, also caused by OOMKilled.

This is the pod memory usage (w/o cache): The first worker container restart in ~40 mins.
![memory-usage-1](https://user-images.githubusercontent.com/1645062/130680998-77e5cd1b-f556-4ec7-96ba-5d91eac54dd6.png)

Then more worker containers restart in next few hours.
![memory-usage-2](https://user-images.githubusercontent.com/1645062/130681378-c50e37ca-a15d-4a79-9240-f3c5d6b19ec8.png)

We saw a lot of cache memory in pod's containers, which is not expected.
![memory-quota](https://user-images.githubusercontent.com/1645062/130681504-40da6a34-580e-4c55-9a0b-1fa6974d0a18.png)

**Expected behavior**
We expect the worker to run stable and within the memory usage limit.

**Urgency**
This is urgent, we are using Alluxio in production to speed up I/O and optimize Spark data loading.

**Additional context**
We suspect the ramdisk usage is somehow added into k8s memory usage and triggered OOM. We tried to set 120 GB k8s pod limit and 100 GB ramdisk size. Now we clearly see the memory usage (w/o cache) hit 20 GB (= 120GB - 100 GB) and then container restarted.
<img width="1410" alt="memory-usage-3" src="https://user-images.githubusercontent.com/1645062/130683162-2e5720fb-9a13-43e7-854b-f5d609b28bb4.png">

```
➜  ~ kubectl describe pod alluxio-worker-8mkpc
Containers:
  alluxio-worker:
    State:          Running
      Started:      Tue, 24 Aug 2021 11:40:31 -0700
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 24 Aug 2021 09:56:35 -0700
      Finished:     Tue, 24 Aug 2021 11:40:27 -0700
    Ready:          True
    Restart Count:  3
    Limits:
      cpu:     4
      memory:  120G


➜  ~ kubectl exec -it alluxio-worker-8mkpc -c alluxio-worker -- bash
alluxio@alluxio-worker-8mkpc:/opt/alluxio-2.6.1$ alluxio getConf alluxio.worker.ramdisk.size
100G


alluxio@alluxio-worker-8mkpc:/opt/alluxio-2.6.1$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
ramdisk                      100G   99G  1.1G  99% /mnt/alluxio-k8s/ramdisk
```

**Comment by yuzhu** [comment]
@ffcai could you collect a heap dump before OOMed. something like `jmap -dump:file=heap.hprof pid` Also what was the workload on the workers when you experienced  increased memory usage?

**Comment by yuzhu** [comment]
it would also help to paste your alluxio configuration and any jvm options here.

**Comment by yuzhu** [comment]
@ffcai any update on this? have you tried to clear the ramdisk cache to see if that is indeed counted in the k8s memory limit? 
or have you received any guidance from k8s community on this?

**Comment by ZhuTopher** [comment]
@yuzhu Just for your reference, here is the prior investigation regarding the Alluxio worker container memory limits wrt ramdisk in Kubernetes: https://github.com/Alluxio/alluxio/issues/13022

**Comment by ffcai** [comment]
Hi @ZhuTopher I just read through https://github.com/Alluxio/alluxio/issues/13022, the issue we ran into is very close to it, and it took us quite a few days to realize the pod memory limit needs to take account of the memory-backed volume, same as your [explanation](https://github.com/Alluxio/alluxio/issues/13022#issuecomment-801290907) and [conclusion](https://github.com/Alluxio/alluxio/issues/13022#issuecomment-802971440).

Now we have increased worker's pod memory limit to 120 GB, which include the 50 GB ramdisk(memory-backed volume), the worker's jvm heap size is under 20 GB, the Alluxio cluster is running stable. We are also trying 500 GB pod memory limit with 400 GB ramdisk size when k8s node is not running heavy jobs, and will continue to monitor the cluster.

I think we need to add this to the doc [Deploy Alluxio on Kubernetes](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html). I believe more and more Alluxio deployment will be cloud native and on k8s. Although it's more a k8s issue because of the current lack of support on memory-backed volume, Alluxio community can make it more clear for users. There's no reason to blame on Alluxio for this, as I said when discussed this issue with @yuzhu earlier last week, but if we can add a note in the installation doc, that would be very helpful.

We actually tried both `emptyDir` and `hostPath`, I'll post some test results with more details later. Overall, it's the same thing about memory limit discussed in https://github.com/Alluxio/alluxio/issues/13022. Thanks everyone for the help!

**Comment by yuzhu** [comment]
@ffcai  Thanks for reporting back your findings. Glad it works now. 

@ZhuTopher do you mind adding some notes in our doc mentioning that pod memory limit needs to include ramdisk allocation as well?  We can close the issue once doc is updated.

**Comment by jiacheliu3** [comment]
> Hi @ZhuTopher I just read through #13022, the issue we ran into is very close to it, and it took us quite a few days to realize the pod memory limit needs to take account of the memory-backed volume, same as your [explanation](https://github.com/Alluxio/alluxio/issues/13022#issuecomment-801290907) and [conclusion](https://github.com/Alluxio/alluxio/issues/13022#issuecomment-802971440).
> 
> Now we have increased worker's pod memory limit to 120 GB, which include the 50 GB ramdisk(memory-backed volume), the worker's jvm heap size is under 20 GB, the Alluxio cluster is running stable. We are also trying 500 GB pod memory limit with 400 GB ramdisk size when k8s node is not running heavy jobs, and will continue to monitor the cluster.
> 
> I think we need to add this to the doc [Deploy Alluxio on Kubernetes](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html). I believe more and more Alluxio deployment will be cloud native and on k8s. Although it's more a k8s issue because of the current lack of support on memory-backed volume, Alluxio community can make it more clear for users. There's no reason to blame on Alluxio for this, as I said when discussed this issue with @yuzhu earlier last week, but if we can add a note in the installation doc, that would be very helpful.
> 
> We actually tried both `emptyDir` and `hostPath`, I'll post some test results with more details later. Overall, it's the same thing about memory limit discussed in #13022. Thanks everyone for the help!

@ffcai Thx for the added information! I'm very curious on the performance difference in `emptyDir` vs `hostPath`. I'd appreciate it if you could share that!

**Comment by apc999** [comment]
docs contributed by @ZhuTopher has been merged. so I will close this ticket.
thanks everyone!
