### ISSUE TITLE
Alluxio Embedded HA can't work when two follower crash

### ISSUE THREAD

**Issue by codings-dan** [Alluxio/alluxio#13987]
**Alluxio Version:**
2.6.1

**Describe the bug**

Our cluster has three master nodes, namely master-0, master-1, and master-2, of which master-2 is the leader. Master-0 and master-1 went down at the same time. After the two nodes restarted, master-1 became the new leader. At this time, we found that no new raft logs were generated in master-2. After we killed master-2 and restarted master-2, we found that the raft log still could not be generated.

**To Reproduce**
1. Kill 2 followers at the same time in a 3-node cluster
2. After the cluster restarts and the new leader is selected, kill the original leader
3. Observe the changes in the raft log

**Expected behavior**
When the two nodes are down and restarted normally, the cluster can still return to normal working status

**Urgency**
Normal

**Comment by apc999** [comment]
Since this is not supported currently by Ratis, I will close this as a bug
@maobaolong do you have further input? Feel free to re-open it if you have further update.
