### ISSUE TITLE
Add TotalBlocks metric as reported by the worker

### ISSUE THREAD

**Issue by yuzhu** [Alluxio/alluxio#14014]
**Is your feature request related to a problem? Please describe.** 
This is different from UniqueBlock which is from master's point of view. 
We can get a sense of how replicated blocks are from these two metrics.

**Comment by apc999** [comment]
@maobaolong  are you going to work on it?

**Comment by maobaolong** [comment]
@apc999 Sure, I push a new PR to solve this issue.
