### ISSUE TITLE
Invalidate client-side metadata cache to be consistent

### ISSUE THREAD

**Issue by bzheng888** [Alluxio/alluxio#14011]
**Is your feature request related to a problem? Please describe.**
When we enable client metadata cache(like fuse), the default cache expired time is 2 hour,  we  can't update the cache when the metadata is actually changed until the old metadata cache expired. It affects the workload sometimes.
Based on the above reasons，It's useful to a new command to clear the client metadata cache 
**Describe the solution you'd like**
A new command maybe to clear metadata cache on our own initial.

**Describe alternatives you've considered**
Maybe we can supply a not just clear operation but also other useful operation to handle the client side cache data.

**Urgency**
No
**Additional context**
NO

**Comment by apc999** [comment]
one way possibly to handle this is to make worker services modular and then make it possible to turn on FUSE service and Proxy service, then we can run generic commands to the Proxy server, e.g. `fs ls -f` to force update cache

**Comment by bzheng888** [comment]
> one way possibly to handle this is to make worker services modular and then make it possible to turn on FUSE service and Proxy service, then we can run generic commands to the Proxy server, e.g. `fs ls -f` to force update cache

Thanks for your reply, Let me think about this problem carefully and give a better way to complete this.

**Comment by LuQQiu** [comment]
Fixed by @bzheng888 via https://github.com/Alluxio/alluxio/commit/b892c642ecbce3dd465eb46f634cc419c2c07430
