### ISSUE TITLE
Allow running stress master bench without mounting a UFS

### ISSUE THREAD

**Issue by dbw9580** [Alluxio/alluxio#14015]
**Is your feature request related to a problem? Please describe.**

Currently the `StressMasterBench` needs a UFS mounted to create test files. In order to create the maximum stress possible on the master, an approach is to allow running the benchmark without a UFS.

**Describe the solution you'd like**
Allow running the `StressMasterBench` without a UFS mounted. 

**Describe alternatives you've considered**
Alternatively, add a in-memory mock UFS that stores the data in memory only, so that the UFS does not become the bottleneck of the stress benchmark.

**Urgency**
Medium

**Additional context**
This issue is from discussion with @maobaolong. 

FYI @yuzhu @LuQQiu.

**Comment by dbw9580** [comment]
The scope of this issue might extend to other benchmarks beyond `StressMasterBench`.

**Comment by HelloHorizon** [comment]
@dbw9580 what is the current status of this issue?

**Comment by dbw9580** [comment]
@HelloHorizon This has been addressed by #14842. By using a local UFS and specifying the write type as `MUST_CACHE`, the benchmark can effectively work without a UFS.

We have not tested the new option extensively, so maybe leave this issue open until we have some feedback from community. cc @maobaolong

**Comment by jiacheliu3** [comment]
Can this be closed?

**Comment by maobaolong** [comment]
Not yet, I found that, some of the operations within StressMasterBench were not respect to the `MUST_CACHE` config.

Something like this 

<img width="810" alt="image" src="https://user-images.githubusercontent.com/17329931/167233483-ed9a9823-55bf-4737-94eb-7d3aeddb07ba.png">

**Comment by maobaolong** [comment]
Yeah, thanks @dbw9580 @jiacheliu3
