### ISSUE TITLE
Thousands of gRPC connection slow down machine learning read

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14020]
**Alluxio Version:**
Alluxio 2.6.1

**Describe the bug**
When using DALI data loader https://developer.nvidia.com/dali to load imagenet data. The dataset is about 1.2 millions file * 105KB on average per file = 130GB total data. DALI loads data in batches, doing some machine learning training, and then close the input streams in batches (related script can be found https://github.com/LuQQiu/DALI/blob/master/docs/examples/use_cases/pytorch/resnet50/main.py)

In normal read workload, a file is open()， read（), and then immediately close(), which the current code works well.
In machine learning world, a file is open(), read（）, wait for machine learning training job to finish, and then close(). When reading a large number of small files, many gRPC stream will be opened concurrently and consumes a lot of CPU resources. By closing the gRPC stream immediately after finishing reading can release gRPC stream earlier and improve overall read performance.

**To Reproduce**
- Set up Alluxio on Kubernetes cluster with worker fuse
- Load imagenet data into Alluxio
- Run the machine learning training job. Here is a mocked sample
```
arena --loglevel info submit pytorch \
  --name=test-job \
  --gpus=0 \
  --workers=4 \
  --cpu 6 \
  --memory 32G \
  --selector alluxio-master=false \
  --image=nvcr.io/nvidia/pytorch:21.05-py3 \
  --data-dir=/alluxio/ \
  --sync-mode=git \
  --sync-source=https://github.com/LuQQiu/DALI.git \
  "python /root/code/DALI/docs/examples/use_cases/pytorch/resnet50/main.py \
  --process 4 \
  --batch-size 256 \
  --print-freq 1000 \
  /alluxio/alluxio-mountpoint/alluxio-fuse/dali"
```
- compare the result between the current impl and close stream immediately after reading
**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by sg-c** [comment]
@LuQQiu , why cannot the user call `close()` once all data is read?
