### ISSUE TITLE
Remote read performance improvement in distributed training of millions of files

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14028]
**Summary**
Use Nvidia Data loading library DALI https://developer.nvidia.com/dali for distributed data loading. Nvidia  Data Loading Library DALI provides built in data loaders and data iterators. DALI supports overlapping training and data pre-processing to reduce latency and training time. It can be used as a benchmarking to test the data loading speed from Alluxio storage in AI workloads.

Workloads
- Launch AWS EKS cluster
```
EKS cluster, 1 master and 6 workers, r5.8xlarge (32 vCPU, 256GB memory)
512 gp2 SSD for worker nodes
```
- Launch Alluxio cluster
```
All the workers are SSD only with Worker embedded Fuse.
Root UFS is a s3 bucket with all imagenet original data, a little modification use the script https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh
1000 folders * 1300 imgs/folder * 105KB on average each file (range from 30k to 200k), total 140GB data
```
- Use Arena https://github.com/kubeflow/arena to launch the data loading script in FOUR OUT OF SIX nodes running AlluxioWorker 
```
Arena is a command-line interface for the data scientists to run and monitor the machine learning training jobs and check their results in an easy way
```

**Data loading script**
Our [benchmarking code ](https://github.com/LuQQiu/DALI/blob/2f79c1eaa34f561051ec5b6aa20c27c68c8cbf4f/docs/examples/use_cases/pytorch/resnet50/main.py)is modified from [Nvidia DALI example script](https://github.com/NVIDIA/DALI/blob/c4e86b55dccba083ae944cf00a478678b7e906cc/docs/examples/use_cases/pytorch/resnet50/main.py) given by the [DALI tutorial ImageNet Training in PyTorch](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html#training). The original script supports reading from the imagenet original dataset, do data loading, data preprocessing, and data iteration with DALI, train the model with pyTorch resnet models. 

Our modifications include
- Remove the training logic from the script, only include the DALI data loader logics.
- Change DALI to use CPU only instead of using GPU or  MIXED devices.
- Support multi-process data loading in each node

Our script can:
- Support running DALI data loader from multiple nodes, multiple data loading threads in each node
- Record the images loaded number and data loading time of each node and calculate the image/s/node.

**Launch arena job**
```
arena --loglevel info submit pytorch \
--name=test-job \
--gpus=0 \
--workers=4 \
--cpu 4 \
--memory 32G \
--selector alluxio-master=false \
--image=nvcr.io/nvidia/pytorch:21.05-py3 \
--data-dir=/alluxio/ \
--sync-mode=git \
--sync-source=https://github.com/LuQQiu/DALI.git \
"python /root/code/DALI/docs/examples/use_cases/pytorch/resnet50/main.py \
--process 4 \
--batch-size 256 \
--print-freq 1000 \
/alluxio/alluxio-mountpoint/alluxio-fuse/dali"

$  arena list test-job                                                    ok
NAME      STATUS     TRAINER     AGE  NODE
test-job  SUCCEEDED  PYTORCHJOB  33m  N/A
$ kubectl get pods
NAME                READY   STATUS      RESTARTS   AGE
test-job-master-0   0/1     Completed   0          34m
test-job-worker-0   0/1     Completed   0          34m
$ kubectl logs test-job-master-0
$ kubectl logs test-job-worker-0

```

**Comment by LuQQiu** [comment]
Experiment 1
Question: why cluster read throughput is that slow, only 2400 img/s

Observation: 
cluster settings
- CPU/memory
- Alluxio configuration -> master/worker/fuse config
ML workloads, ML read pattern
Alluxio Fuse
- Underlying FUSE/libfuse/jnifuse impl
- Alluxio Fuse impl
- Alluxio client code
- Alluxio client metadata ops
- Alluxio client data ops

Hypothesis: 
CPU resources are not enough
Memory resources are not enough
Some of the Alluxio configs is missing
The ML read pattern is special, not like traditional workloads. We didn’t deal with the special pattern well
Performance is bounded by underlying modules: Fuse + libfuse + jnifuse
Performance is bounded by Alluxio Fuse + Alluxio client/server

Which steps are most cost-effective?
Which steps help rule out the biggest possibilities and help narrow down the question?

Try Hypothesis 1 & 2
Try to enlarge the CPU/Memory -> throughput doesn’t change

**Comment by LuQQiu** [comment]
Experiment 2
Question: Narrow down the question: Performance is bounded by 
Underlying Fuse + libfuse + jnifuse or Alluxio Fuse/client/master/worker

Hypothesis: Fuse + libfuse + jnifuse + directly reading from local filesystem can generate much better throughput than 1500 img/s. Alluxio impl has the potential to achieve much better performance.
Experiment:
StackFs = Fuse + libfuse + jnifuse + directly reading from local filesystem 6000 img/s
AlluxioFuse = Fuse + libfuse + jnifuse + AlluxioFuse with 6 replica on local machine 1600 img/s
Conclusion: Alluxio impl has the potential to achieve much better performance

**Comment by LuQQiu** [comment]
Experiment 3
Question: How can Alluxio with 6 replica read performance increase from 1600 img/s to a value that close to 6000 img/s

Observation: compare the two env and understand the diff. Understand the Alluxio read path and see where could be the potential bottleneck. Use flamegraph/visualvm to see potential bottlenecks.

Hypothesis
- Metadata operation: Metadata in StackFs is local while AlluxioFuse needs to fetch metadata from master
- Data operation: RPC between Fuse and Worker. RPC code itself or RPC resources contention

Experiment
- Enable client side metadata cache
- Enlarge client pool size
- Use hacky changes to remove RPC between Fuse and  local Worker

Result: increase from 1500 img/s to 4700 img/s ← which we are satisfied

Actions:
1. add worker storage java opts to client java opts since Fuse need to know the worker storage location
2. Add metadata cache to cover the whole test
```
ALLUXIO_FUSE_JAVA_OPTS: >- 
  -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.user.metadata.cache.expiration.time=2h -Dalluxio.user.metadata.cache.max.size=10000000 
```
3. Enlarge the client pool size
```
-Dalluxio.user.block.worker.client.pool.max=4096
```
4. Implement Fuse on Worker 
https://docs.google.com/document/d/1hdI5LPAPN-NPEYhcxdw47yGyP4GdyzJRf98oawJx0rA/edit?usp=sharing

**Comment by LuQQiu** [comment]
Experiment 4
Question: Why Fuse on worker implementation does help improve the overall cluster read performance? How can we improve cluster read performance?

Hypothesis: Remote read is the performance bottleneck.

Experiment: Add a bunch of metrics to see where the time spend.

Result: Most of the time spend in remote read. Fuse process local read 576 MB/s, Fuse remote read 16.4 MB/s. More than 30X diff.
Conclusion: Remote read is the performance bottleneck.

**Comment by LuQQiu** [comment]
Experiment 5
Question: Why remote read is the performance bottleneck? How to improve remote read performance?

Hypothesis:
gRPC itself is the performance bottleneck
Remote read slowness is expected, since it includes transferring data through network. Network IO is the performance bottleneck

Experiment:
Implement Fuse single node read stressbench test to compare Fuse process local read vs gRPC local read vs gRPC remote read

Result: the gap between the three read way (<2X)  is much smaller than what observed in MS env (>30X)


<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-de8608ec-7fff-05d5-1ea9-20789286b181">

Read type/Thread number | 1 | 2 | 4 | 8
-- | -- | -- | -- | --
Process Local | 61MB/s | 128MB/s | 258MB/s | 247MB/s
Grpc Local | 54.9MB/s | 109MB/s | 213MB/s | 250MB/s
Grpc Remote | 43.8MB/s | 91MB/s | 186MB/s | 251MB/s

</b>

**Comment by LuQQiu** [comment]
Experiment 6
Question 1: Why remote read is the performance bottleneck? How to improve remote read performance?
Question 2: What are the differences between DALI env and Stressbench env that could result in the diff?

The hypothesis from observation:
- CPU resources. DALI env worker only has 1 CPU (configured by kubectl yaml scripts）which stressbench env worker can use up to 16 CPU
- ML read pattern. Stressbench open()-read()-close(), only 4 files are open() at the same time while ML env more than 1500 files are opened at the same time.

Experiment
- Enlarge CPU resources
- Close gRPC stream immediately after reading all the data

Results: Both hypotheses are performance bottlenecks. With the combined effort, we increase performance from 2k img/s to more than 13k img/s.
- Enlarge CPU
CPU resources needed for training
<google-sheets-html-origin><style type="text/css"></style>

Node CPU | Data Loading Process | Data Loading CPU | Arena Memory (GB) | Alluxio Worker CPU | Alluxio Worker Memory (GB) | Throughput
-- | -- | -- | -- | -- | -- | --
32 | 4 | 4 | 32 | 3 | 16 | 4723 img/s
32 | 8 | 10 | 32 | 4 | 16 | 9425 img/s
32 | 12 | 12 | 32 | 6 | 16 | 12449 img/s
32 | 16 | 20 | 32 | 10 | 32 | 13725 img/s

- Close grpc stream immediately after reading all the data belongs to a file https://github.com/Alluxio/alluxio/issues/14020
- Small improvement: Avoid unneeded async cache RPCs by setting `alluxio.user.file.readtype.default=NO_CACHE`. Async cache will be issued when reading data from remote worker, but because this is a single tier storage and enough space, async cache manager will not do anything

**Comment by Binyang2014** [comment]
Can we provide the detail Alluxio configurations for this experiments? We do want to reproduce the results in our test bed.

**Comment by LuQQiu** [comment]
@Binyang2014 That's the alluxio configuration i used
[mlk8s.zip](https://github.com/Alluxio/alluxio/files/7156210/mlk8s.zip)

Recommend using the docker image  with changes in https://github.com/Alluxio/alluxio/pull/14017
