### ISSUE TITLE
Elect return success while master report timeout exception

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#14029]
**Alluxio Version:**
master branch from d2e9472438057146216374b46ece361c9acd4723

**Describe the bug**

Running elect return success while master report timeout exception

**To Reproduce**

- Start a ha mode 3 master cluster.
- Close one master.
- Elect the closed master to be leader

```
bin/alluxio fsadmin journal quorum elect -address localhost:19200
Transferred leadership to server: localhost:19200
Quorum priorities were reset to 1
```

But I found the error log in master.log, In fact the master encountered some unexpected error.

```
2021-09-07 11:46:51,426 ERROR RaftJournalSystem - caught an error: localhost_19201@group-ABB3109A44C1: Failed to transfer leadership to localhost_19200 (timed out 30000ms): current leader is localhost_19201
```

**Expected behavior**

Return exception to client, report fail to user.

**Urgency**
Normal

**Additional context**
No

**Comment by maobaolong** [comment]
Another related exception is 

```
2021-09-07 14:57:18,645 ERROR RaftJournalSystem - caught an error: localhost_19201@group-ABB3109A44C1 refused to transfer leadership to peer localhost_19202 as it does not has highest priority 242: [localhost_19202|rpc:localhost:19202|admin:|client:|dataStream:|priority:1, localhost_19201|rpc:localhost:19201|admin:|client:|dataStream:|priority:1, localhost_19200|rpc:localhost:19200|admin:|client:|dataStream:|priority:1], old=null

```

**Comment by maobaolong** [comment]
@codings-dan Would you like to take this ticket?

**Comment by codings-dan** [comment]
> @codings-dan Would you like to take this ticket?

will do

**Comment by apc999** [comment]
thanks @maobaolong  do you mean a new cli or a new option in existing cli?

**Comment by maobaolong** [comment]
@apc999 No, I mean we can add a new client-master api to query the transferleadership schedule and result, if the transfer failed, the original master should reply the error reason to the client, so that the client will fail at once rather than waitfor forever like the current behavior.

**Comment by apc999** [comment]
let's have a design discussion on this

**Comment by ggezer** [comment]
Isn't this fixed with https://github.com/Alluxio/alluxio/pull/14027 ?

**Comment by maobaolong** [comment]
@ggezer No, it's two different issue.

**Comment by ggezer** [comment]
It was returning a success because `localhost:19200` and `localhost:19201` had the same hostname part. 
With  #14027 this should no longer be the case, and the shell command should error out.

**Comment by maobaolong** [comment]
ok, you are right, thank you for the explaination.
