### ISSUE TITLE
Run stressMasterBench throw exception when get file status

### ISSUE THREAD

**Issue by codings-dan** [Alluxio/alluxio#14039]
**Alluxio Version:**
alluxio 2.6.1

**Describe the bug**
Use stressMasterBench for stress testing , an exception is thrown

```
java.lang.RuntimeException: Failed to successfully complete the job: Task execution failed: Job worker was lost before the task could complete
	at alluxio.client.job.JobGrpcClientUtils.run(JobGrpcClientUtils.java:94)
	at alluxio.stress.cli.Benchmark.run(Benchmark.java:161)
	at alluxio.stress.cli.Benchmark.mainInternal(Benchmark.java:90)
	at alluxio.stress.cli.StressMasterBench.main(StressMasterBench.java:72)

```
**To Reproduce**

In an alluxio cluster, which contains at least 3 masters and 100 workers, execute the command:

`bin/alluxio runClass alluxio.stress.cli.StressMasterBench --base alluxio://alluxio-master-0:19998/testbase2 --conf alluxio.user.file.writetype.default=MUST_CACHE --conf alluxio.user.block.master.client.pool.size.max=512 --conf alluxio.user.file.master.client.pool.size.max=512 --operation GetFileStatus --duration 500s --threads 256 --target-throughput 200000 --cluster --cluster-limit 100`

**Expected behavior**
Work normally, no longer throw exceptions

**Urgency**
No

**Comment by yuzhu** [comment]
@codings-dan do you have any job worker logs snippet that might help us diagnose the issue?

**Comment by apc999** [comment]
@codings-dan  does this command fail like this deterministically?

**Comment by codings-dan** [comment]
@yuzhu hi,  this scene has not been reproduced recently, and I will post the log next time it reappears.

**Comment by codings-dan** [comment]
@apc999 No, it appears with a certain degree of randomness.

**Comment by apc999** [comment]
that's hard to diagnosis based on the information provided here. I could only tell some job worker is down.
@yuzhu at least we shall add logging to tell which job worker is lost?
so @codings-dan can go to that job worker can look for the job worker logs?

**Comment by yuzhu** [comment]
#14024 should help to provide more detailed logging.

**Comment by apc999** [comment]
with limited information (especially the job worker log which is down), it is too hard for us to debug this issue.
I will close this issue for now, but @codings-dan once you reproduce the issue and get the log, please reopen this issue and upload it here. Will it work? @codings-dan

**Comment by codings-dan** [comment]
@apc999 will do
