### ISSUE TITLE
Permission denied on kubernetes

### ISSUE THREAD

**Issue by clcc2019** [Alluxio/alluxio#14040]
**Alluxio Version:**
2.6.1
**Describe the bug**
![image](https://user-images.githubusercontent.com/46099295/132470407-b2d44314-9c97-4c9e-aa13-4ebc67dd6bb0.png)
Permission denied

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by apc999** [comment]
@clcc2019 the current information is insufficient. Can you share us if this is master or worker log?

**Comment by apc999** [comment]
@clcc2019  I had a closer look. I don't think it is related to K8s.

HDFS was reporting insufficient permission for a user named `root` to write to HDFS root dir ("/") which is owned by HDFS user named `hdfs`.  You will need to either start Alluxio master/worker process using this user `hdfs` which has full permission in HDFS root dir, or perhaps let Alluxio write to some other directory where `root` has write permission.

Hope this helps. Closing this issue and feel free to re-open it if you have different ideas or have new update here.
