### ISSUE TITLE
Directory inode becomes file inode when using Alluxio with Huawei OBS 

### ISSUE THREAD

**Issue by adios666** [Alluxio/alluxio#14051]
**Alluxio Version:**
Alluxio-2.4.1

**Describe the bug**
I'm using Alluxio+Huawei OBS. Sometimes a directory inode becomes a file inode

**To Reproduce**
1. Create a file in /test1/test2/test3/file.out
2. Run "alluxio fs rm -R --alluxioOnly /test1"
3. Run "alluxio fs ls /test1"
4. Run "alluxio fs stat /test1/test2". The FileInfo is "xxx, completed=true, **folder=false,** pinned=false, pinnedlocation=[], xxx"

**Expected behavior**
/test1/test2 should be a directory, not a file.

**Urgency**
High. Hive job can't run because of this bug.

**Comment by yabola** [comment]
This may help you https://github.com/Alluxio/alluxio/pull/14023

**Comment by adios666** [comment]
> This may help you #14023

No. I tried your commits. It still have the same problem. I think there should be a boolean flag in class `ObjectMetadata` and we can get if an inode is folder or not.
