### ISSUE TITLE
Kubernetes script cannot launch

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14079]
**Alluxio Version:**
Alluxio master

**Describe the bug**
Kubernetes cluster cannot come up with changes https://github.com/Alluxio/alluxio/commit/22ecb2c2aa7764191588720945571934d410c568

Using `kubectl logs` `kubectl describe`, no error comes out.
Docker command works well to start Alluxio services.

In kubernetes world, `command: ["tini", "--", "/entrypoint.sh"]` doesn't work
but `command: ["/entrypoint.sh"]` works.

From https://stackoverflow.com/questions/55527105/how-to-fix-exec-user-process-caused-no-such-file-or-directory/56819048
and https://github.com/krallin/tini

Tini has very few dependencies (it only depends on libc), but if your container fails to start, you might want to consider using the statically-built version instead:

```
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static /tini
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by Xenorith** [comment]
re-opening to validate unrelated functionality
