### ISSUE TITLE
Missing "Move a Partitioned Table"  in Chinese Docs

### ISSUE THREAD

**Issue by Stevenchooo** [Alluxio/alluxio#14085]
**Page**
https://docs.alluxio.io/os/user/stable/cn/compute/Hive.html

**Summary**
The method of moving the partition table path to Alluxio is missing in the Chinese document

**Comment by Stevenchooo** [comment]
please assign to me ,I will fix the docs
https://github.com/Alluxio/alluxio/blob/master/docs/cn/compute/Hive.md

**Comment by beinan** [comment]
Hey Steven, many thanks for opening this issue!  Assigned to you and looking forward to seeing your new doc!  Thanks!
