### ISSUE TITLE
the Master.TotalBlocks appears to be -2998885

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#14082]
**Alluxio Version:**
2.6.1

**Describe the bug**
the Master.TotalBlocks appears to be -2998885

**Comment by yuzhu** [comment]
I think this was fixed in https://github.com/Alluxio/alluxio/pull/13911/files

**Comment by apc999** [comment]
yeah this bug is fixed in v2.6.2 and after by https://github.com/Alluxio/alluxio/pull/13911/
