### ISSUE TITLE
Alluxio Kerberos Security Setup Doc - Bad Link

### ISSUE THREAD

**Issue by gregpalmr** [Alluxio/alluxio#14173]
**Page**
https://docs.alluxio.io/ee/user/stable/en/operation/Kerberos-Security-Setup.html

**Summary**
The link to the Red Hat docs page is not valid and results in an HTTP 404 error:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Managing_Smart_Cards/installing-kerberos.html

**Comment by jiacheliu3** [comment]
@gregpalmr I can open this link, although it seems to redirect. Is this still an issue?

**Comment by Xenorith** [comment]
this also wasn't working earlier for me but now it seems to be valid again, through a redirect. probably fine to leave as is and close
