### ISSUE TITLE
S3 API listObjects delimiter process error

### ISSUE THREAD

**Issue by jffree** [Alluxio/alluxio#14189]
**Describe the bug**
According to [ListObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html), a response can contain `CommonPrefixes` only if you specify a `delimiter`.
In alluxio current version, the `delimiter` is not processed, always return response with `CommonPrefixes`.

**To Reproduce**

access s3 listObjects/listBuckets without `delimiter`

**Expected behavior**

When access s3 `ListObjects` rest interface without `delimiter`, the response should not contains `CommonPrefixes`.

**Urgency**
Normal

**Comment by jffree** [comment]
@HelloHorizon FYI

**Comment by HelloHorizon** [comment]
Thanks @jffree ! FYI @madanadit

**Comment by yuzhu** [comment]
@HelloHorizon @jffree is one of you working on a PR to resolve this issue?
