### ISSUE TITLE
The semantics of loadMetadata is ambiguous

### ISSUE THREAD

**Issue by yuyang733** [Alluxio/alluxio#14183]
**Alluxio Version:**
All versions

**Describe the bug**
The semantics of `LoadMetadataCommand` is ambiguous. After LoadMetadata is executed on a directory, the metadata of the existing sub-file under a directory will not be updated, which leads to data inconsistency in UFS overwriting scenarios.

**To Reproduce**
./bin/alluxio fs loadMetadata /<dir>/

**Expected behavior**

The metadata of the existing subfile under the directory `/<dir>` is updated. 

**Urgency**

**Additional context**

The related code: 
![1071632930820_ pic_hd](https://user-images.githubusercontent.com/4209464/135322848-5cb5195b-a553-4164-9f15-5c9f93783a4b.jpg)

**Comment by yuzhu** [comment]
closed via #14184
