### ISSUE TITLE
Parquet file pread errors when accessing Alluxio fuse mounted TCPDS dataset.

### ISSUE THREAD

**Issue by sumokiama** [Alluxio/alluxio#14215]
Our product is Windjammer SNE, a Spark native acceleration engine written in C/C++. It takes as input a Spark physical plan and executes all of the nodes in that plan. We would like to make use of the Alluxio cache and speed Spark SQL execution even more than what our engine can do on its own. We are attempting to benchmark the Alluxio/SNE using TPCDS.

We normally use cloud storage (S3 or GS) to host the TPCDS (or any other) datasets. In order to make use of Alluxio, we have decided to make use of Alluxio FUSE to mount the datasets on the cluster nodes. So we mount the S3/GS dataset bucket onto an Alluxio FS directory, then mount the Alluxio FS directory as a node-local directory. We can use POSIX commands to see all of the parquet files in the datasets.

Our issue is that when we attempt to install the dataset metadata (using the spark-sql-perf tools), we encounter missing parquet file errors. The locally mounted dataset directory is presented to the metadata generator as:
   file:///opt/wjm-datasets

We see errors on parquet files such as:
`/opt/wjm-datasets/tpcds100g/catalog_sales/part-00000-0f2098ab-25f9-44a9-b555-cda6374119eb.snappy.parquet does not exist`

We are using the stand-alone Alluxio FUSE mode in this test. We intend on switching to the worker-based FUSE method and rerun this test.

I am attaching the Alluxio configuration file, our TPCDS metastore script, the output log of the metastore script, the master log, the worker log and the fuse log.

Darryl

[alluxio_fuse_issue.zip](https://github.com/Alluxio/alluxio/files/7314588/alluxio_fuse_issue.zip)

**Comment by yuzhu** [comment]
@ssz1997 do you mind taking a look at the logs and see if you see any configuration error with their Fuse setup?  thanks.

**Comment by yuzhu** [comment]
```2021-10-08 20:33:32,892 WARN  BlockReadHandler - Exception occurred while reading data for read request BlockReadRequest{chunkSize=1048576, end=67108864, id=58401488896, openUfsBlockOptions=ufs_path: "s3://wjm-datasets/tpcds1t/store_sales/part-00013-134ff0d6-b55d-42a9-b308-55b6e697659f.snappy.parquet"
offset_in_file: 0
block_size: 67108864
maxUfsReadConcurrency: 2147483647
mountId: 1236490204785346587
no_cache: false
, promote=false, sessionId=4252404064642447208, start=0, positionShort=false}. session 4252404064642447208: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool```

**Comment by beinan** [comment]
@yuzhu just made a simple fix which might make some improvement.  I think at least we should close the stream when we're create a new one. https://github.com/Alluxio/alluxio/pull/14291

**Comment by ssz1997** [comment]
@sumokiama As the problem is mitigated, I'm closing this issue. Feel free to raise new ones if you see any other problems. Thanks for your contribution!
