### ISSUE TITLE
AlluxioMaster leader switch unexpectedly after manual leader switch with "quorum elect" command

### ISSUE THREAD

**Issue by kevincai** [Alluxio/alluxio#14228]
**Alluxio Version:**
v2.6.2

**Describe the bug**
With embedded journal system, once using 'fsadmin journal quorum elect -address <xxxx>', nodes priorities were changed and not reset, hence,  if the given node temporarily offline and back online sometime later, the leader was switched again immediately after the given node back online.

**To Reproduce**
1. manual switch leader to NodeA `./bin/alluxio fsadmin journal quorum elect -address <node_a>:19200`
2. check the priority info of nodes by `./bin/alluxio fsadmin journal quorum info -domain MASTER`
3. Take down AlluxioMaster process on NodeA, wait for leader role fail overs to one of remain two nodes.
4. Once the remain two nodes reaches final state as one LEADER, one FOLLOWER, take NodeA online again
5. A leader switch happens again once NodeA is online.

**Expected behavior**
in step5, the leader switch is an unexpected operation.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

Should be a side effect of `fsadmin journal quorum elect -address <xxxx>` who sets priorities to master nodes, but doesn't clean the priority after operation done.

Suggest fix:
* restore or reset the priority info by calling `resetPriorities` in `QuorumElectCommand` or calling `resetPriorities` in `RaftJournalSystem::transferLeadership` after leadership is transferred.

**Comment by yuzhu** [comment]
@jenoudet PTAL, thanks.

**Comment by codings-dan** [comment]
@jenoudet @kevincai The change of node priority will indeed affect the result of the next election. When the `quroum elect` command is designed at the beginning, the resetPriority command will be called after the switch is completed.
But I think the `resetPriority` command also needs to monitor whether the priority is reset successfully. If this process is all implemented in resetPriorities in `QuorumElectCommand` or `RaftJournalSystem::transferLeadership`, the switching time may be too long. A compromise solution is to manually reset the priority after the switch is completed. This has been implemented in #14031 , for reference, thx.

**Comment by kevincai** [comment]
Separate `resetPriority` command is only a band-aid solution to give a way to manual fix the problem, but not the fix to the side effect of `quorum elect` command. With this design, daily operators need to remember that whenever they use `quorum elect`, it must be followed by a  `quorum reset`, otherwise expected behavior will happen sometime in future.

I prefer call the `resetPriority` inside the `quorum elect` command after leadership switch successful, even though this is not a sound solution, because the priorities are changed inside master's transferleaderShip, master shall promise no side effect of the RPC call.

As for the `switching time`, the actual impact time is from old leader down to new leader active, `resetPriority` in `QuorumElectCommand` only extends the cli time cost, not the downtime of cluster unavailable due to leader swithing.
