### ISSUE TITLE
Update version to 2.6.3-SNAPSHOT for branch-2.6

### ISSUE THREAD

**Issue by ferhui** [Alluxio/alluxio#14239]
**Alluxio Version:**
2.6.2

**Describe the bug**
Since 2.6.2 has been released, need to update version to 2.6.3-SNAPSHOT for branch-2.6

**To Reproduce**

**Expected behavior**

**Urgency**
Trivial

**Additional context**
No

**Comment by ssz1997** [comment]
Branch-2.6 doesn't updates its numbers with OS releases per our release protocol. I'm closing this issue for now. If you see the necessity, feel free to reopen or raise new issue to discuss this. Thank you for your contribution!
