### ISSUE TITLE
k8s fails to deploy alluxio, and the deployment work reports the following error

### ISSUE THREAD

**Issue by lgy1027** [Alluxio/alluxio#14234]
k8s fails to deploy alluxio, and the deployment work reports the following error；
k8s: 1.20.4
alluxio:2.6.2
![image](https://user-images.githubusercontent.com/38779388/136875522-0be23714-36fb-4636-8bee-373b5b9ea664.png)
![image](https://user-images.githubusercontent.com/38779388/136875548-634f02ec-5dd0-43f6-bf9d-00fa7c320db9.png)

**Comment by ssz1997** [comment]
I'm closing this issue since 2.6.2 is a fairly old version. Feel free to reopen or raise new issues if you still see the problem. Thanks you for your contribution!
