### ISSUE TITLE
alluxio on ceph,delete files,but the files still exists on ceph

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#14286]
**Alluxio Version:**
alluxio 2.6.1

**Describe the bug**
we delete files with following cmd:
alluxio rm -R /path
however we find after serval minutes,the files still exist on alluxio,and the file  authority is from ceph,not alluxio

Solutions:
after checking,we found:
we delete file,the logic is as follows:
the first to do is delete files in underfs,and then cancal persist job,so there will be a problem,the files delete operation in underfilesystem has finished,and some persist job just finished before the persist job is to be cancelled,there will be problems

in the DefaultFileSystemMaster and this method
public void deleteInternal(RpcContext rpcContext, LockedInodePath inodePath,
      DeleteContext deleteContext) throws FileDoesNotExistException, IOException,
      DirectoryNotEmptyException, InvalidPathException {

String failureReason = null;
        if (unsafeInodes.contains(inodeToDelete.getId())) {
          failureReason = ExceptionMessage.DELETE_FAILED_DIR_NONEMPTY.getMessage();
        } else if (inodeToDelete.isPersisted()) {
          // If this is a mount point, we have deleted all the children and can unmount it
          // TODO(calvin): Add tests (ALLUXIO-1831)
          if (mMountTable.isMountPoint(alluxioUriToDelete)) {
            mMountTable.delete(rpcContext, alluxioUriToDelete, true);
          } else {
            if (!deleteContext.getOptions().getAlluxioOnly()) {
              try {
                checkUfsMode(alluxioUriToDelete, OperationType.WRITE);
                // Attempt to delete node if all children were deleted successfully
                //delete
                ufsDeleter.delete(alluxioUriToDelete, inodeToDelete);
              } catch (AccessControlException | IOException e) {
                // In case ufs is not writable, we will still attempt to delete other entries
                // if any as they may be from a different mount point
                LOG.warn("Failed to delete {}: {}", alluxioUriToDelete, e.toString());
                failureReason = e.getMessage();
              }
            }
          }
        }
        todo  by zhoupeijie-->eg:in this moment ,alluxio think files in underfile system has been deleted,however some files still success persist to underfs before the persist job is cancelled. Can mPersistRequests.remove can be moved more earlier?
        if (failureReason == null) {
          if (inodeToDelete.isFile()) {
            long fileId = inodeToDelete.getId();
            // Remove the file from the set of files to persist.
            mPersistRequests.remove(fileId);
            // Cancel any ongoing jobs.
            PersistJob job = mPersistJobs.get(fileId);
            if (job != null) {
              job.setCancelState(PersistJob.CancelState.TO_BE_CANCELED);
            }
          }
          revisedInodesToDelete.add(new Pair<>(alluxioUriToDelete, inodePairToDelete.getSecond()));
        } else {

**Comment by yuzhu** [comment]
Sounds like we issued a persist and then delete the file. but the persist request gets handled after delete happens, so there is a race? we need to remove the persist request from the queue when we delete the file.
