### ISSUE TITLE
alluxio master jvm crash

### ISSUE THREAD

**Issue by dingshun3016** [Alluxio/alluxio#14300]
Alluxio Version:
2.6.1

Describe the bug
the master jvm frequently crash and hs_err_pid log following content:

Stack: [0x00007fef593d4000,0x00007fef594d5000],  sp=0x00007fef594d3128,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x15f349]  __memcmp_sse4_1+0xbb9
C  [librocksdbjni3984758182997356123.so+0x36180d]  rocksdb::DBIter::FindNextUserEntryInternal(bool, rocksdb::Slice const*)+0xfd
C  [librocksdbjni3984758182997356123.so+0x3627f6]  rocksdb::DBIter::FindNextUserEntry(bool, rocksdb::Slice const*)+0x86
C  [librocksdbjni3984758182997356123.so+0x36900f]  rocksdb::DBIter::Next()+0x4af
J 7511  org.rocksdb.RocksIterator.next0(J)V (0 bytes) @ 0x00007ff38e48e4f0 [0x00007ff38e48e440+0xb0]
J 15263 C2 alluxio.master.block.DefaultBlockMaster.generateBlockInfo(J)Ljava/util/Optional; (377 bytes) @ 0x00007ff38f65a1d4 [0x00007ff38f659760+0xa74]
J 10656 C2 alluxio.master.block.DefaultBlockMaster.getBlockInfoList(Ljava/util/List;)Ljava/util/List; (64 bytes) @ 0x00007ff38ec7102c [0x00007ff38ec70de0+0x24c]
J 14213 C2 alluxio.master.file.DefaultFileSystemMaster.getInAlluxioPercentage(Lalluxio/master/file/meta/Inode;)I (109 bytes) @ 0x00007ff38f54011c [0x00007ff38f53fee0+0x23c]
J 15403 C2 alluxio.master.file.DefaultFileSystemMaster.getFileInfoInternal(Lalluxio/master/file/meta/LockedInodePath;Lcom/codahale/metrics/Counter;)Lalluxio/wire/FileInfo; (399 bytes) @ 0x00007ff38f3fe99c [0x00007ff38f3fe800+0x19c]
J 17264 C2 alluxio.master.file.DefaultFileSystemMaster.getFileInfo(Lalluxio/AlluxioURI;Lalluxio/master/file/contexts/GetStatusContext;)Lalluxio/wire/FileInfo; (780 bytes) @ 0x00007ff38f8ec40c [0x00007ff38f8eb840+0xbcc]
J 11589 C2 alluxio.master.file.FileSystemMasterClientServiceHandler$$Lambda$233.call()Ljava/lang/Object; (20 bytes) @ 0x00007ff38ebf7e6c [0x00007ff38ebf7180+0xcec]
J 12915 C2 alluxio.RpcUtils.callAndReturn(Lorg/slf4j/Logger;Lalluxio/RpcUtils$RpcCallableThrowsIOException;Ljava/lang/String;ZLjava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object; (437 bytes) @ 0x00007ff38f1ac934 [0x00007ff38f1ac220+0x714]
J 11472 C2 alluxio.RpcUtils.call(Lorg/slf4j/Logger;Lalluxio/RpcUtils$RpcCallableThrowsIOException;Ljava/lang/String;ZLjava/lang/String;Lio/grpc/stub/StreamObserver;[Ljava/lang/Object;)V (45 bytes) @ 0x00007ff38f00709c [0x00007ff38f007080+0x1c]
J 11570 C2 alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(Ljava/lang/Object;Lio/grpc/stub/StreamObserver;)V (504 bytes) @ 0x00007ff38e792c04 [0x00007ff38e791c20+0xfe4]
J 14127 C2 io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose()V (82 bytes) @ 0x00007ff38f477fbc [0x00007ff38f477f40+0x7c]
J 14194 C2 alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose()V (23 bytes) @ 0x00007ff38f5148dc [0x00007ff38f514180+0x75c]
J 14074 C2 io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext()V (73 bytes) @ 0x00007ff38f3fc558 [0x00007ff38f3fc4e0+0x78]
J 9288 C2 io.grpc.internal.ContextRunnable.run()V (35 bytes) @ 0x00007ff38e9282cc [0x00007ff38e9280c0+0x20c]
J 16102 C2 io.grpc.internal.SerializingExecutor.run()V (99 bytes) @ 0x00007ff38edad08c [0x00007ff38edacf80+0x10c]
J 12888 C2 alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec()Z (11 bytes) @ 0x00007ff38eb56fa8 [0x00007ff38eb56f60+0x48]
J 9716% C2 alluxio.concurrent.jsr.ForkJoinPool.runWorker(Lalluxio/concurrent/jsr/ForkJoinPool$WorkQueue;)V (643 bytes) @ 0x00007ff38e616b98 [0x00007ff38e6167a0+0x3f8]
j  alluxio.concurrent.jsr.ForkJoinWorkerThread.run()V+24
v  ~StubRoutines::call_stub
V  [libjvm.so+0x68825b]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xddb
V  [libjvm.so+0x685b23]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x263
V  [libjvm.so+0x6860e7]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x6f225c]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xa7bb6b]  JavaThread::thread_main_inner()+0xdb
V  [libjvm.so+0xa7be71]  JavaThread::run()+0x2d1
V  [libjvm.so+0x90d922]  java_start(Thread*)+0x102
C  [libpthread.so.0+0x7dc5]  start_thread+0xc5

**Comment by yuzhu** [comment]
@dingshun3016 is it possible for you upload the core dump file when this happens? also what was the workload on alluxio when this happened? steps to reproduce?

**Comment by uniqueZt** [comment]
Do we have any progress here ？upgrade RocksDB to 6.25.3 can solve this？

**Comment by uniqueZt** [comment]
now we solve it by changing RocksBlockStore to HeapBlockStore，but it lead heap increase fast，can we solve it now？

**Comment by yuzhu** [comment]
@uniqueZt do you have a consistent way of reproducing this? have you tried with the new ROcksDB version? 
We have worked with RocksDB community and this PR was to follow their recommendation.

**Comment by amosannn** [comment]
We also encountered the same problem. During the peak hours of daily queries, crashes occurred frequently, and there might be seven to eight times in the morning...
Our cluster version is v2.6.0. Can upgrading to v2.7.0 or upgrading rocksdb improve this phenomenon? @yuzhu

**Comment by yuzhu** [comment]
We are actively investigating this issue right now.

**Comment by uniqueZt** [comment]
we upgrade the rocksdb version to  6.25.3，but cannot solve this。we run about 4 days online，it happen again. Do we have any progress here ？

C  [librocksdbjni9263870174473033234.so+0x587ff2]  rocksdb::BlockBasedTableIterator::CheckDataBlockWithinUpperBound()+0x92
C  [librocksdbjni9263870174473033234.so+0x588277]  rocksdb::BlockBasedTableIterator::InitDataBlock()+0x267
C  [librocksdbjni9263870174473033234.so+0x588d28]  rocksdb::BlockBasedTableIterator::FindBlockForward()+0x348
C  [librocksdbjni9263870174473033234.so+0x589155]  rocksdb::BlockBasedTableIterator::Next()+0xf5
C  [librocksdbjni9263870174473033234.so+0x5891d6]  rocksdb::BlockBasedTableIterator::NextAndGetResult(rocksdb::IterateResult*)+0x16
C  [librocksdbjni9263870174473033234.so+0x474371]
C  [librocksdbjni9263870174473033234.so+0x5e1a38]  rocksdb::MergingIterator::Next()+0x38
C  [librocksdbjni9263870174473033234.so+0x5ddb13]  rocksdb::MergingIterator::NextAndGetResult(rocksdb::IterateResult*)+0x13
C  [librocksdbjni9263870174473033234.so+0x3cbb74]  rocksdb::DBIter::Next()+0x284

**Comment by uniqueZt** [comment]
can we support block store by leveldb？this may solve this problem . now  heap store can not support large metadata , i do not know how to make alluxio  run for a long time online.

**Comment by apc999** [comment]
this issue shall be fixed by https://github.com/Alluxio/alluxio/pull/14856/
