### ISSUE TITLE
Scan the code base for k8s incompatible usage of host:port

### ISSUE THREAD

**Issue by yuzhu** [Alluxio/alluxio#14321]
**Summary**
We previously use host and port pair  or InetSocketAddress to indicate location of the worker. We can not do that in k8s world, we need to use WorkerNetAddress abstraction, which has physical host, containerhost and port 

**Urgency** 
Urgent as it breaks some k8s usecases..

**Comment by ssz1997** [comment]
@yuzhu Seems like we are not having issue with this any more. I'm closing this on Apr 11 if no other concerns raised.
