### ISSUE TITLE
Failed to complete cache request for block with wrong worker hostname on Kubernetes with "hostNetwork: false".

### ISSUE THREAD

**Issue by jingcheng88** [Alluxio/alluxio#14337]
**Alluxio Version:**
2.6.2

**Describe the bug**
I deployed alluxio on kubernetes use helm chart.  

When i used `alluxio fs load` if set hostNetwork to false, the following error messages were displayed.
```
Failed to complete cache request for block 50432311296 of file /alluxio/test1/alluxio-test.tar : io.grpc.StatusRuntimeException: UNKNOWN: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=xxxxx.kubelet.kube-system.svc.cluster.local, SocketAddress=xxxxx.kubelet.kube-system.svc.cluster.local/xxxxxx:29999}/alluxio/test1/alluxio-test.tar  loaded
```

**Comment by ssz1997** [comment]
@jingcheng88 I'll close this issue for now. Feel free to reopen or raise new issues you still have the problem. Thanks for your contribution!
