### ISSUE TITLE
Worker Active Clients metric can exceed 0 at rest

### ISSUE THREAD

**Issue by ZhuTopher** [Alluxio/alluxio#14412]
**Alluxio Version:**
What version of Alluxio are you using?

2.6.2

**Describe the bug**

When performing back-to-back `bin/alluxio runTests`, it is possible to see the `Worker.ActiveClients` metric exceed
`0` while at rest (i.e: there are no active jobs). This implies that the metric counter is being incremented more than it is decremented, or that there are hanging jobs.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

1. Install an Alluxio cluster locally following the [documentation](https://docs.alluxio.io/ee/user/stable/en/deploy/Running-Alluxio-Locally.html).
2. Perform a couple `bin/alluxio runTests`.
3. Observe the `Worker.ActiveClients` metric at a Alluxio worker metrics sink.

**Expected behavior**
The metric `Worker.ActiveClients` should be `0` when there are no jobs.

**Additional context**
This metric was added as part of https://github.com/Alluxio/alluxio/pull/13856

**Comment by ZhuTopher** [comment]
TODO(self): Reproduce this issue while also capturing job count.

**Comment by dbw9580** [comment]
I'm seeing negative active client counts.

This might be the cause: https://github.com/Alluxio/alluxio/blob/25e1882baad606a813a84a15646746a06590df49/core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java#L124-L132

Both `unlockBlock` and `cleanupSession` decrease this counter, and if `unlockBlock` does not throw an exception, the counter is decremented twice for a single client.

**Comment by jiacheliu3** [comment]
@ZhuTopher Are you going to fix this?

**Comment by ZhuTopher** [comment]
@jiacheliu3 I'm not actively working on this nor have it in my pipeline atm.

@dbw9580 That seems like something worth investigating as well; in this issue I personally didn't observe the metric below 0 though.

**Comment by xichen01** [comment]
@jiacheliu3 I also encountered this problem and submitted a PR  https://github.com/Alluxio/alluxio/pull/14088 to solve this problem

**Comment by ZhuTopher** [comment]
Closing since #14088 was merged

**Comment by jiacheliu3** [comment]
fyi @dbw9580
