### ISSUE TITLE
Suspected Worker DataMessageMarshaller.mBufferMap memory leak

### ISSUE THREAD

**Issue by jayzhenghan** [Alluxio/alluxio#14466]
Worker reports errors in read-only scenarios, and memory grows rapidly at the same time，What caused the error in the picture below：

![image](https://user-images.githubusercontent.com/68948288/140754782-14197716-b064-41ec-8707-4626901fea57.png)

 
worker jvm dump：
![image](https://user-images.githubusercontent.com/68948288/140755841-d7c1ebfd-5dc2-4ca9-b258-4f799fe85378.png)
It can be seen from the figure that DataMessageMarshaller.mBufferMap takes up a lot of memory

**Comment by apc999** [comment]
@ggezer  this memory leak looks to me a high priority bug to work on. Let me know if you have any resource to take it or we can talk offline. Thanks @jayzhenghan  for reporting this

**Comment by yuzhu** [comment]
fixed via #14489
