### ISSUE TITLE
Alluxio's async through mode cause inconsistencies in ufs

### ISSUE THREAD

**Issue by adol001** [Alluxio/alluxio#14476]
**Alluxio Version:**
2.6.1

**Describe the bug**
In async through mode, create file b then delete file b, from the perspective of ufs, it may see delete b then create b. 

**To Reproduce**
add code below in PersistDefinition, before "        bytesWritten = IOUtils.copyLarge(in, out, new byte[8 * Constants.MB]);" 

`        Runtime runtime = Runtime.getRuntime();
        Process proc = runtime.exec("/home/adol/works2/alluxio/bin/alluxio fs rm /ufsMountPoint/myFile11");
        proc.waitFor();
        LOG.info("eeeeeeeeeeeeeeeeeeeeeeeeeeeeee|" + proc.exitValue());`

then compile code, start alluxio, 
create file /ufsMountPoint/myFile11, you will see /ufsMountPoint/myFile11 is deleted, but synchronized to ufs

**Expected behavior**
persist in strict order

**Comment by yuzhu** [comment]
do you see eeeeee in your log? our code should have cancelled the persist job when it sees the delete call. so if you do see `eeeeee` then it might be something wrong with our cancellation logic. @adol001

**Comment by adol001** [comment]
> do you see eeeeee in your log? our code should have cancelled the persist job when it sees the delete call. so if you do see `eeeeee` then it might be something wrong with our cancellation logic. @adol001

Yes, I see, and exitValue is 0.
Delete action will cancel persist job. But in the actual test, most of the persist job was completed
"
Starting job Id=1636508935502 Config=PersistConfig{filePath=
Job completed Id=1636508935502 Config=PersistConfig{filePath=
"
And even if the cancellation is successful, it cannot interfere with the persist job executed on job_worker, because the next step of the delete action in the Reproduce instance is `bytesWritten = IOUtils.copyLarge(in, out, new byte[8 * Constants.MB]);`, it’s too late

**Comment by yuzhu** [comment]
@adol001 any reason why you closed this? seems like an important issue to address?

**Comment by adol001** [comment]
> @adol001 any reason why you closed this? seems like an important issue to address?

@yuzhu 
The issue was closed because of two issues. First, our ufs system delete was actually delete -rf before, and second, the local file ufs seemed to be no problem.
However, it was discovered today that if the ufs file is not persisted, it will not trigger the ufs deletion. Even if it is a local file ufs, there will still be residual files in the .alluxio_ufs_persistence directory, and the object file system, because of MASTER_UNSAFE_DIRECT_PERSIST_OBJECT_ENABLED, will leave non-hidden files in the target directory
So, Alluxio's async through mode cause inconsistencies in ufs, the problem still exists
