### ISSUE TITLE
Support alluxio client visit  mult alluxio server via nameservice.

### ISSUE THREAD

**Issue by flaming-archer** [Alluxio/alluxio#14488]
**Is your feature request related to a problem? Please describe.**
A alluxio client can visit mult alluxio server.
May be like 
`  setProp('nameservice','ns1');
  client.getFile(path);`

Then we will visit ns1 alluxio cluster.
or
`setProp('nameservice','ns2');
  client.getFile(path);`

Then we will visit ns2 alluxio cluster.

It will be usefully for one client to visit mult alluxio clusters via nameservice name.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
Maybe I develop a simple one.

**Urgency**
Mid

**Additional context**
``

**Comment by flaming-archer** [comment]
https://github.com/Alluxio/alluxio/pull/14021 maybe work with me.

**Comment by ZhuTopher** [comment]
From your issue description, I believe the feature you are requesting is more along the lines of https://github.com/Alluxio/alluxio/pull/14056? Please update this ticket if you find that #14021 is sufficient for your use-case.

**Comment by flaming-archer** [comment]
> From your issue description, I believe the feature you are requesting is more along the lines of #14056? Please update this ticket if you find that #14021 is sufficient for your use-case.

1.We want to use  EMBEDDED to ha, but #14056 used zk.
2.I have no idea how  #14056 used in java client. Maybe  #14021 just set logic name can meet my needs.

**Comment by flaming-archer** [comment]
#14021 is sufficient for my use-case.
