### ISSUE TITLE
fuse pod require high memory

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#14485]
**Alluxio Version:**
2.6.1

**Describe the bug**
when using fuse pod for tensorflow training,require high memory,max to 50g,cause k8s schedule pressure and will be oom killed if memory set to 10g or lower.

**Expected behavior**
can fuse pod memory down to 10g without oomKill

**Urgency**
very urgency

**Comment by LuQQiu** [comment]
@lilyzhoupeijie can you share a fuse heap dump?

**Comment by LuQQiu** [comment]
Can because of K8S page cache as well.
@lilyzhoupeijie will double check

**Comment by LuQQiu** [comment]
Looks like K8S cannot detect memory pressure correctly. If Process memory + page cache > memory limits, the pod may be detected as OOM by K8S and get killed.

**Comment by LuQQiu** [comment]
a temporary workaround is adding a container inside the pod and doing periodically drop page cache

**Comment by LuQQiu** [comment]
There are two approaches to alleviate the Fuse process memory consumption
1. Improve Fuse performance without using Fuse kernel_cache and other system cache related mount options
2. Solve page_cache problem in the K8S side.
For the second one, it's been a problem for years and does not seem to have a solution in recent years.
https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/
![](https://files.slack.com/files-pri/T0CJBNPD1-F02PEJ57FA5/screen_shot_2021-11-30_at_10.37.34_am.png)
Can try the workaround of setting container memory limit = memory request. See if the problem continues or whether the performance impacted

**Comment by apc999** [comment]
@lilyzhoupeijie  we are resolving this issue with highest priority, aiming for next release after 2.7.1

**Comment by LuQQiu** [comment]
Direct_io is tested in 2.8 and passed the following tests
- JNIFuseIntegrationTest
- Tensorflow test
- Filebench read/write test
- Fuse IO stressbench tests
- Pytorch data loader tests
- Java high concurrency sequential/random read + sequential write tests with variant file sizes and buffer sizes
- Python pandas parquet, CSV, pickle file tests
- Linux dd command

and is verified that using `direct_io` mode eliminates the utilization of system buffer cache and reduces the memory requirement for the fuse pod.

In our performance testing, `direct_io` compared to `kernel_cache` Fuse mount option has better write performance while relatively worse read performance. However, the pod stability cannot be ensured by using the default cache mode or `kernel_cache` mode in Kubernetes.
