### ISSUE TITLE
Configuring two-tier storage always takes up 1024mb space

### ISSUE THREAD

**Issue by amosannn** [Alluxio/alluxio#14521]
**Alluxio Version:**
2.6.2 and 2.6.0

**Describe the bug**
I deployed a new alluxio cluster on the server, but it shows that ‘usedBytes’ uses 1024MB as soon as I start it (two tiers of storage each occupy 1024MB). If I remove the second tier of storage, the occupation will disappear.

And if I upload a file larger than 1GB now, alluxio will report an error indicating insufficient space(ErrorMsg: Failed to cache: Not enough space left on worker data-hdfs-prod01:29999 to store blockId 33554432016.)

![image](https://user-images.githubusercontent.com/16012509/141716573-06f9aac2-47d6-497e-a02a-78ef0ed824b4.png)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**
config:
```
# Common properties
alluxio.master.hostname=data-hdfs-prod01
alluxio.master.mount.table.root.ufs=${alluxio.work.dir}/underFSStorage
alluxio.master.security.impersonation.root.users=*

# Worker properties
alluxio.worker.ramdisk.size=2GB
alluxio.worker.tieredstore.levels=2
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk
alluxio.worker.tieredstore.level0.dirs.mediumtype=MEM
alluxio.worker.tieredstore.level0.dirs.=4GB
alluxio.worker.tieredstore.level0.watermark.high.ratio=0.8
alluxio.worker.tieredstore.level0.watermark.low.ratio=0.5
alluxio.worker.tieredstore.level1.alias=HDD
alluxio.worker.tieredstore.level1.dirs.path=/data/alluxio-data
alluxio.worker.tieredstore.level1.dirs.mediumtype=HDD
alluxio.worker.tieredstore.level1.dirs.quota=1GB
alluxio.worker.tieredstore.level1.watermark.high.ratio=0.9
alluxio.worker.tieredstore.level1.watermark.low.ratio=0.7

# User properties
alluxio.user.file.writetype.default=ASYNC_THROUGH
```

**Comment by yuzhu** [comment]
@amosannn this is not a bug but rather by design as indicated above. please reopen if you have more questions. 

Thanks!

**Comment by amosannn** [comment]
It works, Thanks! @yuzhu
