### ISSUE TITLE
worker heap memory use high

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#14531]
**Alluxio Version:**
alluxio 2.6.1

**Describe the bug**
alluxio worker use memory as follows:
this one only shows heap memory and only alluxio worker use without job worker
![图片](https://user-images.githubusercontent.com/24890599/142128106-9578a312-1ce6-4873-aad5-af1addf844b6.png)
worker jvm setting:
  ALLUXIO_WORKER_JAVA_OPTS: ' -Dalluxio.worker.rpc.port=30062 -Dalluxio.worker.web.port=30063
    -Dalluxio.worker.container.hostname=${ALLUXIO_WORKER_CONTAINER_HOSTNAME} -Dalluxio.worker.memory.size=70Gi
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} -Xmx20g -Xms20g -XX:MaxDirectMemorySize=50g'
And the metaspaceSize show as follows:
 jinfo -flag MaxMetaspaceSize 1
-XX:MaxMetaspaceSize=18446744073709547520
jinfo -flag MetaspaceSize 1
-XX:MetaspaceSize=21807104

**To Reproduce**
spark write to allxuio

**Expected behavior**
can this be smaller?

**Comment by lilyzhoupeijie** [comment]
6 spark jobs write to alluxio ,each spark job has 20 executor and  4 cpu  * 8  memory  per executor

**Comment by LuQQiu** [comment]
@lilyzhoupeijie are you able to get one or more heap dump when the worker memory usage is high?
@yuzhu any suggestions?

**Comment by LuQQiu** [comment]
K8S will calculate memory by adding process memory + process page cache and will issue OOM when using more than 100GB

process memory is small

**Comment by LuQQiu** [comment]
K8S don't have ways to clear page cache
- worker process with new process cleaning page cache
- another manual way cleaning process page cache

**Comment by LuQQiu** [comment]
Close because K8S constraint
