### ISSUE TITLE
Improve the efficiency of s3 rest api multipart upload

### ISSUE THREAD

**Issue by jffree** [Alluxio/alluxio#14549]
When process complete multipart upload request,  alluxio proxy will read all the parts, and then rewrite them to one file. Is there any other way to improve efficiency?
For example, only by modifying metadata to mark multiple part  belonging to one file?

**Comment by ZhuTopher** [comment]
Thanks for this suggestion, I think most likely this would involve a gRPC API change in order to communicate to the Master to "merge" different files and their corresponding blocks into belonging to a single file.

**Comment by jja725** [comment]
I think it's resolved
