### ISSUE TITLE
Active Syncing is not supported on this UFS type: hdfs

### ISSUE THREAD

**Issue by jffree** [Alluxio/alluxio#14568]
**Alluxio Version:**
2.7

**Describe the bug**
When I use command `alluxio fs startSync /test`, it return an error:

```
Starting a full sync of '/test'. You can check the status of the sync using getSyncPathList cmd
Failed to start automatic syncing of '/test'.
alluxio.exception.AlluxioException: Active Syncing is not supported on this UFS type: hdfs
``` 

I found `SupportedHdfsActiveSyncProvider.java` was excluded when compiler underfs hdfs.

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>**/SupportedHdfsAclProvider.java</exclude>
            <exclude>**/SupportedHdfsActiveSyncProvider.java</exclude>
          </excludes>
        </configuration>
      </plugin>
```

Why exclude `SupportedHdfsActiveSyncProvider.java` when compiler code ?

**Comment by HelloHorizon** [comment]
@yuzhu Hey David, can you take a look?

**Comment by yuzhu** [comment]
@jffree our default distributed tarball includes the support for Active Sync for hdfs version >2.7
if you are compiling the source code yourself, be sure to use `-PhdfsActiveSync` flag

**Comment by HelloHorizon** [comment]
Thanks @yuzhu

**Comment by goldenbean** [comment]
I have noticed ufs  cosn module may  have some class loading issue with hdfs module
