### ISSUE TITLE
Alluxio client consume too much memory

### ISSUE THREAD

**Issue by yuyang733** [Alluxio/alluxio#14591]
**Alluxio Version:**
Alluxio 2.4.1

**Describe the bug**
We found that the Alluxio client consumes much more memory than HDFS and other HCFS implements, which will cause the jobs of spark/presto to fail with a greater probability due to insufficient memory resources.

**To Reproduce**

Read a mock file of 10GB size using the Alluxio client, Compared with HDFS, and you can compare the usage of the Alluxio client and HDFS client.

**Expected behavior**

**Are you planning to fix it**
Currently, I have not found a very suitable optimization solution. Therefore, I hope to discuss the repair with the community.

**Additional context**

**Comment by apc999** [comment]
@yuyang733  this is a known issue and 2.4.1 is pretty old. Can you upgrade to 2.7.0 or 2.7.1 (releasing in days) and see if you still have this issue?

**Comment by yuyang733** [comment]
> @yuyang733 this is a known issue and 2.4.1 is pretty old. Can you upgrade to 2.7.0 or 2.7.1 (releasing in days) and see if you still have this issue?

Okay, thanks.
