### ISSUE TITLE
Master crash may cause alluxio metadata to be inconsistent with UFS

### ISSUE THREAD

**Issue by qian0817** [Alluxio/alluxio#14626]
**Alluxio Version:**
master branch.

**Describe the bug**
Master crash may cause alluxio metadata to be inconsistent with UFS.

**To Reproduce**

As an example, Use local ufs to make it easy to reproduce ,firstly modify the `#InodeTree.createPath` method to simulate an abnormal exit of the master node here when create a directory.

```diff
if (currentInodeDirectory.isPinned() && !newInode.isPinned()) {
  newInode.setPinned(true);
  newInode.setMediumTypes(new HashSet<>(currentInodeDirectory.getMediumTypes()));
}
+ // mock master exit
+ Runtime.getRuntime().halt(0);
mState.applyAndJournal(rpcContext, newInode,
    inodePath.getUri().getPath());
Inode inode = Inode.wrap(newInode);
inodePath.addNextInode(inode);
createdInodes.add(inode);
LOG.debug("createFile: File Created: {} parent: {}", newInode, currentInodeDirectory);
return createdInodes;
```
Run the following commands.
```shell
➜  alluxio git:(master) ✗ ./bin/alluxio formatMaster
➜  alluxio git:(master) ✗ ./bin/alluxio-start.sh master
➜  alluxio git:(master) ✗ ./bin/alluxio fs ls /
➜  alluxio git:(master) ✗ ./bin/alluxio fs mkdir /a
```

The master node will then exit as expected. After removing the previously modified code, restart the master node.
```shell
➜  alluxio git:(master) ✗ ./bin/alluxio fs ls /
➜  alluxio git:(master) ✗ ls underFSStorage
a
```
Here the directory `a` exists in the UFS but not in the aluxio metadata, as can be seen the metadata in alluxio is inconsistent with the metadata in ufs.

**Expected behavior**
The metadata should be consistent in this case.

**Urgency**
Middle

**Are you planning to fix it**
No planning.

**Additional context**

**Comment by qian0817** [comment]
Also when I run the command ` ./bin/alluxio fs checkConsistency /`,it does't return anything, which seems to be another problem.

**Comment by apc999** [comment]
thanks @qian0817  , @yuzhu  can you take a look at this issue?

**Comment by ggezer** [comment]
> Here the directory a exists in the UFS but not in the aluxio metadata, as can be seen the metadata in alluxio is inconsistent with the metadata in ufs.

With regards to metadata consistency; how is this different from just adding a file in UFS and saying Alluxio's metadata is not in sync? Alluxio does not own storage content and can't retain the metadata in sync when there are abnormal crashes in between.

**Comment by qian0817** [comment]
> > Here the directory a exists in the UFS but not in the aluxio metadata, as can be seen the metadata in alluxio is inconsistent with the metadata in ufs.
> 
> With regards to metadata consistency; how is this different from just adding a file in UFS and saying Alluxio's metadata is not in sync? Alluxio does not own storage content and can't retain the metadata in sync when there are abnormal crashes in between.

It is reasonable to assume that directly modify the UFS will result in inconsistent metadata. But if the metadata always modify via aluxio, we expect that the metadata in aluxio can always be consistent with the UFS.

**Comment by ggezer** [comment]
> > > Here the directory a exists in the UFS but not in the aluxio metadata, as can be seen the metadata in alluxio is inconsistent with the metadata in ufs.
> > 
> > 
> > With regards to metadata consistency; how is this different from just adding a file in UFS and saying Alluxio's metadata is not in sync? Alluxio does not own storage content and can't retain the metadata in sync when there are abnormal crashes in between.
> 
> It is reasonable to assume that directly modify the UFS will result in inconsistent metadata. But if the metadata always modify via aluxio, we expect that the metadata in aluxio can always be consistent with the UFS.

That's correct, but granted that UFS is disconnected to Alluxio, metadata can't be guaranteed to be in sync when abrupt crashes happen. There are ways we could detect and patch such gaps, but that would be costly in terms of runtime performance. (Like appending a special entry before and after each op to simulate transactional semantics.)

**Comment by qian0817** [comment]
I agree, I think making UFS and Alluxio metadata operations atomic is really a hard problem to deal with.
