### ISSUE TITLE
Journal not sync in masters

### ISSUE THREAD

**Issue by jffree** [Alluxio/alluxio#14632]
**Alluxio Version:**
2.6.1

**Describe the bug**
The journal between masters cannot be synchronized. When the leader loses contact, another master is elected as the leader. This situation will cause journal data inconsistencies.

**To Reproduce**
1. Start alluxio cluster with 3 masters.
2. Start sync one path (use `alluxio fs startSync /xxxx`). 
3. Observe the size of journals of different masters. We can find that the leader's journal grows very fast, but the follwer master's journal hardly grows.
4. kill leader.  Another master will be elected as the leader. New Leader will write journal.
5. Start the killed master node.  It will be re-elected as the leader.

**Comment by yuzhu** [comment]
@jffree can you check if snapshots are taken successfully on the followers? and if there are any log entries indicating errors in the journal system?
