### ISSUE TITLE
refactor Master’s maxThroughput stress benchmark

### ISSUE THREAD

**Issue by yabola** [Alluxio/alluxio#14654]
**Summary**
In this PR https://github.com/Alluxio/alluxio/pull/14207 , job service max throughput refactoring had been completed. But the master’s maxThroughput stress benchmark has yet to be completed. We need to refactor this and then consider how to complete fuse's maxThroughput stress benchmark.

**Comment by yabola** [comment]
@LuQQiu I am in progress

**Comment by LuQQiu** [comment]
Priority medium validated by @yuzhu
