### ISSUE TITLE
Fuse always crash when try to write data in using 'mv'

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#14688]
**Alluxio Version:**
2.5.2

**Describe the bug**
When try to use linux 'mv' command to write data into fuse, fuse client will always crash.

**To Reproduce**

bili-docker /workspace # echo "abcd" > test.txt
bili-docker /workspace # cp test.txt /DATA/jupyter/test3.txt
bili-docker /workspace # cp test.txt /DATA/jupyter/account-steal-data-space/test3.txt
bili-docker /workspace # cat /DATA/jupyter/account-steal-data-space/test3.txt^C
bili-docker /workspace # cp test.txt /DATA/jupyter/account-steal-data-space/test/test3.txt
bili-docker /workspace # cat /DATA/jupyter/account-steal-data-space/test/test3.txt
abcd
bili-docker /workspace # mv test.txt /DATA/jupyter/account-steal-data-space/test/test4.txt
mv: preserving permissions for ‘/DATA/jupyter/account-steal-data-space/test/test4.txt’: Software caused connection abort
mv: failed to close '/DATA/jupyter/account-steal-data-space/test/test4.txt': Transport endpoint is not connected

Fuse crash log:

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f3db433d75e, pid=15, tid=0x00007f3cdbfff700

 JRE version: OpenJDK Runtime Environment (8.0_282-b08) (build 1.8.0_282-8u282-b08-0ubuntu1~16.04-b08)
 Java VM: OpenJDK 64-Bit Server VM (25.282-b08 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x69275e]

 Core dump written. Default location: /opt/alluxio-release-2.5.0-2-SNAPSHOT/core or core.15

 An error report file with more information is saved as:
 /opt/alluxio-release-2.5.0-2-SNAPSHOT/hs_err_pid15.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

**Expected behavior**
Is mv supported for fuse ? If not supported, fuse should reject the mv request instead of crash.

**Comment by maobaolong** [comment]
@Nizifan Good catch, I create a PR to solve this issue. #14690
