### ISSUE TITLE
Fuse can not read file just written with alluxio.user.metadata.cache.enabled=true

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#14699]
**Alluxio Version:**
2.5.0.2

**Describe the bug**
Fuse client can not read file just written
And the next run (meaning we starting  a new fuse) can read the file correctly, and if it read file it just created, it can not read again.

And set Alluxio property: alluxio.user.metadata.cache.enabled=false can resolve this issue immediately.

**To Reproduce**

root@train-244459-worker-0:/cache# echo "zz" > a.txt
root@train-244459-worker-0:/cache# cat a.txt
cat: a.txt: Input/output error

**Additional context**
config map used:
-Dalluxio.master.hostname=fluid-test-master-0 -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME}
    -Dalluxio.master.journal.type=EMBEDDED -Dalluxio.master.journal.folder=/journal
    -Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.alias=SSD
    -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD -Dalluxio.worker.tieredstore.level0.dirs.path=/data/docker/alluxio/default/fluid-test/default/fluid-test
    -Dalluxio.worker.tieredstore.level0.dirs.quota=500GB -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95
    -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7 -Dalluxio.fuse.cached.paths.max=1000000
    -Dalluxio.fuse.debug.enabled=false -Dalluxio.fuse.jnifuse.enabled=true -Dalluxio.fuse.logging.threshold=1000ms
    -Dalluxio.fuse.shared.caching.reader.enabled=true -Dalluxio.fuse.user.group.translation.enabled=true
    -Dalluxio.job.master.finished.job.retention.time=30sec -Dalluxio.job.master.rpc.port=20067
    -Dalluxio.job.master.web.port=20068 -Dalluxio.job.worker.data.port=20071 -Dalluxio.job.worker.rpc.port=20069
    -Dalluxio.job.worker.threadpool.size=164 -Dalluxio.job.worker.web.port=20070 -Dalluxio.master.journal.folder=/journal
    -Dalluxio.master.journal.log.size.bytes.max=500MB -Dalluxio.master.journal.type=UFS
    -Dalluxio.master.metadata.sync.concurrency.level=128 -Dalluxio.master.metadata.sync.executor.pool.size=128
    -Dalluxio.master.metadata.sync.ufs.prefetch.pool.size=128 -Dalluxio.master.metastore=ROCKS
    -Dalluxio.master.metastore.inode.cache.max.size=10000000 -Dalluxio.master.mount.table.root.ufs=s3://coeus-online/prod/model
    -Dalluxio.master.rpc.executor.core.pool.size=128 -Dalluxio.master.rpc.executor.max.pool.size=1024
    -Dalluxio.master.rpc.port=20063 -Dalluxio.master.security.impersonation.root.groups=*
    -Dalluxio.master.security.impersonation.root.users=* -Dalluxio.master.web.port=20064
    -Dalluxio.security.authorization.permission.enabled=false -Dalluxio.security.stale.channel.purge.interval=365d
    -Dalluxio.underfs.object.store.breadcrumbs.enabled=false -Dalluxio.underfs.s3.endpoint=http://jssz-inner-boss.bilibili.co
    -Dalluxio.underfs.s3.inherit.acl=false -Dalluxio.user.block.avoid.eviction.policy.reserved.size.bytes=2GB
    -Dalluxio.user.block.master.client.pool.gc.threshold=10min -Dalluxio.user.block.master.client.threads=1024
    -Dalluxio.user.block.size.bytes.default=16MB -Dalluxio.user.block.worker.client.pool.min=512
    -Dalluxio.user.block.write.location.policy.class=alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
    -Dalluxio.user.client.cache.enabled=false -Dalluxio.user.direct.memory.io.enabled=true
    -Dalluxio.user.file.create.ttl.action=FREE -Dalluxio.user.file.master.client.threads=1024
    -Dalluxio.user.file.passive.cache.enabled=false -Dalluxio.user.file.readtype.default=CACHE
    -Dalluxio.user.file.replication.max=1 -Dalluxio.user.file.writetype.default=MUST_CACHE
    -Dalluxio.user.local.reader.chunk.size.bytes=32MB -Dalluxio.user.logging.threshold=1000ms
    -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.user.metadata.cache.expiration.time=10min
    -Dalluxio.user.metadata.cache.max.size=6000000 -Dalluxio.user.metrics.collection.enabled=true
    -Dalluxio.user.streaming.reader.chunk.size.bytes=32MB -Dalluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.LocalFirstPolicy
    -Dalluxio.user.update.file.accesstime.disabled=true -Dalluxio.user.worker.list.refresh.interval=2min
    -Dalluxio.web.ui.enabled=false -Dalluxio.worker.allocator.class=alluxio.worker.block.allocator.MaxFreeAllocator
    -Dalluxio.worker.block.master.client.pool.size=1024 -Dalluxio.worker.network.reader.buffer.size=32MB
    -Dalluxio.worker.rpc.port=20065 -Dalluxio.worker.web.port=20066 -Daws.accessKeyId=5c333a32a7cc4d33
    -Daws.secretKey=50ea69fa22139f1cccea8736dd2f588a '

**Comment by LuQQiu** [comment]
Tested in both Mac and Linux
Alluxio master branch succeed in the above workloads
while Alluxio 2.5.0-2 failed with the exact same error
