### ISSUE TITLE
Severe performance issue when master serving 10M+ files

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#14729]
**Alluxio Version:**
2.5.0.2

**Describe the bug**
Recently we have provide Alluxio for 2 engineers whose train involve massive count of file. And during training they found severe performance issue.

Case #1
Engineer have ~18M files, evenly spread in 60 folders, of total size 20T. He build a cluster with 13 workers.
At first the cluster work as expected. Around minutes later, all the operation (cd/cat/ls) get hanged.

In the master logs we see massive of GetStatus call exceed max time logs, we see extreme cases of >1800s timeout
2021-12-22 04:26:26,742 WARN  UnderFileSystemWithLogging - ListStatus(path=s3://coeus-chenyimin/data/datasets/full/0820_full_320p/847468542_392173062) returned OK in 35079 ms (>=10000 ms)

Case #2
Engineer have 100M+ files of high levels of folder struct, total size around 3T. His training will only access a small set of them.
The first epoch read show very bad performance, take 20~40s to read a 200M file while normal download take 1s.
Later engineer try to cache a subset of 2.5M and receive very great performance.

Below is some codlin trace info.
![wecom-temp-99e24129dfb168d38862f5a3c893cd69](https://user-images.githubusercontent.com/11472213/147035809-1d0bf8ee-3807-4348-9e40-7933e1018e74.png)

**Comment by Nizifan** [comment]
below is our config:
ALLUXIO_JAVA_OPTS: '-Dalluxio.master.hostname=chenyimin-master-0 -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME}
  -Dalluxio.master.journal.type=EMBEDDED -Dalluxio.master.journal.folder=/journal
  -Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.alias=SSD
  -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD -Dalluxio.worker.tieredstore.level0.dirs.path=/data/docker/alluxio/cv-pretrain/chenyimin/cv-pretrain/chenyimin
  -Dalluxio.worker.tieredstore.level0.dirs.quota=1250GB -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95
  -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7 -Dalluxio.fuse.cached.paths.max=1000000
  -Dalluxio.fuse.debug.enabled=false -Dalluxio.fuse.jnifuse.enabled=true -Dalluxio.fuse.logging.threshold=1000ms
  -Dalluxio.fuse.shared.caching.reader.enabled=true -Dalluxio.fuse.user.group.translation.enabled=true
  -Dalluxio.job.master.finished.job.retention.time=30sec -Dalluxio.job.master.rpc.port=20076
  -Dalluxio.job.master.web.port=20077 -Dalluxio.job.worker.data.port=20080 -Dalluxio.job.worker.rpc.port=20078
  -Dalluxio.job.worker.threadpool.size=164 -Dalluxio.job.worker.web.port=20079 -Dalluxio.master.journal.folder=/journal
  -Dalluxio.master.journal.log.size.bytes.max=500MB -Dalluxio.master.journal.type=UFS
  -Dalluxio.master.metadata.sync.concurrency.level=128 -Dalluxio.master.metadata.sync.executor.pool.size=128
  -Dalluxio.master.metadata.sync.ufs.prefetch.pool.size=128 -Dalluxio.master.metastore=ROCKS
  -Dalluxio.master.metastore.inode.cache.max.size=10000000 -Dalluxio.master.mount.table.root.ufs=s3://coeus-chenyimin/data/datasets
  -Dalluxio.master.rpc.executor.core.pool.size=128 -Dalluxio.master.rpc.executor.max.pool.size=1024
  -Dalluxio.master.rpc.port=20072 -Dalluxio.master.security.impersonation.root.groups=*
  -Dalluxio.master.security.impersonation.root.users=* -Dalluxio.master.web.port=20073
  -Dalluxio.security.authorization.permission.enabled=false -Dalluxio.security.stale.channel.purge.interval=365d
  -Dalluxio.underfs.object.store.breadcrumbs.enabled=false -Dalluxio.underfs.s3.endpoint=http://jssz-inner-boss.bilibili.co
  -Dalluxio.underfs.s3.inherit.acl=false -Dalluxio.user.block.avoid.eviction.policy.reserved.size.bytes=2GB
  -Dalluxio.user.block.master.client.pool.gc.threshold=10min -Dalluxio.user.block.master.client.threads=1024
  -Dalluxio.user.block.size.bytes.default=16MB -Dalluxio.user.block.worker.client.pool.min=512
  -Dalluxio.user.block.write.location.policy.class=alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
  -Dalluxio.user.client.cache.enabled=false -Dalluxio.user.direct.memory.io.enabled=true
  -Dalluxio.user.file.create.ttl.action=FREE -Dalluxio.user.file.master.client.threads=1024
  -Dalluxio.user.file.passive.cache.enabled=false -Dalluxio.user.file.readtype.default=CACHE
  -Dalluxio.user.file.replication.max=1 -Dalluxio.user.file.writetype.default=MUST_CACHE
  -Dalluxio.user.local.reader.chunk.size.bytes=32MB -Dalluxio.user.logging.threshold=1000ms
  -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.user.metadata.cache.expiration.time=10min
  -Dalluxio.user.metadata.cache.max.size=6000000 -Dalluxio.user.metrics.collection.enabled=true
  -Dalluxio.user.streaming.reader.chunk.size.bytes=32MB -Dalluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.LocalFirstPolicy
  -Dalluxio.user.update.file.accesstime.disabled=true -Dalluxio.user.worker.list.refresh.interval=2min
  -Dalluxio.web.ui.enabled=false -Dalluxio.worker.allocator.class=alluxio.worker.block.allocator.MaxFreeAllocator
  -Dalluxio.worker.block.master.client.pool.size=1024 -Dalluxio.worker.network.reader.buffer.size=32MB
  -Dalluxio.worker.rpc.port=20074 -Dalluxio.worker.web.port=20075 -

**Comment by jiacheliu3** [comment]
@yuzhu @apc999 Are you aware of this one?

**Comment by yuzhu** [comment]
@LuQQiu fyi

**Comment by LuQQiu** [comment]
@yuzhu For the first case, do you think it's related to any of the issues we fixed between master branch and 2.5.0-2? 
I am thinking about whether upgrading to the newest version can help solve the issue? or ask them to try again in this older version and get the needed logs, metrics,  threaddump?

**Comment by umialpha** [comment]
> @yuzhu For the first case, do you think it's related to any of the issues we fixed between master branch and 2.5.0-2? I am thinking about whether upgrading to the newest version can help solve the issue? or ask them to try again in this older version and get the needed logs, metrics, threaddump?

Thanks @LuQQiu , we can try to upgrade our version to 2.8 at the same time.

**Comment by LuQQiu** [comment]
Changed to version 2.7.2. Compared to 2.5, performance has huge improvements
but encounter master memory limit problem. could be related to #14746
