### ISSUE TITLE
Move scheduling decision from client to master

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#14730]
This proposal is from @maobaolong 

The ask is to move the scheduling decision from the client into the master. Right now the client decides which worker to go to.

**Is your feature request related to a problem? Please describe.**
Right now the scheduling decision is made at the client side at https://github.com/Alluxio/alluxio/blob/cd1902383555d65ea85a561d1840137052b9ff4e/core/client/fs/src/main/java/alluxio/client/block/util/BlockLocationUtils.java#L46
This relies on the client having updated info about the workers. Having the decision made (at least preference decided) at the master side could yield smarter decisions (and more extensibility in the future).

Also due to the fact that it's relatively easier to update the master than it is to upgrade the client jar in mass prod environments like @maobaolong 's, having the scheduling logic in the master side enables them to have feedback and iterate faster.

**Describe the solution you'd like**
Move the scheduling decision partly or fully into the master.

A few pros from our previous discussion and my opinions:

Pros:
* The master is slightly more up-to-date about the worker status.
* The master may have a more global view of the cluster and can make better decisions. This can be a bit more extensible in the future, if we see the worker can provide more info to the master to aggregate a global view on worker latency, for example.
* Shorter iteration due to smaller upgrade overhead. In some environments upgrading client jar involves coordination with many other teams and the procedures are cumbersome.
* Lighter client (not necessarily). If the master decision does not worker, it also makes sense for the client to make yet other decisions in retries.
* Less need for the client to be up-to-date on the worker status with the master.

**Describe alternatives you've considered**

**Urgency**
Medium

**Additional context**

**Comment by maobaolong** [comment]
@jiacheliu3 Thank you advance for create this issue and given these `Pros` here, this is significant change, after this, @xichen01 would like to add more choose worker policy on master.

**Comment by elega** [comment]
@jiacheliu3 is this issue still valid?

**Comment by jiacheliu3** [comment]
Will not address in master-2.x.
And in the new Dora structure (main branch), the master component will become more lightweight, meaning this scheduling decision will only happen in client.
