### ISSUE TITLE
请问支持BeeGfs文件系统吗？

### ISSUE THREAD

**Issue by goodpp** [Alluxio/alluxio#14762]
看官网支持的底层文件系统里面没有BeeGfs，想请问下是否支持或者有计划支持BeeGfs吗？

**Comment by LuQQiu** [comment]
@goodpp 目前 alluxio 不支持 BeeGfs，但是可以通过 https://docs.alluxio.io/os/user/stable/en/ufs/Ufs-Extension-API.html 实现一个 BeeGfs 接口。我们短期内没有计划支持 BeeGfs, 欢迎提交 PR 实现 BeeGfs UFS
