### ISSUE TITLE
Add Fuse shell doc in POSIX API doc

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14776]
**Page**
[POSIX API page](https://docs.alluxio.io/os/user/stable/en/api/POSIX-API.html)
Add documentation for Fuse shell in general
and the current available commands.
In the future, when there are more Fuse shell commands, consider moving to a separate page.

**Summary**

**Comment by LuQQiu** [comment]
@bzheng888 PTAL and help add the Fuse shell doc, thanks!

**Comment by bzheng888** [comment]
WIll do!

**Comment by LuQQiu** [comment]
Thanks @bzheng888 !
