### ISSUE TITLE
alluxio.user.client.cache.store.type=ROCKS can not work

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#14822]
**Alluxio Version:**
alluxio-shaded-client-2.6.2-2.jar

**Describe the bug**
alluxio.user.client.cache.store.type=ROCKS can not work.

**To Reproduce**
1. Config prestodb's hive connector with alluxio local cache:
    etc/jvm.config
    `-Dalluxio.user.client.cache.store.type=ROCKS`
    etc/catalog/hive.properties
    `cache.enabled=true`
    `cache.base-directory=file:///.../data`
   ` cache.type=ALLUXIO`
    `cache.alluxio.max-cache-size=16GB`
2. Execute query.

**Expected behavior**
alluxio.user.client.cache.store.type=ROCKS works well.

**Urgency**
Urgent. Local cache can not work effectively on HDD.

**Additional context**
Error on presto side:
java.lang.NoClassDefFoundError: alluxio/shaded/client/org/rocksdb/CompressionType 	at alluxio.client.file.cache.store.RocksPageStoreOptions.<init>(RocksPageStoreOptions.java:50) 	at alluxio.client.file.cache.store.PageStoreOptions.create(PageStoreOptions.java:39) 	at alluxio.client.file.cache.LocalCacheManager.create(LocalCacheManager.java:112) 	at alluxio.client.file.cache.CacheManager$Factory.create(CacheManager.java:111) 	at alluxio.client.file.cache.CacheManager$Factory.get(CacheManager.java:89) 	at alluxio.hadoop.LocalCacheFileSystem.initialize(LocalCacheFileSystem.java:108) 	at com.facebook.presto.cache.alluxio.AlluxioCachingFileSystem.initialize(AlluxioCachingFileSystem.java:72) 	at com.facebook.presto.cache.CacheFactory.createCachingFileSystem(CacheFactory.java:54) 	at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration.lambda$getConfiguration$0(HiveCachingHdfsConfiguration.java:71) 	at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration$CachingJobConf.createFileSystem(HiveCachingHdfsConfiguration.java:105) 	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:59) 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373) 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295) 	at com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:71) 	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23) 	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70) 	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64) 	at com.facebook.presto.hive.HiveWriteUtils.isS3FileSystem(HiveWriteUtils.java:385) 	at com.facebook.presto.hive.HiveWriteUtils.getTableDefaultLocation(HiveWriteUtils.java:365) 	at com.facebook.presto.hive.HiveLocationService.forNewTable(HiveLocationService.java:60) 	at com.facebook.presto.hive.HiveMetadata.beginCreateTable(HiveMetadata.java:1551) 	at com.facebook.presto.hive.HiveMetadata.beginCreateTable(HiveMetadata.java:353) 	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.beginCreateTable(ClassLoaderSafeConnectorMetadata.java:404) 	at com.facebook.presto.metadata.MetadataManager.beginCreateTable(MetadataManager.java:858) 	at com.facebook.presto.execution.scheduler.TableWriteInfo.createWriterTarget(TableWriteInfo.java:89) 	at com.facebook.presto.execution.scheduler.TableWriteInfo.createTableWriteInfo(TableWriteInfo.java:76) 	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:166) 	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:353) 	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:242) 	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:171) 	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:522) 	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:371) 	at com.facebook.presto.$gen.Presto_0_266_c1e2e77____20220110_071855_1.run(Unknown Source) 	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:266) 	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:197) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.ClassNotFoundException: alluxio.shaded.client.org.rocksdb.CompressionType 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) 	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) 	... 38 more

**Comment by apc999** [comment]
@JySongWithZhangCe local cache with Rocks is experimental -- I think I have seen this issue before.
Tag @beinan here to track this

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe local cache with Rocks is experimental -- I think I have seen this issue before. Tag @beinan here to track this . Beinan, you have run local cache with Rocks before, right?

I have found how to fix this issue, and I will submit a PR.

**Comment by beinan** [comment]
rerun the test.
I didn't see this error before, I'm thinking I might have rocksdb jar somewhere in the dependency tree somewhere.  Let me double check.

**Comment by JySongWithZhangCe** [comment]
And there is another `java.lang.UnsatisfiedLinkError` when RocksDB call native method while RocksDB is shaded.

**Comment by beinan** [comment]
> And there is another `java.lang.UnsatisfiedLinkError` when RocksDB call native method while RocksDB is shaded.

Yep, I will take a look and try to optimized the shading rule

**Comment by beinan** [comment]
fixed in https://github.com/Alluxio/alluxio/pull/15120
