### ISSUE TITLE
Confused isSet() and isSetByUser()

### ISSUE THREAD

**Issue by xichen01** [Alluxio/alluxio#14835]
**Alluxio Version:**
2.7.2

**Describe the bug**

There are a lot of codes that use `isSet()` to determine whether the key is set, but according to the code context, it may be more accurate to use `isSetByUser()` 

`isSetByUser()` can accurately determine whether the key is set by the user, regardless of whether the `key` has a default value.
 if the `key` has a default value, `isSet()` will not be able to distinguish whether the `key` is set by the user or has a default value.

example:
https://github.com/Alluxio/alluxio/pull/14833

There may be other places in Alluxio that confuse the two interfaces(`ConfusedisSet()` and `isSetByUser()`), which may contain some bugs

**To Reproduce**

**Expected behavior**
There may be misjudgments, maybe the user has not set the key, but using `isSet()` will return `True` if the key has a default value

**Urgency**
**Are you planning to fix it**
**Additional context**

**Comment by apc999** [comment]
`isSet(key)` is typically used before `conf.get(key)` to avoid the case a property key has no default value set.
that's the expected use case. 
I left some comments in https://github.com/Alluxio/alluxio/pull/14833

**Comment by apc999** [comment]
Fixed by https://github.com/Alluxio/alluxio/pull/14833.
Feel free to submit follow up PRs to clean up the codebase
