### ISSUE TITLE
Write data causes master crash and can't restart.

### ISSUE THREAD

**Issue by bzheng888** [Alluxio/alluxio#14847]
**Alluxio Version:**
2.7

**Describe the bug**
Write data(maybe include read, delete operation) to Alluxio cluster and the Alluxio master will crush.
The master crush log:
![image](https://user-images.githubusercontent.com/42070967/149337707-bc6e4eef-a0d5-4c72-84fb-3b4d7f1fa9a4.png)

**To Reproduce**
1. Create a Alluxio cluster with one Master and three workers.
2. Our Impala will write data to Alluxio. 

**Expected behavior**
The master should not crush.

**Urgency**
Urgent

**Are you planning to fix it**
No

**Additional context**
No

**Comment by jiacheliu3** [comment]
We expect https://github.com/Alluxio/alluxio/pull/14856 to fix the rocksDB crash issue for you. If possible, please try to upgrade to a version with that change and try. 

FYI @maobaolong
