### ISSUE TITLE
Can alluxio mount oss bucket directly?

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#14874]
**Alluxio Version:**
What version of Alluxio are you using?

2.7.3-SNAPSHOT

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

I tried to mount oss bucket `test` to alluxio file system, and run `ls`. There are no files

```
alluxio fs mount --option fs.oss.endpoint=oss-cn-shanghai-internal.aliyuncs.com --option fs.oss.accessKeyId=abc --option fs.oss.accessKeySecret=efg /abc oss://test/
Mounted oss://wdl-shanghai/ at /abc
alluxio fs ls /abc
alluxio fs umount /abc
Unmounted /abc
```

Instead  I tried with the directory `oss://test/tfrecords` under the ossbucket, it works. 

```
alluxio fs mount --option fs.oss.endpoint=oss-cn-shanghai-internal.aliyuncs.com --option fs.oss.accessKeyId=abc --option fs.oss.accessKeySecret=efg /abc oss://test/tfrecords
Mounted oss://wdl-shanghai/tfrecords at /abc
alluxio fs ls /abc
              0       PERSISTED 01-19-2022 07:28:08:958  DIR /abc/transformed_metadata
           1180       PERSISTED 12-28-2020 12:12:08:000   0% /abc/transformed_metadata.tar.gz
              0       PERSISTED 01-19-2022 07:28:08:960  DIR /abc/train
```

I am wondering if it's as design. 

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by cheyang** [comment]
ping @apc999

**Comment by apc999** [comment]
@cheyang  it looks like a bug to us. Let David (@yuzhu ) help here

**Comment by HelloHorizon** [comment]
@beinan can you take a look at this issue?

**Comment by TrafalgarZZZ** [comment]
Same problem here. And I found that it only occurs when I am using Alluxio 2.7. When I change it back to Alluxio 2.5.0, it works well.

**Comment by beinan** [comment]
Hi @HelloHorizon & @fuzhengjia , I think it might be caused by this change https://github.com/Alluxio/alluxio/commit/95d69b2e7f0651f2c5fb01dca3fe54bde861c993 because it's just failing to list the root dir.   I think the issue could be reproduced on both s3 and oss.

**Comment by HelloHorizon** [comment]
#14664 related pr

**Comment by beinan** [comment]
synced with @fuzhengjia offline,  we're on it and we will get back to you guys soon once we have a solution.

**Comment by HelloHorizon** [comment]
https://github.com/Alluxio/alluxio/pull/15361 fix this issue
