### ISSUE TITLE
Set alluxio.user.block.write.location.policy.class to round robin policy does not work

### ISSUE THREAD

**Issue by lynus** [Alluxio/alluxio#14875]
**Alluxio Version:**
2.7.2

**Describe the bug**
Accroding to javadoc describing round robin policy[1] , "A policy that chooses the worker for the next block in a round-robin manner and skips workers that do not have enough space", the out stream would choose a available work and continue to write. 
But the outStream still fails on out of space exception.
**To Reproduce**
1.Setup a cluste with 4 workers that contains 32GB, 32GB, 4GB, 4GB memory cache repectively. 
2. set alluxio.user.block.write.location.policy.class = alluxio.client.block.policy.RoundRobinPolicy in alluxio-site.properties
3. Using java api AlluxioFileOutStream to write a 8 GB file.

**Expected behavior**
The write should sucess. 

**Urgency**
Not sure

**Are you planning to fix it**
Not sure

**Additional context**
[1]https://docs.alluxio.io/os/javadoc/stable/index.html

**Comment by JySongWithZhangCe** [comment]
Default write type in Alluxio 2.7.2 is `ASYNC_THROUGH`, this type requires all blocks under the same file should write to the one single Alluxio Worker. Your file is 8 GB over 4 GB. You can set `alluxio.user.file.writetype.default=CACHE_THROUGH` to solve your problem.

**Comment by lynus** [comment]
Thanks for your reply.
