### ISSUE TITLE
alluxio fuse delete file unexpectedly in open function

### ISSUE THREAD

**Issue by liuyongqing** [Alluxio/alluxio#14895]
**Alluxio Version:**
2.7.2

**Describe the bug**
alluxio fuse  not correctly deal with open flags O_RDONLY、O_WRONLY、O_RDWR，which will delete file unexpectely.

**To Reproduce**
the below code open file with O_WRONLY, which will not delete exist file in linux，however in alluxio fuse, it will delete the file,
we should delete the file only if user specify O_TRUNC flag.

#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include<stdio.h>
int main()
{
    int fd, size;
    char s[] = "Linux Programmer!\n";
    char buffer[80];
    char txt[] = "mnt/test.txt";
    fd = open(txt, O_WRONLY|O_CREAT, 644);
    if (fd < 0) {
       printf("failed to open file, fd:%d", fd);
       return -1;
    }
    int len = sizeof(s);
   printf("len:%d\n", len);
    int ret = write(fd, s, len);
    if (ret < 0) {
       printf("failed to write data, ret:%d", ret);
       return ret;
    }
   close(fd);
}

**Expected behavior**
we should delete the file only if user specify O_TRUNC flag.

**Urgency**
middle level urgency

**Are you planning to fix it**
To avoid file was wrongly deleted, i'm planning to remove the exist file only if user specify O_TRUNC flag

**Comment by liuyongqing** [comment]
@LuQQiu

**Comment by liuyongqing** [comment]
@LuQQiu ,the fixed pr is https://github.com/Alluxio/alluxio/pull/14897

**Comment by LuQQiu** [comment]
@liuyongqing 
Alluxio internally does not support file overwriting or file appending.
I tested the script, looks like
1. when test.txt already exist
2. the script will open with flag `0x8001` write only
3. Alluxio will delete the existing file and create a new one, write the content
4. [alluxio@ProcessLocalRead-worker-0 alluxio-standalone-fuse-read]$ cat test.txt
Linux Programmer!
```
2022-01-24 19:41:55,540 DEBUG AlluxioJniFuseFileSystem - Open path /test.txt with flags 0x8001 for overwriting. Alluxio deleted the old file and created a new file for writing
2022-01-24 19:41:55,540 DEBUG AlluxioJniFuseFileSystem - Exit (0): Fuse.open(path=/test.txt,flags=0x8001) in 41 ms
2022-01-24 19:41:55,540 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Write(path=/test.txt,buf=java.nio.DirectByteBuffer[pos=0 lim=19 cap=19],size=19,offset=0)
```
Linux system will not delete the existing file because it supports file overwriting

**Comment by LuQQiu** [comment]
@liuyongqing what's the fuse behavior you want? error out directly when the file exists and open with `Write` flag?

**Comment by liuyongqing** [comment]
@LuQQiu ，the following open test, it will not delete the exist file in linux, hower it will delete exist file in alluxio fuse, we can delete the exist file except we specify flag  O_WRONLY|O_TRUNC
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
main()
{
    int fd, size;
    char s[] = "Linux Programmer!\n", buffer[80];
    fd = open("/tmp/temp", O_WRONLY);
    write(fd, s, sizeof(s));
    close(fd);
    fd = open("/tmp/temp", O_RDONLY);
    size = read(fd, buffer, sizeof(buffer));
    close(fd);
    printf("%s", buffer);
}

**Comment by liuyongqing** [comment]
further more, i think we treat O_RDWR is complicated in current alluxio 2.7 branch，which defer the input/output stream to first read to write; because alluxio can't read or write for same fd, consider the following process:
1. O_RDONLY，we should record an input stream for read
2. O_WRONLY，if no O_TRUNC specify, should report error, because we can't rewrite part to content; if specify, we can delete exist file, and record a outputstream
3. O_RDWR ，if no O_TRUNC, and file exist we should downgrade to read mode; if specify O_TRUNC, we can delete exist file, and record a outputstream.

**Comment by liuyongqing** [comment]
the following is an overwrite cp strace: ![企业微信截图_8dad107d-f7eb-4323-a3a4-9ef1b4eda816](https://user-images.githubusercontent.com/5205797/151101446-33f1b42f-3415-491a-b66d-02bc62e75d44.png)

**Comment by liuyongqing** [comment]
for open trunc case, could refer: 
https://github.com/Alluxio/alluxio/pull/14897
https://github.com/s3fs-fuse/s3fs-fuse/blob/master/src/s3fs.cpp(function s3fs_open)

**Comment by LuQQiu** [comment]
@liuyongqing Thanks for the detailed information! Will modify the current open logics

**Comment by LuQQiu** [comment]
Thanks a lot @liuyongqing 
Basically we 
```
if (READONLY & TRUNCATE) {
	return -EACESS
}
if (TRUNCATE && file exist) {
   // DELETE FILE
}
wait for file completed or error out
if (READONLY || (READ_WRITE && file exists)) {
  OPEN FILE_IN_STREAM
} else {
 OPEN_FILE_OUT_STREAM
}
```
in this case, we don't need to defer READ_WRITE to first read() or write()

The code is much more correct and clean, appreciate your help and wonderful suggestions!

**Comment by LuQQiu** [comment]
@maobaolong FYI
