### ISSUE TITLE
DistributedLoad fails in k8s env

### ISSUE THREAD

**Issue by ssz1997** [Alluxio/alluxio#14924]
Alluxio version: v2.7.2

In a k8s env where alluxio runs in docker containers, we have 1 master and 1 worker, a distributed load on a dir with 1.9G can only cache 8MB. 

worker log:
[worker.log](https://github.com/Alluxio/alluxio/files/7947411/worker.log)
job worker log:
[job_worker.log](https://github.com/Alluxio/alluxio/files/7952972/job_worker.log)

This problem can be reproduced consistently in Fluid with version 2.7.2.
Alluxio 2.7.0 doesn't have the issue

From the worker log, we found
```
2022-01-27 00:59:20,564 WARN  CacheRequestManager - Failed to async cache block 9110028288 from remote worker (ip-10-0-5-96.ec2.internal/10.0.5.96:20088) on copying the block: alluxio.exception.status.DeadlineExceededException: Timeout waiting for response after 300000ms. clientClosed: false clientCancelled: false serverClosed: false (Zero Copy GrpcDataReader)
```
The worker is requesting itself to async cache block and read from itself.
https://github.com/Alluxio/alluxio/blob/d3e231a02ea4ef1415e623cfbc742c5f69e8ba8c/core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java#L225

By looking into commits between 2.7.0 (good version) and 2.7.2 (bad version), we found
possible commit: https://github.com/Alluxio/alluxio/commit/e765c8436d36aaf911607f2fb4b772c52ac82f0a
with code comments
```
    // issues#11172: If the worker is in a container, use the container hostname
    // to establish the connection.
    if (!dataSource.getContainerHost().equals("")) {
      host = dataSource.getContainerHost();
    }
```
https://github.com/Alluxio/alluxio/blob/d3e231a02ea4ef1415e623cfbc742c5f69e8ba8c/job/server/src/main/java/alluxio/job/util/JobUtils.java#L215
```
// issues#11172: If the worker is in a container, use the container hostname
```

**Comment by LuQQiu** [comment]
@yuzhu @jja725 DistributedLoad nearly unusable in Kubernetes env with Alluxio 2.7.2. Please take a look. @ssz1997 can help guide you to reproduce the environment

**Comment by LuQQiu** [comment]
May relates to https://github.com/Alluxio/alluxio/issues/14851

**Comment by jja725** [comment]
@LuQQiu Why it's related?

**Comment by LuQQiu** [comment]
@jja725 no worries, linked the wrong issue

**Comment by jja725** [comment]
My investigation:
DistributedLoad would fail but when we are using loadCommand it works fine(requesting the same host and using the same patther to find host)
workerNetaddress for selected worker doesn't have containerHost field:
```
WorkerNetAddress{host=10.0.5.165, containerHost=, rpcPort=20168, dataPort=20168, webPort=21288, domainSocketPath=, tieredIdentity=TieredIdentity(node=10.0.5.165, rack=null)}
```
@yuzhu  @ZhuTopher

**Comment by ZhuTopher** [comment]
Not sure why you're seeing no `containerHost` value. From my understanding of the [original issue](https://github.com/Alluxio/alluxio/issues/11172#issuecomment-605620207) which introduced that field, if a worker is deployed in a k8s Pod that metadata needs to exist for routing to work properly.
- Our current [Helm chart](https://github.com/Alluxio/alluxio/blob/93e5d0c9fe2effae9e0463fa6d7008d25afef850/integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml#L275-L284) ensures that the corresponding ENV var `ALLUXIO_WORKER_CONTAINER_HOSTNAME` is set. That ENV var gets read in the `PropertyKey`  `WORKER_CONTAINER_HOSTNAME `.

From the [linked commit](https://github.com/Alluxio/alluxio/commit/e765c8436d36aaf911607f2fb4b772c52ac82f0a#diff-59d51a543b3ce7b3b26fd8ea98f91ff8eb9aab12a9ba5961b1e3155415b7e51fR217),:
```
    String host = dataSource.getHost();
    // issues#11172: If the worker is in a container, use the container hostname
    // to establish the connection.
    if (!dataSource.getContainerHost().equals("")) {
      host = dataSource.getContainerHost();
    }
```

I'm not sure how you're missing that information.

**Comment by ZhuTopher** [comment]
**UPDATE:** from a working session with @ssz1997 and @jja725 we found that the environment deployed by Fluid does _not_ include the `ALLUXIO_WORKER_CONTAINER_HOSTNAME` variable. Adding it does not resolve the issue though.

**Comment by jja725** [comment]
While using the same env, loadCommand works fine but distributedLoad has a connection issue. Although they are using the same code pattern.

**Comment by ssz1997** [comment]
The reason fluid is not picking up `ALLUXIO_WORKER_CONTAINER_HOSTNAME` is because they set `Worker.HostNetwork` to true. 

By fixing this, Alluxio in Fluid has the environment variable, which is the pod IP, and it is actually different the node IP.

In the job worker log, we see this 
```
2022-02-17 00:17:34,611 INFO  JobUtils - selected dataSource :WorkerNetAddress{host=10.0.6.202, containerHost=10.0.6.195, rpcPort=21710, dataPort=21710, webPort=24562, domainSocketPath=, tieredIdentity=TieredIdentity(node=10.0.6.202, rack=null)}
```
So it know about this env variable. However it still fails with the same error `cannot connect to remote block worker`.

**Comment by jja725** [comment]
```
Caused by: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=10.0.6.202, SocketAddress=hbase-worker-0.hbase-worker.default.svc.cluster.local/10.0.6.195:21710}
	at alluxio.client.block.stream.BlockWorkerClient$Factory.create(BlockWorkerClient.java:62)
	at alluxio.client.block.stream.BlockWorkerClientPool.createNewResource(BlockWorkerClientPool.java:71)
	at alluxio.client.block.stream.BlockWorkerClientPool.createNewResource(BlockWorkerClientPool.java:34)
	at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:327)
	at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:296)
	at alluxio.client.file.FileSystemContext.acquireBlockWorkerClientInternal(FileSystemContext.java:565)
	at alluxio.client.file.FileSystemContext.acquireBlockWorkerClient(FileSystemContext.java:545)
	at alluxio.job.util.JobUtils.loadThroughCacheRequest(JobUtils.java:231)
	... 11 more
Caused by: alluxio.exception.status.UnavailableException: Failed to connect to remote server GrpcServerAddress{HostName=10.0.6.202, SocketAddress=hbase-worker-0.hbase-worker.default.svc.cluster.local/10.0.6.195:21710}. GrpcChannelKey{ClientType=DefaultBlockWorkerClient-Stream, ClientHostname=hbase-worker-0.hbase-worker.default.svc.cluster.local, ServerAddress=GrpcServerAddress{HostName=10.0.6.202, SocketAddress=hbase-worker-0.hbase-worker.default.svc.cluster.local/10.0.6.195:21710}, ChannelId=8c7108b3-7ac0-491f-a7bc-ecb4dbc16323}
```
I think we are using the correct PodId to connect to the worker pod after setting env in fluid but still get a connection error. And we are able to call this address in job worker. And it's fluid specific problem.
@ZhuTopher any thought on this? In the mean time we would let Fluid people aware of this problem as well.

**Comment by ZhuTopher** [comment]
> I think we are using the correct PodId to connect to the worker pod after setting env in fluid but still get a connection error. And we are able to call this address in job worker. And it's fluid specific problem.

Given the above, unfortunately I have no idea what the problem might be. Can you narrow down the exact commit between 2.7.0 and 2.7.2 where this issue presents itself?
- Do some git bisecting (i.e: a binary search) to find the commit; I know it will be slow given that you need to deploy Alluxio in k8s

**Comment by ssz1997** [comment]
@ZhuTopher @jja725 The root cause is Fluid by default set `alluxio.job.worker.threadpool.size` to 164, and in Alluxio the default is 10. The 164 threads seems flooding the connection, which errors out saying `cannot connect to remote block worker`.
I set this property to 10 in Fluid and no more such errors.
@apc999 @yuzhu FYI

**Comment by LuQQiu** [comment]
Why `alluxio.job.worker.threadpool.size= 164` is too big for the new implementation, and relatively reasonable for the old one?

Is it possible that the distributedLoad with 2.7.3 slow while loading millions of small file also related to the unreasonable huge number of connections (grpc threads?)?

**Comment by LuQQiu** [comment]
Close the issue, thanks for the investigation!
