### ISSUE TITLE
Fuse remove file too slow

### ISSUE THREAD

**Issue by ssz1997** [Alluxio/alluxio#14933]
Small-size files (100k) generated with 8 threads in ~ 3 min with fuse stressbench takes more than 30min to delete through POSIX API. Write type is `MUST_CACHE` so UFS is not involved.

**Comment by LuQQiu** [comment]
@ssz1997 what's your remove file command

**Comment by ssz1997** [comment]
Inside the mount point, ran `rm -R /mnt/standalone-fuse-write/threads-8/fuseIOStressbench`

**Comment by LuQQiu** [comment]
Note that linux command is single threaded similar to `cp -R`
there may be multi-thread rm command that's much faster
