### ISSUE TITLE
Is there a good solution to whether spark Shuffle data can be stored in Alluxio

### ISSUE THREAD

**Issue by liangrui1988** [Alluxio/alluxio#14936]
spark shuffle data on alluxio?

https://issues.apache.org/jira/browse/SPARK-25299
Check whether it is stable and available
https://github.com/MemVerge/splash/

What other good solutions can be implemented

**Comment by HelloHorizon** [comment]
@liangrui1988 If you are using a cloud store(or remote storage cluster) with Spark remote shuffle service(no matter which with HDFS interface), it's a good idea to keep the shuffle data in Alluxio for fast access.

**Comment by liangrui1988** [comment]
Spark Shuffle cannot be configured with third-party storage directly, so it needs to be developed by itself. I would like to know if There is any plug-in developed for Alluxio that can be used directly.

**Comment by HelloHorizon** [comment]
@liangrui1988 we don't provide the remote shuffle service plugin from our side. If you are interested in this feature, you can raise issue at the Spark community.
