### ISSUE TITLE
Alluxio CLI code for distributed load and copy always return zero.

### ISSUE THREAD

**Issue by vimalKeshu** [Alluxio/alluxio#14974]
**Is your feature request related to a problem? Please describe.**
I am interacting with the Alluxio form python code by creating the python sub process and executing commands like distributed load and copy. Alluxio code for distributed load and copy always return the zero value even though it couldn't succeed in loading or copying all the files. 
For example, ```Completed count is 203,Failed count is 617.```
Code reference: https://github.com/Alluxio/alluxio/blob/2df1da2d4f6caa47574640bf54c52447e8c0f3ea/shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java#L314
https://github.com/Alluxio/alluxio/blob/2df1da2d4f6caa47574640bf54c52447e8c0f3ea/shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java#L150 
**Describe the solution you'd like**
 If Alluxio code returns the appropriate integer value like -1 (Exception), 0(Successful) or 1(Error) , it would help parent process to take the decision and control the code flow accordingly. For example, in case of distributed load cli command, if Alluxio loads all the files it should return 0 to indicate successful copy; if it loads partial files and failed for other files, it should return 1 to indicate error in copying all the files; if it faces any exception while doing distributed load, it should return -1 to indicate its process abruption.
**Describe alternatives you've considered**
As of now, Alluxio returns the zero value for any situation and prints the line ```Completed count is %d,Failed count is %d.``` on console. I need to take the python sub process output, parse it, find the Failed count and make the decision like whether distributed load succeeded or not.
**Urgency**
Explain why the feature is important
It makes more sense to return appropriate value of the process rather than zero for all the situations. That's how CLI works.
**Additional context**

**Comment by HelloHorizon** [comment]
thanks @vimalKeshu for reporting! @jja725 can you take a look?

**Comment by vimalKeshu** [comment]
@HelloHorizon thank you. let me study the code and come up with the initial PR.

**Comment by jja725** [comment]
@vimalKeshu We are currently designing and implementing the async job submission feature(somehow similar to what you are thinking in the other PR, return the job id and later, external system calls/polls the job status) which would be released in 2.8.0 and the rough timeline would be around April. I feel like there's duplicate work if we plan to update the current distributedLoad CLI response. But really appreciate the proposal!

**Comment by vimalKeshu** [comment]
Hi @jja725 , eagerly waiting for this feature; any update.

**Comment by jja725** [comment]
https://github.com/Alluxio/alluxio/pull/15242 It's near completion. We would update the document after the 2.8 release
