### ISSUE TITLE
Server Configuration Check	FAILED

### ISSUE THREAD

**Issue by liangrui1988** [Alluxio/alluxio#14985]
<html>
<body>

Server Configuration Check | FAILED
-- | --

</body>
</html>
What's wrong with this test?How can it be corrected, without any hint, beyond comprehension

![image](https://user-images.githubusercontent.com/7435076/153329509-0c85b36e-df89-4532-8ac2-1079da626aca.png)

master config

alluxio.master.keytab.file=/data/alluxio/alluxio/conf/liangrui-master01.keytab
alluxio.master.principal=liangrui/_HOST@TESTCLUSTER.COM
alluxio.worker.keytab.file=/data/alluxio/alluxio/conf/liangrui-master01.keytab
alluxio.worker.principal=hdfs/_HOST@TESTCLUSTER.COM

alluxio.master.hostname=fs-testcluster-master01.hiido.host.yydevops.com
alluxio.master.mount.table.root.ufs=hdfs://testcluster/user/alluxio/liangrui
alluxio.master.embedded.journal.addresses=xx19200,xx19200

**Comment by HelloHorizon** [comment]
@LuQQiu can you help here?

**Comment by LuQQiu** [comment]
@liangrui1988 can you try using 
```
# shows server-side configuration errors and warnings
$ ./bin/alluxio fsadmin doctor configuration
```
and see what's the results?
For more details, please refer to https://docs.alluxio.io/os/user/stable/en/operation/Admin-CLI.html#doctor

**Comment by liangrui1988** [comment]
alluxio fsadmin doctor configuration
alluxio.master.keytab.file=/etc/alluxio/conf/alluxio-master01.keytab
alluxio.master.keytab.file=/etc/alluxio/conf/alluxio-master02.keytab

The two configurations have the same requirements and have been corrected.But this is not an exception and should display the prompt specification.Thank you very much
