### ISSUE TITLE
redundent JVM options for worker and job_worker processes

### ISSUE THREAD

**Issue by lynus** [Alluxio/alluxio#14994]
**Alluxio Version:**
2.7.2
**Describe the bug**
Duplicate options are passed to JVM. Using `ps aux|grep Alluxio` to see the process's command
**To Reproduce**
./alluxio-start.sh worker 
./alluxio-start.sh job_worker

**Expected behavior**
No duplicate options, like master and job_master

**Urgency**
low

**Are you planning to fix it**
yes

**Additional context**
no

**Comment by HelloHorizon** [comment]
Thanks for reporting @lynus ! Look forward for your fix :)

**Comment by yabola** [comment]
@lynus @HelloHorizon Do you want to fix it? I can take it.
