### ISSUE TITLE
alluxio remote read slow than read local disk

### ISSUE THREAD

**Issue by wukong1992** [Alluxio/alluxio#14999]
**Alluxio Version:**
2.7.3

**Describe the bug**
I read from local disk and alluxio(cached, I load first!)

from alluxio:

`bash-5.0# time alluxio fs cat /5G.file > /dev/null

real        0m5.791s
user        0m11.820s
sys        0m4.344s`

from local
`bash-5.0# time cat /tmp/5G.file > /dev/null

real        0m1.155s
user        0m0.001s
sys        0m1.154s`

And I test my network bandwidth with iperf:
`[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  26.5 GBytes  22.7 Gbits/sec`

I ensure the cpu is not the bottleneck.

I don't know the alluxio read speed is in line with expectations. And want to know the bottleneck, what should I do.

**Comment by HelloHorizon** [comment]
@wukong1992 please refer to the existing test regards of the speed of RamDisk. Compare to the system call cat, the Alluxio cat is not performance-optimized and we are not focusing on the speed of the cat in most scenarios. If you are interested in Alluxio performance, please refer to https://docs.alluxio.io/os/user/stable/en/operation/StressBench.html
