### ISSUE TITLE
Failed to Build The Project

### ISSUE THREAD

**Issue by dyiopd** [Alluxio/alluxio#15011]
**Alluxio Version:**
What version of Alluxio are you using?
2.7.0

**Describe the bug**
When building the project,  the compiler shows the error that cannot find the symbol Class UfsConstants.
There is no UfsConstants Java file in this project.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
Clone the whole project from GitHub and compile it in Intellij Idea 2021.3.2

**Expected behavior**
Project can be compiled successfully

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by apc999** [comment]
@dyiopd  have you tried running `maven` first out side Intellij.
It may require generating some constants first using certain maven plugins

here is the instruction https://docs.alluxio.io/os/user/stable/en/contributor/Building-Alluxio-From-Source.html
and let me know if this works for you

**Comment by dyiopd** [comment]
It works. Thanks a lot.
