### ISSUE TITLE
 ERROR Format - Failed to format  java.nio.file.AccessDeniedException: /user/alluxio/journal

### ISSUE THREAD

**Issue by liangrui1988** [Alluxio/alluxio#15034]
`2022-02-22 15:24:08,280 DEBUG AlluxioProperties - Property sun.cpu.isalist from source SYSTEM_PROPERTY is unrecognized
2022-02-22 15:24:08,336 INFO  Format - Formatting master journal: hdfs://yycluster02/user/alluxio/journal/
2022-02-22 15:24:08,384 ERROR Format - Failed to format
java.nio.file.AccessDeniedException: /user/alluxio/journal
        at alluxio.master.journal.raft.RaftJournalSystem.format(RaftJournalSystem.java:1104)
        at alluxio.cli.Format.format(Format.java:123)
        at alluxio.cli.Format.main(Format.java:97)`

my config
```
#keytab
alluxio.master.keytab.file=/etc/alluxio/conf/alluxio-master01.keytab
alluxio.master.principal=alluxio/_HOST@YYDEVOPS.COM


alluxio.master.mount.table.root.ufs=hdfs://xxcluster02/user/alluxio/ufs
alluxio.master.embedded.journal.addresses=fs-alluxio-master01.xx:19200,fs-alluxio-master02.xx:19200

#journal
#alluxio.master.journal.folder=hdfs://xxcluster02/user/alluxio/journal
```

**Page**
https://docs.alluxio.io/os/user/2.7.2/cn/deploy/Running-Alluxio-On-a-HA-Cluster.html#%E9%80%89%E9%A1%B91%E5%9F%BA%E4%BA%8Eraft%E7%9A%84%E5%B5%8C%E5%85%A5%E5%BC%8F%E6%97%A5%E5%BF%97
https://docs.alluxio.io/os/user/2.7.2/cn/operation/Journal.html

**Summary**
Hi I ask, how the configuration specified keytab, is invoked in the general configuration alluxio. Master.. Keytab file attribute value?Why is no permission reported after the HDFS log path is specified? If no permission is specified, the startup is normal
![image](https://user-images.githubusercontent.com/7435076/155092017-4b21df81-cd75-48b3-87dc-5ed2368ed10f.png)

![image](https://user-images.githubusercontent.com/7435076/155092050-66f9f1b1-0957-489a-907f-c7e57dfdb129.png)
If Raft embedded logging is enabled, there is no need to configure HDFS shared log path.So how do you keep the master and slave metadata in sync?If the master is not active, the 19999 page cannot be opened at all.What's going on here

<a href="../../en/operation/Journal.html＃embedded-journal-configuration">嵌入式日志配置文档</a>  This is invalid

**Comment by liangrui1988** [comment]
If you kill the master manually or soTP the master, the service will automatically switch to the standby master.Still need what configuration, not configuration alluxio. Master. Journal. Folder = HDFS: under the condition of xx

alluxio fsadmin journal quorum elect -address fs-alluxio-master01.hiido.host.yydevops.com:19200

**Comment by liangrui1988** [comment]
![image](https://user-images.githubusercontent.com/7435076/155447822-0cd2e2d9-38ac-4346-aa53-b52cde412742.png)
After the stop leader master is stopped, the service is unavailable and a new leader is not automatically elected

Failed to get the leader master.

**Comment by HelloHorizon** [comment]
@jenoudet @tcrain can you take a look?

**Comment by liangrui1988** [comment]
I tried to extend another master node, then stopped the master node and switched over normally. Why can't the two nodes be switched over?Do I have to have 3 masters?It doesn't make sense, and then I try to stop another node, but again it doesn't work, so I have to have two master nodes alive to access it.

**Comment by jenoudet** [comment]
In general, we recommend running an odd number of masters (3, 5, 7, etc...) in HA. 
With regards to the `AccessDeniedException`, the EmbeddedJournal uses your local UFS to store its log files. Make sure you have access to that. If you do, we will need more logs to investigate if this issue happens again.

**Comment by liangrui1988** [comment]
> 

3. I've verified that it can be switched.But if you stop one more, you can't cut, which means you have to have two active machines to run the whole cluster, right?If you have to, you'd better document it, otherwise it's a big problem,
