### ISSUE TITLE
AlluxioJobWorker jvm  env parameter configuration

### ISSUE THREAD

**Issue by liangrui1988** [Alluxio/alluxio#15041]
**Page**
https://docs.alluxio.io/os/user/2.7.2/cn/operation/Configuration.html#use-environment-variables

**Summary**
AlluxioJobWorker
MaxHeapSize              = 32210157568 (30718.0MB)

![image](https://user-images.githubusercontent.com/7435076/155291276-fe2c7a76-24f6-42c3-98b7-5b05d1133762.png)

ALLUXIO_JOB_WORKER_JAVA_OPTS="-Xms2g -Xmx4g" ?这样可以吗？

**Comment by liangrui1988** [comment]
I tried it and it worked, but the document should be completed  
 MaxHeapSize              = 4294967296 (4096.0MB)

**Comment by jja725** [comment]
yes, you can use ALLUXIO_JOB_WORKER_JAVA_OPTS to tune the job worker. Thanks for finding this issue in the doc and we would update that soon!
