### ISSUE TITLE
Spark SQL syntax: How to configure cache as ALLuxio as CAHCE storage

### ISSUE THREAD

**Issue by liangrui1988** [Alluxio/alluxio#15069]
Spark SQL syntax, how to configure cache as alluxio as cahCE storage, non-Scala script writing, but pure SQL syntax, because we big data unified platform SQL language, how to configure SQL as alluxio, did not see the related description

https://spark.apache.org/docs/3.0.0-preview/sql-ref-syntax-aux-cache-cache-table.html
Syntax:
CACHE [ LAZY ] TABLE table_name
    [ OPTIONS ( 'storageLevel' [ = ] value ) ] [ [ AS ] query ]

**Comment by HelloHorizon** [comment]
Hey @liangrui1988 , I checked into this doc and it seems to use the Spark internal data structure to store the cached data instead of an external storage system. Can you provide more details what you want to do?

**Comment by liangrui1988** [comment]
`create temporary view product as
select 
  id,
  product_key,
  algo 
from hiidosdk.m_product_view
where is_filter_stat=0
;`
How do I store the data from this temporary table into alluxio?, because our platform is unified SQL, we cannot use RDD Save

**Comment by liangrui1988** [comment]
![image](https://user-images.githubusercontent.com/7435076/156101598-493a1bc3-bbaa-40be-8056-2b3bb670b498.png)

**Comment by HelloHorizon** [comment]
I don't think Apache Spark supports the temp data in an external system, you can check with the Spark community for a more accurate response.
