### ISSUE TITLE
trino skip ufs to access s3 layer directly

### ISSUE THREAD

**Issue by githubjianli** [Alluxio/alluxio#15073]
**Alluxio Version:**
What version of Alluxio are you using?
2.4.1-1
**Describe the bug**
When query against to alluxio table, somehow it will skip to reading data from ufs but directly trying to access the underlying source s3 bucket(we have s3 bucket mounted to ufs already).

Slack thread: (https://alluxio-community.slack.com/archives/CEXGGUBDK/p1646072406054089)

example table describe:
column1  string
column2 string
.
.
.
Location:            alluxio://alluxio-egap-remote.egdp-analytics.aws.away.black:19998/hcom-data-prod-bix-email-crm/email_performance_agg NULL

example table partition describe:
Location:            alluxio://alluxio-egap-remote.egdp-analytics.aws.away.black:19998/hcom-data-prod-bix-email-crm/email_performance_agg/sentdate=2022-02-04

example error logs:
[2022-02-28T12:21:08.265891 #15195] ERROR -- : Command execution failed with exception: Query 20220228_121928_00047_i5smg failed: io.prestosql.spi.PrestoException

Failed to list directory: s3://hcom-data-prod-bix-email-crm/email_performance_agg/sentdate=2022-02-04

io.prestosql.plugin.hive.util.HiveFileIterator$FileStatusIterator.processException(HiveFileIterator.java:178)

io.prestosql.plugin.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:146)</init>

io.prestosql.plugin.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:131)</init>

io.prestosql.plugin.hive.util.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:120)

io.prestosql.plugin.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:113)

io.prestosql.plugin.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:38)

com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)

com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)

java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)

java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)

java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)

java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)

java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)

java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)

io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:296)

io.prestosql.plugin.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:109)

io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:222)

io.prestosql.plugin.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)

io.prestosql.plugin.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)

io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)

io.prestosql.$gen.Presto_____20220228_091734_1.run(Unknown Source)

io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)

java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

java.base/java.lang.Thread.run(Thread.java:834)

Caused by: io.prestosql.plugin.hive.s3.PrestoS3FileSystem.UnrecoverableS3OperationException

com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: VR5T9GYNMDWR843Y; S3 Extended Request ID: ejdIvC6fsbzHJAMeH8Lwzu0eeupE3/cU4XTJ0NAkMjP4eUrTdT7MRi+zqtPrOiXfKhFAy0q44OQ=), S3 Extended Request ID: ejdIvC6fsbzHJAMeH8Lwzu0eeupE3/cU4XTJ0NAkMjP4eUrTdT7MRi+zqtPrOiXfKhFAy0q44OQ= (Path: hcom-data-prod-bix-email-crm/email_performance_agg/sentdate=2022-02-04)

io.prestosql.plugin.hive.s3.PrestoS3FileSystem.lambda$geObjectListing$1(PrestoS3FileSystem.java:614)

io.prestosql.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)

io.prestosql.plugin.hive.s3.PrestoS3FileSystem.geObjectListing(PrestoS3FileSystem.java:596)

io.prestosql.plugin.hive.s3.PrestoS3FileSystem.listPrefix(PrestoS3FileSystem.java:536)

io.prestosql.plugin.hive.s3.PrestoS3FileSystem.access$000(PrestoS3FileSystem.java:131)

io.prestosql.plugin.hive.s3.PrestoS3FileSystem$1.<init>(PrestoS3FileSystem.java:308)</init>

io.prestosql.plugin.hive.s3.PrestoS3FileSystem.listLocatedStatus(PrestoS3FileSystem.java:306)

io.prestosql.plugin.hive.s3.PrestoS3FileSystem.listLocatedStatus(PrestoS3FileSystem.java:299)

org.apache.hadoop.fs.FilterFileSystem.listLocatedStatus(FilterFileSystem.java:283)

io.prestosql.plugin.hive.CachingDirectoryLister.list(CachingDirectoryLister.java:82)

io.prestosql.plugin.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:143)</init>

io.prestosql.plugin.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:131)</init>

io.prestosql.plugin.hive.util.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:120)

io.prestosql.plugin.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:113)

io.prestosql.plugin.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:38)

com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)

com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)

java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)

java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)

java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)

java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)

java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)

java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)

io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:296)

io.prestosql.plugin.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:109)

io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:222)

io.prestosql.plugin.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)

io.prestosql.plugin.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)

io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)

io.prestosql.$gen.Presto_____20220228_091734_1.run(Unknown Source)

io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)

java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

java.base/java.lang.Thread.run(Thread.java:834)

Caused by: com.amazonaws.services.s3.model.AmazonS3Exception

Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: VR5T9GYNMDWR843Y; S3 Extended Request ID: ejdIvC6fsbzHJAMeH8Lwzu0eeupE3/cU4XTJ0NAkMjP4eUrTdT7MRi+zqtPrOiXfKhFAy0q44OQ=)

**Comment by apc999** [comment]
discussed offline. this is due to some consistency issue in the catalog service to use the correct address (s3 vs alluxio)
