### ISSUE TITLE
when just delete PERSISTED file,NOT_PERSISTED file also deleted

### ISSUE THREAD

**Issue by lichar-cheng** [Alluxio/alluxio#15130]
**Alluxio Version:**
2.6.2

**Describe the bug**
has two status file(PERSISTED,NOT_PERSISTED) in path, when delete PERSISTED path,other path also delete

**To Reproduce**
create two statsu file,
one is PERSISTED, other is NOT_PERSISTED
![image](https://user-images.githubusercontent.com/35256099/157574992-dfab3f35-1102-429b-9212-2a7e2afe1657.png)

then,delete PERSISTED file

![image](https://user-images.githubusercontent.com/35256099/157575113-0a390265-7f4a-4fd0-a166-61bb68184792.png)

now,select  parent path,don't exists

![image](https://user-images.githubusercontent.com/35256099/157575209-dfae8b02-9531-49f2-bbad-deba74fe66e8.png)

u can create  file by this way to reproduce two file

![image](https://user-images.githubusercontent.com/35256099/157575418-9dc525b3-0a48-44e1-9737-9589b2b4bf52.png)
 one file write and colse,other don't close

**Expected behavior**
other path also exists when  PERSISTED file deleted

**Additional context**
alluxio.user.file.writetype.default is ASYNC_THROUGH

ufs is minio

**Comment by HelloHorizon** [comment]
@lichar-cheng thanks for the reporting! I think it's the same issue as #14306 , please take a look.

**Comment by lichar-cheng** [comment]
use version 2.7.2 also can reproduce bug, #14307 can't fix

**Comment by HelloHorizon** [comment]
@lichar-cheng do you make any modifications to Alluxio? I can not reproduce your issue at my side

**Comment by lichar-cheng** [comment]
@HelloHorizon 
this is my configmap ,no other change

ALLUXIO_FUSE_JAVA_OPTS: '-XX:MaxDirectMemorySize=2g '
  ALLUXIO_JAVA_OPTS: -Dalluxio.master.hostname=alluxio-master-0 -Dalluxio.user.file.metadata.sync.interval=0
    -Dalluxio.underfs.s3.default.mode=0777 -Dalluxio.master.journal.type=UFS -Dalluxio.master.journal.folder=/journal
    -Dalluxio.underfs.address=s3a://fdp -Dalluxio.underfs.s3.endpoint=http://minio.minio-single.svc.cluster.local:9000
    -Daws.accessKeyId=xxx -Daws.secretKey=xxx
    -Dalluxio.underfs.s3.disable.dns.buckets=true -Dalluxio.underfs.s3.inherit.acl=false
    -Dalluxio.security.login.username=root -Dalluxio.security.authorization.permission.enabled=false
    -Dalluxio.security.authorization.permission.umask=000 -Dalluxio.security.authorization.permission.supergroup=root
    -Dalluxio.user.file.delete.unchecked=true 
    -XX:+PrintGCTimeStamps
  ALLUXIO_JOB_MASTER_JAVA_OPTS: -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME}
    -Dalluxio.master.security.impersonation.root.users=* -Dalluxio.master.security.impersonation.root.groups=*
    -Dalluxio.master.security.impersonation.client.users=* -Dalluxio.master.security.impersonation.client.groups=*
  ALLUXIO_JOB_WORKER_JAVA_OPTS: '-Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME}
    -Dalluxio.job.worker.rpc.port=30001 -Dalluxio.job.worker.data.port=30002 -Dalluxio.job.worker.web.port=30003 '
  ALLUXIO_MASTER_JAVA_OPTS: -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} -Dalluxio.master.security.impersonation.root.users=*
    -Dalluxio.master.security.impersonation.root.groups=* -Dalluxio.master.security.impersonation.client.users=*
    -Dalluxio.master.security.impersonation.client.groups=*
  ALLUXIO_WORKER_JAVA_OPTS: -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} -Dalluxio.worker.rpc.port=29999
    -Dalluxio.worker.network.async.cache.manager.threads.max=8 -Dalluxio.worker.web.port=30000
    -Dalluxio.worker.data.server.domain.socket.address=/data/alluxio-domain -Dalluxio.worker.data.server.domain.socket.as.uuid=true
    -Dalluxio.worker.container.hostname=${ALLUXIO_WORKER_CONTAINER_HOSTNAME} -Dalluxio.worker.memory.size=2G
    -Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.alias=MEM
    -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=MEM -Dalluxio.worker.tieredstore.level0.dirs.path=/dev/shm
    -Dalluxio.worker.tieredstore.level0.dirs.quota=1G -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95
    -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7
  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: /dev/shm

**Comment by lichar-cheng** [comment]
i try to change use oss ufs ,configmap change to
-Dalluxio.master.mount.table.root.ufs=oss://XXX -Dfs.oss.endpoint=XXX
    -Dfs.oss.accessKeyId=XXX -Dfs.oss.accessKeySecret=XXX

can't reproduce this issue

**Comment by lichar-cheng** [comment]
upgrade minio version to minio/minio:RELEASE.2021-12-09T06-19-41Z fix bug
