### ISSUE TITLE
Need some suggestion in limiting GC rate/Memory usage

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#15183]
**Alluxio Version:**
2.7.2

**Describe the bug**
When training with large scale of files, there are excessive master gc happen, which induce bad performance in reading.
In the former case, uplifting GCThread and Jvm max memory can really help resolve this issue, but in this case we have uplift memory to half of the node but still excessive gc is observed.

We need help in below two fields:
1. immediate suggestion on limiting gc rate/memory usage
1.1 suggestion on config
1.2 suggestion on file struct / usage
2. Investigation and make fix/feature on limit memory

Detailed information:
Jvm memory usage:
![企业微信截图_61ff88ed-2343-468c-912c-880fb097497f](https://user-images.githubusercontent.com/11472213/159251112-d103f833-a5b8-4a84-8184-19f9e635ace5.png)
Jvm memory usage:
![image](https://user-images.githubusercontent.com/11472213/159251170-6f6bfa3b-fc1e-4a12-b404-384f7513ab2d.png)

Master log:
[alluxio-audf-master.log](https://github.com/Alluxio/alluxio/files/8316278/alluxio-audf-master.log)

Master jmap:
[jmap-audf.txt](https://github.com/Alluxio/alluxio/files/8316279/jmap-audf.txt)

**Comment by Nizifan** [comment]
Some description about user's files:
Total directory: 5121
Total files: 10559774
Single file size: 156.25k
Directory depth: 5121

**Comment by LuQQiu** [comment]
@Nizifan can you help provide the detailed information about 
- cluster setup: how many masters and how many workers
- CPU/memory resources for each master/worker node or pod
- cluster configuration
- what kind of training workloads it's

**Comment by kevincai** [comment]
JDK11 + G1GC might worth a try.

**Comment by Nizifan** [comment]
The config is:
128Gi memory master * 1 + 400 Gi quota worker * 5.

Configuration is below:
[audf-config.txt](https://github.com/Alluxio/alluxio/files/8320810/audf-config.txt)

Training workload is generation training, training each data randomly for certain rounds of epoch.

**Comment by Nizifan** [comment]
I will try use G1GC parameter suggested by @kevincai

**Comment by Nizifan** [comment]
Many thanks for suggestion from @kevincai 
Change to G1GC + Jdk11 indeed improve gc performance, from the log I can see both gc time and gc frequency limited to a very low value compared to before.
The frequency drop from ~10 times/hour to ~1time/hour
The gc time from 30~60s drop to 1~2s

@LuQQiu shall we consider making those configuration as "suggested" or "default"

**Comment by LuQQiu** [comment]
@Nizifan @kevincai Thanks for the recommendation. We will prioritize improving the POSIX API doc to document the recommended configuration for different datasets.
Now we are in the testing phrase to get more confidence of the recommendation

**Comment by theMYang** [comment]
https://github.com/Alluxio/alluxio/issues/15210

**Comment by Nizifan** [comment]
We run a higher stake test and reading speed reach 2x compared to before. We will apply jdk11 + g1gc option to all new created Alluxio instance.
