### ISSUE TITLE
the block size configuration is not working

### ISSUE THREAD

**Issue by SansiroWang** [Alluxio/alluxio#15192]
**Alluxio Version:**
2.7.3

**Describe the bug**
we set the block size configuration like this(master and worker both set):
alluxio.user.block.size.bytes.default=128MB
and run the command below:
./bin/alluxio runTests
then i check the file in alluxio, the  file's block size is 128MB,like below:

File Name | Size | Block Size | In-Alluxio | Mode | Owner | Group | Persistence State | Pin | Creation Time | Modification Time
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
| /default_tests_files/BASIC_CACHE_ASYNC_THROUGH | 80B | **128.00MB** | 100% | -rw-r--r-- | hdfs| hdfs| PERSISTED | NO | 03-24-2022 01:55:40:556 | 03-24-2022 01:55:40:563

But if i run hadoop test teragen, the file's block size is 64MB

File Name | Size | Block Size | In-Alluxio | Mode | Owner | Group | Persistence State | Pin | Creation Time | Modification Time
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
| /terasort/input-3G/part-m-00019 | 1324.55MB | **64.00MB** | 100% | -rw-r--r-- | ansible | ansible | PERSISTED | NO | 03-24-2022 01:13:06:400 | 03-24-2022 01:13:17:893

I check the config of alluxio.user.block.size.bytes.default in CLI and web console, it is  both 128MB actualy

**Comment by SansiroWang** [comment]
more info:
we use HDFS 2.10.1 as the ufs of alluxio, and the default block size of HDFS 2.10.1 is **128MB**

**Comment by HelloHorizon** [comment]
Hey @fuzhengjia @beinan can you help here?

**Comment by HelloHorizon** [comment]
@SansiroWang If you want to set up the block size for your MapReduce application, you also need to update the configuration `alluxio.user.block.size.bytes.default` in `core-site.xml`. And remember to restart your Hadoop cluster after you change the configuration file. https://docs.alluxio.io/os/user/stable/en/compute/Hadoop-MapReduce.html#customize-alluxio-user-properties-for-all-mapreduce-jobs

**Comment by SansiroWang** [comment]
problem solved.
tks
