### ISSUE TITLE
Solve memory problems in high concurrency for Alluxio master

### ISSUE THREAD

**Issue by theMYang** [Alluxio/alluxio#15210]
**Alluxio Version:**
2.6.2

**Describe the bug**
Master heap memory grows rapidly in high concurrent request.  Full GC is very frequent. Young GC and Full GC takes a lot of time give rise to failover to another master.

- Young GC cost time
![ygc](https://user-images.githubusercontent.com/16862184/160224353-26caf0ed-1327-431e-aae2-787ac6f8aac2.png)

- Full GC cost time
GC cost 28 seconds give rise to failover to another master.
![fgc](https://user-images.githubusercontent.com/16862184/160224415-8292c79c-d30a-48d7-b918-d56df7fe8c04.png)

Here's how I solved this problem.

**Problem Analysis & Solving**
Two problems were identified.
1. There are a lot of Finalizer objects! This is the key to the memory problems!!! Object `rocksdb/AbstractNativeReference` in RocksDB JNI implements method of `finalize`.  This resulted in instances that could not be collected in a timely manner And has a great impact on the efficiency of GC. 
![fin](https://user-images.githubusercontent.com/16862184/160224568-00aac0f4-7ae3-4b60-a295-ffc4cec21be4.png)

A large number of Finalizer instances cannot be GC in time. According to the dynamic age algorithm, objects will enter the old generation at a very young age.
![old](https://user-images.githubusercontent.com/16862184/160225292-24689d3b-1eb6-411c-ac84-dd5970093966.png)

***Bug Fix***
I recompile the RocksDB JNI without Finalizer and it looks good to me.

2. memory leakage
Object ReadOptions, Slice of RocksDB are not closed in `RocksBlockStore` and `RocksInodeStore`.
![rock](https://user-images.githubusercontent.com/16862184/160224854-ca23586a-6483-4788-adfd-798931243b35.png)

**Comment by HelloHorizon** [comment]
@theMYang Thanks for reporting! @jiacheliu3 @yuzhu do you aware if this issue and can you take a look?

**Comment by HelloHorizon** [comment]
FYI @LuQQiu

**Comment by jiacheliu3** [comment]
@theMYang Could you try 2.7.3? We have fixed the RocksDB object leak in that version.

Do you have suggestion on the Finalizer? According to discussion in https://github.com/facebook/rocksdb/issues/9378, RocksJava currently relies on Finalizer and they may change to implementing some internal logic to replace finalizer in later versions. I don't know of a way to avoid using Finalizers at this stage.

**Comment by theMYang** [comment]
@jiacheliu3 I just recompile the RocksDB JNI without Finalizer and it looks good to me.

**Comment by HelloHorizon** [comment]
@theMYang I don't think it's a compile issue but a bridge issue from Java to native land. If we don't use Finalizer the Rocks will not hold the reference and JVM can GC the object which we don't want to release. You can check into adam's explanation for more details https://github.com/facebook/rocksdb/issues/9378#issuecomment-1015401139. We will keep an eye on Rocks' updating and optimize this memory usage in the future.
