### ISSUE TITLE
Inode should store Fingerprint as a proto rather than String

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#15211]
**Summary**
Inode stores the fingerprint in `mUfsFingerprint`. So every time we want to check or update this field, excessive String parsing and concatenation have to be done. In order to reduce String usage (reduce creation of Strings and temp variables), we can store the fingerprint as a proto instead, so we only need to update fields.

**Urgency**
MEDIUM

**Comment by elega** [comment]
finger print is just a string.. highly doubt if it can be stored as a proto. Close the issue for now and feel free to reopen if you have further information.
