### ISSUE TITLE
Does mpp database like greenPlum is supported by alluxio at now?

### ISSUE THREAD

**Issue by dark-tea** [Alluxio/alluxio#15230]
we want use alluxio and mpp database to build a efficient data search system, 
so we want to know does alluxio can connect with mpp database？
and does the feature of mpp database is well combined with alluxio?
How can I use it ?

**Comment by HelloHorizon** [comment]
@dark-tea which MPP engine are you using?

**Comment by dark-tea** [comment]
we are using greenplum

**Comment by dark-tea** [comment]
> @dark-tea which MPP engine are you using?

we are using greenplum

**Comment by HelloHorizon** [comment]
@dark-tea you can check with Greenplum to see if they support the HDFS Java client, if that is the case, Alluxio should support Greenplum.
