### ISSUE TITLE
fuse oom failed to remount

### ISSUE THREAD

**Issue by liugs0213** [Alluxio/alluxio#15248]
**Alluxio Version:**
2.8.0

**Describe the bug**
fuse oom After restart, tf job cannot mount new fuse.
According to:
![image](https://user-images.githubusercontent.com/55676558/161192613-95abbeaf-c39f-4baa-a8ae-e4234f13162d.png)

**To Reproduce**
1.Start a TF job to read data in Alluxio.
![image](https://user-images.githubusercontent.com/55676558/161192929-1142f553-0fd9-44c3-82f8-1de855ee6223.png)
![image](https://user-images.githubusercontent.com/55676558/161193267-ac801658-b33d-4b01-a871-2695b258ac94.png)
2.Fuse OOM mounted by TF job (can delete)
3.Access the directory where FUSE is mounted
![image](https://user-images.githubusercontent.com/55676558/161193417-44131e7f-73c6-4535-a860-2541038981a0.png)

**Expected behavior**
After the new FUSE is up, open the same path file to read, and this should be successful

**Comment by HelloHorizon** [comment]
@LuQQiu ptal

**Comment by ssz1997** [comment]
@liugs0213 Need to clarify a few things here:
1. Seems like your tf job was running in k8s. How did you set up the Alluxio cluster? Is your Alluxio cluster also running in a k8s pod? Or is it on the bare machine? Or any other kind of setup?
2. If AlluxioFuse process is in k8s pod, did the pod restart itself, or you manually restarted it? If AlluxioFuse process is running on bare machine, did the process restart by some kind of script, or did you manually run the fuse mount command to remount Alluxio?
Thanks.

**Comment by LuQQiu** [comment]
@liugs0213 I guess the old mount point is not cleaned up, do you have new Fuse logs when the new Fuse pod is up?

**Comment by LuQQiu** [comment]
@liugs0213 can you add the detailed alluxio commit  number if possible, want to confirm whether OOM is related to https://github.com/Alluxio/alluxio/issues/15295

**Comment by liugs0213** [comment]
> 

![image](https://user-images.githubusercontent.com/55676558/162867311-d571923e-cfc7-426f-8d66-1d7ef2f4a6e6.png)
Fuse logs are fine after being restarted

**Comment by yyongycy** [comment]
So the scenario is two different PODs, one is FUSE pod, the other the POD running TF jobs?
And the FUSE POD restarts and works correctly in the new FUSE POD, while the mont point is not accessible in the TF POD.

I am assuming the mount is bidirection bind, right?

**Comment by LuQQiu** [comment]
@liugs0213 can you help see if it can be reproduced in raw linux environment?
@ssz1997 would it happens because of the kubernetes settings of bidirectional mount?

**Comment by LuQQiu** [comment]
For the fuse OOM issue or any other OOM related issues, it will be good if we can get a memory dump to analyze from.
In plain Alluxio install, alluxio can set the JAVA opts to dump memory when OOM to local filesystem path.
```
-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/alluxio/heap/alluxio_master_pid.hprof 
```

**Comment by liugs0213** [comment]
> For the fuse OOM issue or any other OOM related issues, it will be good if we can get a memory dump to analyze from. In plain Alluxio install, alluxio can set the JAVA opts to dump memory when OOM to local filesystem path.
> 
> ```
> -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/alluxio/heap/alluxio_master_pid.hprof 
> ```

Fuse task of quick OOM has not been found, it may be sent to you later

**Comment by liugs0213** [comment]
> @liugs0213 can you help see if it can be reproduced in raw linux environment? @ssz1997 would it happens because of the kubernetes settings of bidirectional mount?

Sorry, not very well reproduced in the Linux raw environment, involving CSI and fluid

**Comment by liugs0213** [comment]
> So the scenario is two different PODs, one is FUSE pod, the other the POD running TF jobs? And the FUSE POD restarts and works correctly in the new FUSE POD, while the mont point is not accessible in the TF POD.
> 
> I am assuming the mount is bidirection bind, right? I am expecting to clarify the exact environment. Whether this is related to the raw linux environment, or it is related to the container.

Sorry, it is not very good to reappear in Linux raw environment, involving CSI, mount PVC and fluid, currently suspected tf job abnormal endpoint not connect that is due to the process responsible for fuse, did not umount the point before dying.

**Comment by yyongycy** [comment]
A few tips to reproduce, in your environment, the fuse is killed by OOM, but you can try to manually kill the process by `kill -9 fuse_process`, that can also simulate the same.

Then after remount, you can check if the problem is same.

Another thing is to check your k8s environment, how is your fuse mount point mapped in the TF? is it bidirection mount?

**Comment by liugs0213** [comment]
> A few tips to reproduce, in your environment, the fuse is killed by OOM, but you can try to manually kill the process by `kill -9 fuse_process`, that can also simulate the same.
> 
> Then after remount, you can check if the problem is same.
> 
> Another thing is to check your k8s environment, how is your fuse mount point mapped in the TF? is it bidirection mount?

Yes, I can stably reproduce by delete Fuse Pod,
Tfjob is connected by mounting
![image](https://user-images.githubusercontent.com/55676558/163121745-abce7e7d-4e63-4c26-946e-11b2d24e985a.png)

**Comment by yyongycy** [comment]
What is your parameter to mount the fuse mount point into your TF pod? 
Not sure if you can try the following option:
  - mountPath: /runtime-mnt/alluxio/ai/rec-data-295188
   mountPropagation: Bidirectional
   name: alluxio-fuse-mount-0

**Comment by liugs0213** [comment]
> What is your parameter to mount the fuse mount point into your TF pod? Not sure if you can try the following option:
> 
> * mountPath: /runtime-mnt/alluxio/ai/rec-data-295188
>   mountPropagation: Bidirectional
>   name: alluxio-fuse-mount-0
It's consistent with what you said
![image](https://user-images.githubusercontent.com/55676558/163124822-e6309ed3-93c2-4a40-b5c2-7792ee33b755.png)

**Comment by yyongycy** [comment]
how about trying both Bidirectional.

**Comment by liugs0213** [comment]
> how about trying both Bidirectional.
Ok, I'll try

**Comment by yyongycy** [comment]
So this problem in essential is a configuration issue. Not specific to the alluxio-fuse.
