### ISSUE TITLE
What causes io.grpc.StatusRuntimeException: UNAUTHENTICATED: Channel: xx is not authenticated for call: yyy?

### ISSUE THREAD

**Issue by living42** [Alluxio/alluxio#15373]
**Alluxio Version:**
2.7.4

I'm not sure this is a bug, but i just wondering why it happens.

For long time, i notice Alluxio constantly report this Exception, for most of time, it does not cause any issue, but recently i found critical one that could interrupt automatic snapshot, and the Master_JournalEntriesSinceCheckPoint is ever growing, in this case, the only choice i found was to switch leadership.

<img width="1901" alt="image" src="https://user-images.githubusercontent.com/3095390/163915485-db7d1610-8df5-4e45-bdba-595bab2dc838.png">

![image](https://user-images.githubusercontent.com/3095390/163915602-2528ea0f-795b-47a0-8f50-89a6ed7e8ba2.png)

**Comment by jenoudet** [comment]
This is caused by some gRPC streams being closed improperly / too early. Some steps have been taken in the upcoming 2.8 release which greatly improve the checkpointing process. Some corner cases have been observed to still occur, however, although rarely.

**Comment by living42** [comment]
@jenoudet thank you for the response, i have upgraded to 2.8.0 a couple week ago and it solved my problem, despite there still some UNAUTHENTICATED occasionally, by my cluster runs pretty stable. i am very happy with that, thank you all.
