### ISSUE TITLE
Support setting MAX_IDLE_THREADS in libfuse3

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#15453]
**Is your feature request related to a problem? Please describe.**
Support setting MAX_IDLE_THREADS in libfuse 3

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by ssz1997** [comment]
@LuQQiu Seems -o options can set max_idle_threads. This can be closed I think.
