### ISSUE TITLE
listStatus should update files' lastSyncTime under the directory for HDFS

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#15486]
**Is your feature request related to a problem? Please describe.**

When ufs is hdfs, listStatus a directory
1. syncs and updates meta data of files under it
2. does not updates lastSyncTime of files under it

These causes accessing a file under the directory just after listStatus needs to sync meta once more.

Below is an example with alluxio.user.file.metadata.sync.interval=5m

```
// 1. the meta data of the file is outdated
$ bin/alluxio fs ls -Dalluxio.user.file.metadata.sync.interval=-1 /nginx/master.log
-rw-rw-r--  alluxio   alluxio   2036694       PERSISTED 04-29-2022 12:18:00:414 100% /nginx/master.log

// 2. listStatus on the directory
$ bin/alluxio fs ls /nginx
-rw-rw-r--  alluxio   alluxio   2037635       PERSISTED 04-29-2022 12:22:22:016   0% /nginx/master.log

// 3. check audit log at hdfs side
$ tail hdfs-audit.log|grep nginx
2022-04-29 12:26:50,818 INFO FSNamesystem.audit: allowed=true   ugi=... ip=... cmd=getfileinfo src=.../nginx
2022-04-29 12:26:50,821 INFO FSNamesystem.audit: allowed=true   ugi=... ip=... cmd=listStatus  src=.../nginx

// 4. check meta data of the file at alluxio side, it is updated
$ bin/alluxio fs ls -Dalluxio.user.file.metadata.sync.interval=-1 /nginx/master.log
-rw-rw-r--  alluxio   alluxio   2037635       PERSISTED 04-29-2022 12:22:22:016   0% /nginx/master.log

// 5. access the file with normal style
$ bin/alluxio fs ls /nginx/master.log
-rw-rw-r--  alluxio  alluxio    2037635       PERSISTED 04-29-2022 12:22:22:016   0% /nginx/master.log

// 6. check audit log at hdfs side, find the meta data of the file synced once more
$ tail hdfs-audit.log|grep nginx
2022-04-29 12:27:06,947 INFO FSNamesystem.audit: allowed=true   ugi=... ip=..  cmd=getfileinfo src=.../nginx/master.log
```

**Describe the solution you'd like**
listStatus should also update lastSyncTime of files under the directory.

**Describe alternatives you've considered**
No

**Urgency**
This can improve the performance of AlluxioMaster.

**Additional context**
Testing based on alluxio-2.7.1

**Comment by secfree** [comment]
@jiacheliu3 @tcrain  can you help assess if this is needed? Thank you.

**Comment by secfree** [comment]
>>>> When a child is checked, UfsSyncPathCache.shouldSyncPath() checks parents of this child. So if the user performs a full sync on /dir, then checks /dir/file, the latter sync will be skipped correctly.

>>> It seems that this is not implemented yet, it needs this feature #15486

>> This is in ... but that can just be a bug in UfsSyncPathCache

> Thanks for your help. I will verify it.

(from: https://github.com/Alluxio/alluxio/pull/15277#issuecomment-1119316301)

Checked the code and did a test, this only works if the "ls" operation for the directory has the "recursive" option. @jiacheliu3

**Comment by secfree** [comment]
@jiacheliu3 May I know

1. Why I know why SyncTime.mLastRecursiveSyncMs is needed besides SyncTime.mLastSyncMs?
2. Is it ok to update mLastRecursiveSyncMs of the first level children after listStatus the directory without "recursive" option?

**Comment by secfree** [comment]
> @jiacheliu3 May I know
> 
> 1. Why is SyncTime.mLastRecursiveSyncMs needed besides SyncTime.mLastSyncMs?
> 2. Is it ok to update mLastRecursiveSyncMs of the first level children after listStatus the directory without "recursive" option?

Checked the code and learned that I had misunderstanding about updating `mLastRecursiveSyncMs`. Setting `mLastRecursiveSyncMs` of the directory is faster than updating all its offsprings, so it is needed.

Please ignore the above two questions here.  Sorry for the inconvenience.

**Comment by jiacheliu3** [comment]
Thanks for the question. Seems the `mLastRecursiveSyncMs` is updated when `DescendantType.ALL`. So `DescendantType.ONE` is actually quite ambiguous here. 

From a Unix/Linux FS perspective, the direct children list is part of the directory metadata. So updating the directory metadata and the direct children both count as updating the directory (not recursive). That sounds fine, just a bit counter-intuitive at the first sight.

WDYT? @yuzhu @tcrain @secfree

**Comment by secfree** [comment]
> Thanks for the question. Seems the `mLastRecursiveSyncMs` is updated when `DescendantType.ALL`. So `DescendantType.ONE` is actually quite ambiguous here.
> 
> From a Unix/Linux FS perspective, the direct children list is part of the directory metadata. So updating the directory metadata and the direct children both count as updating the directory (not recursive). That sounds fine, just a bit counter-intuitive at the first sight.
> 
> WDYT? @yuzhu @tcrain @secfree

If the directory has a lot of children, updating all of them may be expensive. Is it ok to add another field like `mLastChildrenSyncMs` to `UfsSyncPathCache.SyncTime`?

**Comment by jiacheliu3** [comment]
> If the directory has a lot of children, updating all of them may be expensive. Is it ok to add another field like `mLastChildrenSyncMs` to `UfsSyncPathCache.SyncTime`?

@secfree Good question. If we are updating all the children's `SyncTime.mLastSyncTimeMs`, then yes adding the field `mLastChildrenSyncMs` will definitely make sense. However I don't find where we are doing that, I only see here we update the parent's sync time.
https://github.com/Alluxio/alluxio/blob/e26e635d50419879cdf2c48d0ad84f12fe0aa12d/core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java#L441

Please correct me if I'm wrong :)

**Comment by secfree** [comment]
Yes, you are right. The current implementation of listStatus only update the directory's sync time, but not its children.

However, if we want to avoid accessing ufs for the file (just under the directory) once again just after listStatus, we may need to do one of the following options
1. Update children's sync time
2. Add `mLastChildrenSyncMs` field
3. Other options ...

**Comment by secfree** [comment]
#16081 updates the metadata of children if listStatus the directory prefetched the metadata, so I will close this issue.
