### ISSUE TITLE
Alluxio Helm Chart tarball does not include helm-generate.sh

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#15548]
**Is your feature request related to a problem? Please describe.**
When I directly download the Alluxio Helm Chart tarball from Alluxio's helm chart download address
```
$ curl https://alluxio-charts.storage.googleapies.com/openSource/2.8.0/alluxio-0.6.40.tgz > ./foo.tgz
```
This helm chart tarball does not include the `helm-generate.sh` for me to manually create my YAMLs. I will have to download the full Alluxio tarball and find that. This is a bit inconvenient.

```
➜  alluxio ls -alR
total 104
drwxr-xr-x@  8 jiacheng  staff    256 May 12 14:36 .
drwx------@ 64 jiacheng  staff   2048 May 12 14:36 ..
-rw-r--r--   1 jiacheng  staff    333 Apr 27 15:11 .helmignore
-rw-r--r--   1 jiacheng  staff   6649 Apr 27 15:11 CHANGELOG.md
-rw-r--r--   1 jiacheng  staff    365 Apr 27 15:11 Chart.yaml
-rw-r--r--   1 jiacheng  staff  12821 Apr 27 15:11 README.md
drwxr-xr-x   9 jiacheng  staff    288 May 12 14:36 templates
-rw-r--r--   1 jiacheng  staff  19210 Apr 27 15:11 values.yaml
```

**Describe the solution you'd like**
The helm chart tarball should include the `helm-generate.sh`.

**Describe alternatives you've considered**

**Urgency**
LOW

**Additional context**

**Comment by jiacheliu3** [comment]
fyi @ssz1997 @ZhuTopher

**Comment by jiacheliu3** [comment]
I think you can just move a few files
```
-rw-r--r--  1 jiacheng  staff   3.0K Mar  9 20:37 CSI_README.md
-rw-r--r--  1 jiacheng  staff   3.7K Mar  9 20:37 README.md
drwxrwxrwx  4 jiacheng  staff   128B Mar  9 20:37 helm-chart <- This is the helm chart tarball base
-rwxrwxrwx  1 jiacheng  staff   9.3K Dec 12 16:59 helm-generate.sh
```

You can just move the files outside `helm-chart/` into it.

**Comment by jiacheliu3** [comment]
@ssz1997 can this be closed?

**Comment by ssz1997** [comment]
Solved by https://github.com/Alluxio/alluxio/pull/15637
