### ISSUE TITLE
Speed ​​up rocksdb checkpoint

### ISSUE THREAD

**Issue by adol001** [Alluxio/alluxio#15672]
**Is your feature request related to a problem? Please describe.**
We now store 10 billion alluxio inode metadata using rocksdb. The current alluxio checkpoint will tar.gz rocksdb data file by single thread, alluxio restart or re-election leader will untar.gz by single thread. This speed is not fast.

**Describe the solution you'd like**
To divide the rocksdb data into parts and tar.gz each part separately, so that rocksdb write to checkpoint or restore from checkpoint can speed up the speed

**Comment by adol001** [comment]
In addition to checkpoint, backup is also single-threaded gz. It should also be optimized too.

**Comment by yuzhu** [comment]
@jenoudet FYI as well.

**Comment by adol001** [comment]
Refine checkpoint by Parallel zip compression and decompression
https://github.com/Alluxio/alluxio/pull/16151

The current implementation of backup, instead of executing backup, it is better to reload it
