### ISSUE TITLE
Unable to open Fuse file with O_WRONLY|O_RDWR

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#15842]
**Alluxio Version:**
Master

**Describe the bug**
pjdfstest open/23.t
```
expect 0 create ${n0} 0644
expect "0|EINVAL" open ${n0} O_RDONLY,O_RDWR
expect "0|EINVAL" open ${n0} O_WRONLY,O_RDWR
expected 0|EINVAL, got EIO
```
Flag: 0x8003
```
      switch (OpenFlags.valueOf(flags & O_ACCMODE.intValue())) {
        case O_RDONLY:
          return FuseFileInStream.create(mFileSystem, uri, flags, status);
        case O_WRONLY:
          return FuseFileOutStream.create(mFileSystem, mAuthPolicy, uri, flags, mode, status);
        case O_RDWR:
          return FuseFileInOrOutStream.create(mFileSystem, mAuthPolicy, uri, flags, mode, status);
        default:
          throw new RuntimeException(String.format("Cannot create file stream with flag 0x%x. "
              + "Alluxio does not support file modification. "
              + "Cannot open directory in fuse.open().", flags));
      }
```
fall to default with 0x8003, O_ACCMODE

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by yyongycy** [comment]
This is to open a file for read and write at the same time.

**Comment by LuQQiu** [comment]
@yyongycy then it should be processed just like O_RDWR which we can only do read-only or write-only by first read/write operation
