### ISSUE TITLE
Overwrite a read-only permission file succeed

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#15878]
**Alluxio Version:**
2.7.1

**Describe the bug**
Overwrite a read-only permission file succeed.

**To Reproduce**

```
$ echo hello > test_file
$ ll test_file
-rw-rw-r-- 1 test test 6 Jul 13 11:55 test_file
$ chmod 400 test_file
$ ll test_file
-r-------- 1 test test 6 Jul 13 11:55 test_file

$ echo hello > test_file
$ ll test_file
-rw-r--r-- 1 test test 6 Jul 13 11:56 test_file
```

We can found that the original file was deleted and a new file created with default permission.

**Expected behavior**
Failed with "Permission denied" as the local filesystem.

**Urgency**
ACL does not take effect

**Are you planning to fix it**
Yes

**Comment by yyongycy** [comment]
could you try with mount option "default_permission"?

**Comment by yyongycy** [comment]
@LuQQiu  Any comment here?

**Comment by secfree** [comment]
> could you try with mount option "default_permission"?

`default_permissions` works, thanks a lot @yyongycy
