### ISSUE TITLE
Cannot persist an empty directory

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#15896]
**Alluxio Version:**
2.7.1

**Describe the bug**
Cannot persist an empty directory in alluxio to UFS.

**To Reproduce**

```
$ ./bin/alluxio fs ls /projects |grep test_dir
drwxrwxr-x  test   test                 0   NOT_PERSISTED 07-16-2022 15:45:32:035  DIR /projects/test_dir
$ ./bin/alluxio fs persist /projects/test_dir
Found 0 files to persist.
$ ./bin/alluxio fs ls /projects|grep test_dir
drwxrwxr-x  test   test                 0   NOT_PERSISTED 07-16-2022 15:45:32:035  DIR /projects/test_dir
```

**Expected behavior**
The empty directory can persist to UFS.

**Urgency**
Normal

**Are you planning to fix it**
Yes

**Comment by HelloHorizon** [comment]
Thanks @secfree for reporting. @yuzhu @apc999 I remember we intend not to persist the empty directory to UFS, do you know the reason behind it?

**Comment by HelloHorizon** [comment]
@secfree Alluxio intends not to persist the empty directory since the object store doesn't have the concept of the directory. If Alluxio has to persist the directory, Alluxio has to create a temp(?) file in UFS. 

We can see how we can persist the empty file if it's a non-object store system.

**Comment by secfree** [comment]
> 

In the source code of alluxio, it creates an empty object for each directory in object storages. Please check "ObjectUnderFileSystem#mkdirs -> ObjectUnderFileSystem#mkdirsInternal -> S3AUnderFileSystem#createEmptyObject" .

Now alluxio only persists a directory only persisting a file, but it does creates an object in UFS. Is it ok to persist the directory actively? @HelloHorizon

**Comment by HelloHorizon** [comment]
Yup, Allxuio creates an object if the user wants to create the file in the object under the file system. However, the persist is a different operation only persist the file. I think it makes sense to persist the directory if UFS is HDFS in your case. @yuzhu any opinion?

**Comment by secfree** [comment]
> In the source code of alluxio, it creates an empty object for each directory in object storages.

Let me share more details. After creating a file under `/projects/test_dir`, alluxio creates two keys in UFS(ozone)
1. key = "test_dir/", value = ""(empty value)
2. key = "test_dir/file.1", value = "..."

Are there any problems if alluxio creates the key "test_dir/" with an empty value in the under object storage system before the user creats a file under the directory?

**Comment by HelloHorizon** [comment]
I have not sure how ozone implements in their data structure. But normally object store don't have the concept of folders, directories, files, or any hierarchies that you would normally see in a file-based system. Thus for S3 it's impossible to create an empty folder without any object. We have to create a placeholder object in the object store to make sure we can maintain the empty directory in the Alluxio namespace.

**Comment by secfree** [comment]
It is ok for us to create an empty file under the directory to get around this issue, so I will just close this.
