### ISSUE TITLE
Can not get attribute without the read permission of files in fuse

### ISSUE THREAD

**Issue by Haoning-Sun** [Alluxio/alluxio#15936]
**Alluxio Version:**
master

**Describe the bug**
When using alluxio fuse, if the current user does not have read permission to the file, the attribute of the file cannot be obtained.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/13930429/180378353-a311ae93-a6e6-4e85-a3de-25901a311885.png">

![image](https://user-images.githubusercontent.com/13930429/180378484-bd35baf9-bfc7-4491-a647-8b01f27854e2.png)

In the local file system, the current user needs read and execute permission on the parent directory of the file to obtain the attribute, and does not need to have any permission on the file.
![image](https://user-images.githubusercontent.com/13930429/180375729-870422b9-e54a-4ce7-8d22-c9275153f45c.png)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
Using alluxio fuse has the same performance as the local file system.

**Urgency**
Urgency.

**Are you planning to fix it**
Yeah.

**Additional context**
no.

**Comment by LuQQiu** [comment]
Thanks for the debugging!
From my POSIX tests comparing EXT4 and Alluxio Fuse
- EXT4 allows getting status of file/dir with all kinds of permissions but Alluxio Fuse requires read permission to get file/dir status.
- EXT4 does not require the parent folder has any permission to get the inner file status

```
[root@Ec2Cluster-worker-0 myex]# mkdir folder
[root@Ec2Cluster-worker-0 myex]# touch folder/file
[root@Ec2Cluster-worker-0 myex]# ls -al folder/file
-rw-r--r--. 1 root root 0 Jul 25 23:42 folder/file
[root@Ec2Cluster-worker-0 myex]# chmod 000 folder/file
[root@Ec2Cluster-worker-0 myex]# ls -al folder/file
----------. 1 root root 0 Jul 25 23:42 folder/file
[root@Ec2Cluster-worker-0 myex]# ls -al folder
total 8
drwxr-xr-x. 2 root root 4096 Jul 25 23:42 .
drwxr-xr-x. 4 root root 4096 Jul 25 23:42 ..
----------. 1 root root    0 Jul 25 23:42 file
[root@Ec2Cluster-worker-0 myex]# ls -al
total 24
drwxr-xr-x. 4 root root  4096 Jul 25 23:42 .
drwxr-xr-x. 4 root root    38 Jul 25 23:38 ..
drwxr-xr-x. 2 root root  4096 Jul 25 23:42 folder
drwx------. 2 root root 16384 Jul 25 23:38 lost+found
[root@Ec2Cluster-worker-0 myex]# chmod 300 folder
[root@Ec2Cluster-worker-0 myex]# ls -al folder/file
----------. 1 root root 0 Jul 25 23:42 folder/file
[root@Ec2Cluster-worker-0 myex]# chmod 200 folder
[root@Ec2Cluster-worker-0 myex]# ls -al folder/file
----------. 1 root root 0 Jul 25 23:42 folder/file
[root@Ec2Cluster-worker-0 myex]# chmod 100 folder
[root@Ec2Cluster-worker-0 myex]# ls -al folder/file
----------. 1 root root 0 Jul 25 23:42 folder/file
[root@Ec2Cluster-worker-0 myex]# chmod 000 folder
[root@Ec2Cluster-worker-0 myex]# ls -al folder/file
----------. 1 root root 0 Jul 25 23:42 folder/file
```

**Comment by yyongycy** [comment]
Please check the hdfs behavior. Does this change any current behavior of hdfs?

**Comment by Haoning-Sun** [comment]
@yyongycy I didn't find the impact of hdfs behavior for files. What impact do you consider？

**Comment by Haoning-Sun** [comment]
@yyongycy I tested the getFileStatus method of HDFS, and only need to have execution permission on the parent folder.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/13930429/181155760-f7f97de3-bdb5-41b5-a488-e156ea9716c6.png">
<img width="596" alt="image" src="https://user-images.githubusercontent.com/13930429/181155783-7e90748d-672c-4bce-b112-a689cf74eee0.png">

```
public static void printStatus(FileSystem fileSystem, String path) {
        try {
            FileStatus fileStatus = fileSystem.getFileStatus(new Path(path));
            System.out.println(path + " permission: " + fileStatus.getPermission().toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
<img width="371" alt="image" src="https://user-images.githubusercontent.com/13930429/181155601-724818fb-e3cb-4389-9155-efb6e98686cf.png">

- no permission for parent folder.

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/13930429/181156072-06f6f8f0-523b-4af9-844e-bcb12c8298e7.png">

**Comment by tcrain** [comment]
In posix 
- listing or removing a file/directory is determined by the owner of the parent directory
- but a non-empty directory cannot be removed

@LuQQiu please retry your test not as root user

The same issue mentioned here exists for the list status operation of alluxio, but is fixed in (https://github.com/Alluxio/alluxio/runs/7663843517?check_suite_focus=true)

**Comment by yyongycy** [comment]
If I have a file like:
/a/b/c/d/e/f.file

What if userA only has the permission to access /a/b/c/d/e, no read permission to /a/b/c/d,

Would the getStatus work for /a/b/c/d/e/f.file? In both posix and hdfs?

the checkParentPermission would check from /a to /a/b/c/d/e, am I right?

**Comment by Haoning-Sun** [comment]
Both posix and hdfs check the permissions of each level of directory.  It is same for checkParentPermission.

**Comment by LuQQiu** [comment]
Yeah similar to what @Haoning-Sun mentioned
Get file status checks the execute permission of all parent directories
```
[ec2-user@Ec2Cluster-worker-0 folder]$ mkdir folderA
[ec2-user@Ec2Cluster-worker-0 folder]$ mkdir folderA/folderB
[ec2-user@Ec2Cluster-worker-0 folder]$ touch folderA/folderB/file
[ec2-user@Ec2Cluster-worker-0 folder]$ chmod 000 folderA/folderB/file
[ec2-user@Ec2Cluster-worker-0 folder]$ ls folderA/folderB/file
folderA/folderB/file
[ec2-user@Ec2Cluster-worker-0 folder]$ ls -al  folderA/folderB/file
----------. 1 ec2-user ec2-user 0 Aug  8 23:09 folderA/folderB/file
[ec2-user@Ec2Cluster-worker-0 folder]$ chmod 000 folderA/folderB
[ec2-user@Ec2Cluster-worker-0 folder]$ ls -al  folderA/folderB/file
ls: cannot access folderA/folderB/file: Permission denied
[ec2-user@Ec2Cluster-worker-0 folder]$ chmod 300 folderA/folderB
[ec2-user@Ec2Cluster-worker-0 folder]$ ls -al  folderA/folderB/file
----------. 1 ec2-user ec2-user 0 Aug  8 23:09 folderA/folderB/file
[ec2-user@Ec2Cluster-worker-0 folder]$ chmod 300 folderA
[ec2-user@Ec2Cluster-worker-0 folder]$ ls -al  folderA/folderB/file
----------. 1 ec2-user ec2-user 0 Aug  8 23:09 folderA/folderB/file
[ec2-user@Ec2Cluster-worker-0 folder]$ chmod 000 folderA
[ec2-user@Ec2Cluster-worker-0 folder]$ ls -al  folderA/folderB/file
ls: cannot access folderA/folderB/file: Permission denied
```

**Comment by yyongycy** [comment]
What I mean the permission check is recursively in alluxio, could you please double check this based on alluxio?

**Comment by Haoning-Sun** [comment]
I've tested it. It's true.

**Comment by yyongycy** [comment]
Is it same in the pure hdfs or posix env?

**Comment by Haoning-Sun** [comment]
@yyongycy For getStatus, both posix and hdfs check the execution permission recursively and do not need the read permission.

**Comment by yyongycy** [comment]
thanks for investigating/fixing it.
