### ISSUE TITLE
alluxio version is 2.8.0 

### ISSUE THREAD

**Issue by lizhanyang505** [Alluxio/alluxio#15953]
**Alluxio Version:**
What version of Alluxio are you using?

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
@lizhanyang505 Thanks for creating the issue. looks like this issue is creating by mistake, can we close the issue?

**Comment by ssz1997** [comment]
Close due to inactivity
