### ISSUE TITLE
can not find security configuration in source code

### ISSUE THREAD

**Issue by wsjswy** [Alluxio/alluxio#15950]
I want to encrypt the files stored in the alluxio worker.
I find their some security configurations like alluxio.security.tier.storage.encryption.enabled=true;
the related link: https://docs.alluxio.io/ee/user/stable/en/operation/Security.html#configuring-alluxio-with-encryption-at-rest;
but I can not  find security configuration in source code.
could you please tell me how to find the security configurations in the source code.

**Comment by HelloHorizon** [comment]
@wsjswy the doc you opened is the enterprise version, please let me know if you are interested in the EE version.
