### ISSUE TITLE
alluxio version is 2.8.0 

### ISSUE THREAD

**Issue by lizhanyang505** [Alluxio/alluxio#15954]
**Alluxio Version:**
v2.8.0

**Describe the bug**
] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/conf/Hash.java:[14,39] 程序包org.apache.commons.codec.binary不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/LogUtils.java:[17,34] 程序包org.apache.commons.logging不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/LogUtils.java:[18,34] 程序包org.apache.commons.logging不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/LogUtils.java:[19,39] 程序包org.apache.commons.logging.impl不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/LogUtils.java:[20,39] 程序包org.apache.commons.logging.impl不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[17,23] 程序包org.apache.http不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[18,23] 程序包org.apache.http不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[19,23] 程序包org.apache.http不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[20,37] 程序包org.apache.http.client.config不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[21,38] 程序包org.apache.http.client.methods不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[22,38] 程序包org.apache.http.client.methods不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[23,35] 程序包org.apache.http.impl.client不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[24,35] 程序包org.apache.http.impl.client不存在
[ERROR] /Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[189,17] 找不到符号

this steps

git clone https://github.com/Alluxio/alluxio.git

 git checkout v2.8.0

mvn clean install -Phadoop-3 -Dhadoop.version=3.0.0-cdh6.3.2 -DskipTests

**Comment by lizhanyang505** [comment]
build alluxio 2.8.0 to support cdh ,is error

**Comment by LuQQiu** [comment]
@lizhanyang505 Thanks for reporting the issue, can you try giving a more descriptive name for this issue (e.g. describing the bug?)

**Comment by lizhanyang505** [comment]
Compile alluxio 2.8.0 to support cdh

**Comment by lizhanyang505** [comment]
this is my command

**Comment by lizhanyang505** [comment]
1. org.apache.commons.logging does not exist
2. Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[189,17] Symbol not found

**Comment by lizhanyang505** [comment]
Thanks for your help


Compile alluxio 2.8.0 to support cdh


Command:


git clone&nbsp;https://github.com/Alluxio/alluxio.git

git checkout v2.8.0

mvn clean install -Phadoop-3 -Dhadoop.version=3.0.0-cdh6.3.2 -DskipTests



Error:

org.apache.commons.logging does not exist

Users//Desktop/alluxio/core/common/src/main/java/alluxio/util/network/HttpUtils.java:[189,17] Symbol not found



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alluxio/alluxio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 上午7:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alluxio/alluxio] alluxio version is 2.8.0  (Issue #15954)





 
@lizhanyang505 Thanks for reporting the issue, can you try giving a more descriptive name for this issue (e.g. describing the bug?)
