### ISSUE TITLE
Active Syncing is not supported on this UFS type: hdfs

### ISSUE THREAD

**Issue by Crazybean-lwb** [Alluxio/alluxio#15973]
**Alluxio Version:**
Alluxio version: v2.8.0

**Other tools  Version:**
k8s version: v1.20.11
docker version: 20.10.11
hdfs version: 3.3.2

**Some background to add**
hdfs was deployed by binary file
hdfs was started by user root:supergroup
alluxio was deployed in k8s by helm run user root:root

**Describe the bug**
[bug1] I can't sync metadata and raw data from hdfs to alluxio.
`output exception:  Active Syncing is not supported on this UFS type: hdfs`
[bug2] I can't write data in ReadWriteMany PVC created by alluxio csi
`output  xxx.txt" E514: write error (file system full?)`
**To Reproduce**
1. start sync alluxio dir in alluxio master pod
![image](https://user-images.githubusercontent.com/22042825/181467845-f14f6c2a-8dd1-46ec-8622-ed8abb90b0a9.png)
2. error log in alluxio master
![image](https://user-images.githubusercontent.com/22042825/181468274-d47324b1-4aff-4b46-acb9-58e5645b7450.png)
-------------------------------------------------------------------------------------------------
3. I can touch new file in alluxio pvc, but can not write data in
when write something into touched new file, error occured:
![image](https://user-images.githubusercontent.com/22042825/181469760-d4db7cf8-8cd4-4d6a-afec-d19a670e5f19.png)
or `can not write into swap file`
4. error log in alluxio master
![image](https://user-images.githubusercontent.com/22042825/181470132-be27c980-4b95-46ee-9501-0d99207d4e31.png)

**Problem**
1. I found out hdfs version 3.3.2 have enabled support for ACL, can not understand `Active Syncing is not supported on this UFS type: hdfs`
2. I do not understand the procession of write data, .swap file id needed, but alluxio can not sync it.

**Comment by yohengyang** [comment]
Make sure parent path of your startSync path /liuweibin  in the mount table specifies the hdfs version

**Comment by liuweibin6566396837** [comment]
> Make sure the parent path of your startSync path /liuweibin in the mount table specifies the hdfs version. you can use "alluxio fs mount --option alluxio.underfs.version=xxx"

I have tried, output as follows:
![image](https://user-images.githubusercontent.com/22042825/183551624-0bb57fe8-b604-47a9-9f5d-dddfb2a28fbb.png)

**Comment by liuweibin6566396837** [comment]
> Make sure the parent path of your startSync path /liuweibin in the mount table specifies the hdfs version. you can use "alluxio fs mount --option alluxio.underfs.version=xxx"

I have tried many times mount hdfs with under.version, no differences happend.

**Comment by liuweibin6566396837** [comment]
> > Make sure the parent path of your startSync path /liuweibin in the mount table specifies the hdfs version. you can use "alluxio fs mount --option alluxio.underfs.version=xxx"
> 
> I have tried many times mount hdfs with under.version, no differences happend.

I found sollution to [1. start sync alluxio dir in alluxio master pod]
alluxio latest version surpport hdfs version 3.3.1 by default, while my hdfs version is 3.3.2.
I build alluxio-underfs-hdfs jar following the document, I can resolve the problem
![origin_img_v2_0ed46b3f-91af-4454-a30a-f88d520bb9bg](https://user-images.githubusercontent.com/22042825/187139129-aa404417-1f1e-4e19-99a5-0464be27c097.jpg)
----------------------------------------------
bug2 still can not be resolved.
I still can not  write data in ReadWriteMany PVC created by alluxio csi
output xxx.txt" E514: write error (file system full?)

**Comment by liuweibin6566396837** [comment]
> > > Make sure the parent path of your startSync path /liuweibin in the mount table specifies the hdfs version. you can use "alluxio fs mount --option alluxio.underfs.version=xxx"
> > 
> > 
> > I have tried many times mount hdfs with under.version, no differences happend.
> 
> ## I found sollution to [1. start sync alluxio dir in alluxio master pod]
> alluxio latest version surpport hdfs version 3.3.1 by default, while my hdfs version is 3.3.2.
> I build alluxio-underfs-hdfs jar following the document, I can resolve the problem
> ![origin_img_v2_0ed46b3f-91af-4454-a30a-f88d520bb9bg](https://user-images.githubusercontent.com/22042825/187139129-aa404417-1f1e-4e19-99a5-0464be27c097.jpg)
> bug2 still can not be resolved. I still can not write data in ReadWriteMany PVC created by alluxio csi output xxx.txt" E514: write error (file system full?)

get some reply for bugs 2
![image](https://user-images.githubusercontent.com/22042825/187588376-45cdb8be-9281-49df-9665-0f9662d252c4.png)
