### ISSUE TITLE
how to install CRDs with kubectl in k8s deploy scenario

### ISSUE THREAD

**Issue by wwq2333** [Alluxio/alluxio#16069]
**Page**
https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html#csi

**Summary**
Deploy alluxio with kubectl according to the documentation;
And During the installation of CSI driver, failed to execute the following command:
```
kubectl create -f alluxio-csi-controller-rbac.yaml
serviceaccount/csi-controller-sa created
clusterrole.rbac.authorization.k8s.io/alluxio-external-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/alluxio-csi-provisioner-binding created

kubectl create -f alluxio-csi-controller.yaml
deployment.apps/alluxio-csi-controller created

kubectl apply -f alluxio-csi-driver.yaml
error: resource mapping not found for name: "alluxio" namespace: "" from "alluxio-csi-driver.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"
ensure CRDs are installed first
```
so how to install CRDs with kubectl;

> Then please use helm-generate.sh (see [here](https://github.com/Alluxio/alluxio/tree/master/integration/kubernetes#generate-kubectl-yaml-templates-from-helm-chart) for usage) to generate related templates. All CSI related templates will be under ${ALLUXIO_HOME}/integration/kubernetes/csi.

I also try to use helm-generate.sh to re-generate CSI templates, but not found CRD templates.

```
alluxio-csi-controller-rbac.yaml.template
alluxio-csi-controller.yaml.template
alluxio-csi-driver.yaml.template
alluxio-csi-fuse-configmap.yaml.template
alluxio-csi-nodeplugin.yaml.template
alluxio-nginx-pod.yaml.template
alluxio-pv.yaml.template
alluxio-pvc-static.yaml.template
alluxio-pvc.yaml.template
alluxio-storage-class.yaml.template
```

**Comment by HelloHorizon** [comment]
@ssz1997 can you take a look?

**Comment by ssz1997** [comment]
@wwq2333 Sorry I missed this one eariler. It seems to me that your k8s version maybe outdated. We require the k8s cluster version to be at least 1.17. Can you help confirm the version of your k8s cluster?

**Comment by ssz1997** [comment]
@wwq2333 A workaround for you is to modify the `apiVersion` field in your `alluxio-csi-driver.yaml.template` to `storage.k8s.io/v1`, instead of `storage.k8s.io/v1beta1`.

Helm may have trouble comparing version strings of 1.24.x. Could you check the version of your Helm? To support k8s 1.24.x, you need helm version of 3.9.x. See https://helm.sh/docs/topics/version_skew/.
