### ISSUE TITLE
The exists method lacks permission check

### ISSUE THREAD

**Issue by Haoning-Sun** [Alluxio/alluxio#16195]
**Alluxio Version:**
master.

**Describe the bug**

I tested the exists method of HDFS and Alluxio. HDFS need to have execution permission on the parent folder and Alluxio has no permission to check.

**To Reproduce**
### HDFS
test code:
```
public static void printStatus(FileSystem fileSystem, String path) {
    try {
        System.out.println(fileSystem.exists(new Path("/a/b/c")));
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

- without parent permission:

```
drwx------   - alluxio staff          0 2022-08-04 15:41 /a/b
```

output:
```
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): Permission denied: user=hdfs, access=EXECUTE, inode="/a/b/c":hdfs:staff:drwx------
```

- with parent permission:

```
drwx--x--x   - alluxio staff          0 2022-08-04 15:41 /a/b
```

output:
```
true
```

### Alluxio

test code:
```
public static void exists() throws Exception {
   FileSystem fs = getFileSystem();
   System.out.println(fs.exists(new AlluxioURI("/a/b/c")));
}
```

- without parent permission:
```
drwx------  alluxio    staff                        2       PERSISTED 08-31-2022 09:05:59:745  DIR /a/b
```

output:
```
true
```

**Expected behavior**
The exists method requires permission check.

**Urgency**
Urgency.

**Are you planning to fix it**
Yes.

**Comment by yyongycy** [comment]
Wondering how this bug is discovered, in what scenario?
