### ISSUE TITLE
Reinit client side cluster config hash failed

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#16491]
**Alluxio Version:**

Master branch

**Describe the bug**

Log file is full of the `The interval of Master Replication Check updated to 60000`

**To Reproduce**

Just start master.

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by maobaolong** [comment]
@chunxiaozheng would you like to take this issue?

**Comment by chunxiaozheng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jiacheliu3** [comment]
@maobaolong Could you update this issue with more details? I don't really see what the issue is. Thx :)
