### ISSUE TITLE
The fuse pod will restart every few days

### ISSUE THREAD

**Issue by shaolei7788** [Alluxio/alluxio#16581]
**Alluxio Version:**
alluxio 2.8.1

**Describe the bug**
The fuse pod will restart every few days . it shows unable to umount fuse

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
The fuse pod will restart every few days

**Urgency**
high

**Are you planning to fix it**
I can't find a specific reason

**Additional context**

![image](https://user-images.githubusercontent.com/39719096/203676046-d36d80ae-ef24-4f2e-af7a-0cc0a4263910.png)

**Comment by ssz1997** [comment]
@shaolei7788 We fixed a bug in 2.9.0 that potentially fixed your problem. Could you try the newest version of Alluxio 2.9.0?

**Comment by LuQQiu** [comment]
@shaolei7788 Does Alluxio 2.9.0 solve the issue or do you still see this issue? thanks

**Comment by shaolei7788** [comment]
It doesn't happen again

**Comment by ssz1997** [comment]
@shaolei7788 Thanks for confirming. Closing this issue.
