### ISSUE TITLE
Alluxio metrics are missing from Presto

### ISSUE THREAD

**Issue by arunthirupathi** [Alluxio/alluxio#16596]
**Alluxio Version:**
2.8.1

**Describe the bug**
After Presto 278 release upgraded Alluxio version from 2.7.3 to 2.8.1 Cache JMX metrics are gone

**To Reproduce**
Deploy the Presto version 278

**Expected behavior**
Cache metrics are still present

**Urgency**
HIGH, this makes the operability hard as we don't know what is the cache hit rate.

**Are you planning to fix it**
I looked around the code, no change in the code. 

**Additional context**
Possible related issue: https://github.com/Alluxio/alluxio/issues/14200

**Comment by beinan** [comment]
@JiamingMai could you help take a look?  Thanks!  I think this issue is talking about the metrics of local cache on prestodb

**Comment by LuQQiu** [comment]
@JiamingMai any update for this issue?

**Comment by arunthirupathi** [comment]
This was a bug in the Meta's metrics collection, where dynamic metrics like this had an issue. We root caused and fixed the issue. Apologies for the wrong report and thanks for looking at it.
