### ISSUE TITLE
Excuse me, does alluxio support cdp hadoop3.1 and how to compile

### ISSUE THREAD

**Issue by mjh568412187** [Alluxio/alluxio#16617]
**Alluxio Version:**
What version of Alluxio are you using?

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

Excuse me, does alluxio support cdp hadoop3.1 and how to compile?
We want to use alluxio to integrate with hadoop3.1

**Comment by LuQQiu** [comment]
@jingwenouyang Please take a look, thanks

**Comment by LuQQiu** [comment]
@mjh568412187 can you ask this question in Alluxio slack channel https://slackin.alluxio.io/
internally we have more details about CDH hadoop but CDH hadoop is currently unavailable in Alluxio OS repo

**Comment by LuQQiu** [comment]
@mjh568412187 this is a question better suitable for [alluxio.io/slack](http://alluxio.io/slack) #troubleshooting channel.
Greg (Email: greg.palmer@alluxio.com @gregpa) has more information about the CDP hadoop, feel free to contact him directly.
