### ISSUE TITLE
distributedCp command hang when batch job failed and cannot cancel

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#16708]
**Alluxio Version:**
Alluxio 2.8.0

**Describe the bug**
```
Status: CREATED   Count: 0
Status: CANCELED  Count: 0
Status: FAILED    Count: 84
Status: RUNNING   Count: 0
Status: COMPLETED Count: 1559

10 Most Recently Modified Jobs:
Timestamp: 12-28-2022 11:29:06:735       Id: 1672221793398       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:753       Id: 1672221793348       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:753       Id: 1672221793349       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:752       Id: 1672221793346       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:752       Id: 1672221793347       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:752       Id: 1672221793350       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:752       Id: 1672221793351       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:751       Id: 1672221793356       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:751       Id: 1672221793357       Name: BatchedJob          Status: FAILED
Timestamp: 12-28-2022 11:28:59:751       Id: 1672221793358       Name: BatchedJob          Status: FAILED
```
 the `distributedCp` is hanging on waiting state, when some batchedJob failed and it's not getting canceled
Running distributedCp
```
Please wait for command submission to finish..
Submitted successfully, jobControlId = 1672308342397
Waiting for the command to finish ...
```

Workload:
copying data from hdfs to gcs using a replication of 8  on a cluster of 3 masters and 8 workers.
```
alluxio.user.file.readtype.default=CACHE_PROMOTE
alluxio.user.file.writetype.default=CACHE_THROUGH
```
worker log
```
TaskExecutor - Exception running task for job BatchedJob(BatchedJobTask{jobConfig=LoadConfig{
FilePath=/path_to_file, Replication=8}, jobTaskArgs=[LoadTask{FilePath=/path_to_file, blockId=27699183616, workerNetAddress=WorkerNetAddress{host=xxx-host, containerHost=, rpcPort=29999, dataPort=29999, webPort=30000, 
domainSocketPath=, tieredIdentity=TieredIdentity(node=xxx-host, rack=null)}}]}) :
 Network closed for unknown reason (Zero Copy GrpcDataReader)
```
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
@jja725 PTAL, thanks

**Comment by jja725** [comment]
I think there’s some problem with the job service about the job status update so the command is waiting forever for the given information. This could be partially solved by using the async command and writing your own client to wait for the command to finish within a given timeout. 
And we noticed other problems with the current architecture of the job service so we did the redesign and open-sourced the new distributed load recently. The following plan would be to support the new job service and deprecate the old one.

**Comment by othmanequarati** [comment]
thanks for the update

**Comment by vimalKeshu** [comment]
@jja725
I and @deepak-shivamurthy were able to reproduce it in our environment. I have identified the possible root cause of the issue and proposed the changes in the PR, https://github.com/Alluxio/alluxio/pull/16786. Please review it; if needed lets discuss.

**Comment by jja725** [comment]
I believe this is resolved.
