### ISSUE TITLE
alluxio-fuse keeps mounting and umounting, causing reads cache file error

### ISSUE THREAD

**Issue by nithinkxx** [Alluxio/alluxio#16705]
**Alluxio Version:**
2.8.1

**Describe the bug**
alluxio-fuse keeps mounting and umounting, causing reads cache file error

[alluxio-fuse.log](https://github.com/Alluxio/alluxio/files/10341010/alluxio-fuse.log)

**Comment by LuQQiu** [comment]
@nithinkxx is it launched through K8S/Fluid?

**Comment by LuQQiu** [comment]
From the alluxio fuse log, looks like the launched FUSE process gets killed quickly by external force (kill command, or unmount command)

**Comment by ssz1997** [comment]
@LuQQiu Normally unmount only happens when the fuse pod is being deleted, which is when csi detects no application pod is using alluxio as a volume. It looks like this is not the case here. Csi nodeserver is in control whether it is terminating fuse pod, so its log may have more information.

**Comment by LuQQiu** [comment]
From @nithinkxx they have their own script to mount/unmount fuse and is doing internal check

**Comment by LuQQiu** [comment]
For future reference of how to debug this kind of issue
From @ssz1997 
```
the csi nodeserver log in the node of fuse pod may have the fuse mount/unmount information，in the namespace of fluid-system，pod name is csi-nodeplugin-fluid，container name is plugin
```

**Comment by LuQQiu** [comment]
Close this issue since no new activities for one month, feel free to reopen if needed, thanks!
