### ISSUE TITLE
Stale raft journal metrics after leadership change

### ISSUE THREAD

**Issue by kaijchen** [Alluxio/alluxio#16704]
**Alluxio Version:**

2.9.0-SNAPSHOT (873bcca82e8cc1abb421bbb316bd9ef99b306c16)

**Describe the bug**

After a leadership change, journal entries (which is read from metrics) will get stuck:
<img width="1296" alt="before" src="https://user-images.githubusercontent.com/5821159/210472225-b5855af5-ca70-49a3-8e09-a801c95cb16f.png">

(The WebUI is with the change in #16636)

In this screenshot, `localhost:19988` lost primacy, and its `Journal Entries` got stuck.

**To Reproduce**

1. Start a HA cluster
2. Use Ratis shell to transfer leadership
3. Perform some operations, to increase journal entries
4. Observe journal entries metrics in each master

**Expected behavior**

The master lost primacy should have its metrics up to date.

**Urgency**

Medium.

**Are you planning to fix it**

Yes.

**Comment by LuQQiu** [comment]
@kaijchen Thanks for creating the github issue!
