### ISSUE TITLE
How can I access data in Aluxio in k8s using s3 protocol?

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#16719]
How can I access data in Aluxio in k8s using s3 protocol?
I guess I would need to fetch ACCESS_KEY_ID and ACCESS_KEY from Aluxio somehow
Can I use rclone with aluxio?

**Comment by LuQQiu** [comment]
https://docs.alluxio.io/os/user/stable/en/api/S3-API.html

By @lucyge2022 
By default alluxio s3 proxy doesn't do authentication at proxy end (specified by config parameter `alluxio.s3.rest.authentication.enabled` which is false by default), so you can set your s3 client application's `ACCESS_KEY_ID` to be the name of the intended user to access alluxio data in clear text  (e.g. `ACCESS_KEY_ID=alluxiouser1`) and any string for `ACCESS_KEY` since it doesn't matter
an example could be :
```
ACCESS_KEY_ID=alluxiouser1
ACCESS_KEY_ID=alluxiouser1
```
let me know if you have more questions

**Comment by LuQQiu** [comment]
By @lucyge2022 
We haven't tried rclone internally AFAIK, but it should work to serve as a rclone target to accept upload objects workload

**Comment by LuQQiu** [comment]
By Alex,
BTW, which auth type should I use v2 or v4 with rclone?

**Comment by LuQQiu** [comment]
By @lucyge2022 
v4 is recommended

**Comment by ssz1997** [comment]
@LuQQiu As far as I remember this is for experimenting. I'm closing this issue on Apr 11 if no objection.

**Comment by lucyge2022** [comment]
@ssz1997  this is resolved on the community slack channel and Lu's comment on Jan 5 is merely reflecting the conversation for the same, it's all good to close the issue, thanks.
