### ISSUE TITLE
Alluxio cache cephfs

### ISSUE THREAD

**Issue by andyzheung** [Alluxio/alluxio#16755]
I want to use alluxio to cache cephfs:
If this para can config subdir like this:
alluxio.underfs.cephfs.mount.point=/mnt/aaa/bbb
If not this para did any other para to config it?

**Comment by beinan** [comment]
Our official doc for ceph: https://docs.alluxio.io/os/user/stable/en/ufs/CephFS.html
feel free to ping us if it does not answer your question

**Comment by andyzheung** [comment]
> Our official doc for ceph: https://docs.alluxio.io/os/user/stable/en/ufs/CephFS.html feel free to ping us if it does not answer your question

yes I have read this ,still don't know if the cephfs need to mount the sub-dir can use this para?

**Comment by andyzheung** [comment]
Yes I have solve this problem:
