### ISSUE TITLE
Support adding necessary modules when generate tarballs.

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#16831]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when all modules are added when generate tarballs. It make the tarball too big.

**Describe the solution you'd like**
Support adding necessary modules when generate tarballs.

**Urgency**
General

**Comment by JySongWithZhangCe** [comment]
@jiacheliu3 Would you like to take a look? Thanks♪(･ω･)ﾉ

**Comment by jja725** [comment]
@Xenorith @jiacheliu3

**Comment by Xenorith** [comment]
is your request specific to the mechanism in which a tarball can be generated via the existing scripts or is it a comment on the tarballs available for download, for example in https://downloads.alluxio.io/downloads/files/ ?

if it is with regards to the tarball generation script, are you aware of the `-ufs-modules` flag in the `./generate-tarballs release` command?

**Comment by JySongWithZhangCe** [comment]
> is your request specific to the mechanism in which a tarball can be generated via the existing scripts or is it a comment on the tarballs available for download, for example in https://downloads.alluxio.io/downloads/files/ ?
> 
> if it is with regards to the tarball generation script, are you aware of the `-ufs-modules` flag in the `./generate-tarballs release` command?

Yeap! I'll try it! Thanks♪(･ω･)ﾉ

**Comment by LuQQiu** [comment]
This issue will be closed, feel free to reopen the issue if need further discussion, thanks for submitting the issue!

**Comment by JySongWithZhangCe** [comment]
> is your request specific to the mechanism in which a tarball can be generated via the existing scripts or is it a comment on the tarballs available for download, for example in https://downloads.alluxio.io/downloads/files/ ?
> 
> if it is with regards to the tarball generation script, are you aware of the `-ufs-modules` flag in the `./generate-tarballs release` command?

I have tried and found some problems：

**Comment by JySongWithZhangCe** [comment]
> This issue will be closed, feel free to reopen the issue if need further discussion, thanks for submitting the issue!

It seems that I can't turn it open, can you help me turn it open again? Thanks♪(･ω･)ﾉ

**Comment by JySongWithZhangCe** [comment]
> > is your request specific to the mechanism in which a tarball can be generated via the existing scripts or is it a comment on the tarballs available for download, for example in https://downloads.alluxio.io/downloads/files/ ?
> > if it is with regards to the tarball generation script, are you aware of the `-ufs-modules` flag in the `./generate-tarballs release` command?
> 
> I have tried and found some problems：
> 
> 1. When I specify `-ufs-modules "ufs-hadoop-ozone-1.2.1"`, the compilation will report an error, because the package name that the system wants cp is not the actual package name.（Actually is alluxio-underfs-hadoop-ozone-1.2.1-2.10.0-SNAPSHOT.jar, but alert `alluxio-underfs-ozone-2.10.0-SNAPSHOT.jar: No such file or directory`）
> 2. Modules like fuse will continue to be compiled. Since fuse does not support arm currently, there will be some problems.

The alert is due to I added ozone configuration in `dev/scripts/src/alluxio.org/build-distribution/cmd/common.go`,  and the alert will not be reported after rollback.
`var libJars = map[string]struct{}{
	"integration-tools-hms":        {},
	"integration-tools-validation": {},

	"underfs-abfs":          {},
	"underfs-adl":           {},
	"underfs-cos":           {},
	"underfs-cephfs":        {},
	"underfs-cephfs-hadoop": {},
	"underfs-gcs":           {},
	"underfs-local":         {},
	"underfs-obs":           {},
	"underfs-oss":           {},
        "underfs-ozone":           {},
	"underfs-s3a":           {},
	"underfs-swift":         {},
	"underfs-wasb":          {},
	"underfs-web":           {},
}`

**Comment by JySongWithZhangCe** [comment]
Modify the ozone configuration in `lib-jars`, and specify `lib-jars` and `ufs-modules` at the same time to package only ozone. Other ufs have not been tried yet, and they may be the same
   var libJars = map[string]struct{}{
	"integration-tools-hms":        {},
	"integration-tools-validation": {},

	"underfs-abfs":          {},
	"underfs-adl":           {},
	"underfs-cos":           {},
	"underfs-cephfs":        {},
	"underfs-cephfs-hadoop": {},
	"underfs-gcs":           {},
	"underfs-hadoop-ozone-1.2.1":           {},
	"underfs-local":         {},
	"underfs-obs":           {},
	"underfs-oss":           {},
	"underfs-s3a":           {},
	"underfs-swift":         {},
	"underfs-wasb":          {},
	"underfs-web":           {},
    }

**Comment by Xenorith** [comment]
@JySongWithZhangCe it sounds like you found the solution on your own
- `-ufs-modules` will specify which UFS jars to build. if left empty, it will build the default set of ufs modules, which is a fairly long list
- `-lib-jars` will specify which which jars within the lib folder to be copied into the tarball. by default it will copy the list you found defined by `var libJars` in `common.go`. this is the current list of UFS jars, besides the hadoop ones, that are built by default and would be copied by default.

so your conclusion is correct. any ufs that is not built by default would need to specify both flags in order for it to be included into the final tarball. note that we cannot add the hadoop-ozone-1.2.1 underfs line as part of `libJars` because we would not normally build that and the tarball generation will fail with a file not found when trying to copy that path.

let me know if there are other problems i may have not addressed and/or if the issue needs to be reopened
