### ISSUE TITLE
Alluxio Cluster formatted  failed

### ISSUE THREAD

**Issue by liuzx8888** [Alluxio/alluxio#16861]
**Alluxio Version:**
master

> mvn clean install -Pufs-hadoop-3 -Dhadoop.version=3.2.3 -DskipTests -Dmaven.buildNumber.revisionOnScmFailure=2.10.0  -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Dlicense.skip

**Describe the bug**

> `[root@gpmaster alluxio-master]# ./bin/alluxio formatMasters
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at alluxio.conf.PropertyKey.javadocLink(PropertyKey.java:7395)
> 	at alluxio.conf.PropertyKey.<clinit>(PropertyKey.java:6546)
> 	at alluxio.conf.AlluxioProperties.merge(AlluxioProperties.java:142)
> 	at alluxio.conf.Configuration.reloadProperties(Configuration.java:581)
> 	at alluxio.conf.Configuration.<clinit>(Configuration.java:85)
> 	at alluxio.ClientContext.create(ClientContext.java:80)
> 	at alluxio.cli.GetConf.main(GetConf.java:267)
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 8
> 	at java.lang.String.substring(String.java:1963)
> 	at alluxio.RuntimeConstants.<clinit>(RuntimeConstants.java:39)
> 	... 7 more
> `

**To Reproduce**

> `# Common properties
> alluxio.master.hostname=gpmaster
> alluxio.master.mount.table.root.ufs=hdfs://192.168.2.182:9000/alluxio-quick-start/data
> alluxio.master.mount.table.root.option.alluxio.underfs.version=3.2.3
> alluxio.underfs.hdfs.configuration=/opt/softinstall/hadoop-3.2.3/etc/hadoop/core-site.xml:/opt/softinstall/hadoop-3.2.3/etc/hadoop/hdfs-site.xml`

./bin/alluxio formatMasters

**Expected behavior**
 build Alluxio with a specific Hadoop release version

**Urgency**
important

**Comment by LuQQiu** [comment]
@liuzx8888 can you try with different master hostnames for each master?
and try if ./bin/alluxio formatMaster work?

**Comment by liuzx8888** [comment]
@LuQQiu   It was my own fault that caused this error. I wrote the wrong version number. The version number should be 2.10.0-SNAPSHOT. I wrote 2.10.0. The following code caused an error
![image](https://user-images.githubusercontent.com/10862577/218013409-11d4a940-7c22-47fc-a03f-7735955959e0.png)
