### ISSUE TITLE
conf/alluxi-site.properties configuration

### ISSUE THREAD

**Issue by qingliangyang** [Alluxio/alluxio#16905]
How do I add OBS V4 information to the alluxi-site.properties configuration?
<img width="633" alt="image" src="https://user-images.githubusercontent.com/125526459/219565688-cba84563-96eb-4a62-8c9c-94fc1e2e8184.png">

**Comment by jiacheliu3** [comment]
Dup in https://github.com/Alluxio/alluxio/issues/16894
