### ISSUE TITLE
alluxio.user.block.size.bytes.default not apply to object storage system

### ISSUE THREAD

**Issue by xiaopeifeng** [Alluxio/alluxio#16904]
**Alluxio Version:**
What version of Alluxio are you using?
2.9.0
**Describe the bug**
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
1 minio as  backend storage system
2 upload 1G size object
3 i still see the object in minio system

**Expected behavior**
expect slice object large than config(alluxio.user.block.size.bytes.default) to smaller slices

**Urgency**
Describe the impact and urgency of the bug.
normal
**Are you planning to fix it**
Please indicate if you are already working on a PR. 
no
**Additional context**
![微信图片_2](https://user-images.githubusercontent.com/7620721/219540371-7fdacfa3-335e-41dc-bbee-91f27a9af14d.png)
![微信图片_1](https://user-images.githubusercontent.com/7620721/219540512-30368a3e-1721-4a4a-ab0f-89c12c05b925.png)

**Comment by huanghua78** [comment]
Hello @xiaopeifeng , thank you for reporting issues to Alluxio.

`alluxio.user.block.size.bytes.default` is the block size for internal block cache on workers.
It is the file size of the cache file (both for a sync write and read) on workers.
It is not the final object size in UFS (here objects in Minio).

This is not an issue.
Closed.

**Comment by xiaopeifeng** [comment]
ok, thanks
