### ISSUE TITLE
So many URLs in https://docs.alluxio.io/ redirect to https://www.alluxio.com.cn/

### ISSUE THREAD

**Issue by xiaozhch5** [Alluxio/alluxio#16923]
**Page**
[Include the link to the page you are reporting a defect
](https://www.alluxio.io/alluxio-presto-sandbox-docker/)

https://www.alluxio.io/blog/data-orchestration-the-missing-piece-in-the-data-world/

......

So many other URLs.

![image](https://user-images.githubusercontent.com/46479816/220231228-037213d9-e8b9-4699-8b48-bba36a722140.png)

**Summary**

That's too bad that So mamy URLs in alluxio document redirect to  https://www.alluxio.com.cn/ without any hints. In this way, so much useful information will be ignore for Chinese developer.

I think the url redirect in alluxio official documents should be correct.

**Comment by fuzhengjia** [comment]
Hi xiaozhch5,
Thanks for your comments and feedback, we will look into the current url redirect mechanism and improve the experience
