### ISSUE TITLE
getStatus will list all metadata in UFS

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#16922]
**Alluxio Version:**
2.9.0

**Describe the bug**
alluxio dir: `/s3`
mount hdfs: `/` -> alluxio `/s3`
then `bin/alluxio fs cat /s3 -Dalluxio.user.file.metadata.sync.interval=0` will use `URIStatus status = mFileSystem.getStatus(path);`
<img width="966" alt="image" src="https://user-images.githubusercontent.com/45056332/220184742-aa55dfa7-8062-47f2-a4ce-77d7bc2ff098.png">
**then all files of hdfs will be loaded!**

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by elega** [comment]
Hi thanks for reporting the issue. We need some clarification.
1. Is this /s3 path a directory or a file?
2. GetStatus only returns a file info of a single inode. When you said "list" all metadata in UFS in your issue subject, did you mean all file metadata of this directory were loaded into alluxio? What exactly did you get when you execute this cli command?

**Comment by humengyu2012** [comment]
`/s3` is a directory, i use `cat` command just want to use the alluxio filesystem command `getStatus`, `list` command will not invoke this method. 
`fs.getStatus("/s3")` should just load metadata in `/s3` without recursion, but I found that it will recursively load the meta information of all files under `/s3` by HDFS audit log.

**Comment by humengyu2012** [comment]
We can also use `bin/alluxio fs stat /s3 -Dalluxio.user.file.metadata.sync.interval=0`.

**Comment by HelloHorizon** [comment]
related to #16935

**Comment by jiacheliu3** [comment]
@humengyu2012 please check if this is fixed by https://github.com/Alluxio/alluxio/pull/16935, thanks!

**Comment by humengyu2012** [comment]
Fixed by https://github.com/Alluxio/alluxio/pull/16935.
