### ISSUE TITLE
integrate ratis-shell to the alluxio tarball.

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#16943]
**Is your feature request related to a problem? Please describe.**

- https://cloud.tencent.com/developer/article/2039789
- https://issues.apache.org/jira/browse/RATIS-1427

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by dbw9580** [comment]
Thanks for the feature proposal. Pinging @HelloHorizon to take a look.

**Comment by codings-dan** [comment]
Thanks @maobaolong for raising this issue, I will complete this task in the future

**Comment by maobaolong** [comment]
@codings-dan Looks forward to see your PR.

**Comment by jiacheliu3** [comment]
@HelloHorizon Does this make sense to you?

**Comment by jiacheliu3** [comment]
Per discussion with @HelloHorizon , we are okay with integrating ratis shell into Alluxio. I'll follow up on the PR. Thanks a lot for the work!

**Comment by elega** [comment]
https://github.com/Alluxio/alluxio/pull/16980

**Comment by maobaolong** [comment]
@codings-dan Would you like to start the work on this issue?

**Comment by codings-dan** [comment]
@maobaolong Sure, let me start this work recently.
