### ISSUE TITLE
Fix some errors occurred when formatting alluxio

### ISSUE THREAD

**Issue by jianghuazhu** [Alluxio/alluxio#16949]
**Alluxio Version:**
What version of Alluxio are you using?
2.9.0/2.9.1

**Describe the bug**
When I try to start Alluxio quickly, I follow the following link:
https://docs.alluxio.io/os/user/stable/cn/overview/Getting-Started.html
I configured allouxio-site.properties and executed the./bin/allouxio format. Here I will receive some errors. In {allouxio_home_dir}/logs/task. log:
[2023-02-27 14:46:32][localhost] Error: Cannot find 'java' on path or under $JAVA_ HOME/bin/. Please set JAVA_ HOME in alluxio-env.sh or user bash profile.
[2023-02-27 14:46:32][localhost] Connection to localhost closed.

Obviously, we need to create alloxio-env.sh in advance and add JAVA_ HOME.

**To Reproduce**
The following steps can be followed:
1. Download allouxio-2.9.1-bin.tar.gz
2. Press it
3. Configure conf/alloxio-site.properties
4. Execute the command:./bin/alluxio validateEnv local
5. Execute the command:./bin/alluxio format

**Expected behavior**
When executing the command:/ When bin/alloxio format, everything should be as usual without any errors

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by jianghuazhu** [comment]
I will submit pr later.

**Comment by fuzhengjia** [comment]
Sounds good, looking forward to your PR submission

**Comment by jianghuazhu** [comment]
@fuzhengjia thank you so much for your comments. I have submitted a new pr. Link: https://github.com/Alluxio/alluxio/pull/16950
