### ISSUE TITLE
User Authentication & Authorization

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#17009]
**Is your feature request related to a problem? Please describe.**
If I know the master's address, I don't need any authentication information to interact with the master and read the file. And I don't need authorization to access the files  that don't belong to me. This is a very dangerous thing.

**Describe the solution you'd like**

Provide a plugin that enables me to implement authentication and authorization myself.

**Comment by elega** [comment]
@HelloHorizon for feature request
and @yyongycy for security
