### ISSUE TITLE
Replace HashMap<Long, Long> etc with primitive maps

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#17028]
**Summary**
Data structures like `HashMap<Long, Long>` are poor in memory utilization. 

The key and value are the effective data you are storing (2 * 8 bytes). The boxing from `long` to `Long` will make each a 24 byte object (including obj heads and Klass pointers). Then the `Map.Entry<Long,Long>` object will add another round of object heads and Klass pointers. Then the Entry has a 8-byte `next` field and a 4-byte `hash`. Then in the HashMap there's the 8-byte ref to the Entry object. I'm not counting the padding the JVM mem allocation so the actual utilization is even lower.

For big maps we should try our best to utilize primitive maps like fastutils.

**Urgency**
MEDIUM - LOW

**Comment by voddle** [comment]
Upon investigation, we found that there is no usage of `HashMap<Long, Long>` in Alluxio. There are only two instances where `HashMap<Long, WorkerNetAddress>` is used, namely in `mBlockLocationCache` of `RoundRobinPolicy`, and `mWorkerIdMap` of `DefaultBlockMaster`. Typically, these two HashMaps will only contain a few hundred objects, so they are unlikely to grow very large. Additionally, `DefaultStorageTier` contains a `HashMap<Integer, StorageDir> mDir`, which also consumes minimal memory.

Therefore, in my opinion, there is no room for optimization here :D
