### ISSUE TITLE
Wrong cpu core num returned from k8s env

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#17021]
In kubernetes env, deploy a pod with cpu core limit, lets say limit 30.

```
public class A {
  public static void main(String[] args) {
    System.out.println("Max core : " + Runtime.getRuntime().availableProcessors());
  }
}
```

```
# cat /proc/cpuinfo | grep processor | wc -l
30
# java A
Max core : 192
```

--------------

The above test is from Tencent (TKE) kubernetes, the  `192` is the node cpu processor number, but `cpuinfo` return the right value of pod cpu limit `30`

```
java -version
openjdk version "1.8.0_272"
```

@ssz1997 did the same test in aws kubernetes, return the opposite result.

**Comment by elega** [comment]
@ssz1997 can take on this one

**Comment by ssz1997** [comment]
@maobaolong Did some testing on my end:
k8s (EKS from Amazon) env:
Client version: 1.20. Server version: 1.22. Java version: 1.8.0_362
1. CPU limits exists in the yaml file, without jvm option `-XX:+UseContainerSupport`:
      Output of `cat /proc/cpuinfo | grep processor | wc -l` is the number of cpu of host machine.
      Output of the java program is the number of cpu of the control plane machine (my laptop)
2. CPU limits exists in the yaml file, with jvm option `-XX:+UseContainerSupport`:
        Output of `cat /proc/cpuinfo | grep processor | wc -l` is the number of cpu of host machine.
        Output of the java program is the number of cpu specified in the yaml file.
3. CPU limits doesn't exist in the yaml file, with & without jvm option `-XX:+UseContainerSupport`:
       Output of `cat /proc/cpuinfo | grep processor | wc -l` is the number of cpu of host machine.
       Output of the java program is the number of of host machine.
So in k8s env, if we set limit, we should include `-XX:UseContainerSupport`. Or don't set the limit if user sees fit.

None of our tests return "1" so I tried to reproduce the original issue that made me did the change (all the fallback logic in the properties), and I was not able to reproduce it with the original image (Alluxio 2.6.2).

**Comment by ssz1997** [comment]
@maobaolong The recommendation for you is to try `-XX:UseContainerSupport` since you mentioned offline this may help. 
And for the fallback logic in the code, they won't affect you if you can get the correct number of CPU.

 I'm afraid there're some environments still have the problem, so let's keep the way it is.
