### ISSUE TITLE
Master TTL checker cannot be disabled by specifying a negative heartbeat interval

### ISSUE THREAD

**Issue by MEILIDEKCL** [Alluxio/alluxio#17057]
**Alluxio Version:**
2.1.0

**Describe the bug**
Set the alluxio.master.ttl.checker.interval configration to zero or negative values, and start the alluxio by `./bin/alluxio-start.sh local`.
And I find the `alluxio.master.AlluxioMaster` process fills one cpu core, and the logs size reach to 1G just by one minute.
```bash
hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ du -sh logs/
1007M   logs/
```
the master log info is Repetitive like this. And all 100 master logs are printed with the same information.
```bash
2023-03-13 11:04:38,474 WARN  SleepingTimer - Master TTL Check last execution took 0 ms. Longer than the interval -1
```
**To Reproduce**

Firstly, make sure the conf(alluxio-site.properties) is like this.
```bash
alluxio.master.hostname=localhost
alluxio.master.mount.table.root.ufs=/tmp
alluxio.master.ttl.checker.interval=-1
```
Secondly, use shell below.

```bash
hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ ./bin/alluxio-mount.sh SudoMount
Unmounting /mnt/ramdisk
[sudo] password for hadoop: 
Formatting RamFS: /mnt/ramdisk (2757178709)

hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ ./bin/alluxio format
Executing the following command on all worker nodes and logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs/task.log: /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/bin/alluxio formatWorker
Waiting for tasks to finish...
All tasks finished
Executing the following command on all master nodes and logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs/task.log: /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/bin/alluxio formatJournal
Waiting for tasks to finish...
All tasks finished

hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ ./bin/alluxio-start.sh local
Assuming NoMount by default.
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Starting master @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
Starting job master @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
Starting worker @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
Starting job worker @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
Starting proxy @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
-----------------------------------------
Starting to monitor all local services.
-----------------------------------------
--- [ OK ] The master service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.
--- [ OK ] The job_master service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.
--- [ OK ] The worker service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.
--- [ OK ] The job_worker service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.
--- [ OK ] The proxy service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.

hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ du -sh logs/
1007M   logs/
hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ top -c

```

**Expected behavior**
It will check the unvalid conf by using it. Or how long the process shuts down after trying few seconds.
**Urgency**
Describe the impact and urgency of the bug.
It will fills a cpu core continuously, and makes the log system lossed other information.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by dbw9580** [comment]
Hi @MEILIDEKCL, I don't think `alluxio.master.ttl.checker.interval` currently supports an interval that's 0 or negative. Are you looking to disable the TTL check altogether by specifying `-1`?

**Comment by MEILIDEKCL** [comment]
Hi @dbw9580, I mean if user use this misconf(`alluxio.master.ttl.checker.interval` set to zero or negative), the master will log the warn info to master.log continuously because of the thread.

**Comment by dbw9580** [comment]
Are you trying to disable the TTL checker by specifying a negative interval?

**Comment by MEILIDEKCL** [comment]
No, I just set the TTL checker to a negative interval, and watching the system response.
I am not trying to disable the TTL checker.

**Comment by dbw9580** [comment]
Then what is your expected outcome for a negative heartbeat interval?

**Comment by MEILIDEKCL** [comment]
I think system shouldn't just keeps logging, because it will cover old log infomation and waste system resource usage.
And I expect when initializing the system, it will pre-check the interval conf and throw related infomation.

**Comment by MEILIDEKCL** [comment]
> Then what is your expected outcome for a negative heartbeat interval?

Hi, you mean the negative ttl interval should disable the master ttl check?
If so, I will try to focus it. Thank you.

**Comment by MEILIDEKCL** [comment]
I will give a new issue

**Comment by MEILIDEKCL** [comment]
link to #17408
