### ISSUE TITLE
When start the Alluxio, the log system will repeatdly the same warn info.

### ISSUE THREAD

**Issue by MEILIDEKCL** [Alluxio/alluxio#17062]
**Alluxio Version:**
2.1.0

**Describe the bug**
Set the `alluxio.user.conf.sync.interval` configration to zero or negative values, and start the alluxio by `./bin/alluxio-start.sh local`
The number of job_master.log, master.log and proxy.log will quickly reach to 100, and the logs size reach to 3G in two minutes. The content is probably the same about meta master
`2023-03-13 11:23:33,297 WARN  SleepingTimer - Meta Master Config Hash Sync-app-310874816738036463 last execution took 0 ms. Longer than the interval -1`

And the process of `alluxio.master.AlluxioMaster` ,`alluxio.proxy.AlluxioProxy`, `alluxio.master.AlluxioJobMaster`  both have high CPU usage. Especially the `alluxio.master.AlluxioMaster`. （My machine is 4-core 4G）

This config will affects not noly master.log , but also proxy.log and job_master.log

**To Reproduce**
Firstly, make sure the conf(alluxio-site.properties) is like this.

```bash
alluxio.master.hostname=localhost
alluxio.master.mount.table.root.ufs=/tmp
alluxio.user.conf.sync.interval=-1
```
Secondly, use shell below.
```bash
hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ ./bin/alluxio-mount.sh SudoMount
Unmounting /mnt/ramdisk
[sudo] password for hadoop: 
Formatting RamFS: /mnt/ramdisk (2757178709)

hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ ./bin/alluxio format
Executing the following command on all worker nodes and logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs/task.log: /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/bin/alluxio formatWorker
Waiting for tasks to finish...
All tasks finished
Executing the following command on all master nodes and logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs/task.log: /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/bin/alluxio formatJournal
Waiting for tasks to finish...
All tasks finished

hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ ./bin/alluxio-start.sh local
Assuming NoMount by default.
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Killed 0 process(es) on hadoop-Standard-PC-i440FX-PIIX-1996
Starting master @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
Starting job master @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
Starting worker @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
Starting job worker @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
Starting proxy @ hadoop-Standard-PC-i440FX-PIIX-1996. Logging to /home/hadoop/ecfuzz/data/app_sysTest/alluxio-2.1.0-work/logs
-----------------------------------------
Starting to monitor all local services.
-----------------------------------------
--- [ OK ] The master service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.
--- [ OK ] The job_master service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.
--- [ OK ] The worker service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.
--- [ OK ] The job_worker service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.
--- [ OK ] The proxy service @ hadoop-Standard-PC-i440FX-PIIX-1996 is in a healthy state.

hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ du -sh logs/
3.3G    logs/
hadoop@hadoop-Standard-PC-i440FX-PIIX-1996:~/ecfuzz/data/app_sysTest/alluxio-2.1.0-work$ top -c

```

**Expected behavior**
It will check the unvalid conf by using it. Or how long the process shuts down after trying few seconds.

**Urgency**
It will cause system wasting usage.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by Kai-Zhang** [comment]
The `alluxio.user.conf.sync.interval` is not supposed to be zero or minus. But this behavior can be improved. You can open a pr to improve it if you're willing to.

**Comment by MEILIDEKCL** [comment]
> The `alluxio.user.conf.sync.interval` is not supposed to be zero or minus. But this behavior can be improved. You can open a pr to improve it if you're willing to.
Yeah, thank you so much. I will open a pr to improve it on 2.1.0

**Comment by MEILIDEKCL** [comment]
> The `alluxio.user.conf.sync.interval` is not supposed to be zero or minus. But this behavior can be improved. You can open a pr to improve it if you're willing to.

Hi, I have given a pr to improve it on branch 2.1. Can you check it? Thank you.
