### ISSUE TITLE
flink don't support alluxio ha, eg alluxio:///

### ISSUE THREAD

**Issue by felixzh2020** [Alluxio/alluxio#17077]
**Alluxio Version:**
What version of Alluxio are you using?
2.9.0
**Describe the bug**
https://www.alluxio.com.cn/quickstart/alluxioapache-flink/
flink don't support alluxio, eg : alluxio:///

Caused by: java.lang.IllegalArgumentException: URI scheme hdfs does not match the expected scheme alluxio

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
flink run -t yarn-per-job WordCount.jar --input alluxio:///ss --output /output1

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by Kai-Zhang** [comment]
Thank you for the feedback. Could you provide the log of alluxio components on this? Are there any errors or exceptions?

**Comment by felixzh2020** [comment]
- Alluxio use raft mode. 
- When ha, you must use flink run -t yarn-per-job WordCount.jar --input alluxio://master1IP:19998,master2IP:19998/ss. 
- That is not work, flink run -t yarn-per-job WordCount.jar --input alluxio:///ss.
- When debug, alluxio/2.9.0/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java initialize method input parameter uri is hdfs://mycluster.
-
