### ISSUE TITLE
MutableInode  reference bug 

### ISSUE THREAD

**Issue by tokingHong** [Alluxio/alluxio#17083]
**Alluxio Version:**
2.8.1

**Describe the bug**
if we set
alluxio.master.metastore=ROCKS
alluxio.master.metastore.inode.cache.max.size=0

copyFromLocal will get
`Cannot persist an incomplete Alluxio file`

**Additional context**
update inode by inode tree use the same reference with lockedInodePath only work in heap or caching . 
the LockedInodePath will got a dirty value when use that config

**Comment by jiacheliu3** [comment]
@elega @lucyge2022 Could you take a look? Thanks!

**Comment by elega** [comment]
Thanks for reporting the issue. The fix is WIP
https://github.com/Alluxio/alluxio/compare/master...elega:alluxio:yimin/fix-reference-issue?expand=1

**Comment by jiacheliu3** [comment]
fixed in #17145
