### ISSUE TITLE
Worker java.lang.Out0fMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#17180]
**Alluxio Version:**
2.9.2

**Describe the bug**
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/45056332/229362212-02101acf-c0cb-4092-b1ab-76c686546f6d.png">

Worker jvm config:
```
ALLUXIO_WORKER_JAVA_OPTS="$ALLUXIO_WORKER_JAVA_OPTS -Xms32G -Xmx32G -XX:+UseG1GC -XX:MaxDirectMemorySize=16g"
```

<img width="893" alt="image" src="https://user-images.githubusercontent.com/45056332/229362393-fd187d15-347f-4ad1-a71e-e1bfbda1fb44.png">
<img width="956" alt="image" src="https://user-images.githubusercontent.com/45056332/229362434-591c8f2c-b086-42c4-8a3b-827f94256d1e.png">
<img width="925" alt="image" src="https://user-images.githubusercontent.com/45056332/229362452-8649c24c-cff1-4661-b486-9e76a74d5bca.png">
<img width="890" alt="image" src="https://user-images.githubusercontent.com/45056332/229362780-902ecb51-afa4-4e03-8e3a-506706adfae9.png">

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by ChunxuTang** [comment]
@humengyu2012 Thanks for raising the report!
Is this related to the PR (https://github.com/Alluxio/alluxio/pull/17179) you raised?

**Comment by humengyu2012** [comment]
> @humengyu2012 Thanks for raising the report! Is this related to the PR (#17179) you raised?

No, in fact, they are not related. 
The cause of the OOM I don't know yet, but I will try to increase the direct memory from 16G to 32G. If there is a follow-up, I will synchronize here.

**Comment by jianghuazhu** [comment]
@humengyu2012 ，has this problem been solved after adding memory to the node?

**Comment by humengyu2012** [comment]
> @humengyu2012 ，has this problem been solved after adding memory to the node?
@jianghuazhu  It seems to be better now, maybe we need a longer time to observe it.
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/45056332/230704123-bda39053-1909-44d9-846b-dbc5b98dc30e.png">
