### ISSUE TITLE
Cannot cast java.lang.String to alluxio.grpc.TtlAction 

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#17255]
**Alluxio Version:**
client 2.9.0
master 2.9.2

**Describe the bug**
use command:
```
bin/alluxio fs ls /
```
we will get an exception:
```
Cannot cast java.lang.String to alluxio.grpc.TtlAction
```
If we upgrade the version of master, all clients will be affected.
Should we change the default behavior of ttlAction back to `DELETE`?
```
enum TtlAction {
  DELETE = 0; // Delete the file after TTL expires.
  FREE = 1;   // Free the file after TTL expires.
  DELETE_ALLUXIO = 2; // Delete the data and metadata in Alluxio after TTL expires.
}
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by jja725** [comment]
This is a known issue and has already been fixed in a newer version. https://github.com/Alluxio/alluxio/pull/17039#issuecomment-1461060184

@ssyssy @yuzhu  fyi.
