### ISSUE TITLE
Wait for the file to be marked as complete by the writing thread or application.

### ISSUE THREAD

**Issue by lingchuanzhou** [Alluxio/alluxio#17286]
**Alluxio Version:**
2.9.1

**Describe the bug**
when I use presto select, but ocurrs this error:
`presto:default> select count(1) from alert_log_flink where dt = '2023-04-10';

Query 20230419_072822_00011_6eyd2, FAILED, 8 nodes
Splits: 543 total, 0 done (0.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20230419_072822_00011_6eyd2 failed: Error opening Hive split alluxio://alluxio-master-0.alluxio:19998,alluxio-master-1.alluxio:19998,alluxio-master-2.alluxio:19998/flink/alert_log_flink/data_table/dt=2023-04-10/alert_log-0989d3eaf18f401faffba96cea93e45d.snappy.parquet (offset=0, length=0): alluxio.exception.FileIncompleteException: Cannot read from /flink/alert_log_flink/data_table/dt=2023-04-10/alert_log-0989d3eaf18f401faffba96cea93e45d.snappy.parquet because it is incomplete. Wait for the file to be marked as complete by the writing thread or application.`

my data is produce by flink , which write to alluxio.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by Jackson-Wang-7** [comment]
https://github.com/Alluxio/alluxio/issues/17289 the same issue
