### ISSUE TITLE
load metadata v2 raise UnknownHostException 

### ISSUE THREAD

**Issue by wwq2333** [Alluxio/alluxio#17485]
**Alluxio Version:**
master-2.x  commit 71bd202

**Describe the bug**
when we use `alluxio fs loadMetadata -v2` to sync meta from UFS(ceph s3), it raise the UnknownHostException;
It seems that this configuration(`alluxio.underfs.s3.disable.dns.buckets:true`) does not work, the s3 host is set by `alluxio.underfs.s3.endpoint`, but the s3 client try to parse `${bucket}.${endpoint}` which is invalid ;

![image](https://github.com/Alluxio/alluxio/assets/12540485/d6fbf81f-e16c-4242-b992-93112ae1b342)

**Comment by jja725** [comment]
@elega

**Comment by elega** [comment]
fixed in https://github.com/Alluxio/alluxio/pull/17420
