### ISSUE TITLE
403 on creating s3 objects using Alluxio

### ISSUE THREAD

**Issue by kiranchitturi** [Alluxio/alluxio#17481]
I have deployed Alluxio (v2.9.3) on an EKS cluster with the below configuration

```
  alluxio.security.stale.channel.purge.interval: 365d
  alluxio.master.mount.table.root.ufs: "s3a://bucket-v2"
  alluxio.underfs.s3.region: "us-west-2"
  alluxio.underfs.s3.inherit.acl: 'false'
  alluxio.underfs.s3.default.mode: "0777"
  alluxio.user.file.writetype.default: "CACHE_THROUGH"
```

Permission is setup for Alluxio to access S3 using an IAM role that has full permissions to S3 bucket

Alluxio is able to read data now but when I try to write the data using Alluxio it fails with a 403 error

The command I ran from the master pod is 

```
 alluxio fs mkdir /iceberg_test/dir_creation 
Cannot create or load UFS directory s3a://prism-data-processing-prod-v2/iceberg_test/dir_creation: java.io.FileNotFoundException: Failed to fetch directory status s3a://prism-data-processing-prod-v2/iceberg_test/dir_creation.
```

Log from Alluxio entering the mkdirs
```
2023-05-23 18:41:11,967 DEBUG [master-rpc-executor-TPE-thread-115](UnderFileSystemWithLogging.java:1260) - Enter: Mkdirs(path=s3a://bucket-v2/iceberg_test/dir_creation, options=MkdirsOptions{createParent=false, owner=alluxio, group=alluxio, mode=rwxr-xr-x})
```

After enabling debug in the logs, I noticed that 403 occurred in the PutObject call to S3. How can I debug this more? What other configuration params need to be set to get this working? 

Is there any user mapping that needs to be done or is there a similar setting to not pass on the ACL at write time?

**Comment by ChunxuTang** [comment]
Hi @kiranchitturi, thanks for raising the question!
@jja725 Would you mind having a look at this issue? More details: https://alluxio-community.slack.com/archives/C03RDNW962C/p1684867213532909

**Comment by jja725** [comment]
@Jackson-Wang-7  @yyongycy do you have any insights into this problem?

**Comment by yyongycy** [comment]
maybe you can try directly with aws cli to see if your account works.
