### ISSUE TITLE
load metadata v2 probabilistic stuck

### ISSUE THREAD

**Issue by wwq2333** [Alluxio/alluxio#17511]
**Alluxio Version:**
master-2.x commit [71bd202](https://github.com/Alluxio/alluxio/commit/71bd2029b53c3dbd0a1c9055d0f68bfcfee4de75)

**Describe the bug**
when we use alluxio fs loadMetadata -v2 to sync meta from UFS(ceph s3), there will be a certain probability of being stuck during execution, after a forced break (ctrl-c), the master does not respond to various `alluxio fs` commands;

**Additional context**

- cmd: `alluxio fs loadMetadata -v2 -R -a -d SINGLE_LISTING /`

- load meta log ()

```
Task group id: 10
Task id: 3
State: RUNNING
Sync duration: 451434
Ops/sec: 0.0
Task info:
 TaskInfo{UFS path: s3://dataset/mdtest_1024w, AlluxioPath: /, Descendant Type: ALL, Directory Load Type: SINGLE_LISTING, Id: 3}
Task stats:
 TaskStats{Success op count={}, # of batches=0, # of objects loaded from UFS=0, # of load requests=1, # of load errors=0}
```

- folder structure (files: 16 * 640,000; single file size: 100KB)
```
├── 00
│   └── test-dir.0-0
│       └── mdtest_tree.0
......
|
└── 15
    └── test-dir.0-0
        └── mdtest_tree.0
```
- [jstack.log](https://github.com/Alluxio/alluxio/files/11595183/jstack.log)
- [profile.zip](https://github.com/Alluxio/alluxio/files/11595194/profile.zip)

**Comment by elega** [comment]
Ack. We are looking into the issue.
This seems to be a lock issue. Can you profile 3 jstacks with an interval of 30s? Thanks!

**Comment by elega** [comment]
Synced with @wwq2333 offline, the alluxio cluster used UFS journal and the async journal writer got stuck and froze the whole sync process. 
Recommended @wwq2333 to switch to use the embedded journal and the issue appeared to be gone
