### ISSUE TITLE
How to connect the master to operate the file?

### ISSUE THREAD

**Issue by coldwind6** [Alluxio/alluxio#17526]
I want to set the file ttl. Then i create the FileSystem to operate the file , but it spend a lot of time to connect the Master node than operate . the code like:
```
AlluxioProperties alluxioProperties = new AlluxioProperties();
alluxioProperties.set(PropertyKey.ZOOKEEPER_ENABLED, true);
alluxioProperties.set(PropertyKey.ZOOKEEPER_ADDRESS, zookeeperAddr);
InstancedConfiguration sConf = new InstancedConfiguration(alluxioProperties);
FileSystem fileSystem = FileSystem.Factory.create(sConf );

fileSystem.exists(alluxioUrl)
fileSystem.open(alluxioUrl);

```

I want to know is this the right way to operate the alluxio file? The fileSystem object  can reuse like define as spring bean？

**Comment by jiacheliu3** [comment]
`new InstancedConfiguration()` is expensive, please make sure you are not doing this for every FS operation.
1. The FS object can be reused.
2. The `InstancedConfiguration` object should be reused.
As long as you do the above, I think your performance should be okay at least. Please let us know if you see issues, thanks!

**Comment by coldwind6** [comment]
Thanks
