### ISSUE TITLE
Should the interface CacheFilter be an abstract class?

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#17543]
**Alluxio Version:**
2.9.3

**Describe the bug**

I attempted to implement `alluxio.client.file.cache.filter.CacheFilter` on my own, but I encountered errors when using it:
```
java.lang.NoSuchMethodException: com.facebook.presto.cache.alluxio.CacheFilterTest.<init>(alluxio.conf.AlluxioConfiguration, java.lang.String)
```
The reason is:
![image](https://github.com/Alluxio/alluxio/assets/45056332/e67b06ca-7bb3-40bc-a3d0-5d8d418aec44)

Since we have identified that the `CacheFilter` has this constructor method, why don't we make it an abstract class so that the users won't encounter any issues when implementing the `CacheFilter`?

**Comment by jiacheliu3** [comment]
@ChunxuTang  do you mind taking a look? thanks!

**Comment by beinan** [comment]
hello @humengyu2012 ,   thanks a lot for the suggestion!   I might prefer to use guice injection in alluxio 300+, then we can binding an implementation of the cache filter interface.
