### ISSUE TITLE
Fuse position read bug

### ISSUE THREAD

**Issue by bzheng888** [Alluxio/alluxio#17647]
**Alluxio Version:**
Alluxio 301

**Describe the bug**
The position read will return -1 when read position >= filesize(This can happen in fuse), then the `cp` command will throw an error.
![image](https://github.com/Alluxio/alluxio/assets/42070967/c931fa11-f4ca-4897-bbb7-29341998eb47)
**To Reproduce**
Step1: Mount the ufs or dora cluster to local mount point with fuse option -o alluxio.fuse.position.read.enabled=true
Step2: Prepare a 100mb file in the fuse mount point.
Step3: Execute the cp command, cp the 100mb file to local filesystem

**Expected behavior**
The 100mb file is copied to local filesystem without error.
**Urgency**
Urgency

**Are you planning to fix it**
https://github.com/Alluxio/alluxio/pull/17558
Try to fix this problem on fuse side.

**Comment by LuQQiu** [comment]
Solves by https://github.com/Alluxio/alluxio/pull/17558 
@HelloHorizon FYI
