### ISSUE TITLE
Support HDFS Trash when UFS is  HDFS?

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#17723]
**Is your feature request related to a problem? Please describe.**

In certain situations, the startup user of Alluxio may be configured as the superuser of HDFS, which is a very dangerous thing. For example, if a user deletes a file in Alluxio Fuse, they may not realize that they are deleting a large directory on HDFS. Therefore, we need a way to recover the deleted files.

**Describe the solution you'd like**

Change some code in `HdfsUnderFileSystem.java` like:

![image](https://github.com/Alluxio/alluxio/assets/45056332/fcf598a6-5c46-4098-9b0d-51d3bc187033)

**Comment by ChunxuTang** [comment]
Thanks for raising the feature request!

**Comment by humengyu2012** [comment]
> Thanks for raising the feature request!

We have already implemented the relevant functionality internally, and if the community needs it, we can contribute it. However, we are concerned that it may not be part of the community's plans.
