### ISSUE TITLE
Refactoring some duplicate REST APIs, such as webui_logs,webui_config,et al

### ISSUE THREAD

**Issue by chunxiaozheng** [Alluxio/alluxio#17888]
**Is your feature request related to a problem? Please describe.**
Some REST APIs, such as webui_logs, the implementation methods of these interfaces are basically the same, but they have been repeatedly implemented in both the master and worker. Can they be extracted and placed in webServer

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by jiacheliu3** [comment]
hi @chunxiaozheng thanks for the proposal!

Per our discussion, if you can keep all web URLs unchanged, we will be very happy to review and merge your refactor :)

**Comment by chunxiaozheng** [comment]
> hi @chunxiaozheng thanks for the proposal!
> 
> Per our discussion, if you can keep all web URLs unchanged, we will be very happy to review and merge your refactor :)

Thanks @jiacheliu3. If the above interface is extracted into WebServer, the prefix of the RESP API will change from api/v1/master or api/v1/worker to api/v1/common. As we discussed, it cannot be proven whether this will affect other customers, so I will close this issue.
