### ISSUE TITLE
Worker container start failed with 2.X version images

### ISSUE THREAD

**Issue by lucaspeng12138** [Alluxio/alluxio#17968]
**Alluxio Version:**
2.9.0 2.9.3

**Describe the bug**
Worker container start failed with a stack in waiting master.

**To Reproduce**
Start a cluster on Kubernetes using Alluxio version 2.9.0 or 2.9.3.

**Expected behavior**
The cluster should start successfully.

**Urgency**
High priority.

**Are you planning to fix it**
No, we may only need to cherry-pick a merge request from version 294.

**Additional context**
Please refer to the following link for more information: https://github.com/Alluxio/alluxio/pull/17163

**Comment by ssz1997** [comment]
For network problems, I recommend following this doc to do troubleshooting: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/. You could also try to start the cluster as root and install any package you need in the containers.

**Comment by lucaspeng12138** [comment]
> For network problems, I recommend following this doc to do troubleshooting: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/. You could also try to start the cluster as root and install any package you need in the containers.

I'm sorry I didn't describe the issue clearly, I found this logs, it seems no `nslookup` command
![image](https://github.com/Alluxio/alluxio/assets/100204617/6ba3ffc1-6a56-4326-8e6d-0f0434283647)

**Comment by ssz1997** [comment]
I see. You are using the chart or operator from https://github.com/Alluxio/k8s-operator? That one only works for Alluxio 3xx but not 2.x. I would recommend try 3xx out as it's more robust and performing than 2.x.

**Comment by lucaspeng12138** [comment]
> I see. You are using the chart or operator from https://github.com/Alluxio/k8s-operator? That one only works for Alluxio 3xx but not 2.x. I would recommend try 3xx out as it's more robust and performing than 2.x.

I'm using k8s-operator. I need `mount` command, so I can't use 3XX version

**Comment by ssz1997** [comment]
@lucaspeng12138 The k8s-operator doesn't support 2.x. What's the use case you need `mount` command? It's not possible to set the cluster up directly with the UFS without running `mount` later?

**Comment by lucaspeng12138** [comment]
@ssz1997 I want to mount several buckets into one alluxio...

**Comment by lucaspeng12138** [comment]
@ssz1997 

> @lucaspeng12138 The k8s-operator doesn't support 2.x. What's the use case you need `mount` command? It's not possible to set the cluster up directly with the UFS without running `mount` later?

`The k8s-operator doesn't support 2.x`, how to deploy alluxio in k8s such as 2.9.3 version?

**Comment by lucaspeng12138** [comment]
> @lucaspeng12138 The k8s-operator doesn't support 2.x. What's the use case you need `mount` command? It's not possible to set the cluster up directly with the UFS without running `mount` later?

Add I don't think this is caused by k8s-operator, it's caused by base images:

![image](https://github.com/Alluxio/alluxio/assets/100204617/ed2d6126-60c3-4070-b6c6-88646f5fce48)

**Comment by lucaspeng12138** [comment]
@ssz1997 I think I know what you means, I delete nslookup in k8s-operator can fix this problem.
