### ISSUE TITLE
When creating a directory,alluxio creates an empty file with an empty name in the aws filesystem

### ISSUE THREAD

**Issue by zhangty123321** [Alluxio/alluxio#18199]
**Alluxio Version:**
alluxio version 2.9.3

**Describe the bug**
When creating a directory,alluxio creates an empty file with an empty name in the aws filesystem, which causes other users to query this file through s3.

How do you not create empty files or make s3 users unaware

**Comment by ssz1997** [comment]
@zhangty123321 How did you create the directory?

**Comment by zhangty123321** [comment]
Use alluxio fuse's mkdir command

**Comment by zhangty123321** [comment]
> @zhangty123321 How did you create the directory?

Use alluxio fuse's mkdir command

**Comment by zhangty123321** [comment]
> @zhangty123321 How did you create the directory?

use alluxio shell mkdir command

**Comment by zhangty123321** [comment]
> @zhangty123321 How did you create the directory?
