### ISSUE TITLE
fuse模式部署Alluxio集群，训练任务无法写入宿主机路径。

### ISSUE THREAD

**Issue by yk2012985** [Alluxio/alluxio#18375]
各位好！
使用fuse pod模式通过helm在K8s集群中部署单Master集群，每一个计算节点上都启动了fuse pod并双向挂载了node的一个路径。
训练任务也通过hostPath方式挂载到了计算节点相同的路径，但任务启动后报出了节点路径拒绝写入的错误。具体报错和配置信息请看附件。
麻烦指出问题所在。
感谢！
![对应节点fuse pod报错](https://github.com/Alluxio/alluxio/assets/35766096/be77d2a5-61a1-440a-82ad-85e8cfdd1fcd)
![训练任务报错](https://github.com/Alluxio/alluxio/assets/35766096/506c74da-a346-4fc7-a80a-46f3f064fbba)
[Alluxio配置信息.zip](https://github.com/Alluxio/alluxio/files/13262189/Alluxio.zip)

**Comment by humengyu2012** [comment]
这个报错是alluxio客户端向alluxio集群写入的时候报错还是fuse进程向宿主机目录写入的时候报错？

**Comment by humengyu2012** [comment]
@yk2012985 如果是写入alluxio集群时报错，尝试以一个权限比较高的用户（或者是目录的owner）来访问 alluxio，用这个配置：
```
alluxio.security.login.username=alluxio
```

**Comment by yk2012985** [comment]
> 这个报错是alluxio客户端向alluxio集群写入的时候报错还是fuse进程向宿主机目录写入的时候报错？

fuse进程向宿主机写入时报错

**Comment by yk2012985** [comment]
> @yk2012985 如果是写入alluxio集群时报错，尝试以一个权限比较高的用户（或者是目录的owner）来访问 alluxio，用这个配置：
> 
> ```
> alluxio.security.login.username=alluxio
> ```

解决了，谢谢！
