### ISSUE TITLE
Prometheus metrics with label values in names.

### ISSUE THREAD

**Issue by PigNatovsky** [Alluxio/alluxio#18413]
**Alluxio Version:**
2.9.3

**Describe the bug**
Alluxio produces crazy amount of metrics __names__ - some of them contains params in names instead of labels values. In our cluster, worker related metrics names has 118435 values.  For example: 
`Worker_ActiveClients_host1_name` instead of `Worker_ActiveClients` with label `instance` and a value `host1_name`.

My blind shot is that this is related witd dropwizard library and a way in which metrics names are created (it's somehow related to how Grapphite handles tags).

**To Reproduce**
Just enable Prometheus metrics in Your cluster.

**Expected behavior**
In my opinion metrics should have short and consistent list of names and labels that are responsible for dimensions.

**Urgency**
It's not a very urgent topic, but for sure it will be much easier to monitor Alluxio clusters.

**Are you planning to fix it**
I think that my programming skills ale too low for that. 

**Additional context**
Generally users can use metric relabels, but at some point those relabels will be really, really expensive in terms of resources.

**Comment by PigNatovsky** [comment]
It will be nice if someone can say few words about that - it's still hard to track available metrics.

**Comment by YichuanSun** [comment]
Thanks for your advice! We will take a look soon. WDYT? @Kai-Zhang
