### ISSUE TITLE
"job load" encountered NOT_FOUND even the path exists

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#18463]
**Alluxio Version:**
alluxio-308-SNAPSHOT

**Describe the bug**
"job load" encountered the NOT_FOUND exception even the path exists

**To Reproduce**
"alluxio-site.properties" has the following configuration

```
alluxio.dora.client.ufs.root=hdfs://dev/user/test/alluxio
```

"alluxio fs ls" works well

```
$ ./bin/alluxio fs ls /
drwxr-xr-x  zhaoqun.deng   zhaoqun.deng                 0                 11-23-2023 16:07:26:303  DIR /dir.01
-rw-rw-r--  zhaoqun.deng   zhaoqun.deng              1366                 10-03-2023 15:57:58:354 FILE /file.01
-rw-rw-r--  zhaoqun.deng   zhaoqun.deng              1366                 10-03-2023 16:04:48:995 FILE /file.02
```

but "alluxio fs job load" failed with the Exception "NOT_FOUND"

```
$ ./bin/alluxio job load --path /dir.01 --submit
Failed to submit load job /dir.01: NOT_FOUND: /dir.01
Error: error running load
 --- at /tmp/alluxio459172732/cli/src/alluxio.org/cli/env/command.go:115 (BaseJavaCommand.RunWithIO) ---
Caused by: exit status 255
Usage:
  bin/alluxio job load [flags]
```

**Expected behavior**
The path should exists.

**Are you planning to fix it**
Yes

**Comment by humengyu2012** [comment]
Could you paste detail logs, in `$ALLUXIO_LOG_DIR/user/xxx.log`.

**Comment by secfree** [comment]
Found the "path" parameter needs to be the full UFS path. For the above case, the following command worked

```
./bin/alluxio job load --path hdfs://dev/user/test/alluxio/dir.01 --submit
```

May I know if this is expected? @jja725 Thanks.

**Comment by jja725** [comment]
yes it's expected since we want to use ufs full path more at master/worker side instead of relying on the single root

**Comment by secfree** [comment]
I see. Thank your for your clarification.
