### ISSUE TITLE
alluxio2.9.3 An error occurs in the /bin/alluxio format command

### ISSUE THREAD

**Issue by fantastic2085** [Alluxio/alluxio#18475]
**Alluxio Version:**
What version of Alluxio are you using?
alluxio2.9.3

**Describe the bug**
/bin/alluxio format
![image](https://github.com/Alluxio/alluxio/assets/4116773/80db5214-d55f-4342-95cd-40ca1114be7f)

system info：
![f7e15a52590418229c42fee830f38f7](https://github.com/Alluxio/alluxio/assets/4116773/be0619ce-737a-4608-a7a3-04764373060f)

java：
![7dfce9278587ff3b3a113524a3bb11f](https://github.com/Alluxio/alluxio/assets/4116773/3d585fb0-85ea-4412-97d0-5d699b9f652a)

logs:
[logs.zip](https://github.com/Alluxio/alluxio/files/13734764/logs.zip)

/etc/hosts
![image](https://github.com/Alluxio/alluxio/assets/4116773/4ef0c551-bed2-4d10-a8e1-cc33da9174f4)

conf：
[conf.zip](https://github.com/Alluxio/alluxio/files/13734796/conf.zip)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by humengyu2012** [comment]
Have you configured passwordless SSH login among all master nodes?

**Comment by fantastic2085** [comment]
ssh pairwise non-encryption has been configured @humengyu2012

**Comment by fantastic2085** [comment]
@humengyu2012  The root user of the system has already been granted password free access

**Comment by humengyu2012** [comment]
Please check whether the dir exists:
```
[2023-12-21 11:15:16][node02] 2023-12-21 11:15:16,632 INFO  [main](Format.java:134) - Formatting Data path for tier 0:/mnt/ramdisk/alluxioworker
[2023-12-21 11:15:16][node02] 2023-12-21 11:15:16,635 ERROR [main](Format.java:97) - Failed to format
```
