### ISSUE TITLE
Is alluxio@305 an official version?Whether it has changed a lot, can you give me a document description?

### ISSUE THREAD

**Issue by fubingting** [Alluxio/alluxio#18489]
**Is alluxio@305 an official version?Whether it has changed a lot, can you give me a document description?Thanks**
Download address: https://downloads.alluxio.io/downloads/files/305/
**1.When I execute alluxio-h, it looks like this,It is very different from the previous version,There are no orders such as alluxio format.:**
```
Usage:
  bin/alluxio info [command]

Available Commands:
  cache       Reports worker capacity information
  collect     Collects information such as logs, config, metrics, and more from the running Alluxio cluster and bundle into a single tarball
  doctor      Runs doctor configuration or storage command
  nodes       Show all registered workers' status
  report      Reports Alluxio running cluster information
  version     Print Alluxio version.
```
**2.When I execute bin/alluxio on aarch64, the error will be as follows. I need to change alluxioCli-Linux-arm64 to alluxioCli-Linux-aarch64.**
```
./alluxio: line 29: /home/bin/../cli/src/alluxio.org/cli/bin/alluxioCli-Linux-aarch64: No such file or directory
```

**Comment by jasondrogba** [comment]
you can read the blog [Introducing DORA: The Next-generation Alluxio Architecture](https://www.alluxio.io/blog/introducing-dora-the-next-generation-alluxio-architecture/), to know about the newly DORA Architecture in Alluxio 3.x
[User Command](https://docs.alluxio.io/ee-ai/user/stable/en/operation/User-CLI.html) is about the user command in alluxio 3.x

**Comment by jasondrogba** [comment]
The problem about executing bin/alluxio on aarch64
do you have a arm64 machine? maybe you build alluxio in a arm64 machine, then generate file `alluxioCli-Linux-arm64`, but you run the command in aarch64 machine.
you can look `build/cli/build-cli.sh`

**Comment by fubingting** [comment]
> The problem about executing bin/alluxio on aarch64 do you have a arm64 machine? maybe you build alluxio in a arm64 machine, then generate file `alluxioCli-Linux-arm64`, but you run the command in aarch64 machine. you can look `build/cli/build-cli.sh`

I use the binary package of the official website. There is nothing wrong with the previous version, but now there is a problem with aarch64/arm64. url:https://downloads.alluxio.io/downloads/files/309/alluxio-309-bin.tar.gz

**Comment by fubingting** [comment]
How should the tar package be compiled with source code? Is it okay to execute build-cli.sh? Don't I need maven compilation?

**Comment by jasondrogba** [comment]
[Building Alluxio From Source
](https://docs.alluxio.io/os/user/stable/en/contributor/Building-Alluxio-From-Source.html#:~:text=To%20speed%20up%20the%20compilation%2C%20you%20can%20run%20the%20following%20instruction%20to%20skip%20different%20checks%3A)

**Comment by jasondrogba** [comment]
you can watch commit https://github.com/Alluxio/alluxio/commit/236081939cc6510ca9a8a2774edeed75dbac79a5 and you can replace to aarch64
if you have the source code, only need to build the cli code with the command `./build/cli/build-cli.sh -a`

**Comment by fubingting** [comment]
> @fubingting you can watch commit [2360819](https://github.com/Alluxio/alluxio/commit/236081939cc6510ca9a8a2774edeed75dbac79a5) and you can replace to aarch64 if you have the source code, only need to build the cli code with the command `./build/cli/build-cli.sh -a`

Thanks very much.  It has been successfully built from the source code.

**Comment by jasondrogba** [comment]
@fubingting Can you tell me what your environment is and why you need to use an aarch64 machine? I think this will help Alluxio to improve the code. If you need more help, welcome to join [slack](https://alluxio.io/slack)

**Comment by lillianokok** [comment]
> @fubingting你可以看commit [2360819](https://github.com/Alluxio/alluxio/commit/236081939cc6510ca9a8a2774edeed75dbac79a5) ， 如果你有源代码，你可以替换为aarch64 ，只需要使用命令构建cli代码`./build/cli/build-cli.sh -a`

运行这个构建代码，自测用例也会被编译吗？我需要用什么方式把自测用例执行起来啊？

**Comment by jasondrogba** [comment]
> 运行这个构建代码，自测用例也会被编译吗？我需要用什么方式把自测用例执行起来啊？

@lillianokok 你指的是什么自测用例？`./build/cli/build-cli.sh -a`只会编译构建cli部分的代码
