### ISSUE TITLE
alluxio-fuse mount with libfuse2 encountered "undefined symbol: fuse_main_real"

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#18513]
**Alluxio Version:**
v308

**Describe the bug**
alluxio-fuse mount with libfuse3 is ok but using libfuse2 encountered the following exception

```
$ ./dora/integration/fuse/bin/alluxio-fuse mount o3fs://alluxio.test.dev/ /mnt/data/
Mounting o3fs://alluxio.test.dev/ to /mnt/data
.............................................................
[2024-02-07T06:46:41+0000]: Failed to mount ufs path o3fs://alluxio.test.dev/ to local mount point /mnt/data.
ERROR ../../src/main/native/libjnifuse/jnifuse_helper.cc:34 Validate standard errors can be logged as expected
/usr/lib/jvm/java-8-openjdk-amd64/bin/java: symbol lookup error: /tmp/libjnifuse5856113114345062784.so: undefined symbol: fuse_main_real
```

**To Reproduce**

Add the following configuration to alluxio-site.properties

```
alluxio.underfs.version=1.2.1
alluxio.underfs.hdfs.configuration=./conf/ozone-site.xml
alluxio.dora.client.ufs.root=o3fs://alluxio.test.dev/
alluxio.dora.enabled=false
alluxio.fuse.jnifuse.libfuse.version=2
```

and mount with the following command

```
./dora/integration/fuse/bin/alluxio-fuse mount o3fs://alluxio.test.dev/ /mnt/data/
```

**Expected behavior**
mount should succeed

**Comment by lucyge2022** [comment]
Thanks for creating the issue! Will fix the libjnifuse.so build right away.

**Comment by lucyge2022** [comment]
Hi @secfree    The fix is merged into main branch now with this commit : https://github.com/Alluxio/alluxio/commit/0fb4043a5cbeaa0091072f33822784b1d9926ad1

Please try again to verify if it fixes your issue, thanks!
