### ISSUE TITLE
Collector already registered that provides name: jmx_exporter_build_info

### ISSUE THREAD

**Issue by ziyangRen** [Alluxio/alluxio#18547]
**Alluxio Version:**
Alluxio 2.9.3

**Describe the bug**
我在启动时添加了javaagent，导致了报错无法启动Alluxio，我的alluxio-env.sh配置文件见下：
![image](https://github.com/Alluxio/alluxio/assets/83994958/3132f2fc-349a-4a16-a2f3-8c7b8d45e1e7)
我得到了如下的报错：
![image](https://github.com/Alluxio/alluxio/assets/83994958/158ade81-e910-4554-98e1-4bc91d981324)

**Comment by jasondrogba** [comment]
https://github.com/prometheus/jmx_exporter/issues/290
>You got your invocation wrong, that only happens if you load the javaagent twice into the same JVM.

did you also set `ALLUXIO_MASTER_JAVA_OPTS`, you can refer to [ALLUXIO_JAVA_OPTS](https://docs.alluxio.io/os/user/stable/en/operation/Configuration.html?q=alluxio-env#:~:text=the%20Alluxio%20servers.-,ALLUXIO_JAVA_OPTS,-Java%20VM%20options)

Java VM options for the Alluxio master, worker, and shell commands. By default, ALLUXIO_JAVA_OPTS is prepended to other ALLUXIO_*_JAVA_OPTS environment variables, such as ALLUXIO_MASTER_JAVA_OPTS and ALLUXIO_USER_JAVA_OPTS.
