### ISSUE TITLE
About pre-apply in JournalSystem

### ISSUE THREAD

**Issue by QueenOfBees** [Alluxio/alluxio#18558]
**Alluxio Version:**
release-310

**Describe the bug**

Let's say we have a x = 3 in memory

write request:
 try (JournalContext c = journal.createJournalContext()) {
      x = 3
      c.append(exampleBlockJournalEntry);
  }

read request:
return x
  
if the leader node lost leadership while flushing pending jounal (network reason/long time gc),
the read request will see x = 3 immediately, that means we read a uncommited change,  is this correct?

I'd appreciate it if you could give me a hint.

**To Reproduce**

**Expected behavior**

**Urgency**

**Are you planning to fix it**

**Additional context**

**Comment by QueenOfBees** [comment]
my another conflusion is: what's the benefit of pre-apply exactly.
"avoid journaling operations which do not result in state modification" (comment of RaftJounalSystem)，which is difficult to understand

**Comment by YichuanSun** [comment]
Actually now we have no leading node in Alluxio 3.x, Alluxio 3.x is a decentralized architecture.
