### ISSUE TITLE
Neither Master.InodeHeapSize nor Master.BlockHeapSize can be found in metrics/json

### ISSUE THREAD

**Issue by ziyangRen** [Alluxio/alluxio#18562]
**Alluxio Version:**
2.9.3

**Describe the bug**
Neither Master.InodeHeapSize nor Master.BlockHeapSize can be found in metrics/json
![image](https://github.com/Alluxio/alluxio/assets/83994958/eaf3837b-3ea9-4de8-97ce-4071c449faf0)

**Comment by jasondrogba** [comment]
Have you set the master's metrics correctly?
https://docs.alluxio.io/os/user/stable/en/operation/Metrics-System.html#usage
>You can send an HTTP request to /metrics/json/ of the target Alluxio processes to get a snapshot of all metrics in JSON format.

**Comment by YichuanSun** [comment]
Close due to no response.
