### ISSUE TITLE
Data consistency issue

### ISSUE THREAD

**Issue by yzcwf** [Alluxio/alluxio#18571]
If Alluxio detects that the source data in UFS has changed during the data reading process, how will it handle it? Will this reading process directly report an error?

**Comment by Kakarot163** [comment]
If you set the config `alluxio.user.file.metadata.sync.interval = 0` in file "conf/alluxio-site.properties", when Alluxio detects that the source data in UFS has changed, data in alluxio will be Invalid，the reading process will go to UFS to get the data.
