### ISSUE TITLE
[Deploy]alluxio-worker has been unable to work

### ISSUE THREAD

**Issue by edenbuaa** [Alluxio/alluxio#18620]
**Alluxio Version:**
v2.9.3

 Deploy alluxio v2.9.3 in k8s(single node), the alluxio-master is running normally, but alluxio-worker pod always restart and there's only one log :

![image](https://github.com/Alluxio/alluxio/assets/16248697/8a2e95c5-1f8a-4b16-934f-836b81e5d8e1)

The pod events show:

![image](https://github.com/Alluxio/alluxio/assets/16248697/35bd7746-0baa-46a2-955d-73918627ecef)

Cloud you have a look and find out the problem? thanks a lot.

**Comment by YichuanSun** [comment]
Can the master and worker pod connect with each other? Ensure that there are no network policies or firewalls blocking communication between the Alluxio master and worker pods. If the network works, please give us more background information, such as the K8s configurations and alluxio configurations.

**Comment by edenbuaa** [comment]
The issue was found to be related to the `hostname` of master.  alluxio worker doesn't work if use like `'127.0.0.1'` or `localhost`

**Comment by YichuanSun** [comment]
@jasondrogba Do you have any idea? I'm not familiar with k8s.
