### ISSUE TITLE
alluxio.user.file.readtype.default can not by set by user.

### ISSUE THREAD

**Issue by cenyuhai** [Alluxio/alluxio#3022]
User can not set alluxio.user.file.readtype.default, it is CACHE by default.

**Comment by uronce-cc** [comment]
@cenyuhai Please report any issue to the jira system https://alluxio.atlassian.net/secure/Dashboard.jspa.

**Comment by cenyuhai** [comment]
@uronce-cc I can not create an account in that site.

**Comment by yupeng9** [comment]
@cenyuhai Can you post the question to the user mailing list  https://groups.google.com/forum/?fromgroups#!forum/alluxio-users ? Thanks.
