### ISSUE TITLE
问题：120G以上数据上传时，会出现Connection reset

### ISSUE THREAD

**Issue by vainly** [Alluxio/alluxio#3023]
因为tachyon client 初始化后是单例的，我基于源码做了修改，允许其多实例，但是，上传文件时，数据量在120G以上时，会出现Connection reset问题，我们是不是有些地方没有注意到，能否解答一下。多客户端是因为我们会根据数据源不同，上传文件到不同的tachyon中。

**Comment by apc999** [comment]
hi @vainly , for alluxio project, we use this mail list: https://groups.google.com/forum/#!forum/alluxio-users to post questions when using the system. Could you post your question there where more people will be able to see it and help you?

**Comment by apc999** [comment]
close this issue for now, let me know (binfan@alluxio.com) if you have questions in posting the question on the mail list, I will be happy to help.
