### ISSUE TITLE
Command 'persist'

### ISSUE THREAD

**Issue by 900827zy** [Alluxio/alluxio#3281]
I am new to Alluxio. Recently, I study and exercise alluxio on my compute. And I got a problem which makes me puzzled.
Firstly, I entry ${alluxio_home}, execute command "touch hello", then "echo 'hello world' > hello", and do "copyFromLocal" to put file to alluxio; 
Secondly, do command "bin/alluxio fs persist /hello";
Thirdly, restart alluxio.
After this steps, I could still get data in file(/hello) by "bin/alluxio fs cat /hello". But if skip the second step, I only get "Block xxx is not available in Alluxio". Although I can see the file by "bin/alluxio fs ls /".
How can I get the file back to alluxio. Please help me.

**Comment by haoyuan** [comment]
Please post your question here: https://groups.google.com/forum/?fromgroups#!forum/alluxio-users

If you can't access the above link, please post your question here: http://alluxio-users.85194.x6.nabble.com/
