### ISSUE TITLE
Frame size (1213486160) larger than max length (16384000) ,how to fix it ? sos

### ISSUE THREAD

**Issue by KerwinZeng** [Alluxio/alluxio#3414]
FILENAME:  test.cdr     FILESIZE:2GB

spark-shell :
........
scala> val sogou1=sc.textFile("alluxio://nn1:19888/user/zengke/test.cdr")
....
scala> sogou1.cache()
...
scala> sogou1.count()
16/05/31 21:08:49 INFO logger.type: initialize(alluxio://nn1:19888/user/zengke/test.cdr, Configuration: core-default.xml, core-site.xml, mapred-default.xml, mapred-site.xml, yarn-default.xml, yarn-site.xml, hdfs-default.xml, hdfs-site.xml). Connecting to Alluxio: alluxio://nn1:19888/user/zengke/test.cdr
16/05/31 21:08:49 INFO logger.type: Loading Alluxio properties from Hadoop configuration: {}
16/05/31 21:08:49 INFO logger.type: Alluxio client (version 1.0.1) is trying to connect with FileSystemMasterClient master @ nn1/*.*.*.*:19888
16/05/31 21:08:49 INFO logger.type: Client registered with FileSystemMasterClient master @ nn1/132.121.94.197:19888
java.io.IOException: Frame size (1213486160) larger than max length (16384000)!
        at alluxio.AbstractClient.checkVersion(AbstractClient.java:109)
        at alluxio.AbstractClient.connect(AbstractClient.java:172)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:291)
        at alluxio.client.file.FileSystemMasterClient.getUfsAddress(FileSystemMasterClient.java:255)
        at alluxio.hadoop.AbstractFileSystem.getUfsAddress(AbstractFileSystem.java:598)
        at alluxio.hadoop.AbstractFileSystem.initialize(AbstractFileSystem.java:440)

**Comment by haoyuan** [comment]
Please post your question at our user mailing list: https://groups.google.com/forum/?fromgroups#!forum/alluxio-users

If you can't access the above link, please post your question its mirror: http://alluxio-users.85194.x6.nabble.com/

**Comment by KerwinZeng** [comment]
Sorry , alluxio port is wrong. 
bad uri:alluxio://nn1:19888/user/zengke/test.cdr
correct uri:alluxio://nn1:19998/user/zengke/test.cdr

**Comment by haoyuan** [comment]
Glad it works. Thanks for the updates.

**Comment by KerwinZeng** [comment]
THANKS !
