### ISSUE TITLE
文档写的还是很粗糙

### ISSUE THREAD

**Issue by wjw465150** [Alluxio/alluxio#3420]
1.01版的文档全部看完,感觉还是很粗糙.能否有一篇完善的"Alluxio完全分布式参考指南(包含master的运行,worker的运行,故障节点移除/添加)"?

**Comment by rorovic** [comment]
同意楼主！可能功能完善了很多！文档略微有点滞后。

**Comment by darionyaphet** [comment]
写过文档的人都知道这东西很不好写  字字斟酌  句句计较  宽容一些吧

**Comment by apc999** [comment]
我是Alluxio项目的maintainer. 谢谢大家的反馈. 完全同意@wjw465150关于"Alluxio完全分布式参考指南"的意见. 我会转达给文档的maintainer. 

关于Alluxio社区内的Issues汇报和讨论, 请使用我们的用户邮件列表https://groups.google.com/forum/#!forum/alluxio-users, 墙内用户可以使用如下的列表镜像: http://alluxio-users.85194.x6.nabble.com/
github的这个Issue我会关闭. 希望能在maillist上见到大家
