### ISSUE TITLE
单机运行web UI一直报错

### ISSUE THREAD

**Issue by sd4324530** [Alluxio/alluxio#3547]
单机安装hadoop 2.7.2
alluxio版本 1.1.0 修改pom hadoop版本号为2.7.2
服务器jdk版本 1.8_92
本机编译通过（各种踩坑，甚至源码里竟然有引用测试包里的类- -）
format的时候出现
Pseudo-terminal will not be allocated because stdin is not a terminal.
无视之
启动后，19999 30000的页面都出现500错误
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP

PWC6199: Generated servlet error:
The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files
尝试1：升级jetty版本到8.1，不行
尝试2：修改pom里的java.version到1.8，不行

只是页面不行，文件系统本身的使用都可以，接入hdfs，spark都没问题

**Comment by sd4324530** [comment]
集群安装也尝试了
版本1.0.1
hadoop版本2.2.0
jdk 1.8_60
19999页面正常
30000页面出现500，而且错误和上面不太一样
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP

PWC6199: Generated servlet error:
The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files

**Comment by pfxuan** [comment]
@sd4324530 , 情改用jdk1.8.0_77或者以下JDK版本，详情参见：
https://groups.google.com/forum/#!topic/alluxio-users/H1mcoZY77F8

**Comment by sd4324530** [comment]
@pfxuan 降低jdk版本果然就可以了，是不是说明这个是最新版本的jdk里的bug导致的呢？
能否通过代码的修改避开这个问题呢？要不然真心有点郁闷

**Comment by pfxuan** [comment]
@sd4324530 关于这个问题的详细讨论可以参考：
https://alluxio.atlassian.net/browse/ALLUXIO-1956
https://github.com/Alluxio/alluxio/pull/3546

**Comment by aaudiber** [comment]
Please post questions here: https://groups.google.com/forum/?fromgroups#!forum/alluxio-users
