### ISSUE TITLE
Issue when "Alluxio Standalone on a Cluster"

### ISSUE THREAD

**Issue by jiangyuhe123** [Alluxio/alluxio#4459]
2016-12-20 05:02:43,542
   INFO MASTER  Connecting to node1 as hadoop...
2016-12-20 05:02:43,549
   INFO MASTER  Connecting to node2 as hadoop...
2016-12-20 05:02:43,555
   INFO MASTER  Connecting to node3 as hadoop...

which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)

dirname: 缺少操作数

Try 'dirname --help' for more information.

Formatting Alluxio Worker @ node1

/home/hadoop/alluxio-1.3.0/bin/alluxio:行166: /../bin/java: 没有那个文件或目录

Connection to node1 closed.

which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)

dirname: 缺少操作数

Try 'dirname --help' for more information.

Formatting Alluxio Worker @ node3

/home/hadoop/alluxio-1.3.0/bin/alluxio:行166: /../bin/java: 没有那个文件或目录

Connection to node3 closed.

which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)

dirname: 缺少操作数

Try 'dirname --help' for more information.

Formatting Alluxio Worker @ node2

/home/hadoop/alluxio-1.3.0/bin/alluxio:行166: /../bin/java: 没有那个文件或目录

Connection to node2 closed.

**Comment by haoyuan** [comment]
Thanks for the interest. Please post questions at our user mailing list: https://groups.google.com/forum/?fromgroups#!forum/alluxio-users or its mirror: http://alluxio-users.85194.x6.nabble.com/
