### ISSUE TITLE
alluxio比较hdfs性能没有明显提升

### ISSUE THREAD

**Issue by cafe-babe** [Alluxio/alluxio#4551]
/tmp/spark.test文件存放在alluxio中，显示在内存里
![image](https://cloud.githubusercontent.com/assets/7964537/21637466/edef15a6-d2a1-11e6-9420-7c737457ec6c.png)

从alluxio中读取，然后count()，速度没有比hdfs明显快，而且第二次执行速度也没有明显提升
![image](https://cloud.githubusercontent.com/assets/7964537/21637552/5b94206a-d2a2-11e6-82bb-665956d0f7f7.png)
5000万行的统计大概耗时13秒。

请问一下，是我测试的方式不对吗？

**Comment by apc999** [comment]
@cafe-babe  could you post questions in [user mail list](https://groups.google.com/forum/?fromgroups#!forum/alluxio-users) ? Alluxio uses github to track development and usage related questions will be visible and answered by the community in the user mail list. In case you can not access it, it has a mirror site [here](http://alluxio-users.85194.x6.nabble.com)
