### ISSUE TITLE
Cannot start tachyon with 0.5.0

### ISSUE THREAD

**Issue by DannyGuoHT** [Alluxio/alluxio#456]
1. tar jar package
2. cp tachyon-env.sh.template tachyon-env.sh
3. modify "export TACHYON_UNDERFS_ADDRESS=/tmp"
4. ./bin/tachyon-start.sh local
   print：
   Killed 0 processes
   Killed 0 processes
   Connection to localhost... root@localhost's password: 
   Killed 0 processes
   Connection to localhost closed.
   Formatting RamFS: /mnt/ramdisk (1gb)
   Starting master @ localhost
   Starting worker @ hdh139
   and nothing in log/

what's wrong ?Thanks

**Comment by guotong1988** [comment]
Could not find or load main class tachyon.Format

**Comment by guotong1988** [comment]
错误: 找不到或无法加载主类 tachyon.Format

**Comment by johncolezhang** [comment]
the link here is invalid, i can't find `Running-Tachyon-Locally.html`

**Comment by haoyuan** [comment]
http://www.alluxio.org/documentation/v1.0.1/en/
