### ISSUE TITLE
Compile error with Alluxio 1.4.0: some repository not available now

### ISSUE THREAD

**Issue by GeLiXin** [Alluxio/alluxio#5511]
Linux ubuntu 4.8.0-36-generic
Compile Alluxio 1.4.0 release with maven command: mvn clean package -Djava.version=1.8 -Dhadoop.version=2.6.0 -Dspark.version=2.0.0 -DskipTests

Some repository is not available for download now, and the error message is:

[INFO] ------------------------------------------------------------------------
[INFO] Building Alluxio Integration - FUSE 1.4.0
[INFO] ------------------------------------------------------------------------
Downloading: https://repo1.maven.org/maven2/com/github/serceman/jnr-fuse/0.3/jnr-fuse-0.3.pom
Downloading: https://repository.apache.org/content/repositories/releases/com/github/serceman/jnr-fuse/0.3/jnr-fuse-0.3.pom
Downloading: https://repository.cloudera.com/artifactory/cloudera-repos/com/github/serceman/jnr-fuse/0.3/jnr-fuse-0.3.pom
Downloading: http://repository.mapr.com/maven/com/github/serceman/jnr-fuse/0.3/jnr-fuse-0.3.pom
Downloading: http://repo.spring.io/libs-release/com/github/serceman/jnr-fuse/0.3/jnr-fuse-0.3.pom
Downloading: http://repo.hortonworks.com/content/repositories/releases/com/github/serceman/jnr-fuse/0.3/jnr-fuse-0.3.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Alluxio Parent ..................................... SUCCESS [  9.554 s]
[INFO] Alluxio Core ....................................... SUCCESS [  1.574 s]
[INFO] Alluxio Core - Common Utilities .................... SUCCESS [02:36 min]
[INFO] Alluxio Under File System .......................... SUCCESS [  1.228 s]
[INFO] Alluxio Under File System - Local FS ............... SUCCESS [ 12.796 s]
[INFO] Alluxio Under File System - HDFS ................... SUCCESS [ 59.585 s]
[INFO] Alluxio Under File System - Gluster FS ............. SUCCESS [ 26.364 s]
[INFO] Alluxio Under File System - Aliyun OSS ............. SUCCESS [ 25.848 s]
[INFO] Alluxio Under File System - Swift .................. SUCCESS [ 20.866 s]
[INFO] Alluxio Under File System - S3 ..................... SUCCESS [01:17 min]
[INFO] Alluxio Under File System - S3A .................... SUCCESS [ 21.734 s]
[INFO] Alluxio Under File System - GCS .................... SUCCESS [ 12.494 s]
[INFO] Alluxio Core - Client .............................. SUCCESS [01:00 min]
[INFO] Alluxio Core - Server .............................. SUCCESS [10:08 min]
[INFO] Alluxio Key Value .................................. SUCCESS [  1.183 s]
[INFO] Alluxio Key Value - Common Utilities ............... SUCCESS [ 30.647 s]
[INFO] Alluxio Key Value - Client ......................... SUCCESS [ 17.501 s]
[INFO] Alluxio Key Value - Server ......................... SUCCESS [ 15.547 s]
[INFO] Alluxio Shell ...................................... SUCCESS [ 23.666 s]
[INFO] Alluxio Examples ................................... SUCCESS [ 21.345 s]
[INFO] Alluxio MiniCluster ................................ SUCCESS [ 17.906 s]
[INFO] Alluxio Tests ...................................... SUCCESS [ 21.907 s]
[INFO] Alluxio Integration ................................ SUCCESS [  1.275 s]
[INFO] Alluxio Assemblies ................................. SUCCESS [ 15.807 s]
[INFO] Alluxio Integration - FUSE ......................... FAILURE [02:16 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23:19 min
[INFO] Finished at: 2017-05-28T21:16:47-07:00
[INFO] Final Memory: 104M/322M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project alluxio-integration-fuse: Could not resolve dependencies for project org.alluxio:alluxio-integration-fuse:jar:1.4.0: Failed to collect dependencies at com.github.serceman:jnr-fuse:jar:0.3: Failed to read artifact descriptor for com.github.serceman:jnr-fuse:jar:0.3: Could not transfer artifact com.github.serceman:jnr-fuse:pom:0.3 from/to spring-releases (http://repo.spring.io/libs-release): Connect to repo.spring.io:80 [repo.spring.io/35.186.232.213] failed: Connection timed out (Connection timed out) -> [Help 1]

What should I do to resolve this?

**Comment by yupeng9** [comment]
@GeLiXin 

Thanks for checking out Alluxio. Please post the question to the [user mailing list](https://groups.google.com/forum/?fromgroups#!forum/alluxio-users). If you cannot access Google, you can use this [mirror](http://alluxio-users.85194.x6.nabble.com/).
