### ISSUE TITLE
how to append data into alluxio

### ISSUE THREAD

**Issue by jeromeheng** [Alluxio/alluxio#5533]
I want to write data into alluxio,but i don't know how to execute it , and  the doc can not take this funcution to me, so I hope you can help me , thanks !

**Comment by yupeng9** [comment]
@jeromeheng 

Thanks for checking out Alluxio. Please post the question to the [user mailing list](https://groups.google.com/forum/?fromgroups#!forum/alluxio-users). If you cannot access Google, you can use this [mirror](http://alluxio-users.85194.x6.nabble.com/).
