### ISSUE TITLE
Alluxio speed when data set is small

### ISSUE THREAD

**Issue by HorizonVoice** [Alluxio/alluxio#6611]
I have done some experiments, and I found Spark cache (persist on memory) is faster than Alluxio when data set is small. Why this happen?

**Comment by gurmeetb** [comment]
Since all issues are referenced/addressed via JIRA tickets, can you open one ticket here - https://alluxio.atlassian.net/projects/ALLUXIO/ ?

**Comment by HorizonVoice** [comment]
@gurmeetb Sure, Thanks
