### ISSUE TITLE
I could not download alluxio-bin.tar.gz from the alluxio index in Shanghai ,China!

### ISSUE THREAD

**Issue by YinChunGuang** [Alluxio/alluxio#7068]
I could not download alluxio-bin.tar.gz from the alluxio index  in Shanghai ,China!

**Comment by aaudiber** [comment]
Hello @YinChunGuang,

What version are you having trouble with? Are you downloading through [https://alluxio.org/download](https://alluxio.org/download)?

**Comment by aaudiber** [comment]
Closing this for now - see https://github.com/Alluxio/alluxio/issues/329
