### ISSUE TITLE
FastDFS适合作为底层存储吗？

### ISSUE THREAD

**Issue by DPnice** [Alluxio/alluxio#8180]
想要开发底层存储扩展，想用FastDFS作为底层存储，FastDFS适合作为Alluxio的底层存储吗？

**Comment by apc999** [comment]
Hi @DPnice , sorry  I know very little about FastDFS to comment on whether FastDFS is a good choice as Alluxio UFS. 
In case you are interested in creating a new UFS adaptor in general, here is the guideline for developers:
http://www.alluxio.org/docs/1.8/en/ufs/Ufs-Extension-API.html

**Comment by apc999** [comment]
@DPnice  do you still need more info on this? If not, I would close this issue later. You may continue the discussion on our mailing list (https://groups.google.com/forum/#!forum/alluxio-users) on this topic.

**Comment by DPnice** [comment]
Thank you. FastDFS is not suitable for Alluxio's underlying storage. SeaweedFS seems to be suitable.

**Comment by apc999** [comment]
do you have any particular target use case in mind? To my knowledge, SeaweedFS is similar to Haystack and designed for massive amount of small files (like images). Is this your target data to store?

**Comment by apc999** [comment]
@DPnice I've seen no update here after 7 days. close this PR for now. feel free to let me know if you have more comments.

**Comment by DPnice** [comment]
> do you have any particular target use case in mind? To my knowledge, SeaweedFS is similar to Haystack and designed for massive amount of small files (like images). Is this your target data to store?

Sorry for not replying in time.Yes, most of the data size is 10-1024M.
