### ISSUE TITLE
Issue when running Alluxio-Fuse

### ISSUE THREAD

**Issue by Yar0myr** [Alluxio/alluxio#8207]
Hi Guys,

We've encountered a problem when running alluxio-fuse. Here is the message we get - "/entrypoint.sh: line 99: integration/docker/bin/alluxio-job-worker.sh: No such file or directory"

A bit more context we are trying to run it on AWS ECS, Fargate launch type.

Any ideas how to fix it?

**Comment by apc999** [comment]
@Yar0myr which version of Alluxio are you running? `alluxio-job-worker.sh` is only introduced in master branch. We suggest to go with released version from here http://www.alluxio.org/download

**Comment by apc999** [comment]
@Yar0myr do you still have this issue or have your problem solved? Mind sharing your solution in this case?
