### ISSUE TITLE
Integration with hive error

### ISSUE THREAD

**Issue by zjfplayer** [Alluxio/alluxio#8214]
I have completed the configuration of Hadoop-MapReduce.md and HDFS.md and Hive.md, and passed the test in the example：

> hive> CREATE TABLE u_user (
>     > userid INT,
>     > age INT,
>     > gender CHAR(1),
>     > occupation STRING,
>     > zipcode STRING)
>     > OW FORMAT DELIMITED
>     > FIELDS TERMINATED BY '|'
>     > LOCATION 'alluxio://master_hostname:port/ml-100k';

and select sql returned right result:

> hive> select * from u_user;
> OK
> 1       24      M       technician      85711
> 2       53      F       other   94043
> 3       23      M       writer  32067
> 4       24      M       technician      43537
> 5       33      F       other   15213
> 6       42      M       executive       98101
> 7       57      M       administrator   91344
> 8       36      M       administrator   05201
> 9       29      M       student 01002
> 10      53      M       lawyer  90703
> 11      39      F       other   30329
> 12      28      F       other   06405
> 13      47      M       educator        29206
> 14      45      M       scientist       55106

, but when I execute the count sql, I got an error:

> hive> select count(1) from u_user;
> Query ID = root_20181221105858_876d5979-c4ac-45a6-a7e4-e0468a8483e0
> Total jobs = 1
> Launching Job 1 out of 1
> Number of reduce tasks determined at compile time: 1
> In order to change the average load for a reducer (in bytes):
>   set hive.exec.reducers.bytes.per.reducer=<number>
> In order to limit the maximum number of reducers:
>   set hive.exec.reducers.max=<number>
> In order to set a constant number of reducers:
>   set mapreduce.job.reduces=<number>
> java.io.IOException: Cannot initialize Cluster. Please check your c              onfiguration for mapreduce.framework.name and the correspond server               addresses.
>         at org.apache.hadoop.mapreduce.Cluster.initialize(Cluster.j              ava:143)
>         at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:              108)
>         at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:              101)
>         at org.apache.hadoop.mapred.JobClient.init(JobClient.java:4              77)
>         at org.apache.hadoop.mapred.JobClient.<init>(JobClient.java              :455)
>         at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.execute(Exe              cDriver.java:395)
>         at org.apache.hadoop.hive.ql.exec.mr.MapRedTask.execute(Map              RedTask.java:142)
>         at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.jav              a:214)
>         at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(              TaskRunner.java:99)
>         at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:              2052)
>         at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:174              8)
>         at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java              :1501)
>         at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1285)
>         at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1275)
>         at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(Cli              Driver.java:226)
>         at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDrive              r.java:175)
>         at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriv              er.java:389)
>         at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDr              iver.java:781)
>         at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:              699)
>         at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java              :634)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Meth              od)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethod              AccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Delegati              ngMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
>         at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
> Job Submission failed with exception 'java.io.IOException(Cannot in              itialize Cluster. Please check your configuration for mapreduce.fra              mework.name and the correspond server addresses.)'
> FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.              ql.exec.mr.MapRedTask

I am sure this sql is available before inheritance

**Comment by zjfplayer** [comment]
My environment is cdh5.14.2. After I failed to follow the configuration given in the documentation, I modified the following configuration, which will be configured as follows:
`<property>
  <name>fs.alluxio.impl</name>
  <value>alluxio.hadoop.FileSystem</value>
  <description>The Alluxio FileSystem (Hadoop 1.x and 2.x)</description>
</property>
<property>
  <name>fs.AbstractFileSystem.alluxio.impl</name>
  <value>alluxio.hadoop.AlluxioFileSystem</value>
  <description>The Alluxio AbstractFileSystem (Hadoop 2.x)</description>
</property>
<property>
  <name>fs.alluxio-ft.impl</name>
  <value>alluxio.hadoop.FaultTolerantFileSystem</value>
  <description>The Alluxio FileSystem (Hadoop 1.x and 2.x) with fault tolerant support</description>
</property>
<property>
    <name>fs.defaultFS</name>
  <value>alluxio://zk@test1:2181,test2:2181,test3:2181/</value>
</property>
<property>
    <name>alluxio.zookeeper.enabled</name>
    <value>true</value>
  </property>
  <property>
    <name>alluxio.zookeeper.address</name>
    <value>test1:2181,test2:2181,test3:2181</value>
  </property>`
Added to hdfs-site.xml, core-site.xml, hive-site.xml in /etc/hive/conf/ and /etc/hadoop/conf/

**Comment by zjfplayer** [comment]
And my alluxio-site.properties settings is below：
`alluxio.master.hostname=test1
alluxio.underfs.address=hdfs://nameservice1:8020/alluxio
alluxio.underfs.hdfs.configuration=/etc/hadoop/conf/core-site.xml:/etc/hadoop/conf/hdfs-site.xml

alluxio.worker.memory.size=30GB
alluxio.worker.tieredstore.levels=1
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk

alluxio.master.security.impersonation.alluxio_user.users=hdfs,yarn,hive,root
alluxio.master.security.impersonation.client.users=*
alluxio.master.security.impersonation.alluxio_user.groups=supergroup,hadoop
alluxio.master.security.impersonation.client.groups=*
alluxio.security.login.impersonation.username=

alluxio.zookeeper.enabled=true
alluxio.zookeeper.address=test1:2181,test2:2181,test3:2181`

**Comment by zjfplayer** [comment]
I repackage alluxio with the following command:

> mvn install -Phadoop-2 -Dhadoop.version=hadoop.version=2.6.0-cdh5.14.2 -DskipTests
mvn package -Phadoop-2 -Dhadoop.version=hadoop.version=2.6.0-cdh5.14.2 -DskipTests

And the result is all success

**Comment by apc999** [comment]
@zjfplayer do you mean after running Alluxio with `hadoop.version=2.6.0-cdh5.14.2`, Hive command `select count(1) from u_user;` is working fine for you?

**Comment by zjfplayer** [comment]
> @zjfplayer do you mean after running Alluxio with `hadoop.version=2.6.0-cdh5.14.2`, Hive command `select count(1) from u_user;` is working fine for you?

I reconfigured it again and found no such problem.
