### ISSUE TITLE
OutputStream Problems in Extending Storage

### ISSUE THREAD

**Issue by DPnice** [Alluxio/alluxio#8216]
When I expand the underlying storage, I find that I write 8192B every time. Is that correct?

**Comment by apc999** [comment]
@DPnice can you clarify your questions? 
- how do you expand the underlying storage? What's the storage?
- "I find I write 8192B every time" -> Who writes this 8192B? Client or the worker? What's the workload generator?  I don't think Alluxio worker wrote such a small amount of data to UFS each time. Is it possible from the user-side logic?

**Comment by DPnice** [comment]
1. The underlying storage is seaweedfs
2. extends BaseUnderFileSystem
3. Using a single node

cmd:

    $ /alluxio/bin/alluxio fs persist /test2.txt
Some worker log：

    2018-12-25 14:27:33,718 INFO  SeaweedfsOutputStream - 当前长度: 56803328
    2018-12-25 14:27:33,738 INFO  SeaweedfsOutputStream - write(byte[] b, int off, int len)当前长度:56811520
    2018-12-25 14:27:33,738 INFO  SeaweedfsOutputStream - 当前长度: 56811520
    2018-12-25 14:27:33,799 INFO  SeaweedfsOutputStream - write(byte[] b, int off, int len)当前长度:56819712
> You can see 8192B data written at a time.

**Comment by apc999** [comment]
@DPnice thanks for the update. I checked the Alluxio source code and I actually find there is a small buffer of 16KB is allocated for persist command ([link](https://github.com/Alluxio/alluxio/blob/v1.8.1/core/common/src/main/java/alluxio/util/io/BufferUtils.java#L303)). This can be an issue if you need very fast persist implementation. I will create an issue to address this.
