### ISSUE TITLE
Provide a dist dir to facilitate deployment after compiling the source code

### ISSUE THREAD

**Issue by Chopinxb** [Alluxio/alluxio#8240]
After compiling, we would deploy the whole project dir which contains source code. Can there be a concise directory (like Spark's dist) for deployment?

**Comment by aaudiber** [comment]
In `master`, `branch-1.8`, and `branch-1.7`, you can generate a distribution by running

```bash
$ dev/scripts/generate-tarballs single
```

**Comment by Chopinxb** [comment]
Super cool！thanks~
