### ISSUE TITLE
Incorrect directories created metric

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8254]
**Alluxio Version:**
1.8.1

**Describe the bug**
The "Directories Created" metric in the web ui includes created files in its count.

**To Reproduce**
Create a bunch of files and look at http://localhost:19999/metricsui

**Expected behavior**
"Directories Created" should only count directories

**Additional context**
It looks like we increment both files and directory count here: https://github.com/Alluxio/alluxio/blob/master/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L1343

**Comment by tahakashaf** [comment]
Done [PR](https://github.com/Alluxio/alluxio/pull/8434)
