### ISSUE TITLE
Redacting aws keys for mount command

### ISSUE THREAD

**Issue by jaiseban** [Alluxio/alluxio#8260]
**Alluxio Version:** <enter version here, e.g. 1.8.1>

**Describe the bug**
Nested mount information shows aws access and secret keys.
**To Reproduce**

1. Execute a nested mount to S3 using access key and secret key using Alluxio client
2. After this, if you just execute mount command - it displays all the mount along with access and secret keys.

**Expected behavior**
Sensitive information should be redacted

**Additional context**

**Comment by apc999** [comment]
@LuQQiu  this issue has been addressed in 2.0.0 and 1.8.2-SNAPSHOT, right? please confirm

**Comment by LuQQiu** [comment]
@bf8086 Is it addressed in both 2.0.0 and 1.8.2?

**Comment by apc999** [comment]
I checked that this issue is solved in branch 2.0, but not in branch 1.8.
 can we cherrypick this to 1.8 branch @bf8086 ?

**Comment by apc999** [comment]
ping @LuQQiu  @bf8086

**Comment by LuQQiu** [comment]
Agree to cherry pick to 1.8. @bf8086 Could you help cherry pick to 1.8?
