### ISSUE TITLE
docker container for alluxio community 1.8.1 is not avaliable

### ISSUE THREAD

**Issue by antonkulaga** [Alluxio/alluxio#8315]
Looks like you forgot to publish a docker container for alluxio-community 1.8.1

**Comment by apc999** [comment]
@antonkulaga will this repo work for you?
https://hub.docker.com/r/alluxio/alluxio
this has the image for official Alluxio open source edition including 1.8.1

**Comment by apc999** [comment]
alluxio-community is indeed the free one. We will re-organize the dockerhub repos later. Let me know if you have any issue running https://hub.docker.com/r/alluxio/alluxio. Close this issue for now
