### ISSUE TITLE
Alluxio 'du' command doesn't properly report the amount of data in Alluxio

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#8356]
**Alluxio Version:** 1.8.1

**Describe the bug**
When using the Alluxio du -s -h command, the value for 'In Alluxio' is not correctly reported.

**To Reproduce**
Write data to a directory with writetype MUST_CACHE
run 'bin/alluxio fs du -s -h /path/to/directory/'
Note that the field for 'In Alluxio' says 0B.

**Expected behavior**
The value for 'In Alluxio' should show the amount of data stored in Alluxio for the given directory.

**Comment by IT-DONG** [comment]
Is it right that "'bin/alluxio fs du -s -h /path/to/directory/" is similar to "'bin/alluxio fs ls /path/to/directory/", will alluxio "WRITE" data to store?  if NOT, the field of the command result for 'In Alluxio' says 0B should be expected info?

<img width="320" alt="MacHi 2019-03-11 14-45-55" src="https://user-images.githubusercontent.com/10387174/54105030-bf392380-440c-11e9-8f01-e3f1a60fa810.png">

**Comment by apc999** [comment]
@ns1123 do you know if this issue gets addressed in 2.0.0?

**Comment by ns1123** [comment]
not sure if it has been resolved or not

**Comment by LuQQiu** [comment]
I fixed this issue in https://github.com/Alluxio/alluxio/commit/390729e0cee40b27fe6a53c4cae25f496c60791c
Will cherry pick to 1.8.2

**Comment by ns1123** [comment]
This was closed in 2.0.0
