### ISSUE TITLE
FileSystemUtils methods should be included in the public FileSystem interface

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#8366]
**Alluxio Version:** 1.8.1

**Describe the Issue**

The `FileSystemUtils` class has a few crucial methods such as `persist`, `waitCompleted`, and `checkConsistency`. These methods require access to a `FileSystemContext` and `FileSystem`. The `BaseFileSystem` already contains a `FileSystemContext` so it seems odd that these utility methods need both. I believe these methods are also useful enough to warrant moving them directly into the client API so users can access their functionality.

**To Reproduce**
N/A

**Expected behavior**
The FileSystem class should expose the `waitCompleted`, `persistFile`, and `checkConsistency` functions.

**Additional context**
N/A

**Comment by apc999** [comment]
For public API change, 2.0 is a better vehicle than 1.8.2.  Label this to be 2.0.0 rather than 1.8.2
