### ISSUE TITLE
Remove UNDERFS_ADDRESS PropertyKey

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#8384]
**Alluxio Version:** 1.8.1

**Describe the bug**
The `UNDERFS_ADDRESS` PropertyKey has been deprecated since 1.5.0 and should be removed for version 2.0 

**To Reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
N/A

**Comment by apc999** [comment]
@ZacBlanco can you double check with @aaudiber  as this may be needed for docker environment

**Comment by ZacBlanco** [comment]
Well I wouldn't be surprised if docker uses the UNDERFS_ADDRESS property key but it's marked as deprecated. If we choose to keep it around then it shouldn't be marked as such. Otherwise anywhere that utilizes `UNDERFS_ADDRESS` should be migrated to using `MASTER_MOUNT_TABLE_ROOT_UFS` (alluxio.master.mount.table.root.ufs) instead

**Comment by aaudiber** [comment]
Docker doesn't require any special handling for `UNDERFS_ADDRESS`
