### ISSUE TITLE
DefaultMetaMaster should utilize ConfigurationUtils to determine HA mode

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#8393]
**Alluxio Version:** 2.0.0-SNAPSHOT

**Describe the bug**

`ConfigurationUtils` contains a method [`isHaMode`](https://github.com/Alluxio/alluxio/blob/master/core/common/src/main/java/alluxio/util/ConfigurationUtils.java#L260) however the `DefaultMetaMaster` uses its own logic to determine is HA is enabled or not. Changes in how HA mode is defined may result in issues for the DefaultMetaMaster

**To Reproduce**
See https://github.com/Alluxio/alluxio/blob/master/core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java

**Expected behavior**
`DefaultMetaMaster` should utilize `ConfigurationUtils.isHaMode()`

**Additional context**

N/A

**Comment by aaudiber** [comment]
Fixed by https://github.com/Alluxio/alluxio/pull/8661
