### ISSUE TITLE
Consolidate alluxio.exception.status.Status with gRPC io.grpc.Status.Code

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8401]
These classes are almost identical. We should be able to replace our `alluxio.exception.status.Status` with `io.grpc.Status.Code`

This should happen before we release 2.0 since it affects backwards compatibility.

**Comment by ggezer** [comment]
This is done.

**Comment by aaudiber** [comment]
@ggezer can you link to the PR?

**Comment by apc999** [comment]
@ggezer is this ticket addressed? If yes, I will close this issue

**Comment by apc999** [comment]
saw previous discussion, I will close this issue
