### ISSUE TITLE
Phantom inodes cause journal replay failures

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8430]
**Alluxio Version:** Reproduced in 1.8.1 and 1.7.1, probably an issue in many earlier versions as well

**Describe the bug**
Concurrent creation operations can lead to invalid inodes. The race condition looks like:

Initial state: Only inode in Alluxio is "/", ufs contains "/a/b/c"
Thread A: begins to create /a/b
Thread B: tries to create /a/b/c
Thread A: begins to create /a
Thread A: takes a write lock on /a
Thread A: creates a new inode for /a
Thread A: adds /a to the children list of "/"
Thread A: calls syncPersistDirectory to sync "/a" with the ufs
Out of band: /a/b/c gets removed in the UFS
Thread B: traverses to "/a/b/c" and finds "/a" as a child of "/"
Thread B: takes a read lock on "/a" and blocks since thread A still has the write lock
Thread A: throws InvalidPathException("Cannot create or load UFS directory")
Thread A: removes "/a" from the child list of "/"
Thread A: unlocks "/a"
Thread B: acquires read lock on "/a" and continues traversal
Thread B: assumes that "/a" is part of the inode tree and performs operations on it. But there is no journal creation entry for "/a", so any operations will cause journal replay to fail.

**To Reproduce**
Make a lot of concurrent recursive creation requests while also deleting/renaming the underlying ufs directories.

**Expected behavior**
Alluxio should stay consistent, replay should never fail

See https://github.com/Alluxio/alluxio/pull/8431 for a test which reproduces the issue

**Comment by apc999** [comment]
@aaudiber has this issue been fixed? If yes, please close it
