### ISSUE TITLE
Avoid generating files suffixed by "_$folder$" for OSS UFS

### ISSUE THREAD

**Issue by warhin** [Alluxio/alluxio#8470]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by apc999** [comment]
@warhin I translated the title into English. Can you please fill in the detail of this request?

**Comment by warhin** [comment]
now i knowned these files suffixed by "_$folder$" are marked files for identiting dir or file,it's alluxio feature,don't need change.you can close it,thanks.






At 2019-03-06 07:58:58, "Bin Fan" <notifications@github.com> wrote:


@warhin I translated the title into English. Can you please fill in the detail of this request?

**Comment by apc999** [comment]
Thanks, yes "`_$folder$`" was introduced to mark directories in object stores. However I still want to keep your issue open as we have already removed adding this extra auxiliary for GCP and AWS S3. We should apply the same trick to other object stores like OSS. @madanadit , can you take a look and get an estimation how much complicate to achieve this?

**Comment by madanadit** [comment]
This is a trivial change of only a couple of lines. We just need to add to configuration parameter for OBS similar to alluxio.underfs.s3a.directory.suffix. Zero-byte objects with the configured suffix are created to represent empty directories (mkdir) and also during list operations as a performance optimization. Note: these breadcrumbs are only created when the mount is not read-only

**Comment by aaudiber** [comment]
@apc999 @madanadit I've created https://github.com/Alluxio/alluxio/issues/8677 to track this change
