### ISSUE TITLE
Use JCommander for CLI opts parsing

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#8513]
**Is your feature request related to a problem? Please describe.**

CLI opts parsing is not consistent across different Alluxio modules. Both `jcommand` and `commons-cli` are used. Proposing to use `jcommand` consistently across modules.

**Describe the solution you'd like**
Use `jcommand` consistently across modules.

**Describe alternatives you've considered**
N/A

**Additional context**
Discussion originally started here https://github.com/Alluxio/alluxio/pull/8494

**Comment by LuQQiu** [comment]
Looks like currently commons-cli is used more consistently across modules, do we think this request is still valid?
