### ISSUE TITLE
Docker guide does not work on MacOS

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#8550]
**Alluxio Version:** 1.8.1

**Describe the bug**
By following docker guide http://www.alluxio.org/docs/1.8/en/deploy/Running-Alluxio-On-Docker.html,
it will fail on MacOS

**To Reproduce**
1. Install docker on MacOS
2. Run the following:
```bash
$ docker run -d --net=host     -v /mnt/data:/opt/alluxio/underFSStorage     alluxio/alluxio master
bc39aeffc1e6b64a020619c0994bb5b33178c65646e972bbd74335d607d5bcf4
docker: Error response from daemon: Mounts denied: 
The path /mnt/data
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

**Expected behavior**
The guide should work on MacOS with Docker installation.

**Additional context**
` /mnt/data` is the the path for mount points on MacOS but good for Linux. 
Plus there might be some extra setup needed for Docker on MacOS

**Comment by IT-DONG** [comment]
docker: Error response from daemon: Mounts denied: 
The path /mnt/data
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.

According to the error, I checked the default shared path of docker, which shows info in the figure below, no /mnt/ available!
<img width="487" alt="MacHi 2019-03-09 23-12-10" src="https://user-images.githubusercontent.com/10387174/54073364-39f52800-42c1-11e9-9715-f1648625891a.png">

**Comment by apc999** [comment]
Thanks @IT-DONG for root-causing this issue. 
@aaudiber , do you mind to incorporate this setting on MacOS into our documentation ?

**Comment by aaudiber** [comment]
This isn't really a bug - the guide is designed for Linux only. It says this in the pre-requisites at the start.

Docker doesn't have good integration with OSX. Even if you fix the mount volume issue, there are networking problems which make it difficult to access the web UI or use the alluxio CLI from outside the server containers. To support OSX, we need to add an extra section to the doc where we discuss how to overcome the differences between OSX and Linux

**Comment by apc999** [comment]
Make sense. Let's target to add a separate session talking about running Alluxio docker image on MacOS then?

**Comment by aaudiber** [comment]
Sounds good
