### ISSUE TITLE
Unsupported major.minor version 52.0 is thrown when starting masters and workers

### ISSUE THREAD

**Issue by IT-DONG** [Alluxio/alluxio#8555]
Alluxio Version: 1.8.1, 2.0

**Describe the bug**
On MacOS and Centos(6.3 tested), suppose that we create an account named "alluxio", and deploy it with this account, then when running "./bin/alluxio-start.sh all SudoMount", it says the following error: "Exception in thread "main" java.lang.UnsupportedClassVersionError: alluxio/master/AlluxioMaster : Unsupported major.minor version 52.0"

**To Reproduce**
after deploy alluxio the a ordinary account, run "./bin/alluxio-start.sh all SudoMount"

**Expected behavior**
the masters and the workers processes can be started successfully

**Additional context**
2 cases for this issue:
case 1: we have not installed JDK 1.8
case 2: even if we have installed JDK 1.8, we still meet with the problem on MacOS and Centos

**Comment by apc999** [comment]
Hi @IT-DONG  Alluxio 1.8 and 2.0 source code is written using Java 8 and built with javac 8. Thus it is required to have JDK 8 (aka 52.0) installed to run Alluxio runtime. This is not an issue but a requirement to run latest Alluxio versions.
