### ISSUE TITLE
Support changing embedded journal masters without reformat

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8560]
**Is your feature request related to a problem? Please describe.**

The new embedded journal requires that the list of master hostnames stay the same. This makes it impossible to grow or shrink the number of masters without re-formatting the journal.

**Describe the solution you'd like**

An admin tool that allows masters to be added or removed from a running cluster. Even better, a tool that could add/remove masters whether or not the cluster is currently running.

**Describe alternatives you've considered**

It's possible to use DNS to migrate masters without reformat (same hostname, different machine). However, this doesn't work for growing/shrinking the cluster.

**Comment by apc999** [comment]
@ns1123 has this issue been addressed in 2.0.0?

**Comment by ns1123** [comment]
No this is not yet addressed. I would defer to @ggezer but it sounds like the new embedded journal stores the master hostnames in the journal itself.

**Comment by ggezer** [comment]
https://github.com/Alluxio/alluxio/pull/9533 Have added the capability to remove masters from running cluster. Adding new masters is as easy as booting up a new master with list of existing masters.
