### ISSUE TITLE
Multi-threaded backup

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8571]
**Is your feature request related to a problem? Please describe.**
Alluxio can back up around 3 million files per minute. When the master contains hundreds of millions of files, backups can take hours. This is largely because a single thread does all the backup work.

**Describe the solution you'd like**
We could use multiple threads (e.g. equal to number of processors on the machine) to speed up the backup process. One thread writes serialized inodes to the backup while other threads walk the inode tree and feed the writer thread serialized inodes to write.

**Describe alternatives you've considered**
Right now we write directly to a single backup file. To improve performance further, we could write to multiple files within a directory, and then archive them at the end. Then we won't be bottlenecked on a single writer thread. This is a bigger change since it requires modifying the backup file format.

**Comment by gpang** [comment]
Can we consider taking a journal backup from a standby? We could briefly "stop" the leader master to write out a journal entry to all the masters, and then the assigned standby could pause all the journals at that point in time, to run the full backup.

**Comment by aaudiber** [comment]
I like the idea of enlisting the help of standby masters to avoid leader downtime. With a secondary taking the backup, there shouldn't be any need at all to stop the leader. We could use either RPC or special journal entry to communicate a standby that it needs to take a backup. RPC might be better so that we can respond to the CLI synchronously, and so that we can control which standby tries to take the backup. 

Some other thoughts:
- Standbys only see completed logs, so we need to complete the current log as a part of running `backup`, and also tell the standby what sequence number it should catch itself up to.
- To extend this approach to single-master-node deployments, we could share the backup functionality across both standbys and dedicated `SecondaryMaster` processes.

**Comment by gpang** [comment]
The potential issue I see is if the standby cannot replay the journal entries for some reason.

But, in general, offloading the backup from the primary to the standby avoids the pause that is directly proportional to the metadata size.

**Comment by aaudiber** [comment]
Created https://github.com/Alluxio/alluxio/issues/8935 for the idea of using standbys to take snapshots
