### ISSUE TITLE
format command fails silently when ssh fails

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8573]
**Alluxio Version:**
2.0.0-preview

**Describe the bug**
The format command tries to ssh to all workers/masters and format them. Whether the command succeeds or fails, it prints
```
Waiting for tasks to finish...
All tasks finished
```
This gives a false impression that it succeeded when it may have actually failed. To see whether it actually succeeded, users need to look at `logs/task.log`

**To Reproduce**
1. Put incorrect worker hostnames in `conf/workers`
2. Run `bin/alluxio format` or `bin/alluxio formatWorkers`

**Expected behavior**
If format fails, it should report an error to stdout

**Comment by IT-DONG** [comment]
I'll look at this issue
