### ISSUE TITLE
Add a UFS to read from files hosted using http/https protocols

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#8574]
**Is your feature request related to a problem? Please describe.**
Make files hosted using http/https available using Alluxio

**Describe the solution you'd like**
Add a new UFS type so users can mount a http URL into Alluxio namespace.

```bash
$ bin/alluxio fs mount /files http://downloads.alluxio.org/downloads/files/2.0.0-preview/
$ bin/alluxio fs ls /files
<you will see alluxio-2.0.0-preview-bin.tar.gz and alluxio-2.0.0-preview-bin.tar.gz.md5 listed>
```
We may even want to support reading from compressed files

```bash
$ bin/alluxio fs mount /input https://s3.amazonaws.com/alluxio-sample/datasets/sample-1g.gz --compressed 
$ bin/alluxio fs ls /input
<files inside sample-1g.gz listed>
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ZacBlanco** [comment]
@apc999 close this issue?
