### ISSUE TITLE
backup command with no arguments hits NPE 

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8575]
**Alluxio Version:**
2.0.0-preview

**Describe the bug**
Running
`bin/alluxio fsadmin backup` causes an NPE

**To Reproduce**
1. start an alluxio master
2. run `bin/alluxio fsadmin backup`

**Expected behavior**
This should create a backup in the default backup directory

**Additional context**
This bug can be worked around by explicitly passing the directory to back up to
`bin/alluxio fsadmin backup /path/to/dir`

**Comment by IT-DONG** [comment]
@aaudiber what's the path of "the default backup directory"?  and how should we name it?
