### ISSUE TITLE
Add options and responses to all RPCs

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8599]
`alluxio-2.0.0` is breaking client backwards compatibility by switching from Thrift to gRPC. To avoid breaking backwards compatibility during `alluxio-2.x`, we should include an options object in every RPC request. Then we can add new options and deprecate old ones without breaking compatibility. Today, most RPCs already follow this convention, but there are also many that don't, e.g. `FileSystemMasterClient#getFilePath(long fileId)`, `MetaMasterClient#getConfigReport()`

We should do the same thing for responses. Any RPC named `X` should return an `XResponse`. Then we can evolve the api to add additional information to the return value of the RPC.

**Comment by ggezer** [comment]
gRPC enforces single request/response messages per RPC. So at the RPC layer we're already safe for breaking changes.
Java API has some translation by its own to split RPC fields into multiple parameters but that should be safe against adding/deleting fields later.
