### ISSUE TITLE
S3 '_$folder$' files and Presto/Hive on read from Alluxio

### ISSUE THREAD

**Issue by roman-io** [Alluxio/alluxio#8602]
**Is your feature request related to a problem? Please describe.**
Assume we have a directory with Parquet files in S3 called `mydir`.
Alluxio setup in EMR cluster with this directory as the UFS with read-only permission.
The data in this directory is generated by S3 Hadoop related components that create _$folder$ files in the directory. These _$folder$ files should not be deleted.
Presto and Hive in the EMR cluster query a table with 
`LOCATION 'alluxio://master_hostname:port/mydir'`
When trying to query the data with Presto or Hive, I'm getting this error:
`Query 20190321_132537_00026_4enx4 failed: Error opening Hive split alluxio://master_hostname:port/year=2019/month=01_$folder$ (offset=0, length=0): alluxio://master_hostname:port/year=2019/month=01_$folder$ is not a valid Parquet File`

Hive doesn't have an option to ignore specific files based on regex,
neither Alluxio. These files shouldn't be deleted.

**Describe the solution you'd like**
Add configuration to ignore files based on regex, or
Add configuration to ignore _$folder files.

**Describe alternatives you've considered**
Can't find any solution.

**Comment by aaudiber** [comment]
@roman-io Alluxio has a similar concept of using empty placeholder objects to represent directories. Instead of `_$folder$` we use `/` by default. The suffix is controlled by the `alluxio.underfs.s3a.directory.suffix` property. Can you try setting the property to `_$folder$`? Then Alluxio will understand that `month=01_$folder$` is a folder, not a file.

To update the property, update `alluxio-site.properties` on all servers

`alluxio.underfs.s3a.directory.suffix=_$folder$`

then restart the cluster

**Comment by apc999** [comment]
this feature request can be already achieved by existing alluxio properties. We will close this Issue in a few days if you don't have further request .

**Comment by roman-io** [comment]
> @roman-io Alluxio has a similar concept of using empty placeholder objects to represent directories. Instead of `_$folder$` we use `/` by default. The suffix is controlled by the `alluxio.underfs.s3a.directory.suffix` property. Can you try setting the property to `_$folder$`? Then Alluxio will understand that `month=01_$folder$` is a folder, not a file.
> 
> To update the property, update `alluxio-site.properties` on all servers
> 
> `alluxio.underfs.s3a.directory.suffix=_$folder$`
> 
> then restart the cluster

It worked.
Thanks!
