### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [Alluxio/alluxio#8613]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by ZacBlanco** [comment]
Hi @gustavosizilio, great question!

We use AmpLab Jenkins to compile and run our suite of unit and integration tests against every PR that's opened on this repository.

https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-Pull-Request-Builder/

I checked our documentation to see if it was mentioned in there, but I wasn't able to find it. It is something that we could add to our [contributor guide](https://www.alluxio.org/docs/1.8/en/contributor/Contributor-Getting-Started.html#sending-a-pull-request)

**Comment by gustavosizilio** [comment]
Thank you very much!
