### ISSUE TITLE
java.lang.IllegalStateException: Inconsistent Zookeeper configuration; Exception using with spark

### ISSUE THREAD

**Issue by abhishek021** [Alluxio/alluxio#8658]
I'm using alluxio-1.8.1
Getting **java.lang.IllegalStateException: Inconsistent Zookeeper configuration; alluxio.zookeeper.address should be set if and only if alluxio.zookeeper.enabled is true** 
while running spark job.
Alluxio URI - "alluxio://master:19998/s3/path"

alluxio.zookeeper.enabled=true
alluxio.zookeeper.address=[host]:[port]
This configuration is already there in alluxio-site.properties

**Comment by apc999** [comment]
hi @abhishek021 in this case, because you are using zookeeper, we should use

**Comment by abhishek021** [comment]
Thanks @apc999 the issue has been resolved.
There was another issue with spark conf which I had to set for zookeeper
i.e. alluxio.zookeeper.enabled=true and alluxio.zookeeper.address=[host]:[port]
