### ISSUE TITLE
Make the object storage folder suffix configurable for all object stores

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8677]
**Is your feature request related to a problem? Please describe.**
Currently some object stores use a hard-coded "_$folder$" suffix to identify folder objects (as opposed to files). Users can configure the suffix used by S3 via `alluxio.underfs.s3a.directory.suffix`, but other object stores don't have such a property. It would be good to have a single property that controls the default suffix for all object stores.

**Describe the solution you'd like**
New property, e.g. `alluxio.underfs.directory.suffix`

**Describe alternatives you've considered**
We could implement per-store properties, but then we'll need to remember to keep adding them whenever we add a new object store UFS.

**Urgency**
I haven't seen anyone ask for this, but it's good to be consistent

**Additional context**
The issue originally came up in https://github.com/Alluxio/alluxio/issues/8470

**Comment by ns1123** [comment]
Closing stale issue. Requirement is not imperative.
