### ISSUE TITLE
Mount Alluxio as an NFS mount to the local filesystem

### ISSUE THREAD

**Issue by we7team** [Alluxio/alluxio#8746]
I think if the client supports NFS protocol mounting, it can be applied in most scenarios. I hope it can be supported

**Comment by gpang** [comment]
Hi @we7team Alluxio allows mounting an [NFS mount to the Alluxio namespace](http://www.alluxio.org/docs/master/en/ufs/NFS.html). However, are you talking about mounting Alluxio like an NFS mount to the local file system?

**Comment by we7team** [comment]
yes，i hope client file system can mount to nfs，because most k8s environment support this protocol，nfs can do it so easy

**Comment by gpang** [comment]
I see. As an alternative, Alluxio can be mounted to the local file system via a fuse mount. More documentation can be found here: http://www.alluxio.org/docs/master/en/api/POSIX-API.html

**Comment by calvinjia** [comment]
@we7team does the fuse mount satisfy your use case?

**Comment by apc999** [comment]
@we7team Alluxio does support FUSE client to mount the service as a part of local file system.
Please let us know if https://www.alluxio.org/docs/1.8/en/api/FUSE-API.html helps. Otherwise, we will close this issue in a week

**Comment by anuragrawat28** [comment]
This doesn't work as Fuse is launching a java process to mount alluxio locally. Its not using NFS protocol to mount. Plus using fuse also degrades the performance of Alluxio, than what's the point of using it.

**Comment by ns1123** [comment]
Closing this as there are no immediate plans to support this
