### ISSUE TITLE
Add health check service to standby masters

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8765]
**Is your feature request related to a problem? Please describe.**
Standby masters don't currently expose any APIs. The only way to tell whether standby masters are alive is by using `ps` and grepping for their process. It would be useful to have standby masters expose an API for checking their health remotely.

**Describe the solution you'd like**
We could do this through a web server instead. Alongside the health check endpoint, the web server could also requests UI requests to the current primary.

**Describe alternatives you've considered**
We could use a gRPC service instead.s

**Urgency**
Not super urgent, but it would help the implementation of https://github.com/Alluxio/alluxio/pull/8663 since we could use the health check instead of `ps`. Redirecting web requests to the primary would also be a big win for HA mode usability.

**Comment by LuQQiu** [comment]
Addressed via https://github.com/Alluxio/alluxio/pull/16636
which shows standby master information on leading master web ui
