### ISSUE TITLE
Add a native exists API

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#8852]
**Is your feature request related to a problem? Please describe.**
Currently the get status API is used for exists, this is inefficient.

**Describe the solution you'd like**
Add a new exists API.

**Describe alternatives you've considered**
Continue using the current API.

**Urgency**
Urgent to be fixed before 2.0.

**Additional context**

**Comment by ns1123** [comment]
@calvinjia same here

**Comment by calvinjia** [comment]
Yes, we are still using `getStatus` and catching the file not found exception
