### ISSUE TITLE
Remove unknown block size logic

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#8853]
**Is your feature request related to a problem? Please describe.**
Unknown block sizes are no longer required.

**Describe the solution you'd like**
Remove unknown block size logic.

**Describe alternatives you've considered**

**Urgency**
Adds unnecessary code to the codebase.

**Additional context**

**Comment by ns1123** [comment]
@calvinjia is this addressed?

**Comment by calvinjia** [comment]
Unfortunately, I think this is still around

**Comment by LuQQiu** [comment]
@beinan is this issue still exist?
Otherwise this issue will be closed, thanks
