### ISSUE TITLE
No way to proactively sync alluxio data to underFS when MUST_CACHE used

### ISSUE THREAD

**Issue by perrywang** [Alluxio/alluxio#8867]
**Alluxio Version:**
1.8.1

**Describe the bug**
When CACHE_THROUGH used the performance is experiencing terribly situations. And all kinds of random application errors happen. When MUST_CACHE used all things works fine but we lost capability to sync alluxio local new added file to sync with underFS. Also there is no any approach exposed to proactively sync alluxio data to remote underFS.

**To Reproduce**
as described above

**Expected behavior**
provide command interface to sync alluxio data to underFS

**Urgency**
Urgent

**Additional context**
N/A

**Comment by calvinjia** [comment]
@perrywang We currently have two ways 
1. Use ASYNC_THROUGH mode (much more mature in Alluxio 2) which will write data into Alluxio and then asynchronously write it to the underFS.
2. Use the persist command to explicitly flush files only in Alluxio to the underFS.

Would either of these ways work for you? If not, could you detail what kind of behavior you are looking for?

**Comment by liuzx32** [comment]
@calvinjia Hello, If I Use ASYNC_THROUGH , is there something wrong leading to data loss?

**Comment by liuzx32** [comment]
@perrywang What about writetype is THROUGH?

**Comment by calvinjia** [comment]
@liuzx32 Good questions!
For the async through write type, you can specify the number of replicas you want to write into Alluxio space to prevent data loss. For example, if you have only 1 copy, you will lose data if that machine crashes, with 3 replicas, you will get similar durability as other distributed storages. Keep in mind only 1 replica needs to be intact within the time of completing the write to Alluxio and the async persist to the underFS.
Write type THROUGH writes synchronously to the underFS, so there is no chance of data loss unless the underFS has data loss.

**Comment by liuzx32** [comment]
@calvinjia Thanks for your answer.
#
Now the write performance of  THROUGH is better then CACHE_THROUGH and ASYSNC_THROUGH.
And the cmd persist -p n is also slower then others.

**Comment by calvinjia** [comment]
@liuzx32 
I would expect THROUGH and CACHE_THROUGH to have similar performance (Alluxio overhead should be small). ASYNC_THROUGH should have better performance (similar to your MUST_CACHE performance). What is your environment like (underFS, # nodes, network)?

**Comment by liuzx32** [comment]
@calvinjia underFS is oss of aliyun.
#
Writing to alluxio is good performance for AYSNC_THROUGH and CACHE_THROUGH, but much slower for sync to oss.
And THROUGH is is good performance for sync to oss, but no cache.

**Comment by ns1123** [comment]
Closing this issue. Please reopen if there are further questions.
