### ISSUE TITLE
maven compile error, no io.atomix.copycat.alluxio:copycat-server:jar:1.2.12

### ISSUE THREAD

**Issue by liuzx32** [Alluxio/alluxio#8868]
[ERROR] Failed to execute goal on project alluxio-core-server-common: Could not resolve dependencies for project org.alluxio:alluxio-core-server-common:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: io.atomix.copycat.alluxio:copycat-server:jar:1.2.12, io.atomix.copycat.alluxio:copycat-client:jar:1.2.12: Could not find artifact io.atomix.copycat.alluxio:copycat-server:jar:1.2.12

**Comment by calvinjia** [comment]
@liuzx32 Thanks for reporting this issue.

Could you also share the command you used to compile the project?

**Comment by liuzx32** [comment]
@calvinjia mvn -U clean install -DskipTests
#
The jar io.atomix.copycat.alluxio:copycat-server:jar:1.2.12 is not in the maven repo.
I can't find io.atomix.copycat.alluxio:copycat-server:jar:1.2.12 in other maven public repo.
Where should I find the jar io.atomix.copycat.alluxio:copycat-server:jar:1.2.12 for alluxio-2.0.0?

**Comment by ZacBlanco** [comment]
@liuzx32 Could you also provide the version of maven that you're using?

**Comment by liuzx32** [comment]
@ZacBlanco maven 3.5.4
#
$mvn -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /usr/local/maven
Java version: 1.8.0_151, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.14", arch: "x86_64", family: "mac"

**Comment by LuQQiu** [comment]
Hi @liuzx32, the copycat jar is located in the static website of `alluxio.artifacts` S3 bucket. The place that we defind the jar address is in `alluxio/pom.xml`:
```
    <repository>
      <id>alluxio.artifacts</id>
      <url>http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release</url>
    </repository>
```

Listing and reading objects do not require aws keys. If maven is unable to download the jar directly, could you try to see if you can directly open the page [http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release/io/atomix/copycat/alluxio/copycat-server/1.2.12/copycat-server-1.2.12.jar](url)
 and download the jar. Thanks

**Comment by apc999** [comment]
I tested building the master branch on a clean machine and the maven build process completes for me

**Comment by liuzx32** [comment]
@LuQQiu Thanks for the jar, @apc999 Thank you very much.

**Comment by zhipcui** [comment]
> Hi @liuzx32, the copycat jar is located in the static website of `alluxio.artifacts` S3 bucket. The place that we defind the jar address is in `alluxio/pom.xml`:
> 
> ```
>     <repository>
>       <id>alluxio.artifacts</id>
>       <url>http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release</url>
>     </repository>
> ```
> 
> Listing and reading objects do not require aws keys. If maven is unable to download the jar directly, could you try to see if you can directly open the page [http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release/io/atomix/copycat/alluxio/copycat-server/1.2.12/copycat-server-1.2.12.jar](url)
> and download the jar. Thanks

still build failed!

```bash
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project alluxio-core-server-common: Compilation failure: Compilation failure:
[ERROR] /opt/push/cuizp/alluxio/core/server/common/src/main/java/alluxio/master/journal/raft/JournalEntryCommand.java:[20,25] cannot find symbol
[ERROR]   symbol:   class Command
[ERROR]   location: package io.atomix.copycat
[ERROR] /opt/push/cuizp/alluxio/core/server/common/src/main/java/alluxio/master/journal/raft/JournalEntryCommand.java:[28,45] cannot find symbol
[ERROR]   symbol: class Command
[ERROR] /opt/push/cuizp/alluxio/core/server/common/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java:[25,25] cannot find symbol
[ERROR]   symbol:   class Command
[ERROR]   location: package io.atomix.copycat
[ERROR] /opt/push/cuizp/alluxio/core/server/common/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java:[26,34] package io.atomix.copycat.protocol does not exist
[ERROR] /opt/push/cuizp/alluxio/core/server/common/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java:[27,34] package io.atomix.copycat.protocol does not exist
[ERROR] /opt/push/cuizp/alluxio/core/server/common/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java:[35,30] package io.atomix.copycat.util does not exist
[ERROR] /opt/push/cuizp/alluxio/core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java:[97,59] cannot access io.atomix.copycat.Operation
[ERROR]   class file for io.atomix.copycat.Operation not found
```

**Comment by apc999** [comment]
@zhipcui  have you get this resolved?

**Comment by jinhang** [comment]
@zhipcui@apc999 how to fix "Cannot resolve io.atomix.copycat.alluxio:copycat-client:1.2.14" ? where is this jar in maven rep?

**Comment by jinhang** [comment]
![image](https://user-images.githubusercontent.com/4497831/70239595-8ca73600-17a6-11ea-8052-2ff10f9b6f7c.png)

**Comment by sunweihao** [comment]
@apc999 
I got the error similar to the error as @zhipcui when compiling the source code tagged 2.1 after I downloaded the copycat jar and install it by myself. 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project alluxio-core-server-common: Compilation failure: Compilation failure: 
[ERROR] /home/ubuntu/code/alluxio/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java:[36,37] package io.atomix.catalyst.serializer does not exist
[ERROR] /home/ubuntu/code/alluxio/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java:[37,36] package io.atomix.catalyst.transport does not exist
[ERROR] /home/ubuntu/code/alluxio/core/server/common/src/main/java/alluxio/master/journal/raft/RaftPrimarySelector.java:[17,37] package io.atomix.catalyst.concurrent does not exist
[ERROR] /home/ubuntu/code/alluxio/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java:[278,23] cannot find symbol
[ERROR]   symbol:   class Address
[ERROR]   location: class alluxio.master.journal.raft.RaftJournalSystem
```

It seemes that I lacked the dependency of io.atomix.catalyst and actually it is. So i tried to find the definition of this dependency but I got nothing. I wonder where the dependency defines or which dependency contains it since I need to know the version it to add it to my repository.

**Comment by zhipcui** [comment]
@jinhang @sunweihao You need manually download jars list as below
- [copycat-client-1.2.12.jar]( http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release/io/atomix/copycat/alluxio/copycat-client/1.2.12/copycat-client-1.2.12.jar)
- [copycat-protocol-1.2.12.jar](http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release/io/atomix/copycat/alluxio/copycat-protocol/1.2.12/copycat-protocol-1.2.12.jar)
- [copycat-server-1.2.12.jar](http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release/io/atomix/copycat/alluxio/copycat-server/1.2.12/copycat-server-1.2.12.jar)

**Comment by jinhang** [comment]
@apc999 @calvinjia @ZacBlanco 
[ERROR] Failed to execute goal on project alluxio-core-server-common: Could not resolve dependencies for project org.alluxio:alluxio-core-server-common:jar:2.2.0-SNAPSHOT: Failed to collect dependencies at io.atomix.copycat.alluxio:copycat-server:jar:1.2.14: Failed to read artifact descriptor for io.atomix.copycat.alluxio:copycat-server:jar:1.2.14: Could not transfer artifact io.atomix.copycat.alluxio:copycat-server:pom:1.2.14 from/to alluxio.artifacts (http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release): Authorization failed for http://alluxio.artifacts.s3-website-us-east-1.amazonaws.com/release/io/atomix/copycat/alluxio/copycat-server/1.2.14/copycat-server-1.2.14.pom 403 Openproxy_Blocked_URL_list -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
