### ISSUE TITLE
alluxio-fuse:latest Docker image does not exist

### ISSUE THREAD

**Issue by mingfang** [Alluxio/alluxio#8914]
According to https://hub.docker.com/r/alluxio/alluxio-fuse/tags the newest tag is 2.0.0-SNAPSHOT but the "latest" tag is missing https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/alluxio-fuse.yaml.template#L28

**Comment by ZacBlanco** [comment]
Docker builds are now published regularly with the `latest` tag
