### ISSUE TITLE
bin/alluxio copyDir should copy to both masters and workers

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8915]
**Is your feature request related to a problem? Please describe.**
`bin/alluxio copyDir` is often used to sync configuration across cluster machines. Currently it only syncs to worker machines listed in `conf/workers`. It would be good to also sync to master machines listed in `conf/masters`. 

**Describe the solution you'd like**
sync to both `conf/masters` and `conf/workers`

**Describe alternatives you've considered**
The alternative is manually syncing to master nodes.

**Urgency**
New users could naturally assume that copyDir will sync master configuration. This will result in confusion and difficulty deploying Alluxio.

**Comment by liuzx32** [comment]
@aaudiber Thank you very much.
