### ISSUE TITLE
Create backups on standbys instead of primary

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8935]
**Is your feature request related to a problem? Please describe.**
Today, backups are taken by (1) pausing all master operations and waiting for outstanding RPCs to complete (2) serializing master state to a backup. This has the downside of disrupting service.

**Describe the solution you'd like**
It would be better if the primary could delegate the backup work to a standby. The standby needs to catch up to the primary, then it can write a backup of its state.

**Urgency**
Some environments can't afford any master downtime, so backup is unusable.

**Comment by ns1123** [comment]
@ggezer can you link the PR that closes this issue?
