### ISSUE TITLE
Can we add fuse example for docker setup?

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#8939]
**Is your feature request related to a problem? Please describe.**

I'm looking into the guide: https://www.alluxio.org/docs/master/en/deploy/Running-Alluxio-On-Docker.html. And I want to know how to use fuse with alluxio in docker. Especially about how to enable short-circuit.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by madanadit** [comment]
thanks @cheyang we have some documentation for how to do this when launching docker containers in k8s. we will add more docs for this on the docker page

**Comment by ns1123** [comment]
Closing since this has been added to the doc section in https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html
