### ISSUE TITLE
hadoop maven dependencies should be in provided scope

### ISSUE THREAD

**Issue by mingfang** [Alluxio/alluxio#8949]
When integrating Alluxio with environments that already has hadoop jars such as Spark Workers, the hadoop jars from Alluxio conflicts with the hadoop jars from the Spark Worker.  
This leads to serialization and/or class casting problems.
Putting the hadoop dependencies in provided scope avoids this problem.

**Comment by madanadit** [comment]
HI @mingfang, thanks for reporting the issue. Can you specify which version of Alluxio and Spark you are using? Also can you provide more details of your workaround? Thx

**Comment by mingfang** [comment]
I was using Alluxio 2.0.0-preview and Spark 2.3.3.
You will find detailed documentation and see the actually test in my Jupyter notebook here https://github.com/mingfang/terraform-provider-k8s/blob/master/examples/alluxio/AlluxioExample.ipynb

**Comment by ZacBlanco** [comment]
@mingfang when integrating with spark/hadoop, which jars exactly are you putting on their classpath to access Alluxio?

The proper client jar uses shaded dependencies which shouldn't result in any conflicts. From your link at https://github.com/mingfang/terraform-provider-k8s/blob/master/examples/alluxio/AlluxioExample.ipynb I see you're referencing `org.alluxio alluxio-core-client-runtime 2.0.0-preview`. This jar doesn't have the dependencies shaded which is probably why you're seeing issues.

The jar which should be used can be found at `{ALLUXIO_INSTALL}/client/alluxio-${VERSION}-client.jar`.

**Comment by mingfang** [comment]
@ZacBlanco can you please publish that artifact to maven?

**Comment by ZacBlanco** [comment]
I don't have the power to publish the maven artifact, but I don't think this is something we want to publish. You can get it by downloading an alluxio tarball at `https://www.alluxio.io/download/` or by building from source and looking in the `client` folder.

@apc999 may have other opinions on this however. Feel free to chime in.

**Comment by mingfang** [comment]
Since the official solution is to use the `{ALLUXIO_INSTALL}/client/alluxio-${VERSION}-client.jar` then I'm closing this issue.
