### ISSUE TITLE
Move Inode Indices into InodeStore

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/alluxio#8991]
**Is your feature request related to a problem? Please describe.**
Today, even when using the RocksInodeStore for off-heap inode storage, we still maintain inode indices fully on-heap. The indices we currently maintain are
- `PinnedInodeFileIds`: inode ids of all pinned files
- `ReplicationLimitedFileIds`: inode ids of all files with a max replication set
- `ToBePersistedFileIds`: inode ids of all files which should be asynchronously persisted
- `TtlBucketList`: data structure for keeping track of which files with a time to live (TTL) applied.

These structures take around 50 bytes per inode, so to store 1 billion files in one of these indices, we would need 50GB of heap memory.

Due to worker memory limitations, it is unlikely that users will want to pin that many files, so `PinnedInodeFileIds` is less of a problem. It is also unlikely that so many files will be persisted or have TTL set at the same time, so `ToBePersistedFileIds` and `TtlBucketList` are lower priority. But it's possible that users will set a max replication on all of their files, causing `ReplicationLimitedFileIds` to take up a lot of memory.

**Describe the solution you'd like**
We should support off-heap storage for `ReplicationLimitedFileIds`, similar to how we store blocks and inodes off-heap. Ideally the solution can be extended to other inode indices, but this isn't a requirement.

**Describe alternatives you've considered**
Tell users to increase their JVM heap if they want to set replication limits on hundreds of millions of files.

**Urgency**
Not urgent yet, but will become important once users try to combine our replication limiting feature with large namespace scale.

**Comment by ggezer** [comment]
Some findings: 
* Default interval for a replicationchecker is 1min.
* ROCKS can iterate 200M keys in a minute.
Some ideas:
* We could consider, compacting the in-memory representation of indexes as range sets. As we generate Ids sequentially, they could eventually converge to a reasonable size in memory.

@gpang It looks like replication checker is running every minute (not second). 1billion distinct indices could be iterated in less than 5 minutes from ROCKS. So there still could be a justification for putting indices to disk. WDYT?

**Comment by jja725** [comment]
@tcrain do you mind taking a look to see whether this issue is still valid? otherwise, I will close this. Thanks

**Comment by tcrain** [comment]
The concepts are still valid.

I feel that there would have a be some testing to validate that users are actually using these features at large scale though. Without evidence of this it is likely not worth spending the time to make the suggested changes.

**Comment by jja725** [comment]
OK I would close it for now and feel free to reopen it if it become valid with some user feedback

**Comment by tcrain** [comment]
I added some metrics for these (and some already existed), see https://github.com/Alluxio/alluxio/pull/16818.

So if we see high memory usage of a master, we can check
```
Master.FilesPinned
Master.FilesToBePersisted
Master.TTLBuckets
Master.TTLInodes
Master.ReplicationLimitedFiles
```
