### ISSUE TITLE
Mount two same name ns to alluxio can not be support

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#9000]
**Alluxio Version:**
Alluxio-2.0.0-SNAPSHOT, in fact, i build it from master branch at 5/5/2019

**Describe the bug**

Blank in my mount commandline will be parsed as a parameter

**To Reproduce**

- /software/servers/alluxio-2.0.0-preview/bin/alluxio mkdir /tmp

- /software/servers/alluxio-2.0.0-preview/bin/alluxio fs mount --readonly --option alluxio.underfs.hdfs.configuration=/software/servers/alluxio-2.0.0-preview/hadoop-conf/cluster1/hadoop/hdfs-site.xml /tmp/app-logs/ hdfs://ns19/tmp/app-logs/

-  /software/servers/alluxio-2.0.0-preview/bin/alluxio fs mount --readonly --option alluxio.underfs.hdfs.configuration=/software/servers/alluxio-2.0.0-preview/hadoop-conf/cluster2/hadoop/hdfs-site.xml /tmp/app-logs2/ hdfs://ns19/tmp/app-logs/

**Expected behavior**

`Mount point hdfs://ns19/tmp/app-logs is a prefix of hdfs://ns19/tmp/app-logs`

**Urgency**

urgent

**Additional context**

if we can support this, we can combine our all hdfs cluster's ns.

**Comment by maobaolong** [comment]
@yuzhu Sorry for the confusing description, let me show more detail.

The `ns19` in `/software/servers/alluxio-2.0.0-preview/hadoop-conf/cluster1/hadoop/hdfs-site.xml` means to connect namenode address A, and `ns19` in `/software/servers/alluxio-2.0.0-preview/hadoop-conf/cluster2/hadoop/hdfs-site.xml` stand for namenode address B. 

So the following two mount behaviors is different. we should check whether the two `ns19` are same.

```
/software/servers/alluxio-2.0.0-preview/bin/alluxio fs mount --readonly --option alluxio.underfs.hdfs.configuration=/software/servers/alluxio-2.0.0-preview/hadoop-conf/cluster1/hadoop/hdfs-site.xml /tmp/app-logs/ hdfs://ns19/tmp/app-logs/
/software/servers/alluxio-2.0.0-preview/bin/alluxio fs mount --readonly --option alluxio.underfs.hdfs.configuration=/software/servers/alluxio-2.0.0-preview/hadoop-conf/cluster2/hadoop/hdfs-site.xml /tmp/app-logs2/ hdfs://ns19/tmp/app-logs/
```

**Comment by LuQQiu** [comment]
@maobaolong is this being addressed? why is it hard to have two different names for the two different hdfs clusters?

**Comment by jja725** [comment]
seems like this is more of a feature request. Will close it for now, feel free to reopen it and contact us if this is a strong request!
