### ISSUE TITLE
Merge job_master into master and job_worker to worker. 

### ISSUE THREAD

**Issue by witgo** [Alluxio/alluxio#9003]
**Is your feature request related to a problem? Please describe.**
Two new types of processes have been added to alluxio 2.0.0, job_master and job_worker. This will increase the difficulty of operation and maintenance.

**Describe the solution you'd like**
Merge job_master into master and job_worker to worker. 

**Describe alternatives you've considered**
NA

**Urgency**
My suggestion is to complete the change before the version of 2.0.0 is released.
**Additional context**
NA

**Comment by zrss** [comment]
cc

**Comment by LuQQiu** [comment]
@jja725 FYI

**Comment by jja725** [comment]
yes this is ongoing
