### ISSUE TITLE
Worker's overview page can sort the `Storage Usage Summary` by alias and it can show block count

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#9004]
**Is your feature request related to a problem? Please describe.**
In worker's page, if i config 3 tier, it will be better to show the `Storage Usage Summary` sorted by alias, and if we can see the Storage usage, we can know more about this worker.

**Describe the solution you'd like**

**Describe alternatives you've considered**

- sort the `Storage Usage Summary`  by alias.
- add a column named Blocks

**Urgency**
LOW

**Additional context**

![image](https://user-images.githubusercontent.com/17329931/57277631-23a7f480-70d7-11e9-8c0a-94438ffbe97d.png)

**Comment by maobaolong** [comment]
We add the block count into this page now, we need a sorter to sort this table by block count or usage or any column here.

It would be great to have this feature, but guys from my sides are not good at web ui `nodejs` and `react`, please feel free to take this ticket any time.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request!
