### ISSUE TITLE
Worker's blockInfo page can show the blockId, filtered by blockId

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#9006]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**

if we can see the blockid in the blockInfo page, we can know the block information related to a file, it is useful for debug.

**Describe alternatives you've considered**

Add a column named blockId.

**Urgency**

MIDDLE

**Additional context**

![image](https://user-images.githubusercontent.com/17329931/57278578-6f5b9d80-70d9-11e9-85f9-e31ecdc75591.png)

**Comment by LuQQiu** [comment]
@maobaolong is this issue still valid and still useful?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
