### ISSUE TITLE
`job worker` and `worker` should be in the different container of the same Pod in Kubernetes.

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9017]
**Is your feature request related to a problem? Please describe.**

Thanks very much for your kubernetes solution! I noticed in alluxio 2.0 there are two processes `job worker` and `worker` in the same container, no systemd to manage their lifecyle. I think it's better to make them in the same Pod instead of the same container, because it's required the same lifecycle of  process inside container with the container itself.  For example, there will be some cases that the container is alive but the job worker is dead. Do you agree?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by madanadit** [comment]
https://github.com/Alluxio/alluxio/pull/9133
