### ISSUE TITLE
alluxio sometimes load the local / dir

### ISSUE THREAD

**Issue by liuzx32** [Alluxio/alluxio#9022]
**Alluxio Version:**
master

**Describe the bug**
The cmd "alluxio ls -f" will sometimes load the local / dir, just like the picture.

<img src="https://user-images.githubusercontent.com/19620810/57345297-e39b4d00-717c-11e9-86b7-a412f418f86b.png" width="100" align=center>

**Comment by liuzx32** [comment]
/bin /boot /dev /etc /mnt /sys ... are the local machine dirs, not the cloud bucket dir.

**Comment by ZacBlanco** [comment]
Thanks for reporting this! We'll need some more information to be able to debug this. Do you have a configuration that reliably reproduces this problem? and could you describe your environment?

If we can reliably reproduce the issue, then we should be able to fix it.

**Comment by liuzx32** [comment]
@ZacBlanco Thanks for the answer.
#
The case is not necessarily recurring, and It only happens on alluxio-2.0.0-SNAPSHOT.
After alluxio runs for a while, produces files on s3 or oss, then alluxio ls -f to update the alluxio meta.

**Comment by liuzx32** [comment]
Refer: https://github.com/Alluxio/alluxio/pull/9308

**Comment by rastogiasr** [comment]
If this issue is still valid, please re-open it.
