### ISSUE TITLE
Prevent leadership changes during backup

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#9023]
**Is your feature request related to a problem? Please describe.**
Backup is a long running process and could render leader not responsive to leadership heartbeats, which will result in the current leader relinquishing leadership. That will cause current backup to be failed due to master process shutdown.

**Describe the solution you'd like**
Backups could be offloaded to standby masters when in a FT cluster, as discussed in https://github.com/Alluxio/alluxio/issues/8571

**Describe alternatives you've considered**
Standby masters should be informed of an ongoing backup via RPC. That should effectively cause them to disregard leadership status changes until backup is completed. To account for leader crashes, this information should be sent regularly, each time disabling leader switches for a constant time.

**Comment by aaudiber** [comment]
What we really need to figure out is why leadership is changing when there isn't a network partition. If we can fix that, the problem here goes away.

If leadership legitimately does change during backup (due to network partition), I agree that we should allow the backup to complete.
