### ISSUE TITLE
Multi-file backup format

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#9025]
**Is your feature request related to a problem? Please describe.**
Backup times could be improved by writing to a multiple backup files concurrently. This would require a new backup format that is a folder with multiple files.

**Describe the solution you'd like**
Write backup streams concurrently to multiple out streams. Utilize JournalEntry's sequence number for merging the files into one continuous stream, during restoring. Restore overhead could be mitigated by chunking large enough continuous entries together in the same stream.

**Urgency**
Not urgent. Good for taking backups on large namespaces.

**Comment by LuQQiu** [comment]
Looks like Rocks DB already have this improvement
```
When the metadata are stored in RocksDB, Alluxio 2.9 added support to checkpointing with multiple threads. alluxio.master.metastore.rocks.parallel.backup=true will turn on multi-threaded checkpointing and make the checkpointing a few times faster(depending how many threads are used). alluxio.master.metastore.rocks.parallel.backup.threads controls how many threads to use. alluxio.master.metastore.rocks.parallel.backup.compression.level specifies the compression level, where smaller means bigger file and less CPU consumption, and larger means smaller file and more CPU consumption.
```
