### ISSUE TITLE
Worker startup with no error report while the storage tier folder permission deny.

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#9028]
**Alluxio Version:**
2.0.0

**Describe the bug**

Worker startup with no error report while the storage tier folder permission deny.

**To Reproduce**

- with the following alluxio-site.properties

```properties
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk/alluxio/alluxio-blockpool
```

```
$ ll /mnt/ramdisk/
total 0
drwxr-x--- 3 root root 0 May  8 17:40 alluxio
```

- /software/servers/alluxio-2.0.0/bin/alluxio-start.sh worker

**Expected behavior**

Maybe we need some error report here.

**Urgency**

LOW

**Additional context**

No

**Comment by bf8086** [comment]
Thanks for the report! While we don't have a startup error for such situation, there are some ways to check storage errors.
During the startup, the worker will check the access to the storage paths, if a storage path fails the check, it will report an error in the worker log and skip the storage path. You can also check for storage errors by using the `alluxio fsadmin doctor storage` command, see https://github.com/Alluxio/alluxio/pull/8736 for details.

**Comment by maobaolong** [comment]
@bf8086  Thank you for your reply, if we have a startup error for this error storage, we can know the storage error early.

**Comment by ggezer** [comment]
@bf8086 Maybe we can have a flag to crash the worker instead when startup check fails on some directory ?

**Comment by jja725** [comment]
seems like this is more of a feature request. Will close it for now, feel free to reopen it and contact us if this is a strong request.
