### ISSUE TITLE
Please build docker image for alluxio fuse for 2.0.0 preview, thanks

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9046]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by bf8086** [comment]
@cheyang We have published docker images for recent 2.0.0 RC release. You can check them out at https://hub.docker.com/r/alluxio/alluxio/

**Comment by cheyang** [comment]
Thank you!
