### ISSUE TITLE
More documentation on FS APIs

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9100]
**Is your feature request related to a problem? Please describe.**

More documentation put into the FS API:
https://docs.alluxio.io/os/user/edge/en/api/FS-API.html

For example, 
- How to build a minimal Java app using Alluxio FS API
- Basic functions of Java API
- Examples to use REST API 

**Describe the solution you'd like**
Described above

**Describe alternatives you've considered**

**Urgency**
Median

**Additional context**

**Comment by LuQQiu** [comment]
https://docs.alluxio.io/os/user/edge/en/api/Java-API.html
