### ISSUE TITLE
HDFS ACLs not synced when HDFS ACLs get changed

### ISSUE THREAD

**Issue by chentao** [Alluxio/alluxio#9117]
**Alluxio Version:**
2.0-preview and 2.0 master branch

**Describe the bug**

- when profile "hdfsAcl" is enabled ("hdfsActiveSync" disabled):
    1. `hadoop fs -mkdir /tmp/testacl`
    2. `hadoop fs -setfacl -m "user:tchen2:rwx" /tmp/testacl`
    3. `alluxio fs getfacl /tmp/testacl`
         so far is OK.
    4. `hadoop fs -setfacl -m "user:tchen3:rwx" /tmp/testacl`
    5. `alluxio fs getfacl /tmp/testacl`
         the second ACL(user tchen3) is not showed, i guess not synced to alluxio.

- when profile "hdfsActiveSync" is enabled ("hdfsAcl" disabled):
    1. same steps as before, both the two ACLs is not showed
    2. with `alluxio startSync` executed, ACLs is not synced

- when enable the two profiles, "ACL sync" is totally dismissed
     the two profiles "hdfsAcl" and "hdfsActiveSync" exclude each other's provider class:
![image](https://user-images.githubusercontent.com/101755/58092688-4968e980-7bff-11e9-96a7-0110d6946f5d.png)

**To Reproduce**
as "Describe the bug"

**Expected behavior**
newly added ACLs to HDFS path is showed at alluxio getfacl command.

**Urgency**

**Additional context**
alluxio: 1 master , 1 worker, HDFS cluster with 6 nodes
alluxio-site.properties: 
```
alluxio.master.hostname=host123
alluxio.underfs.address=hdfs://ns1/
alluxio.worker.memory.size=32GB
alluxio.underfs.hdfs.configuration=/etc/hadoop/conf.cloudera.hdfs/core-site.xml:/etc/hadoop/conf.cloudera.hdfs/hdfs-site.xml
```

**Comment by bf8086** [comment]
Alluxio by default does not automatically sync file metadata from under file system, so the first case (hdfsAcl enabled and hdfsActiveSync disabled) is expected.

When `hdfsAcl` profile is disabled, Alluxio will not attempt to retrieve ACL information from HDFS.

The 3rd case sounds like a bug. @yuzhu Can you take a look?
