### ISSUE TITLE
WebUI gets an index out of bounds error for large directories

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#9137]
**Alluxio Version:**
2.0.0-preview

**Describe the bug**
When trying to access a directory with over 1 thousand files, the browse REST endpoint throws an error. It is not 100% known that the error is due to the number of files.

**To Reproduce**
Create a directory with 1000 files, try to access it through the browse page on the UI.

**Expected behavior**
The UI displays the files in the directory.

**Urgency**
Urgent, this prevents users from using the WebUI.

**Additional context**
Master side error:
`RestUtils - Unexpected error invoking rest endpoint: Index: 0, Size: 0`

**Comment by MBlanco03** [comment]
Attempted to recreate the bug in both 2.0.0-preview and master and was not able to reproduce. I made a new directory and created copies from a single file until there were over 1000 files. I was able to browse the directory in the WebUI with no errors.
