### ISSUE TITLE
Create helm chart to simplify the alluxio deployment in Kubernetes

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9171]
**Is your feature request related to a problem? Please describe.**

One click to install alluxio in Kubernetes is helpful in delivering alluxio in the kubernetes. Maybe helm can help install/upgrade/uninstall scenario for alluxio.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by apc999** [comment]
Addressed in 2.1 snapshot by https://github.com/Alluxio/alluxio/pull/9468
