### ISSUE TITLE
the package for UI , called node-10.11.0-linux-x64.tar.gz can't be extracted

### ISSUE THREAD

**Issue by Oscilloputer0627** [Alluxio/alluxio#9191]
**Alluxio Version:**
newest version

**Describe the bug**
one the instrall process pops out a info
"[INFO] Alluxio UI 2.0.0-SNAPSHOT .......................... FAILURE [  1.423 s]"

and the [ERROR] message are as below:

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project alluxio-webui: Could not extract the Node archive: Could not extract archive: '/home/orkesh_nurbolat/.m2/repository/com/github/eirslett/node/10.11.0/node-10.11.0-linux-x64.tar.gz': EOFException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :alluxio-webui

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**

**Additional context**

**Comment by bf8086** [comment]
@Oscilloputer0627 Looks like the file `/home/orkesh_nurbolat/.m2/repository/com/github/eirslett/node/10.11.0/node-10.11.0-linux-x64.tar.gz` is not downloaded correctly. Can you try deleting it and rerun the maven command?

**Comment by Oscilloputer0627** [comment]
@bf8086 OK., let me try...

**Comment by rastogiasr** [comment]
@Oscilloputer0627 - please reopen if the issue is still there.
