### ISSUE TITLE
FileSystemContext.acquireMasterClient() cause NPE while we create FileSystem.create()

### ISSUE THREAD

**Issue by nkrishnappaGIT** [Alluxio/alluxio#9193]
**Alluxio Version:**
What version of Alluxio are you using?
1.8.0

**Describe the bug**
whenever we're trying to upload multiple files simultaneously to alluxioFileSystem. Ex: if I upload 10 files, 2-3 file upload fails due to a below-given exception. 

And I’m using below api: 

```
FileSystem.get(hdfsConfiguration)

fileSystem.create(alluxioFilePath, (short) 1)
```

hdfsConfiguration contains 

```
"[fs.alluxio.impl]": alluxio.hadoop.FileSystem"
[fs.AbstractFileSystem.alluxio.impl]": alluxio.hadoop.AlluxioFileSystem
```

```
Exception - java.lang.NullPointerException: nullat
alluxio.client.file.FileSystemContext.acquireMasterClient(FileSystemContext.java:285)at 
alluxio.client.file.BaseFileSystem.exists(BaseFileSystem.java:187)at 
alluxio.client.file.BaseFileSystem.exists(BaseFileSystem.java:181)at 
alluxio.hadoop.AbstractFileSystem.create(AbstractFileSystem.java:183)at 
alluxio.hadoop.FileSystem.create(FileSystem.java:27)at 
org.apache.hadoop.fs.FileSystem.create(FileSystem.java:909)at 
org.apache.hadoop.fs.FileSystem.create(FileSystem.java:890)at 
org.apache.hadoop.fs.FileSystem.create(FileSystem.java:816)

```

**Expected behavior**
All files should be uploaded successfully. 

Alluxio JIRA Link - https://alluxio.atlassian.net/browse/ALLUXIO-3399

**Comment by apc999** [comment]
I think this is a race condition fixed in v1.8.1 with `CONTEXT_CACHE_LOCK` to guard the singleton creation inside [`FileSystemContext.get`](https://github.com/Alluxio/alluxio/blob/082ccd3594f20e617a2e894df0846bcfdb1c2555/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java#L134)
