### ISSUE TITLE
hdfs metadata loading is very slow when setting alluxio.user.file.metadata.sync.interval to 0

### ISSUE THREAD

**Issue by gengxin** [Alluxio/alluxio#9214]
**Alluxio Version:**
1.8.1

**Describe the bug**
hdfs metadata loading is very slow and metric of GetFingerprint ufs operation is very large when setting alluxio.user.file.metadata.sync.interval to 0

**To Reproduce**
We are testing apache impala on alluxio, the software environment includes:
1. alluxio 1.8.1, hdfs 2.7.3, impala 2.12
2. set alluxio.user.file.metadata.sync.interval to 0 so impala can always read the newest data from hdfs (which will be updated frequently by hive / spark).

After executing SQL on impala for about 2 hours, we found:
1. hdfs metadata loading become very slow and many sql executions are blocked, much slower than directly access namenode.
2. In metrics page of alluxio master, we found GetFingerprint ufs operation is much larger than GetFileStatus ufs operation. 

![image](https://user-images.githubusercontent.com/1214939/58937690-be165900-87a5-11e9-931a-f460bccd1921.png)

**Expected behavior**
load metadata from alluxio should not be much slower than load from namenode

**Urgency**
Many sql executions are blocked.

**Comment by witgo** [comment]
https://github.com/Alluxio/alluxio/pull/7924/files

**Comment by gengxin** [comment]
@witgo Thanks, we will have a try.

**Comment by rastogiasr** [comment]
@gengxin - please verify if your issue is resolved, if not reopen the issue.
