### ISSUE TITLE
EMR integration does not work with embedded journal

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#9236]
**Alluxio Version:**
2.0.0-SNAPSHOT

**Describe the bug**
When launching Alluxio with the given emr script, the master fails to come up due to the journal not being formatted.

**To Reproduce**
Start an Alluxio cluster with the instructions provided for Alluxio on EMR.

**Expected behavior**
The Alluxio cluster comes up successfully.

**Comment by apc999** [comment]
@ns1123 we need to run "alluxio format" before starting the cluster to format the cluster (master journal, worker dirs)

**Comment by ns1123** [comment]
This is resolved by #9247
