### ISSUE TITLE
Short circuit write IO metrics is not reported even with client metrics collection enabled

### ISSUE THREAD

**Issue by bf8086** [Alluxio/alluxio#9273]
**Alluxio Version:**
2.0.0-RC3

**Describe the bug**
Enable client metrics collection and start the cluster in local mode. Try writing a file using copyFromLocal and the Alluxio Write metrics does not increase.

**To Reproduce**
See above.

**Expected behavior**
The metrics should record the bytes written through copyFromLocal

**Urgency**
medium - can be confusing for user tweaking locality.

**Additional context**

**Comment by rastogiasr** [comment]
@ZacBlanco  - I think this has been resolved.

**Comment by ggezer** [comment]
@ZacBlanco Can you please verify is this is resolved?

**Comment by LuQQiu** [comment]
Short-circuit read/write will be deprecated in future alluxio versions and will not focus on improving them
