### ISSUE TITLE
Consolidate tieredstore  alias with mediatype

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9352]
**Summary**
We have both `alluxio.worker.tieredstore.level{x}.alias` and
`alluxio.worker.tieredstore.level{x}.mediatype`, where the latter can be viewed as the extended version of `alluxio.worker.tieredstore.level{x}.alias`. This is a valid setting:

```
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.mediatype=MEM,SSD,HDD
```
which can be very confusing to users.

I am proposing to

- first make `alias` and `mediatype` the same property, which requires to fix the capacity collection and display (which is totally depending on `alias` but ignoring `mediatype`
- eventually remove `alias`

**Urgency**
It is pretty confusing to have a tier with `alias=MEM` but meanwhile setting `mediatype=MEM,SSD,HDD` to indicate three storage dirs on different media type.

**Comment by jja725** [comment]
Will close it for now, and would reconsider tier management during redeisgn
