### ISSUE TITLE
Support specifying mode when create new file by Alluxio FUSE

### ISSUE THREAD

**Issue by liuhongtong** [Alluxio/alluxio#9367]
**Alluxio Version:**
Alluxio 1.8 or 2.0

**Describe the bug**
If create a new file with mode 0740, then get mode 0644.

**To Reproduce**
test program(C):
```
/* creat.c */
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>

int main(int argc, const char **argv)
{
    //int ret = open("mode_0740", O_CREAT, S_IRWXU | S_IRGRP);
    int ret = creat("mode_0740", S_IRWXU | S_IRGRP);
    if (ret >= 0) {
        printf("open mode_0740 fd: %d\n", ret);
        return 0;
    } else {
        printf("open mode_0740 failed: %d\n", errno);
        return -errno;
    }
}
```
gcc creat.c -o /tmp/creat
cd /your/alluxio/fuse/directory
\# execute test program
/tmp/creat
ls -l mode_0740
-rw-r--r-- 1 root root 0 Jun 27 16:20 mode_0740
\# this mode_0740 file's mode is 0644

**Comment by bf8086** [comment]
@LuQQiu Can you take a look? Seems to me it was not implemented in the fuse client.
