### ISSUE TITLE
Provide a way to start Alluxio processes in foreground for process supervisors

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#9389]
**Is your feature request related to a problem? Please describe.**

In many Linux-based distributions such as Debian, Ubuntu, CentOS, RHEL, etc.. process supervisors like `systemd` are utilized to launch processes and track the life of a process, and automatically restart the process if it fails.

To function properly these process supervisors expect a program which runs in the foreground when launched in a terminal. This is because supervisors like `systemd` take care of daemonizing and tracking the status of the process.

Currently, our start script only starts processes via a command in the form`(nohup ${args} 2>&1 ${log_path}) &`. We provide no options which leaves out the `&` that forces the process into the background.

**Describe the solution you'd like**

It would be useful to add an option to our `alluxio-start.sh` script that will force the Alluxio java process to run in the foreground. This would allow process supervisors to properly track Alluxio (job) masters, (job) workers, and possibly restart, or report when these processes crash or fail.

It might also be useful to provide a "default" set of system service files so that users can install Alluxio as a service through systemd.

**Describe alternatives you've considered**

None so far

**Urgency**

Low

**Additional context**

**Comment by ZacBlanco** [comment]
@apc999 what do you think?

**Comment by madanadit** [comment]
+1
