### ISSUE TITLE
What's the solution of HA alluxio cluster in Kubernetes?

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9391]
**Alluxio Version:**
2.0.0
**Describe the bug**
What's the solution of HA alluxio cluster in Kubernetes?

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by rastogiasr** [comment]
Please ask the question in mailing list or slack and this is not a bug or feature request.

**Comment by cheyang** [comment]
> Please ask the question in mailing list or slack and this is not a bug or feature request.

I think this should be in document to make the user understand the HA strategy in Kubernetes. @apc999 @madanadit

**Comment by fengguangyuan** [comment]
@cheyang @rastogiasr 
Hi, dear all. I'm a newer for Alluxio, and want to deploy Alluxio 2.0 on a product cluster, but from the latest official doc, I got this note.

> Note: Embedded Journal configuration is not supported on Kubernetes.

I do really have no much knowledges of Embedded Journal implementation, so could you give me some clues for that caution? 
Thanks a lot.
