### ISSUE TITLE
Investigate if passing property values to docker is fully supported

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9393]
**Is your feature request related to a problem? Please describe.**

Currently, to pass customized properties to a docker container through environment variable `ALLUXIO_JAVA_OPTS`, space is used as the separator across different property keys. This prevents us using property keys with values having space inside.

e.g.,:
```
$ docker run -d \
           --net=alluxio_nw \
           --name=alluxio-worker \
           --shm-size=1G \
           -v ufs:/opt/alluxio/underFSStorage \
           -e ALLUXIO_JAVA_OPTS="-Dalluxio.worker.memory.size=1G -Dalluxio.master.hostname=alluxio-master" \
           alluxio/alluxio worker
```
**Describe the solution you'd like**
Not clear now

**Describe alternatives you've considered**

**Urgency**
Median

**Additional context**

**Comment by apc999** [comment]
I realized that passing values with space is supported here by single quote: https://docs.alluxio.io/os/user/2.0/en/deploy/Running-Alluxio-On-Docker.html#set-server-configuration

I updated this task to investigate if the current way to pass properties is sufficient to cover all cases. @rastogiasr

**Comment by madanadit** [comment]
looks like this works, closing this issue
