### ISSUE TITLE
Make PropertyKey type-safe

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9396]
**Summary**
Introduce type-safe `PropertyKey`s, so getters like `Configuration.getMs` can only accept properties meant to be a time duration; passing other properties as the argument will raise runtime compilation error, like `conf.getMs(PropertyKey.MASTER_RPC_PORT)`

Benefits include:
- Compile time type check to ensure property keys are used correctly: `conf.getMs(PropertyKey.MASTER_RPC_PORT)` will not compile.

- Fine-grained access control depending on property types: `conf.getCredential(PropertyKey.GCS_ACCESS_KEY)` yields different result from  `conf.get(PropertyKey.GCS_ACCESS_KEY)`

**Urgency**
This is something good to have, most benefiting developers but less for users.

**Comment by LuQQiu** [comment]
Addressed by https://github.com/Alluxio/alluxio/pull/15097
