### ISSUE TITLE
Add noEvictor class to one layer of tieredstore

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9399]
**Is your feature request related to a problem? Please describe.**
In Deep learning scenario, we are using `MEM` layer to speed up training speed. But the eviction action in `MEM` layer produces additional overhead. 

**Describe the solution you'd like**
Can we add `noEvictor` to `alluxio.worker.evictor.class`, and make it for MEM layer? it just doesn't add more data to `MEM` layer. And the deep learning application can be benefit with the memory layer without swap in and out.

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by apc999** [comment]
@cheyang  thanks for proposing the idea. Wondering if command `pin`([doc](https://docs.alluxio.io/os/user/2.0/en/basic/Command-Line-Interface.html#pin)) work for you for this particular purpose? Basically, "pinned" data in Alluxio space will not be evicted out.

**Comment by cheyang** [comment]
Yes, I think this one should be good for my scenario. I will try it later.

**Comment by cheyang** [comment]
@apc999 , I see the following error. As you know the data for training is always read-only. Any suggestions?

```
/opt/alluxio/bin/alluxio fs pin  /training-data/images/
A write operation on /training-data/images under a readonly mount point /training-data/images is not allowed
```

**Comment by apc999** [comment]
Pin should not be a write operation.  @cheyang  let me fix this issue
