### ISSUE TITLE
Track job service metrics

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#9400]
**Is your feature request related to a problem? Please describe.**
When the job service does work, metrics such as I/O amount are not tracked.

**Describe the solution you'd like**
Work done by the job service is displayed along with the Alluxio cluster metrics.

**Comment by yuzhu** [comment]
Specifically we want to track
for these job types:
DistributedLoad - # of files loaded, total size loaded, average rate of loading
DistributedCopy, Migrate job, AsyncPersist

**Comment by LuQQiu** [comment]
@jja725 I think a bunch of job service metrics have been added, correct me if i am wrong

**Comment by jja725** [comment]
yes, they are added for distributedLoad, Cp, Mv.

**Comment by LuQQiu** [comment]
Thanks @jja725 ! Close issue since job service metrics is added. Please re-open if additional job service metrics are needed
