### ISSUE TITLE
data balance

### ISSUE THREAD

**Issue by phenixmzy** [Alluxio/alluxio#9425]
**Is your feature request related to a problem? Please describe.**
i am add several  worker node in cluster, the data won't balance to new worker node.
so, 
1  Is it necessary add a balance tools to balance data between worker nodes；
2  balance between store level.the balance strategy priority of consume top store level (eg: in HDD block may be move to new node memory until ratio)
or just between store level balance(eg: memory to memory , HDD to HDD).

**Comment by ZacBlanco** [comment]
Hi @phenixmzy!

To answer your questions:

1) You should not need another tool to balance data across other nodes unless the amount of control desired is more than what Alluxio location policies provide. See below for a bit more on read location policies.

2) I do not believe we currently have any balancing strategies between tiers across nodes. However, we do provide the option to move data between different medium types (MEM, SSD, HDD) in Alluxio 2.0. I don't quite understand the point you're trying to get across here. Could you elaborate a bit further?

### Read Location Policies

The worker that your data ends up on will depend on the read location policy. For best performance, you typically will want the data cached locally on the same node which requires the data.

From the page https://docs.alluxio.io/os/user/stable/en/advanced/Performance-Tuning.html

> 3. Is data is well-distributed across Alluxio workers?

> By default, Alluxio clients will use the LocalFirstPolicy to write data to their local Alluxio worker. This is efficient for applications which write data from many nodes concurrently. In a scenario where all data is written from a single node, its local worker will be filled, leaving the remaining workers empty. See [this page](https://docs.alluxio.io/os/user/stable/en/api/FS-API.html#location-policy) for discussion of the different location policies and how to configure them.

If your data exceeds the cache of an Alluxio worker, you may want to configure the LocationPolicy on your applications. This will improve data distribution across your cluster.

**Comment by rastogiasr** [comment]
If this issue is still valid, please re-open it.
