### ISSUE TITLE
Skip module alluxio-shaded-hadoop during release 

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9432]
**Alluxio Version:**
v2.0.0

**Describe the bug**
module alluxio-shaded-hadoop should not be published to maven repo. During `mvn release` process, this module should be skipped, so the version of this module (`${ufs.hadoop.version}`) will not be hard-coded and bumped, preventing the bug like https://github.com/Alluxio/alluxio/issues/9416

**To Reproduce**

**Expected behavior**

**Urgency**
High

**Additional context**
See bug report https://github.com/Alluxio/alluxio/issues/9416 . A quick fix has been merged but this ticket is looking for a clean solution

**Comment by zrss** [comment]
cc

**Comment by LuQQiu** [comment]
In the `alluxio/shaded/hadoop/pom.xml`, we already have the `maven-deploy-plugin` which configures that the `alluxio-shaded-hadoop` will be skipped during deployment. 

When we publish release. we use maven release plugin:
```
mvn release:prepare    // alluxio-shaded-hadoop will not be skippped.  ${ufs.hadoop.version} will be resolved to 2.2.0 (should be changed back manually after release)
mvn release: perform //alluxio-shaded-hadoop will be skipped so it will not be published to the maven main repo.
```

**Comment by rastogiasr** [comment]
@LuQQiu -can this issue be closed.

**Comment by LuQQiu** [comment]
Yeah
