### ISSUE TITLE
EMR Bootstrap script Errors in 2.0.0

### ISSUE THREAD

**Issue by CraigChaffee** [Alluxio/alluxio#9435]
**Alluxio Version:**
2.0.0

**Describe the bug**
The bootstrap script doesn't work on the latest EMR.
1. integration/emr/alluxio-emr.sh:14 should be 
`if [ -z "$MASTER" ]`
2. After fixing the above there's still a permission error in task.log for the formatWorker step. "Permission denied (publickey)."
3. The comments in the file refer to a preview version that is 404.

**To Reproduce**
Deploy the latest version of EMR and Alluxio 2.0.0 per the documentation.

**Comment by ZacBlanco** [comment]
Hi Craig, thanks for reporting this! @ns1123 can you take a look when you have the time.

**Comment by apc999** [comment]
Resolved with https://github.com/Alluxio/alluxio/pull/9467. The issues with previous script were
- curl version change : different return code were seen. Now switched to Alluxio shell script directly to coordinate the start of Master and Workers
- Stop using monitor when launching
