### ISSUE TITLE
Some fonts in the WebUI on Firefox show up black.

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#9445]
**Alluxio Version:**
2.0.0

**Describe the bug**
Download the latest version of Firefox on MacOS and open the Alluxio UI and click the "Browse" tab. 

All of the filesystem entries are black. Nearly impossible to read. Not very usable.

**To Reproduce**

- Download the latest version of Firefox
- Start Alluxio locally `alluxio-start.sh local SudoMount`
- go to http://localhost:19999/browse
- Font color is all black

![image](https://user-images.githubusercontent.com/3464508/61013284-f2e27680-a336-11e9-882a-4a54b3941e77.png)

![image](https://user-images.githubusercontent.com/3464508/61013305-02fa5600-a337-11e9-98da-ad4aeae5eed1.png)

**Expected behavior**

The font colors should be green for filename and white for permissions like they are in Google Chrome

![image](https://user-images.githubusercontent.com/3464508/61013365-21f8e800-a337-11e9-9cb3-0311cc1da59a.png)

**Urgency**
Depends on how many people use firefox.

**Additional context**

I think it stems from the way the react application loads fonts. Chrome and Firefox handle them differently.

**Comment by ZacBlanco** [comment]
@tieujason330 FYI

**Comment by ggezer** [comment]
@tieujason330 Is this issue still present?

**Comment by ZacBlanco** [comment]
This is fixed by #10826
