### ISSUE TITLE
Short-circuit read metrics got removed from webUI

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9450]
**Summary**
We should put it back and depending on `alluxio.user.metrics.collection.enabled`, show something like `N/A` if the flag is `false`. The current way to display metrics is confusing and users may have wrong takeaway on data locality
![image](https://user-images.githubusercontent.com/1413748/61098441-dc5e1d00-a413-11e9-9dda-9fbc8d84765f.png)

**Urgency**
Median

**Comment by calvinjia** [comment]
I think we can put a placeholder for now (ie. N/A). The issue with displaying the data is that it is a partial number (ie. best effort and not guaranteed to be on for all clients) and we may want to remove the client-server metric sync in the future.
