### ISSUE TITLE
Umount failed by Alluxio FUSE

### ISSUE THREAD

**Issue by liuhongtong** [Alluxio/alluxio#9461]
**Alluxio Version:**
2.0

**Describe the bug**
Umount Alluxio FUSE mount point failed, while there is no other process occupy this mount point.
```
\# umount /mnt/alluxio-fuse/
umount: /mnt/alluxio-fuse: target is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
```

**To Reproduce**
loop execution:
```
alluxio-fuse mount -o allow_other /mnt/alluxio-fuse/ /
touch /mnt/alluxio-fuse/mount-test/mount-test
umount /mnt/alluxio-fuse/
```

**Comment by apc999** [comment]
any finding from kernel level logs on why the mount point was busy, @liuhongtong ?

**Comment by apc999** [comment]
Hi @liuhongtong, to unmount Alluxio fuse, the expected way is 

`alluxio-fuse umount /mnt/alluxio-fuse/` which will kill the alluxio fuse client process.

is there any reason you have to use system `umount` rather than `alluxio-fuse umount`?

**Comment by liuhongtong** [comment]
@apc999 umount syscall need add reference of the mount point. umount syscall may success only when the reference is 2, while the default reference is 1. If another umount executed, the reference will be 3, then all the two umount will fail.

**Comment by liuhongtong** [comment]
@apc999 alluxio-fuse umount is the right way. But FUSE is one file system of Linux, so Alluxio FUSE should support umount command as well.
