### ISSUE TITLE
Unified way to  append arbitrary Alluxio property keys in EMR bootstrap and docker CLI

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9477]
**Is your feature request related to a problem? Please describe.**

https://github.com/Alluxio/alluxio/blob/master/integration/emr/alluxio-emr.sh#L82

> # Arg 3. Extra Alluxio Options. These will be appended to alluxio-site.properties. Multiple options can be specified using ';' as a delimiter

However, ';' as a delimiter might introduce issues as it may be a part of a property value, see https://docs.alluxio.io/os/user/v2.0/en/deploy/Running-Alluxio-On-a-HA-Cluster.html

**Describe the solution you'd like**
A more general solution to pass in multiple property keys

**Describe alternatives you've considered**

**Urgency**
Medium

**Additional context**

**Comment by ns1123** [comment]
@apc999 this is already available in the EMR script as the last option.

**Comment by apc999** [comment]
what's the discussion result @ns1123 & @gpang ?
in case this is hard to achieve, we can switch to support #9489

**Comment by ns1123** [comment]
+1 for doing this using #9489 approach of an S3 file path to append to the existing properties. Escaping to me feels like over-engineering a non-problem
