### ISSUE TITLE
Support specifying worker memory size in EMR bootstrap script

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9478]
**Is your feature request related to a problem? Please describe.**

Currently "20GB" per worker was hard-coded in https://github.com/Alluxio/alluxio/blob/master/integration/emr/alluxio-emr.sh#L76

**Describe the solution you'd like**

The script should be able to accept different worker memory size. Maybe let users to specify the value in `alluxio.worker.memory.size` in `args`.

**Describe alternatives you've considered**

**Urgency**
Medium

**Additional context**

**Comment by ns1123** [comment]
@apc999 from our discussion I think we agreed to default to adding logic into the bootstrap script to calculate 1/3rd of the available memory and use that value as the default unless specified by the user. @ZacBlanco, let us know what you think of this approach
