### ISSUE TITLE
Support ability to pass in a file as an arg to EMR bootstrap to append to alluxio-site.properties 

### ISSUE THREAD

**Issue by dborkar** [Alluxio/alluxio#9489]
**Is your feature request related to a problem? Please describe.**
Some time Alluxio properties are quite complex. If a bootstrap doesn't allow a file to be passed in, updating a large number of Alluxio properties every time an EMR cluster comes up, can lead to human errors. 

**Describe the solution you'd like**
pass a file in with properties that get appended to alluxio-site.properties

**Comment by ns1123** [comment]
@dborkar Is the idea for this that as an alternative to a string input, a user can provide an s3:// URI that points to a file which is then appended to the default properties? This could work, but we may want to decide on which of the existing ones can be overridden.
