### ISSUE TITLE
Ability to pass EMR bootstrap in a pre-generated ssh public/private key pair

### ISSUE THREAD

**Issue by dborkar** [Alluxio/alluxio#9490]
In larger environments that are deployed, there is no simple way to propagate config changes and restarts to workers.  The EMR way might be to simply just re-bootstrap the entire environment with the new change, but it would be nice to have the option to be able to leverage the ALLUXIO SSH-based tools like copyDir and start/stop scripts.

**Comment by ns1123** [comment]
The SSH logic used to be there but it was pretty messy. It forces the bootstrap to create a private key, upload said key to S3, and then have all workers download from S3. This also means the user would have to redownload a new private key from S3 on each run of EMR. Is there a reason users can't redeploy a cluster?

**Comment by ZacBlanco** [comment]
I don't think this is something we want/need to do. @apc999 can you confirm/deny?

I think supporting this is much more difficult thing to implement.

**Comment by ns1123** [comment]
Closing this since this doesn't fit the EMR service model. Configuration changes should be done by redeploying the cluster.

**Comment by rastogiasr** [comment]
@dborkar - please make sure you have reviewed this ticket and the are ok with it. May want to talk to Alex about it.
