### ISSUE TITLE
Register worker fails with UnsupportedOperation exception

### ISSUE THREAD

**Issue by guang7niu** [Alluxio/alluxio#9501]
**Alluxio Version:**
2.0.1-snapshot

**Describe the bug**
When worker registers itself to master with a list of blocks, master will check for duplication of block ids. However the lambda expression will try to modify the block list provided by protobuf which is readonly, hence a UnsupportedException is raised. 
Example:
core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java::registerWorker & blockHeartbeat, 
Collectors.toMap  (e1, e2) -> {
                     e1.addAll(e2);
                     return e1;
  
**To Reproduce**
Just restart the worker (depends on what block is in worker, may not be reproduced every time)

**Expected behavior**
No exception raised.

**Urgency**
Middle

**Additional context**

**Comment by ZacBlanco** [comment]
@apc999 please close this issue if it is fixed.

**Comment by apc999** [comment]
Fixed in 2.1.0-SNAPSHOT and cherry-picked into 2.0 branch by #9517
