### ISSUE TITLE
Display three the same records in  BlockInfo tab of worker node WEBUI 

### ISSUE THREAD

**Issue by phenixmzy** [Alluxio/alluxio#9518]
**Alluxio Version:**
2.1.0-SNAPSHOT

**Describe the bug**
when entering page of **BlockInfo** of worker node , each file has three the same records in WEBUI.
clicked the link of file which three the same records, display the same information in WEBUI.
![图片](https://user-images.githubusercontent.com/303954/61579980-1ed3d800-ab3f-11e9-8273-8a1cace55f4b.png)

![图片](https://user-images.githubusercontent.com/303954/61579997-462aa500-ab3f-11e9-8653-adc78ce2065f.png)

**To Reproduce**
enter page of BlockInfo of worker node 

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by tieujason330** [comment]
@phenixmzy Do you have any steps to reproduce this? How many workers do you have? I'm not able to see this on my end

**Comment by phenixmzy** [comment]
yes, have completed, i am very busy these days so forget.

**Comment by phenixmzy** [comment]
> 
> 
> @phenixmzy Do you have any steps to reproduce this? How many workers do you have? I'm not able to see this on my end
yes, have completed, i am very busy these days so forget.

**Comment by phenixmzy** [comment]
Fixes Alluxio/new-contributor-tasks#9518
