### ISSUE TITLE
Job_master health check failed

### ISSUE THREAD

**Issue by lodocj** [Alluxio/alluxio#9526]
**Alluxio Version:**
v2.0.0

**Describe the bug**
JOB_MASTER‘s main class is alluxio.master.AlluxioJobMaster  , but MasterHealthCheckClient check command were as follows:
> ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 hostname ps -ef | grep "alluxio.master.job.JobMaster$" | grep "java" | awk '{ print $2; }'

Class alluxio.master.job.JobMaster not on the process list so that will never sucessed. 

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by ZacBlanco** [comment]
Thanks for reporting this! You are correct that the check won't succeed currently.

I took a closer look. Specifically this should happen when the job master is running in HA mode and the `alluxio-monitor.sh` script is used to check the health of the job master.

We are hoping in a near release to completely remove the need to for the `ps -ef | grep` in the health check and instead replace it with a ping to the RPC port of the job master. However, currently in HA mode, we don't open RPC ports on the non-primary job masters, so we can't use the RPC ping to check if they are up.
