### ISSUE TITLE
Support checkpointing job_master journal via shell cmd

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#9538]
**Is your feature request related to a problem? Please describe.**
`fsadmin checkpoint` cmd only works for master journal. It should support taking checkpoints on job_master journal as well.

**Describe the solution you'd like**
Additional flag for specifying the domain for the journal.

**Comment by calvinjia** [comment]
@ggezer Which journal are you referring to, we do not journal for the job master.

**Comment by ggezer** [comment]
We don't but still create a separate `JournalSystem` for `job_master`s. This is just for infrastructural completeness.

**Comment by rastogiasr** [comment]
@ggezer - what is the downside of not checkpointing the job_master journal?
