### ISSUE TITLE
alluxio fs startSync failed

### ISSUE THREAD

**Issue by myg821561935** [Alluxio/alluxio#9544]
ALLUXIO ENVIRONMENT:
(1) ALLUXIO 2.0.0
(2) HADOOP-2.7.3(HDFS)
(3) Hadoop client (Hadoop3.3)
(4) JAVA 1.8

 we set the hdfs and we want to set dir /nn-cluster/user/bigdata/tensorflow/submarine sync to hdfs dir。when we execute the command：alluxio fs startSync /nn-cluster/user/bigdata/tensorflow/submarine ，it report errors：
![image](https://user-images.githubusercontent.com/5190099/61682357-e81adf00-ad43-11e9-8789-f883580b8fe2.png)

can anyone give us some advices？

**Comment by ZacBlanco** [comment]
Hi @myg821561935 . It helps us if the initial post is in our standard format for bug reports. We ask that you follow the format next time.

1. You're initial post is not quite clear enough as to what `HADOOP-2.7.3` means. Is this the UFS version?
2. What do you mean by Hadoop client. Is this what you're using to try to connect to Alluxio?

If my assumption in (1) is correct that your UFS is HADOOP-2.7.3, then the error message is accurate. ActiveSync is not supported on Hadoop versions < 3. From my limited knowledge ActiveSync relies on the DSFInotifyEventInputStream  which is not available in Hadoop 2.7.3 (I couldn't find it in their reference docs https://hadoop.apache.org/docs/r2.7.3/api/index.html)

**Comment by myg821561935** [comment]
yes，ufs hdfs version is 2.7.3. In this blog（https://www.alluxio.io/blog/two-ways-to-keep-files-in-sync-between-alluxio-and-hdfs/）, mentioning hadoop2.7+ is fine. Maybe I was misled. thanks

**Comment by apc999** [comment]
@yuzhu can you help take a look at this issue and verify the HDFS version required

**Comment by ZacBlanco** [comment]
I could be wrong as well. I'll get a more accurate version for you some time within the next day. I'll also make sure it gets added to our documentation. I noticed that at https://docs.alluxio.io/ee/user/stable/en/advanced/Namespace-Management.html?#metadata-active-sync-for-hdfs we don't mention version compatibility

**Comment by ZacBlanco** [comment]
@myg821561935 can you also provide your Alluxio master configuration?

**Comment by myg821561935** [comment]
> @myg821561935 can you also provide your Alluxio master configuration?
ok
[alluxio-site.properties.txt](https://github.com/Alluxio/alluxio/files/3420711/alluxio-site.properties.txt)

**Comment by ZacBlanco** [comment]
Hi @myg821561935 can you try to configure the alluxio property `alluxio.underfs.version`?

https://docs.alluxio.io/os/user/stable/en/ufs/HDFS.html#using-site-properties

From the documentation, you should be able to put `2.7` as the value for this property. It defaults to 2.2: https://github.com/Alluxio/alluxio/blob/v2.0.0/core/common/src/main/java/alluxio/conf/PropertyKey.java#L3395-L3401

**Comment by myg821561935** [comment]
> alluxio.underfs.version

thanks ,after configure alluxio.underfs.version=2.7 ,it's ok

**Comment by haoyuan** [comment]
@myg821561935 great to hear!
