### ISSUE TITLE
UfsSyncPathCache does not cache descendants when recursive is used

### ISSUE THREAD

**Issue by liuzx32** [Alluxio/alluxio#9545]
**Alluxio Version:**
alluxio version 2.0.0

**Describe the bug**
After running  `ls -Rf dir_path`, `UfsSyncPathCache` only cache `dir_path`, but not the file under `dir_path` recursively.

As a result, after setting `alluxio.user.file.metadata.sync.interval=3hour` and start MR job to read the files inside the dir, 
the method `shouldSyncPath` of `UfsSyncPathCache` will get `null` from `mCache`, and then alluxio will recursively load the metadata once again for every file in the `dir_path`. It will process slowly.

**Expected behavior**
`UfsSyncPathCache` uses guava cache to cache time for path.
When `ls -Rf dif_path`, `UfsSyncPathCache` will cache the dir_path not for every recursive file,
and alluxio really has the metadata for the dir_path, but not in the `UfsSyncPathCache`.
If using the longest prefix match to get the key，and get time from cache with the lpm key, It will achieve the same effect. This way can also save memory for alluxio.

**Urgency**
very urgency

**Additional context**
Related method calls
1. DefaultFileSystemMaster.syncMetadataInternal()
2. UfsSyncPathCache.notifySyncedPath()
3. UfsSyncPathCache.shouldSyncPath

**Comment by apc999** [comment]
@gpang or @yuzhu , can you verify if this is a bug in the master implementation?

**Comment by apc999** [comment]
@gpang @yuzhu , this can be a bad bug. Can you confirm if this is the case?

**Comment by yuzhu** [comment]
I think this has been the behavior for a while. We can improve it by 
1. add all the paths into `UfsSyncPathCache` during a recursive sync,
this would result in a lot of files in the `UfsSyncPathCache`

or
2. Change `UfsSyncPathCache` to a map from <path, isRecursive> to timestamp. We only record the top level path in the cache, and during file access time, we check if its parent, its parent of parent ... has been recursively synced in the last time interval. This add some overhead in file access time. 

We are still debating which route to take to improve this. 
@liuzx32 will let you know as soon as we decide and have a fix for this.

**Comment by liuzx32** [comment]
> I think this has been the behavior for a while. We can improve it by
> 
> 1. add all the paths into `UfsSyncPathCache` during a recursive sync,
>    this would result in a lot of files in the `UfsSyncPathCache`
> 
> or
> 2. Change `UfsSyncPathCache` to a map from <path, isRecursive> to timestamp. We only record the top level path in the cache, and during file access time, we check if its parent, its parent of parent ... has been recursively synced in the last time interval. This add some overhead in file access time.
> 
> We are still debating which route to take to improve this.
> @liuzx32 will let you know as soon as we decide and have a fix for this.

@yuzhu I think that it's a problem about the longest prefix match, and only cache the parent dir can solve the last time interval case. Only cache dir not every recursive files can save memory for master.
