### ISSUE TITLE
Can't distinguish creator of file by Alluxio FUSE with allow_other options

### ISSUE THREAD

**Issue by liuhongtong** [Alluxio/alluxio#9552]
**Alluxio Version:**
2.0

**Describe the bug**
When mount Alluxio FUSE by user alluxio, if another user creates a file or directory in the mount point, the owner of the file or directory will be the user alluxio. I can't distinguish who is the true owner.

**To Reproduce**
mount Alluxio FUSE by user alluxio
```
alluxio $ alluxio-fuse mount -o allow_other /mnt/alluxio-fuse/ /
```
mkdir by user hahaha
```
hahaha $ cd /mnt/alluxio-fuse
hahaha $ mkdir hahaha
hahaha $ ls -l -d hahaha
drwxr-xr-x 1 alluxio alluxio 0 Jul 24 15:09 hahaha
```

**Comment by apc999** [comment]
I view this a feature request to support Group/User information through fuse rather than a bug report.

@LuQQiu  is there any way to get gid or uid information in JNR-FUSE?

**Comment by LuQQiu** [comment]
As far as I know, Fuse mkdir method does not expose uid and gid information. Fuse by design is to only allow the user that mounting the file system to access and do any operation in it. `allow_other` and `allow_root` is asked by users and fuse decides to loose it's restrictions but those two mount options have some security impacts and limitations. This is one of the limitations.

**Comment by liuhongtong** [comment]
I agree with @LuQQiu, but that's one limitation of jnr-fuse instead of fuse.
When studing the source code of fuse, I find fuse exposes the uid by req->ctx.uid and gid by req->ctx.gid.
```
static struct fuse_lowlevel_ops fuse_path_ops = {
        ......
        .mkdir = fuse_lib_mkdir,
        ......
}
static void do_mkdir(fuse_req_t req, fuse_ino_t nodeid, const void *inarg)
{
        struct fuse_mkdir_in *arg = (struct fuse_mkdir_in *) inarg;

        if (req->f->conn.proto_minor >= 12)
                req->ctx.umask = arg->umask;

        if (req->f->op.mkdir)
                req->f->op.mkdir(req, nodeid, PARAM(arg), arg->mode);
        else
                fuse_reply_err(req, ENOSYS);
}
```
req->f->op.mkdir may be the pointer of  fuse_lib_mkdir() by default, who ignores the req but invokes fuse_fs_mkdir(), while fuse_fs_mkdir() invokes the mkdir(). mkdir() is registered by FuseOperations in jnr-fuse.
```
static void fuse_lib_mkdir(fuse_req_t req, fuse_ino_t parent, const char *name,
                           mode_t mode)
{
        struct fuse *f = req_fuse_prepare(req);
        struct fuse_entry_param e;
        char *path;
        int err;

        err = get_path_name(f, parent, name, &path);
        if (!err) {
                struct fuse_intr_data d;

                fuse_prepare_interrupt(f, req, &d);
                err = fuse_fs_mkdir(f->fs, path, mode);
                if (!err)
                        err = lookup_path(f, parent, name, path, &e, NULL);
                fuse_finish_interrupt(f, req, &d);
                free_path(f, parent, path);
        }
        reply_entry(req, &e, err);
}

int fuse_fs_mkdir(struct fuse_fs *fs, const char *path, mode_t mode)
{
        fuse_get_context()->private_data = fs->user_data;
        if (fs->op.mkdir) {
                if (fs->debug)
                        fprintf(stderr, "mkdir %s 0%o umask=0%03o\n",
                                path, mode, fuse_get_context()->umask);

                return fs->op.mkdir(path, mode);
        } else {
                return -ENOSYS;
        }
}
```
So, If AlluxioFuse registers fuse_lowlevel_ops instead of FuseOperations, fuse can transfer req to AlluxioFuse. But that may lead to big modification.

**Comment by LuQQiu** [comment]
Thanks for doing the investigation. Looks like we need to 
either (1) modify jnr-fuse to support fuse lowlevel ops 
or (2) get ride of jnr-fuse, use libfuse + Alluxio C++ client (We have discussed that we don't want to do that for 2.0)

Will modify jnr-fuse able to register the fuse lowlevel_ops? If the modification is big, jnr-fuse author may not want to let our PRs go in, then we will need to host our version of jnr-fuse. 

Is it a really necessary requirement to allow other users to create file/dir own by them?
Will modify jnr-fuse able to solve the issue? How many effort do you think is needed?

**Comment by apc999** [comment]
@liuhongtong For 1.8 or 2.0 branch, I don't think we want to introduce big changes like switching to fuse_lowlevel_ops from FuseOperations. For future minor releases, do you have more insights into the benefits for this change in addition to support gid / uid (which can be important enough to me). It will be good to have a list of benefits and also estimated costs & risks of doing so before we make this decision

**Comment by liuhongtong** [comment]
@apc999 @LuQQiu I will do more investigation next week and evaluate costs and risks.

**Comment by liuhongtong** [comment]
@apc999 @LuQQiu I found LibFuse of jnr-fuse exposes the fuse_get_context() function, who can get the FuseContext. Then we can get uid and gid from FuseContext. I have check the source code in fuse, FuseContext is shared by fuse. 
This clue simplifies this issue immediately.
