### ISSUE TITLE
main scope polluted with test dependencies

### ISSUE THREAD

**Issue by pranasblk** [Alluxio/alluxio#9560]
**Summary**
The main scope polluted with test dependencies
https://github.com/Alluxio/alluxio/blob/a375ff4f455d20b2dc5632938931df233c96e917/minicluster/pom.xml#L45

**Urgency**
It's better to avoid test artefacts potentially creeping into production deployment (wasting resources system and providing ability to introduce dependant accidental dependencies in client's code).

**Comment by apc999** [comment]
thanks @pranasblk this is definitely a good suggestion. On a related note, are you currently using alluxio minicluster to test your Alluxio application? I would like to learn more about the experience. Previously users have problems with it https://github.com/Alluxio/alluxio/issues/8564

**Comment by calvinjia** [comment]
The Alluxio minicluster is intended to be used in testing environments as a mock Alluxio cluster. Therefore the dependencies are included outside of just a test scope.

**Comment by pranasblk** [comment]
Hi,

Not using it at the moment, but code looks good. I'll keep it on my list of
technology to explore.

Regards
Pranas

**Comment by apc999** [comment]
@pranasblk `curator-test` is needed in this module as this Alluxio Minicluster is supposed to be used as a mock in other Alluxio tests as well as external projects. Thus it is depended on compile scope currently.

but @calvinjia in the same pom, depending on the `junit` on compile scope is unnecessary and `powermock-reflect` can be relatively easily worked around too (only one method is using it). If I have spare time I will submit a small fix to improve it. For now I will close this issue as depending on `curator-test` is expected

```
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-reflect</artifactId>
      <scope>compile</scope>

```
