### ISSUE TITLE
Add a column to display file has block amount in the worker UI

### ISSUE THREAD

**Issue by phenixmzy** [Alluxio/alluxio#9576]
**Is your feature request related to a problem? Please describe.**
add a column display file has block amount in the worker . 
![图片](https://user-images.githubusercontent.com/303954/61988639-849bf480-b056-11e9-8c58-0ca50538f797.png)

**Describe the solution you'd like**
step 1
add a name of mBlocks  membership variables in UIFileInfo to record the blockid when UIFileInfo#addBlock

step 2
in webui model , add the value  at renderBlockInfoListing method in BlockInfo.tsx and BlockiInfo.test.tsx.snap and add a name blocks attribute in IFileInfo.txs 

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by bf8086** [comment]
Hi @phenixmzy, Currently to see all the blocks for a particular file, you can click on the file name to get to the page specifically for the file. There you will see a list of the blocks stored in this worker.

Is there a particular reason you need to see block count showing up in the block list page?

**Comment by phenixmzy** [comment]
> Hi @phenixmzy, Currently to see all the blocks for a particular file, you can click on the file name to get to the page specifically for the file. There you will see a list of the blocks stored in this worker.
> 
> Is there a particular reason you need to see block count showing up in the block list page?

Hi @bf8086 
I want to see block count showing up in the block list page because i want kown about
 the blocks distributed  on this worker.
Personally, I think this will make it clearer.

**Comment by phenixmzy** [comment]
> Hi @phenixmzy, Currently to see all the blocks for a particular file, you can click on the file name to get to the page specifically for the file. There you will see a list of the blocks stored in this worker.
> 
> Is there a particular reason you need to see block count showing up in the block list page?

I see column（in-MEM ）showing up 100%  of the list page for the first time，would think all the blocks on this worker.
When i click the file to detail page show not all blocks.

**Comment by LuQQiu** [comment]
@maobaolong is it useful to have this kind of information? good-to-have or must-to-have?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request!
