### ISSUE TITLE
Alluxio tag 2.0.0 can not be built

### ISSUE THREAD

**Issue by zrss** [Alluxio/alluxio#9578]
**Alluxio Version:**
What version of Alluxio are you using?

tag v2.0.0

**Describe the bug**

run the building command

`mvn -T 2C clean install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Dlicense.skip`

```
[ERROR] Failed to execute goal on project alluxio-core-server-common: Could not resolve dependencies for project org.alluxio:alluxio-core-server-common:jar:2.0.0: The following artifacts could not be resolved: io.atomix.copycat.alluxio:copycat-server:jar:1.2.12, io.atomix.copycat.alluxio:copycat-client:jar:1.2.12: Failure to find io.atomix.copycat.alluxio:copycat-server:jar:1.2.12 in http://uk.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of UK has elapsed or updates are forced -> [Help 1]
```

**Comment by zrss** [comment]
#8868

**Comment by zrss** [comment]
# 9416

**Comment by apc999** [comment]
has https://github.com/Alluxio/alluxio/pull/9428 fixed your issue @zrss ?

regarding the request on documentation, I updated https://github.com/Alluxio/alluxio/issues/9559 on `generate-tarballs`

**Comment by zrss** [comment]
thx apc999, #9428 has fixed my problem. and currently, we lack of the doc of `generate-tarballs` (i get it in buiding docker shell ...)

**Comment by apc999** [comment]
thanks for the response. As mentioned I've updated #9559 to add a task about adding more documentation on generate-tarballs.  #9559 serves as a running issue for all documentation defects (in your case the lack of description on generate-tarballs). Close your issue now.
