### ISSUE TITLE
Can Alluxio 2.0.0 works well in k8s ?

### ISSUE THREAD

**Issue by zrss** [Alluxio/alluxio#9580]
**Alluxio Version:**
What version of Alluxio are you using?

tag v2.0.0

**Describe the bug**

we can define the env in configmap in alluxio 1.8 but how can we do it in alluxio 2.0 ?

i don't suppose this can work ...

https://github.com/Alluxio/alluxio/blob/29a7c86f02f11786bafc36b5cec3b58d977122c6/integration/kubernetes/conf/alluxio.properties.template#L12

**Comment by ZacBlanco** [comment]
Hi @zrss Have you read our doc on deploying on K8s?

https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html#configure-alluxio-properties

Is there something with this solution that doesn't allow you to configure Alluxio properly in your given use case? Any extra context helps

**Comment by zrss** [comment]
thx zac. i have read this doc, and it turns out that it's very hard to understand these words. finnally i makes it work by define properties directly in alluxio-site.properties rather than env in alluxio-site.properties

```
alluxio.master.mount.table.root.ufs=<under_storage_address>
```

and obviously, the default value of alluxio-site.properties in `integration/docker` isn't work due to the entrypoint impl

https://github.com/Alluxio/alluxio/blob/29a7c86f02f11786bafc36b5cec3b58d977122c6/integration/docker/entrypoint.sh#L49-L75

it won't generate the alluxio-site.properties file and neither do a **effective** alluxio-env.sh, if u create the configmap by

```
kubectl create configmap alluxio-config --from-env-file=conf/alluxio.properties
```

**Comment by ZacBlanco** [comment]
Is there a specific sentence(s) that are hard to understand or that you would like to see changed?

Setting values directly in site properties can work, but using the master/worker templates along with the configmap command should be easier to use than defining site properties across many containers. 

Also, the documentation for k8s has been recently updated as we've added a helm chart in `master`. The instructions for non-helm deployment with `kubectl` has also been updated. Could you take a look at the latest version and let us know if it is more helpful?

https://docs.alluxio.io/os/user/edge/en/deploy/Running-Alluxio-On-Kubernetes.html#using-kubectl
