### ISSUE TITLE
can generate-tarballs exclude webui

### ISSUE THREAD

**Issue by zrss** [Alluxio/alluxio#9594]
**Is your feature request related to a problem? Please describe.**

tag v2.0.0

webui building cost much time

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by gpang** [comment]
@zrss Thanks for this issue! Could you fill out all the sections in the description?

**Comment by ns1123** [comment]
@zrss Currently, generate-tarballs is used to bundle Alluxio binaries into a full release for end-users. For this reason, it wouldn't make sense to remove the webui as part of this build. Internally it runs this command with some added profiles.

mvn -T 2C -am clean install -DskipTests -Dfindbugs.skip -Dmaven.javadoc.skip -Dcheckstyle.skip

If you want to skip building the web-ui, I would add "-pl webui" and run the mvn command locally in the root of the alluxio repo. I've tried adding the arguments to the generate tarball script, but it seems that the generate-tarball script doesn't parse the argument correctly for mvn.

**Comment by zrss** [comment]
thx ns1123. we deploy the alluxio by container in k8s, or could we give a doc about building a docker image of alluxio after the mvn building ?

currently, i just see the `generate-tarballs` can build a tarball in a convenient way then untar this tarball to docker image for image building

**Comment by ns1123** [comment]
@zrss I've raised a PR for your change. I'm not sure if it will get accepted, but if not, you can checkout the file from my repo and add the flag for skipping the webui stage. Testing shows that the flag shaves off 2 minutes from the build time.

**Comment by zrss** [comment]
oh thx @ns1123  ~ i can borrow your mind and apply to my local alluxio

**Comment by ns1123** [comment]
Glad to help :) If this solves your problem, remember to close this issue.
