### ISSUE TITLE
[Doc Improvement] Add / Improve ActiveSync doc

### ISSUE THREAD

**Issue by haoyuan** [Alluxio/alluxio#9609]
**Is your feature request related to a problem? Please describe.**
In community channel, ppl asked "Does ActiveSync in Alluxio only support hadoop3+?".

**Describe the solution you'd like**
Add doc for ActiveSync and the doc should have addressed this question.

**Describe alternatives you've considered**
N/A

**Urgency**
Important. Impact user experience.

**Additional context**
https://groups.google.com/forum/?fromgroups#!topic/alluxio-users/fCNxsUuZ_TA

**Comment by ns1123** [comment]
Doc for ActiveSync: https://docs.alluxio.io/os/user/stable/en/advanced/Namespace-Management.html?q=active%20sync#metadata-active-sync-for-hdfs

Needs to be updated with supported HDFS versions

**Comment by ZacBlanco** [comment]
It should also specify that users need to set `alluxio.underfs.version` if using a high enough version of HDFS, or else this defaults to 2.2 which doesn't support activesync

**Comment by ZacBlanco** [comment]
@haoyuan can you please edit the title of this issue to more accurately reflect the change we are trying to make?

**Comment by haoyuan** [comment]
@ZacBlanco updated.

**Comment by yuzhu** [comment]
Fixed in #9756

**Comment by apc999** [comment]
Fixed by https://github.com/Alluxio/alluxio/pull/9756
