### ISSUE TITLE
Async flush data to shared data storage takes a lot of time!

### ISSUE THREAD

**Issue by haoyuan** [Alluxio/alluxio#9610]
**Is your feature request related to a problem? Please describe.**
In alluxio 2.0, async flush data to shared data storage (Isilon) takes a lot of time!

**Describe the solution you'd like**
Faster async to leverage bandwidth between Alluxio and its UFS fully.

**Describe alternatives you've considered**
Some users are running their own scripts to get this done.

**Urgency**
The sooner the better.

**Additional context**
Thanks @mohammad-ligadata for providing this feedback!

**Comment by gpang** [comment]
Hi @mohammad-ligadata , could you provide additional details on this scenario? For example, is there an isolated example where the async-through is slower than the manual scripts? Also, how are the scripts persisting the data to the UFS? Thanks!

**Comment by rastogiasr** [comment]
If this is still valid, re-open the issue.
