### ISSUE TITLE
Publish k8s helm chart to public repo

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#9615]
**Is your feature request related to a problem? Please describe.**
Publish Alluxio chart to https://github.com/helm/charts so that there is no requirement to set up own helm repo.

**Describe the solution you'd like**
Contribute to helm repo: https://github.com/helm/charts/blob/master/CONTRIBUTING.md

**Describe alternatives you've considered**

**Urgency**

**Additional context**

**Comment by madanadit** [comment]
In addition, we might consider publish SNAPSHOT charts on a nightly basis

**Comment by ssz1997** [comment]
@LuQQiu The helm repo is archived and not supported any more. Currently we publish our helm chart on google storage managed by ourselves.

Someone also publish it here: https://artifacthub.io/packages/helm/alluxio/alluxio, which is an open source project. Personally I don't see the necessity to publish our helm chart here.

**Comment by LuQQiu** [comment]
Thanks @ssz1997 for giving the updates! 
This issue has been closed due to inactivity and is not valid anymore. Please re-open if you have a preferred location to put our helm charts to with reasons of why it helps your use case. Thanks!
