### ISSUE TITLE
Metrics JSON endpoint not reporting correct UFS metrics

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#9628]
**Alluxio Version:**
1.8.2

**Describe the bug**
UFS metrics are not reported correctly. When creating two different mount points on the same HDFS cluster, operations on the second mount point are incorrectly reported to the first mount point.

**To Reproduce**
Mount two different directories from an HDFS cluster into the same Alluxio cluster. RunTests on the second mount directory. Check the /metrics/json/ endpoint and see the value of getBlockSizeBytes().

**Expected behavior**
Operations like getBlockSizeBytes should be reported based on which mount point they were run on instead of aggregating in the first mount point.

**Urgency**
Medium

**Additional context**
Was not able to reproduce in 2.x

**Comment by gpang** [comment]
@ns1123 @chcn Do we know why is this not reproducible on master branch?

**Comment by gpang** [comment]
fixed by https://github.com/Alluxio/alluxio/pull/9846 https://github.com/Alluxio/alluxio/pull/10343
