### ISSUE TITLE
alluxio 2.0.0 browse?path not working

### ISSUE THREAD

**Issue by venukolluri** [Alluxio/alluxio#9651]
alluxio 2.0.0 browse?path not working for a path (mounted hdfs) with more files (300+).  I can browse directories with less files,

Thanks,
Venu

**Comment by calvinjia** [comment]
@venukolluri Could you provide some more details such as how the page doesn't work (500 error or page just doesn't load) and if there are any other special characteristics aside from the number of files in the directory?

Does the path you are browsing have special characters (ie `=`)? If so, it could be related to https://github.com/Alluxio/alluxio/pull/9473

**Comment by venukolluri** [comment]
yes calvin, path is /mnt/hdfs/emr/test/year=2016/.....

**Comment by calvinjia** [comment]
This is a known issue which will be addressed in 2.0.1.
In the meanwhile you can use the CLI to list the directory (`bin/alluxio fs ls`). Alternatively you could build 2.0.1-SNAPSHOT from `branch-2.0` which already has the fix.

**Comment by venukolluri** [comment]
Great, Thanks Calvin. Do you've release date for 2.0.1?

**Comment by calvinjia** [comment]
2.0.1 will most likely be released this month (August).
