### ISSUE TITLE
Add docs for running Tensorflow / other ML frameworks on k8s

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#9671]
**Is your feature request related to a problem? Please describe.**
Improve k8s documentation by providing guidelines for running a framework like Tensorflow on Alluxio in k8s.

**Describe the solution you'd like**
Add a documentation page for ML frameworks on k8s with recommendations such as using the POSIX FUSE API and common pitfalls / configuration options.

**Describe alternatives you've considered**
N/A

**Urgency**
Medium

**Additional context**
In addition, for standalone Alluxio deployment on k8s the use of the helm chart or its shortcomings should be mentioned.

**Comment by LuQQiu** [comment]
[There is ](https://docs.alluxio.io/os/user/stable/en/compute/Tensorflow.html)
