### ISSUE TITLE
Implement a fast CLI

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#9673]
**Is your feature request related to a problem? Please describe.**
The Alluxio CLI (ie. `bin/alluxio fs`) is very slow (~1s+ response times).

**Describe the solution you'd like**
A faster Alluxio CLI (<100ms response times)

**Urgency**
Not urgent

**Additional context**
We could use the rest interface but that has a dependency on the proxy.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
