### ISSUE TITLE
Handle interrupt exceptions consistently in the codebase

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#9679]
**Summary**
Interrupt exceptions are handled in different ways throughout the codebase, some of which are not following best practice which can lead to bugs or unexpected behavior.

Define a convention for handling them and apply this to the codebase. Ideally add static analysis to ensure the conventions are adhered to.

For example, if an interrupt is logical as part of the operation, propagate the interrupt after possible cleanup steps.
Alternatively, if the method can logically handle the interrupt, handle it within the method and propagate the interrupt flag before returning to the caller.

**Urgency**
We can avoid unexpected and hard to debug runtime behavior.

**Comment by jja725** [comment]
Will reconsider it when exception redesign. close it for now, feel free to reopen it and contact us if this is a strong request.
