### ISSUE TITLE
Website documentation search doesn't use the "edition" search criteria

### ISSUE THREAD

**Issue by niyue** [Alluxio/alluxio#9688]
**Alluxio Version:**
2.0.0

**Describe the bug**
Website documentation search result could hide enterprise edition documentation if community edition is selected in the search criteria. 
Currently the edition criteria doesn't seem to work, and people may not notice the edition change after searching. This may be misleading sometimes, and users may get confused how to proceed when seeing some enterprise relevant information, and it could be problematic if the operation described in the documentation could be applied the same way to two editions but with different outcome.

**To Reproduce**
* Go to https://docs.alluxio.io/os/user/stable/en/search.html
* Select "Community Edition" on the left hand side menu as the search criteria
* Enter "docker" as keyword for searching and search
* In the search result, click the first item, named "Deploy Alluxio on Docker - Alluxio v2.0 (stable) Documentation". It is a documentation for enterprise edition (at least currently), and the second item with the same title is for community edition.

**Expected behavior**
Only documentation for "community edition" are shown since it is used as search criteria for documentation (at least the "version" number like v1.8 works this way). However, documentation for "enterprise edition" are shown as well in the search result. 

**Urgency**
Low

**Additional context**

**Comment by apc999** [comment]
@Xenorith some feedback from users on the search function

**Comment by ZacBlanco** [comment]
@apc999 

This was an internal ask from the team to combine search functions. It is not a bug. I do not expect that we will change this behavior.

I've asked previously to designate which search results are EE/OS but I don't think we'll be doing that any time soon
