### ISSUE TITLE
Improved the structure of Alluxio CLI commands

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9691]
**Is your feature request related to a problem? Please describe.**

Reorganize Alluxio CLI to implement the CLI style to Git or Brew using subcommands with very few entry points, rather than exposing too many separate scripts for users to start

**Describe the solution you'd like**
This is initial idea regarding the new structure. We can iterate from here:

- Use `bin/alluxio` as the top level entry-point for user facing operations which provides a bunch of subcommands. Most users will use this entry point to interact with Alluxio service for tasks like reading/writing files, run some predefined tests, check configuration and etc.

```console
$ bin/alluxio
common subcommands:
  fs   		file system operations, including ls, rm, copyFromLocal and etc
  test 		various tests
  getConf	Look up a configuration key, or print all configuration
  version	print version
  ...
```
- Introduce a new entry point `sbin/alluxio-admin` for the admin facing operations . This is the top-level command to access operations like starting/stopping service, creating journal backup, and etc.

```console
$ sbin/alluxio-admin
common subcommands:
  format	format master or worker ...
  fs      	admin level file system operations, including mount, unmount and etc
  backup   	back journal
  doctor  	check health
  start    	start master or worker
  stop    	stop master or worker
  logLevel    	set or get log level of Alluxio servers
  copyDir  	copy the PATH to all master/worker nodes
  ...
```

**Describe alternatives you've considered**

**Urgency**
Medium

**Additional context**

**Comment by gpang** [comment]
I think this would make it easier to understand the operations as well as maintain the code. I'd also propose that most of the CLI functionality get moved into non-shell code, instead of all the shell scripting that exists today.

**Comment by gpang** [comment]
I think this would make it easier to understand the operations as well as maintain the code. I'd also propose that most of the CLI functionality get moved into non-shell code to take advantage of command-line libraries, instead of all the shell scripting that exists today.

**Comment by jja725** [comment]
Will reconsider during next redesign. close it for now, feel free to reopen it and contact us if this is a strong request.
