### ISSUE TITLE
getStatus of a specific file following a listStatus on the parent may trigger unnecessary syncMetadata

### ISSUE THREAD

**Issue by yuzhu** [Alluxio/alluxio#9705]
**Alluxio Version:**
2.1.0-SNAPSHOT

**Describe the bug**
with the default configuration, after `listStatus(/parent)`, 
`getStatus(/parent/file1)` should not trigger a call to`syncMetadata`. but currently it does because the `ufsSyncPathCache` caches the parent directory, but we check for exact match `/parent/file1` and we won't be able to find the exact match in our cache

**To Reproduce**
see above

**Expected behavior**
getStatus("/dir/file") should not trigger UFS sync

**Urgency**
medium

**Additional context**
related to #9545

**Comment by yuzhu** [comment]
@liuzx32 @gpang filed an issue to track the bug we discussed yesterday / today.

**Comment by yuzhu** [comment]
@apc999 FYI

**Comment by apc999** [comment]
will this also affect 2.0 branch or 1.8 branch too?

**Comment by yuzhu** [comment]
@apc999 yes, it affects both 2.0 and 1.8

**Comment by yuzhu** [comment]
This was addressed by #9773
