### ISSUE TITLE
Tune JVM parameters to improve GC behavior in Alluxio

### ISSUE THREAD

**Issue by bf8086** [Alluxio/alluxio#9716]
**Is your feature request related to a problem? Please describe.**
Alluxio servers can use a lot of JVM memories and GCs (especially full GCs) can be rather expensive and result in high latencies in handling request and communications with other services. We should look into setting various JVM properties to improve the GC behavior and reduce the latencies. 

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**

**Urgency**
Medium, we have recently switch to CMS GC which helps in this case, but further tuning can give us additional performance improvement.

**Additional context**
Related PR https://github.com/Alluxio/alluxio/pull/9706

**Comment by LuQQiu** [comment]
G1GC of Java 11 has been proved that it will improve the GC behavior and memory usage significantly in Alluxio.

**Comment by LuQQiu** [comment]
Please refer to https://github.com/Alluxio/alluxio/issues/15183

**Comment by LuQQiu** [comment]
This issue has been closed due to inactivity. Please re-open if this still requires investigation.
