### ISSUE TITLE
Mount by configuration

### ISSUE THREAD

**Issue by Taccart** [Alluxio/alluxio#9720]
**Is your feature request related to a problem? Please describe.**
Today, to mount fs, I need to use command line interface (alluxio fs mount...)
I would like to be able to have an automated mount at startup (at end of start up sequence).

**Describe the solution you'd like**
I would like to define mounts settings in configuration so that when my Alluxio starts, 
1/ it's fully pre-configured and no manual action is required for default mounts.
2/ each mount can be defined as mandatory (fail on error), meaning if ufs cannot be mounted the alluxio cluster is stopped.

Example of possibilty  the cli execution
./bin/alluxio fs mount --option aws.accessKeyId=... --option aws.secretKey=...\
  /mnt/s3 s3a://data-bucket/
could be defined in properties as 
alluxio.fs.mount.demos3bucket.option.aws.accessKeyId=....
alluxio.fs.mount.demos3bucket.option.aws.secretKey=....
alluxio.fs.mount.demos3bucket.path=/mnt/s3 
alluxio.fs.mount.demos3bucket.ufs=s3a://data-bucket/
alluxio.fs.mount.demos3bucket.readonly=false
alluxio.fs.mount.demos3bucket.failonerror=false

**Describe alternatives you've considered**
Having a post-script.sh that's called after starting Alluxio.
This is easy to implement,. Stopping alluxio if some mandatory mount is failing requires additional processing, and Alluxio instance will be up and running for a short amount of time.

**Urgency**
No urgency.

**Additional context**
None

**Comment by gpang** [comment]
@Taccart Thanks for this request! This looks something like a mount table, which is something that was considered in the past. A configuration file with the mount table is good for setting up a new cluster with a set of mounts.

However, after the Alluxio cluster is running, it is possible to update the mount table, with mount and unmount commands. After updates to the mount table, and the Alluxio cluster is restarted, what should the mount table look like? Could you describe the desired behavior when there is a "mount table" config file, and subsequent updates to the mount table?

**Comment by LuQQiu** [comment]
This issue has been closed due to inactivity. Please re-open if this still requires investigation.
