### ISSUE TITLE
Add doc section for tuning GC

### ISSUE THREAD

**Issue by bf8086** [Alluxio/alluxio#9730]
**Is your feature request related to a problem? Please describe.**
User can run into long full GCs that will cause various problem including fail over or connection loss. We should add a document section to explain how to tune GC parameters.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
medium, helps users to deal with some nasty situations.

**Additional context**

**Comment by rastogiasr** [comment]
Resolved in pre-prod checklist doc
