### ISSUE TITLE
Alluxio client should allow multiple alluxion configurations

### ISSUE THREAD

**Issue by Taccart** [Alluxio/alluxio#9745]
**Is your feature request related to a problem? Please describe.**
In Alluxio (2.0.0) the configuration of Alluxio client is passed thru configuration file or environment variables, which forbids setting different policies for different actions in an application.

**Describe the solution you'd like**
I would like to be able to set, on client side, a MUST_CACHE, CACHE_THRU or ASYNC_THRU... policy when writing in one Alluxio destination, and another when writing to another destination, 
Moreover, if one application must write data in two different Alluxio clusters (ex: store large history to cold storage and summary to hot storage), today, the client will use the same configuration for both clusters.

**Describe alternatives you've considered**
First, the application can write in direct connection to object store, but it breaks the "Alluxio expects that all modifications to under file systems occur through Alluxio" rule.
Second, I thought that having different policies in Alluxio using mount could do the job, but it does not as we can have recovery scenario where we want to skip caching data to avoid useless Alluxio cache usage (which could drive data eviction).

**Urgency**
No urgency as the scenario 

**Additional context**
Application needs to connect to two alluxio locations with different settings.

**Comment by ZacBlanco** [comment]
Hi @Taccart 

From my understanding, you want to set arbitrary properties on the same cluster (i.e. WriteType) depending on the path you write to. We do have something that may be able to support your need through [`pathConf`](https://docs.alluxio.io/os/user/stable/en/operation/Admin-CLI.html#pathconf). This command allows you to set arbitrary properties based on the destination your application writes to.

Additionally, If you're writing applications in Java using the Alluxio client directly there is a client constructor which supports using a configuration with arbitrary values. [See here](https://github.com/Alluxio/alluxio/blob/master/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java#L112-L118)

If neither of these solutions fit your needs, could you describe exactly why they don't fit? Or if they do, let us know of course :)

**Comment by calvinjia** [comment]
@Taccart Was PathConf able to address your use case?

**Comment by gpang** [comment]
Closing, since path configuration can be used for path-specific user configuration.
