### ISSUE TITLE
UfsJournal ignores unrecognized journal entries

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#9751]
**Alluxio Version:**
2.1.0-SNAPSHOT

**Describe the bug**
An unrecognized journal entry is simply ignored.

**To Reproduce**
- Write a journal entry newly added in v2.x
- Read journal from v2.y < v2.x
- Master starts up successfully

**Expected behavior**
Master should crash with `IllegalStateException` as a journal entry was unrecognized

**Urgency**
Medium, this an an early detection of journal compatibility 

**Additional context**
`EmbeddedJournal` calls `JournalAssociation` and will throw an `IllegalStateException` whereas `UfsJournal` does not

**Comment by gpang** [comment]
`UfsJournal` did/does not need the `JournalAssociation` method, since each master reads its own journal files, so all those entries are known to belong to the that specific master.

**Comment by gpang** [comment]
https://github.com/Alluxio/alluxio/blob/master/core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java#L178 ignores the return value, which should signify if the master recognizes the entry or not.
