### ISSUE TITLE
Inline exception messages inside ExceptionMessage.java and remove this class

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9788]
**Summary**

In Alluxio source code, there is `ExceptionMessage.java` which is only used to contain a lot of exception messages. This was initially aim to help Unit Tests to avoid hard-code exception strings in the tests but using these messages as the templates as a simplification. However,  later on this approach shows bigger issues: 

- when reusing the same exception message in different places in the source code, it is very difficult to locate the actual line in the src code when exception messages are seen without stack trace.
- as the source code is evolving, when some messages are no longer used, it is hard for us to tell from enum `ExceptionMessage` and remove this unused enum item, introducing dead source code. 

The proposed way is to simply inline all these messages into their callers. If the same message is used multiple times in different exceptions, we need to make the message different so we can tell the source of exception.

If one message is used multiple times in a unit tests, we can define the template inside the unit test file to simplify the code. 

**Urgency**
Low

**Comment by jja725** [comment]
It's ongoing. Will close it for now since the left overs are critical path.
