### ISSUE TITLE
Support appends

### ISSUE THREAD

**Issue by we7team** [Alluxio/alluxio#9790]
我看alluxio 2.0的master已经解决了数据一致性问题，我感觉可以把这个方案用到内容追加上，目前找了很多分布式存储方案，alluxio算是最好的解决方案了，但是针对日志、缓存文件等内容追加的场景还是无法完美的支持，如果能支持内容追加就更完美了。

I think the master of alluxio 2.0 has solved the problem of data consistency. I feel that this scheme can be used to append. At present, many distributed storage schemes have been found. alluxio is the best solution, but the scenario of appending to logs, cached files and so on can not be perfectly supported if it can be used. Supporting content append are even more perfect.

**Comment by lijufeng2016** [comment]
墙裂建议增加append功能，实时小文件问题才能得到解决，目前hdfs api支持append，所以现在没法用alluxio

**Comment by apc999** [comment]
this feature is at a large scope and requires a lot of change. it is not planned so far.
I will update the community when this becomes priority
