### ISSUE TITLE
Low performance of distributedLoad

### ISSUE THREAD

**Issue by liuhongtong** [Alluxio/alluxio#9791]
**Alluxio Version:**
2.0.0

**Describe the bug**
I have contrasted the performance of load and distributedLoad with 5TiB data. The size of file is 600MiB. The cluster has 30 nodes
```
\# date; alluxio fs load /ns1_lht_test_alluxio; date
Sun Aug 25 17:13:07 CST 2019
......
Aug 26, 2019 7:18:42 AM
```
It takes 14 hours and 5 minutes.

```
\# date; alluxio fs distributedLoad /ns1_lht_test_alluxio; date
Mon Aug 26 08:57:36 CST 2019
......
Mon Aug 26 18:07:15 CST 2019
```
It takes 9 hours and 10 minutes.

There is no enormous improvement for `distributedLoad`.
If this is a bug or any optimized configuration is available? 

**To Reproduce**
refer the section above

**Expected behavior**
distributedLoad can support high performance.

**Urgency**
N/A

**Comment by calvinjia** [comment]
@liuhongtong Are you loading multiple 600MB files for a total of 5TB data? Also, can you verify if all the nodes are being utilized (you can generally tell by all the workers having Alluxio space used).
