### ISSUE TITLE
Alluxio worker fails to start when using multiple storage media in single tier on EMR

### ISSUE THREAD

**Issue by thereisnospoon** [Alluxio/alluxio#9810]
**Alluxio Version:**
2.0

**Describe the bug**
When using `alluxio-emr.sh` script and trying to configure Alluxio to use both ramdisk and hard drive workers fail to start.

**To Reproduce**
I'm using the following properties to configure Alluxio to use both ramdisk and hard disk for storage:
```
alluxio.worker.memory.size=20GB
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk,/mnt
alluxio.worker.tieredstore.level0.dirs.quota=16GB,350GB
alluxio.worker.tieredstore.levels=1
```

The ramdisk is being mounted using: `/opt/alluxio/bin/alluxio-mount.sh SudoMount local`
After that when I try starting a worker using `sudo runuser -l alluxio -c "/opt/alluxio/bin/alluxio-start.sh -a worker"` it gives an error:
`ERROR: Ramdisk /mnt/ramdisk,/mnt is not mounted with mount option NoMount. Use alluxio-mount.sh to mount ramdisk.`

**Expected behavior**
It should be possible to configure Alluxio to use several storage types in a single tier on EMR.

**Urgency**
Normal

**Comment by madanadit** [comment]
@ns1123 can you please ask for more info required to debug this?

**Comment by thereisnospoon** [comment]
I think the problem might be here https://github.com/Alluxio/alluxio/blob/603c6fc29121e3e4f085bfdb4b6e510e259d85dc/bin/alluxio-start.sh#L80
The argument passed to `is_ram_folder_mounted` is comma-delimited string containing mount pahs with the first mount path being ramdisk mount path.
Extracting `ramdisk_mount_path=$(cut -d ',' -f1 <<<  ${1})` and using it in validation loop:
```
for fs in ${mounted_fs}; do
    if [[ "${ramdisk_mount_path}" == "${fs}" || "${1}" =~ ^"${fs}"\/.* ]]; then
      return 0
    fi
  done
```
might help.

**Comment by bf8086** [comment]
@ns1123 can you take a look?

**Comment by ZacBlanco** [comment]
@thereisnospoon this issue is resolved by https://github.com/Alluxio/alluxio/pull/10152


Based on the initial configuration provided, the only additional line of configuration you should add is 

```properties
alluxio.worker.tieredstore.level0.dirs.mediumtype=MEM,MEM
```

Using this configuration scripts should determine which paths are ramdisks and mount them appropriately. Starting the workers afterwards should also succeed. Please re-open this issue if you think there is still a problem. Thanks!
