### ISSUE TITLE
WebUI browse don't display files under table partition

### ISSUE THREAD

**Issue by soliverr** [Alluxio/alluxio#9833]
**Alluxio Version:** 2.0.0

**Describe the bug**
I have created partitioned table in Spark-SQL connected to Alluxio storage (`/db` directory in my environment).

Her is list of files from Alluxio CLI (`test_table` has two partitioned columns):

```
$ALLUXIO_HOME/bin/alluxio fs ls --sort lastModificationTime /db/test_table/VERSION_ID=3958/
drwxr-xr-x  hadoop         hadoop                       1   NOT_PERSISTED 09-03-2019 18:32:10:687  DIR /db/test_table/VERSION_ID=3958/SCN=1
drwxr-xr-x  hadoop         hadoop                       1   NOT_PERSISTED 09-04-2019 12:50:40:439  DIR /db/test_table/VERSION_ID=3958/SCN=2
```

But in WebUI `Browse` nothing displayed when I click _/db/test_table/VERSION_ID=3958_ link.

**To Reproduce**
Create partitioned table in Spark-SQL.
Take a look into WebUI `Browse`.

**Expected behavior**
In Alluxio 1.8.1 WebUi `Browse` all contents was displayed correctly.

**Comment by ZacBlanco** [comment]
@tieujason330 Is this something that was fixed in 2.0.1? It sounds like the characters in the URL might not have been encoded properly.

**Comment by tieujason330** [comment]
@ZacBlanco Yeah it's in 2.0.1. It's a very similar issue to #9465 that was fixed a couple months back.

**Comment by ZacBlanco** [comment]
@soliverr Can you upgrade to 2.0.1 and try? We've fixed a number of issues in the latest patch release.

**Comment by soliverr** [comment]
Thank you. I've missed this update.

Now it's working well in 2.0.1.
