### ISSUE TITLE
File content modification is supported through AlluxioFuse

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#9841]
**Summary**
With Alluxio branch-2.0, the operation sequence as below can modify file content in Alluxio and local UFS:
1) ./bin/alluxio-start.sh local; 
2) ./bin/alluxio fs copyFromLocal LICENSE /LICENSE
2) ./integration/fuse/bin/alluxio-fuse mount ./cx/ / 
3) vim ./cx/LICENSE and modify the content
4) re-vim the ./cx/LICENSE and make sure content changed
5) ./bin/alluxio fs cat /LICENSE      content changed!
cat ./underFSStorage/LICENSE     content changed!
All properties use default value.

1. What're the dependencies of this workflow
It's depending on mac and certain mac version?
will it work with other UFS
2. Why does this happen? Is the local mac system do cache_file_with_new_content, delete_old_file, write_new_file operations combination?

**Urgency**
No urgent, but it will be really helpful to understand why this behavior happens.

**Comment by LuQQiu** [comment]
Alluxio does not support append or modify file content. 
Mac system (> 10.13) will translate user file modification behavior (vi/vim and mofify) to the following operations.
suppose we have a file `/a` in Alluxio, it's mounted to local filesystem, and we use vi/vim to modify it in the fuse mount point.
The modification will translate to the following operations:
(1) open file `/a` for reading
(2) create file (`/.a.swp` and `/.a.swpx`) to save the modified content
(3) delete `/.a.swp`, `/.a.swpx` and create a final `/.a.swp`
(4) rename `/a` to `/a~`
(5) create a new `/a` with content from `/.a.swp`
(6) delete `/.a.swp`

So in order to modify the file, mac system do many create file, delete file operation combination. For a large file, we still not encourge modify the file, but for small files, alluxio-fuse do support this operation in MacOS

**Comment by apc999** [comment]
@LuQQiu  shall we close this ticket then?
