### ISSUE TITLE
More traces for copycat

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#9849]
**Is your feature request related to a problem? Please describe.**
Copycat library does not have enough traces for debugging purposes.

**Describe the solution you'd like**
Some core operations/decisions within copycat should be traced.
   - Snapshot installation
   - Storage cleaning actions
   - Register requests
   - Heartbeat failures
   - Flush failures

**Comment by ns1123** [comment]
@ggezer can we close this?

**Comment by ggezer** [comment]
@ns1123 Let's keep it open for a while.
