### ISSUE TITLE
Support Java 11

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9856]
**Is your feature request related to a problem? Please describe.**
Currently, Alluxio only supports Java 8

**Describe the solution you'd like**
Java 11 is the next LTS release of Java.  

> The end of public updates for Java 8 is scheduled for January of 2019 for commercial use. For non-commercial use, the same is scheduled at an unspecified date in December of 2020.

**Describe alternatives you've considered**
Current Alluxio 2.1-SNAPSHOT does not compile with JDK 11.
We should fix the src code so it works with either JDK 8 and JDK 11

**Urgency**
Medium

**Additional context**

**Comment by ZacBlanco** [comment]
@apc999 I've looked into this issue previously, and while there is less change specifically with our code that we need, the main issue I've faced is dealing with dependencies.

Specifically, the toughest issue is that we use lots of hadoop libraries. The `hadoop-common` library depends on a specific system jar - `tools.jar` - which has been around in the JDK for a while, but has since been removed in Java 11. There is no replacement for this dependency. Many of the features of it have been replaced. To continue supporting hadoop 2, I don't believe we can upgrade to Java 11.

**Comment by apc999** [comment]
two ways to solve it:
(1) when JDK 11 is enabled, by default bump hadoop.version to 3.0 or higher
(2) split hadoop dependency into separate submodules, covering hadoop1 hadoop2 and hadoop3. When JDK 11 is used, skipping compiling module hadoop1 or hadoop2

**Comment by ZacBlanco** [comment]
An additional comment - even hadoop 3 doesn't support Java 11. I suspect the current Hadoop 3 libraries won't work with Java 11 either.

https://issues.apache.org/jira/browse/HADOOP-15338

So I imagine we could create a maven profile which skips compiling all hadoop-related modules (client+ufs)

**Comment by electrum** [comment]
@ZacBlanco Presto uses the Hadoop libraries without any problems on Java 11. The Hadoop issue you linked to seems to be about running all of Hadoop on Java 11, not just the client libraries (which already work).

**Comment by electrum** [comment]
Presto excludes `jdk.tools` for `hadoop-common`: https://github.com/prestosql/presto-hadoop-apache/blob/master/pom.xml#L166-L169

**Comment by ZacBlanco** [comment]
@electrum Thanks for the clarification. I'll add the exclusion for java 11 and see how that affects our build.

**Comment by ChethanUK** [comment]
Latest Presto's default Java version is 11:  `Future versions of Presto will require Java 11 after March 2020` and I want to use Java 11 only thought there is a temporary option...

- When will 2.3 get released?
- Till 2.3 is available, is there any way to use Alluxio and Presto together?

**Comment by apc999** [comment]
> Latest Presto's default Java version is 11: `Future versions of Presto will require Java 11 after March 2020` and I want to use Java 11 only thought there is a temporary option...
> 
> * When will 2.3 get released?
> * Till 2.3 is available, is there any way to use Alluxio and Presto together?

As discussed offline, a "hacky" workaround  is to use Alluxio client in Presto w/ Java 11 -- this should be fine; To start Alluxio servers it requires Java 8. You can set `$JAVA` or `$JAVA_HOME` in `conf/alluxio-env.sh` pointing to a non system default JDK

**Comment by ZacBlanco** [comment]
While you can try using the Alluxio java client on presto with Java 11, it is not guaranteed to work; only start. Once you begin processing data none of the code paths are guaranteed to be compatible. You may try, but you should expect the likelihood of runtime errors.

**Comment by apc999** [comment]
One more related discussion on slack https://alluxio-community.slack.com/archives/CEXGGUBDK/p1588574275337900 to check out

**Comment by jefflester** [comment]
I just read [your documentation](https://docs.alluxio.io/os/user/stable/en/operation/Configuration.html#java-11-configuration) for v2.4 and it has instructions for enabling Java 11. Is this fully supported as of the v2.4 release?

**Comment by apc999** [comment]
@jefflester  Java 11 is supported since Alluxio v2.4.0, seeing its [release notes](https://www.alluxio.io/download/releases/alluxio-2-4-0-release/).

I am closing this issue as it has been resolved with latest v2.4.0 release

**Comment by findepi** [comment]
@apc999 thanks for the update
Are you planning on updating alluxio-client in Presto?
It's currently at 2.3.0:
https://github.com/prestosql/presto/blob/c088019514db5a3a99270938d383bbd4eaf5487c/pom.xml#L1107-L1109

**Comment by apc999** [comment]
@findepi I was about to create a PR to bump the version and found prestosql/presto#5730 is already created
