### ISSUE TITLE
Backup command show wrong console message and docs

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#9863]
**Alluxio Version:**
2.0.0 and possible master also have the issue

**Describe the bug**
When the root mount is hdfs
./bin/alluxio fsadmin backup
backup to the leader master local directory but show message that `Successfully backed up journal to hdfs://......`

Alluxio docs about how to run backup command should also be updated

**Urgency**
Not urgent, but may seen confusing for users

**Additional context**
This bug happens because we change the journal backup default in https://github.com/Alluxio/alluxio/pull/9283 and forget to change the console message and docs.

**Comment by bf8086** [comment]
@LuQQiu Is this issue still relevant now that #9867 is closed?

**Comment by LuQQiu** [comment]
Fixed via #9867
