### ISSUE TITLE
Alluxio fails to sync updated file on S3 when working with Presto

### ISSUE THREAD

**Issue by thereisnospoon** [Alluxio/alluxio#9865]
**Alluxio Version:**
2.0.0

**Describe the bug**
There is a file on S3 which gets updated daily. This file is queried by Presto. After `free`ing the file from Alluxio Presto query on this file fails with `Not valid Parquet file: alluxio:/Metadata/parquet/app/app.snappy.parquet expected magic number: [80, 65, 82, 49] got: [-45, -111, -10, 121]`
After trying to `free` the file for the second time I'm getting: `java.util.concurrent.TimeoutException: Timed out waiting for file to be freed. Another user may be loading it. options: WaitForOptions{interval=1000, timeout=10000}`

**To Reproduce**
1. Create a file on S3.
2. Ensure you have a Presto cluster with Alluxio installed having S3 as under storage.
3. Query the file from Presto for the first time. Make sure it's cached in Alluxio.
4. Update the file.
5. Do `alluxio fs ls -f <path-to-file>`
6. Do `alluxio fs free <path-to-file>`
7. Query the file from Presto for the second time. See the error about invalid Parquet file.
8. Try to `alluxio fs free <path-to-file>` for the second time. See `java.util.concurrent.TimeoutException: Timed out waiting for file to be freed. Another user may be loading it. options: WaitForOptions{interval=1000, timeout=10000}`

**Expected behavior**
Ideally, Alluxio should automatically drop files from the cache in case the metadata for the files fetched in `alluxio fs ls -f` for the files are different from the metadata for the files in Alluxio metastore (e.g. if a file size has changed in under storage then after `ls` Alluxio should drop the file from cache).
In case automatic cache invalidation is hard to implement then at least `free` operation shouldn't cause the errors described above.

**Urgency**
This problem prevents us from using Alluxio in production.

**Additional context**

**Comment by thereisnospoon** [comment]
Using `alluxio fs ls -Dalluxio.user.file.metadata.sync.interval=0 <path>` has helped. Looks like it causes removal of file from Alluxio cache in case the file metadata has changed.
Thanks

**Comment by madanadit** [comment]
Thanks for the info @thereisnospoon! I believe your workflow would be as follows?
1. files created in s3 directly (not via alluxio) on a daily basis. this includes new file names and replacing the content of older files? note for the former, `ls -f` would be sufficient. for the latter `ls -Dalluxio.user.file.metadata.sync.interval=0` is needed to refresh metadata in case files were created with the same name
2. `ls -Dalluxio.user.file.metadata.sync.interval=0 -R` to refresh alluxio metadata
3. hive `msck repair` to discover any new partitions from alluxio?
4. run queries. also, can you confirm if queries are not run b/w steps 1 and 2? you might see issues for stale files in alluxio (incorrect metadata) before you re-sync in step2
