### ISSUE TITLE
Improve the error message when master hostname is not set

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9899]
**Summary**
When the following message is given, it looks like ZK or HA is required, which is not true
```
Cannot run Alluxio fs shell; Unable to determine master address. Please modify alluxio-site.properties to either set alluxio.master.hostname, configure zookeeper with alluxio.zookeeper.enabled=true and alluxio.zookeeper.address=[comma-separated zookeeper master addresses], or utilize internal HA by setting alluxio.master.embedded.journal.addresses=[comma-separated alluxio master addresses]
```

**Urgency**
Low

**Comment by ZacBlanco** [comment]
@apc999 why do you think it looks like HA is required?

**Comment by apc999** [comment]
my way to read this: 

either "set alluxio.master.hostname, configure zookeeper with alluxio.zookeeper.enabled=true and alluxio.zookeeper.address=[comma-separated zookeeper master addresses]", 

or "utilize internal HA by setting alluxio.master.embedded.journal.addresses=[comma-separated alluxio master addresses]"

**Comment by yangjf2019** [comment]
Hi, @apc999 Does it resolved? Thank you!

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
