### ISSUE TITLE
Consolidate a general framework for multi-threaded CLIs

### ISSUE THREAD

**Issue by liuhongtong** [Alluxio/alluxio#9905]
**Is your feature request related to a problem? Please describe.**
alluxio command provides distributedCp, distributedLoad and distributedMv options. Actually that is a serial process, so the performance may be not acceptable.

**Describe the solution you'd like**
Design a general parallelism framework for multi-threaded CLIs.

**Describe alternatives you've considered**
N/A

**Urgency**
N/A

**Additional context**
N/A

**Comment by jja725** [comment]
It's on the plan and we already have new load v2.
