### ISSUE TITLE
Consolidate generate-release-tarballs.go and generate-tarball.go

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#9907]
**Summary**

`generate-release-tarballs.go` is no more relevant after 1.8. We should consolidate the subcommand of `single` mode and `release` mode and only based on `generate-tarball.go`

**Urgency**
Low

**Comment by LuQQiu** [comment]
Already consolidated, this issue is not valid anymore. Please reopen if find still valid and useful
