### ISSUE TITLE
Reactivate MasterFaultToleranceIntegrationTest

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#9908]
**Summary**
We are missing out on an important validation without this test.

**Comment by ggezer** [comment]
Killing a leader closes fsclients created from it. So next call fails. Client pooling should be done at application/test layer, not at master-process.

**Comment by LuQQiu** [comment]
11:13:04.556 [INFO] Running alluxio.server.ft.FileSystemMasterFaultToleranceIntegrationTest
11:13:25.070 [INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.492 s - in alluxio.server.ft.FileSystemMasterFaultToleranceIntegrationTest
The test is running in github actions
