### ISSUE TITLE
Is it possible for Alluxio fuse to support PageCache

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9913]
**Is your feature request related to a problem? Please describe.**

The current alluxio fuse only supports direct_io. Do you think if the user can have flexibility to enable page cache when it's read only scenario.

https://github.com/Alluxio/alluxio/blob/068f7bf46dc62733b33c3f3e6cabcd8909e76e35/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java#L69

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by apc999** [comment]
the reason to use `direct_io` is alluxio data will be already in memory (if in MEM tier), and avoid spending double resource to serve the same data

**Comment by cheyang** [comment]
There are two reasons I want to have chance to enable page cache:
1.If the alluxio data is in the remote worker, and no copy in local
2.Reduce the interaction with alluxio master 

Does this make sense to you?

**Comment by bf8086** [comment]
@apc999 any further thoughts?

**Comment by apc999** [comment]
resolved by https://github.com/Alluxio/alluxio/pull/12606 which supports kernel_cache
