### ISSUE TITLE
Legacy GCS under store requires credentials to be specified explicitly

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#9917]
**Is your feature request related to a problem? Please describe.**
When running on GCE or dataproc, the legacy GCS under store is not able to read the credentials from the credentials store and needs the properties .`fs.gcs.accessKeyId` and `fs.gcs.secretAccessKey` to be set explicitly.

**Describe the solution you'd like**
The under store should not require credentials to be set. The connector here https://github.com/Alluxio/alluxio-extensions/tree/master/underfs/gsg should be ported to the Alluxio repo.

**Describe alternatives you've considered**
N/A

**Urgency**
Medium

**Additional context**
N/A

**Comment by calvinjia** [comment]
Fixed by #12842
