### ISSUE TITLE
Avoid resolving path during listStatus

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#9938]
**Is your feature request related to a problem? Please describe.**
`FileInfo` returned as part of listStatus call contains some fields that are only leveraged internally and calculation of which requires resolving the path against mount table. Returning these fields could be made optional by only explicitly asking for them when sending `ListStatusRequest`.

**Additional context**
fileInfo.ufsPath
fileInfo.mountId

**Comment by bf8086** [comment]
@ggezer Do you know whether this is still an issue?

**Comment by ggezer** [comment]
There is another issue opened to track this problem.
