### ISSUE TITLE
Alluxio mount command hangs forever if underlying mount directory is deleted

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#9946]
**Alluxio Version:**
Alluxio 2.0.0

**Describe the bug**
With multiple nested HDFS mount points, if one of the mounted directories is deleted in HDFS out-of-band, then the alluxio fs mount command hangs indefinitely

**To Reproduce**
Mount 2+ HDFS directories, then delete the underlying directory in HDFS for one of the nested mounts. `./bin/alluxio fs mount` should hang.

**Expected behavior**
The mount command should still return the mount-table

**Urgency**
Urgent. This prevents users from knowing their mount structure and from identifying which directory is deleted which in turn prevents them from fixing the structure.

**Comment by bf8086** [comment]
@ns1123 is this fixed in 2.1.x?

**Comment by ns1123** [comment]
Not sure. Need to double check.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
