### ISSUE TITLE
Missing a data persistence state graph

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#9960]
**Page**
Include the link to the page you are reporting a defect

**Summary**
There's no public document page illustrating the persistence state shift flow. Having one such graph will help users understand the persistence states. This also helps users trouble-shoot scenarios like LOST files in ASYNCH_THROUGH.

**Comment by ns1123** [comment]
+1 for a developer document detailing valid inode states and state transitions. I've been hit with weird messages such as IllegalStateException cannot transition from TO_BE_PERSISTED to NOT_PERSISTED etc.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
