### ISSUE TITLE
Alluxio does not initFromBackup correctly when specifying local path

### ISSUE THREAD

**Issue by ns1123** [Alluxio/alluxio#9969]
**Alluxio Version:**
master branch

**Describe the bug**
Alluxio's restore from backup using the `alluxio-start.sh -i <Backup-URI>` does not work as intended. The master takes any user-specified URI and strips it of scheme/authority before checking the root UFS for the backup. This prevents users from specifying a local path using 'file:///'.

**To Reproduce**
Try to restore from a backup file in a non-root UFS URI

**Expected behavior**
Restoring from backup should allow either Root UFS URI or Local URI based on user specified scheme.

**Urgency**
HIGH

**Additional Context**
This used to work before the changes in PR #9808. Unit tests should be added here to prevent breaking changes like this in the future.

**Comment by ZacBlanco** [comment]
[Offending diff](https://github.com/Alluxio/alluxio/commit/0455c219fcbf716c83025f59276c5de4bd002b7e#diff-1f06075f91e4f9f549c218c7c797a590L171-R177)
